### ISSUE TITLE
Can't import code/ modules from other notebooks.

### ISSUE THREAD

**Issue by aiqc** [jupyterlab/jupyterlab#10124]
_Making a few extra issues that tested well in the survey for the new team members that Darian mentioned._

### Problem
Many notebook authors are not yet programmers. They are not comfortable writing `.py` scripts and `import`'ing them into their notebooks. They just keep writing more code in their notebook, and the result is outrageously long notebooks. These long notebooks severely degrade the notebook UI performance, and they lead to badly written code. Honestly, apart from publishing pypi/conda packages, if I didn't have to write `.py` scripts, I wouldn't.

---

### Proposed Solution
Jupyter magic command for `hook`'ing other notebooks. Would it strip out the json/markdown/non-code cells to treat it like a `.py` file?

When you have hooked another notebook, can you access its server-side memory?

---

### Additional context
![image](https://user-images.githubusercontent.com/74990642/115451088-bf5e9c80-a1ea-11eb-92a7-85248cc114fb.png)

**Comment by agoose77** [comment]
I've [played around with this](https://github.com/agoose77/literary) to implement a form of literate programming.

`literary` can be activated with `%run -m literary.notebook`, which does two things:
- Enable the Python import hook to permit importing notebooks
- Set `__package__` in the current module to permit relative imports

Currently, notebooks do not export any code cells by default (requiring an opt-in by adding a cell-tag named `export`).  Seeing that it might be useful elsewhere, I think I will modify the library to use a preprocessor to do this, so that it can be disabled if required.

I'm closing this issue as answered, because this is not a feature that JupyterLab could support; JupyterLab is the frontend for Jupyter notebooks, whereas you need something that can work at the kernel-level (e.g. as a Python module (`literary`), or a custom kernel/hook). Feel free to [raise an issue](https://github.com/agoose77/literary/issues) if you have any questions :)
