### ISSUE TITLE
Add a list of connected users in RTC and clicking on takes you to that cursor

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/jupyterlab#10202]
### Problem

* I would like it if there was a list of users (ala Google Docs) that displayed all connected users on the RTC PR and clicking on them would take you to that cursor.

![gdoc](https://user-images.githubusercontent.com/3627835/117351692-9d644b80-ae73-11eb-9b2c-e74e69585f83.gif)

### Additional context

This is in the context of https://github.com/jupyterlab/jupyterlab/pull/10118

@cooperrc in the latest [RTC meeting](https://hackmd.io/UbnBH58hS8itoWgfiWT77A) suggested that we could use images of different [Jupiter Moons](https://en.wikipedia.org/wiki/Moons_of_Jupiter) as the avatars for the users that connect, and we could also use the names of them (I guess) much in the vein of random animals, the way also GDocs does it.

There was overwhelming agreement on this so props to Ryan 💯 

![image](https://user-images.githubusercontent.com/3627835/117351553-7dcd2300-ae73-11eb-829c-bce258a5d826.png)

So... 
- Anonymous Europa
- Anonymous Io
- Anonymous Ganymede 

Pinging @dmonad. @jess-x was in the last RTC meeting and was very keen on working and helping on this :) !

**Comment by dmonad** [comment]
Thank you for raising the ticket!

I think the best way to handle this is as a Jupyterlab plugin. The plugin could render a list of users in some part of the UI. It is quite easy to render a list of users with Yjs. There is a tutorial section specifically about this: https://docs.yjs.dev/getting-started/adding-awareness

It would be awesome if someone else with more Jupyter experience could implement the Jupyter plugin (more experience than me, so that's a very low bar). I'd be happy to help out on the Yjs-related stuff.

**Comment by goanpeca** [comment]
@jess-x has good experience with that, so I think she will be working on that, and maybe ping you for pointers with YJs stuff :-p

**Comment by dmonad** [comment]
Oh, that's great! That would be the first RTC extensions :)

Please DO feel free to ping me. My mail address is in my profile and I'm also available on Gitter https://gitter.im/dmonad

**Comment by jess-x** [comment]
> @jess-x has good experience with that, so I think she will be working on that

Thank you @goanpeca for making the issue and also the creative design 🌔 
I would love to work on the extension!

> 

> There is a tutorial section specifically about this: https://docs.yjs.dev/getting-started/adding-awareness

> Please DO feel free to ping me.

@dmonad Thanks for the resources!! I would definitely let you know as things go  

> That would be the first RTC extensions :)

would be my honor to help make this :)

**Comment by goanpeca** [comment]
Some ideas from some work @echarles started

<img width="1440" alt="rtc-list" src="https://user-images.githubusercontent.com/3627835/117732939-57322380-b1b6-11eb-962d-d3b7bf27b5ef.png">

**Comment by jess-x** [comment]
To pick the color schemes, [color brewer](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3) & [material color tool](https://material.io/resources/color/#!/?view.left=0&view.right=0) were suggested in the dev meeting. Putting them here for later reference :)

**Comment by dmonad** [comment]
@jess-x Feel free to reuse the colors I use for my projects: https://github.com/yjs/website/blob/master/src/usercolor.js#L3-L12 These reusable colors are [Public Domain / CC0](https://creativecommons.org/share-your-work/public-domain/cc0).

**Comment by williamstein** [comment]
We just discussed usernames during the JupyterLab dev call, and Isabela encouraged me to add a note here about what I need for cocalc.   I would like a command line option to the jupyterlab server that makes it so when a user connects to jupyterlab, the URL specifies a username and color, and that will be used.   E.g.,
```
https://hub.gke2.mybinder.org/user/jtpio-6ce263817-f1da4af742b7f72-vmoi7f4j/lab/tree/agenda.md?username="William Stein"&color="red"
```

CoCalc handles all of its own security/auth, so this would be sufficient for my needs, and probably a lot easier to implement than many of the more powerful things you are implementing.   I suspect many other similar end users of JupyterLab may have similar needs.

**Comment by jtpio** [comment]
cc @davidbrochart who has been making progress reusing some of @echarles's work in https://github.com/davidbrochart/jupyterlab-auth

If you would like to comment here and share ideas, screencast or screenshots that would be great :+1:

**Comment by davidbrochart** [comment]
Here is a screencast of the [JupyterLab extension](https://github.com/davidbrochart/jupyterlab-auth):

https://user-images.githubusercontent.com/4711805/124929855-1cefd180-e001-11eb-8a39-f5dfecbeec2d.mp4

Currently there is a tab on the left with the connected users, but clicking on them takes you to their GitHub account, which is what they use to connect. I have added a new menu with the currently logged in user (which only allows to log out for now).

It would be great to have both the list of users and the current user on the right ala Google Docs, and clicking on them would take you to their cursor. I think it still makes sense to have the tab on the left, because it's kind of separate: it has to do with users registered in the back-end (with their permissions, etc.), so they can e.g. be off-line and you wouldn't see them on the right.

**Comment by fcollonval** [comment]
This is implemented in https://github.com/jupyterlab/jupyter_collaboration
