### ISSUE TITLE
Docs: Update docs on real time collaboration

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/jupyterlab#10227]
From https://github.com/jupyterlab/jupyterlab/pull/10118

---

I think we should document the collaborative "shared model" approach in https://jupyterlab.readthedocs.io/en/stable/. The patterns described in the jupyterlab/rtc repository seem to be out-of-date now.

1. The `shared-models` package contains a `SharedNotebook` and a `SharedFile` which are the abstract interfaces to work against if you want to manipulate a notebook or a file. In a MVVM pattern, the `shared-models` are the model. The view is implemented by the other packages (`codemirror`, `cells`, `notebook`, ..) which render the shared model. The model enables you to manipulate and observe data using a well-defined interface - completely independent from the networking technology that is used to synchronize the model. 
2. A useful resource: `jlpm docs` generates documentation for the collaborative interfaces exposed by the `shared-models` package.
2. I imagine that there is already a lot of documentation on how to manipulate notebooks using `notebook/model` or `cell/model` or `codeeditor/model`. Now everything is bundled into a single interface. We should work towards replacing the existing documentation to describe the new `SharedNotebook` interface instead. Eventually, we should deprecate the old model implementations in favor of a single consistent & collaborative interface.
2. We should document how to add more shared-models to Jupyter. It is fairly easy to define new models (even outside of the `shared-models` package). @hbcarlos is already working on a shared model for Draw.io. The "shared model" is implemented using Yjs https://docs.yjs.dev/ and exposes a Yjs Document that the provider syncs to other devices. 
3. The new `docprovider` package is one implementation that enables peers to synchronize shared-models / Yjs documents over a websocket-python server. It is possible to implement different providers (e.g. based on any existing Yjs provider) or synchronize the shared models to any service provider that can synchronize Yjs documents.

Regarding 1.: The pattern that we established is to create an abstract interface around the "thing" that we want to make collaborative. Internally, we use Yjs to implement that model. Then we use Yjs' providers to synchronize the underlying Yjs document to other peers. These are patterns that are already established in the general Yjs ecosystem. So it might make sense to link to https://docs.yjs.dev/ at some point.

This is just a short description of the inner workings and the patterns that we want to establish. Please let me know if you want to discuss anything in more detail.

Furthermore, we should probably clarify in `jupyterlab/rtc` that we arrived at a single solution. Further work should be coordinated directly on the `jupyterlab/jupyterlab` repository.

**Comment by hbcarlos** [comment]
In addition to those points, I would add examples to [jupyterlab/extensions-examples](https://github.com/jupyterlab/extension-examples).

It's always useful seeing examples.

**Comment by bollwyvl** [comment]
Selfishly, i'd like some insight into how one might use a different backend, ideally requiring only a labextension that doesn't require monkeypatching, but I'm not above getting dirty.

Concretely, in https://github.com/yuvipanda/jupyter-videochat/issues/28 I'd like to see about implementing a `JitsiConnector` that (ab)uses the  [sendendpointtextmessage](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#sendendpointtextmessage) -> [incomingmessage](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#incomingmessage) pipe. The long con is making this contraption work in [jupyterlite](https://github.com/jtpio/jupyterlite)...

**Comment by dmonad** [comment]
Hi @bollwyvl,

Interesting use-case. It should be as easy as replacing the `docprovider` package with another implementation, which I was told would be possible. 

Currently, `docprovider` requires a locking mechanism to prevent data loss when two users are writing a document to the server at the same time. But eventually, we want to switch to a model where the client doesn't need to send an HTTP requests to save the file. It should just be saved in a regular interval by the rtc-server.

You can absolutely use Jitsi as a collaborative backend. You can even that peer-to-peer over WebRTC by porting https://github.com/yjs/y-webrtc/ to Jitsi. You just need to implement some kind of locking approach to prevent concurrent writes to the server.

There are a number of Yjs connectors that are ready-to-use: https://docs.yjs.dev/ecosystem/connection-provider
If you want to implement your own network provider, you can do that with Yjs' updates API: https://github.com/yjs/y-webrtc/

**Comment by bollwyvl** [comment]
Yeah, i guess that's the point of docs requests, specific to _this_ integration, which doesn't _quite_ quack like the ones on the mainline implementations.

> replacing the docprovider package with another implementation, which I was told would be possible.

Looks like it's referenced concretely when setting a private member [within the huge constructor of Context](https://github.com/jupyterlab/jupyterlab/blob/16cba948f03a07578cb249c368ead7589b9cae6f/packages/docregistry/src/context.ts#L94-L96) , which is also concretely used everywhere else. Luckily, `private` _isn't_. So to get a piece of it, I could intercept it at [Context.prototype.initialize](https://github.com/jupyterlab/jupyterlab/blob/16cba948f03a07578cb249c368ead7589b9cae6f/packages/docregistry/src/context.ts#L254), which is already an awaitable, with a nasty hack like this:

```ts
Context.prototype.initialize = function(isNew: boolean): Promise<void> {
  if(shouldReplaceProvider(this)){
    this._provider.destroy();
    this._provider = providerProvider.createProvider(...);
    await this._provider().initialize();
  }
  await super.initialize(isNew);
}
``` 

From a UI perspective, I guess i'd imagine this appear next to `Open With...` in the file context menu, and be like `Share with <meeting> as...`.

As for the locks: welp, the documented Jitsi IFrame API for arbitrary data is pretty austere... even though there _is_ WebRTC and strophejs XMPP and who knows what else under the hood, I'm figuring sticking to the dumb text pipe is the least likely to break on me/users. The "moderator" (there's always exactly one, based on the order in which we joined) can be the gatekeeper for locks, and I guess I can do some base64 and bitbanging... is there a kaitastruct or soemthing for the wire protocol?

Anyhow, standing back from my monkeyshines: We're probably going to need a nice [API on DocManager](https://github.com/jupyterlab/jupyterlab/blob/master/packages/docmanager/src/manager.ts#L477) for this kind of thing, and it has to be easy to turn on and off, support multiple simultaneous implementations, etc. etc. Will have to do some thinking on what that looks like.

**Comment by jtpio** [comment]
> Selfishly, i'd like some insight into how one might use a different backend, ideally requiring only a labextension that doesn't require monkeypatching, but I'm not above getting dirty.

https://github.com/jupyterlab/jupyterlab/pull/10252 and https://github.com/jupyterlab/jupyterlab/issues/10256 should normally help make that part swappable via the plugin system.

**Comment by bollwyvl** [comment]
Thanks for the effort, sterling work.

I am concerned about another winner-takes-all "extension" point. I don't
see too much of a stretch to the use case of opening a document shared with
my colleagues over a jitsi pipe while I'm also "second screen" sharing
another document to a tablet on 8888.

The providers will rapidly become intertwined with identity, and may be
very customized per provider... And not every document should have sharing
enabled. So it seems like "Share with..." would need to become the norm vs
opening the file and broadcasting MY_PRIVATE_NOTES.md to everyone on my
current jitsi meeting just because I have that plugin installed.

Bridging two collaborative sessions sounds kinda ridiculous... But
resharing did work with e.g jupyterlab-dat, though the only use case I
could come up with that would be in a live, multi-party review, e.g.
student, TA, and Prof where there's "hidden" knowledge that only some
parties could have.

**Comment by dmonad** [comment]
I don't think that Jitsi will ever become a communication channel for JupyterLab. But it is certainly possible that a conferencing tool like https://room.sh can integrate Jupyter Notebooks to enable the participants to collaborate on the same data. Another use-case would be VSCode, which recently added support for Jupyter Notebooks. They can write a docprovider extension that integrates into their existing collaborative-editing solution.

To be clear, there is no intention of adding WebRTC support to JupyterLab. Personally, I'm just really excited that this generic shared-model approach allows other integrations as well (which might be well out of the scope of the Jupyter project).

In JupyterLab and JupyterHub, the most sensible solution is a WebSocket server that synchronizes the content between all the peers that have access to JupyterLab/JupyterHub. The server is in full control of who can access/view/write the Jupyter Notebooks. We haven't discussed whether we will have a separate docprovider package for JupyterHub. It is certainly possible that we will have a "winner-takes-all extension" that will be used across all Jupyter projects. We just want to leave the option open to add an alternative backend solution.

**Comment by bollwyvl** [comment]
> I don't think that Jitsi will ever become a communication channel for JupyterLab.

Welp, for my money, it's [self-hostable](https://github.com/krakazyabra/jitsi-helm), uses standards up the wazoo... and already has an [implementation](https://github.com/yuvipanda/jupyter-videochat) we've used for a couple events. Free-as-in-beer-speech tastes mighty good, and they haven't broken their API on me yet. 

> WebSocket server that synchronizes the content between all the peers that have access to JupyterHub

Indeed, I see a happy place of Zulip, Jitsi, radical, GitLab (as managed hub services) all co-existing inside a per-user tailorable JupyterLab UI, and collaborative editing, log/test/job/sim watching, etc. might occur wherever it needs to. If this requires a new bespoke service, that's fine. But for demo purposes, if i can show 5+-2 people dropping into a Jitsi call without sharing tokens, and casually editing a notebook  backed by an existing, free, well-known service, that's a huge win. 

> allows other integrations as well (which might be well out of the scope of the Jupyter project).

Right: Jupyter's users win when our APIs are more open, better documented, and demonstrate-able with off-the-shelf stuff vs a heavyweight integrated "platform" solutions.

> VSCode ... their existing collaborative-editing solution.

... where your data goes... somewhere... and certainly can't be self-hosted, much less used with another client. It would probably be a terms of service violation to adapt something to work with their protocols outside of VSCode, though of course they _love_ when extension authors use those APIs, so they that your open source can't be used in other clients...

> a "winner-takes-all extension" that will be used across all Jupyter projects. We just want to leave the option open to add an alternative backend solution.

We may be violently agreeing, but my issue is not that one can choose _an_ alternative (removing the "official" jupyter one), but rather, _as many collaboration alternatives as the user chooses to have at one time_. In a number of other places throughout the stack, the extend-by-replacement (rather than extend-by-composition) pattern makes it hard to do interesting and useful things, leading to solutions like [hybridcontents](https://github.com/viaduct-ai/hybridcontents) (with which there is nothing wrong, but seems like it could be supported better natively).

**Comment by dmonad** [comment]
So we agree. We want to give others (e.g. the team behind VSCode) the option to integrate Jupyter Notebook into their existing backend. They might have other auth and permission concepts. However, we still want a consistent, extensible backend that works across the Jupyter Project.

There is little advantage in giving users the option to switch between backends. I don't think anyone is talking about that yet. But certainly, a backend author could implement it that way if they choose to. There is nothing bad about giving other developers the option to switch the backend dynamically (even if we don't agree with their choice). However, we don't talk about that yet in the context of the Jupyter Project. We want a single backend with concepts that we can reuse across JupyterLab & JupyterHub.

**Comment by hbcarlos** [comment]
Hi @goanpeca, I think we can extend or modify some of the following sections on JupyterLab docs:

In  [JupyterLab interface](https://jupyterlab.readthedocs.io/en/stable/user/interface.html#the-jupyterlab-interface), we could do an introduction of RTC, how to activate it and which changes bring to the interface

> ### Real-Time Collaboration
> From JupyterLab v3.1, file documents and notebooks have collaborative editing using the Yjs > shared editing framework. By default, this is not activated; to activate it, start JupyterLab with `--collaborative`  flag.

In [tokens](https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html#core-tokens): we could document the new `IDocumentProviderFactory` token.

> `@jupyterlab/docprovider:IDocumentProviderFactory`: A factory object that creates new providers for shared documents. Use this if you want to create a provider for a new shared document.

We could add a new section in [Documents](https://jupyterlab.readthedocs.io/en/stable/extension/documents.html#documents) to the new shared models even though there is no section for ModelDB.
