### ISSUE TITLE
Copy shareable link does not use /hub/user-redirect/ in URL

### ISSUE THREAD

**Issue by alexkim-avant** [jupyterlab/jupyterlab#10369]
## Description

Clicking "copy shareable link" copies to the clipboard a URL that uses the `/user/name/` path instead of the wanted `/hub/user-redirect/`.

## Reproduce

1. Right click on notebook in the file explorer 
2. Click on "Copy Shareable Link" 

## Expected behavior

Returns a URL that uses the /hub/user-redirect/ path schema

## Context

JupyterLab - 3.0.16
JupyterHub - 1.3.0
k8s - 1.16

**Comment by jasongrout** [comment]
Relevant parts of the code, for someone wanting to dive into this:

Share File is provided by a plugin so that it is easy to override. In the docs, the user-direct case is explicitly mentioned: https://github.com/jupyterlab/jupyterlab/blob/9850b1a0461ae7d32374ca970185bdd12029fa62/packages/filebrowser-extension/src/index.ts#L487-L526

Notice the sharing code uses PageConfig.getUrl. Searching jlab for user-redirect, I notice a place where a sharing URL is set: https://github.com/jupyterlab/jupyterlab/blob/9850b1a0461ae7d32374ca970185bdd12029fa62/jupyterlab/labapp.py#L785 and accessed 
https://github.com/jupyterlab/jupyterlab/blob/9850b1a0461ae7d32374ca970185bdd12029fa62/packages/coreutils/src/pageconfig.ts#L119-L124

So nominally we can change getUrl to take a baseUrl parameter in https://github.com/jupyterlab/jupyterlab/blob/9850b1a0461ae7d32374ca970185bdd12029fa62/packages/coreutils/src/pageconfig.ts#L170-L190
defaulting to the existing behavior. Then in the share plugin, we pass in PageConfig.getShareUrl() for that baseUrl parameter?

Setting as good first issue, since I think the above would be enough?

**Comment by jasongrout** [comment]
On the other hand, https://github.com/jupyterlab/jupyterlab/issues/10275 indicates that the user-direct url is coming up in jupyterhub, so someone should reproduce this problem first of all, to make sure it's a problem in JupyterLab and not, for example, in the configuration or something of your particular setup.

**Comment by shngt** [comment]
I tried reproducing this issue, and it seems like it's related to configuration - my firm's deployment of JupyterHub uses the correct `hub/user-redirect` links, but when I tried setting it up on my machine, I could only see `user/name/` links. I'm very new to this project however, so not sure if I'm doing things right.

**Comment by jasongrout** [comment]
I'll have to defer to someone else then - I haven't set up JupyterHub in a production environment before.

**Comment by shngt** [comment]
Apologies for deleting my earlier comment, I didn't want to add any confusion to this thread. For reference, it was this:
> I tried reproducing this issue, and it seems like it's related to configuration - my firm's deployment of JupyterHub uses the correct hub/user-redirect links, but when I tried setting things up on a local machine, I could only see user/name links. I'm very new to > this project however, so not sure if I'm doing things right.

However, I was just reading the documentation for `shareFile` that you linked above - the last line says "If you need to change how this link is generated (for instance, to copy a /user-redirect URL for JupyterHub), disable this plugin and replace it with another implementation." I think this indicates that @alexkim-avant would have to write a custom plugin for JupyterHub sharing?

**Comment by jasongrout** [comment]
I imagine it is already written, and perhaps distributed with jupyterhub or something? I don't know for sure, but I imagine we'd have a lot more people opening issues if this was a widespread problem.

Have you asked in the jupyterhub channels?

**Comment by alexkim-avant** [comment]
I thought this was an issue with JupyterLab, but I can direct this question to the JupyterHub team as well. Thank you!

**Comment by shngt** [comment]
Should this be closed?

**Comment by amimoto** [comment]
This issue does affect me as well but seeing as I'm already making a plugin for an internal project, just going to roll the tweaks to the Copy Shareable URL into that.

Am I understanding correctly that while `page_config['shareUrl'] = ujoin(hub_prefix, 'user-redirect') ` gets set, it doesn't get used later on?

**Comment by gthomas-slack** [comment]
Can confirm that we are seeing the same issue in our deployment of jupyterhub + jupyterlab.

Links generated using the "Copy Shareable Link" take the form of `/user/name/` instead of `/user-redirect/`

JupyterLab - 3.0.16
JupyterHub - 1.4.2
k8s - 1.18.16

**Comment by NoobMaster1999** [comment]
I want to solve the issue.. is this still open??
