### ISSUE TITLE
No menu point for exporting notebook, e.g. to PDF.

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#10450]
![image](https://user-images.githubusercontent.com/3391614/122625420-4781e680-d062-11eb-8f24-cf7560038200.png)
I am missing the menu point for exporting to PDF in JupyterLab 3.0.14.

Is there something that I have to install??

**Comment by fcollonval** [comment]
@soerendip it looks like you are using some extension because the File menu is using a non standard wording `Diagram Notebook`. If you start the stock JupyterLab with binder, you will see the export feature:

![image](https://user-images.githubusercontent.com/8435071/122938545-24fa1100-d373-11eb-9981-71bcc1296107.png)

**Comment by fcollonval** [comment]
You need to have a notebook selected to have access to that submenu.

**Comment by krassowski** [comment]
This might be related to https://github.com/deathbeds/ipydrawio/issues/21 and https://github.com/jupyterlab/jupyterlab/pull/9958.
