### ISSUE TITLE
Move Galata to the `jupyterlab` repo?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10480]
Opening a new issue since this was originally brought by @fcollonval during the weekly meeting yesterday: https://github.com/jupyterlab/team-compass/issues/117#issuecomment-867008413

Should we move Galata to the `jupyterlab` repository here?

Galata currently lives in its own repo under the `jupyterlab` organization: https://github.com/jupyterlab/galata

This would make it easier to iterate on it when core PRs make significant changes to the UI for example.

For reference there is already the `testutils` package being developed in core lab, that other third-party extensions can depend on for unit tests: https://github.com/jupyterlab/jupyterlab/tree/master/testutils

**Comment by jtpio** [comment]
Adding to 4.0 since this is not critical for now, but at least worth considering.

**Comment by krassowski** [comment]
+1. I find it difficult to create new galata test cases just because of the very abstract API that does not allow to test elements that galata is not aware of; for example I tried to create a test case for #10693, which is exactly the kind of integration test I think galata could shine with, but galata has no support for command palette, nor a motion of editor inside of the cell.

This is a third time I tried to write a galata test and just gave up. If galata were in the monorepo this could have helped me to add the missing bit to the galata. An alternative solution would be to make the API more generic, but I guess that would be against the current design goals.
