### ISSUE TITLE
RTC: Username hidden when the cursor is on the first line of a cell

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10625]
## Reproduce

Using this gist for testing: https://gist.github.com/jtpio/6ce26381703355e0ef1da4af742b7f72

1. Start JupyterLab in `collaborative` mode
2. Create a new notebook
3. Stay on the first line in the cell
4. Open JupyterLab in another window / browser

![image](https://user-images.githubusercontent.com/591645/125765920-a60e314a-d806-42c9-923e-f2ef61b3af03.png)

## Expected behavior

The username should be readable.

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: Latest Firefox and Chromium
- JupyterLab version: 3.1.0rc1

**Comment by jtpio** [comment]
Probably this can be fixed with a bit of CSS.

Or upstream in `y-codemirror` if the issue is also there.

**Comment by jtpio** [comment]
Setting as 3.1 if there is time for it. Otherwise it could also be fixed later.

**Comment by bollwyvl** [comment]
If we're fighting CSS... maybe we also put at least a one pixel padding above and below so `y` don't bleed out.

![Screenshot from 2021-07-15 09-09-32](https://user-images.githubusercontent.com/45380/125793505-8550df4c-af2a-49e0-b22a-abf0359ff4ce.png)

Maybe also throw a _tiny_ `border-radius` on all of the corners except for the one that connects with the cursor bar.

**Comment by goanpeca** [comment]
Pinging @hbcarlos :)

**Comment by dmonad** [comment]
It is nearly impossible to render the username outside of the codemirror editor (** there is a solution, but I don't think we should implement it). The username is rendered within a scroll-element. While we can use `z-index` to layer elements on-top of other elements, this doesn't work to bring things out of a scroll-element.

** It is possible to calculate the window-position of the cursor on every change and then abolutely-position the element on the window object so we can make use of `z-index`. But this will likely lead to a bad user experience because of the computational overhead.

> Maybe also throw a tiny border-radius on all of the corners except for the one that connects with the cursor bar.

@bollwyvl This we can do ;) Maybe @hbcarlos?

**Comment by hbcarlos** [comment]
Yes, I can do the round corners.

**Comment by jasonm** [comment]
Tossing a couple other ideas into the ring:

1. If there's an issue with "up-flag" cursors on the first line (e.g. the name indicator is positioned above the text line), could we draw "down-flag" cursors on the first line only? Might it be more computationally feasible to compute whether a cursor is on the first line and conditionally insert some `is-on-first-line` css class?
2. We could add more padding to the top of the codemirror div, so there's enough "breathing room" for the cursor flags to draw. This looks a little odd, though.
3. Similar to (2) but could we use some clever mix of negative margin / padding / wrapper divs to add some additional whitespace that the cursor can draw into without clipping, while still appearing to have the border in the correct place? Basically this would still add vertical padding like (2) but the padding would visually appear above the codemirror box instead of inside it.

I'm curious if any of these strike you as good ideas?

**Comment by fcollonval** [comment]
Fixed by https://github.com/jupyterlab/jupyter_collaboration/pull/122
