### ISSUE TITLE
Remove debug buttons in toolbar

### ISSUE THREAD

**Issue by 3coins** [jupyterlab/jupyterlab#10680]
### Problem

Current notebook has 3 separate debug buttons which serve the same purpose. This is a poor use of toolbar space which could be used by other toolbar items.

<img width="700" alt="Screen Shot 2021-07-22 at 11 48 35 AM" src="https://user-images.githubusercontent.com/289369/126694679-85220209-cf5e-41ee-a999-01ccf6146cbe.png">

### Proposed Solution

Here are a few solutions:
1. Remove both debug button (1) and switch (2) items, keep the right panel button (3) for debug panel display.
2. Hide debug buttons in the toolbar, add a setting option for display of debug button. 
3. Combine the debug icon with the debug toggle button.

### Additional context

N/A

**Comment by krassowski** [comment]
That's an excellent point. Some quick ideas:
3.1 Place the bug on the toggle button (discussed at team meeting - very mixed feelings)
3.2 Let's hide the flick switch and use colour and shape of the bug icon to indicate that the debugger is on. We could make the bug orange when the debugger gets activated. To make it colourblind friendly we could also add a running icon triangle (▶) in the lower right corner of the bug icon.

I don't like option (1) because the state of the debugger currently is tied to a notebook, so it makes sense to have it in the toolbar. When having multiple notebook side-by-side users will get confused on whether the debugger is on or off if the only indication will be in the sidebar.

Having a single icon should be fine given #10469. Maybe the effort should focus more on making it even easier for users to hide items, this is once #10469 is in to allow them to right click one a toolbar button and choose "hide this button" from context menu?

**Comment by fcollonval** [comment]
I fully agree with @krassowski 

1. :-1: 
2. Removing the switch that is taking horizontal space and put things on the icon would be better
3. Suggestion on the modified toolbar and button positions:
:arrow_forward:  (:beetle::arrow_forward:) :stop_button:  or :arrow_forward: :play_or_pause_button: :stop_button:   
I'm unsure about the need to highlight the fact that the debug mode is on. But this is probably a developer IDE bias.

Additional note: since `ipykernel` has now debug enabled. We should not show/hide the debug button dynamically. I hate that and it feel awkward as it takes time to show up. We should rather use the disable/enable feature.

**Comment by jtpio** [comment]
At some point it was also discussed whether debugging should always be on, or when the user starts adding breakpoints. In that case the switch is not needed.

But as mentioned above having some visual indication in the toolbar can still be relevant, since the debugger is activated per notebook / kernel.
