### ISSUE TITLE
Writing Tests for JupyterLab Extensions

### ISSUE THREAD

**Issue by subhamagrawal7** [jupyterlab/jupyterlab#10706]
1. Can this library [Galata](https://github.com/jupyterlab/galata) be used for testing lab extensions and in general be used outside the core team??
2. If the tests can be written in Galata, it would be really helpful if you could provide some documentation for the same as the repository does not seem to have them (apart from the Readme.md which doesn't give all the functions that the API has).
3. If the tests cannot be written in Galata, then, could you give some recommendations for writing the tests in [Cypress](https://github.com/cypress-io/cypress) to ensure they are robust (e.g. don't break on classname changes)

**Comment by fcollonval** [comment]
Hey @subhamagrawal7 


> Can this library Galata be used for testing lab extensions and in general be used outside the core team??

Yes you can. Jupyter widgets are tested using it for example: https://github.com/jupyter-widgets/ipywidgets/tree/master/ui-tests

> If the tests can be written in Galata, it would be really helpful if you could provide some documentation for the same as the repository does not seem to have them (apart from the Readme.md which doesn't give all the functions that the API has).

Having use it, lately the experience is not as great as it could be. There are some plans to build it a bit differently to exploit more features from Playwright.

> If the tests cannot be written in Galata, then, could you give some recommendations for writing the tests in Cypress to ensure they are robust (e.g. don't break on classname changes)

So I would recommend using [Playwright](https://playwright.dev) rather than Cypress. For having use Cypress, Playwright is really above especially in term of default selectors determine by the test code generator tool.

You can see demonstration of integration test with Playwright on the official examples repository: https://github.com/jupyterlab/extension-examples  
Every example has a `ui-tests` folder that contains the integration tests. The readme in that folder describes the main commands to use to create, execute and debug tests.

**Comment by bollwyvl** [comment]
For a lot of extensions I work on, i prefer the workflow offered by [robotframework](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html) and [seleniumlibrary](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html).

Some of the lab/notebook/(old) nteract patterns are wrapped up in the `pip`/`conda-forge` installable [robotframework-jupyterlibrary](https://robotframework-jupyterlibrary.readthedocs.io) (disclaimer: author). 

Here's an example on [`jupyter-server-proxy`](https://github.com/jupyterhub/jupyter-server-proxy/blob/master/tests/acceptance/Lab.robot) where the `robot` execution is wrapped inside [`pytest`](https://github.com/jupyterhub/jupyter-server-proxy/blob/master/tests/acceptance/test_acceptance.py) so that the change to local/CI testing was quite small, and accomodates both JupyterLab and Notebook Classic.

The advantages I find for me and my teams:
- testing can at least be _started_ by non-developers, as it _pretty much_ looks like english
- the reports are very human-  and machine- readable, if a bit bespoke
- since it doesn't directly depend on `jupyterlab` (or `nodejs` for that matter) it's easier to test against multiple versions
- it uses _real browsers_
- it avoids `nodejs` on windows entirely :tada:

Some disadvantages vs node-based solutions:

- there is no formalized WebDriver spec for:
  - built-in video recording
    - the heavyweight solutions are... _heavy_. like run the whole shooting match in a VM and record _that_
  - browser console log access
  - _good_ PDF generation
- the selenium stack is _flaky_
  - plan accordingly (e.g. allow for retries, etc)
- it can be _very_ hard to keep some browsers in sync with their webdrivers  (e.g. anything based on chromium) 
  - in most CI runners, there are already (old) browsers installed, but they have the right `*driver`
  - with `conda-forge`, one can install `firefox` (including the LTS) and `geckodriver` and _basically_ always get a working configuration (disclaimer: maintainer of both)

**Comment by subhamagrawal7** [comment]
Thank you for all the suggestions @fcollonval @bollwyvl !! Will definitely try them out.

**Comment by subhamagrawal7** [comment]
I am getting 500 Internal Server Error when using config specified [here](https://github.com/jupyterlab/jupyterlab/tree/master/galata#launch-jupyterlab). I think the issues is coming when specifying `dev_mode=true` since I was also getting this error with `--dev-mode` flag. This is causing problems since the Galata v4 seems to be using node-fetch internally, which seems to be checking some `/lab/api endpoint` which is not available when you normally start the lab instance.

**Comment by fcollonval** [comment]
Thanks for reporting back @subhamagrawal7 
Could you try with the settings used in the jupyterlab-git PR:

```py
from tempfile import mkdtemp

c.ServerApp.port = 8888
c.ServerApp.token = ""
c.ServerApp.password = ""
c.ServerApp.disable_check_xsrf = True
c.ServerApp.root_dir = mkdtemp(prefix="galata-test-")
c.ServerApp.open_browser = False
c.LabApp.expose_app_in_browser = True
```

You probably nail the error. And we should correct the documentation if the above works for you.

**Comment by subhamagrawal7** [comment]
With these settings, lab is working, but, I am still getting `FetchError: invalid json response body at LAB_URL/lab/api/contents/ui-tests-foo-Create-New-Notebook?type=directory&content=1 reason: Unexpected token < in JSON at position 0` when running the test mentioned [here](https://github.com/jupyterlab/jupyterlab/tree/master/galata#first-test)

**Comment by subhamagrawal7** [comment]
This [file](https://github.com/jupyterlab/jupyterlab/blob/15d51ef6c521b9680584dc429bee82f53f46215c/galata/src/contents.ts) is being used which seems to be causing the error. This is the error log that I am getting -
```
1) ui-tests/simple.spec.js:7:5 > Notebook Tests Create New Notebook ==============================

    FetchError: invalid json response body at LAB_URL/lab/api/contents/ui-tests-simple-Create-New-Notebook?type=directory&content=1 reason: Unexpected token < in JSON at position 0

        at /node_modules/node-fetch/lib/index.js:273:32
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at ContentsHelper.directoryExists (/node_modules/@jupyterlab/galata/src/contents.ts:88:21)
        at Object.tmpPath [as fn] (/node_modules/@jupyterlab/galata/src/fixtures.ts:247:9)
```
Can you tell how can I disable the checks being done regarding this?? Since even after using `autoGoto: false`, I am still getting the error. I am not able to debug what is the issue here.

**Comment by fcollonval** [comment]
My bad, I forgot that indeed the `tmpPath` fixture and the contents helper are using `node-fetch`...

To explain the stack trace you are reporting, for each test, an unique folder is created on the server (to be sure content does not pollute other tests). That folder is created by the `tmpPath` fixture [there](https://github.com/jupyterlab/jupyterlab/blob/e9a82c3f35b76edb124a3998d101695a337e5c0a/galata/src/fixtures.ts#L245). It used the contents API to create the folder on the server. Those API are JSON based, but in your case the answer to the call testing if there is already a `tmpPath` returns a non-JSON body; hence the error. So now the question is why. I would guess the `baseURL` fixture is not appropriate for your configuration. The default value is `baseURL ?? process.env.TARGET_URL ?? 'http://localhost:8888'`. Say differently, if the server is not running on _http://localhost:8888_, you should set the environment variable `TARGET_URL` or the fixture `baseURL` to the proper URL.

> `autoGoto` does not have effect because that code runs before going to the webpage.

**Comment by subhamagrawal7** [comment]
I have tried setting the baseUrl in my spec file by using this -
`test.use({ baseURL: "http://localhost:8889/lab/" });`
But still things don't seem to work . Am I doing something incorrect here??

**Comment by fcollonval** [comment]
You should drop the `/lab/`:

```ts
test.use({ baseURL: "http://localhost:8889/lab/" });
```

Could you extract the example test with your configuration and share it through github or a similar service?

**Comment by subhamagrawal7** [comment]
Thank you so much @fcollonval, that actually worked!!! I think we should probably mention this somewhere as /lab is kind of natural tendency. (I was picking up from some of the previous tests that had been written somewhere). Should have mentioned this earlier. Thanks!!

**Comment by krassowski** [comment]
@fcollonval I'm struggling with:

```
Failed to create directory test-styles-Citation-styles-support-show-some-styles-after-opening FetchError: request to http://localhost:8888/api/contents/test-styles-Citation-styles-support-show-some-styles-after-opening failed, reason: connect ECONNREFUSED 127.0.0.1:8888
```

message over at https://github.com/krassowski/jupyterlab-citation-manager/pull/41. I seeded the boilerplate from your draft PR on jupyterlab-git and the tests are passing fine locally (and one of them passes fine on CI) but the other one has some kind of an issue with creating a directory. Any idea what could be going on? How I can debug this?

**Comment by krassowski** [comment]
Oh, it looks we need to wait for JupyterLab to actually be ready. Fixed in https://github.com/krassowski/jupyterlab-citation-manager/pull/41/commits/37676fa5aecc784e8a33be618c0b0fe1873f0e22, the `jupyterlab-git` PR (https://github.com/jupyterlab/jupyterlab-git/pull/1030) will probably benefit from that too (though it could have been exacerbated by citation-manager server extension which is taking time to find citation style XMLs on disk).

**Comment by fcollonval** [comment]
Sorry @krassowski I was mostly AFAK this week-end. Indeed I got lucky in `jupyterlab-git` to not have to wait for the server. I'll update the PR to reflect that.

**Comment by jtpio** [comment]
FYI @subhamagrawal7 the cookiecutter now has support for testing (added in https://github.com/jupyterlab/extension-cookiecutter-ts/pull/207).

Closing as answered and fixed, but feel free to comment here or open a new issue if you still have questions. Thanks all!

**Comment by subhamagrawal7** [comment]
Thanks @jtpio, @fcollonval and the JupyterLab Team ! The suggestions were really helpful and we were able to add tests for our specific use cases for extensions using Galata.
