### ISSUE TITLE
Update package to remove vulnerability in dependencies of old version of @jupyterlab/coreutils

### ISSUE THREAD

**Issue by vincentsum777** [jupyterlab/jupyterlab#10753]
Hi, @jtpio @afshin, I accidentally find there is a vulnerability introduced by package **url-parse**:
### Issue

   A vulnerability is introduced in **_@jupyterlab/coreutils@4.3.0_**:
     Vulnerability **CVE-2021-27515** is detected in package **_url-parse_** (versions:<1.5.0):  [https://snyk.io/vuln/SNYK-JS-URLPARSE-1078283](https://snyk.io/vuln/SNYK-JS-URLPARSE-1078283)
  As far as I know, the above vulnerable package is referenced by **_@jupyterlab/coreutils@4.3.0_** via:
1. `@elyra/metadata-editor-extension@1.0.0-rc.2 ➔ @elyra/application@1.5.3 ➔ @elyra/ui-components@1.5.3 ➔ @jupyterlab/ui-components@2.3.0 ➔ @jupyterlab/coreutils@4.3.0 ➔ url-parse@1.4.7`
2. `@dfnotebook/dfnotebook-extension@0.1.0-beta.0 ➔ @dfnotebook/dfcells@0.1.0-beta.0 ➔ @dfnotebook/dfoutputarea@0.1.0-beta.0 ➔ @jupyterlab/apputils@2.3.0 ➔ @jupyterlab/coreutils@4.3.0 ➔ url-parse@1.4.7`

### Solution
As you can see, since **_@jupyterlab/coreutils@4.3.0_** ([2,746 downloads per week](https://www.npmjs.com/package/@jupyterlab/coreutils/v/4.3.0?activeTab=versions)) is transitively referenced by **297** downstream projects (e.g., [@jupyterlab/tabmanager-extension 2.3.0](https://www.npmjs.com/package/@jupyterlab/tabmanager-extension) (latest version), [@elyra/metadata-editor-extension 1.0.0-rc.2](https://www.npmjs.com/package/@elyra/metadata-editor-extension) (latest version), [jupyterlab-nvdashboard 0.5.1](https://www.npmjs.com/package/jupyterlab-nvdashboard) (latest version), [jupyterlab-execute-time 1.1.0](https://www.npmjs.com/package/jupyterlab-execute-time) (latest version), [k3d 2.9.6](https://www.npmjs.com/package/k3d) (latest version))

If **_@jupyterlab/coreutils@4.3.\*_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

Could you help update the package in this version?

### Fixing suggestions

In **_@jupyterlab/coreutils@4.3.\*_**, you can kindly perform the following upgrade(not crossing major version) :
`url-parse ~1.4.7 ➔ ~1.5.0`; 

**Note:**
_url-parse@1.5.0(>=1.5.0) has fixed the vulnerability ([CVE-2021-27515](https://snyk.io/vuln/SNYK-JS-URLPARSE-1078283))_

Thanks for your contributions to the downstream users!^_^

**Comment by krassowski** [comment]
Welcome @vincentsum777.

I believe this was fixed with an update of url-parse to 1.5.1 by #10219 in 3.1 release and backported to 3.0 branch in #10221 in 3.0.15. Please correct me if I am wrong.

As a PSA I would like to highlight that url-parse update wreaked havoc downstream (https://github.com/krassowski/jupyterlab-lsp/issues/595, https://github.com/krassowski/jupyterlab-lsp/issues/612) because it broke handling of `file:` protocol (https://github.com/unshiftio/url-parse/issues/203) and friends (https://github.com/unshiftio/url-parse/issues/205); fixes for both issues already landed and it seems that 1.5.3 was released last week, so indeed we should be able to backport this to 2.x seamlessly now (but we need to ensure 1.5.3 or newer is used).

As for the impact assessment, I can say that `jupyterlab-execute-time 1.1.0` is not the latest version, they just no longer publish to NPM and instead distribute it as pre-built extension published via PyPI and the latest version is not affected. Similarly `@jupyterlab/tabmanager-extension` is a dead package, no longer used since 3.0. I do not know the other packages.

**Comment by vincentsum777** [comment]
@krassowski, thank you for your feedback. I know that this issue has been resolved since **@jupyterlab/coreutils@5.0.6**. However, **@jupyterlab/coreutils@4.3.0** still directly depends on **url-parse@1.4.7**:
`@jupyterlab/coreutils@4.3.0 ➔ url-parse@1.4.7`

What’s worse, **@jupyterlab/coreutils@4.3.0** is so popular ([2,746 downloads per week](https://www.npmjs.com/package/@jupyterlab/coreutils/v/4.3.0?activeTab=versions)) that about 297 downstream projects still depend on it. In this case, lots of downstream projects got the vulnerability reports every build. A feasible solution is to release a patched version **@jupyterlab/coreutils@4.3.1**. 
In **@jupyterlab/coreutils@4.3.1**, you can simply perform the following update:
`url-parse ~1.4.7 ➔ ~1.5.3`;

As you konw, **url-parse@1.5.3** has removed the vulnerability ([**CVE-2021-27515**](https://snyk.io/vuln/SNYK-JS-URLPARSE-1078283)) and resolved some other issues. Then this vulnerability patch will be automatically propagated into a large amount of downstream projects via **@jupyterlab/coreutils@4.3.1**.

Thanks again.

**Comment by krassowski** [comment]
Thank you. There is a draft pul request open for that #10755, please feel welcome to help with it. As I mentioned `url-parse@1.5.x` **breaks things** and apparently even 1.5.3 broke our tests, so if you believe it is _simply_ performing that update, please do help ;)

I see you opened similar or identical issues in other repositories - please see responses of other maintainers (e.g., https://github.com/gatsbyjs/gatsby/issues/32657, https://github.com/jquense/yup/issues/1431) which explain why the fixes for ReDoS don't get the highest priority for back-porting several versions back.

**Comment by jtpio** [comment]
@vincentsum777 were you able to check again now that https://github.com/jupyterlab/jupyterlab/pull/10755 has been merged and released?

**Comment by krassowski** [comment]
Closing as this appears resolved. Please reopen if needed.
