### ISSUE TITLE
Editor ignores indent setting in Python notebooks

### ISSUE THREAD

**Issue by GoliathLeviathan** [jupyterlab/jupyterlab#10751]
When using JupyterLab, the indent setting seems to be ignored on notebook files (.ipynb). Tested with JupyterLab 3.1.1 (installed from pypi).

My user settings of the JupyterLab editor contains the following setting (created by JupyterLab when setting the indention using the Settings menu):
```
{
    "editorConfig": {
        "cursorBlinkRate": 530,
        "fontFamily": null,
        "fontSize": null,
        "lineHeight": null,
        "lineNumbers": true,
        "lineWrap": "on",
        "wordWrapColumn": 80,
        "readOnly": false,
        "tabSize": 4,
        "insertSpaces": false,
        "matchBrackets": true,
        "autoClosingBrackets": false,
        "rulers": [],
        "codeFolding": false
    }
}
```
I would expect, that the editor inserts a tab character when indenting with the tab-key, but it still inserts 4 spaces. I tested setting the indention to 8 spaces, and in the notebooks it still only uses 4 spaces. I created a new Python file in the editor and there the Indention setting is respected (tab character or 4/8 spaces, whatever is chosen).

Jupyter notebook is able to insert tabs. I have the following settings in ~/.jupyter/nbconfig/notebook.json:
```
{
  "CodeCell": {
    "cm_config": {
      "indentWithTabs": true
    }
  }
}
```

**Comment by krassowski** [comment]
Ok, I looked more into this. Your configuration is good and it indeed should (and does) insert tabs instead spaces. The problem is might be that you are editing configuration for Text Editor and expecting that it would work in Notebook too (I would expect the same but it does not). Instead you may need to go to *Advanced Settings Editor* → *Notebook* and edit configuration in there, separately for `codeCellConfig`, `markdownCellConfig`, and `rawCellConfig`. Please let me know if it worked.

There are discussions about unifying those settings in the future.

**Comment by GoliathLeviathan** [comment]
This works indeed.

Looking forward to the unification of these settings, but my issue is solved.

Thanks.
