### ISSUE TITLE
Notebook version reverts to 4.4 during RTC

### ISSUE THREAD

**Issue by cameron-toy** [jupyterlab/jupyterlab#10784]
## Description

When multiple people are collaborating on a notebook, the notebook reversion reverts from 4.5 to 4.4

## Reproduce

Start a notebook session with RTC enabled. Open a notebook--the version should be 4.5. Connect with another client, open the same notebook, and check the notebook version again.

EDIT:
The collaborator must edit and save before the notebook version change happens.

## Expected behavior

The notebook version stays the same.

## Context

- JupyterLab version: 3.1.3

**Comment by hbcarlos** [comment]
Hi @cameron-toy, thanks for opening this issue. I can take a look.

I'm a bit lost on the notebook version. Is it the `nbformat` and `nbformat_minor` attributes on the notebook's metadata?

**Comment by cameron-toy** [comment]
@hbcarlos yes, `nbformat`.`nbformat_minor`

Before collaborator connects:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/38936057/128740917-994b9ad0-8e54-42e0-8f92-eec3e70465ef.png">

After collaborator connects, edits the notebook, and saves it:
http://localhost:8888/lab/workspaces/auto-j/tree/new%20notebook.ipynb

The 4.5->4.4 shift is significant because 4.4 doesn't have cell ids.

**Comment by hbcarlos** [comment]
The issue comes from RTC not sharing the state attributes like `nbformat`, `nbformatMinor`, and `dirty`.

The default `nbformat` version supported in JupyterLab is 4.4 (see #10018). When loading a notebook from disk, if the format version of the notebook is higher than the default version, JupyterLab updates the state of the notebook to the corresponding version in the method `fromJSON()`:
https://github.com/jupyterlab/jupyterlab/blob/aef7e9e7233a3c910e0cd417c1a7a6460458cf66/packages/notebook/src/model.ts#L320-L324

When using JupyterLab in collaborative mode, the file is loaded from disk only for the first client opening the notebook. Every other client receives the notebook's content from the document provider, so we don't call the `fromJSON()` method. As the state attributes are not shared, when JupyterLab updates the `nbformatMinor` attribute on the first client, this change is not propagated through Yjs to other clients.

**Comment by hbcarlos** [comment]
This is solved in #10795

**Comment by jasongrout** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/10795
