### ISSUE TITLE
Dark theme dropdown unreadable

### ISSUE THREAD

**Issue by mohmad-null** [jupyterlab/jupyterlab#10857]
Version 3.1.7 - first time using it; completely new install; firefox
I changed the theme to JupyterLab Dark. Then I try and create a new notebook and the dropdown looks like:

![image](https://user-images.githubusercontent.com/22342282/129750512-e3b3884f-389b-452c-9015-628216eaff40.png)

**Comment by krassowski** [comment]
This does not look good indeed. I wanted to fix it so first I tried to reproduce it but I could not reproduce it with information that you provided alone. Using Firefox 91 on Ubuntu 21.04 I opened JupyterLab 3.1.7 with Dark Theme:

![firefox](https://user-images.githubusercontent.com/5832902/129756829-8a7d73c2-d418-493c-acb9-c8b6f65d9f9a.gif)

It wold greatly help if you could provide more information following the [bug report template](https://github.com/jupyterlab/jupyterlab/issues/new?assignees=&labels=bug&template=bug_report.md), including:
- What version of Firefox are you using?
- What operating system are you using?
- Do you have any specific Firefox theme installed? If yes, have you tired to disable any non-default theme and see how it works with the default theme?

**Comment by mohmad-null** [comment]
Firefox 60.6.1esr on win 7
No firefox themes that I'm aware of. Nor any extensions that touch theming either I don't think.

**Comment by krassowski** [comment]
That is an old version of Firefox it seems. I just looked it up and the currently supported versions of Firefox (by Mozilla) are:
- Firefox 91.0
- Firefox 91.0 ESR
- Firefox 78.13 ESR

I don't know how much other maintainers are willing to support old releases of browsers, but I personally cannot install software which is not currently supported (like Firefox 60) due to potential security issues.

This is relevant because Firefox has multiple bugs in handling dropdowns and older versions are more likely to be affected.

Would you be able to check with a recent version of Firefox, please?

**Comment by mohmad-null** [comment]
That particular install of FF can only access localhost so I don't bother keeping it updated.
I can confirm that accessing it on a FF91 it looks as expected, same if I use a chromium browser.

I'm happy if you flag this as "won't fix". Thanks!

**Comment by krassowski** [comment]
Thanks!
