### ISSUE TITLE
Can't update my module by import

### ISSUE THREAD

**Issue by newyorker123** [jupyterlab/jupyterlab#10883]
## Description

I have a module my_module.py , and define a function my_fun1 in it.
I import my_module in ipynb and can use my_func1 normally.

But if I add a new function my_func2 in the module and save the .py module, and import the module again in ipynb, my_func2 still can not be found. And raise an AttributeError .

Only by restarting the kernal can solve the problem, but all variables will be lost.

## Expected behavior

Should get access to all the function after re-Importing the module 

## Context

- Operating System and version:macOS Big Sur 
- Browser and version: Chrome
- JupyterLab version: 3.1.7

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Hi @newyorker123, thanks for opening this issue. This is not a bug but a behaviour which can be changed in the kernel (as most things related to any specific programming language are related to the kernels, not to JupyterLab itself). I am not sure which kernel you are using because you omitted the troubleshoot output in the bug report template, so I will just assume that it is IPython/ipykernel.

IPython has an [autoreload _magic_](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html), which allows you to achieve the intended behaviour. You can enable it by placing the following commands in the first cell of your notebook:

```ipython
%load_ext autoreload
%autoreload 2
```

(remember to restart the notebook). See more in the relevant Stack Overflow question: [Reloading submodules in IPython](https://stackoverflow.com/questions/5364050/reloading-submodules-in-ipython).

Tip: if you have multiple commands like which you run at the beginning of each notebook you can create a new notebook, say `prepare.ipynb`, put those commands in there and run all of them at once by placing the run magic `%run prepare.ipynb` in the first cell.

**Comment by agoose77** [comment]
To add to @krassowski's point; Jupyter Notebooks are powered by Jupyter Kernels, which run code for different languages (simplified). Most kernels are stateful, which means that the result of running one cell can change the result of running a later cell. For example,

```python
>>> x = 1
```
```python
>>> x = 2
```
```python
>>> print(x)
2
```

In Python, importing a module modifies the state of the interpreter: it stores the created `ModuleType` object in `sys.modules`. This means that when you import the same module again, Python doesn't re-load it from disk: the object in `sys.modules` is just re-used. So, this is a *Python* feature, not a bug in JupyterLab (or IPyKernel).
