### ISSUE TITLE
Add `list` to `jupyter lab workspace` to see all workspaces

### ISSUE THREAD

**Issue by baggiponte** [jupyterlab/jupyterlab#10890]
### Problem

Switching from one workspace to another is not super easy unless you save a `.jupyterlab-workspace` within the project directory. Problem: sometimes said file is exactly in the directory you want to open.

Opening workspaces is straightforward, as outlined in the [docs](https://jupyterlab.readthedocs.io/en/stable/user/urls.html#managing-workspaces-ui). However, sometimes one might not exactly recall the workspace name - I usually rely on `jq` to list the number of workspaces I have.

### Proposed Solution

Add the CLI subcommand `jupyter lab workspaces list` to see all workspaces (and location?). In this way, one can simply copy-paste the name inside the URL bar.

**Comment by karthikayan4u** [comment]
Hello @agoose77 , I wish to work on this issue. Should I be assigned for this issue to work on the same? I am a complete beginner to open source.

**Comment by ariso-sac** [comment]
Hi Team !!
I would like to work on this issue.
Could you help me with code architecture and place where this shell commands are placed ?

**Comment by agoose77** [comment]
Hi all - 
JupyterLab is split into a "front end" in TypeScript, and a "back end" in Python. The Python-side uses the `traitlets` library to implement configurable, typed, reactive objects. Traitlets is *also* used to implement (through layers of inheritance) a command-line API. The classes that implement the workspace commands are in `jupyterlab/labapp.py`, e.g. the `LabWorkspaceExportApp`
https://github.com/jupyterlab/jupyterlab/blob/05c2482bd9cb85cd134dff4bcb047a3c7d5e2326/jupyterlab/labapp.py#L261-L294


Information about how `traitlets` is used to implement commandline programs can be found [in its documentation](https://traitlets.readthedocs.io/en/stable/config.html#the-main-concepts)

Now, the actual workspace reading logic for the JupyterLab API (which the frontend talks to over HTTP) is in a separate repo: 
https://github.com/jupyterlab/jupyterlab_server/blob/900ee8a4547749cd46fcc5d1649c1f5b9da675e5/jupyterlab_server/workspaces_handler.py#L134-L139

This calls `_list_workspaces` - https://github.com/jupyterlab/jupyterlab_server/blob/master/jupyterlab_server/workspaces_handler.py#L21-L46

I think you'd want to re-implement this code yourself because it is private. It's not clear to me how we ended up with this particular separation (some logic in `jupyterlab_server`, some in `jupyterlab`), but I'm sure that @jasongrout et al. might weigh in if we need to move things around. I'm pretty sure we need to add this code in `jupyterlab` because we can't move the existing workspace commands without breaking other peoples code!

The general steps required here are:
1. Create a new `LabWorkspaceListApp`
2. Create a method to list the workspaces using the same logic in https://github.com/jupyterlab/jupyterlab_server/blob/master/jupyterlab_server/workspaces_handler.py#L21-L46
3. Add both a "json" and "human-readable" output. For this, look at the [`jupyter server list` command](https://github.com/jupyter-server/jupyter_server/blob/master/jupyter_server/serverapp.py#L587-L634) — it takes `--json` and `--jsonlist` flags which turn on per-entry and entire-output JSON serialisation!

**Comment by karthikayan4u** [comment]
Thank you @agoose77 . I will complete and raise a PR. In case I get stuck somewhere, I will get back to you.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/introduce-yourself/17/265
