### ISSUE TITLE
Undo causes changes to occur outside viewport.

### ISSUE THREAD

**Issue by adpatter** [jupyterlab/jupyterlab#11253]
## Description

The current implementation can work like this:

1. A user has been working on a very long workflow e.g., tens of cells of various lengths.
2. The user opens the Notebook and scrolls to the bottom of the workflow.
3. The user makes a modification that changes which Medical Record Numbers will be included for a cohort of subjects.
4. The user scrolls to the top of the workflow.
5. The user makes a modification to a cell near the top of the workflow.
6. The user backs out of the modification using CTRL-Z.
7. The user mistakenly presses the key sequence too many times and unknowingly removes the change to the Medical Record Numbers at the bottom of the workflow because **_the viewport did not scroll to where the undo was happening_**.

**Comment by jasongrout** [comment]
I think you were there in the [discussion](https://github.com/jupyterlab/team-compass/issues/128#issuecomment-936683833) we had in the dev meeting yesterday around the document-wide undo/redo. I think the consensus there was that the default 3.0 behavior should be fully restored when the experimental `--collaborative` flag is not given, i.e., the document-wide undo/redo should *also* be considered experimental at this point. Clearly there are some rough edges, and we're working through those.

It seems that this rough edge in particular touched a nerve with you. I don't think having this behavior was intentional, and those working on it have put a *lot* of time and effort into bringing a very valuable foundation for future work (not just real-time collaboration, but this foundation is enabling us to do other things we've wanted to do for years). We appreciate kindness and patience in bringing these points up in a constructive way. We also definitely appreciate all the help you've been in the community. You've been an example of how to reach out and help especially new users and developers. Thank you.

Summarizing your issue above, I agree that undo should scroll to the place where the undo is happening by default, or at least indicate very clearly that a change happened above or below the current viewport (perhaps flashing something somewhere indicating a change?). Scrolling to the place of the undo should hopefully be a relatively straightforward change to correct this oversight.

Another great thing would be to also have a time slider that lets you very easily scroll back and forth in the undo/redo history, like CoCalc has.

**Comment by adpatter** [comment]
This is an application that is being actively used in highly critical contexts.  This is an enormous responsibility.  This is a responsibility that far outweighs the aspirations of developers and the introduction of new features.   **This responsibility is what makes developer contributions important.**  I think we understand that.

You wrote, "It seems that this rough edge in particular touched a nerve with you."  I am speaking for the person who is affected by the application and may not even know the application exists.  This person wants to be accurately placed into the correct experimental drug cohort.  Collaborative Notebooks aren't even a concept for this person.

**Comment by krassowski** [comment]
Cross-referencing a comment where this was suggested earlier: https://github.com/jupyterlab/jupyterlab/issues/10791#issuecomment-898044343. I am really happy to see this as a separate issue. I understand why this behaviour is annoying, I experienced it yesterday too. I hope we can continue discussing how to fix the problem in a friendly tone.

**Proposed solution**: in document-wide undo/redo mode, when user requests undo or redo always change focus to the cell which gets modified.

In addition, maybe (just maybe): if a change gets undone/redone in a cell different than the current cell a small (150ms?), configurable delay gets added so that the change happens when the user is looking. The main thread should be released before the delay/undo starts so that the focus operation is performed and repainting happens prior to the actual operation and the users sees the notebook after scrolling to the appropriate place.

**Context**: Applications such as PowerPoint, or LibreOffice Impress have a similar problem. In LibreOffice it is solved by switching to the slide which was modified, but it is still not satisfying for me because (1) I do not see the change itself; further, (2) if the change was addition of a slide and its outside of the view LibreOffice does not have a slide to switch to and switches to the first slide in the deck which is really annoying (say you are on slide 50, you undid addition of slide 100 but you are taken back to slide 1). This lead me to develop a habit of <kbd>Ctrl</kbd> + <kbd>z</kbd> → <kbd>Ctrl</kbd> + <kbd>y</kbd> → (small delay) → <kbd>Ctrl</kbd> + <kbd>z</kbd>, to actually see what gets undone.

We will have the same problems with cells. Based on (1) and (2) I propose that we consider having a slight delay between switching to cell and actually performing the undo. I know that this idea might not be well received as it introduces extra complexity, but I am trying to think about UX one step ahead to mitigate future headaches and make it possible to write it well on the first pass. Of course there is a problem of what happens if during the delay something changes; well I think that undo manager should always consider that anyways given the RTC (what happens if another user edited before your undo request was processed), so I don't consider it to be an extra requirement.

I think that it would be good if you could please check with the slides software (MS/Apple one) so we can see if anyone implements this with a delay, or animation as suggested above, or if they have different solutions.

**Additional improvements**
- In a long term I imagine optional very quick (300ms?) animation for cell deletion and addition could provide valuable clues for users. I don't think these are necessary for the initial solution though.
-  The newly focused cell could get a highlight effect on the border to make it more apparent where the change is happening; this could fade out in say 500ms second so it is persists after the change was applied, allowing users to process what just happened; additional highlights could be applied to the text itself (I am not a huge fan of those, but lets discuss):
   - if the undo resulted in addition of text, it could be highlighted, e.g. with a light green background
   - if the undo resulted in removal of text, it could have a strike through effect applied for a fraction of a second prior to the removal.

**Comment by krassowski** [comment]
I think this conveys the same idea that I proposed above, unless I am missing something? If it's the same but from a different angle then I'm happy that we agree, otherwise a bit more detailed description highlighting the differences would help.

**Comment by jasongrout** [comment]
> However, perhaps, in JupyterLab, movements among cells should constitute a discrete undo event.

That's an elegant way to address the focus shifting. Perhaps not all cell movement should be considered an undo event, but perhaps just movements that involve editing a cell? For example, if quickly moved to another cell to check something, then moved back, I would expect that the movement alone would not be an undo event. But if I moved down and changed something, perhaps that would count as two different undo events - the movement down, and then the change?

**Comment by adpatter** [comment]
The Notebook is scrolling to the place where the undo takes place in 3.1.7.  However, I wasn't able to find the PR that fixed this.
