### ISSUE TITLE
Next steps on RTC

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#11434]
I'm opening this issue to keep track of the next steps we plan for real-time collaboration in JupyterLab 4.0.

### Deduplicate content
Currently, we have the document's content triplicated in the view, ModelDB and YJS. I.e., the same content is mirrored in different data structures. This means that every time one of the models changes, we must update all other models to keep them in sync. This approach is very complex and prone to bugs. As commented several times, we need to remove ModelDB and use only the shared models to manipulate content. This will allow us to simplify the existing code. For extension authors, this means that they will no longer have access to ModelDB. Instead, they should use the new shared-models API, which provides better guarantees. The switch should be fairly straight-forward.
* jupyterlab/jupyterlab#11602 

### Add tests
* To the shared models
* To the username: https://github.com/jupyterlab/jupyterlab/pull/11852#issuecomment-1011994165

### Changes on the Shared-models
* Undo manager by cell jupyterlab/jupyterlab#10791
* jupyterlab/jupyterlab#11640

### ICurrentUser
* jupyterlab/jupyterlab#10965
* jupyterlab/jupyterlab#11443
* jupyterlab/jupyterlab#11678

### UI features
* List of collaborators: jupyterlab/jupyterlab#11528
* Current focused cell: jupyterlab/jupyter_collaboration#109
* Rename anonymous users

### Add RBAC
* jupyterlab/jupyterlab#11355

### Use the python port of YJS on the backend
The locking approach used now does not work well when there are many collaborators, we could improve it to make it work decently, but it will always be prone to fail.

The best approach is to adopt the new python bindings for YJS on the backend. This implies removing the content REST API and accessing the document's content through YJS. At the same time, we would need to remove the save button/command since the document's content would always be synced to disk; a la google docs. Using YJS on the backend has some other benefits that could be tackled later by extension, like using YJS versions to see the list of changes between versions; a la git. 
* jupyterlab/jupyterlab#11599

In addition, it allows to tackle the following issues:
* jupyterlab/jupyterlab#2833
* jupyterlab/jupyterlab#9621
* jupyterlab/jupyterlab#10544

cc @dmonad

**Comment by martinRenou** [comment]
> At the same time, we would need to remove the save button/command since the document's content would always be synced to disk

Maybe JupyterLab could always work on file copies and only overwrite the original on save?

**Comment by hbcarlos** [comment]
I updated the first comment with new PRs and issues.

**Comment by minrk** [comment]
https://github.com/jupyterlab/jupyterlab_server/issues/219 will be important to resolving the right permissions for any given request

**Comment by minrk** [comment]
Consolidating some notes on roles across a few PRs.

Jupyter Server doesn't plan to implement roles. Instead, it implements resource-level permissions (scopes) in https://github.com/jupyter-server/jupyter_server/pull/165.

Roles are not necessary for fine-grained permissions. They are a convenience for _managing_ those permissions, but have no part in their enforcement.

I don't think Jupyter Server should have a concept of roles, and I'm not sure JupyterLab should, either. Instead, _scopes_ should be sufficient. Roles make sense as an implementation detail for how permissions are resolved from user->scopes, but I think that should be the responsibility of the Authorization provider (e.g. JupyterHub), and not part of the JupyterLab or Jupyter Server APIs.

The plan for integrating this in JupyterHub is to allow custom scope definitions in JupyterHub roles, so you could have e.g.

```python
c.JupyterHub.load_roles = [
{
  "name": "read-only",
  "scopes": [
    "access:servers", # baseline access for get_current_user
    "custom:jupyter_server:read:contents", # custom scope, passed along to Authorizer
  ]
}
]
```

where a Jupyter Server Authorizer class would resolve that scope to authorize requests with `resource='contents', action='read'`.

I think the only situation where 'roles' should be used on lab/server is if folks decide that 'scopes' should not be used directly, and only have strictly defined, immutable list of 'roles' that correspond to collections of permissions. In this case, the custom JupyterHub role would look more like:

```python
c.JupyterHub.load_roles = [
{
  "name": "read-only",
  "scopes": [
    "access:servers", # baseline access for get_current_user
    "custom:jupyter_server:reader", # custom scope embeds role assignment only, 'reader' role interpreted by Authorizer
  ]
}
]
```

The reason I think these should be immutable is that if JupyterLab needs to make UI decisions based on the role name, it needs to know what the role name _means_, and needs to encode the same permission map of role name to endpoints that the server will enforce. If this is mutable, it needs to resolve scopes directly at runtime anyway, in which case the role falls away as a server-side implementation detail the UI doesn't need to know about.

**Comment by minrk** [comment]
Here's my current understanding of tasks for this:

1. implement authorization of endpoints in jupyter-server (AuthorizationManager API, https://github.com/jupyter-server/jupyter_server/pull/165)
2. define authorization scopes for RTC in jupyterlab-server and enforce with the appropriate calls to Jupyter Server's `authorized`
3. handle partial permissions in JupyterLab UI (it's unclear to me what the frontend needs to be _aware_ of vs just failing unauthorized actions with 403. I would guess this is relevant for the RTC part, at least).
3. support custom scopes in JupyterHub roles
4. implement JupyterHubAuthorizationManager that handles custom scopes stored in JupyterHub roles to resolve authorizations (scopes are already present in the user model when run with 2.0, just need the AuthorizationManager to define how they should be represented and look for them).

There is an additional JupyterHub-specific step for RTC from a UI perspective that is allowing users to grant _other_ users access to their servers. Currently, users cannot assign each other permissions that they do not already have. But all of the above should work with a baseline of granting permissions at the JupyterHub config level.

**Comment by hbcarlos** [comment]
> Jupyter Server doesn't plan to implement roles. Instead, it implements resource-level permissions (scopes) in jupyter-server/jupyter_server#165.

After reading a little more about the work in server and hub, I agree with you, @minrk. The best way of handling permissions would be to add scopes following the pattern on Jupyter-Server. The idea would be to define what level of permission needs every of the critical UI actions in the frontend based on the level of permission that https://github.com/jupyter-server/jupyter_server/pull/165 introduces for each resource.

In my opinion, a good start would be to follow this table, posted by @davidbrochart [here](https://github.com/jupyter-server/jupyter_server/pull/165#issuecomment-856633819) which summarizes the permission of each resource in the server:
![image](https://user-images.githubusercontent.com/26092748/146157424-a7758888-21f1-4edc-b912-3c4e79f22426.png)

Regarding the list of tasks, I would add:

- The https://github.com/jupyter-server/jupyter_server/issues/638
- An endpoint in Jupyter-Server to request a list of users with permission to access the server.
- An endpoint in Jupyter-Server to grant permissions to other users
- A UI in JupyterHub and JupyterLab to grant permissions to other users to access the server.

I think it is important to grant permissions to other users from Jupyter-Server because this way we can create a widget in JupyterLab to create and share a link to other users, a la google docs. This is more intuitive and convenient than going to JupyterHub to generate the link in most situations.

Another use case would be deploying JupyterLab without JupyterHub, having another identity/authorization provider that doesn't serve multiple servers for multiple users. Instead, there is only one server, but the user can still create and share a token from JupyterLab, and see who has permission to access it.

**Comment by minrk** [comment]
Yes, I agree with all of those tasks. I think it can be in two stages, though - making things work _assuming you have the permissions_ is a tangible, achievable goal with significant immediate benefit, while we work out how exactly to allow users to grant new permissions. This is a nontrivial amount of technical work at several levels, so there's plenty of frontend work to do while we work on that.

I agree that Jupyter Server should provide an abstraction for granting new share permissions, so that any authorization provider can implement that API and the Lab UI only needs to understand the Jupyter Server API for it.

Listing users who may have permissions is an interesting one - I hadn't thought of that, and it may prove tricky with JupyterHub as the authorization provider. What would that be for?

**Comment by jrmoserbaltimore** [comment]
I'd like to put in my view from an end-user perspective looking at JupyterLab use cases.

My use case is JupyterLab with single-user subdomains and DockerSpawner.  This specifically means no XSS and separate containerized environments for each single-user server—my goal is high security against users attacking other users.

Security considerations:

1. If any user can execute any code from any notebook, that user has remote code execution permissions on that single-user server and can be assumed to have all access.
2. If a user executes a notebook on *their* single-user server, they aren't able to execute code in the context of a different user.  (Guarantees might break down in less-segregated environments.)
3. There may be legal or policy reasons prohibiting the sharing of different information, such that a user may be on two projects, may have two separate notebooks for those projects, and may want to share them each with other users on the respective projects *but not with anyone else*.

## Execution Environment

The considerations (1) and (2) make it reasonable to allow a user to execute any notebook in the context of their own server:  if Alex has shared SensitiveNotebookA to Bobbie, Bobbie can run SensitiveNotebookA under Alex's single-user server without doing damage to Alex, but accepts the risk of Alex's code running on Bobbie's server.  The user executing the notebook takes the risks; the user sharing their notebook doesn't.

That line of thinking can go in various directions with different security implications (as I continuously think up ways to attack all of them) but I've decided this is not entirely interesting, as others here are likely more equipped to make decisions about all that.  At some point, it requires some user to take additional risk.

## Alternative by Segregation

Another option—a feature I wasn't sure about at first, but after a little more thought I've decided I would quite like—would be to execute in the context of a separate server entirely. That is something handled technically at the JupyterHub level, and I think a UI tweak to JupyterLab would simplify use of the existing named server feature.

Currently, JupyterLab has several tabs available along the left side for directory browsing, listing open tabs, and viewing the table of contents.  It would improve the user's workflow to also have a tab for named servers, if the feature is allowed by whatever JupyterLab manager (e.g. JupyterHub) is running.  Currently, this is a separate page in JupyterHub, and not as elegant as the JupyterLab UI.

When JupyterLab is configured to talk to JupyterHub and manage named servers, it would show this tab.  This would be a hierarchical layout, so could have Project1 which may be a server (which may also be a container) or may be a non-server container; and it may be a container, meaning that the user also has a server Project1→TeamA.  If using DockerSpawner, these are run in separate Docker containers (different definition of container…), achieving a high degree of isolation.  Giving a user access to Alex→Project1→TeamA does not give them access to Alex→Project1→TeamB; giving them access to Alex→Project1 does not give them access to Alex→Project1→TeamA, either.

It is an exercise for the reader to determine how to deal with hierarchical compartmentalization, e.g. Alex→Project1→TeamA vs Alex→Project1→TeamB being rendered as project1-teama-alex.jupyter.example.com or alex-project1-teama.jupyter.example.com and so forth, since you can't have multi-level subdomains.

Not sure how all that sounds to anyone else, and it doesn't replace per-resource permissions or other security features *within* a single-user server; but a smooth workflow to isolate separate projects fully into their own per-user named servers would make an *additional* layer of security easy and intuitive to the user.  Fewer clicks to access such a feature has a significant impact on user uptake, as it requires less training and less effort to use.

**Comment by fcollonval** [comment]
Closing this meta issue to more specific issues (already opened).
