### ISSUE TITLE
JupyterLab cannot display currently running servers.

### ISSUE THREAD

**Issue by liaomingg** [jupyterlab/jupyterlab#11491]
## Description
Is this a bug?
### jupyterlab==3.1.14 and 3.2.4
the different packages: jupyterlab and jupyterlab-server.

jupyerlab==3.2.4
![jupyterlab_bug2](https://user-images.githubusercontent.com/26960050/142343001-16194e73-ebb0-4c1a-8da0-396760071527.jpg)

jupyerlab==3.1.14
![jupyterlab_bug](https://user-images.githubusercontent.com/26960050/142341172-11f90c57-39a3-4dcf-8c63-e8d38b56fa38.jpg)

## jupyterlab==1.2.3 works.
jupyter-client         7.0.6
jupyter-core           4.8.1
jupyter-server         1.11.1
jupyterlab             1.2.3
jupyterlab-pygments    0.1.2
jupyterlab-server      1.0.9
![jupyterlab_works](https://user-images.githubusercontent.com/26960050/142341787-b09ad207-c542-40c3-8f18-dfa59eec33d7.jpg)

## Reproduce

$ pip install jupyterlab
$ jupyter-lab --allow-root --ip 0.0.0.0 --port 6008
$ jupyter notebook list

## Expected behavior

show the currently running servers: 
## Context

- Operating System and version: ubuntu16.04
- Browser and version: Chrome 95
- JupyterLab version: 3.1.14, 3.2.4

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Thanks for asking! This is not a bug but a result of the change in the underlying architecture. For JupyterLab 3.x and newer you should use `jupyter server list` instead of `jupyter notebook list`.

For more context please see [migrate from notebook](https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html#migrate-from-notebook) chapter of `jupyter-server` documentation and [this answer](https://stackoverflow.com/a/67804732/6646912).

**Comment by liaomingg** [comment]
Thanks！
