### ISSUE TITLE
ctrl+v pastes the copied content twice

### ISSUE THREAD

**Issue by ipozdeev** [jupyterlab/jupyterlab#11639]
## description
ctrl+c/ctrl+v leads to the copied content being pasted twice in markdown cells, as if ctrl+v is used twice. the problem only appears in `jupyter lab`, not in `jupyter notebook`...

## reproduce
1. run `jupyter lab`
2. copy anything, paste in a markdown cell
3. the paste is duplicated.

## context
JupyterLab v. 3.2.1
Firefox 95
Linux Mint 20.2

**Comment by davidbrochart** [comment]
Hi @ipozdeev, thanks for reporting the issue. I tried to reproduce locally, with JupyterLab 3.2.1 and Firefox 95 but Ubuntu 21.04, and didn't have the issue.
Do you have access to a different OS, to see if it's not related to Linux Mint?

**Comment by ipozdeev** [comment]
strange, can't reproduce myself. closing for now, i guess....

**Comment by cyaris** [comment]
I've been experiencing this issue as well.

**Comment by krassowski** [comment]
@cyaris could you please list the version of JupyterLab, browser, and operating system?

**Comment by cyaris** [comment]
Running exclusively within JupyterLab desktop application...

JupyterLab: 3.2.5-2
Chrome: 96.0.4664.110 (Official Build) (x86_64)
MacOs Big Sur: 11.6.2

**Comment by cyaris** [comment]
I have my own key binding for Command-V in another program. It seems that Jupyter is not overriding this, but running both. How can I disable the Jupyter Command-V paste?

**Comment by bsgreenb** [comment]
@cyaris I believe this may cover how to remove the shortcut.  https://github.com/microsoft/vscode-jupyter/issues/1732#issuecomment-659213526 I'm facing same issue and checking that out rn

**Comment by nthiery** [comment]
I can reproduce this behavior reproducibly in the following setup:
- Conda environment:
    ```
    name: test-lab
    
    channels:
    - conda-forge
    
    dependencies:
    - pip
    - pip:
      - jupyterlab>=4.0.0a16
    ```
- Python 3.10.6
- JupyterLab 4.0.0.a30 (behavior also observed on earlier 4.0 versions)
- Running on Linux Ubuntu 22.04
- firefox 106.0 and chromium

Steps to reproduce:
- create a new notebook
- create a markdown cell
- paste text with Ctrl-V in that cell
- the text is pasted twice, the seconde instance appearing with a tiny delay after the first one

I temporarily moved my .local directory to avoid interferences with local setups.

**Comment by nthiery** [comment]
The other day, we made our 300 students work on a Jupyter notebook
designed to teach them to use the keyboard rather than the mouse for
efficient edition. With this bug, we did not quite convince them :-)

**Comment by nthiery** [comment]
Presumably fixed by #13230; see #13206.

**Comment by krassowski** [comment]
Yes, that fix will be included in 4.0.0a31. Thank you for testing out the alpha version!

Regarding keyboard navigation, we recently had a collaborative event to review the keyboard navigation pitfals in Jupyter Notebook v7 alpha: https://github.com/isabela-pf/a11y-events/pull/10/ but we did not have one for JupyterLab recently. It would be amazing to hear if there was any other feedback on the JupyterLab 4.0 alpha (as we are approaching the beta stage).

**Comment by nthiery** [comment]
Will do. It was indeed bleeding edge to put the alpha version in production with hundreds
of users :-) We had to leap forward due to our extensive use of jupytext which was not
quite compatible with JupyterLab before 4.0.0.a27.

The good news, is that this is quite smooth: beyond what I have reported so far, keyboard
navigation seems fine. Where we have more trouble is with ensuring compatibility with the many
extensions that we use (ipylab, jupytext, nbgrader, ipywidgets, ...). I'll try to report something
exploitable about these.

**Comment by JulianSMoore** [comment]
@krassowski FYI I just encountered this again, on 1st use of jupyter lab after PC woken from sleep/hibernation in Chrome/ Win 10 (22H2)

This, like LSP no longer running, is fixed by F5 refresh.

**Comment by krassowski** [comment]
@JulianSMoore which version of JupyterLab?

**Comment by JulianSMoore** [comment]
> @JulianSMoore which version of JupyterLab?

Couldn't remember or find the magic for diagnsotics earlier, but info is:

(PYTFCurrent) C:\Users\Julian>conda list jupyter
# packages in environment at C:\Users\Julian\anaconda3\envs\PYTFCurrent:
#
# Name                    Version                   Build  Channel
jupyter-client            7.4.8                    pypi_0    pypi
jupyter-core              5.1.1                    pypi_0    pypi
jupyter-events            0.5.0                    pypi_0    pypi
jupyter-lsp               1.5.1                    pypi_0    pypi
jupyter-server            2.0.6                    pypi_0    pypi
jupyter-server-terminals  0.4.3                    pypi_0    pypi
jupyterlab                3.5.0                    pypi_0    pypi
jupyterlab-lsp            3.10.2                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.16.2                   pypi_0    pypi
jupyterlab-widgets        1.1.1                    pypi_0    pypi

HTH

(NB any interaction with ipympl? I had v8 installed but downgraded to ?7.7 per recommendation because plots were not appearing at all. Now it just cuts off legends outside the plot area, but that's a known issue apparently)

**Comment by ajfriend** [comment]
I've just run into this issue for the first time.

I'm using jupyterlab 3.6.1 on macOS 13.2.

Is there a fix for this in the 3.x branch?

**Comment by krassowski** [comment]
@ajfriend did you use "New View for Notebook" function?

**Comment by ajfriend** [comment]
> @ajfriend did you use "New View for Notebook" function?

No. Just tried again on a fresh virtual env. Still got the double paste without using "New View for Notebook".

**Comment by ajfriend** [comment]
@krassowski, I may have another clue. Reproduction is a little stochastic, but this is consistent enough that I think it is a real effect:

- I **do see** the issue when I install both `jupyterlab jupyterlab_execute_time`
- I **do not see** the issue when I install just `jupyterlab`

I'm installing in a fresh virtual env:

```sh
python -m venv env
env/bin/pip install --upgrade pip setuptools
env/bin/pip install jupyterlab jupyterlab_execute_time
```

I'm using Python 3.9.7

**Comment by zhaowb** [comment]
Just to mention, when the markdown cell is having the duplicated paste, changing it to code type cell then change it back to markdown seems can fix the problem.

I'm not sure what's causing the problem. I have `jupyterlab_execute_time` installed like @ajfriend has mentioned. I also see the problem goes away after disabled the plugin by set `'enabled': false` in user preferences, then enable it makes the problem comes back. But it's not stable reproduce. Sometimes it takes to refresh lab page, sometimes it doesn't. Also I'm wondering if any other plugin may have similar situation.

**Comment by castorfou** [comment]
I have upgraded to 3.6.1 and I still have the issue.

I use `jupyterlab_execute_time`. 

> Just to mention, when the markdown cell is having the duplicated paste, changing it to code type cell then change it back to markdown seems can fix the problem.

nice workaround, thank you
