### ISSUE TITLE
Switching from user extension to user service

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#11678]
### Problem

In https://github.com/jupyterlab/jupyterlab/pull/11443, a new package for handling user information was created. At the beginning that PR was also proposing to give access to user permission (as read-only). It was pointed out that this is dangerous as if the extension is replace by malicious code, the user permission can be tampered.

The sole source of truth of user identity and permissions should come from the server.

### Proposed Solution

As discussed in https://github.com/jupyter-server/jupyter_server/issues/638, the Jupyter server needs to get a proper identity API. That should be the source of truth for the user identity and permissions. And we should reconsider the user package as a new service and not use extension and token mechanism to provide access to that information.

**Comment by fcollonval** [comment]
cc @hbcarlos

**Comment by jtpio** [comment]
> As discussed in [jupyter-server/jupyter_server#638](https://github.com/jupyter-server/jupyter_server/issues/638), the Jupyter server needs to get a proper identity API. That should be the source of truth for the user identity and permissions. And we should reconsider the user package as a new service and not use extension and token mechanism to provide access to that information.

This sounds like adding a new service to the `ServiceManager.IManagers` interface? 

https://github.com/jupyterlab/jupyterlab/blob/091cc6ed9712cbd14731892384be1c5155f335eb/packages/services/src/manager.ts#L218-L272

**Comment by fcollonval** [comment]
> This sounds like adding a new service to the `ServiceManager.IManagers` interface?

I think so. But we probably have to wait for identity API to make it to figure out how to move forward.

**Comment by hbcarlos** [comment]
> I think so. But we probably have to wait for identity API to make it to figure out how to move forward.

The user information should come from the server. The idea of the ICurrentUser was to act as a placeholder until we can fetch the data from jupyter-server/jupyter_server#638.

If it is better to have the ICurrentUser as a service instead of its package, maybe we could create a mock service already. We don't need to release a JupyterLab 4.0 beta (or even the final version while waiting for the Identity API) with the ICurrentUser plugin.

The idea would be to have something like the `MockProvider` used in the document provider package when the RTC is deactivated. In this case, we could implement the functionality of the ICurrentUser in this mock service.

https://github.com/jupyterlab/jupyterlab/blob/a783add538f2fcd10ab4481fa5afd209c4d602c4/packages/docprovider/src/mock.ts#L3-L22

**Comment by ellisonbg** [comment]
Because Jupyter (as its main feature) allows arbitrary code execution in both the frontend or backend, a server extension is just as likely to be overridden or hacked by an attacker as a frontend extension. In particular, with JupyterLab 3, both server and JupyterLab extensions are just pip/conda packages, so this "attack" is as simple as a user opening a terminal and using `pip/conda install` to install a replacement. Thus, I don't think that it is inherently more secure for this to be handled by the server.

At the same time, I do think that in some deployments it will make sense for it to be handled by the server. However, the frontend `ICurrentUser` plugin will be useful for other deployments. Put another way - JupyterLab is deployed in a diverse set a contexts and situations which may require the customization of identity either in the server, frontend, or both. 

Based on this my recommendation would be for us to have a customizable `ICurrentUser` plugin in the frontend (we already have that) and a customization server-side service and to have the default implementation of `ICurrentUser` in the frontend get its information by calling the server-side service.

Once usage case that likely requires the frontend extension is a proxy based deployment (similar to JupyterHub) but where all auth (athentication and authorization) is done by the proxy, without coordination with or modification of the JupyterServer. This is common when you want to avoid putting auth logic on the server where the user (through arbitrary code execution) can hack it as described above.

**Comment by fcollonval** [comment]
The idea here is not to bring the feature from a server extension. But to acknowledge that this is not an extension but a feature provided by the jupyter server (as it will be when the identity API lands). So this can't be replaced (like for the kernel API for example). Moreover a server extension is not hot loaded (at least in the current status). So the attack you are mentioning is not possible as the server handlers are already in memory and can't be replaced by freshly corrupted package.

The only secure path to handle authentication and authorization is to have them provided by the server (trying to get them from the front end will likely be hard as requests to third-party identity providers will likely be forbidden due to CORS policy).

So I do support the pattern of customized server-side service (although not in the sense of customized interfaces between jupyter server and the front end but more in the sense of JupyterHub authenticator Python API). But I'm definitely not in favor of a plugin providing the identity and authorization on the frontend that (on the opposite of a server extension and as you mentioned in https://github.com/jupyterlab/jupyterlab/pull/11443#discussion_r761468868) can be easily replaced. It should be a non-customizable API like for contents or kernel handling. But the attributes provided will vary depending on the server-side provider customization (as JupyterHub is doing).

**Comment by echarles** [comment]
Building on what exists for now, interactions with the server for the content, kernel, trust, debugger... is done via the services which are not extensible as willing to enforce and respect a well-defined protocol. The security aspect (Authentication and Authorisation) sound like fitting that pattern where we want control.

On the other hand, I can imagine use cases where an extension developer is willing to customize in some way the display of the users. There are already a case https://github.com/jupyterlab/jupyterlab/issues/11657 where we are discussing about family name... If the server relies on an external auth (e.g GitHub auth), the user has very custom attributes that JupyterLab will want to display.

I had hard time recently having to deal with a very strict service interface for the debugger where I could not extend it to transit custom control messages https://github.com/jupyterlab/jupyterlab/pull/11285#issuecomment-990974096

So even if Auth resides at the end in services, how can an extension author benefit from custom user attributes. Should the model be extensible? Should services evolve to support some controlled way of extensibility?

**Comment by fcollonval** [comment]
> Should the model be extensible? Should services evolve to support some controlled way of extensibility?

That is where I'm uncertain. Is it controlled extensibility or generic server request API.

For authorization, it sounds that a generic call like:

```ts
isAuthorized(payload: IAuthorizationRequest): Promise<boolean>;

interface IAuthorizationRequest {
  // mandatory
  attributeA: typeA,
  attributeB: typeB
  // Extension may pass additional attributes to be understood by the customized authenticator/authorization layer on the server
}

getPermissions(): Promise<IPermissions>;

interface IPermissions {
  // some default attributes
  // + some customized one
}
```

will get us covered. For example if an extension adds a new type of resources, this should be transparent. In its extension, the author will be able to cast the interface to its real type.

But for the debugger case mentioned, from a quick look, generic API `createMessage` and `sendControlMessage` are already in place. So I presume the blocker was the check of the variable type? If so we should definitely relax some type constrains. It will be up to the backend to deal with unknown payload. Would that be enough for that example?

**Comment by echarles** [comment]
Authorization is indeed a good case to be generic, request has custom attributes, answer is true/false (well the answer maybe a bit more evolved, it could be `yes, but only for 5 minutes`).

>  So I presume the blocker was the check of the variable type? 

Exactly, for resource usage case (I said debugger because for now the control channel is only for debug messages, but it sould not), it is a matter of request/reply type. The method is there and is ok. So yes, relaxing the request/reply type will cover the resource usage case.

For Authentication, IMHO the methods should be strict and well defined, but the object types should be flexible. I like having such API in the services, but for now, the services are too strict. This can be changed.

**Comment by fcollonval** [comment]
Is there an opened issue in which we could list what needs to be done (this will definitely be a great addition for v4 maybe even for v3.3 for some relaxation)?

**Comment by echarles** [comment]
I have opened https://github.com/jupyterlab/jupyterlab/issues/11713 to discuss the feasibility of more extensible services.

**Comment by ellisonbg** [comment]
I feel like I am missing something in this discussion. We already know that JupyterLab gets deployed in dozens of different configurations, with instances, supercomputers, containers, different auth and identity services and protocols, as a single server, with JupyterHub and as a component in other JupyterHub like system. Thus, I don't understand statements above like "this can't be replaced", which implies that JupyterLab will enforce one and only way of handling all of these things. How can the identity layer not be extensible in a rather flexible way, both in the frontend and backend.

**Comment by fcollonval** [comment]
> How can the identity layer not be extensible in a rather flexible way, both in the frontend and backend.

It will be. The only constrain we have to set is how the frontend gets the information from the backend without the ability to change the how (for security reasons). The flexibility being on the what (what information is obtained from the frontend to the backend).

![image](https://user-images.githubusercontent.com/8435071/146741775-8ef9cf37-f0da-4e9b-99f0-c2e30788a66f.png)

The box `User service` is a constrain but the identity object should fulfilled only a small interface (like displayed name) but could contain much more. And the permissions, will need to respect some format (because some will be used in core to for example tune the UI for read only or read/write-no-execution). But it will basically be some kind of mapping: `{<resource>: <scope>[]}` as mentioned in https://github.com/jupyter-server/jupyter_server/issues/638. We can do a parallel with the contents API. One can define its own content manager on the backend and server any kind of file to be interpreted by an appropriate viewer. But you cannot temper with how to get access to the file from the frontend.

Do I miss some flexibility needs on the frontend?
