### ISSUE TITLE
Simple mode by default

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#11735]
### Problem

Simple mode gives users a notebook like experience with lab features. Some users prefer this and would like to always use simple mode. Can we have a setting which defaults new workspaces? E.g. https://my-instance.example.com/lab/workspaces/auto-Z?reset starts in simple mode.

### Proposed Solution

Add a new user setting that allows a user to default to simple mode.

**Comment by jtpio** [comment]
Thanks @mlucool for the suggestion.

At the moment one way to default to simple mode at startup is to redirect users to the `/doc` endpoint. Maybe that's good enough in most cases.

Otherwise there could indeed be a setting that would be activated on startup, and trigger the switch to single mode if users land on `/lab`.
