### ISSUE TITLE
Toggle Palette with Keyboard shortcut (i.e. hide)

### ISSUE THREAD

**Issue by verginer** [jupyterlab/jupyterlab#1173]
I have noticed that when I summon the palette (i.e. press `cmd+shift+p`) doing the same again won't hide it.
However toggling works with the  the Files pane (i.e. `cmd+shift+f` toggles it).
In the notebook interface hiding the palette is possible by pressing `<Esc>`.
Would it be possible to implement either Esc or the palette shortcut to hide the palette again?

**Comment by jasongrout** [comment]
Thanks. There's already a discussion of the matter on #277 (still open...), so let's continue the discussion there.

**Comment by jasongrout** [comment]
A short answer is that it will definitely be possible, especially when we have custom keyboard shortcuts. However, I think your question is about the default keybindings, which is what #277 is also about. The question is about having a good interaction - we used to have escape hide it, but found that it was rather unpredictable because often the palette wouldn't be focused after running a command, for example.
