### ISSUE TITLE
Don't bump version for @jupyterlab/rendermime-interfaces

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#11748]
## Description

The JS packages version bump to v4 is probably to severe. In particular, the rendermime interfaces did not change. And that package is very likely to be used by numerous downstream extensions. It would be good to not bump it.

> The bump occured because it explicitly depends on @jupyterlab/translation. We should probably cut that dependency (as I think the idea was to have this package provide a long-term stable API) as this is done for all the other interfaces (like `ISanitizer`, `IRenderMime`, ...). And we should depends on this package in the other ones to ensure we are not breaking those stable interfaces (for now we do not check if we break or not the interfaces copied in `rendermime-interfaces`...).

## Expected behavior

We should be able to install extension like plotly that provides a rendermime extension on JupyterLab v4 without requiring an update of the extension.

**Comment by jtpio** [comment]
Thanks @fcollonval for spotting this.

For reference the bump was done in https://github.com/jupyterlab/jupyterlab/pull/11537.

> We should probably cut that dependency

Ideally yes, although in practice not sure it will be feasible? Since the translator is part of the interface here:

https://github.com/jupyterlab/jupyterlab/blob/9ad40ceed4f74470f2ea1d99f12c883f8d460a16/packages/rendermime-interfaces/src/index.ts#L274-L277

And removing it would mean breaking the interface, which would need a major version bump.
