### ISSUE TITLE
JupyterLab takes seconds to execute simple code -- It's too SLOW

### ISSUE THREAD

**Issue by KaneGreen** [jupyterlab/jupyterlab#11811]
## Description
My JupyterLab is very slow to execute code, even very simple code (e.g. evaluating 1+1).
It's not that the code itself is slow: it seems that JupyterLab is very slow in other ways.
For this issue I will upload a video, as you can see from the video:
1. Basic mathematical calculations cannot display the result immediately, and it takes at least 1 second.
2. Timeit shows that mathematical computations themselves are fast.

Miscellaneous: 1. Both python.exe and ipython.exe are responsive when used directly in the terminal.
2. Using jupyter-notebook also responds quickly.
3. My CPU is AMD 3700X, it can't be that slow. 

### Video
https://user-images.githubusercontent.com/20700283/148743325-85aa0fd5-b4f9-4a5d-97af-65d51fa36491.mp4
(4K resolution, 75 seconds, about 59MiB)

## Reproduce
1. Installing Anaconda3 on Windows.
2. Creating an environment and install jupyterlab (e.g. `conda create -n testenv jupyterlab`)
3. Activating the environment (e.g. `conda activate testenv`)
4. Starting the JupyterLab (e.g. `jupyter-lab.exe`)

## Expected behavior
It should be faster.

## Context
- Operating System and version: Windows 10 21H2
- Browser and version: Chrome 97.0 and Firefox 95.0.2
- JupyterLab version: 3.2.1
- Python version: 3.9.7

----
Update:
My package versions:
```
ipykernel                 6.4.1
ipython                   7.29.0
ipython_genutils          0.2.0
jupyter_core              4.9.1
jupyter_server            1.4.1
jupyterlab                3.2.1
jupyterlab_pygments       0.1.2
jupyterlab_server         2.10.2
nbclassic                 0.2.6
nbclient                  0.5.3
nbconvert                 6.1.0
nbformat                  5.1.3
python                    3.9.7
```

<details><summary>Command Line Output</summary>
<pre>
[D 2022-01-10 17:20:18.819 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'nbclassic': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2022-01-10 17:20:18.820 ServerApp] jupyterlab | extension was successfully linked.
[D 2022-01-10 17:20:18.827 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'nbclassic': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[W 2022-01-10 17:20:18.832 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance expected an int, not the NoneType None.
[D 2022-01-10 17:20:18.833 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'nbclassic': True}>}}
[D 2022-01-10 17:20:18.833 ServerApp] Ignoring min_open_files_limit because the limit cannot be adjusted (for example, on Windows)
[I 2022-01-10 17:20:18.863 LabApp] JupyterLab extension loaded from C:\ProgramData\Anaconda3\envs\testenv\lib\site-packages\jupyterlab
[I 2022-01-10 17:20:18.863 LabApp] JupyterLab application directory is C:\ProgramData\Anaconda3\envs\testenv\share\jupyter\lab
[I 2022-01-10 17:20:18.866 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-01-10 17:20:19.072 ServerApp] nbclassic | extension was successfully loaded.
</pre>
</details>

**Comment by KaneGreen** [comment]
Further testing shows that it seems to be related to the `jupyter_client` package:
- `conda create -n testenv jupyterlab jupyter_client=6.1.12` and `conda create -n testenv jupyterlab jupyter_client=7.0.6` both work fine (response quickly).
- But the latest `7.1.0` version has issues (slow).

But I don't know why.

**Comment by jweill-aws** [comment]
Another possibly related complaint from today on the forum: https://discourse.jupyter.org/t/jupyterlab-substaintially-slower-than-jupyter-notebook/3548/5

**Comment by KaneGreen** [comment]
> Recent performance complaints on the forum:
> 
> * https://discourse.jupyter.org/t/jupyterlab-substaintially-slower-than-jupyter-notebook/3548/5
> * https://discourse.jupyter.org/t/cripplingly-slow-ui-am-i-the-only-one/5351/35?u=jweill-aws

The performance drop in this issue is a recent one. I speculate that it might be different from the previous performance drop.

**Comment by kevin-bates** [comment]
(Sorry, I just realized after typing most of this, that I'm not on the jupyter_client issue: https://github.com/jupyter/jupyter_client/issues/735)

Thanks @jweill-aws - this is helpful.  While "lags" can happen for any number of reasons, the recent posts - both of which state or imply lab versions >= 3.2.1 are potentially good data points.

About all we know (or strongly believe) is:
- a relation to jupyter_client 7.1.0: 
    This version introduces pending kernel support, but that was implemented to be opt-in and disabled by default and I don't suspect `--AsyncMappingKernelManager.use_pending_kernels=True` is being specified.  It's also strange that the problem is more in regards to cell execution response time while the pending kernel feature is only about the kernel's lifecycle management.  That said, there's still a strong connection to jupyter_client 7.1.0, so we should retain that.

- Notebook doesn't have the same issue when used with juptyer_client 7.1.0
   This is interesting since its plumbing is quite similar to jupyter server's, although doesn't have pending kernel changes (although server's are not in use).

- Was originally reported on Windows, but the forum links imply it may be on other platforms (if they're the same issue), so I don't think we have enough to say that it's platform-specific.

- I'm not finding it reproducible in any form (MacBook pro).

One thing we haven't checked are the versions of IPython and IPykernel.  Since this feels like a message-based issue, those versions should be included, although I'm assuming they have not been "swapped out" in the various version tests - so probably not an issue - but good to know.

Another thing to do is enable debug logging by starting the lab server using: `jupyter lab --debug`.  Then carefully look for the following log statements with executing the cell `1+1`:
When the cell is submitted for execution, you should see two lines like the following:
```
[D 2022-01-11 07:44:43.751 ServerApp] activity on 7dcd0953-d1c8-4e9f-a208-ba7f9ae7aa23: status (busy)
[D 2022-01-11 07:44:43.753 ServerApp] activity on 7dcd0953-d1c8-4e9f-a208-ba7f9ae7aa23: execute_input
```
indicating the kernel has received the cell.  Upon its completion, you should see two more lines like the following:
```
[D 2022-01-11 07:44:46.754 ServerApp] activity on 7dcd0953-d1c8-4e9f-a208-ba7f9ae7aa23: execute_result
[D 2022-01-11 07:44:46.755 ServerApp] activity on 7dcd0953-d1c8-4e9f-a208-ba7f9ae7aa23: status (idle)
```
indicated the kernel has sent the result and is waiting for more work.

In my test above, I happened to include `time.sleep(3)` - so you'll notice the time differences.

If we see sub-second time differences, then the delay is likely not the result of messaging within the server.  For example, here are my logging results for `1+1` without the forced delay:
```
[D 2022-01-11 08:03:46.586 ServerApp] activity on 4ccdbea0-adb5-42dc-8ee5-7244f8c0323b: status (busy)
[D 2022-01-11 08:03:46.611 ServerApp] activity on 4ccdbea0-adb5-42dc-8ee5-7244f8c0323b: execute_input
[D 2022-01-11 08:03:46.613 ServerApp] activity on 4ccdbea0-adb5-42dc-8ee5-7244f8c0323b: execute_result
[D 2022-01-11 08:03:46.625 ServerApp] activity on 4ccdbea0-adb5-42dc-8ee5-7244f8c0323b: status (idle)
```
I suspect something, somehow, somewhere is holding up the cell's send or the response but perhaps the `--debug` test will provide more information.  

**Lab devs**: can any debug logging be enabled on the client-side where we might be able to correlate those with the server's timestamps to better determine where the delay might originate?

**Comment by KaneGreen** [comment]
My ipython version:
```
ipykernel                 6.4.1
ipython                   7.29.0
ipython_genutils          0.2.0
```
  
I need more time to test with the `--debug` option.

**Comment by KaneGreen** [comment]
When `jupyter_client=7.0.6`, the time interval between `execute_result` and `status (idle)` is only a few milliseconds.
```
[D 2022-01-12 09:07:54.359 ServerApp] activity on c9539a74-bf0e-42c5-95c9-debfc7cfe545: status (busy)
[D 2022-01-12 09:07:54.359 ServerApp] activity on c9539a74-bf0e-42c5-95c9-debfc7cfe545: execute_input
[D 2022-01-12 09:07:54.361 ServerApp] activity on c9539a74-bf0e-42c5-95c9-debfc7cfe545: execute_result
[D 2022-01-12 09:07:54.370 ServerApp] activity on c9539a74-bf0e-42c5-95c9-debfc7cfe545: status (idle)
```

When `jupyter_client=7.1.0`, the time interval between `execute_result` and `status (idle)` reaches nearly 3000ms.
```
[D 2022-01-12 09:11:55.314 ServerApp] activity on bcd5b8ea-c418-422c-8804-3131d80196b8: status (busy)
[D 2022-01-12 09:11:55.315 ServerApp] activity on bcd5b8ea-c418-422c-8804-3131d80196b8: execute_input
[D 2022-01-12 09:11:55.316 ServerApp] activity on bcd5b8ea-c418-422c-8804-3131d80196b8: execute_result
[D 2022-01-12 09:11:58.314 ServerApp] activity on bcd5b8ea-c418-422c-8804-3131d80196b8: status (idle)
```

**Comment by kevin-bates** [comment]
Thanks @KaneGreen - this is interesting (and helpful).  Sorry for the delay (meetings and noodling).

This logging is produced by the [activity watching in server](https://github.com/jupyter-server/jupyter_server/blob/6b57dab450ae611b5901429db46687d7a890992d/jupyter_server/services/kernels/kernelmanager.py#L494-L527) - which is used to determine the _cullability_ of a kernel (when enabled for culling) - and hooks the `on_recv` callback for the `iopub` channel.

I believe this is showing that the delay is occurring between the time the kernel sends the execution result and announces it's back in an idle state.  Since both ipykernel and IPython depend on jupyter_client, they too are candidates for this exercise of determining where this issue originates.  

An **ideal test** would be to run the kernel in a _different_ python environment than what the server is running and use a jupyter_client version < 7.1 in that environment.  If we don't see the issue then this implies the delay is on the kernel side, and we should flip the two jupyter_client versions (in the kernel and server envs) to confirm the issue **does** occur.  If the polarity of the results are flipped, then the issue is likely _server-side_.

The easiest way to ensure the ipykernel process executes in a different env is to install [`nb_conda_kernels`](https://github.com/Anaconda-Platform/nb_conda_kernels).  This exposes a kernel relative to each conda env and activates that env prior to launching the kernel.  This can be a little difficult to remove because its installation installs/updates configuration that enables an override of the `KernelSpecManager` so that it can inject this kind of logic.

Another approach (I just confirmed) is to locate the applicable `kernel.json` file and make the following edits.
- Fully qualify the path the `python` executable that resides in the _other_ env. 
- Include or extend the `env` stanza to prefix the existing PATH with the `bin` directory of the _other_ env.
Here, my _other_ env is located in `/opt/anaconda3/envs/py3.9-dev` so I reference that `bin` directory in each updated entry:
```json
{
 "argv": [
  "/opt/anaconda3/envs/py3.9-dev/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "env": {
   "PATH": "/opt/anaconda3/envs/py3.9-dev/bin:${PATH}"
 },
 "display_name": "Python 3 (3.9)",
 "language": "python"
}
```
I also suggest tweaking the `display_name` entry so, when viewed from lab, you know you're picking up the updated kernel specification.

The location of the applicable `kernel.json` file can be determined by running `jupyter kernelspec list`, locating the kernel name on the left, and editing the `kernel.json` file located in the corresponding directory on the right.

(I'm hoping the Windows-equivalent steps are easily determined should there be any platform-specific items here.)

**Comment by KaneGreen** [comment]
Sorry, I can't seem to follow the steps you describe. (My current work is dependent on already installed environments, I don't want to mess them up for now)

As far as I'm testing now, I've created multiple conda envs, using the `jupyter_client=7.1.0` and `jupyter_client=7.0.6` versions at the time of creation (the versions of other packages are not specified). As of the current time, even if the version of `jupyter_client` is different, the version numbers of packages such as `ipython` and `jupyter_server` in different environments are **the same** (as shown at the beginning of this issue).

Under these circumstances:
conda env | jupyter-lab.exe | jupyter-notebook.exe | ipython.exe
----|----|----|----
`jupyter_client=7.1.0` | ❌ delay | ✔ good | ✔ good
`jupyter_client=7.0.6` | ✔ good | ✔ good | ✔ good

Thus, this delay **only** occurrs on jupyter-lab.exe on Windows.

**Comment by kevin-bates** [comment]
Thanks for the update @Kane.  I see you've added a row to the table in a recent edit - thank you.  I don't think it mimics the scenario I'm trying to test - where the server is running on one conda env and the kernel is running in a second.  The reason I say that is because the path to the kernel spec for the second entry is buried in the conda env instead of in a shared area so this spec wouldn't be found if the server is in another env.  (Yes, this is complicated and you are not expected to follow what I'm getting at here.) 

At any rate, when I asked for the split env tests, it hadn't occurred to me that the Notebook behavior is essentially an example of that since it too uses the same ipykernel version.  As a result, I suspect the delay is on the _server-side_ and only when jupyter_server and Lab are in play -  so the issue could be in any of those 3 packages.

As @vidartf mentioned on https://github.com/jupyter/jupyter_client/issues/735, especially given that he can't reproduce this on Windows, I agree we need to analyze your env's packages.  

Let's move this discussion back over to https://github.com/jupyter/jupyter_client/issues/735 for now.

**Comment by kevin-bates** [comment]
All indications are this wound up being related to an update in juptyer_server 1.8 to prefer the SelectorEventLoop on Windows: https://github.com/jupyter/jupyter_client/issues/735#issuecomment-1017987224 where previous server versions with python 3.8+ would exhibit the issue.

Special thanks to @KaneGreen for the great help in obtaining information and @vidartf for spending the time to reproduce the issue and narrow the problem to a sensible explanation.

This issue can be closed.  Should something come up, we'll re-open the sibling issue (unless of course that _something_ has strong Lab-only implications :smile: ).
