### ISSUE TITLE
Plotly support in JupyterLab

### ISSUE THREAD

**Issue by tc0312** [jupyterlab/jupyterlab#1188]
Plotly uses AMD to inject its javascript library to the browser from the kernel: [code](https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L159)

This's not working in JupyterLab right now because lab.html doesn't load require.js.

**Comment by jasongrout** [comment]
Thanks for opening the issue. There are two issues here: plotly support, and having require.js in the global namespace by default. I think Plotly support should be done through a plugin that wraps the plotly javascript library, if possible, much like the [jupyterlab_vega](https://github.com/altair-viz/jupyterlab_vega) project provides rendering support for vega graphs. 

As for require.js in the page by default: in this case, I think it was needed because the extension mechanism for the classic notebook is pretty terrible, making it so that you basically have to have this mixing of javascript and python code and javascript code injection. Making the extensions work well to have a clean separation between kernel and frontend was a design goal for JupyterLab. I think we should not make requirejs available by default on the page in JupyterLab, and encourage and help people to port extensions over to the new plugin system. Of course, someone could make a plugin that loads requirejs into the global page context, but we should encourage cleaner ways of extending Lab.

**Comment by sccolbert** [comment]
:-1: for putting `requirejs` on the page by default. We talked about this when making the current plugin/bundler system, and decided it would be better to hide the details about how plugins are actually bundled/loaded. We currently do this by have the jlab extension builder, which completely abstracts away the fact that we are using webpack with a custom loader plugin under the hood. This separation will allow us to transition to a different loader in the future (like HTTP2) without requiring extension authors to rewrite any code. Exposing `requirejs` by default will lock us into that loader in perpetuity.

**Comment by rgbkrk** [comment]
nteract has a [plotly renderer](https://github.com/nteract/nteract/blob/0f14082c6e98bbc86a54ea1d3c33d655b1f252f2/src/notebook/components/transforms/plotly.js) that relies on the [Plotly JSON Chart Schema](http://help.plot.ly/json-chart-schema/) with mimetype `application/vnd.plotly.v1+json`.

/cc @chriddyp

**Comment by tc0312** [comment]
Just took a look at [Plotly JSON Chart Schema](http://help.plot.ly/json-chart-schema/).
We are actually trying to port [autovizwidget](https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget), a visualization library that uses Plotly, to JupyterLab. It consumes table but not chart. Users can select different chart types in the UI.

![Screenshot](https://github.com/jupyter-incubator/sparkmagic/raw/master/screenshots/autoviz.png)

**Comment by rgbkrk** [comment]
As you create charts, you're implicitly creating the format for Plotly JSON (their whole goal is serialization across languages even if it's not apparent as you work with Plotly.js).

In a chain, you're roughly looking at:

```
DataFrame --> User Selections --> Plotly JSON --> Rendered Plot
```

I realize it's not that simple because of how the widgets are constructed. However, one way of thinking on the plot view inside the widget is that it can use the plotly mimetype (assuming it's built in). @jasongrout can probably chime in more on approaches there.

**Comment by jasongrout** [comment]
If you don't need two-way communication, it's simpler to implement this as a table renderer in the rendering system, rather than an ipywidget. We should support the ability for the user to pick, at or even after render time, which renderer they want. (Perhaps tabs, or a right-click menu, could let the user pick the renderer for a particular mimebundle).

**Comment by tc0312** [comment]
I think adding a renderer for a table mime type is the way to go.
In the renderer, it requires user inputs like selecting the x/y columns and chart type.
If renderer can't persist these data into the notebook file, users have to re-specify these every time they reload the notebook
 Should we allow renderer to persist states?

**Comment by blink1073** [comment]
Yes, we have a mechanism for a renderer to update its own mime bundle: https://github.com/jupyterlab/jupyterlab/blob/afb440bf2b62bdee57db5c6d662ca8677798031e/src/rendermime/index.ts#L289.

**Comment by ellisonbg** [comment]
@gnestor also has a jupyterlab extension for rendering plotly:

https://github.com/gnestor/jupyterlab_plotly

Closing this as no action for now, please feel free to re-open if needed. We are also working on better table rendering in #1194
