### ISSUE TITLE
R documentation not working with R version 4.1.1 or above

### ISSUE THREAD

**Issue by roks531** [jupyterlab/jupyterlab#11957]
After updating R version from 4.1.0 to 4.1.1 or 4.1.2 **R documentation in jupyterlab, is not working anymore** regardless of system (tested on multiple computers using Manjaro linux, kernel 5.16 or Linux mint, kernel 5.4). Tested on jupyterlab version 3.2.8 and lower.

When looking for R documentation in "Show contextual help" with ctrl+i, only the function definition is shown (below an example of the paste0 function):
![Screenshot_2022-01-28_13-55-35](https://user-images.githubusercontent.com/51192277/151551193-af709ad6-022c-45a0-ab11-859211a027d6.jpg)

Expected behaviour and working before R version 4.1.1:
![Screenshot_2022-01-28_13-55-22](https://user-images.githubusercontent.com/51192277/151551289-2386891f-b3de-4cfe-871b-81eb03a0ecb8.png)

R doumentation is working as expected in R studio.

The solution is to downgrade R version to 4.1.0, but that isn't really a solution as it breaks multiple other packages for me if I don't want to downgrade them as well.

**Comment by krassowski** [comment]
Thank you for opening this issue. It has very likely to do with a specific R kernel that you are using (because the the contextual help is generated by the kernel and clients like JupyterLab just display it as-is) and not with JupyterLab at all, unless you can verify that it works well in another Jupyter frontend (like Jupyter Notebook) but not in JupyterLab (which is very unlikely, but still a possibility).

Which R kernel and version of the kernel are you using? Have you reported this issue to the maintainers of that kernel?

The most popular R kernel is https://github.com/IRkernel/IRkernel, but there are others too like https://github.com/JuniperKernel/JuniperKernel.

**Comment by roks531** [comment]
Thank you for the fast answer! You were totally right, it was the problem of IRkernel which I had installed from R using CRAN. I checked, and it was version 1.3 and the one on github was 1.3.0.9, so this solves the issue...

Thanks again.
