### ISSUE TITLE
right click may not work in Chrome 55

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#1196]
https://www.chromestatus.com/feature/5663174342737920

It looks like in Chrome 55:
> "click" event will no longer be dispatched for non-primary buttons.

This may affect the right click menus available. It looks like we'll need to use the (nonstandard?) auxclick event.

Setting as Needs Info, since we'll need to confirm this.

**Comment by tomnomnom** [comment]
I think I might be currently experiencing the effects of this problem under Chrome 55/current and 56/beta; I'm not having any problems under Chrome 54 which I've just re-installed.

I'm running Ubuntu 16.04 and using the [goomwwm](https://github.com/seanpringle/goomwwm) window manager.

The effects I've noticed so far are: 

* right click menus don't appear
* HTML select dropdowns don't appear when clicked
* The Chrome 'three dot' menu doesn't appear when clicked

I'm not 100% sure the last two effects are related as they are left-click actions, but it feels like too much of a coincidence to not mention them.

I've disabled all extensions, and hardware acceleration too (some Googling suggested those as fixes to a similar problem in older versions so I thought it prudent to try them just in case).

The problem doesn't seem to present itself when using Unity rather than goomwwm.

Are there any logging options or other checks I could do to provide you with more information?

**Comment by blink1073** [comment]
Hi @tomnomnom, most of us are on holiday this week, but it does sound like the first problem is due to the change @jasongrout highlighted.  I suspect can work around this by adding an `auxclick` event handler or by using `mouseup`.  As for the other problems, does the dropdown on this site work for you?  http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by tomnomnom** [comment]
@blink1073 completely understandable! No rush :) I just saw the 'Needs Info' label and thought I might be able to help out.

Nope, that dropdown doesn't work for me under Chrome 55.

I've taken a quick video of what's happening: https://youtu.be/RAbwbWssGFw

VLC doesn't seem to want to record my mouse pointer so it's a little difficult to follow, so in sequence:

1. [00:00] Showing the `chrome://version` page
2. [00:08] Clicking the `<select>` dropdown in the linked page (watch for it flashing slightly)
3. [00:18] Right clicking on the webpage (watch for the title/top bar flashing slightly on each click)
4. [00:23] Clicking the 'three dots' menu (watch for the click animation happening)

Hope that's of some use. Let me know if there's any more info I can provide.

**Comment by blink1073** [comment]
@tomnomnom, thanks for taking the time to make a video, top notch bug reporting!  Unfortunately it looks like the right click part is the only thing we can help you with from the Jupyter end.  I suspect we may end up installing Chrome 55 just for the right click fix and then reverting based on that video ;).  Happy new year in advance!

**Comment by blink1073** [comment]
I am tested using the latest Chrome (55.0.2883.95) on OSX, Ubuntu and Windows, and right click is working without modifications to our click handlers.

**Comment by landsman** [comment]
I have same problem in "Verze 55.0.2883.95 (64-bit)" on last OSX :-(

**Comment by blink1073** [comment]
Hi @landsman, to be clear, right clicking on a file browser item intermittently does not bring up a context menu?

**Comment by ScarletMcLearn** [comment]
same here.
i click right click. 
doesn't respond to my clicks.
after several clicks it comes.

**Comment by jasongrout** [comment]
Can you post a screenshot video showing this? Also, where are you clicking, what browser, version, and OS do you have?
