### ISSUE TITLE
Debounce the kernel sources filter

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#12029]
### Problem

https://github.com/jupyterlab/jupyterlab/pull/11566 has introduced a new debugger panel that show the available sources in the kernel. That list can be filtered, but as the list is typically large, every keystrokes requests a refresh of the panel, which can be slow and not user-friendly

### Proposed Solution

Debounce the keystrokes in the filter box.

**Comment by krassowski** [comment]
I think we can improve rendering time without introducing debouncer; we still need to do that for #12012. I believe that we should just render a custom list widget with `<li>` items (like in file manager) instead of using tons of individual widgets (as those have too much overhead).

I feel that debouncer should be more like a last resort solution when something cannot be made snappy with other means because it takes away from interface responsibility by design.

**Comment by krassowski** [comment]
> but still a debouncer for a not-light action (filtering and displaying potentially thousands of entries) deserves a debouncer IMHO

Possibly. For now, could we settle on making it 250ms or 500ms instead of 1000ms?

**Comment by echarles** [comment]
> Possibly. For now, could we settle on making it 250ms or 500ms instead of 1000ms?

I have now explicitly set to 500ms which is the default IIRC
