### ISSUE TITLE
A "navigate to parent directory" keyboard shortcut in filebrowser.

### ISSUE THREAD

**Issue by ilibarra** [jupyterlab/jupyterlab#12047]
### Problem

When browsing through the file browser in Jupyter, one can press the Enter key and go inner directories in a give filesystem hierarchy. However, one then cannot return to parent directories, e.g. by pressing backspace. Such a shortcut is not available in the "filebrowser:[COMMAND]" variable.  One has to rely on mouse clicking to navigate to parent directories.

### Proposed Solution

A shortcut variable to trigger going to the parent directory in the File Browser e.g. Backspace.

HTHs.

**Comment by krassowski** [comment]
Thanks for opening the issue. There is already a shortcut like this which was implemented in #6859 and included in JupyterLab 3.1 (and this issue is a duplicated of #6808). What version of JupytrerLab are you using? I am aware of a limitation in with regards to the selector (i.e. an element in the browser has to be selected for the shortcut to work because otherwise it would also kick-in while editing file name - a technicality) but otherwise it should work ell.

**Comment by ilibarra** [comment]
@krassowski my bad I was using 3.0.x. I have upgraded to >3.1 and now I can see the `filebrowser:go-up` shortcut.

Thanks!
