### ISSUE TITLE
allow linear-gradient in background-image html styling within Markdown cells

### ISSUE THREAD

**Issue by gutow** [jupyterlab/jupyterlab#12093]
## Description

Styling such as `style="background-image:linear-gradient(green,blue);"` within the styling of `div` or other element specified within a markdown cell is not rendered. Plain background images are rendered.

Unless there is a security issue I am unaware of, I think gradient styling should be allowed.

## Reproduce

Enter the following in a markdown cell and run it to render:
```
<div style = "height: 20px; width:100%; background-image:linear-gradient(green,blue);"></div>
<div style = "height: 20px; width:100%; background-color:blue;"></div>
```
The first will not be shown, but the second will.

## Expected behavior

The expected behavior is that the gradient will be rendered.
## Context

- Operating System and version: all
- Browser and version: at least Chrome and Firefox
- JupyterLab version: 3.1.1 (latest I could get to launch in Binder from the repositories).

**Comment by fcollonval** [comment]
The sanitizer forbids the usage of `background-image` as it could bring external file through `url` definition. A way around would be to define an extension that overrides the `ISanitizer` token by providing a custom sanitizer.

**Comment by krassowski** [comment]
@fcollonval i don't believe this is the case. Sanitizer does allow `background-image`. It only does not know that `linear-gradient` is a valid property because the allowlist was not updated in a long time:

https://github.com/jupyterlab/jupyterlab/blob/047fbe7c2772bc34503207b7724216f9e0bbcfc3/packages/apputils/src/sanitizer.ts#L117

See additional discussion in https://github.com/jupyter/notebook/issues/6270#issuecomment-1014956760

**Comment by fcollonval** [comment]
Thanks for the detailed information @krassowski 
This is then a valid bug.

**Comment by t-vi** [comment]
In a similar theme, I liked to use floating images (`style="width: 200px; float: right;" `), to get images to be on the right of the markdown text. Unfortunately, this stopped working.
Is there a way to make this configurable?
