### ISSUE TITLE
Easier copying of the current file

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12099]
### Problem

We should make it easier to copy the file you are currently working on. Today you can only do this (as far as I can tell) by finding the file in the file browser then right clicking on it then duplicate.

### Proposed Solution
Do some of:
1. Add a menu item like nbclassic (File->Make a Copy)
2. Right click on the tab and "Make a copy"
3. Add a Command Palette item to allow for this + hotkey opt-in support

**Comment by fcollonval** [comment]
A workaround for now (in JupyterLab 3.2 or later) would be to add the command to the file menu and/or the context menu through the settings.

The command id is `'filebrowser:duplicate'`. 
The tab selector is `"#jp-main-dock-panel .lm-DockPanel-tabBar.jp-Activity .lm-TabBar-tab"`

**Comment by peytondmurray** [comment]
I'd like to work on this!

**Comment by fcollonval** [comment]
Thanks @peytondmurray

do you need pointers?

**Comment by peytondmurray** [comment]
@fcollonval I was looking at the menu items in the file menu and in the context menu that appears when you right-click on a tab:

![image](https://user-images.githubusercontent.com/14017872/178029261-9c35c5f3-2dc2-4492-b0b5-fba1e54b377a.png)

and I noticed that the commands you see there are part of the `docmanager`. Similarly to how there is both `docmanager:rename` and `filebrowser:rename`, I was thinking of adding a `docmanager:duplicate` command so that I could easily insert that command next to the other similar menu options. I've been able to do this (see the `Duplicate Notebook` option in the menu), but wanted to double check about this approach with you because as you mentioned above there is already a `filebrowser:duplicate` command.

What approach do you prefer? Should I just reuse `filebrowser:duplicate`, and insert it into the menus where they need to be? Or should I create a new command `docmanager:duplicate`, to keep document management code together in one place?

**Comment by fcollonval** [comment]
@peytondmurray I would go for creating a new command `docmanager:duplicate` that use the `contextMenuWidget` required to deal with context menu opened on the non-active tab.

**Comment by krassowski** [comment]
The File menu is getting pretty long:

![image](https://user-images.githubusercontent.com/5832902/183318050-fbbb2126-e6f9-44c3-b1a7-15798e313dab.png)

is having "File" -> "Duplicate Notebook" worth it given that we already have "File"->"Save Notebook As..." (11th option, <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>)?

We could combine the two by modifying the "save as" dialog to default to `{name}-Copy{nth}.{format}` instead of current `{name}.{format}` and having `{name}-Copy{nth}` auto-selected so if user starts typing they can replace this part easily.

**Comment by peytondmurray** [comment]
You're right, there is overlapping functionality between `Duplicate` and `Save As...` - I'll do this and let you know when I'm ready for another look.

**Comment by peytondmurray** [comment]
@krassowski After taking another look at the behavior for duplicate, I'm second guessing myself because it seems like setting the right default name in the "save as" dialog is not as straightforward as I thought. `docmanager:duplicate` calls [`Drive.copy()`](https://github.com/jupyterlab/jupyterlab/blob/fde79dc677cd1431002c529fe3c4451e527529ae/packages/services/src/contents/index.ts#L1272), which sends a POST request to the server to copy the existing file to the same directory (e.g. copy `/home/user/workspace/nb.ipynb` to `/home/user/workspace/`). Then the [server decides the new name to use for the duplicated file](https://github.com/jupyter-server/jupyter_server/blob/76239661a69708de8b4d842261cdde763f5edba6/jupyter_server/services/contents/handlers.py#L195). In principle we could recreate the [logic for deciding the duplicate name](https://github.com/jupyter-server/jupyter_server/blob/main/jupyter_server/services/contents/manager.py#L576) in the frontend and use that as the "save as" dialog default, but we'd then need to send a request to the server to get a list of the contents of the target directory so that we could determine the appropriate name to put in the dialog box; from what I can tell this can be done with a call to `FilterFileBrowserModel.items()` from the `filebrowser` extension.

I'm not as familiar with this part of the code base. It looks like the `Save File As...` menu option is part of the `docregistry` package; I'll need to modify [getSavePath](https://github.com/jupyterlab/jupyterlab/blob/fde79dc677cd1431002c529fe3c4451e527529ae/packages/docregistry/src/context.ts#L1031), creating a new `FilterFileBrowserModel` instance in order to get a list of files - does this sound right?

**Comment by krassowski** [comment]
> I'm not as familiar with this part of the code base. It looks like the Save File As... menu option is part of the docregistry package; I'll need to modify [getSavePath](https://github.com/jupyterlab/jupyterlab/blob/fde79dc677cd1431002c529fe3c4451e527529ae/packages/docregistry/src/context.ts#L1031), creating a new FilterFileBrowserModel instance in order to get a list of files - does this sound right?

That would introduce a dependency cycle (`filebrowser` already depends on `docregistry`). Instead, we could request the listing of files directly from the server contents API (something like `this._manager.contents.get(dirPath)`, see [`handleContents`](https://github.com/jupyterlab/jupyterlab/blob/5c04fa6e8f8996608fa8d36be071d8d17a85a061/packages/filebrowser/src/model.ts#L582)).

There is also difference in behaviour I have not considered earlier: `Duplicate` makes a copy in the background, while `Save File as...` swaps the model of the widget. Looking at LibreOffice Writer, there is both "Save as..." and "Save a copy". Maybe its okay as-is, and we can just move other things out of this menu (e.g. maybe `Close All Tabs` could be in `Tabs` menu).

Still, it would be nice to implement an auto-focus in save-as on the relevant part - we can extract that to a new issue.

**Comment by peytondmurray** [comment]
Okay, let's leave `Duplicate` in the File menu for now, and open another issue for moving some other items out of this menu if need be.
