### ISSUE TITLE
Deploy a notebook using `console_scripts`

### ISSUE THREAD

**Issue by qci-amos** [jupyterlab/jupyterlab#12185]
### Problem

I would like to "deploy" notebooks to users as applications.

For CLI tools, I can add them to `console_scripts` and then my application ends up on their `PATH`. I would like something comparable for notebooks. This way it doesn't matter which repo or which folder the application lives in, it's always immediately available to a user as long as they have installed it.

The [documentation ](https://docs.jupyter.org/en/latest/running.html#how-do-i-open-a-specific-notebook) recommends this:
```
jupyter notebook notebook.ipynb
```

but that requires the user to know a) this command line, and b) which folder the `.ipynb` lives.

### Proposed Solution

I would like to be able to do something like this in my `setup.py`:
```
    entry_points={
        "console_scripts": [
            "my_application = my_package.my_module:launch_jupyter_notebook",
        ],
    },
```

where somehow it does the equivalent to `jupyter notebook notebook.ipynb` (and not *execute* the notebook).

### Additional context

Maybe I could use `Popen` like [this person](https://stackoverflow.com/a/59345982/319034) did? Maybe I could use or follow [something like](https://github.com/takluyver/nbopen/blob/e3b1b5fb5b166e19503654b99ce8fb45738ada9e/nbopen/nbopen.py#L21-L52) `nbopen`? It looks like `nbopen` is mostly what I want and it seems to work, but that repo also hasn't been modified in ~4yrs.

Some official guidance would be appreciated.

**Comment by jweill-aws** [comment]
@qci-amos Have you checked on the [Discourse forum](https://discourse.jupyter.org/) about this request? I'm not sure that this constitutes a feature request for JupyterLab; it looks more like a question about deploying JupyterLab or Jupyter Server to meet your needs. If there aren't any features or strategies that meet your needs, please come back and reopen this issue so that we can consider adding a new feature.
