### ISSUE TITLE
Any chance to output results in a new tab?

### ISSUE THREAD

**Issue by Yefee** [jupyterlab/jupyterlab#12254]
Hi community,

I am wondering if there is an option to set results presented in a new tab? Like the Datalore, see pic below.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/6420873/159394865-d79b5c83-d36d-4cdb-8571-10451d646d6a.png">

**Comment by jweill-aws** [comment]
Similar issue in Jupyter Notebook: https://github.com/jupyter/notebook/issues/2791

**Comment by jtpio** [comment]
There is also a side-by-side rendering mode added in https://github.com/jupyterlab/jupyterlab/pull/10648

See the screencasts in https://github.com/jupyterlab/jupyterlab/pull/10648#issue-947789058 for more info, not sure this feature is in the documentation.

@Yefee maybe that works for your use case?

**Comment by krassowski** [comment]
And there is also:
- `Create New View for Output` in context menu
  ![new-view](https://user-images.githubusercontent.com/5832902/159926701-9538a843-e476-448e-a03f-068e773d15f3.gif)
- [jupyterlab-sidecar](https://github.com/jupyter-widgets/jupyterlab-sidecar)
  ![sidecar](https://github.com/jupyter-widgets/jupyterlab-sidecar/raw/master/sidecar.gif)
- since JupyterLab 3.3 you can also render variables in a tab using the debugger preview (requires recent ipython/ipykernel):
  ![debugger](https://user-images.githubusercontent.com/5832902/159926456-49b0f3cf-9e8c-489f-a3a5-0b7f7e6ae4fa.gif)
- Edit: there is also https://github.com/xiaohk/stickyland for completeness
  ![Image](https://github.com/user-attachments/assets/8bb58524-919a-49b2-9b07-8de0a9cd5472)

**Comment by jweill-aws** [comment]
We don't have a mode that looks exactly like the Datalore screen shot you shared, but the "side-by-side" view added in #10648 should allow you to view inputs and outputs in a two-column view. @krassowski also shared an alternate "new view" option that you can move to the side using JupyterLab's layout options. Closing this issue. If you specifically need Datalore's layout, please reopen.

**Comment by Yefee** [comment]
> 
This seems a great alternative! Thanks!
