### ISSUE TITLE
Extra cell getting created when using `?` to get function docstrings

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#12269]
## Description
With lab 3.3.x, lab creates an extra cell when using `?` to get in notebook help. This GIF demonstrates this behavior - 
![cell_add_bug](https://user-images.githubusercontent.com/30082866/159871402-e280cc82-559a-4261-a1a0-9e44fd4b1d1c.gif)

## Reproduce

Small code snippet to reproduce this - 
1. In cell 1 write - `import numpy as np`
2. In cell 2 write - `np.zeros((1,2)).append?`
3. Run the notebook.

## Expected behavior
It should not create the extra cells.

## Context

- Operating System and version: Linux Ubuntu 21.04
- Browser and version: Chrome 92
- JupyterLab version:  3.3.x

**Comment by krassowski** [comment]
Confirmed. This bug was there for quite a while now, I believe I saw it even in 1.x. Another example which does not require third-party packages:

```
sum([1]).denominator?
```

However, `sum.__name__?` works ok, so it seems to be something with the parentheses `()`.

**Comment by krassowski** [comment]
Briefly, when parens are absent what happens is `execute_input"` is send on `iopub` channel with code `sum.__name__?` and then `execute_reply` is returned on the shell channel:

```json
{
    "status": "ok",
    "execution_count": 18,
    "user_expressions": {},
    "payload": [
        {
            "source": "page",
            "data": {
                "text/plain": "\u001b[0;31mType:\u001b[0m        str\n\u001b[0;31mString form:\u001b[0m sum\n\u001b[0;31mNamespace:\u001b[0m   Python builtin\n\u001b[0;31mLength:\u001b[0m      3\n\u001b[0;31mDocstring:\u001b[0m  \nstr(object='') -> str\nstr(bytes_or_buffer[, encoding[, errors]]) -> str\n\nCreate a new string object from the given object. If encoding or\nerrors is specified, then the object must expose a data buffer\nthat will be decoded using the given encoding and error handler.\nOtherwise, returns the result of object.__str__() (if defined)\nor repr(object).\nencoding defaults to sys.getdefaultencoding().\nerrors defaults to 'strict'.\n"
            },
            "start": 0
        }
    ]
}
```

The reply is handled in `_onExecuteReply` and output gets added via `OutputAreaModel.add` - nothing unusual.

However, when the code in request is `sum([1]).denominator?` a different `execute_reply` payload is provided on the `shell` channel, this time with `set_next_input` source.

```json
{
    "status": "ok",
    "execution_count": 19,
    "user_expressions": {},
    "payload": [
        {
            "source": "set_next_input",
            "text": "sum([1]).denominator",
            "replace": false
        }
    ]
}
```

This looks like an issue in ipykernel, as what follows is JupyterLab correctly sets next input as instructed.

**Comment by krassowski** [comment]
In IPython if the result is not found the `_inspect()` [method returns](https://github.com/ipython/ipython/blob/47ccec77b41b010091ec18a20ff7d2bedcc674da/IPython/core/interactiveshell.py#L1684-L1686):

```python
else:
    print('Object `%s` not found.' % oname)
    return 'not found'  # so callers can take other action
```

I don't quite see how it leads to `set_next_input` :confused: 

One way to fix it would be to simply execute everything prior to `?` which would also fix https://github.com/ipython/ipython/issues/2451 (instead of doing manual traversal of objects and failing to do so when a call is encountered).

**Comment by krassowski** [comment]
It is also reproducible with:

```python
%pinfo sum.denominator?
```

This one does not:

```python
ipython._inspect('pinfo', 'sum.denominator')
```

Nor does this one:

```python
get_ipython().run_line_magic('pinfo', 'sum.denominator')
```

which means that the problem must be in the input transformer... Here we go:

https://github.com/ipython/ipython/blob/0c5563497fe94a8a24ec88912433959908f2506e/IPython/core/inputtransformer.py#L196-L210

```python
def _make_help_call(target, esc, lspace, next_input=None):
    """Prepares a pinfo(2)/psearch call from a target name and the escape
    (i.e. ? or ??)"""
    method  = 'pinfo2' if esc == '??' \
                else 'psearch' if '*' in target \
                else 'pinfo'
    arg = " ".join([method, target])
    #Prepare arguments for get_ipython().run_line_magic(magic_name, magic_args)
    t_magic_name, _, t_magic_arg_s = arg.partition(' ')
    t_magic_name = t_magic_name.lstrip(ESC_MAGIC)
    if next_input is None:
        return '%sget_ipython().run_line_magic(%r, %r)' % (lspace, t_magic_name, t_magic_arg_s)
    else:
        return '%sget_ipython().set_next_input(%r);get_ipython().run_line_magic(%r, %r)' % \
           (lspace, next_input, t_magic_name, t_magic_arg_s)
```

This code is ancient. Apparently it got written like that in 2012 during a refactor to remove "next_input nonsense in magic calls": https://github.com/ipython/ipython/commit/3f192dc6a1873b0d2e5345fc475ffab0fa403466.

It serves a purpose though; it appears to be intended to allow inserting the `?` mid line: https://github.com/ipython/ipython/blob/0c5563497fe94a8a24ec88912433959908f2506e/IPython/core/inputtransformer.py#L342-L355

```python
@StatelessInputTransformer.wrap
def help_end(line):
    """Translate lines with ?/?? at the end"""
    m = _help_end_re.search(line)
    if m is None or ends_in_comment_or_string(line):
        return line
    target = m.group(1)
    esc = m.group(3)
    lspace = _initial_space_re.match(line).group(0)

    # If we're mid-command, put it back on the next prompt for the user.
    next_input = line.rstrip('?') if line.strip() != m.group(0) else None

    return _make_help_call(target, esc, lspace, next_input)
```

This however would not work with the current input transformer because the AST transformer only handles `?` at the end of the line.

**Comment by krassowski** [comment]
I opened https://github.com/ipython/ipython/issues/13602 and will wait for feedback. I was annoyed by this dozens of times so went ahead and investigated but may not have time to fix it myself; I hope that anyone interested will have enough details to create a pull request on IPython repository to fix that based on the information here and in the linked issue.

**Comment by agoose77** [comment]
Related to #9278 too :)
