### ISSUE TITLE
Hide the cell toolbar on mobile

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#12523]
## Description

The cell toolbar is still displayed on mobile devices and looks a bit off.

## Reproduce

Using JupyterLab 3.4.0 with this gist on Binder: https://gist.github.com/jtpio/dc217fb83255f54bf826a3804f5a0d7c

https://user-images.githubusercontent.com/591645/166635951-f9545ec5-cb32-437d-87c0-da2bded14e0a.mp4

## Expected behavior

The toolbar should be hidden when the viewport is getting smaller.

## Context

Follow-up to https://github.com/jupyterlab/jupyterlab/pull/12028

**Comment by jweill-aws** [comment]
In JupyterLab 4, when the viewport is narrow enough for us to consider things to be "mobile", we should use a two-line layout with the cell toolbar on top. However, I'm not seeing that right now.

**Comment by JasonWeill** [comment]
If #13115 is fixed, that may make this issue moot

**Comment by andrii-i** [comment]
@jtpio in the posted binder / jupyterlab 3.4.0 cell toolbar doesn't disappear when viewport size changes and obscures text in the cell. PR [#12028](https://github.com/jupyterlab/jupyterlab/pull/12028) solves this problem by introducing 2-line layout for viewports less than 760px. Would you say the problem in this issue is solved or you have a strong preference to explicitly hide cell toolbar and issue should remain open to facilitate discussion around this? 

How same interaction looks on head-of-master / will look in 4.0.0:
![cell_toolbar_4_0](https://user-images.githubusercontent.com/26686070/214730829-51f5e5eb-7723-4534-8bf1-d71dc3b6798d.gif)

PS: while working on this issue found material to create 2 new issues 😄
- #13857 
- #13858

**Comment by jtpio** [comment]
Thanks @andrii-i for checking this.

I just tried with `4.0.0a32` on Chromium with the mobile device dev tools mode and this is what it looks like:

https://user-images.githubusercontent.com/591645/214816835-62ccecb2-a54f-47f3-9e2e-8b17abbd1fce.mp4

The difference with the screencast is the left sidebar being collapsed which probably changes the behavior?

**Comment by andrii-i** [comment]
@jtpio it actually behaves the same on my end; I understand the issue now, thank you

**Comment by andrii-i** [comment]
Created PR #13896 that hides cell toolbar on mobile
