### ISSUE TITLE
Let extensions add buttons to cell toolbar via API

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#12557]
### Problem

Let other extensions (e.g., commenting) add buttons to the cell toolbar when the extension is active. The API to do this should be similar to the `contextMenu` aspect of `app` (application) which can be customized with a new button as follows:

```
    app.contextMenu.addItem({
      command: CommandIDs.addNotebookComment,
      selector: '.jp-Notebook .jp-Cell',
      rank: 13
    });
```

This would help with the implementation of #12032.

### Proposed Solution

Offer an API to let other extensions add buttons to the cell toolbar by specifying a command, a selector, and a rank.

### Additional context

Documentation on customizing context menu: https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html#context-menu

**Comment by fcollonval** [comment]
The menu API is kept for retro compatibility (and to support the case of dynamic items). But it will be good to not add any API that overlaps with data based UI because they bring troubles to handle things properly by breaking the single source of truth principle. The best example that still lives in master is the debugger toolbar button. It is not added through the settings definition. 
So if you update the toolbar definition, its position is not consistent.

Could you elaborate on the use case that would prevent changing the cell toolbar definition through the API settings?

**Comment by jweill-aws** [comment]
In `cell-toolbar-extension`, I see that the toolbar items are retrieved here: https://github.com/jupyterlab/jupyterlab/blob/5c04fa6e8f8996608fa8d36be071d8d17a85a061/packages/cell-toolbar-extension/src/index.ts#L31-L40

`CellBarExtension.FACTORY_NAME` is `"Cell"`.

So would I be able to have the `comments-extension` affect the cell toolbar by adding the following info to `plugin.json` in the new package?

```js
   "jupyter.lab.toolbars": {
     "Cell": [
       {
         "name": "add-comment",
         "command": "jl-comments:add-notebook-comment",
         "rank": 10 // or whatever would put it at the right of the cell toolbar
       },
   }
```

**Comment by fcollonval** [comment]
Yes that will work - the principle for building the complete list is exactly the same as for the menus or shortcuts. So any extension can easily add new items in any toolbar. And users are able to disable those default items if they want.

**Comment by jweill-aws** [comment]
@fcollonval Thank you! I have a WIP code review for adding a button to the cell-toolbar in the new `comments-extension` package: #12588. I don't see the new button appear and I don't see the new settings appear in the settings pane. Is there something else I need to do to have JupyterLab apply settings in a new core package?
