### ISSUE TITLE
Galata: baseURL extra params generated by the test location

### ISSUE THREAD

**Issue by jujogi** [jupyterlab/jupyterlab#12651]
### Problem
We are trying to implement Galata in our Playwright AVR environment. We have some utilities that we want to replace for some Galata's methods. We already have our JupyterLab working in production, so we are using the playwright factory to override the baseUrl property before the test starts.

This is the code we are using to override the **baseUrl**  and **appPath** properties:
```
const url = "https://domain.com";
test.use({
  baseURL: url,
  appPath: "hub",
});

test.only("Test Name", async ({ page, baseURL, tmpPath }) => {
  await page.goto();
  const fileName = "create_test.ipynb";
  await page.notebook.createNew(fileName);
});
```

When we run the command, we figured out that the url has some extra params, following this structure:

```
https://domain.com/hub/tree/test-Galata-notebook-Test-Name-galata
baseUrl/appPath/tree/mainFolderTest-testFolder-testFileName-testName-galata
```

<img width="590" alt="Screen Shot 2022-06-03 at 11 04 14 AM" src="https://user-images.githubusercontent.com/5192743/171903107-c12ce5a2-39ec-4552-82c9-0807f5d6423f.png">

Is there a way to remove the next part of the appPath segment? It is a problem because the browser is returning a 404 error: **Jupyter has lots of moons, but this is not one…**

<img width="854" alt="Screen Shot 2022-06-03 at 11 09 16 AM" src="https://user-images.githubusercontent.com/5192743/171903985-a0e0aabb-ba57-469a-87ca-60159d4f2609.png">

**Comment by jweill-aws** [comment]
Triage notes: Usually, the base URL is configurable in the Playwright config. Can you please share your Playwright config with us?

**Comment by jweill-aws** [comment]
@fcollonval Can you provide any other context about Galata and URLs, please?

**Comment by fcollonval** [comment]
@jujogi from your screenshots, it looks like you are passing through some proxy to get to the Jupyter Server (something like JupyterHub).

The reason you are hitting that error is because galata creates on the Jupyter Server a test folder for every test. But in your case the server your are interacting with is the proxy not the Jupyter Server. So that requests is probably failing and the endpoint to go to that folder does not exists.

The Playwright `page` fixture is overridden by Galata at https://github.com/jupyterlab/jupyterlab/blob/989d2bcccb9c50389c98d3436dd617a1b04660a7/galata/src/fixtures.ts#L312. So you have two options:
- Simple approach: set fixture `autoGoto` to false and provide the correct target URL for each test using `page.goto(<target url>)`.
- Set your own `page` fixture.

> Important note: galata is NOT designed for that (i.e. Hub + Lab) and I would recommend mocking the interaction between the Jupyter server and the proxy rather than testing the all stack. For instance galata inject javascript dedicated to JupyterLab when opening a page and it uses some of its API like the contents REST API to upload files.
