### ISSUE TITLE
More semantic API for the ITranslator

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#12684]
### Problem
The public API of the ITranslator only has one method, `load`.

To know what language JupyterLab uses, we need to access the setting's plugin and load the translator's settings ('@jupyterlab/translation-extension:plugin'). Probably we should have a more semantic API for this plugin so we can request what language is loaded. Some extensions may use libraries with support for multiple languages, and they may need to listen for changes in JupyterLab to load the corresponding language.

### Proposed Solution
Expose a more semantic API. Maybe a signal `languageChanged` is tricky because after changing the language, Jupyterlab is reloaded, but at least a property that indicates what language is being used.

### Additional context

cc @fcollonval

**Comment by krassowski** [comment]
The `NullTranslator` object already has a `locale` property and `TranslationManager` stores `_currentLocale`; we can easily create a consistent `locale` property and make it public by adding it to the `ITranslator` interface. It would be useful for spellchecker and other extensions.

Locale however might be a misnomer as it only stores a language code rather than a full locale config, so we may want to rename it to `languageCode` or similar, or instead we could make a stub for a fully-fledged locale support (which could or could not be useful in the future for things like decimal place separators, default paper format for notebook exports, etc - but maybe it should not be the responsibility of _translator_, but of a _localisationManager_).

**Comment by hbcarlos** [comment]
> Locale however might be a misnomer as it only stores a language code rather than a full locale config, so we may want to rename it to languageCode or similar

That's a great idea.

> we could make a stub for a fully-fledged locale support (which could or could not be useful in the future for things like decimal place separators, default paper format for notebook exports, etc - but maybe it should not be the responsibility of translator, but of a localisationManager)

In my opinion, we should add it to the public API once we support those features. Otherwise, it could be a bit confusing.

**Comment by hbcarlos** [comment]
As discussed above, to improve the ITranslator's API, we will need to:

Add a new property, `languageCode`, to the interface here:
https://github.com/jupyterlab/jupyterlab/blob/adafbabcef3315bc706381d533d229115c07b5a6/packages/rendermime-interfaces/src/index.ts#L600
then we will need to expose the private property `_currentLocale` in the TranslatorManager
https://github.com/jupyterlab/jupyterlab/blob/adafbabcef3315bc706381d533d229115c07b5a6/packages/translation/src/manager.ts#L74
and also add the `languageCode` property to the NullTranslator here:
https://github.com/jupyterlab/jupyterlab/blob/adafbabcef3315bc706381d533d229115c07b5a6/packages/translation/src/base.ts#L11
