### ISSUE TITLE
Broken markdown rendering for reference links in table

### ISSUE THREAD

**Issue by seignovert** [jupyterlab/jupyterlab#12745]
## Description

Since the version `3.4.2`, the markdown rendering for links with a reference in a table is broken:

Example:
```markdown
| Header 1                      | Header 2         |
|-------------------------------|------------------|
| [link a](https://example.org) | [link b][link_b] |

[link c][link_c]

[link_b]: https://example.org
[link_c]: https://example.org
```
<img width="1598" alt="JupyterLab-md_issue" src="https://user-images.githubusercontent.com/13715971/176236374-e38e1cac-36d1-4511-8c7e-433b145e8871.png">

## Reproduce

1. Start JupyterLab ≥ 3.4.2
2. Render the markdown cell above.

## Expected behavior

Reference links inside and outside the table should be rendered the same way.

## Context

- Operating System and version: macOS (BigSur)
- Browser and version: Firefox and Chrome
- JupyterLab version: 3.4.2 and 3.4.3

**Comment by krassowski** [comment]
Thank you for reporting. JupyterLab 3.4.2 upgraded marked renderer to v4.0.15 which had this regression. It looks like this bug was since reported (https://github.com/markedjs/marked/issues/2217) and fixed upstream in v4.0.16. There is also v4.0.17 which contains another bugfix, so I think we should upgrade to get those fixes.
