### ISSUE TITLE
reopen "Invisible text Cursor when editing python text files in Dark mode theme #4030"

### ISSUE THREAD

**Issue by edblak** [jupyterlab/jupyterlab#12764]
## Description
cursor invisible on browsers using chrome://flags dark mode

might need to reopen "Invisible text Cursor when editing python text files in Dark mode theme #4030"

**Comment by jweill-aws** [comment]
@edblak Can you please provide screen shots of what you're seeing in dark mode? Information about how these diverge from your expectations will help us to understand what work has to be done.

**Comment by jweill-aws** [comment]
Closing this issue for lack of additional information. @edblak if you can provide more info, please reopen. Thanks!

**Comment by keflavich** [comment]
I'm having this issue so I'll provide some screenshots:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/143715/180625902-c2501a4f-581e-44e3-a1db-2285c508018f.png">


Version is:

```
Selected Jupyter core packages...
IPython          : 7.21.0
ipykernel        : 5.1.2
ipywidgets       : 7.7.0
jupyter_client   : 7.3.4
jupyter_core     : 4.10.0
jupyter_server   : 1.17.1
jupyterlab       : 3.4.3
nbclient         : 0.6.4
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 5.2.2
```

(this may be related to open issue #8407)

**Comment by atimeofday** [comment]
I am also having this issue. I can provide information/screenshots if they would help, but I'm not sure what would be needed.

**Comment by krassowski** [comment]
@atimeofday can you please list: JupyterLab version, browser and operating system versions, JupyterLab extensions installed, and any browser extensions installed.

**Comment by atimeofday** [comment]
jupyter --version:
IPython              : 8.4.0
ipykernel            : 6.15.2
ipywidgets         : 8.0.2
jupyter_client     : 7.3.5
jupyter_core      : 4.11.1
jupyter_server   : 1.18.1
jupyterlab          : 3.3.2
nbclient              : 0.5.13
nbconvert          : 6.4.4
nbformat            : 5.5.0
notebook           : 6.4.12
qtconsole          : not installed
traitlets              : 5.1.1

Vivaldi | 5.5.2805.44 (Stable channel) stable (64-bit)

Pop!_OS 22.04 LTS

No browser extensions installed which affect page colors.

vivaldi://flags - Auto Dark Mode for Web Contents - Enabled
#enable-force-dark

Currently using this experimental flag because it provides a much better dark mode experience than any browser extension I have tried. Let me know if there's anything else.
