### ISSUE TITLE
Improve long completion UX

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12830]
### Problem

Long autocomplete becomes unusable as users cannot tell the difference between options. For example see this screen shot:
![image](https://user-images.githubusercontent.com/1813603/180093478-64bbd1c4-fc22-4846-add0-9fbe8094ff71.png)

### Proposed Solution

1. Use a larger fraction of the browser width
2. If the string is still too long, elide up to the largest common prefix for example (maybe leave a few characters to make it clear):
   - ...ion/a_short
   - ...ion/b_very_very_very_long_name
   - ...ion/c_medium_name
3. If the string is still too long after 2, elide the end the end as well
   - ...ion/a_short
   - ...ion/b_very_very_very_l...
   - ...ion/c_medium_name

What do you think?

**Comment by peytondmurray** [comment]
@mlucool I've been looking into this today on the most recent commit on `master` to try to reproduce. It looks like the width of the floating completion widget is set to `auto`, and I'm not seeing the ellipsis even for completion widgets that take up the entire width of the browser window:

![image](https://user-images.githubusercontent.com/14017872/182697954-e23fcfed-7d08-4cf6-ab62-2f2f27fabac0.png)

Is this some browser setting on my side of things?

**Comment by mlucool** [comment]
This was on 3.4.3. I can reproduce on the binder in this projects README too (although its only 3.2.0):

```
import os

!mkdir -p a/really/really/a/really/really/a/really/really/a/really/really/a/really/really/a/really/really
!mkdir -p a/really/really/a/really/really/a/really/really/a/really/really/a/really/really/b/really/really
!touch  a/really/really/a/really/really/a/really/really/a/really/really/a/really/really/a/really/really/longfile

os.list('a/really/really/a/really/really/a/really/really/a/really/really/a/really/really/<tab>
```

![image](https://user-images.githubusercontent.com/1813603/182732038-f0987c90-d661-468a-a796-36c876494fc1.png)

It's possible this is fixed on master and just needs a backport?

**Comment by krassowski** [comment]
Could it be that you was using [jupyterlab-lsp](https://github.com/jupyter-lsp/jupyterlab-lsp) extension or something similar? I don't see icons on the initial screenshot which makes it kind of weird, as neither core lab completer nor lsp looks like this in notebooks by default.

jupyterlab-lsp does have a feature of trimming the width of completion item with an ellipsis, see https://github.com/jupyter-lsp/jupyterlab-lsp/pull/508/.

It indeed needs a fix for completions of paths (and there is already an issue about this: https://github.com/jupyter-lsp/jupyterlab-lsp/issues/787) as it trims at the end but for paths you want to see the end. This feature is however needed, as it solves the bigger problem of long completion labels occluding the view of the notebook (for lsp labels which include more details) - compare:

Before https://github.com/jupyter-lsp/jupyterlab-lsp/pull/508/:
![cycle-before](https://user-images.githubusercontent.com/5832902/107132373-4253a480-68d6-11eb-9da2-4d719c2c1bc3.gif)

After https://github.com/jupyter-lsp/jupyterlab-lsp/pull/508/:
![cycle-after](https://user-images.githubusercontent.com/5832902/107132375-47185880-68d6-11eb-833a-4ea6a2f29de6.gif)

It should be easily possible to conditionally change the CSS for trimming completion labels so that for completion items of type `file` or `path`, the label is trimmed at the beginning. It would however,

**Comment by mlucool** [comment]
Ah you are right @krassowski it does seem to come from LSP (even with code completion disabled which I *think* controls this?). Maybe that's a separate bug and either way belongs on jupyterlab-lsp
