### ISSUE TITLE
Support new kernels REST API

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#12867]
### Problem

Jupyverse just got support for a [new code execution mode](https://github.com/jupyter-server/jupyverse/pull/191) through a POST request, where the front-end doesn't have to deal with the kernel protocol (this is handled in the back-end). It's still experimental and limited (e.g. widgets are currently not supported), but it could be interesting to start supporting that mode in JupyterLab.

### Proposed Solution

Support code execution using the new POST request instead of using the kernel protocol over WebSocket when JupyterLab is launched with e.g. `--post_execute_request` and RTC is enabled.

### Additional context

https://github.com/jupyter-server/jupyter_server/issues/900.

**Comment by matthewwiese** [comment]
Hi @davidbrochart I'm interested in contributing to the support for this feature, because if I understand correctly it should help to resolve #2833.

Since I am unfamiliar with the JupyterLab codebase, could you provide guidance for a new contributor? I have time which I can set aside to pursue development of this.

**Comment by davidbrochart** [comment]
Hi @matthewwiese, thanks for offering help on this.

There are two parts:
- the back-end, which must provide the `POST /api/kernels/{kernel_id}/execute` route. Since this has been implemented [in Jupyverse](https://github.com/jupyter-server/jupyverse/blob/465551af1203c3a7659dc3e53e179b123b6d853a/plugins/kernels/fps_kernels/routes.py#L181-L205), maybe you can have a look over there and try to implement it in [jupyter-server](https://github.com/jupyter-server/jupyter_server). But since it already exists in Jupyverse, it may be better to focus on the second part.
- the front-end, which must do a request to the route. I think this is the interesting part. Currently [JupyterLab opens a WebScocket](https://github.com/jupyterlab/jupyterlab/blob/897bb5a3c6af7f1ac5b17fd323a952027c9ab22a/packages/services/src/kernel/kernel.ts) and talks the kernel protocol over it. You would have to add another mode where the kernel POSTs code to execute. In a way it is simpler, but you will have to figure out how to do it.

**Comment by davidbrochart** [comment]
cc @Zsailer if you want to take a shot at it.

**Comment by matthewwiese** [comment]
@davidbrochart Is there a spec for the new kernels REST API?

**Comment by davidbrochart** [comment]
You can start from the REST endpoint definition [in Jupyverse](https://github.com/jupyter-server/jupyverse/blob/9dc18fa223e8ff9db15b1ec0a3f1ad210ec98efc/plugins/kernels/fps_kernels/routes.py#L225-L230). It is a `POST /api/kernels/{kernel_id}/execute`, with a [body](https://github.com/jupyter-server/jupyverse/blob/a3c91996ad20fef03a8ebfe4150bc9eea38dfbb2/jupyverse_api/jupyverse_api/kernels/models.py#L40-L42) that has a `document_id` and a `cell_idx`.
You can also have a look at the [test](https://github.com/jupyter-server/jupyverse/blob/a3c91996ad20fef03a8ebfe4150bc9eea38dfbb2/tests/test_server.py#L51).

**Comment by matthewwiese** [comment]
@davidbrochart Is there an internal JupyterLab API for accessing/determining the `document_id` and `cell_idx`? For example, the best I've come up with to determine the cell index is:

```javascript
const cell_id = cell.model.sharedModel.getId();
const cell_index = cell.model.sharedModel.notebook?.cells.findIndex(cc => cc.id === cell_id);
```

Where `cell` is typed as a `CodeCell`.

Are there helper methods like `getId()` which I can use to determine the `document_id` and `cell_idx` needed for the request body?

**Comment by davidbrochart** [comment]
I'm not sure about `cell_idx`, but it seems you have something working.
For the `document_id`, you'll need to implement [this](https://github.com/jupyter-server/jupyverse/blob/a3c91996ad20fef03a8ebfe4150bc9eea38dfbb2/tests/test_server.py#L70-L81) in JupyterLab.

**Comment by matthewwiese** [comment]
@davidbrochart So I have something in a buggy state at my fork: https://github.com/matthewwiese/jupyterlab

I was able to determine the `document_id` and `cell_idx` for the `POST` to `/api/kernels/{kernel_id}/execute`. However, it requires an open WebSocket connection at `/api/yjs/{document_id}` which I am unable to reliably keep alive.

It will occasionally "just work" but more often than not you'll see in the logs:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data [serverconnection.ts:160:16]
```
 
Which is caused by the 500 response from the execute request, because there is no open WebSocket connection for that notebook. However, I am at a loss for why this is. I tried replicating the `_createSocket` logic in `KernelConnection`, but there is clearly a gap in my assumptions.

Could somebody weigh in who has more knowledge about the codebase? Perhaps I am simply not managing the Promises correctly, but I feel like something else is going on.

**Comment by davidbrochart** [comment]
That's a good start, congrats!

> However, it requires an open WebSocket connection at `/api/yjs/{document_id}` which I am unable to reliably keep alive.

So I think this endpoint has been deprecated in [this PR](https://github.com/jupyterlab/jupyter_collaboration/pull/126/files#diff-dd6f07306f19dc3b9b8647d1b0ee384dce44ce9f0bfd0a0b90090d4d880a513e). The WebSocket is now at `api/collaboration/room`. Sorry for not telling that earlier, and I think I need to update Jupyverse too.

**Comment by matthewwiese** [comment]
> The WebSocket is now at `api/collaboration/room`

Thanks for the tip! I see that change is on the `main` branch. Unfortunately, I haven't been able to get Jupyverse to run via Hatch on `main` so have been using the outdated `0.0.50` tag.

On `main` running `hatch run dev.jupyterlab:jupyverse --jupyterlab.dev_mode` gives me a `/bin/sh: jupyverse: command not found` error, which doesn't happen on `0.0.50` (using the `dev.jupyterlab-noauth` env instead, of course).

**Comment by davidbrochart** [comment]
Yes, I'm working on Jupyverse right now :smile: 
I have changed the underlying framework, I'll probably release a new version tomorrow.

**Comment by matthewwiese** [comment]
@davidbrochart Thanks for your work on this! I am now able to run the most recent version of Jupyverse (`v0.1.3`).

Is there a replacement for `--jupyterlab.dev_mode`? The code still exists but I can't figure out how to re-enable the option. In the meantime, I've just changed the default in the config and installed from `main`.

Thanks again for being so responsive on this!

**Comment by davidbrochart** [comment]
> Is there a replacement for `--jupyterlab.dev_mode`?

Yes, the CLI has changed a little bit, you now have to use `--set` to pass configuration:
```bash
jupyverse --set jupyterlab.dev_mode=true
```
Because jupyverse is now based on Asphalt, you can also run the Asphalt CLI and use the example [config.yaml](https://github.com/jupyter-server/jupyverse/blob/88b8c01a6e1e83fa9c812fba061b70dc40051b8c/config.yaml) (see [the documentation](https://asphalt.readthedocs.io/en/latest/userguide/deployment.html)):
```bash
asphalt run config.yaml
```

**Comment by matthewwiese** [comment]
@davidbrochart Thank you! One last question for the moment: is there a spec for the RTC/Yjs WebSocket messages, or is it a moving target? If the latter, where could I find the current implementation?

The reason I ask is, since I'm unfamiliar with the larger scope of this endeavor, I was wondering if the WebSocket endpoint at `api/collaboration/room` is meant to replace an existing `KernelConnection` WebSocket in JupyterLab. Are the new RTC/Yjs WebSocket messages supposed to conform to some existing format that is designed to be plug-and-play?

**Comment by davidbrochart** [comment]
I'm not sure to understand you question, but the Y protocol is defined [here](https://github.com/yjs/y-protocols/blob/master/PROTOCOL.md). We implement it in Python [here](https://github.com/y-crdt/ypy-websocket/blob/69cbc95f011e29418cd2c0904245db16b7b0fb64/ypy_websocket/yutils.py).
The goal of this new REST API is indeed to replace the kernel protocol over WebSocket. JupyterLab's frontend won't talk to the kernel anymore through low-level kernel messages, it would send higher-level requests like "execute cell 1 of the notebook". The backend will now talk to the kernel and translate that high-level request into low-level kernel messages, update the notebook with the response of the kernel, and that would automatically be synchronized with the frontend through the WebSocket endpoint at `/api/collaboration/room`. I hope this clarifies your question?

**Comment by matthewwiese** [comment]
Thank you! Your explanation does clear things up.

If I understand correctly that means the endpoint for service events (`/api/events`) will be deprecated in favor of `/api/collaboration/room`, or some other endpoint?

The reason I ask is that I want to work on receiving WebSocket messages after executing a cell with the new `POST` endpoint, and update the frontend results "live" just as JupyterLab does with the existing kernel communication method.

**Comment by matthewwiese** [comment]
@davidbrochart Hi David, would you know if `/api/events` will be deprecated in favor of `/api/collaboration/room` as per my previous comment?

Also, I may have an opportunity to spend more work hours on this in the coming weeks. What is the Jupyter team's plans for this feature in the larger roadmap? Should I join one of the [community meetings](https://docs.jupyter.org/en/latest/community/content-community.html) in order to better inform myself on how this fits into the project's goals (and ask API/spec questions)?

**Comment by davidbrochart** [comment]
I don't think `/api/event` will be deprecated, it is the endpoint for the event system IIRC, so it's independent.
There is no plan to support the new kernels REST API, I think the way to go is to show what it would look like in JupyterLab, and if people are interested then we can move forward. Feel free to join Jupyter meetings to talk about it or ask questions.
