### ISSUE TITLE
Open file restoration throws errors when starting the server in a different directory

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#1293]
I'm running into problems when I start JupyterLab from different directories. It keeps popping up errors about not finding the files that were open when I last closed it. I'm not sure how to deal with it, because I don't know of a good way to determine if the root directory is the same as when the configuration was saved.

Perhaps when a lab server starts, by default it generates a server session id and that is another key for storing the open file information - if the server session id is different, don't try to restore the open files. And perhap there can be an option to maintain the same server session id for servers that have to be restarted, but always in the same working directory.

Thoughts?

**Comment by jasongrout** [comment]
CC @minrk, @afshin

**Comment by afshin** [comment]
I didn't see this one coming. We should discuss our options, but I think the first step is failing more gracefully even if that means that a file you had open before does not open in your new session. Seeing that error is jarring.

**Comment by minrk** [comment]
Good catch! We could store a key derived from the Contents' root_dir (this would have to be provided by the server) and compare that when restoring sessions. If the key doesn't match, don't try to restore the session. Similarly, if restoring documents fails, messages produced by this could probably be demoted to console.warn (or lower), rather than dialogs. This can still happen if the root hasn't changed, but it's been a while since you launched Lab and files have moved, so we should do this one regardless.

 We've had a policy of not including the server-root directory as info available to clients, in particular because sometimes the notebooks don't come from a filesystem at all, e.g. postgres or GDrive. For this reason, the potentially desirable solution of re-resolving relative paths won't be available in general. I'd probably treat the key as an opaque blob, rather than a path. We could even use `md5(notebook_dir)` to encourage that.

**Comment by minrk** [comment]
🎉
