### ISSUE TITLE
Trademark issue with wrong use of an altered Python logo in Jupyter Lab Launcher

### ISSUE THREAD

**Issue by malemburg** [jupyterlab/jupyterlab#13023]
## Description

Hi there, I am Marc-Andre Lemburg, co-chair of the PSF Trademarks Committee. We have become aware of an issue with the use of the Python logo in Jupyter Lab:

![gafflfbmefdngbfl](https://user-images.githubusercontent.com/6735498/187185577-3361ebe5-5511-44e3-921e-b225042a63b4.png)

The blue logo changes the shape of the logo and is thus not correct use of the logo according to our trademark guidelines: https://www.python.org/psf/trademarks-faq/

Could you please replace the logo with the correct unchanged logo (as seen for other items in the screenshot) ? That would resolve the issue.

If you have questions regarding the correct use of the Python logo, please write to the PSF Trademarks Committee <psf-trademarks@python.org>.

Thank you.

## Reproduce

Open the "Launcher" in Jupyter Lab.

## Expected behavior

See above.

**Comment by krassowski** [comment]
Since the problem in principle is with shape and lack of approval, and I like the current colour as it distinguishes the Python file from Python in a notebook, I would like to propose an alternative solution:
- submit logo complying with the shape guidelines (see demo below) for approval to PSF trademark team
- if granted, update with the logo of the same colour but correct shape

To highlight the problem with the current logo:

![Screenshot from 2022-08-30 20-06-53](https://user-images.githubusercontent.com/5832902/187523342-60e27f0b-7dcc-4bab-be05-1d4c91f51cff.png)

Correct shape, colour as-is:

![python-logo-only](https://user-images.githubusercontent.com/5832902/187524272-f785e933-a74e-495e-bec7-086933349d9f.png)

I am not sure if guidelines address the usecase of the logo as in the filebrowser; due to size constraints icons of such size are commonly simplified removing some graphical elements (like the eyes of snakes in this example), which is exactly what PSF website does to its favicon:

![Screenshot from 2022-08-30 20-09-39](https://user-images.githubusercontent.com/5832902/187523257-f23e6709-f18a-40a8-9d14-0c2a8a032902.png)

If we decide to seek permission and get granted an approval to use two variants of the logo (exact shape equivalent in Launcher + simplified/no-eyes in File Browser), we would need to make some more code changes, but it should not be a problem.

@malemburg would you be able to offer an informal insight on whether you think that a permission for such a logo (with/without the simplified variant) is likely to be granted?

**Comment by DavidMertz-atlantis** [comment]
I am the other co-chair of the PSF Trademarks Committee along with Marc-André.  The version in blue that correctly maintains the shape would be great.  If the developers here agree about that, please do send a request to psf-trademarks@python.org for record keeping, but basically it *will* be approved there.

**Comment by DavidMertz** [comment]
I am the other co-chair of the PSF Trademarks Committee along with Marc-André. The version in blue that correctly maintains the shape would be great. If the developers here agree about that, please do send a request to [psf-trademarks@python.org](mailto:psf-trademarks@python.org) for record keeping, but basically it will be approved there.

**Comment by malemburg** [comment]
> @malemburg would you be able to offer an informal insight on whether you think that a permission for such a logo (with/without the simplified variant) is likely to be granted?

As long as the shape is left unchanged (within reason - at low resolutions, this can become difficult), we will be able to approve a blue only variant. Color changes are fine, as long as there is enough contrast with the background and there is a separating space between the logo and any other surrounding graphics.

Please note that changes to the shape such as removing the eyes are not permitted. The [favicon we use](https://www.python.org/favicon.ico) does have the eyes as well. If you want to create a favicon sized logo, it's probably best to start with the variants the PSF is using on the website and simply change the colors.

**Comment by ajbozarth** [comment]
The open PR https://github.com/jupyterlab/jupyterlab/pull/12673 will actually address this. It replace the Python and Markdown icons with their official icons.

**Comment by ajbozarth** [comment]
Per our discussion in our weekly dev call today I will be opening a separate PR to address this later today.

**Comment by krassowski** [comment]
We discussed this during the weekly meeting and decided by informal vote to replace the blue logo with the original icon (without changing colour to blue). There is a technical issues with gradients in our SVG system: https://github.com/jupyterlab/lumino/issues/160.

@malemburg @DavidMertz thank you for your input; would the gradient-less version as presented below (from #12673) require an approval too?

![image](https://user-images.githubusercontent.com/5832902/187732828-c4b85834-adf1-4ddd-8161-20d1a2963d59.png)

**Comment by malemburg** [comment]
Please submit this to the TM committee to have a formal record. It'll be approved.
