### ISSUE TITLE
JupyterLab 3.5.0 Release

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13064]
This is a meta issue to list enhancement candidates for the next minor release 3.5.

Please add a comment with the PRs you would like to be part of 3.5. Eligible candidates cannot break the 3.x API.

- [x] https://github.com/jupyterlab/jupyterlab/pull/12953
- [x] https://github.com/jupyterlab/jupyterlab/pull/13068 - need to release a new version of jupyterlab_server as well
- [x] https://github.com/jupyterlab/jupyterlab/pull/12342
- [x] ~~https://github.com/jupyterlab/jupyterlab/pull/13037~~
- [x] ~~https://github.com/jupyterlab/jupyterlab/pull/12959~~
- [x] ~~Add announcement feature that will use ⬆️ to tell you the user a new version exists e.g.~~
      https://github.com/jupyterlab/jupyterlab/issues/13110
- [x] Publish and use new version of Lumino 1 with deprecation for Lumino 2.
       [Lumino release](https://github.com/jupyterlab/lumino/releases/tag/v2022.10.5)  
       https://github.com/jupyterlab/jupyterlab/pull/13190
- [x] https://github.com/jupyterlab/jupyterlab/pull/13088

> This list will be frozen in 2 weeks (Sept. 21st). And the release process of 3.5.0 (creating the branch and backporting PRs) will start when the listed PRs are merged.
> Checkbox state means PR is merged in 3.5.x branch

---

Planned release schedule:

3.5.0-beta.0 has been released on October 6th
3.5.0-rc.0 will be released on October 12th
3.5.0 final will be released on October 19th

**Comment by dlqqq** [comment]
cc @ellisonbg @3coins @jweill-aws 

@fcollonval Hey, Piyush and I wanted to discuss potentially having Jupyter Server 2 support in JupyterLab 3.5. To clarify, we have several use-cases that depend on latest changes within JS2, which would be tedious to backport to JS1 (e.g. file ID, event bus, commenting, etc.). The idea is that JL 3.5 keeps JS1 as its default version, and merely adds compatibility with JS2. In our opinion, breaking changes in JS do not necessarily constitute a breaking change in JL, since how the JL application interacts with JS is an implementation detail for users.

We would like to get the team's feedback on this proposal, especially on any potential roadblocks on developing JS2 support. I'm happy to lead this effort, but I wanted to get consensus from the team on whether it's OK to have JS2 compatibility be a desired feature of JL 3.5. Thanks!

**Comment by ellisonbg** [comment]
@Zsailer

**Comment by Zsailer** [comment]
@dlqqq this is covered in the checklist above in #13068. 😎 

Once the 3.5.x branch is created, we can backport the PR to the 3.5.x branch and enable JS 2.0 in JLab 3.5.x

**Comment by krassowski** [comment]
- Are there any APIs which are dropped/changed in Lumion 2.0 and we could add a deprecation message in a new 1.x release (and include that release in JupyterLab 3.5?).
- I will try to make a push for backward-compatible scrollable tabbar this weekend.

**Comment by fcollonval** [comment]
> * Are there any APIs which are dropped/changed in Lumio 2.0 and we could add a deprecation message in a new 1.x release (and include that release in JupyterLab 3.5?).

- [BPlusTree removal](https://github.com/jupyterlab/lumino/pull/345)
- [Drag and drop rework](https://github.com/jupyterlab/lumino/pull/355)

@afshin do you see something else?

>     * I will try to make a push for backward-compatible scrollable tabbar this weekend.

🚀

**Comment by fcollonval** [comment]
Notifications and announcement are taken off to release faster a new version.

**Comment by fcollonval** [comment]
#13037 has been removed as it lacks review.

**Comment by krassowski** [comment]
Last-minute proposal: if https://github.com/jupyterlab/jupyterlab/pull/13216 gets a positive review and no concerns raised at the Wednesday meeting, it would be nice to have it in 3.5 as this is a small additive API change which could be classed as a bug fix.

**Comment by jtpio** [comment]
Closing as JupyterLab 3.5.0 final has now been released: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.5.0
