### ISSUE TITLE
Highlight all occurrences of a selected string in the whole notebook

### ISSUE THREAD

**Issue by maxima120** [jupyterlab/jupyterlab#13085]
### Problem

problem is that the way python code is normally written is very dense visually. it is so very easy to miss a variable use.

### Proposed Solution

in Notepad++ they have a simple but powerful feature. you select a string (presumably a variable name) and it got highlighted everywhere.

I know that you can Ctrl+F but it is a "heavier" approach and you need to clear it if you have something previously searched. 

I would much prefer to keep Ctrl+F as it is, separately from the proposed feature

I would like this "highlight on select" to have subtle style/colours (and different from Ctrl+F)

see the illustration:

![image](https://user-images.githubusercontent.com/10121753/189969776-9992fd3d-628e-4c74-83dd-eddcae6eb065.png)

**Comment by krassowski** [comment]
Semantic selection of tokens under the cursor is implemented in https://github.com/jupyter-lsp/jupyterlab-lsp. Simpler selection of matched string could be implemented without LSP, but LSP is already making the way into the core so I am not sure if we will want to have both.

I believe that your issue is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/6112.

**Comment by maxima120** [comment]
Thanks for heads up 6112
LSP - I hope you make it work for average users. It's a bit heavy set of features. Probably will double the size of jupyter code base.
