### ISSUE TITLE
how to upgrade the jupyter lab version in Anaconda

### ISSUE THREAD

**Issue by astronmyphy** [jupyterlab/jupyterlab#13099]
Please tell me how to upgrade the jupyter lab version, but I checked in conda that the latest version is 3.2.1, not the latest version 3.4.7.

**Comment by fcollonval** [comment]
@610069895 you can upgrade using `conda update -c conda-forge jupyterlab`. If the `update` command does not work, you can add a version constraint like `conda install -c conda-force "jupyterlab>=3.4.7".

We also have drop support of Python 3.6 starting with JupyterLab 3.3 (Python needs to be 3.7 or later). So that can explain why you are not able to upgrade. If so I can upgrade python itself - but I would advice you to create a new environment as that kind of large update may be painful.

**Comment by 610069895** [comment]
thanks
