### ISSUE TITLE
No correlation between the font color and the background color

### ISSUE THREAD

**Issue by HaudinFlorence** [jupyterlab/jupyterlab#13152]
Hi,
When working on an extension to create new themes, it appeared that currently in Jupyterlab, in the different elements of the interface, there doesn't seem to be a pre-defined link between the font color of an element including text and the underlying background color: it seems that they have been chosen independently as we can see on this screenshot (same background color for different elements but different font colors and vice versa)

![Screenshot from 2022-09-29 17-36-02](https://user-images.githubusercontent.com/99649086/193075756-0d1db513-8115-439f-bb31-f9a8ee68917f.png)

It may be useful to include some uniform rules linking font and background colors, for instance, for a given element, for a given `i`,`--jp-layout-colori` linked to `--jp-ui-font-colori`. This may help to increase the coherence of the style and the accessibility of the themes.

**Comment by jweill-aws** [comment]
@HaudinFlorence Thanks for opening this issue! Currently, [JupyterLab theme plugins](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#theme-plugins) only declare themselves as "light" or "dark" and our variables are intended to contrast with light or dark backgrounds, respectively. There are JavaScript libraries to help contrast with colors (example: https://www.npmjs.com/package/font-color-contrast) but you'd have to depend on them yourself to come up with appropriate alternate colors. I've reclassified this as an enhancement; colorful themes are something that isn't really possible right now in JupyterLab with our variables, but it could be added in the future.

Thanks again for opening this issue!

**Comment by fcollonval** [comment]
Hey @jweill-aws 

The idea here was not to create a colorful theme but to highlight inconsistencies between background color and text color. This makes it hard to create a theme that will be consistent and in particular ensure accessible contrast ratio. This could be solved if we align the CSS variables used to set the background and the color on an element. So that if a theme designer sets e.g. `--jp-layout-color2` and `--jp-ui-font-color2` (taking into account accessible rules for example) this will propagate correctly within JupyterLab core.

The colorful test of the above screenshot highlights that it is not currently the case. And therefore that makes it harder to create a consistent theme for JupyterLab.

If we consider this as a bug, the PR to solve it will mainly align color number in CSS rule without major breaking changes. Mostly diff like

```diff

-  color: var(--jp-ui-font-color2);
+  color: var(--jp-ui-font-color1);
-  background-color: var(--jp-layout-color0);
+  background-color: var(--jp-layout-color1);

```
