### ISSUE TITLE
Content Manager Path to notebook overridden by URL path in lab 

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#13155]
Consider the following dispatched contents manager created using a snippet from jupyter/notebook#3233.
```python
from notebook.services.contents.filemanager import ContentsManager
from jupyter_server.services.contents.largefilemanager import LargeFileManager
import inspect
VIRTUAL_PREFIX = 'virtual'

def make_dispatched(self, function):
    """
    This function inspects a function and dispatches it out by finding which
    arg is the path, then finding a manager to manage that path and forwarding
    this on
    """
    # functions passed here have self in it, when it's called its bound so -1 for no self
    path_idx = inspect.getargspec(function)[0].index('path') - 1

    def wrapper(*args, **kwargs):
        path = kwargs['path'] if 'path' in kwargs else args[path_idx]
        for manager in self.managers:
            if manager.manages_path(path):
                fn = getattr(manager, function.__name__)
                return fn(*args, **kwargs)
        # This self is jupyter's
        self.log.error("Could not find manager for path %s", path)
        raise Exception('Could not find manager for path "%s"' % path)

    return wrapper


class DispatchedContentsManager(LargeFileManager):
    def __init__(self, **kwargs):
        _managers = [VirtualContentsManager, DefaultContentsManager]
        self.managers = []
        for manager in _managers:
            # Init each manger with the same params
            inst = manager(**kwargs)
            if not hasattr(inst, 'manages_path'):
                raise RuntimeError('Count not find method manages_path in manager!')
            self.managers.append(inst)

        # FIXME: add support for rename_file! This does not follow the pattern below
        for name, method in inspect.getmembers(self,
                                               predicate=inspect.ismethod):
            if (not name.startswith('_') and
                        'path' in inspect.getargspec(method)[0]):
                setattr(self, name, make_dispatched(self, method))


class DefaultContentsManager(LargeFileManager):
    """
    Base contents manager that manages all paths on the filesystem
    """
    def manages_path(self, path):
        return True

class VirtualContentsManager(LargeFileManager):
    """
    Virtual Filesystem that can be used to serve files from any host 
    """

    def manages_path(self, path: str):
        path = path.strip('/')
        return path.startswith(VIRTUAL_PREFIX)

    def get(self, path: str, *args, **kwargs):
        return super().get(path.strip('/')[len(VIRTUAL_PREFIX):], *args, **kwargs)

c.ServerApp.contents_manager_class = DispatchedContentsManager
```

## Description
In the above setup, the `VirtualContentsManager` is just a pass through (in our usecase it used to get files from a different host but here it just returns the files from the same host). 

If lab is launched with the above config and we prefix a notebook path with `/virtual` (eg, `/virtual/home/$USER/Untitled.ipynb`) and inspect the requests, we can see that the path returned in response is `/home/$USER/Untitled.ipynb` which is expected.

Now, if the value of  `tracker.currentWidget.context.path` is checked, it is set to `virtual/home/$USER/Untitled.ipynb` instead of what is returned by contents manager (which ends up being used for any operations like `save`).

Due to this, we need to send a request to the contents manager to get what the actual path of a notebook is.

Also, this works fine in notebook(`nbclassic`). ie. the path used for any requests is the path returned from the contents manager not the path from the url.

The main issue here is how can we get the path returned by the contents manager in the front end apis. 

Here are a few screenshots to show this - 
1. Request sent to `/virtual/home/$USER/Untitled.ipynb` (expected) - 
![image](https://user-images.githubusercontent.com/30082866/193196338-dc8862b1-0379-4425-811d-203917978750.png)
2. Response has the correct path (ie. `home/$USER/Untitled.ipynb`) (expected) -
![image](https://user-images.githubusercontent.com/30082866/193196610-f2e18061-0f8c-4bb4-ac5a-285e6cc129ec.png)

## Reproduce

1. Paste the above code snippet in `~/.jupyter/jupyter_server_config.py`
2. Navigate to any notebook
5. Reload the page by prefixing the path with `/virtual`
6. Try saving the notebook.
7. Repeat the same in notebook to see the difference in behavior

## Expected behavior
I would expect the path from the contents manager to be given higher priority. 

## Context
I am writing a front end extension where I need the actual path of the notebook (the one returned from the contents manager). To do this, I'm unable to use `tracker.currentWidget.context.path` and instead I need to send a request to the contents manager which introduces delay in the extension.

**Comment by krassowski** [comment]
> Now, if the value of `tracker.currentWidget.context.path` is checked, it is set to `virtual/home/$USER/Untitled.ipynb` instead of what is returned by contents manager (which ends up being used for any operations like save).
>
> Due to this, we need to send a request to the contents manager to get what the actual path of a notebook is.

I see how this is problematic. JupyterLab contents API client is not systematic here, for some endpoints it keeps the path returned by the server:

https://github.com/jupyterlab/jupyterlab/blob/65b4d7e727aed343160d81fad7f1871758ff7f22/packages/services/src/contents/index.ts#L845-L858

but for other it retains the path used in the request:

https://github.com/jupyterlab/jupyterlab/blob/65b4d7e727aed343160d81fad7f1871758ff7f22/packages/services/src/contents/index.ts#L792-L804

It seems to me that the possibility of the ContentsManager returning a different path than that in the original request was not a major consideration during the original implementation of this service client because the described functionality of virtual file system can be also implemented using the `IDrive` API. Do I understand correctly that `IDrive` API is not a solution as compatibility with classic notebook (<v7) is required?

The options I see are:
- a) "just" use the path returned by the server in `Contents.IModel.path`
   - this may not be what is expected, as any subsequent action on the file will lack the `/virtual` prefix which means that the DispatchedContentsManager will no longer know how to route the requests
   - from a quick local test it does not seem feasible without extensive codebase modifications due to some non-documented assumptions on what the returned path is
- b) keep `Contents.IModel.path` as is, add new `Contents.IModel.serverPath` which will keep the returned by API from ContentsManager:
   - does not require any other changes, backward-compatible with extensions
   - behaves differently than notebook <v7
- c) make `Contents.IModel.path` always reflect the path returned from server, and introduce a new `Contents.IModel.clientPath` which would take the function of today's `Contents.IModel.path` (in the above example always remembering about `/virtual` prefix)
   - even if we carefully swap `path` with `clientPath` in our codebase, it could break some extensions

**Comment by divyansshhh** [comment]
>Do I understand correctly that IDrive API is not a solution as compatibility with classic notebook (<v7) is required?

Yes, classic notebook compatibility is required for us.

**Comment by vidartf** [comment]
To bring in some context here, here are the docs for the contents API: https://jupyter-server.readthedocs.io/en/latest/developers/contents.html#data-model . There it says about the model's `path` that it should be:
> Full ([API-style](https://jupyter-server.readthedocs.io/en/latest/developers/contents.html#apipaths)) path to the entity.

As such, I would argue that the contents manager implementation used above is not really following the specification. The tests of jupyter-server also checks that the `path` returned by the contents managers' API are the same as was requested:

https://github.com/jupyter-server/jupyter_server/blob/1957aa0416c8467961198fa2dd6f930aca106f85/tests/services/contents/test_api.py#L92-L160

So I would recommend that anyone that wants to rely on the returned `path` differing from what was provided originally are wading into "undefined behavior" territory.
