### ISSUE TITLE
Open files directly from tracebacks

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#13277]
### Problem
Google Colab has a handy feature which allows the user to jump to the file which caused an error directly from the traceback. Here's how this looks - 
![image](https://user-images.githubusercontent.com/30082866/196870101-51b87f56-7c1b-4b75-8811-af8b8bf61b82.png)
I find this really useful and I think it should also be supported in JupyterLab.

### Proposed Solution

It should be possible to modify the `renderText`  (or create a new method altogether) method to have an `ILinkHandler` and `ISanitizer`. The `sanitizer` can take care of wrapping the paths in anchors and the `linkHandler` can handle opening of the file in a sidepanel.

**Comment by krassowski** [comment]
> The sanitizer can take care of wrapping the paths in anchors

Not sure why sanitizer would be responsible for this? One option is to extend `autolink` as used in:

https://github.com/jupyterlab/jupyterlab/blob/3b7a6557352b2a77ce36da46a33fd09f83663507/packages/rendermime/src/renderers.ts#L684

Or to make a second function (`autolinkPaths`?).

Using `ILinkHandler` here sounds like a good idea at first glance.

**Comment by krassowski** [comment]
> modify the `renderText` (or create a new method altogether)

We could have a new `renderError` method which would only be used for outputs with MIME type `application/vnd.jupyter.stderr`. It is probably a good idea, otherwise we may see a slowdown when rendering non-traceback text outputs as there would be an extra penalty for searching large outputs for presence of things which look like path references.
