### ISSUE TITLE
Run terminal commands from launcher

### ISSUE THREAD

**Issue by vivian-rook** [jupyterlab/jupyterlab#13393]
I'm looking to make a jupyterlab extension that would install an arbitrary plugin. The intention being that a user could install R, or openrefine without having to load these into the container image before hand. As such I'm looking for guidance on how one can run arbitrary commands from an extension.
https://github.com/jupyterlab/jupyterlab/issues/5759 suggests that this was possible. Though some of the imports lack the modules they are listed as exporting in that code. So have perhaps been removed.
https://discourse.jupyter.org/t/run-a-command-line-from-a-jupyterlab-extension/3157 also suggests that functions may have been removed.

Is it possible to make an extension that can run arbitrary commands in the container? If so is there documentation or examples on how that might be done?

**Comment by afshin** [comment]
Thanks for opening this issue. You can absolutely write an extension that does this. One way would be to use the [extension cookiecutter](https://github.com/jupyterlab/mimerender-cookiecutter-ts) to create an extension that contains both a front-end JupyterLab extension *and* a back-end Jupyter server extension:

- In the front-end extension, you could add a button the launcher that invokes a command you have created to make a web request to a REST API endpoint you have defined with whatever parameters are necessary.
- In the server extension, you can define a REST API endpoint that executes arbitrary code (including potentially executing a shell scrip) on the server.

Since this isn't exactly an enhancement request in JupyterLab, but rather an extension authoring question, let's close the issue here. But please feel free to come to our [weekly meetings](https://github.com/jupyterlab/jupyterlab/#weekly-dev-meeting) or to post a question on our [forum](https://discourse.jupyter.org/c/jupyterlab/) or our [chat](https://gitter.im/jupyterlab/jupyterlab) if your run into roadblocks authoring your extension.

Good luck!
