### ISSUE TITLE
Request visual preview of features being introduced in Pull Requests

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/jupyterlab#13401]
### Problem

When I'm reviewing a Pull Request (PR) for a new feature for the sake of speed and convenience I want to see a visual preview (preferably GIF or video but at least screenshots) of changes being introduced (if there are any)

### Proposed Solution

Update jupyterlab PR template (https://github.com/jupyterlab/jupyterlab/blob/master/.github/pull_request_template.md) to encourage/expect one
<!-- Provide a clear and concise description of a way to accomplish what you want. For example:

**Comment by krassowski** [comment]
The template you linked already includes an encouragement to include screenshots under "User-facing changes":

```
<!-- Describe any visual or user interaction changes and how they address the issue. -->

<!-- For visual changes, include before and after screenshots here. -->
```

If we were to change something, I would say that maybe each major UI addition should include a documentation screenshot. This way we will both document the state of the feature when the PR was merged AND ensure that the accurate information is exposed to the users in documentation.

In past users reported that a feature X has gone missing because they saw it in a screenshot in a PR but it is no longer here; in one case the PR author changed placement of an icon but forgot to update the screenshot (the feature was still there).

When I work on minor visual changes in my own time and while I try to provide GIFs but the software that I use sometimes has issues so I defer to screenshots. If animations were a requirement, I would probably not open some of the PRs as I would be stuck figuring out how fix the recording.

**Comment by andrii-i** [comment]
> The template you linked already includes an encouragement to include screenshots under "User-facing changes":
> 
> When I work on minor visual changes in my own time and while I try to provide GIFs but the software that I use sometimes has issues so I defer to screenshots. If animations were a requirement, I would probably not open some of the PRs as I would be stuck figuring out how fix the recording.

These are really good points. It should not be a hard requirement for sure. How would you feel about mentioning this as an option and providing guidance e.g. text below?
