### ISSUE TITLE
Check links timeout on CI 

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13438]
## Description

The `check_links` CI check has been timing out on CI lately.

## Reproduce

Example run: https://github.com/jupyterlab/jupyterlab/actions/runs/3489065666/jobs/5838690911

![image](https://user-images.githubusercontent.com/591645/202549787-76f347ce-4ea5-4400-bf2c-84cebfa4287b.png)

## Expected behavior

It should pass like before.

## Context

Happening on the latest commits and PRs.

**Comment by fcollonval** [comment]
The trouble is due to a broken link; see [log](https://github.com/jupyterlab/jupyterlab/actions/runs/3495798323/jobs/5852968433):

Error: /home/runner/work/jupyterlab/jupyterlab/docs/source/extension/internationalization.rst: https://www.labri.fr/perso/fleury/posts/programming/a-quick-gettext-tutorial.html

That page does not seem to load but it does not raise any error neither. Hence the error I guess. I'll open a PR
