### ISSUE TITLE
Explore monaco editor integration

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#135]
Looks like Monaco is easy to embed and use now:

https://github.com/Microsoft/monaco-editor

**Comment by blink1073** [comment]
We could try it in the editor plugin with minimal impact to evaluate it.  Switching the cell editors is more involved, and "codemirror_mode" is even baked into the kernel spec: http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-info.

**Comment by minrk** [comment]
codemirror_mode is only ever defined by kernels for which language name + mime-type + file extension still isn't enough information to pick an editor mode. If we adopted a new editor, we would need something similar to cover those weird cases.

**Comment by eskirk** [comment]
Could this be a potential replacement to the potential changes to the editor in #189? I would be down to try and implement this.

**Comment by blink1073** [comment]
Perhaps, but not until after SciPy I'd say.

**Comment by svenefftinge** [comment]
We have monaco (and code mirror) working in jupyterlab, based on the editor abstract @akosyakov has been working on (see #753). 
Are you interested in a contribution?

**Comment by jasongrout** [comment]
Yes! Nice, thanks! I'm going to look at #753 tomorrow (ran out of time today...)

It'd also be great to have you in on conversations on third party extensions: #728. Do you want to join the JupyterLab dev meeting tomorrow? 4pm UTC on blujeans.com/jupyter/

**Comment by jasongrout** [comment]
(and it may be that the monaco integration lives as a separate plugin for now. Let's review #728 first.)

**Comment by svenefftinge** [comment]
Yes, we will join.

**Comment by TiemenSch** [comment]
What's the current status on this? Quite some time has passed since the last updates and most related issues are referenced here and there, but I can't seem to find what would be needed to make this work. , I see several notions of it being used (and having its own issues in the list).

I'm eager to start writing my own JupyterLab extension for a custom language and as I'm already heavily using VS Code, Monaco would be an awesome editor to use on the web front-end.

**Comment by jasongrout** [comment]
If I recall correctly, the last exploration with this determined that Monaco required an amd module loader to load js (at the time, which I believe was something in mid-2017?). @blink1073 I think was the last to look at this.

The open question was: can Monaco be bundled *without* depending on an AMD loader. Looking briefly at the monaco repo now, it does appear that they have a webpack-friendly ESM module version. How comfortable would you be exploring to see if you can make a plugin which provides monaco to JupyterLab?

**Comment by jasongrout** [comment]
I think the last attempt is documented in https://github.com/jupyterlab/jupyterlab/pull/1382

**Comment by jwkvam** [comment]
If this does happen I think the vim users would be disappointed, https://github.com/Microsoft/monaco-editor/issues/182.

**Comment by TiemenSch** [comment]
Well, based on the current lines of thought, I think these implementations would live alongside each other as plugins. It aims towards an editor agnostic approach of JupyterLab. This focuses each repo on the function it needs to do best. As such, any future web-editor could be implemented using the same mechanics that should become exposed by JupyterLab.

**Comment by jasongrout** [comment]
FYI, I'm working on a proof-of-concept extension this morning.

**Comment by jasongrout** [comment]
I put up a repo: https://github.com/jupyterlab/jupyterlab-monaco

<img width="537" alt="screen shot 2018-04-17 at 4 18 34 pm" src="https://user-images.githubusercontent.com/192614/38904617-453d8afc-4260-11e8-9d69-e6fc88fd78c0.png">

**Comment by vidartf** [comment]
CC @akosyakov, you might have some useful input here, now that Monaco is webpackable?

**Comment by TiemenSch** [comment]
Correct me if I'm wrong: is this how it's structured?

JupyterLab codeeditor package: defines abstract access to the code editor that is loaded by JupyterLab:
https://github.com/jupyterlab/jupyterlab/tree/master/packages/codeeditor
^ This is what we should hook up the Monaco editor's to in the new package.

JupyterLab codemirror package: default codemirror implementation of the above.
https://github.com/jupyterlab/jupyterlab/tree/master/packages/codemirror
^ This is what we're trying to replicate, but then using Monaco. 

JupyterLab fileeditor package: example of usage of JupyterLab/codeeditor package
https://github.com/jupyterlab/jupyterlab/tree/master/packages/fileeditor
An example which just imports the "CodeEditor", agnostic to which editor it actually is (as long as it can expect the functionality of the /codeeditor package). 

However, there are cases where codemirror's files are still explicitly imported (like the cell editor). Some functionality just default to codemirror's if not supplied otherwise, but that could indicate that there's room for moving the functionality description to /codeeditor instead (thus becoming even more editor agnostic).

**Comment by jasongrout** [comment]
> is this how it's structured?

Basically, yes.

> If that's correct, trying to get the file editor to work (as that one seems to be completely editor agnostic) would be the first place to start, right?

Yes. I just pushed some updates with a slightly easier update - just editing files, without implementing the abstract editor interface.

**Comment by TiemenSch** [comment]
Hmm, I can't get your repo to work yet. I must be doing something wrong.

**Comment by jasongrout** [comment]
What did you try to do? What didn't work?

**Comment by TiemenSch** [comment]
I was short on time after all my attempts, sorry for not being more detailed in my comment. 

I've tried to explain it over on the repo:
https://github.com/jupyterlab/jupyterlab-monaco/issues/5

**Comment by CavalloneChen** [comment]
Please consider replacing codemirror with monaco. The whole experience of monaco is just more comfortable.
