### ISSUE TITLE
Bring consistency to the tooltips of the toolbar actions

### ISSUE THREAD

**Issue by GabrielaVives** [jupyterlab/jupyterlab#13503]
### Problem

The tooltips of the toolbar actions are either inconsistent, or do not correctly  represent the action they represent.
For example, some refer to "cells" even though the action will apply only to one cell. This can create misunderstandings for new users, and can be easily fixed.

### Proposed Solution

Change the tooltips as in the illustration below:

![Consistent tooltips](https://user-images.githubusercontent.com/105775162/204349730-b6e4c0b1-c15e-4755-ab4f-536c6c7a0f35.png)

(With the keyboard shortcuts between the brackets at the end of each tooltip).

### Additional context

Providing short and explicit tooltips is always necessary when a button does not have an explicit title, as for icons. Here, some UX basic rules are not followed but require a very low effort to significantly improve the user experience.

Here are some rules we should follow, that I illustrated in the suggestion above:
- Use first letter upper case only
- Be short: if possible, no more than 3 words
- Provide the keyboard shortcut if it exists
- Be consistent between 2 opposite actions

**Comment by krassowski** [comment]
I think the convention is `Title Case` for labels and `Upper case` for captions.

As mentioned on the triage meeting, it is because some commands define both `label` and `caption` while others only define a `label` (and we use `caption` if available and otherwise the `label`), for example `notebook:insert-cell-below` implements both:

https://github.com/jupyterlab/jupyterlab/blob/6efbd56dcc8b58e799036760d4a7862233803037/packages/notebook-extension/src/index.ts#L2338-L2350

but  `notebook:insert-cell-above` only implements `label`:

https://github.com/jupyterlab/jupyterlab/blob/6efbd56dcc8b58e799036760d4a7862233803037/packages/notebook-extension/src/index.ts#L2326-L2337

This can be fixed by ensuring that all relevant commands have consistent `caption`s.

For "duplicate cells" command, the "selection" bit can be relevant as it defined the behaviour when multiple cells are selected. We could assign a function to caption and only mention "selection" when multiple cells are indeed selected.

**Comment by GabrielaVives** [comment]
Thank you for looking in to this!

I didn't know what `label` and `caption` refer to inside the code, or what conventions are used. If it could follow the UX convention to use `lower case` for tooltips (except the first letter of course), that would be great. So that from the user's point of view, everything looks consistent.

For further information, here is the [material design documentation on tooltips](https://m2.material.io/components/tooltips) explaining what the best practices are.

**Comment by fcollonval** [comment]
cc @HaudinFlorence

**Comment by HaudinFlorence** [comment]
I am looking at this issue and opened this PR https://github.com/jupyterlab/jupyterlab/pull/13861.

**Comment by JasonWeill** [comment]
Related: in PR #13939, I added captions to several toolbar buttons that lacked them. A label is typically written in Title Case without articles (e.g., "Interrupt Kernel") and a caption is typically written in sentence case with articles (e.g., "Interrupt the kernel").
