### ISSUE TITLE
Cell `source_hidden` metadata is not effective on loading a notebook.

### ISSUE THREAD

**Issue by yczhangsjtu** [jupyterlab/jupyterlab#13569]
## Description

A cell whose input is hidden does not stay hidden after the notebook is closed and reopened.

## Reproduce
1. Create a new notebook, create a new cell, input `print("Hello world")`, and execute it.
2. Then click the left side to hide the source, and save the notebook.
3. Close the notebook, and open it again. The source code is still visible.

## Expected Behavior

The source code should remain hidden.

## Context

jupyterlab >= 4.0.0a31

## Proposed Solution

The root cause seems to be that, on loading the notebook, the following code is executed before the cell is ready, when `this.placeholder` is `true`. Perhaps should enclose the entire block by `this.ready.then(() { })`?

https://github.com/jupyterlab/jupyterlab/blob/e658b6f28e3501968e7fe8e211677c5378be14d0/packages/cells/src/widget.ts#L421-L430

**Comment by jweill-aws** [comment]
I'm not seeing this in JupyterLab 3.5.1; this may be a regression in 4.

**Comment by jweill-aws** [comment]
@fcollonval Possible regression in JupyterLab 4?

**Comment by fcollonval** [comment]
The mentioned code is related to the windowing feature (only in v4).

@yczhangsjtu thanks for digging up. As `this.placeholder` is `false` when `ready` is resolved, I guess the fix is to change the statement order at:

https://github.com/jupyterlab/jupyterlab/blob/e658b6f28e3501968e7fe8e211677c5378be14d0/packages/cells/src/widget.ts#L266-L273

Would you be willing to open a PR with the following fix and test it indeed solves the issue?

```ts
 protected set placeholder(v: boolean) { 
   if (v === false) { 
     this.initializeDOM();
     this._placeholder = v; 
     this._ready.resolve();
   } 
 }
```

**Comment by yczhangsjtu** [comment]
No. This does not solve the issue, but causes exceptions.

```
Uncaught TypeError: Cannot read properties of null (reading 'isHidden')
    at CodeCell.handleInputHidden (widget.ts:1264:47)
    at set inputHidden [as inputHidden] (widget.ts:434:10)
    at InputCollapser.handleClick (collapser.tsx:101:23)
    at onClick (collapser.tsx:62:59)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
```

I guess it is because when `initializeDOM()` is called without the placeholder being set, the `initializeDOM()` function will try to read properties from uninitialized cells.

**Comment by fcollonval** [comment]
Indeed my guess was wrong as indeed the order is correct due to that line in `initializeDOM`:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/cells/src/widget.ts#L998

Would you mind reporting the Javascript error you are seeing using master (or a stable JupyterLab 4 pre release) version?

**Comment by yczhangsjtu** [comment]
The above Javascript error is what I got in Chrome in the up-to-date master (commit f15709ff4) branch after I switched the two lines.

**Comment by yczhangsjtu** [comment]
Enclosing these code in `this.ready.then()` does solve the problem, for me. But I'm not sure. Will it cause problems elsewhere?

https://github.com/jupyterlab/jupyterlab/blob/e658b6f28e3501968e7fe8e211677c5378be14d0/packages/cells/src/widget.ts#L421-L430

**Comment by fcollonval** [comment]
Could you please open a PR with that fix?
