### ISSUE TITLE
List all plugins within JupyterLab

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13750]
### Problem

It is possible to enable/disable plugins from the command line. But it is hard to find the plugin names - especially because the name does not have to follow some convention; especially true for third-party extensions.

### Proposed Solution

It will be nice to add a new widget listing all plugins (and their description - as this is now [available](https://github.com/jupyterlab/lumino/pull/419) in Lumino). The widget could for example be displayed from the help menu.

The code could get inspiration from https://github.com/jupyterlab-contrib/jupyterlab-plugin-graph - but we should not import the graph feature; or at the expense of using for example d3 that is already a dependency rather than the huge [cytoscape](https://www.npmjs.com/package/cytoscape) package.

**Comment by jtpio** [comment]
Thanks @fcollonval for opening this.

> The code could get inspiration from https://github.com/jupyterlab-contrib/jupyterlab-plugin-graph - but we should not import the graph feature; or at the expense of using for example d3 that is already a dependency rather than the huge [cytoscape](https://www.npmjs.com/package/cytoscape) package.

Yes agree the graph could be reworked. If anyone would like to bring the code in core JupyterLab, that would be great!

We could also iterate in https://github.com/jupyterlab-contrib/jupyterlab-plugin-graph first if needed (which could also be faster), by updating the extension to target 3.6 or whatever version is using the latest Lumino 1.x.

**Comment by jtpio** [comment]
Thinking this could also be useful to have in Notebook 7. Currently https://github.com/jupyterlab-contrib/jupyterlab-plugin-graph does not show up in Notebook 7 because the graph widget is added to the main area. But it could use https://github.com/jupyterlab/jupyterlab/pull/11614 to place somewhere else.

**Comment by suganya-sk** [comment]
I could be missing something really obvious here, but can I ask how this would be different from the Extension manager UI, which has a dedicated section for the installed plugins?

**Comment by fcollonval** [comment]
> I could be missing something really obvious here, but can I ask how this would be different from the Extension manager UI, which has a dedicated section for the installed plugins?

The extension manager allows to deal with extensions that can bundled multiple plugins. And it will not list the core plugins. For administrators, being able to quickly see in their configuration all plugins (core and extensions) hopefully will help to tune their installation.

**Comment by suganya-sk** [comment]
Ah, got it. Thanks for the clarification.

**Comment by bollwyvl** [comment]
I _don't_ think adding a "blessed" graphing library makes a lot of sense. `d3` comes in through vega, fine, but there are simply too many of them based on `d3` or otherwise to pick a "winner" that _everyone_ will have to download.

Having a solid, filtered, table-based view with a CSV/JSON export from the running app would likely be an ideal initial PR. And indeed, this is _basically_ already what _Help &raquo; Licenses_ does at the "bundle" level, so it could become some additional, filterable facet of that existing implementation.

Semi-related: we're looking at this on [a new widget library](https://github.com/jupyrdf/ipyforcegraph/) based on [force-graph](https://www.npmjs.com/package/force-graph) and [3d-force-graph](https://www.npmjs.com/package/3d-force-graph). As we're trying to get to a few thousand nodes for demos, we're considering digging around through private variables to be able to show:
- for each installed bundle 
  - dependencies with licenses
- for each installed plugins
  - `provides` 
  - `consumes`
  - digging around for signals
    - digging around for receivers

Some additional excellent data would be:
- how long each plugin takes to `activate` (this would be lovely for sizing nodes), akin to https://github.com/jupyter-server/jupyter_server/pull/1171

The funny bit is even without rendering it, this data will come back as `pandas.DataFrame`s of `nodes` and `links`, which would allow _any_ kernel-based visualization library to work with it... and indeed, for some of the heavier labs out there, you might _need_ offline rendering with e.g. DataShader or gephi.

**Comment by HaudinFlorence** [comment]
Hello @fcollonval I can try to propose a PR with a simple widget accessible from the help menu or from the left panel. This widget will list the names of the core and external extensions, with their description when completed. Note that external extensions are not always coming with a description. Would be great to make it a mandatory parameter (maybe it is I don't know precisely).

**Comment by fcollonval** [comment]
> Hello.@fcollonval I can try to propose a PR with a simple widget accessible from the help menu or from the left panel. This widget will list the names of the core and external extensions, with their description when existing. Note that external extensions are not always coming with a description. Would be great to make it a mandatory parameter (maybe it is I don't know precisely).

Sure go ahead. Instead of adding the entry to the help menu, it could be good to add it to the extension manager side panel; like adding ... button at the top of the panel to display advanced menu entries.

You could try to use a table as suggested by Nick (reusing the one of the licenses display would be awesome).

**Comment by bollwyvl** [comment]
> accessible from the help menu

yep, this seems like the right place, for now

> extension manager side panel

i think perhaps that conflating _what plugins within what extensions am i running_ with _maybe enable some settings, make some third-party requests, install new extensions, which have no metadata telling you what plugins they provide_ is probably not as helpful.

if such a UI _did_ allow enabling/disabling extensions, then it should probably go in settings editor, but this is partially inaccurate, as not all plugins provide settings, and there's no required correspondence between plugin names and settings namespaces.

**Comment by krassowski** [comment]
@HaudinFlorence sorry I missed your message. I was already far underway implementing the UI which lists and allows enabling/disabling individual for some weeks. The draft PR is in https://github.com/jupyterlab/jupyterlab/pull/14536 and earlier happened in https://github.com/jupyterlab/jupyterlab/issues/14175. I would love your feedback over on #14536.

> if such a UI did allow enabling/disabling extensions, then it should probably go in settings editor, but this is partially inaccurate, as not all plugins provide settings

then it would not be possible to disable Setting Editor, which is why I went for a separate package altogether in #14536.

**Comment by HaudinFlorence** [comment]
@krassowski Thanks for sharing the draft PR. I will try it.
