### ISSUE TITLE
Switching tabs in the main panel does not activate a widget for a selected tab

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#1386]

**Comment by akosyakov** [comment]
It seems to be an issue in our product not in JLab.

**Comment by akosyakov** [comment]
Nope actually it seems to work in JLab just because the console, the notebook and the editor widget calls focus on the code editor on activate. For any other plugin which does not force focus it does not work.

**Comment by sccolbert** [comment]
This cannot be solved holistically. Each widget will be different with a different internal node that should be focused. A widget gets an `activate-request` message when it's tab is selected, and so it should reimplement `onActivateRequest` to do the right thing and focus the relevant node.

This really just needs to be documented as something a plugin author *must do* when writing their widget.

**Comment by sccolbert** [comment]
I'm going to close this issue, but we should open a new issue for each plugin which is not doing the "right thing".

**Comment by akosyakov** [comment]
@sccolbert in most cases we just call `node.focus`. Why cannot it be default?

**Comment by sccolbert** [comment]
@akosyakov Because it's actually a rare case that the node which should actually take input focus is the root node of the widget. There will typically be some input field or button within the widget which is the thing with focus. There will also be lots of cases where the content of the widget will have multiple focusable nodes (like a long form or something) and the widget, when activated, should restore focus to the element which was last focused.

The other point is that `activate-request` doesn't necessarily denote focus. It means: "the user just expressed interest in your widget, you should do something appropriate". In a dock panel, that *does* mean the widget should focus itself, because that's how we track the "active" tab among multiple visible tabs.

**Comment by sccolbert** [comment]
Also, simply calling `node.focus()` is not enough. The node itself must be focusable, which means your widget would have to set `tabIndex = -1` and then disable the CSS outline to remove the focus box. That's a lot of things to make default, just for someone to undo when they don't like that default.

**Comment by akosyakov** [comment]
Could it be solved without focusing then? Would it be possible to update `shell.currentWidget` on the tab click? What if a widget does not need to focus anything, does it mean it never gets activated?

**Comment by sccolbert** [comment]
We talked about this exact issue with the team. `shell.currentWidget` is based on tracking focus, which is typically what you want. If we tracked tab clicks, then it won't do the right thing when the user clicks an input field within the widget content. Rather than track *both* focus and tab click, and trying to deduplicate the work when focus results from tab click, we decided that the plugin author should just give their widget focus as a *must do* thing. *Most* widgets will want to handle focus anyway. It's the minority of content which will not care about focus and will have to do a little bit of extra work.

**Comment by akosyakov** [comment]
I've copy pasted `node.focus` + `tabIndex = -1` 3 times today.

**Comment by sccolbert** [comment]
> I've copy pasted node.focus + tabIndex = -1 3 times today. Thanks for outline: none; hint.

Roll that up into a base class ;)

**Comment by sccolbert** [comment]
The other thing to keep in mind. Phosphor is a toolkit for more than just JupyterLab. So while *you* may need this behavior a lot because of what your are doing with JLab, it may not be the right default decision across the board. 

It's the same thing with the default CSS supplied by Phosphor. It's the *bare minimum* to make things work, because anything more than that would require someone to undo the default, which is much harder than just not providing the default in the first place.
