### ISSUE TITLE
Notebook trust is different compared to the Classic Notebook

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14025]
## Description

In JupyterLab notebooks are shown as not trusted when they are created from the UI and opened in the main area.

With the classic notebook, notebook are shown as trusted when they are created from the file browser page and opened in a new browser tab.

## Reproduce

Here are a couple of screencasts showing how the trust indicator is handled differently between JupyterLab and the Classic Notebook:

**JupyterLab 4.0.0a34**

https://user-images.githubusercontent.com/591645/219586250-9aab511f-a2e6-4b3a-ae74-c104aa104011.mp4

**Classic Notebook 6.5.2**

https://user-images.githubusercontent.com/591645/219586232-19c12b7a-5274-4629-a8fb-42baaacfceeb.mp4

## Expected behavior

Not sure

## Context

This was noticed while adding the trust indicator to Notebook 7: https://github.com/jupyter/notebook/pull/6736

- Operating System and version: Fedora 37
- Browser and version: Firefox
- JupyterLab version: 4.0.0a34

**Comment by jtpio** [comment]
Adding to 4.0 for consideration since it falls into the "Feature Parity" category.

I'm not sure whether this difference is intentional and by design, or a regression.

**Comment by krassowski** [comment]
This is also extends to new cells created after trusting notebook:

![trust-for-new-cells-missing](https://user-images.githubusercontent.com/5832902/219947124-cdff6817-ba4e-4e54-bd08-dd4173c6c380.gif)

**Comment by krassowski** [comment]
I believe we should _mostly_ implement the classic notebook behaviour. The old specification says:

> -  **Outputs** generated by the user are trusted

and:

> Once a user decides to execute code in a notebook, it is considered trusted, and should be allowed to do anything.

Currently we do not set trusted status for new cells at creation time. Instead, we only set `trusted` status only after execution of cells. This leads to discrepancy between UX and the trust indicator. Details in next comment.

**Comment by krassowski** [comment]
Comparing the Classic Notebook with JupyterLab behaviour:
1. We should mark cell as trusted:
   - if user creates it manually (as it has not output)
   - if it is a first (blank) cell in a new notebook
2. We should NOT mark a cell as trusted if user pastes untusted cell from another notebook:
   - this was not specified for Classic notebook as there was no UI for this action
   - because we copy metadata, we also copy trust status so we are already good here, just need a test
4. In agreement with the old specification we already mark a cells as trusted once user executes it.
    - In Classic Notebook this was implemented by [implicitly trusting outputs](https://github.com/jupyter/nbclassic/blob/7b64f4617ae21cee0acc5b6968a390f5b12171d5/nbclassic/static/notebook/js/outputarea.js#LL31) created by user and then copying outputs trust to [cell metadata during serialization](https://github.com/jupyter/nbclassic/blob/7b64f4617ae21cee0acc5b6968a390f5b12171d5/nbclassic/static/notebook/js/codecell.js#L584)
    - In JupyterLab we instead explicitly trust entire cell when it is executed, implemented here:
    https://github.com/jupyterlab/jupyterlab/blob/91751d133da99465ce0ef4f882e82a3f9de3b28d/packages/cells/src/widget.ts#L1445-L1446
    I feel uncomfortable with this behaviour and would prefer to see a dialog asking whether I wan to trust the output.
5. According to specification we should trust all cells without outputs. For that reason Classic Notebook sets cell as trusted when clearing outputs (in [`clear_output`](https://github.com/jupyter/nbclassic/blob/7b64f4617ae21cee0acc5b6968a390f5b12171d5/nbclassic/static/notebook/js/outputarea.js#L1017)), but JupyterLab does not:
    https://github.com/jupyterlab/jupyterlab/blob/91751d133da99465ce0ef4f882e82a3f9de3b28d/packages/cells/src/model.ts#L604-L609


I believe that (3) makes the work with JupyterLab similar enough to classic Notebook that users have not complained about the discrepancy in (1) and (5) which only is noticeable if:
- user looks at the trusted indicator which is much less pronounced in JupyterLab for (1)
- user has deep knowledge of Notebook trust mechanism and has a notebook with mixed state of trusted and untrusted cells and tries to fix it by clearing some outputs for (5)

**Comment by krassowski** [comment]
As a side, note there is 5th behaviour that we need to adjust:

5. When notebook is saved and includes a blank markdown cell the signature computation is wrong which leads to issue https://github.com/jupyterlab/jupyterlab/issues/12889

**Comment by Carreau** [comment]
Just to be clear, right now nbformat emit (or at least should emit) a warning, though it will in the future simply raise if what is sent is invalid.

**Comment by ellisonbg** [comment]
Hmmm, I don't recall why the behavior would be different in Lab. Agree it should be the same.

**Comment by JasonWeill** [comment]
@krassowski Do you have time to work on this issue? It looks like a blocker for both Lab 4.0.0 and Notebook 7.0.0, per discussion at the Lab meeting today.
