### ISSUE TITLE
Installation of some extensions found in "DISCOVER" section of Extension Manager results in "Build Failed" error

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/jupyterlab#14032]
## Description

"DISCOVER" section of Extension Manager shows extensions that are pre-built and that can't be installed through Extension Manager interface. Because of this installation of some extensions found in "DISCOVER" section of Extension Manager results in "Build Failed" error. As a result, it's hard to discover working extensions in "DISCOVER" section.

## Reproduce

1. Go to Extension Manager
2. Attempt to install any extension (for example, '[jupyterlab_urdf](https://github.com/ihuicatl/jupyterlab_urdf)')
3. See 'Build Failed' error that persists until extension is removed

![ext_man](https://user-images.githubusercontent.com/26686070/219843463-e949d3a7-3ad1-4d43-8a18-4dfb75c947b2.gif)

## Expected behavior

It's possible to easily find installable extensions in "DISCOVER" section (seeing only installable extensions or having installable extensions marked in some manner would be help).

## Context

Operating System and version: MacOS 12.6.3
Browser and version: Chrome version 109.0.5414.87 (Official Build) (arm64)
JupyterLab version: head-of-master (WIP 4.0.0)

**Comment by krassowski** [comment]
> JupyterLab version: head-of-master (WIP 4.0.0)

Is this really tip of master branch? We switched extension manager to use PyPI which:
- a) looks differently (screenshot below)
- b) does not require the build step

![Screenshot from 2023-02-18 11-35-30](https://user-images.githubusercontent.com/5832902/219858151-43b24611-b875-4009-bb64-9505a40c276a.png)

> seeing only installable extensions or having installable extensions marked in some manner would be help

Improvements here are always welcome but ultimately we are not controlling the third party extensions and there will always be a way for a third-party author to corrupt the installation process, whatever preventative measures we choose to apply. The only way to really know if installation will succeed is to perform it in isolated environment a-priori or otherwise curate extensions (which we discussed before and may want to do in some way, e.g. highlight high-quality extensions or extensions from Jupyter team, but curating every single extension would require much more resources).

**Comment by andrii-i** [comment]
> a) looks differently (screenshot below)

@krassowski that's actually how extension manager looks after you enter something into search box. I agree that it looks inconsistent and already created issue to track it 

- #14020

**Comment by andrii-i** [comment]
> Improvements here are always welcome but ultimately we are not controlling the third party extensions and there will always be a way for a third-party author to corrupt the installation process, whatever preventative measures we choose to apply. The only way to really know if installation will succeed is to perform it in isolated environment a-priori or otherwise curate extensions (which we discussed before and may want to do in some way, e.g. highlight high-quality extensions or extensions from Jupyter team, but curating every single extension would require much more resources).

Ok closing issue based on this + after reinstallation in clean environment only some extensions fail to build

**Comment by andrii-i** [comment]
@krassowski thank you for looking into this
