### ISSUE TITLE
File size column in File Browser is not visible at default width

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#14237]
## Description

﻿﻿﻿At the default width, the file browser is not wide enough to show the file size:

![image](https://user-images.githubusercontent.com/93281816/226480793-e779302f-d1ba-478f-8fc2-5840b7fd275f.png)

Expanding the left panel makes the file size column visible:

![image](https://user-images.githubusercontent.com/93281816/226480846-da0c97e4-7cba-473c-8611-0162e9403c0c.png)

## Reproduce

1. Launch JupyterLab
2. Make File Browser visible

## Expected behavior

All columns are visible, or if they are not visible, there is a visible indicator that more columns are present but can't be shown (e.g., a `»` button)

## Context

- Operating System and version: Windows 10 Enterprise 21H2
- Browser and version: Firefox 102.9.0esr
- JupyterLab version: 4.0.0a37

**Comment by krassowski** [comment]
I would love to have the columns take up less space. There is some padding CSS tirckery we could do to alleviate it but otherwise we need to have some extra JS logic to either resize columns when a new column is added (whether just to fit or to show overflow indicator as proposed above) or to resize the sidebar itself.

Tagging for 4.0.x as this does not appear blocking for 4.0 release but would ideally be addressed early as it is a severe annoyance deteriorating UX.

**Comment by JasonWeill** [comment]
Related:
* #8497 (no UI to signal existence of invisible columns)
* #3875 (resize columns of file browser)

**Comment by JasonWeill** [comment]
Still an issue as of 4.2.0 alpha; the "File Size" column must be enabled by right-clicking on a column header, but at the default left panel width, it is not visible.

**Comment by JasonWeill** [comment]
PR #15948, which fixes #15947, makes file size visible at the default width, although showing it makes the "Name" column effectively unreadable, and "File Size" does not fit in the tiny column header. Shortening it to "Size" would probably fit, at least in English:

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/b40f3961-e2b0-45cb-94fa-73d2de7d8b62)
