### ISSUE TITLE
Integrate Copilot-like completions with JupyterLab

### ISSUE THREAD

**Issue by unique94** [jupyterlab/jupyterlab#14267]

**Comment by unique94** [comment]
您好，您的邮件我已收到~

**Comment by jtpio** [comment]
FYI @unique94 this is likely to happen in the following repository: https://github.com/jupyterlab/jupyter-ai

**Comment by jtpio** [comment]
cc @dlqqq

**Comment by andrii-i** [comment]
If we talk about standard Github Copilot experience, it's closer to code completion feature that is part of jupyterlab. New Github Copilot X experience on the other hand is definitely closer to https://github.com/jupyterlab/jupyter-ai. @unique94 could you please clarify your request by adding details on which features from Github Copilot you would like to see integrated?

**Comment by unique94** [comment]
@andrii-i  Yeah, what I mean is the code completion feature. The key point is to leverage github copilot (or alternatives) to speed up our coding.

**Comment by ellisonbg** [comment]
Thanks for the input. Right now our focus is on adding more chat-like experiences than autocompletion in Jupyter AI, but this is helpful to hear. Jupyter is also vendor neutral/multi-vendor so we wouldn't offer something that is overly vendor specific (we will support models from many different vendors). While the underlying Codex model from OpenAI is broadly available, Github Copilot does quite a bit on top of that and is not open source.

**Comment by dannyeei** [comment]
+1 code completion from Github Copilot would be huge for my workflow. I've found myself using it less recently because of this.

**Comment by unique94** [comment]
您好，您的邮件我已收到~

**Comment by sxwebster** [comment]
I’m going to weigh in as someone else who would like to see this functionality. My own workflow, and that of a few team and colleagues has swung back towards VsCode with notebooks purely because of GitHub copilot integration.   
   
The increase in personal productivity is significant. It’s important to remember in this discussion that copilot goes beyond simple code completion as it actively scans the open notebook and attempts to understand context. It is very good at guessing what comes next in complex statements, and as it follows you along takes pretty darn good guesses at your intent, filling out bulk suggestions as it becomes more certain.   
   
From my point of view a failure to integrate an offering with matching capabilities pushes our development towards another IDE which has both a local and server side offering, and is more often than not easier to deploy server side.

**Comment by startakovsky** [comment]
https://deepnote.com/blog/introducing-deepnote-ai

**Comment by JasonSanchez** [comment]
I have been a longtime, die hard Jupyter notebook and then JupyterLab fan. Every other notebook experience bothers me due to the UI not feeling snappy, the shortcut keys being different (and often unchangeable), or there not being shift-tab tooltips. Spinning up VS Code feels like I have to do something important and bulky, while launching JupyterLab always feels like I am going to hack on something fun and I end up spending hours having a blast.  

Copilot features as demoed [here](https://youtu.be/QS_bh-3qKdw) are so compelling that they are enough for me to switch to VS Code. This is unfortunate because the implicit interface to Copilot feels like it would be natural within JupyterLab. 

Just wanted to +1 the comments above and provide another signal how valuable this functionality would be. Thank you all for the awesome tool you built.

**Comment by unique94** [comment]
您好，您的邮件我已收到~

**Comment by krassowski** [comment]
This can be implemented using jupyterlab-lsp, or in jupyter-ai using completion provider API. Some research into what LSP servers support it would be helpful (for example there is https://github.com/gobijan/nova-copilot-lsp), but it would be good to know what API other AI completion models support.

**Comment by unique94** [comment]
您好，您的邮件我已收到~

**Comment by krassowski** [comment]
The UI feature that provides ghost text is referred to as:
- autosuggestions in fish/zsh/IPython
- "inline completion" tabnine/VScode/lsp

There is little standardisation as of now, but the upcoming LSP version 3.18 defines [`textDocument/inlineCompletion`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_inlineCompletion) request.

The rough plan would be:
- JupyterLab completion providers (`ICompletionProvider` implementers) will optionally offer `requestInline(): InlineCompletion[]` method
   - we may want to implement streaming (showing results token-by-token as these are generated) to ensure good UX; this could be a `resolveInlineCompletion` method to be called in specified intervals to update the inline completion as it is generated; on UI side this could be indicated by animated dots at the end of the suggestion or similar
- the LSP extension will provide support for `textDocument/inlineCompletion` and expose the results via `requestInline()` method its completion provider; these may come from an AI model, or from any other algorithm/database
- we would implement user interface for inline completions (ghost text + switching between alternatives) in core
- separately `jupyter-ai`, or a third extension depending on `jupyter-ai`, would implement `requestInline()` method using the AI models registered and configured with `jupyter-ai`
   - this will include a toggle on statusbar or toolbar to explicitly opt-in/out for this on per-document basis
   - we may prefer a third extension initially to allow fast experimentation, but I feel that it might end up beneficial to merge it with juypter-ai later to share configurations and avoid conflicting versions of related tooling (we do not have to decide now)

CC @JasonWeill @andrii-i for thoughts

**Comment by ellisonbg** [comment]
@krassowski can you open an issue on Jupyter AI to track the parts of this relevant to it?

**Comment by JasonWeill** [comment]
Mike already linked https://github.com/jupyterlab/jupyter-ai/issues/268, which concerns adding code completion to GitHub; I think we can continue to discuss code completion language models there.

**Comment by krassowski** [comment]
Any thoughts about the proposed API @liyongsea? Would you like to open a PR against JupyterLab, or would you prefer someone else to pick it up and just help with a review?

**Comment by liyongsea** [comment]
> Any thoughts about the proposed API @liyongsea? Would you like to open a PR against JupyterLab, or would you prefer someone else to pick it up and just help with a review?

Sorry I didn't have time to take a look at it yet. Will come back to you soon. We are quite confident that we will be able to open a PR quickly. Is there anyone who would like to work togather on this ?

**Comment by krassowski** [comment]
If there is anything you will need help with just let me know!

**Comment by liyongsea** [comment]
Hi @krassowski If I understand correctly the first step will be to do a PR on LSP ? Or what we need is just [textDocument/inlineCompletion](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_inlineCompletion), and call it from the jupyter side ?
Sorry if the question is dump, i am new to LSP

**Comment by Wzixiao** [comment]
HI @krassowski , I briefly looked into the LSP and jupyter-completer libraries.

I found that jupyter-completer triggers a widget to pop up when the Tab key is pressed, rather than displaying "ghost text", which might not be what we are looking for.

Of course, what I'm more concerned about is using LSP. However, to my understanding, LSP doesn't offer frontend UI operation elements. When you mentioned "textDocument/inlineCompletion", are you suggesting that we implement a part of this interface to exhibit the "ghost text" feature?

**Comment by krassowski** [comment]
Apologies, this appears that my description was not clear enough. It is the other way around:
- yes current completer uses the completer widget; I was NOT suggesting to reuse it, barely to extend the `ICompletionProvider` interface; while the widget currently gets its items via `ICompletionProvider.fetch(): ICompletionItem[]` method (simplifying things a bit) I was suggesting that we add a new method for inline completions, say  `ICompletionProvider.fetchInline(): IInlineCompletionItem[]` (again, this is a simplification)
   - maybe it should be a separate `IInlineCompletionProvider`
- no LSP is not the prime element in the equation; there should be no need to first implement `textDocument/inlineCompletion` handling. For your purposes the first step would to be to extend `ICompletionProvider`  to have a new dedicated function for inline completions or implement `IInlineCompletionProvider`; LSP is one layer above; this is what I meant by:
    > - separately jupyter-ai, or a third extension depending on jupyter-ai, would implement requestInline() method using the AI models registered and configured with jupyter-ai
   >   - [...] 
  >    - alternatively, jupyter-ai _could_ implement LSP server interface; this would require JupyterLab to support multiple servers and make special-casing for AI features slightly more complex
- yes inline completion = ghost completion; as there is no other standard than the proposed LSP I suggest we go with it.
- while LSP is one layer above, we would follow the proposed LSP API because in my experience these APIs are relatively well designed and better for compatibility with other providers.

> Moreover, considering the circumstance you mentioned, where JupyterLab temporarily does not support multiple backends, I have been contemplating that perhaps my current PR could leverage the backend of Jupyter AI, given their functionalities are very close to each other.

No, this is irrelevant in the step one because your jupyter-ai extension would implement `ICompletionProvider` or `IInlineCompletionProvider`. The LSP part is desirable, but not necessary.

> Perhaps we could also simulate a frontend request that directly reaches the AI server. I am not certain whether JSP is capable of simulating a function at the frontend to access the AI server directly, although it might indeed deviate from our initial objectives.

This is what LSP is for and that would be the end goal, but let's do things step-wise.

Does it make sense? I could quickly open a draft PR implementing the scaffold for you to iterate on if that is easier?

**Comment by krassowski** [comment]
I see two arguments for having an `IInlineCompletionProvider` beside `ICompletionProvider`:
- `ICompletionProvider`  has some properties specific to popup completer such as `renderer`; I could imagine that an `IInlineCompletionProvider` implementer may want to customise how the inline hints are displayed too, for example by changing the ghost text font for some fragments, adding annotations, etc
- (less important) this is what [others do](https://vscode-api.js.org/interfaces/vscode.InlineCompletionItemProvider.html)

A counter argument is that we could have it all in `ICompletionProvider` just prefixed with `inline`. Thoughts/preferences?

**Comment by Wzixiao** [comment]
Thank you very much for your detailed reply.

I perhaps fully understand now what we should do.

Of course, I would greatly appreciate it if you could provide a draft for the PR, especially considering that my understanding of Jupyter is still fairly limited. It would be fantastic if the draft could detail the usage of the Provider interface.

Regarding ICompletionProvider and IInlineCompletionProvider:

> A counter argument is that we could have it all in ICompletionProvider, just prefixed with "inline". 

I think implementing this counter-argument is the best, but considering that other developers might go and refactor the relevant codes, so I still think it is the most unreasonable.

Excluding the options mentioned above, I believe that creating a new IInlineCompletionProvider is the best implementation method among the remaining options.

**Comment by krassowski** [comment]
I started implementing the inline completion provider API and the ghost completion CodeMirror 6 extension on a branch; it is not yet even in a draft PR state, but for transparency and coordination, please see https://github.com/jupyterlab/jupyterlab/compare/main...krassowski:inline-completion-api if you are interested.

**Comment by krassowski** [comment]
I don't fully understand what you are proposing, especially what do you need `ContextCompleterProvider`, and what is `InlineCompleterHandler`. However, I believe that `IInlineCompletionContext` should provide everything that you need, because you can extract full notebook structure from `widget` in it. `IInlineCompletionContext` is passed as an argument to `IInlineCompletionProvider.fetch`, see the example `HistoryInlineCompletionProvider`.

I pushed a new commit with slight adjustment ( https://github.com/jupyterlab/jupyterlab/compare/main...krassowski:inline-completion-api).

Can you describe what you would like to achieve in terms of UI features/behaviour (including things which we might decide to not include in core JupyterLab, but want to enable extensions to provide)?

> I am genuinely appreciative of the code you've shared; it has indeed facilitated a clearer pathway and a framework for me. I hope it is alright to ask once again whether I might utilize your code? Additionally, could you guide me on how to proceed with PR to ensure compatibility and seamless integration with your existing work?

I will open a pull request against JupyterLab in the coming week; this will hopefully get reviewed and merged into 4.1 branch. Once next JupyterLab 4.1 alpha/beta is released you will be able to easily develop your extension/jupyter-ai patch with the new API (and we may decide to adjust it based on your feedback). Once JupyterLab 4.1 is released then your extension may or may not be merged into jupyter-ai (this is a separate topic to discuss in the jupyter-ai repository). If you would like to re-purpose any part of my PR to support older versions of JupyterLab in your extension, feel free to do so (with appropriate acknowledgement), but it might be challenging and I would recommend patience until we have that PR in.

**Comment by krassowski** [comment]
That's great to hear! For reference implementation see: https://github.com/krassowski/jupyterlab-transformers-completer. The pull request is still in draft but I am shifting focus to tests coverage/documentation now, so unless any problems with the API are identified it should look mostly like in the current proposal.

**Comment by liyongsea** [comment]
Hi @krassowski 
I have made some progress in the implementation. There will be two ways to tirgger auto complete:
- hot key. When the completion is triggered manually like this, the data will be stream.
- auto complete when user pause for a while (the behavio of copilot)
Here you find a demo of the hot key completion with streaming efffect

https://github.com/jupyterlab/jupyterlab/assets/6381544/e6d3438a-4206-4e7a-bedb-e7daaa0c8de8

**Comment by unique94** [comment]
您好，您的邮件我已收到~

**Comment by Wzixiao** [comment]
Hi @krassowski ,

Thanks to the API you provided, I've largely completed the auto/request-on-keypress functionality. Below is a rough architectural diagram:
![image](https://github.com/jupyterlab/jupyterlab/assets/90966139/6c05bae0-1bce-467d-908b-e410e322f972)

In this diagram, the current API is sent directly from the frontend. I'm not entirely sure if the backend of jupyter-ai is using LSP, but I'm considering integrating with it. What are your thoughts?

Additionally, I'm not sure if I've illustrated the architecture clearly enough. If you can decipher it, could you possibly provide some feedback?

Furthermore, I've had this idea where we should display an error animation whenever there's a request error. I've implemented this based on your branch by adding an "error" field in both IInlineCompletionItem and IGhostText, and updating it in real-time in the last item of ProviderReconciliator. Would it be alright if I create a PR for this in your repository?

**Comment by krassowski** [comment]
I think for now we should skip the LSP part as the new protocol standard was not yet released and directly integrate with jupyter-ai using the provider API, assuming its maintainers are ok with that.

> Furthermore, I've had this idea where we should display an error animation whenever there's a request error. I've implemented this based on your branch by adding an "error" field in both IInlineCompletionItem and IGhostText, and updating it in real-time in the last item of ProviderReconciliator. Would it be alright if I create a PR for this in your repository?

Yeah, this sounds like a good idea. I would suggest to:
- a) open a new issue in this repository with the proposal on adding the error handling (should it be a field? should it be an event etc) and some screenshots on how it could look in UI (there are a few things we could do like, show a notification, turn the ghost text red, show an animation, show an "x" in the hover toolip, etc)
- b) once the main PR gets merged (I hope soon) and we had some time to bounce ideas, you can open a new PR against this repository directly

**Comment by timthelion** [comment]
@liyongsea Looks very impressive. I prefer to press a hot key to trigger the ghost text because flickering ghost text can be distracting but I think it should probably be a config option as others may have a different opinion.

**Comment by krassowski** [comment]
We could add a setting to disable automatic trigger on JupyterLab level.

**Comment by liyongsea** [comment]
A new PR using your end point has been pushed here https://github.com/jupyterlab/jupyter-ai/pull/419
We will still fix some small problem when waiting for your PR to be merged @krassowski

**Comment by J3698** [comment]
Could I ask how can I actually use this feature? This issue and the related one in jupyter-ai are closed, but looking through issue comments/docs I'm not sure how to actually get it to work.

**Comment by unique94** [comment]
您好，您的邮件我已收到~
