### ISSUE TITLE
Clicking on a link to a notebook (by URL) in JLab should open that notebook in JLab

### ISSUE THREAD

**Issue by lheagy** [jupyterlab/jupyterlab#1434]
Currently, following a link to another notebook is displaying json rather than opening the notebook in another tab. For example, I am using 
```
<a href="Mag/InducedMag2D.ipynb">Magnetic App</a>
```
to link to another notebook in the repo
![image](https://cloud.githubusercontent.com/assets/6361812/21291351/a64cbe16-c490-11e6-9ca5-cc14ad6c3100.png)

and clicking on the link leaves jupyter lab and displays the raw json

![image](https://cloud.githubusercontent.com/assets/6361812/21291356/ce38df54-c490-11e6-8f10-29b0b4db6e87.png)

**Comment by jasongrout** [comment]
Thanks for opening an issue. We've had lots of discussion about this, and having an open issue specifically for inter-notebook links helps. See also https://github.com/jupyterlab/jupyterlab/pull/1191

**Comment by jasongrout** [comment]
See also #456.

**Comment by willingc** [comment]
@lheagy Thanks for opening the issue. 

@jasongrout I'm glad that there is discussion on this. I was a little surprised when I tried it that the markdown links in my notebook downloaded the json instead of opening another notebook. Happy to test at a later date as lab is working quite well :smile:

Happy holidays to all!

**Comment by ellisonbg** [comment]
Marking as beta as the handling of links is going to be a show stopper for many usage cases.

**Comment by ellisonbg** [comment]
I am consolidating the link related issues into #1442 so am closing this as a duplicate.
