### ISSUE TITLE
Pluginlist in Settings Editor has grey background that reduces text contrast and readability for no good reason

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/jupyterlab#14364]
## Description

Pluginlist in Settings Editor (used in both react and non-react versions of the settings editor) has grey background that reduces text contrast and readability for no good reason

## Reproduce

1. Open Settings > Settings Editor
2. Note pluginlist (left side of the Settings Editor split panel)

![Screenshot 2023-04-11 at 2 54 02 PM](https://user-images.githubusercontent.com/26686070/231296471-9ada48ed-74ba-4b6b-af32-bb08ec462219.png)

## Expected behavior

Making pluginlist background white would increase text contrast and readability. This can be done by deleting this line 
https://github.com/jupyterlab/jupyterlab/blob/a4aa5ebfd9b63d873bf676863e35e0aa68765d43/packages/settingeditor/style/base.css#L71

Here's how it would look:
![Screenshot 2023-04-11 at 3 00 25 PM](https://user-images.githubusercontent.com/26686070/231297433-656b0d32-e93d-4b79-85ef-af9956ca3641.png)

**Comment by andrii-i** [comment]
@krassowski, @GabrielaVives, would be interested to hear your opinion on this

**Comment by krassowski** [comment]
Visually I much prefer to keep the grey background as it enhances focus on the settings form which is the main area, de-emphasising the plugin list and gives nice visual separation. _Legally_, In the light mode the plugin list items use `var(--jp-ui-font-color1)` that gives the text colour contrast of 14.21 which is WCAG 2.0 AAA. In dark mode the contrast is 8.0, again meeting AAA. Absolutely no change needed here.

The only annoyance is the "Markdown Viewer" icon in dark mode as it is not legible:

![Screenshot from 2023-04-12 05-25-49](https://user-images.githubusercontent.com/5832902/231349539-e2f81f7b-e397-4384-b472-529a72b5eab0.png)

It uses `var(--jp-icon-contrast-color0)` which is `#8e24aa` with contrast ratio 1.42. Non-text elements are required to have contrast of 3:1 however technically it does not apply here (see [Myth 4](https://uxmovement.com/buttons/the-myths-of-color-contrast-accessibility/)); I still think we should increase it. One option would be to use [markdown-mark](https://github.com/dcurtis/markdown-mark) instead of the purple M, another would be to just adjust colour in dark mode.


There is a much bigger issue with plugin list implementation which is lack of keyboard navigation and therefore being inaccessible for screen readers and reduced mobility users. I think that implementing keyboard navigation should be a higher priority.

**Comment by andrii-i** [comment]
@krassowski even more important reason is visual consistency. While in of itself use of grey is a fine stylistic choice, In jupyterlab shading is only used to separate sections with difference in elevation / z-levels. Section "on top" has no shading and is "connected" to the main content area, sections below are shaded: 
![Screenshot 2023-04-12 at 2 28 42 PM](https://user-images.githubusercontent.com/26686070/231590109-831d7cc6-fc6d-4e94-8564-f14fe9986c19.png)

Sections with same elevation are separated with borders, shading is not used:
![Screenshot 2023-04-12 at 2 36 31 PM](https://user-images.githubusercontent.com/26686070/231591626-16d703c9-fde7-44a6-8e7f-7a513f4144f2.png)

In settings editor pluginlist is at the same level as settingspanel, there is no visual indication that it is "below" it. So in this context the use of grey here is inconsistent and visually confusing:
![Screenshot 2023-04-12 at 2 41 13 PM](https://user-images.githubusercontent.com/26686070/231592295-a4d3ddb2-e97e-46c4-bf82-610d9295096d.png)

**Comment by andrii-i** [comment]
@krassowski It's just 1-line change so I created #14375 to implement it and requested your review

**Comment by andrii-i** [comment]
> There is a much bigger issue with plugin list implementation which is lack of keyboard navigation and therefore being inaccessible for screen readers and reduced mobility users. 

@krassowski that's a problem for sure. Do you know if there is an issue tracking it? I searched through open issues but have not found one, would be happy to open

**Comment by krassowski** [comment]
> Sections with highest elevation are "on top", have no shading and are "connected" to the main content area. Sections with lower elevation are "below" and are shaded:

And I believe that plugin list is below the setting form. So it should have grey background. To my eye this will reduce usability as the areas will blend together. We need a third eye (ideally independent).

**Comment by andrii-i** [comment]
@krassowski I agree that when the subjective UIUX preferences are discussed, there is no one correct answer and   beauty is in the eye of the beholder. 

But this is not the case, here we talk about (in)consistency with jupyterlab visual design principles. In all cases where shading is used for section separation there is a clear indication of one element being on top of another. On the screenshot you can see that all areas highlighted red have a collection of control elements that are all shaded when none of the elements are chosen / active. When one of them is chosen, it becomes non-shaded, active, and is getting "connected to the main content area. 

Please give screenshot below a look again taking this into account and let me know your thoughts, I'm very open to the discussion. Can you see what I'm talking about? This approach is consistent throughout jupyterlab.

I would also be happy to get a third opinion, do you have anyone on your mind? @GabrielaVives, maybe you could give this a look and chime in on the discussion if possible? 

![image](https://user-images.githubusercontent.com/26686070/231810136-f2e6a746-a4fc-43df-8b54-a2b332798812.png)

**Comment by GabrielaVives** [comment]
Hi @andrii-i , yes I agree that the grey background here doesn't bring any information to the user. I presume it was initially designed that way to increase the difference between this list and the list of files next to it. 

However, as you point out the grey separators do this job. And the grey background does make it feel like an inactive tab, which it is not. Plus, I find that the grey background makes it look unrelated from the settings details on the right although it's totally related and heavily linked.

**Comment by andrii-i** [comment]
Thank you for sharing your view @GabrielaVives. @krassowski, what do you think?

**Comment by krassowski** [comment]
The change as proposed in the #14375:

-  only leaves 1px border when scrollbars are not shown; for many users the scrollbar is never shown as their browser/OS uses overlay scrollbars; the grey 1px border is too thin for me in light mode but ok in dark mode (see screenshots below)
- the proposed change propagates more pure white (in light mode) and almost pure black (in dark mode) background. I am not very concerned about it because users do not spend hours in settings, but in general pure white and pure black backgrounds cause eyestrain (this is not a universally agreed fact, but it is not a minority view either; you can see some arguments [here](https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/) and [here](https://uxmovement.com/content/when-to-use-white-text-on-a-dark-background/)). Most acclaimed software dev tools use lower contrast for a reason. As a long time user of JupyterLab I feel more eyestrain with each such decision.

> grey background does make it feel like an inactive tab, which it is not. [...] I find that the grey background makes it look unrelated from the settings details on the right although it's totally related and heavily linked.

this can be solved by either:
- making the active tab white (as in sidebars), or
- adding a little bit of blue (or another colour) to the grey (as does PyCharm and Windows)

For reference, proposal in #14375:
 
| Light | Dark |
|-----|----|
| ![image](https://user-images.githubusercontent.com/5832902/232150647-b9b33184-ab98-4c50-9fb6-06c0ddba9857.png) | ![image](https://user-images.githubusercontent.com/5832902/232150679-de53f876-bd1b-4501-8fb1-01cdc24256a4.png) |

Enhancing separation in settings by changing background is also a common pattern, for example PyCharm:

| Light | Dark |
|-----|----|
| ![Screenshot from 2023-04-14 21-29-29](https://user-images.githubusercontent.com/5832902/232148829-8a1070f2-e333-4777-bc0a-ea22befcc359.png) | ![Screenshot from 2023-04-14 21-29-34](https://user-images.githubusercontent.com/5832902/232148871-d5b87c5b-2078-4af7-9971-edf6ac1dec04.png) |

Or Windows:

| Light | Dark |
|-----|----|
| <img src="https://user-images.githubusercontent.com/5832902/232151268-61d15aee-9579-41d1-acd8-dc316e1d7f23.png" width=500px> | <img src="https://user-images.githubusercontent.com/5832902/232149848-cc6fb600-e161-411b-ae3c-65b136827e7f.png" width=500px> |

But of course it is not universal; for example VSCode(ium):

| Light | Dark |
|-----|----|
| ![Screenshot from 2023-04-14 21-43-39](https://user-images.githubusercontent.com/5832902/232151074-b625d461-c8c2-40fb-8075-859353d97174.png) | ![Screenshot from 2023-04-14 21-44-02](https://user-images.githubusercontent.com/5832902/232151144-1157b51b-81be-47d3-84b0-d3cc45d0e35b.png) |

Or Ubuntu:

| Light | Dark |
|-----|----|
| ![Screenshot from 2023-04-14 21-37-42](https://user-images.githubusercontent.com/5832902/232150109-b1ee5c69-f5ae-45e9-bb35-dda57336ce1c.png) | ![Screenshot from 2023-04-14 21-37-45](https://user-images.githubusercontent.com/5832902/232150182-d5e1e3b0-baea-4fe5-ad4e-1dcf4d0d9a13.png) |

However, what **all** of the programs I tested do is:
- avoid forcing pure white or pure black on the full size of the content window (as this is just too much; ok, maybe VSCode has a lot of white but this is not pure white) again see [here 1](https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/).
- have much lower contrast between background and text, again see [here 2](https://uxmovement.com/content/when-to-use-white-text-on-a-dark-background/).

While we do not use pure black, it is so close to pure black that it still causes eyestrain to me. Of course everyone will have their own preference but it would be nice if the default theme could be more thoughtful with the choice of colours.

There is also a seizure concern when UI has too high contrast and happens to be arranged in certain patterns (see https://developer.mozilla.org/en-US/docs/Web/Accessibility/Seizure_disorders - with a recommendation to reduce contrast), but I think the current settings are not as bad to induce a seizure even in dark theme.

**Comment by andrii-i** [comment]
@krassowski thank you for detailed response with references, this helps discussion a lot. I think you make some really good points and I agree that using white background is not the only viable approach, let's discuss and iterate to find the best solution. Taking in account your suggestions, potential solutions are: 
- Iterate on removal of grey background and use of white/black background (depending on the theme) taking in account usability considerations. For example, increasing border width up from 1px as you suggested. @krassowski, could you please advise how do I replicate thin border that you show / what browser and OS do you use when seeing this thin border?  
- Use grey background but try to stay consistent with JupyterLab visual styling by making the active tab white (as in sidebars). Note that in sidebars there are no borders between control element that becomes shaded/unshaded and main content area, emulating this effect would be problematic with Split Panel that is currently used for settings editor
![Screenshot 2023-04-14 at 5 52 35 PM](https://user-images.githubusercontent.com/26686070/232175099-70e53e3c-2631-41f9-a27e-8c48e6e5a7ad.png)
![Screenshot 2023-04-14 at 5 52 30 PM](https://user-images.githubusercontent.com/26686070/232175101-588668bb-c390-4f70-825a-c44942d587d8.png)

- Proceed with the use of different color for pluginlist background, for example much lighter grey (or potentially light blue as you suggested but we don't use colors in JupyterLab except for logo so this also would be inconsistent with design principles of JupyterLab)



Also on the issue of use of "pure white" (in light mode) and "almost pure black" (in dark mode) backgrounds:
- About seizure concerns:
> Reduce contrast
Normally, higher contrast is a good thing when it comes to accessibility. The greater the contrast of a text color to its background (technically called luminosity contrast ratio, according to W3.org's page on [Colors with Good Contrast](https://www.w3.org/WAI/perspective-videos/contrast/), the easier such content is to read. Users with low vision are especially appreciative of efforts to ensure high contrast of text against its background. When the content is animated, however, reducing contrast is actually a way to reduce the likelihood that the animated content will cause seizures. Drop the contrast ratio if three flashes within one second are detected.

^ this is "Reduce contrast" section from [MDN article about web accessibility for seizure disorders](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Seizure_disorders) that you linked. As you can see, contrast reduction is recommended only when content is animated and has high-frequency flashes ("three flashes within one second") which is not the case in JupyterLab. While using pure black might be problematic in some contexts (but again, pure black is not used here), Also reading text on a grey background is problematic for everyone who uses projectors or old monitors.
- Disregarding above, both colors are basic colors used in JupyterLight and JupyterDark themes that we ship by default. Their use and propagation should not be problematic. If we find them problematic, let's adjust the basic colors to be less straining but this should be examined and done in a separate issue and in the meantime it should not be considered a problem. I think you make good points that should be implemented, for example [using grey text, not black](https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/) in JupyterLight

**Comment by krassowski** [comment]
If we are down to the level of quoting the MDN document I linked...

> The fact that static images may cause seizures and other disorders is documented in articles such as ["Gamma Oscillations and photosensitive epilepsy"](https://linkinghub.elsevier.com/retrieve/pii/S0960982217304062), where it is noted "Certain visual images, even in the absence of motion or flicker, can trigger seizures in patients with photosensitive epilepsy". The Epilepsy Foundation, in its article, ["Shedding Light on Photosensitivity, One of Epilepsy's Most Complex Conditions"](https://www.epilepsy.com/stories/shedding-light-photosensitivity-one-epilepsys-most-complex-conditions-0) talks about static images and patterns

> `prefers-contrast`
> From W3C's Draft document, Media Queries Level 5 section on [prefers-contrast](https://drafts4.csswg.org/mediaqueries-5/#prefers-contrast): "The prefers-contrast media feature is used to detect if the user has requested the system increase or decrease the amount of contrast between adjacent colors. For example, many users have difficulty reading text that has a small difference in contrast to the text background and would prefer a larger contrast." **Sometimes there can be such a thing as too much contrast; a halo effect around text can occur in such situations and actually reduce legibility. Putting the amount of contrast in the user's control is a definite gift for accessibility.**

**Comment by krassowski** [comment]
> (or potentially light blue as you suggested but we don't use colors in JupyterLab except for logo so this also would be inconsistent with design principles of JupyterLab)

We use colours I JupyterLab. I would advise to refrain from referring to "design principles of JupyterLab" as a strong argument as this is not something that is set in stone, nor even properly documented - and under such circumstances it resembles Witcher's Code ;)

**Comment by krassowski** [comment]
> could you please advise how do I replicate thin border that you show / what browser and OS do you use when seeing this thin border?

4k screen makes it easy to replicate on any browser as scrollbars disappear anyways. Regardless of the page size Firefox uses overlay scrollbars on Ubuntu for. Chromium browsers also have the overlay scrollbar implemented but whether it is enabled depends on OS and user preferences. Also, make sure you have disabled "Theme scrollbars" as option in Settings Theme if testing locally in dark mode.

**Comment by andrii-i** [comment]
@krassowski thank you for the feedback and advise. 

If we increase the border width so that when overlay scrollbar is enabled there still would be a visible border, would you be ok with changing background color to white?

**Comment by krassowski** [comment]
> would you be ok 

I think my personal opinion is of little weight here. I would be more interested to know what users think about it. I would suggest to create screenshots/mockups for current and proposed state (but without scrollbars) and gather feedback on Jupyter Discourse Forum (and/or other platforms). I think we can create a dedicated thread on Discouse to post questions like that for gathering a quick user feedback.
