### ISSUE TITLE
Virtual Notebook rendering "breaks" custom CSS in JupyterLab 4?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14379]
## Description

In Jupyter notebooks it is common to inject custom CSS (for example with the `%%html` magic) to style the notebook or tweak a few things, without having to write an extension. This is useful for example when making presentations.

However with JupyterLab 4 it looks like doing so might produce some unwanted behavior and UI glitches when using the notebook.

This is the case even for small notebooks.

## Reproduce

Here are two screencasts to compare `4.0.0b1` against `3.6.3` using the following code snippet:

```
%%html

<style>
    .jp-Notebook-cell { margin-bottom: 400px; }
</style>
```

**4.0.0b1**

Scrolling slowly with the mouse we can clearly notice "UI shifts". It's even more apparent when dragging the scrollbar. 

https://user-images.githubusercontent.com/591645/232089176-5c238e0b-57e7-422b-9845-c3a5a9655da5.mp4

**3.6.3**

Doing the same in 3.6 is smooth:

https://user-images.githubusercontent.com/591645/232089153-5391306f-8d28-49aa-9b59-b2f43f24c08c.mp4

## Expected behavior

The same scroll experience as in 3.6.

## Context

Tested with JupyterLab `4.0.0b1`.

I *suspect* this is related to the virtual notebook implementation, but feel free to correct this and the title of the issue if not.

**Comment by jtpio** [comment]
Adding it to the `4.0` milestone as these scrolling issues (like in https://github.com/jupyterlab/jupyterlab/issues/13343) feel like a regression compared to previous versions of JupyterLab.

It can break workflows for folks making presentations with notebooks.

Not sure it is a release blocker, but it would be great to have a way to mitigate this before 4.0 final.

**Comment by SylvainCorlay** [comment]
I am not sure we should fixed this one. By definition, adding custom CSS on the page can break the UI, or behave significantly differently between major releases.

**Comment by JasonWeill** [comment]
Notes from triage: This is not a release blocker for Lab 4.0.0, but it may be a release blocker for Notebook 7.0.0, because custom CSS is often used in classroom settings with Jupyter Notebook. I agree with @SylvainCorlay that introducing custom CSS can break the UI or have other unintended consequences. The same notebook, with the same custom CSS, is not guaranteed to behave identically in Lab 3.x, Lab 4.x, Notebook 7.x, and other software.

**Comment by jtpio** [comment]
It's true there is no guarantee on CSS changes between major releases, and that we usually consider CSS as **not** being part of the API.

However in this case it's not about being supporting previous CSS. it is about being able to customize the look of the interface by adding simple CSS rules. Which is quite common in custom themes for example or custom lab applications.

As mentioned above let's say you want to be able to add some extra margin at the end of bottom of each cell. You can create an extension that adds CSS to `base.css`:

```css
.jp-Notebook-cell {
    margin-bottom: 400px;
}
```

And use the regular template plugin:

```ts
import {
  JupyterFrontEnd,
  JupyterFrontEndPlugin
} from '@jupyterlab/application';

/**
 * Initialization data for the myextension extension.
 */
const plugin: JupyterFrontEndPlugin<void> = {
  id: 'myextension:plugin',
  autoStart: true,
  activate: (app: JupyterFrontEnd) => {
    console.log('JupyterLab extension myextension is activated!');
  }
};

export default plugin;
```

Or you could define your own CSS class called `myCustomCell` and add it to notebook cells via the JupyterLab TypeScript (which is in the API surface), using `addClass()`. And then add styling for your own class:

```css
.myCustomCell{
    margin-bottom: 400px;
}
```

However this triggers the same behavior as mentioned above which makes using the notebook very difficult:

https://user-images.githubusercontent.com/591645/232880907-fbbf60fa-078e-45ee-8fee-a5e81b1e90e6.mp4

---

Maybe the issue is not strictly about custom CSS in general. But more about being able to customize the notebook component with CSS like before in JupyterLab 3. Still without any guarantee that's totally fine. But at least let folks customize it with CSS if they want to.

Maybe the issue is more with the current notebook implementation in JupyterLab 4 which can create frustration with some workflows (see above and linked issues), which is why it feels like a regression. And as mentioned in https://github.com/jupyterlab/jupyterlab/issues/13343#issuecomment-1509017086 could be fixed for 4.0.

**Comment by jtpio** [comment]
Also switching to `none` for notebook windowing seems to fixing the issue:

![image](https://user-images.githubusercontent.com/591645/234997785-295c8a11-b3d4-49e6-b1e4-648b043feb16.png)

As mentioned in https://github.com/jupyterlab/jupyterlab/pull/14444, it could be worth considering `none` as the default. Folks who really need performance can then switch to `defer` or `full`.

**Comment by fcollonval** [comment]
> As mentioned in https://github.com/jupyterlab/jupyterlab/pull/14444, it could be worth considering none as the default. Folks who really need performance can then switch to defer or full.

I'm not in favor of using `none` by default as having performance issue with JupyterLab is a recurrent reported issue that can even prevent opening a large notebook; for instance Cocalc as virtual rendering enabled by default and VS Code has put in place substantial tricks for loading large notebook (I don't know about Colab). As those app are heavily reporting telemetry I take that as a proof that this is a common problem rather than an exception. Especially I would not be surprised if the use of custom CSS is far less happening than having very long notebooks or lots of them opened; after all the users are mostly doing data analysis or education.

To highlight once more the limitation of virtual rendering:
- Scroll is approximative because the cell size is not constant - we could improve this by adding some heuristic but it will never be perfect.
- User playing with CSS margins within the notebook DOM tree should expect trouble as virtual rendering requires element measurement that don't support margins (and will likely never do due to margin's collapsing).
- IFrames internal state is likely to be reset when scrolling them in and out the viewport. That issue could be lifted; for example Cocalc is avoiding that by extracting the iframes from the cell outputs and by positioning them dynamically through JavaScript.

**Comment by jtpio** [comment]
I have opened https://github.com/jupyterlab/jupyterlab/issues/14455 to discuss this more.

**Comment by jtpio** [comment]
> as having performance issue with JupyterLab is a recurrent reported issue that can even prevent opening a large notebook;

Right, but not sure this is the majority of use cases. If users have performance issues they can switch back to `full` or `defer` easily.

**Comment by fcollonval** [comment]
> Possibly related to #14319.

It is not this one is about CSS style not applied because virtual rendering does not render all cells when #14319 is about external CSS rules not loaded or a lack to load new once easily (in particular for fonts).
