### ISSUE TITLE
do you  have finally easy to use option for breakpoint like vs code has?

### ISSUE THREAD

**Issue by Sandy4321** [jupyterlab/jupyterlab#14389]
do you  have finally easy to use option for breakpoint like vs code has?
meaning to run python code till some particular line and after run code line my line ?

**Comment by JasonWeill** [comment]
@Sandy4321 Thanks for your issue! JupyterLab comes with a debugger that works as you describe. You can set breakpoints and run your code either until a breakpoint or line-by-line. You can find documentation here: https://jupyterlab.readthedocs.io/en/stable/user/debugger.html

**Comment by Sandy4321** [comment]
thanks for soon answer
1
run your code either until a breakpoint 
it is not clear how to do it
run cell by cell it works , how to run all code till breakpoint
and after to resume to run all code till next breakpoints?
2
is there option to run manually commands and make plots after stop at breakpint?

**Comment by andrii-i** [comment]
@Sandy4321 Issue was closed as completed because JupyterLab has support for breakpoints. 

At the same time questions that you ask in your last comment are valid, could you please edit the name of the current issue and reopen it or create a new issue regarding "how to run all code till breakpoint and after to resume to run all code till next breakpoints?" or "is there option to run manually commands and make plots after stop at breakpint?" to discuss them further? 

Thank you.

**Comment by JasonWeill** [comment]
@Sandy4321 If the information in the debugger docs doesn't help you, I recommend asking for help with JupyterLab's debugger in the [Jupyter Discourse forum](https://discourse.jupyter.org/) or [Gitter chat room](https://app.gitter.im/#/room/#jupyterlab_jupyterlab:gitter.im). Thanks for your interest!
