### ISSUE TITLE
[Q/FR] Connect to a kernel with a given connection path

### ISSUE THREAD

**Issue by NightMachinery** [jupyterlab/jupyterlab#14535]
I have started a Jupyter lab server:
```
jupyter lab --ip='0.0.0.0' --port='6035' --no-browser --notebook-dir=~/code
```

I then connect to this server using emacs-jupyter and create a kernel/session with the following connection file:
```
/home/x/.local/share/jupyter/runtime/kernel-c3a1494f-61c2-4c64-8c61-ac096278edae.json
```

I want to be able to connect to this session in the web UI accessible on `http://127.0.0.1:6035/`. But I can't find any options to give the web UI the kernel connection file directly. The UI does not show this kernel in its selection list:
<img width="397" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/36224762/98bd4760-27ef-4a6d-9dad-2cd78413f495">

I have taken a look at #2044, but it seems to be about a more complicated use case where the kernel is started from another server. I just want to connect a kernel started from the same server.

PS: I also like to do this with VSCode and PyCharm, in addition to Jupyter Lab's own web UI.

**Comment by davidbrochart** [comment]
If emacs-jupyter is connected to the same server as JupyterLab (which seems to be the case here), then JupyterLab should "see" the kernel/session created by emacs-jupyter. I don't know why it's not the case here.
BTW the use case in #2044 is now possible if you use [Jupyverse](https://github.com/jupyter-server/jupyverse) instead of [jupyter-server](https://github.com/jupyter-server/jupyter_server) (see https://github.com/jupyter-server/jupyverse/pull/265). You could try and see if it helps with your issue. Note that you'll need #13792 and #13851, but you'll have them with `pip install jupyverse[jupyterlab,auth]`.

**Comment by NightMachinery** [comment]
Thanks.

I ended up doing the reverse, setting the kernel in emacs:
```
(setq jupyter-server-kernel-names
 '(("http://127.0.0.1:6035"
  ("a05faeea-05ca-40f9-97df-e8b071a8e3e4" . "orgk1/"))))
```

This worked well.

**Comment by NightMachinery** [comment]
@davidbrochart What is the equivalent of this in `jupyverse`?

```
jupyter lab password

jupyter lab --ip='0.0.0.0' --port='6035' --no-browser --notebook-dir=~/code
```

**Comment by davidbrochart** [comment]
Jupyverse supports token authentication if you installed the `auth` plugin and launched `jupyverse --set auth.mode=token` (it's the default mode).
If you launch `jupyverse --set auth.mode=user` then you will be able to register new users and login with username/password.
You can set the IP address with `--host=0.0.0.0` and the port with `--port=6035`. By default no browser window is opened, but you can open one with `--open-browser`. There is currently no way to select a working directory, just change to the directory before launching `jupyverse`.
