### ISSUE TITLE
Booleans True/False no longer highlighted as numbers in 4.0.0

### ISSUE THREAD

**Issue by lukelbd** [jupyterlab/jupyterlab#14584]
## Description

JupyterLab 4.0.0 seems to highlight the booleans `False` or `True` with the default font color. In the previous version, jupyterlab used a green color for booleans, integers, and floats to indicate numeric values.

<img width="230" alt="Screenshot 2023-05-23 at 12 23 52" src="https://github.com/jupyterlab/jupyterlab/assets/19657652/9ea74821-f373-45fb-bf19-300ac4f147b0">

## Reproduce

Download JupyterLab 4.0.0 and open any notebook.

## Expected behavior

True/False highlighted in green, as with floats and integers.

## Context

- Operating System and version: Tested on macOS and Linux (system independent) 
- Browser and version: JupyterLab Desktop 3.6.2-1 
- JupyterLab version: 4.0.0

**Comment by lukelbd** [comment]
I also noticed the default code font changed. Not sure if this was intentional? Subjectively I preferred the old font (but maybe that discussion is for another thread)

**Comment by dzanellato** [comment]
> This is not limited only to booleans, but all built-in (Python) functions and types, such as print, len, int, or list, are not highlighted anymore for me. Other than those, syntax highlighting works as expected.

The same problem occurs here.

**Comment by krassowski** [comment]
I can reproduce. This was likely caused by migration from CodeMirror5 to CodeMirror6. For builtins we will need to roll our own solution as upstream is not interested as per https://github.com/lezer-parser/python/issues/9 and https://github.com/lezer-parser/python/pull/13.

For `True`/`False` is an issue on our side. I see relevant parsing logic in the lezer code [here](https://github.com/lezer-parser/python/blob/c91887e35a9ee02c1c4b91f36cdec8bfeaadeca1/src/python.grammar#L188) and applied to style tag [`bool` here](https://github.com/lezer-parser/python/blob/c91887e35a9ee02c1c4b91f36cdec8bfeaadeca1/src/highlight.js#L10) and it works on https://codemirror.net/try/ (well colour is different, but it is something):

![Screenshot from 2023-05-24 19-29-17](https://github.com/jupyterlab/jupyterlab/assets/5832902/7393b953-310c-44d6-8a16-7b75b81f3e96)

The issue is that we do not define a highlight for the bool tag in the default theme:

https://github.com/jupyterlab/jupyterlab/blob/eeaa6505f658f7eaaad18ea2d7f15c3c5da0b23a/packages/codemirror/src/theme.ts#L75

PR on the way.

**Comment by sestras** [comment]
Thanks for the fix! Should I open a separate issue for the built-ins or do you have that on your radar anyway?
