### ISSUE TITLE
14702

### ISSUE THREAD

**Issue by numeric-lee** [jupyterlab/jupyterlab#14762]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by numeric-lee** [comment]
reopening issue #14702
my handlers.py looks identical to the repo

Using anaconda navigator, I was able to upgrade Jupyter Lab to version 3.6.3. The behavior persists

**Comment by JasonWeill** [comment]
@numeric-lee Let's keep the conversation going in #14702, which is still open. If you are using JupyterLab through a commercial vendor, please follow up with them. If you are using the open source version, the open source community is not your "vendor"; you are welcome to submit a pull request that fixes the issue, if you find a root cause.
