### ISSUE TITLE
Status bar at 400% zoom

### ISSUE THREAD

**Issue by j264415** [jupyterlab/jupyterlab#14793]
### Problem
When using high zoom settings on lower resolution screens the status bar becomes unusable as the text and icons overlap.
You can see this by zooming to 400% in the browser on a screen less than 1280 pixels wide.

### Proposed Solution

In order to make the status bar accessible and usable at these zoom levels (principally low vision users) we suggest making a few adjustments at high zoom
Hide document title as it visible in the active notebook tab title
Hide kernel name (Python 3 - ipykernel) as this can be accessed by looking at the running tab 
Hide processor icon as this can be accessed by looking at the running tab 
Retain line and column number as not available easily elsewhere
Retain simple interface toggle as useful to have immediately available for users that require it 

### Additional context
None

**Comment by trallard** [comment]
cross referencing https://github.com/jupyterlab/jupyterlab/issues/10004 here since this issue points to an in-depth JupyterLab zoom audit https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/34#issuecomment-1210168155 as well as several proposals to improve 400% support. 

If not done already, it would be worth revisiting the two links above to bring alignment with this issue and other issues/PRs in flight relating to Zoom.
