### ISSUE TITLE
Find/replace highlighting keeps coming back up after find prompt closed

### ISSUE THREAD

**Issue by James-Huffman** [jupyterlab/jupyterlab#14871]
## Description

Highlighting for find/replace in text editor comes back unexpectedly after closing find interface and typing additional text.
![Screenshot 2023-07-21 130935](https://github.com/jupyter/notebook/assets/1227014/3d46c8ef-b616-47c8-994b-888984895572)
![Screenshot 2023-07-21 131004](https://github.com/jupyter/notebook/assets/1227014/4f2e96d3-313f-4bab-ab5b-71202dd4dc15)

I originally found this bug in notebook, but it appears that they implement this search feature from jupyterlab.

## Reproduce

1. Open a text document in JupyterLab or jupyter notebook.
2. Ctrl-f or use Edit -> Find... to open the find prompt.
3. Type string you want to find
4. Press enter to highlight matching cases in your document
5. Press esc to close the find interface
6. Type any new character - the find highlighting will reappear despite the closed interface.

This seems to only affect the text editor, not find/replace behavior within jupyter notebook cells.

Highlighting cannot be resolved by clearing the find query before closing the find/replace interface. Only way to make this go away is to either reload the page or search for a non-matching query.

## Expected behavior

Text should remain unhighlighted until the find/replace interface is re-opened. 

## Context

- Operating System and version: Windows 10 Enterprise
- Browser and version: Chrome 114.0.5735.199

- Jupyter Notebook version: 7.0.0
- JupyterLab version 4.0.3

<details><summary>Troubleshoot Output</summary>
<pre>
[troubleshoot.txt](https://github.com/jupyter/notebook/files/12131167/troubleshoot.txt)
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[command_line.txt](https://github.com/jupyter/notebook/files/12131168/command_line.txt)
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
No output.
</pre>
</details>

**Comment by JasonWeill** [comment]
Do you also see this behavior in JupyterLab 3 or Notebook 6? I know that @krassowski made a lot of improvements to search and replace in the newer versions.

**Comment by James-Huffman** [comment]
Notebook 6 (6.5.4) implements a different find/replace interface, and this bug is not present.

JupyterLab3 (3.6.5) does not have persistent highlighting after using find/replace, but it also does not have cell by cell searching when running notebooks.

**Comment by krassowski** [comment]
Thanks so much for the test case @parmentelat, it helped to dissect the issue in notebook. So this is the trace of that leads to the problematic behaviour:

<details>

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/21c2774f-c399-42e9-8fee-5efbc9709316)

</details>


After a cell gets added the `NotebookSearchProvider._onCellsChanged` gets invoked and I think it needs to be invoked so that we update the cell search providers for a future search (ok):

https://github.com/jupyterlab/jupyterlab/blob/897418f0f25ffbbee3aa06a62770a53246823f85/packages/notebook/src/searchprovider.ts#L564-L572

At the end it emits `NotebookSearchProvider.stateChanged` signal (inherited from `SearchProvider`):

https://github.com/jupyterlab/jupyterlab/blob/897418f0f25ffbbee3aa06a62770a53246823f85/packages/notebook/src/searchprovider.ts#L594

https://github.com/jupyterlab/jupyterlab/blob/897418f0f25ffbbee3aa06a62770a53246823f85/packages/documentsearch/src/searchprovider.ts#L31-L36

`SearchDocumentModel._updateSearch` handles this signal and starts a new search with the existing query.

https://github.com/jupyterlab/jupyterlab/blob/897418f0f25ffbbee3aa06a62770a53246823f85/packages/documentsearch/src/searchmodel.ts#L339-L357

At this moment I think that the solution is to modify `_onCellsChanged` so that it only emits `stateChanged` if there is an active search. How do we know whether the search is active or not? I am not sure if there is an existing way to check it, but if there is not we should probably store a boolean for it, set it in `startQuery()` and clear it in `endQuery()`.

Something similar will probably need to be done for the text editor. Here is the trace for the reproduction instructions provided by @James-Huffman (thank you!):

<details>

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/d90c7f10-0733-4492-bbab-f12738914ee6)

</details>
