### ISSUE TITLE
Why the background thread's ouput will append to last active cell's output, not the actual corresponding cell?

### ISSUE THREAD

**Issue by potoo0** [jupyterlab/jupyterlab#14925]
## Description

the background thread's ouput will append to last active cell's output,

## Reproduce

```
# cell1
from threading import Thread, current_thread
from time import sleep


def task():
    cnt = 3
    while cnt:
        print(f'task(cnt={cnt}) {current_thread()}')
        cnt -= 1
        sleep(1)

# cell2
Thread(target=task, name='t1').start();
# cell2 output
'''
task(cnt=3) <Thread(t1, started 140546848823040)>
''';

# cell3
Thread(target=task, name='t2').start();
# cell3 output
'''
task(cnt=3) <Thread(t2, started 140546857215744)>
task(cnt=2) <Thread(t1, started 140546848823040)>
task(cnt=2) <Thread(t2, started 140546857215744)>
task(cnt=1) <Thread(t1, started 140546848823040)>
task(cnt=1) <Thread(t2, started 140546857215744)>
''';
```

![jupyterlab thread's output](https://imgur.com/a/I54YcOo.jpg)

**Comment by JasonWeill** [comment]
This behavior may be by design. When a Jupyter notebook runs a cell, the cell runs to completion (you can see when `[*]` turns into a number like `[2]`). When future cells run, output is captured for their cell. Cells do not run in isolation from each other, and two cells don't run simultaneously, as far as I've observed.
