### ISSUE TITLE
this version of python appears to be incorrectly compiled

### ISSUE THREAD

**Issue by simonm3** [jupyterlab/jupyterlab#15019]
I am using anaconda with pthon 3.11.3; and a pip install of jupyterlab 4.05. 

I get this message when starting jupyter lab. I have tried uninstalling and reinstalling. 

This version of python seems to be incorrectly compiled
(internal generated filenames are not absolute).
This may make the debugger miss breakpoints.
Related bug: http://bugs.python.org/issue1666807

**Comment by firai** [comment]
According to https://github.com/spyder-ide/spyder/issues/20800#issuecomment-1682527035, this was fixed in Anaconda 2023.07-2, which ships with Python 3.11.4. Can you try using the new version?

If you can't upgrade or if it still doesn't work, maybe try Guido's suggestion to pass `-Xfrozen_modules=off`? Note that the issue you referred to was migrated to Github as shown at the top of the page: https://github.com/python/cpython/issues/44604.

**Comment by simonm3** [comment]
Did try to update but waited 5 hours and conda was still stuck. I guess I
could reinstall but only recently installed 3.11.3 so will just have to
live with it for now.

**Comment by ccordoba12** [comment]
@simonm3, please run

    conda update anaconda

first and then

    conda install python=3.11.4

That should solve your problem.
