### ISSUE TITLE
Read-only status notification toast should show up on `ctrl + s`

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15046]
## Description

https://github.com/jupyterlab/jupyterlab/pull/14600 implements a read-only indicator and a toast notification when user attempts to save the file with "save all" (see https://github.com/jupyterlab/jupyterlab/issues/7980 for design discussion). Notification was not implemented for "save" command as that command is disabled when file is read-only.

## Reproduce

- Open a readonly file in non-RTC mode (create one with chmod 444 file.py)
- Press `ctrl+s`
- See no notification

## Expected behavior

The notification is shown anyways. We could:
- (a) add a new command or just listen to keystrokes and synchronise the keyboard shortcuts but this may be unreliable.
- (b) add a new argument `isKeybinding` to command's `args`, which would allow to conditionally enable the save command when used from shortcut and then show the notification. We already do that for `toolbar` (#14664) and `isPalette`
- (c) have a bespoke new argument in commands, a callback to execute when the command is disabled, let's call it `notifyDisabled()`

(b) and (c) require changes in Lumino. This is somewhat related to the discussion in https://github.com/jupyterlab/lumino/issues/570.

## Context

- JupyterLab version: 4.1 main

**Comment by JasonWeill** [comment]
Other apps with real-time collaboration and autosaving handle CTRL+S/CMD+S differently:

* Quip does nothing when the user presses the key combination
* OneNote does nothing, although there is an option to manually force a sync

**Comment by andrewfulton9** [comment]
From my understanding, changes in lumino would revolve around [this function](https://github.com/jupyterlab/lumino/blob/a817cb2d05ac264403ad930fb9c038746c5393ff/packages/commands/src/index.ts#L614)

If we go with something like options B above, would the idea be to:
- a) make `isKeybinding` return a boolean and allow the `!this.isEnabled(command, args)` conditional to be bypassed when `isKeybinding` is True in `_executeKeyBinding`
- b) make `isKeybinding` a callable that would be called at the beginning of `_executeKeyBinding` to allow custom code execution
- c) something else I'm not seeing

If we got with option C, it would be a really simple implementation as a lot of the logic for a warning is already [implemented](https://github.com/jupyterlab/lumino/blob/a817cb2d05ac264403ad930fb9c038746c5393ff/packages/commands/src/index.ts#L616) (at least in the case of a ). However, as far as I can tell, the only place `isEnabled` is checked and blocks an execution call from within lumino is in this function. Is it possible to call a command while `isEnabled` returns false otherwise though? If not, I don't think that's necessarily a problem. If we want to call `notifyDisabled` from `isEnabled`, so a notification goes out anytime isEnabled is checked, I would expect some errant notifications when a menu and the command palate are built so I don't think that's necessarily a good idea.

Personally, I think option C is the clearest option here. So for this specific issue, we would add the `notifyDisabled` callback option to commands and add the callback to `_executeKeyBinding` when `!this.isEnabled` in lumino, and then in the `saveAs` command in the `docmanager-extension`add the `notifyDisabled` callback and add a call to the execute function when `isEnabled === false` (though that may be redundant). Calling the new callback `onDisabled` instead my be more clear too, since the callback wouldn't necessarily have to be a notification.

**Comment by krassowski** [comment]
> From my understanding, changes in lumino would revolve around [this function](https://github.com/jupyterlab/lumino/blob/a817cb2d05ac264403ad930fb9c038746c5393ff/packages/commands/src/index.ts#L614)

Yes.

> If we go with something like options B above, would the idea be to ...

It would be much simpler. In lumio:

```diff
  private _executeKeyBinding(binding: CommandRegistry.IKeyBinding): void {
    let { command, args } = binding;
+  args.isKeybinding = true;
    if (!this.hasCommand(command) || !this.isEnabled(command, args)) {
```

In [docmanager-extension](https://github.com/jupyterlab/jupyterlab/blob/e00fdc4f197f501445b3e527ebad040e76c60095/packages/docmanager-extension/src/index.tsx#L840-L844):

```diff
  commands.addCommand(CommandIDs.save, {
    label: () => trans.__('Save %1', fileType(shell.currentWidget, docManager)),
    caption,
    icon: args => (args.toolbar ? saveIcon : undefined),
-    isEnabled: isWritable,
+    isEnabled: (args) => args.isKeybinding ? true : isWritable(),
```

and then in `execute()`:

```diff
if (context.model.readOnly) {
+  if (args.isKeybinding) {
+    return Notification.warning(/* options */);
+  }
  return showDialog({
    title: trans.__('Cannot Save'),
    body: trans.__('Document is read-only'),
    buttons: [Dialog.okButton()]
  });
}
```

**Comment by andrewfulton9** [comment]
Should I open an issue in Lumino to add that, or can I just go ahead and make a PR?

**Comment by krassowski** [comment]
I would go ahead with a PR, I believe that https://github.com/jupyterlab/lumino/issues/570 already captures relevant discussion.

**Comment by andrewfulton9** [comment]
I opened [jupyterlab/lumino#644](https://github.com/jupyterlab/lumino/pull/644) for the lumino relevant portion of this issue.
