### ISSUE TITLE
.ipynb files have no syntax highlighting in texteditor

### ISSUE THREAD

**Issue by jans-code** [jupyterlab/jupyterlab#15172]
## Description

Whenever I open .ipynb files in the jupyterlab texteditor, no syntax highlighting is available.
This is also true after changing the filetype selector in the bottom left from 'none' to 'JSON'.

## Reproduce

1. Rightclick any .ipynb in jupyterlab and select open with -> editor
2. (optional) Click on 'none' in the bottom left and choose JSON

## Expected behavior

I expected to see JSON syntax highlighting when editing .ipynb files.

## Context

- Operating System and version: Archlinux
- Browser and version: any
- JupyterLab version: 4.0.6

**Comment by krassowski** [comment]
For (2) the bug is in the line 570:

https://github.com/jupyterlab/jupyterlab/blob/1692817b23ce35a31d02889c4af83df732c00a17/packages/fileeditor-extension/src/commands.ts#L560-L573

Because `spec.mime` can be an array of strings (in case of JSON, ` ['application/json', 'application/x-json']`) casting it to string is a mistake. We could just take the first element of the array in such a case. This is similar to https://github.com/jupyterlab/jupyterlab/pull/15101.

@jans-code would you be interested in opening a PR?

**Comment by jans-code** [comment]
sure, i'm on it :)
