### ISSUE TITLE
Deleting the following lines when doing TAB completition above

### ISSUE THREAD

**Issue by hnykda** [jupyterlab/jupyterlab#1528]
Steps to reproduce:

In one cell:
```
def a(arg):
    pass
```
in the second:
```
a(ar)
b()
```
Go to first line of the second:
![image](https://cloud.githubusercontent.com/assets/2741256/22157512/4aae139e-df38-11e6-99bd-05306ea83d32.png)
press TAB to autocomplete argument `arg` and it deletes all the following lines (`b()` in this case):
![image](https://cloud.githubusercontent.com/assets/2741256/22157540/6001edf6-df38-11e6-8b1c-2ccfbc810008.png)

## EDIT
OK, not just following lines, but all lines in the cell except the one you do autocomplete on. E.g. pressing TAB in this situation:
![image](https://cloud.githubusercontent.com/assets/2741256/22157641/c7325b64-df38-11e6-858e-64b808d9da68.png)

gives me:
![image](https://cloud.githubusercontent.com/assets/2741256/22157649/d18ecbec-df38-11e6-9f0e-37cbc1020862.png)

**Comment by jasongrout** [comment]
It looks like the patch returned from the completer only has the line that is being completed, not the full text of the cell. We could probably fix this if we spliced the patch into the cell instead of replacing the cell text at https://github.com/jupyterlab/jupyterlab/blob/12d081814ba8bfaea55fc65639796d37770fc0ad/src/completer/handler.ts#L208

**Comment by blink1073** [comment]
I'm working on this one right now.
