### ISSUE TITLE
Quickly jump to an open/recently closed notebook

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#15293]
### Problem

I often have many notebooks open and I mean to go back to one I was working on. I can't find it easily.

### Proposed Solution

Add search + recently closed tabs to open tabs. This should be accessible via hotkey.

I think the Chrome search tabs (ctrl+shift+A) is an ideal experience. Mostly because it's a keyboard shortcut where I can see in order the names of the last accessed tabs (notebooks in our case) then type to filter. I can click to jump to a tab or click x to close it. It even has recent tabs. Most of this is there in JupyterLab's open tabs already.

![image](https://github.com/jupyterlab/jupyterlab/assets/1813603/7638d034-09fc-479d-931b-539b545c21d0)

**Comment by krassowski** [comment]
Linking to a recent discussion where we bounced some ideas on better tab navigation, and discussed limitations of the current "Open Tabs" implementation https://github.com/jupyterlab/jupyterlab/issues/15245#issuecomment-1773744541.

Having a popup/modal with tab list that can be filtered could solve the problem of user being required to navigate to the "Running" tab in the sidebar and of the difficulty finding the tab of interest.

**Comment by mlucool** [comment]
> Having a popup/modal with tab list that can be filtered could solve the problem of user being required to navigate to the "Running" tab in the sidebar and of the difficulty finding the tab of interest.

+1

**Comment by krassowski** [comment]
Some additional thoughts:
- the keyboard shortcut is a good UX but probably should not be the only approach
- placing a caret button on the tab bar (like in Chrome) may not work as well because there can be many tab bars
- to make it discoverable we could add:
    - (a) a "modal" button in "Running" sidebar,
    - (b) a new menu entry "Search open and recent tabs" in Tabs menu
- maybe there should be a "Recently closed" section in the "Running" sidebar
- a way to access the recently closed files is implemented in [jupyterlab-contrib/jupyterlab-recents](https://github.com/jupyterlab-contrib/jupyterlab-recents); we could create a service/token with history of recent files (and an action to clear it) in JupyterLab so that extensions can access this information and then extensions can expose it in UI as they wish (e.g. in menu as in jupyterlab-recents, or in a modal as proposed here)
- if we are storing the history of opened files, there will be privacy implications for different use ceases (some administrators will want it always on, some will want to disable it) and we should design an API to cater to these needs (basically this needs to be a separate plugin)
- we had a related discussion back in 2021 in https://github.com/jupyterlab/jupyterlab/issues/11613 where I suggested adding "Reopen Closed Tab" to context menu on the tabbar

Illustrations:

(a) button to open the quick jump modal in the right top corner and the new proposed section:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/f8f8a042-ad20-44d9-ac78-beac9aa2c878)

(b) the proposed menu entry 

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/61e9a7cb-9f52-4041-8923-e85b02cbcb4b)
