### ISSUE TITLE
Should button `jp-ToolbarButtonComponent` styles be restored for 4.x?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15511]
Some extensions, such as `jupyterlab-favourites`, add buttons relying in upstream styles. These buttons are unstyled in 4.1.0a4 due to changes in #15021

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/21f1b860-28b1-47fe-b9b0-96bb85f13b11)

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/f75ae0a8-786c-4184-be75-5494d8ea6e82)

I think we should restore the old styles, even if we do not use them any more, for backward compatibility.

**Comment by ericsnekbytes** [comment]
@brichet Would you like to have a look and create a PR?

Other notes:

- We can add information to extension migration notes
- We can consider adding a red border to all deprecated items in dev mode

**Comment by brichet** [comment]
> @brichet Would you like to have a look and create a PR?

Sure, I'll do it.

> * We can add information to extension migration notes

Can you elaborate ?

**Comment by jtpio** [comment]
> We can add information to extension migration notes

That would be to let extension authors know the styles are being deprecated. The extension migration guide would be a good place to do that.

**Comment by brichet** [comment]
This button looks good on my side, without any change, because it get the class `.jp-Button`, and get [these rules](https://github.com/jupyterlab/jupyterlab/blob/7d3160d50d511343f262e7c7d287bb2df3bec99d/packages/ui-components/style/base.css#L51-L93) applied:

![image](https://github.com/jupyterlab/jupyterlab/assets/32258950/8967311f-3914-40b3-8370-2ce86f2447f4)

I can still restore the `.jp-ToolbarButtonComponent` rules, but I wonder why the button doesn't receive this class in your case @krassowski.

**Comment by krassowski** [comment]
It looks good on your side because you are running v3.2.1 with my https://github.com/jupyterlab-contrib/jupyterlab-favorites/pull/21 which added `.jp-Button` ;) Earlier versions fail as on the screenshot. I would not have time to patch all extensions like this though, nor do we even know about existence of many internal extensions.
