### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'. where as shell command within cells can import it

### ISSUE THREAD

**Issue by vanangamudi** [jupyterlab/jupyterlab#15598]
## Description

Pretty much what the title says. 
- `Pandas` is installed in the virtual environment. 
- Kernel for the virtualenv is installed properly
- Notebook is connected to kernel
`      !which python --> /home/vanangamudi/.virtualenvs/pinnxde/bin/python`
- Importing python from command line works 
`      !python -c "import pandas as pd; print(pd.__version__)" --> 2.1.4`

but cannot import pandas inside jupyter code cells.

## Reproduce

The following notebook consistently suffers this error.
https://gist.github.com/vanangamudi/76077b6e098189cc4f3b4876d7290426

## Context

- Operating System and version: Linux kaithadi 6.2.0-39-generic 40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Browser and version: Firefox 116.0.2
- JupyterLab version: 4.0.10

**Comment by krassowski** [comment]
Most likely you are not using the kernel from the `pinnxde` virtual environment but from another location. The python found by `!` shell bang does not correspond to python used by kernel. In general, you do not want to use shell bangs for anything Python related (e.g. use `%pip` instead of `!pip`). If you want to see which Python is used by the kernel run `import sys; sys.executable` in the kernel itself. You can also run `%pip list` to see what is installed in that environment.

More broadly this would not be an issue in JupyterLab but in ipykernel or ipython.

**Comment by vanangamudi** [comment]
> Most likely you are not using the kernel from the `pinnxde` virtual environment but from another location. The python found by `!` shell bang does not correspond to python used by kernel. In general, you do not want to use shell bangs for anything Python related (e.g. use `%pip` instead of `!pip`). If you want to see which Python is used by the kernel run `import sys; sys.executable` in the kernel itself. You can also run `%pip list` to see what is installed in that environment.

Thanks for the tip on %pip. =sys.executable= does point to system python not virtualenv. 

> More broadly this would not be an issue in JupyterLab but in ipykernel or ipython.

I will try updating ipython and ipykernel before resorting to their forums.
