### ISSUE TITLE
Installing `jupyterlab-lsp` and `jupyter-lsp` breaks the completer plugin 

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15649]
## Description
I want to use the completions from the default completer extension and features from lsp but I don't want to use the lsp code completion. When I install `jupyterlab-lsp` and `jupyter-lsp` in my environment, I can't see any `availableProviders` in the completer extension settings. 

Here's the screenshot - 
![image](https://github.com/jupyterlab/jupyterlab/assets/30082866/a975ab8c-6190-4f94-84bc-8b0c5caef895)

## Reproduce

1. Install and launch jupyterlab
2. Go to the completer extension settings. You'll see kernel and context providers are available.
3. Install jupyter-lsp and jupyterlab-lsp 
4. Go to the completer extension settings again. You'll see that the kernel and context providers are no longer available.

## Expected behavior
I expect the default completer extension to work regardless of lsp packages being installed or not.

## Context

Versions used - 

- jupyterlab               4.0.10
- jupyter-lsp               2.2.1
- jupyterlab-lsp          5.0.1

**Comment by krassowski** [comment]
I cannot reproduce this:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/f82f8a03-ec3d-443e-a41d-8a1b7991f625)

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/50e6fed5-40c5-4ac0-9780-c79319f11468)

> I expect the default completer extension to work regardless of lsp packages being installed or not.

Is there something which does not work?

> I want to use the completions from the default completer extension and features from lsp but I don't want to use the lsp code completion

For now I would recommend disabling the `@jupyter-lsp/jupyterlab-lsp:completion` plugin,.

**Comment by krassowski** [comment]
Are there any errors in the browsers JS console?

**Comment by divyansshhh** [comment]
> Is there something which does not work?

I'm not getting any completion suggestions when pressing `Tab`.

>For now I would recommend disabling the @jupyter-lsp/jupyterlab-lsp:completion plugin,.

Yes, we intend to disable this for now.

> Are there any errors in the browsers JS console?

No, there are no errors. Neither in the terminal nor in the browser console. 


Any  thoughts on why these completers are not present? I'm trying to make a better reproducer in the meantime.

FWIW, I tried doing a dev build and setting a breakpoint in the activate function of the default providers but the breakpoint never got triggered.

**Comment by divyansshhh** [comment]
Here's a screen capture of this (if it helps) - 


https://github.com/jupyterlab/jupyterlab/assets/30082866/5049f444-68c9-45c4-9f4b-7d5f7d58f9d0

**Comment by krassowski** [comment]
Yes, disabling `@jupyter-lsp/jupyterlab-lsp:completion` plugin does make it reproducible - thank you! Interesting, I will take a look.

**Comment by krassowski** [comment]
The problem is in the jupyterlab-lsp extension; it disables `@jupyterlab/completer-extension:base-service` in `disabledExtensions` because it needs to augment the default providers slightly to work correctly in the context of document tranclusions, and to provide a unified UX regardless of completion source ([overrides.ts](https://github.com/jupyter-lsp/jupyterlab-lsp/blob/73ee344d47f9e8990886b54b4be5e8aba8702285/packages/jupyterlab-lsp/src/features/completion/overrides.ts)).

There are a few solutions to consider:
- (a) make it possible to disable a plugin from a plugin level rather than from an extension level; e.g. we could have:
  
  ```js
  {
    "jupyterlab": {
       "disabledExtensions": [
          // short form
          "@org/core-extension:plugin-a",
          // proposed long form
          {"disable": "@org/core-extension:plugin-b", "ifEnabled": "@org/external-extension:plugin"}
      ]
    }
  }
  ```
  
  or we could add a new explicit stanza:
  
  ```js
  {
    "jupyterlab": {
       "replacesPlugins": {
          "@org/core-extension:plugin-b", "@org/external-extension:plugin"
        }
    }
  }
  ```

- (b) make the default completion providers extensible by using hooks; this would be better if multiple extensions want to make small tweaks in their behaviour

In the meantime I will make jupyterlab-lsp re-register the original providers in LSP when the completion plugin is disabled.

**Comment by krassowski** [comment]
I opened a dedicated issue to discuss the (a) option: https://github.com/jupyterlab/jupyterlab/issues/15651 and there is 
a draft PR working the issue around in jupyterlab-lsp: https://github.com/jupyter-lsp/jupyterlab-lsp/pull/1036
