### ISSUE TITLE
Tearing out outputs has weird tab behavior

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#1572]
When I tear out outputs (in 0.13.2) in a JupyterLab browser window taller than about 1065 pixels, the tab bar for the mirrored output is abnormally large. Also, it seems that the blue highlight on the Mirrored Output tab appears even when I click on the tab.

I tried to make a screencast, but all I get is a black screen. Here is a screenshot:
![screen shot 2017-01-27 at 5 44 46 pm](https://cloud.githubusercontent.com/assets/192614/22390320/58a53d94-e4b8-11e6-96e1-c7cbe511148b.png)

**Comment by jasongrout** [comment]
This seems to also happen on master (a564724b5d04bdae6e31ecc6218a3e338e57d2ac)

**Comment by sccolbert** [comment]
I'd first check to see if the mirrored output is somehow getting set with a
max size.

On Jan 27, 2017 4:37 PM, "Jason Grout" <notifications@github.com> wrote:

When I tear out outputs (in 0.13.2) in a JupyterLab browser window taller
than about 1065 pixels, the tab bar for the mirrored output is abnormally
large. Also, it seems that the blue highlight on the Mirrored Output tab
appears even when I click on the tab. See the screencast below.
[image: output]
<https://cloud.githubusercontent.com/assets/192614/22390135/4cd77a32-e4b7-11e6-9565-a53647ccfc62.gif>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jupyterlab/jupyterlab/issues/1572>, or mute the thread

**Comment by jasongrout** [comment]
> I'd first check to see if the mirrored output is somehow getting set with a
> max size.

Wish I had seen your comment before diving into the code for a while. I just found this line giving a max-height of 1000px, which if deleted, lets the mirrored output stretch the full height: https://github.com/jupyterlab/jupyterlab/blob/master/src/outputarea/index.css#L19. I could have probably found it faster had I seen your comment :).
