### ISSUE TITLE
Inline completer is invoked automatically when enabling output scrolling

### ISSUE THREAD

**Issue by EricHUANG970823** [jupyterlab/jupyterlab#15746]
![Untitled](https://github.com/jupyterlab/jupyterlab/assets/97007177/bb9f760d-aa45-4d7e-947b-7ac22cd8389d)

Inline completer is invoked automatically when enabling output scrolling. I think it should be in the way where inline completer is invoked only when editing code.

**Comment by krassowski** [comment]
Thank you for the report. This also affects normal completer when autoinvoke is enabled, hence tagging it for 4.0.x:

![also-affects-normal-completer](https://github.com/jupyterlab/jupyterlab/assets/5832902/0f9f5c28-88d6-46e5-9ffe-c5508fd9b2c2)

The problem is that `onTextChanged` in handler is invoked on any model change (here change in model metadata about scrolling state). I will open a PR.
