### ISSUE TITLE
[Urgent]: GSoC 2024 application info

### ISSUE THREAD

**Issue by henrykironde** [jupyterlab/jupyterlab#15755]
@fcollonval, we require certain information from you. We have sent a spreadsheet via the mailing list, and it would be appreciated if any mentor could provide the necessary details to complete the application.

**Comment by krassowski** [comment]
Hi @henrykironde thanks for reaching out via GitHub. I guess you wanted to tag @fcollonval instead? I am not sure what email you used but it might be worth resending to jupyterlab-council@googlegroups.com  if it is urgent. Cross-linking with https://github.com/jupyterlab/team-compass/issues/234

**Comment by henrykironde** [comment]
My bad, I edited that. I have forwarded the email. Last, on the idea page, you have projects having something like this
 ```
Small
Large
Small
Medium
```
Could you also express the time values in hours (350, 175, 90)? Google might request us to provide them in that format, similar to what happened last year.

**Comment by HaoZeke** [comment]
Unfortunately the project list and issues do not constitute enough information for a proper NF GSoC sub-org application at the moment. We need **at the least**:
- Number of potential mentors
- Number of hours estimated

Additionally, it would be best to have a single long form document with all the projects listed along with the names of the mentors, requirements, and general background. @fcollonval , since the deadline is today, for now we are assuming JupyterLab will be able to provide at-least 3 mentors **total**.

**Comment by JasonWeill** [comment]
Closing in favor of https://github.com/jupyterlab/team-compass/issues/234. Let's continue the conversation there.
