### ISSUE TITLE
Can't drag and drop cells out of viewport

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15777]
## Description
In lab3, it was possible to drag and drop a cell out of the initial viewport because the viewport would scroll. This doesn't happen in lab4. Here's a gif showing the differences in behavior - 
![Drap-n-drop](https://github.com/jupyterlab/jupyterlab/assets/30082866/dedd282b-7401-492f-8e27-265d8cb13219)

## Reproduce
shown in gif

## Expected behavior
I expect the behavior in lab4 to be the same as lab3

## Context

- JupyterLab v4.1.0rc1

**Comment by krassowski** [comment]
I can reproduce in 4.1.0 but not in 4.0.12, tagging as regression.

**Comment by krassowski** [comment]
This is another regression introduced by virtual scrollbar PR (https://github.com/jupyterlab/jupyterlab/pull/15533) which changed the DOM structure (confirmed as working in 4.1.0a4 but failing in 4.1.0b0). We need to move `data-lm-dragscroll="true"` to `jp-WindowedPanel-outer` and add a test because it's the second time it broke.
