### ISSUE TITLE
Editing the console history does nothing

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15772]
## Description
We noticed that lab4 allows editing the console command history but it does nothing afterwards. Here's a gif - 

![editing-console-history](https://github.com/jupyterlab/jupyterlab/assets/30082866/2b37cf26-84e3-4aa5-be4c-0fa7a5774103)

## Context

- JupyterLab v4.1.0rc1

**Comment by krassowski** [comment]
I can reproduce in 4.0.12 and 4.1.0 but not in 3.6.7.

**Comment by krassowski** [comment]
This might have the same or similar underlying issue as https://github.com/jupyterlab/jupyterlab/issues/15514

**Comment by krassowski** [comment]
It might be that the `configChanged` signal gets cleared away too early with:

https://github.com/jupyterlab/jupyterlab/blob/d4ab66c9ba2f61f3fd5475c91f6b529bbdff0dac/packages/console/src/widget.ts#L604-L607

hence the configuration change does not get reflected. A very subtle regression due to how the signal propagation changed in lumino 2.0
