### ISSUE TITLE
Sequencing of highlights is incorrect in notebook when replacing

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15809]
## Description

Sequencing of highlights is incorrect in notebook when replacing but good when searching

## Reproduce

![wrong-order-cross-cells](https://github.com/jupyterlab/jupyterlab/assets/5832902/079c03b5-7c9f-4ba7-8796-0537407efc4e)

replacing numbers 12**6**345 whereas I would expect 123456, as is the case for search.

## Expected behavior

Should replace 123456 in order, the same order as search iteration uses:

![search-ok](https://github.com/jupyterlab/jupyterlab/assets/5832902/8766f29b-5331-4251-97fa-fe925293c6c7)

## Context

- JupyterLab version: >4.0.0,<=4.1.1

**Comment by JasonWeill** [comment]
The file `searchprovider.ts` in the `cells` package forces a loop through the current cell if `currentProviderIndex === -1`, and `-1` is the default value for this attribute:

https://github.com/jupyterlab/jupyterlab/blob/2af428c23caae5e9fd0fcf7f87046845bcae283a/packages/cells/src/searchprovider.ts#L137-L145

It seems like when we're going through the first cell with matches, `currentProviderIndex` should not be `-1`, so that the `cells` `searchprovider` can iterate through all cells.

**Comment by JasonWeill** [comment]
This is fixed by the current version of #15881.
