### ISSUE TITLE
CVE-2024-21501 in sanitize-html

### ISSUE THREAD

**Issue by frenzymadness** [jupyterlab/jupyterlab#15876]
I'm a maintainer of jupyterlab in Fedora Linux and I got a report about CVE-2024-21501 in sanitize-html.

More info:

* Report: https://gist.github.com/Slonser/8b4d061abe6ee1b2e10c7242987674cf
* Fix: https://github.com/apostrophecms/sanitize-html/commit/c5dbdf77fe8b836d3bf4554ea39edb45281ec0b4
* CVE details: https://cve.circl.lu/cve/CVE-2024-21501

My knowledge of the codebase of jupyterlab is not good enough to say whether it's possible to exploit this vulnerability or not but my guess is that it is possible because jupyterlab works with custom HTML documents provided by users.

**Comment by krassowski** [comment]
Looks like we should patch. The advisory was missing proper metadata to trigger dependabot, I submitted https://github.com/github/advisory-database/pull/3745

**Comment by krassowski** [comment]
JupyterLab itself is not affected because we do not use `sanitize-html` on the backend but only on the frontend.

However, third-party packages which re-use the `@jupyterlab/apputils` package _on the backend_ might be affected, depending on the sanitizer settings that they use. Already third-party packages which depend on `@jupyterlab/apputils` can force resolution of `sanitize-html` to a newer version on their end.

We should upgrade to pull the patch to ensure that the new version is tested on CI and pull any improvements.

In future please consider sending questions like this using "Report a vulnerability" button on https://github.com/jupyterlab/jupyterlab/security just to be on the safe side.

**Comment by JasonWeill** [comment]
@krassowski Thank you for opening this pull request!

@frenzymadness Thank you for bringing this to our attention! In the future, please see the [Project Jupyter Security](https://jupyter.org/security) page for information about reporting a vulnerability in an official Jupyter subproject such as JupyterLab..

**Comment by frenzymadness** [comment]
> @frenzymadness Thank you for bringing this to our attention! In the future, please see the [Project Jupyter Security](https://jupyter.org/security) page for information about reporting a vulnerability in an official Jupyter subproject such as JupyterLab..

I was thinking about it but because the vulnerability is already disclosed and it's not in fact in the codebase of jupyterlab, I decided to use a regular issue. If I find a vulnerability in Jupyterlab that nobody knows about, I'd report it only to maintainers.
