### ISSUE TITLE
A JupyterFrontend without polling endpoints by default 

### ISSUE THREAD

**Issue by Zsailer** [jupyterlab/jupyterlab#15890]
### Problem

Summary: `ServiceManager` requires _all_ Jupyter Server endpoints to be authorized on instantiation.

I've been exploring having a new basic "Notebook application" that only allows real-time collaboration to edit the document (not run cells. etc). In other words, it doesn't have access to the kernel, session, or contents APIs (except the single endpoint that returns the one notebook they are viewing).

Naturally, I started from `JupyterFrontend`. The issue is `JupyterFrontend` [requires a `ServiceManager`](https://github.com/jupyterlab/jupyterlab/blob/2af428c23caae5e9fd0fcf7f87046845bcae283a/packages/application/src/frontend.ts#L70).  The default (and only) implementation of the `ServiceManager` [includes multiple subclasses `IManagers`](https://github.com/jupyterlab/jupyterlab/blob/2af428c23caae5e9fd0fcf7f87046845bcae283a/packages/services/src/manager.ts#L120-L170) for each service. The constructors of many of these managers starts polling (e.g. [see sessions manager](https://github.com/jupyterlab/jupyterlab/blob/2af428c23caae5e9fd0fcf7f87046845bcae283a/packages/services/src/session/manager.ts#L27-L48)) their endpoints immediately.

This is problematic for my simple Notebook application, whose access is blocked to most of these endpoints.

### Proposed Solution

Offer a `ServiceManager` that can be configured to not poll all of these endpoints. Because this happens in the constructor, it's difficult to remove this polling without overloading _every_ part of the `ServiceManager`.

### Additional context

I discussed this with @bollwyvl on the Jupyter Server call this morning. He pointed me to JupyterLite—since it suffers from the same issue. Cleverly, JupyterLite [stubs out the `fetch`](https://github.com/jupyterlite/jupyterlite/blob/8901696d9d4cfa57fd078845bcee1b36767c94ed/packages/server/src/app.ts#L58-L70) method to intercept outgoing requests.

**Comment by jtpio** [comment]
Thanks @Zsailer.

For reference, a need for a more modular / configurable was also expressed in https://github.com/jupyterlab/jupyterlab/issues/15329. So that each service of the service manager could be replaced by another plugin (or disabled), via regular extensions (or something similar).

Not sure if we should keep the conversation in one issue only? Unless the request in this issue is more about providing a way to disable the default polling.

> I discussed this with @bollwyvl on the Jupyter Server call this morning. He pointed me to JupyterLite—since it suffers from the same issue. Cleverly, JupyterLite [stubs out the `fetch`](https://github.com/jupyterlite/jupyterlite/blob/8901696d9d4cfa57fd078845bcee1b36767c94ed/packages/server/src/app.ts#L58-L70) method to intercept outgoing requests.

Voila also provides custom managers when instantiating its custom `ServiceManager`: https://github.com/voila-dashboards/voila/blob/5aa861dc153215c66d8ccdff040f4ac868d7af3a/packages/voila/src/services/servicemanager.ts#L16-L26

**Comment by Zsailer** [comment]
Thanks, @jtpio :+1: 

Let's move this over to your issue. I'll close this and add comments to yours later today.
