### ISSUE TITLE
dirty icon vs close tab icon

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1594]
While a closed circle is a clear indication that something has changed, it may be somewhat unconventional to new users that search for a way to close a document. Perhaps the dirty icon should appear next to the cross, instead of replacing it?

**Comment by blink1073** [comment]
@cameronoelsen, thoughts on this one?

**Comment by cameronoelsen** [comment]
Since we don't have very much space to work with in the tab area, what if we made the close arrow invert with the 'unsaved' black circle indicator in the tab area so that the close icon is still represented to the user? @akhmerov @blink1073 

![save-unsaved](https://cloud.githubusercontent.com/assets/6437976/23319835/1a38e41c-fa8d-11e6-9d1e-9e394444de6c.jpg)

**Comment by akhmerov** [comment]
Sounds good to me.

**Comment by sccolbert** [comment]
Here's how sublime handles it:

![browser](https://cloud.githubusercontent.com/assets/137289/23321188/f3bf0444-faa3-11e6-8ce1-0ee92a2a0bfe.gif)
