### ISSUE TITLE
Design specification for JupyterLab navigation bar

### ISSUE THREAD

**Issue by cameronoelsen** [jupyterlab/jupyterlab#16]
This is where I will be posting the design specifications for the navigation bar to iterate on!

**Comment by cameronoelsen** [comment]
Here is what I have come up with for the navigation bar:

![navbar](https://cloud.githubusercontent.com/assets/6437976/15947716/e05c705e-2e51-11e6-8a70-da1e0e7accf3.png)

For each dropdown item, we were planning on the font size to be 12px with a 4px margin on the top and the bottom, equating to a total of 20px of height per dropdown item. But, we found that on many web applications and in web typography in general, 12px is too hard to read. So, we decided on making the base font size in both the navigation and the content area to 13px. This now makes it, with a 4px margin on the top and bottom, to a height of 21px per cell. At the top and bottom of each menu, as well as for the dividers between sections, there is a 4px margin that is used. Lastly, in regards to the single margin between the revert to checkpoint dropdown item and the expansion arrow to it's right, I was thinking that there would be a 12px margin between the longest in length menu item and either the side of the menu dropdown or addition content on the right:
 
### Margin Specifications
![navbar-margins](https://cloud.githubusercontent.com/assets/6437976/15947685/b4dc7fa0-2e51-11e6-95f7-d411b45a0f2b.png)

There weren't enough stylings in the menus for me to make a complete specification, so here are the specifications for each item in the dropdown menu including the hover state:

### Color & Typography Specifications 
![normalfile](https://cloud.githubusercontent.com/assets/6437976/15948301/c7d5d856-2e54-11e6-9b70-06bd7df77411.png)

##### Cell Title (ex. New, Open..., Close): 
Font family: Helvetica Neue
Font weight: Regular
Font size: 13px
Color: #757575

##### Cell Right Justified Title (Command)
Font family: Lucida Grande
Font weight: Regular
Font size: 13px
Color: #9E9E9E

##### Cell Right Justified Arrow
[navbar-arrow.svg.zip](https://github.com/jupyter/jupyterlab/files/308006/navbar-arrow.svg.zip)
Color: #9E9E9E
Hover State Color: #757575

##### Cell Hover State Background Color
Background Color: #EEEEEE

**Comment by bliker** [comment]
Why not use electron/nw.js and use native menu whenever possible.

**Comment by ellisonbg** [comment]
If "whenever possible" was 99% then sure than makes a ton of sense. But hosted/online deployments are becoming more and more important so we have to maintain a strong "browser first" philosophy. A great example is UC Berkeley which is starting to teach *every single student* data science using a hosted/online version of JupyterHub.

Also, if you design for the browser, the moving to something like electron isn't too bad. Moving the other way is more difficult because the browser lack things (like menus, sane keyboard handling, tabs/panels, etc.).

**Comment by SylvainCorlay** [comment]
An issue with these specs is that it is all on OS X retina, and does not reflect how things are going to look like on other platforms (Windows, Linux, OS X non-retina).

Screenshots should rather be done on low-definition screens, and the zoom applied after the screenshot, with a tool that will not use a smoothing algorithm for the image upscaling, such as taking a screenshot of a gimp/photoshop zoomed-in image...

**Comment by bliker** [comment]
This might be a personal opinion but this kind of pixel specs seem a bit out of touch with the actual web development. 

- Lucida Grande is on like 0% of windows/linux so font stack needs to be established rather than single font
- Heights of the cells should be defined in terms of the font size (in percent or em) 
- No way the shortcuts would fit on other platforms (but I think they are great)

**Comment by SylvainCorlay** [comment]
@bliker agreed. Although font-based icons have specific requirements in font-size to be sharp (pixel-perfect).
