### ISSUE TITLE
Keyboard shortcut (`⇧ ⌘ K`) brings up the Table of Contents and DELETES CODE

### ISSUE THREAD

**Issue by jbwhit** [jupyterlab/jupyterlab#16096]
## Description

Using the default keyboard shortcut (`⇧ ⌘ K`) to bring up the Table of Contents (screenshot) deletes the line of code your cursor is on if you're in Edit mode.

<img width="435" alt="Screenshot 2024-04-02 at 3 28 33 PM" src="https://github.com/jupyterlab/jupyterlab/assets/105829/2036f98f-afa5-463b-a48e-47fa5e52f209">

## Reproduce

Brief (66 second) unlisted YouTube video demoing this problem: https://youtu.be/KAsPczNL7YA 

1. Have cursor in edit mode in a non-empty line of code (in code cell, or markdown, same problem in both).
2. Envoke the keyboard shortcut: `⇧ ⌘ K` 
3. See that the Table of Contents has appeared, and the line of code has been deleted.

## Expected behavior

I would expect the keyboard shortcut to ONLY open the Table of Contents panel, not to ALSO delete the line of code when you envoke it.

## Context

- Operating System and version: Mac 
- Browser and version: Firefox, but also confirmed the behavior with JupyterDesktop
- JupyterLab version: 4.1.5

**Comment by krassowski** [comment]
PR https://github.com/jupyterlab/jupyterlab/pull/16078 will address this issue as follows:
- Ctrl + Shift + K will still be bound to removing the current line by default
- when line gets removed, the ToC will not open avoiding confusing double action
- you will now be able to remove the Ctrl + Shift + K binding in the settings

I know this is different from the behaviour that you ask for - this is because removing a binding (Ctrl + Shift + K) that users may be already used to is a bit harder and we would need to have a larger study to see if this is acceptable - so this may still happen but not in the upcoming release.
