### ISSUE TITLE
"Open recent" menu not displaying on startup without open document

### ISSUE THREAD

**Issue by jans-code** [jupyterlab/jupyterlab#16147]
## Description

If i load into the lab with just having the launcher or just a terminal window open the newly introduced "Open recent" menu is not properly working.

![image](https://github.com/jupyterlab/jupyterlab/assets/112409139/c4a87266-5091-4c8c-aa1f-e64196013c79)

## Reproduce

1. Just have a terminal or launcher open.
2. Reload/Close and open again
3. Try to open the "Open recent" menu.
4. (If you open a notebook/document/image... the menu starts working)

## Expected behavior

Should work from the get-go without open document?

## Context

- Operating System and version: Archlinux
- Browser and version: current Chrome
- JupyterLab version: 4.2.0b1

**Comment by krassowski** [comment]
Thank you for testing the beta!

There are two problems:
- when first opening JupyterLab the history of recently opened files is empty. I think we should disable (grey out) the menu in such cases.
- when reloading - I can reproduce an issue with the menu; while the history does get properly persisted and loaded, the menu is not updated. I think this may be fixed by adding `this._recentsChanged.emit(undefined);` in the `_loadRecents` function at the very end.

https://github.com/jupyterlab/jupyterlab/blob/5cfcae170275c4d7f5a60ba8df66d58b7b6df9a1/packages/docmanager/src/recents.ts#L205-L221
