### ISSUE TITLE
Adjust prompt rendering based on width of notebook/console panels

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1614]
Depends on #1613 

When notebook or console panels get narrow, the prompt starts to take up too much space. It would be nice to minimize the prompt based on the width of the panel.

* Wide = normal view
* Narrow = Only show the `[12]:` part of the prompt
* Tiny = Omit the prompt text entirely, but leave a very narrow prompt div to server as a drag handle.

**Comment by stsievert** [comment]
I'd appreciate this. On my 13" screen, the width of the notebook cells is 61 characters when two notebooks are displayed side-by-side and the browser has the entire screen. This makes the code hard to read. I think this would be important for mobile too.

At first, I didn't want this because of #4028. Now I do.

**Comment by stsievert** [comment]
Here’s a screenshot of jupyterlab on mobile (courtesy of pangeo.pydata.org)

<img width="140px" src="https://user-images.githubusercontent.com/1320475/39714126-b8aee54c-51ee-11e8-9315-754be631db84.png" />


I have to go to landscape to read code effectively.
