### ISSUE TITLE
Increase/Decrease Text Editor Font Size not working

### ISSUE THREAD

**Issue by matthewgasbarro** [jupyterlab/jupyterlab#16182]
## Description

Increase/Decrease Text Editor Font Size is not working and is a no-op

## Reproduce

1. Open a Text Editor in either JupyterLab 4 or Notebook 7
2. Type in some text
3. Click on Settings -> Increase/Decrease Text Editor Font Size
4. See that no font resizing occurs

Browser console will show following JavaScript error
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'fontSize')
    at execute (commands.js:141:77)
    at c.execute (index.es6.js:364:33)
    at p.triggerActiveItem (index.es6.js:6365:27)
    at p._evtMouseUp (index.es6.js:6707:14)
    at p.handleEvent (index.es6.js:6510:22)
```

![chrome_PtBVZmiGKp](https://github.com/jupyterlab/jupyterlab/assets/11775352/ce9fba98-bce1-498c-9973-b544ff6a6355)

## Expected behavior

Text should resize accordingly

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome Version 123
- JupyterLab version: 4.1.5
- Notebook version: 7.1.2

**Comment by krassowski** [comment]
This seems to be coming from this line:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/fileeditor-extension/src/commands.ts#L261-L264

It was not caught by type checking because config is typed as `any`:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/fileeditor-extension/src/commands.ts#L147

which is another argument for forbidding `any` (https://github.com/jupyterlab/jupyterlab/issues/16038).

And we will need to add a test case for these commands.

**Comment by janengcodes** [comment]
Hi, we have been trying to solve this issue. When trying to reproduce the error, we were getting uncaught error saying that fontSize was undefined. However, after adding console.log statement in the code sections referencing fontSize (in commands.ts) we were not able to see any of our console.logs and were wondering if its possible that fontSize is being referenced somewhere else, which is causing the error to be thrown. When trying to trace the error in the console, it was unable to point us to a file. We tried catching the error as well in commands.ts but it had no effect. Are there any other suggestions of where this uncaught error may be originating from?

**Comment by krassowski** [comment]
@janengcodes if you did not see the logs, did you check that logs which you add in other places are visible? I would suspect that you are may not be using the compiled dev versions (do you see a red strip/bar at the top of the page?)
