### ISSUE TITLE
Issue with Python indented structures in JupyterLab

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#16196]
## Description

Consider the following snippet -
```python
def fn():
    print("hi")
    for i in range(10):
        print("hello")
```
If the cursor is at the end of the last line and enter is pressed twice, the user is sent outside the function definition which is unintuitive. Attaching a gif demonstrating this - 
![enter-indentation](https://github.com/jupyterlab/jupyterlab/assets/30082866/eafc15f4-883f-4867-80e7-a45de93a3453)

This happens even when defining functions in a class. 

## Reproduce

<see gif>

## Expected behavior
I would expect the behavior to be the same as lab3/vscode. 

![vscode-enter-indentation](https://github.com/jupyterlab/jupyterlab/assets/30082866/71bf19b3-a861-4d8c-80ec-c80fa8b72795)

## Context

- JupyterLab version: 4.1.5

**Comment by krassowski** [comment]
For reproduction upstream: https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge3B5dGhvbn0gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZy1weXRob24iCmltcG9ydCB7IGluZGVudFVuaXQgfSBmcm9tICJAY29kZW1pcnJvci9sYW5ndWFnZSI7CgpuZXcgRWRpdG9yVmlldyh7CiAgZG9jOiAiZGVmIGZ1bmMoKTpcbiAgICBwYXNzXG5cbmNsYXNzIENsYXNzOlxuICAgIGRlZiBtZXRob2QoKTpcbiAgICAgICAgcGFzc1xuIiwKICBleHRlbnNpb25zOiBbYmFzaWNTZXR1cCwgcHl0aG9uKCksIGluZGVudFVuaXQub2YoJyAgICAnKV0sCiAgcGFyZW50OiBkb2N1bWVudC5ib2R5Cn0pCg==

**Comment by krassowski** [comment]
Dedenting is intentional in the `lang-python` implementation by CodeMirror according to this [code comment](https://github.com/codemirror/lang-python/blob/cc69f687f582366af5245472a775351d0fcb8f48/src/python.ts#L11-L12) and the reasoning was given here: https://github.com/codemirror/lang-python/pull/4#issuecomment-887681931

> I think this is the worst example, where the user intends to end the block, leave a blank line and start a new block of code but the indentation is forced into alignment with the body:
> 
> ![gif](https://user-images.githubusercontent.com/44397098/127196961-088d70f7-3745-4768-a2aa-8122cb14eae5.gif)

However, I think that dedent on enter should only move you one block back, not two blocks back. I can reproduce the suboptimal behaviour in CodeMirror playground:

![should-have-dedented-once](https://github.com/jupyterlab/jupyterlab/assets/5832902/0f9305fb-f40c-4de3-8c21-0fca234400f3)

And because there is no dedent when typing function definition (indent on input is not implemented for Python for this case):

![no-dedent-on-method](https://github.com/jupyterlab/jupyterlab/assets/5832902/bd031895-0f0c-4945-baea-da80b5fb1f1b)

The current implementation is _de facto_ fighting the user who tries to add a method to a class definition (whether they decide to add a new line per convention, or to start writing in the first new line they end up with wrong indentation anyways). I will open an issue upstream to discuss.
