### ISSUE TITLE
Rewrite "pending input" popup to be clearer

### ISSUE THREAD

**Issue by mr-aryanwasule** [jupyterlab/jupyterlab#16320]
run code problem _the cell not executed due to pending input _ **the cell has not been executed to avoid kernal deadlock as there is another pending input! Submit your pending input and try again_**
   #this problem faced...

**Comment by krassowski** [comment]
This means that one of your cells has an input box which you need to submit before you can continue. For example in Python the input boxes come from executing `input()` or `getpass()` functions (but specific kernels can sent these boxes any time when user input is required):

![input-box](https://github.com/jupyterlab/jupyterlab/assets/5832902/8acee943-a396-4c0b-b5a8-244969d093b5)

**Comment by JasonWeill** [comment]
@mr-aryanwasule Can you please provide information about the OS name and version and the JupyterLab version you're running? Also, if possible, attaching a notebook or a screen shot of the problem would help us to diagnose this issue further.

**Comment by krassowski** [comment]
(To clarify, further details are not needed here - the dialog just needs to make the instructions easier to understand; currently this guards against kernel deadlock but users have no idea what a kernel deadlock is because, well the guard works well against it; the instructions need to specify how to recover, i.e. type something in the input box and press `Enter`)

**Comment by krassowski** [comment]
Flagging this as higher priority because it was reported a few more times, see:
- https://discourse.jupyter.org/t/input-function-not-working/2290/14
- https://discourse.jupyter.org/t/cell-not-executed-due-to-pending-input/24036
