### ISSUE TITLE
.csv file viewer very slow

### ISSUE THREAD

**Issue by asteppke** [jupyterlab/jupyterlab#16329]
## Description
I vividly remember that during the transition from Jupyter Notebook to Jupyter Lab that there was a presentation from the core team where a `.csv` file was opened and scrolling through a huge table happened smooth and instantaneous.

Recently I need to work more and more with `.csv` files and even scrolling from top to bottom in a very moderately sized table (15 rows, 2000 columns) takes roughly 1-2 minutes. 

No other parts of the interface (menus, notebooks, side-panels) show any sign of sluggishness. 

## Reproduce

1. Open a `.csv` file of moderate size (< 1 MB) with mixed contents (numbers and strings)
2. Scroll to the bottom and observe the update rate of the output (roughly every 2 seconds)

## Expected behavior

Fast scrolling in both dimensions.

## Context

Linux (RHEL 8)
Jupyterlab 4.1.8
Chrome browser

Several extensions that should not influence `.csv` file behavior as far as I know:

- jupyterlab-matplotlib
- jupyterlab-jupytext
- jupyterlab-code-formatter
- jupyterlab-pygments
- jupyterlab-collaboration-extension

**Comment by krassowski** [comment]
Can you also reproduce this with the examples on https://lumino.readthedocs.io/en/latest/examples/datagrid/index.html ?

**Comment by asteppke** [comment]
@krassowski Thank you for looking into this instantly! 

In the lumino examples the "Streaming Rows", "Random Ticks 2" and "Trillion Rows" are very slow (2s updates) here.

**Comment by JasonWeill** [comment]
In the examples on my computer (macOS Ventura, M1 Pro chip, Firefox), "Random Ticks 2" is well below 60 fps when I scroll on either axis. Other examples on that page render smoothly. With Chrome on the same computer, only "Streaming Rows" displays very slowly.

Which version of Chrome are you using? Do you have hardware acceleration enabled? If so or if not, how does the behavior change when you disable/enable hardware acceleration in Chrome settings?

**Comment by ivxnwm** [comment]
I have the same problem on Safari Version 18.3.1 (20620.2.4.11.6) on MacOS Sequoia M4 Pro.

My file is only 35 KB, 122 rows and 14 columns, yet the refresh rate is less than 1 FPS.

No problems with using Chrome (135.0.7049.96) on the same laptop, and Chrome is able to perfectly handle much larger files. Disabling hardware accelerators for Chrome reduces FPS to about 10. For Safari there is no way to enable/disable accelerators - they are always on.

In the Lumino examples, again, Chrome works perfectly and Safari really struggles with all of them. For some reason I cannot scroll the Copy table at all without using scroll bars in both browsers.

The problem is the same when using the web version of Jupyter and when running it from terminal.

Checking Activity Monitor shows that Safari and Chrome both use about the same amount of GPU when scrolling.
Seems the problem is with the browser and not Jupyter.
