### ISSUE TITLE
Encoding more information in the virtual scroll bar

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#16332]
### Problem

The virtual scroll bar is nice, but now that its a custom scrollbar, it seems like we can use it to encode more information. 
### Proposed Solution

For example, maybe code and markdown cells should look slightly different. We could also imagine encoding something about which are the big code cells with some sort of very slim sparkline. I'm not sure of any exact idea - but it seems navigation could be greatly enhanced by hinting at what is in the cell. Other ideas including showing which cells have an error etc.

![image](https://github.com/jupyterlab/jupyterlab/assets/1813603/0bb3f515-97b3-4de7-9adc-5519198baa6c)
Above cell 3 is markdown (gray) and cell 2 has more than 2x the code than cell 4.

**Comment by krassowski** [comment]
Related to:
- https://github.com/jupyterlab/jupyterlab/issues/3738
- https://github.com/bollwyvl/ipython-notebook-navigator

We do not want to render a mini version of the cell in the scrollbar as this would take away the performance benefits of virtualization.

- We already have the size information about cells and outputs, we could resize the scrollbar cells accordingly.
- I think showing the execution count number by the code cells could be very useful, because right now there is a disconnect between cell index and the execution number which users see in the notebook. I think the cell index is not needed if we have a rich representation of the cells, but it could still be shown on hover.
- For code we could store information about number of lines in the editor, and:
  - use 1-3 variants like:
     - ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/7db973b7-abdd-4084-8380-37c1322b3bb9) for an editor with a lot of text/code,
     - ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/bad43288-9de0-48f0-bbf2-fc66c14dedf1) for an editor with medium amount of text, and
     - ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/f451ad05-3738-4792-8386-564c202b93a2) for an editor with little text.
  - or we could even generate the number of lines (and lengths) dynamically to to match the text content; this will still be way faster to render than syntax highlighted code
- Users will be interested to find cells with specific outputs, cells which are executing, and cells which failed to execute; we could show:
  - ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/fe64fe5f-2d44-4c40-9aaf-68ee67bf1045) a spinner in output section of cells which are executing
  - ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/155242ec-9975-42e5-ac14-dfc6397b48c6) an alert for cells which have an exception traceback in outputs
  - I think that a generic text output should have no icon; maybe text lines like in editor possibly in a different colour
- For outputs which include plots we could show:
   - ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/ce20036b-b057-4a66-8f8f-149a899224b9) or ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/db93b094-d4b0-4df7-8e5f-5cfc85cfb7a1) one image/plot icon regardless of number of plots/outputs
   - ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/9f8be44a-a8d4-4ccc-8d59-5b3cf912266a) or ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/2ea64b0c-5747-42a0-b2ee-ef505c5fc268) show "multiple pictures" icon if there are multiple plots
   - show one icon per one output

We could also have a different icon for ipywidgets too.

There are different tradeoff depending on which information we decide to display. For example encoding both the execution count/cell type and the cell editor content seems to leave no space for output unless we break with the "each cell occupies equal height in the scrollbar" convention (or make the cell box very wide). Showing just the editor content and output seems like a better use of space but then there is no execution counter to show:

| Execution counter/cell type + editor content | Editor content (left) + output (right) |
|--|--|
| ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/23ef652e-c749-4322-a6fb-506b39dec940) | ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/9a57e07d-db70-4c7a-b235-19384f3d2697) |

In the `Editor content + output` option we could show the execution counter on hover. The executing cells could have a spinner (and in a future a progress bar, one API for this is available).

**Comment by krassowski** [comment]
Implementation-wise we would need to modify the virtual renderer for the notebook:

https://github.com/jupyterlab/jupyterlab/blob/d86e3cd521b345abf3c6548585d12d63a4226d55/packages/notebook/src/widget.ts#L1317-L1335

it looks like it already can access cells so rendering it should be easy (set aside cross-browser CSS issues we encountered during the initial implementation).

We may need to ensure that rendering is selectively updated when cell editor content, execution status or outputs change. Currently the entire scrollbar is redrawn on every update request, but as we start making the nodes more complex and need to synchronise state more frequently we need more granular rendering updates.

**Comment by mlucool** [comment]
> * We already have the size information about cells and outputs, we could resize the scrollbar cells accordingly.

I like that they are all the same size now. It's a good mental model for me

> * I think showing the execution count number by the code cells could be very useful, because right now there is a disconnect between cell index and the execution number which users see in the notebook. I think the cell index is not needed if we have a rich representation of the cells, but it could still be shown on hover.

I'm on the fence here, but I see the argument to go to execution number.

> * For code we could store information about number of lines in the editor, and:
>   
>   * use 1-3 variants like:
>     
How would we define these amount of code? I also find the icons proposed a bit large

>   * or we could even generate the number of lines (and lengths) dynamically to to match the text content; this will still be way faster to render than syntax highlighted code

This is similar to the line I proposed above - but mine was more of a hint.

> * Users will be interested to find cells with specific outputs, cells which are executing, and cells which failed to execute; we could show:

I like the idea of showing a spinner and an alert for failed cells. I agree - success should not show anything in your face (I could see executed vs. not having a very subtle indication)

> * For outputs which include plots we could show:

I personally think this gets too cluttered.

> There are different tradeoff depending on which information we decide to display. For example encoding both the execution count/cell type and the cell editor content seems to leave no space for output unless we break with the "each cell occupies equal height in the scrollbar" convention (or make the cell box very wide). Showing just the editor content and output seems like a better use of space but then there is no execution counter to show:

I think we should really keep these as minimal hints and shy away from anything too in your face. How about:
1. Cell colors for type and error (maybe this is a shade of red)
2. Icons for important things that change the cells status: running, queued.
3. Numbering system is configurable (execution count or cell number)
4. Two constants for code size. If is <10 LOC it shows a small marking, < 50 LOC a medium one, and >50 a larger marking. I'd still prefer something very slim and subtle.

**Comment by krassowski** [comment]
> I like that they are all the same size now. It's a good mental model for me

I agree that this is advantageous, especially because very long cells can be skipped easily. If we wanted to go for the squiggle lines representing the actual number of code lines in the editor, we could cap it at showing at most say 20 lines + a gradient or symbol to indicate that there is more lines.

>  I also find the icons proposed a bit large

My screenshots of the MDI icons were possibly a bit large, and we may simplify them slightly, but there is only so much we can do here.

> 1. Cell colors for type and error (maybe this is a shade of red)

Using color would conflict with using color for cell selection status. Currently we use light blue for selection and dark blue for active cell:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/e9a72bc5-efe1-44e5-b560-01a486987f5c)

A frequent feature of minimap is to overlay both selection, and the boundary of the viewport, as done by https://github.com/replit/codemirror-minimap (blue - selection, grey - viewport):

<img height="275" alt="image" src="https://github.com/replit/codemirror-minimap/assets/16962017/cb2f33a2-726f-4395-a8bd-8d219a74b1e6">
<img height="275" alt="image" src="https://github.com/replit/codemirror-minimap/assets/16962017/3b148589-0883-4eb0-8b26-584909cb0900">

If we use colors for cell types (and execution status), then this becomes tricky, especially when we get to the details of making it meet AA accessibility standards.

We could:
- (a) increase the border width and then use the border color to indicate selection/active cell, and make background indicate cell type/status (but this is still conflating multiple types of information with the same visual indicator), or
- (b) strive for a more faithful representation of the notebook structure where each cell would have two boxes, one for input and one for output (if present), and the background around these boxes would change color to indicate selection/active status; then the content of the boxes can take any color (but also, markdown cells would have no output, so they would already be easier to spot).

I feel like (b) could be more intuitive to users, although the size of the scrollbar would increase.

**Comment by mlucool** [comment]
The highlighting that is there seems like a waste of all that space as users rarely multi-select cells (at least in my exp). I was thinking its outline as it is in the notebook. That is:
![image](https://github.com/jupyterlab/jupyterlab/assets/1813603/53397bb9-2760-459a-b7a7-eeb9718cd4a4)

Exclude the bolds/lack of thinness of the lines, but now you can see what is on screen at any time easily (which to me is the a key part of the minimap).

Now we still have some room inside the cell to mark running/queued (e.g. reusing the *) and use a simple single color to call out markdown (e.g. a very light gray).

**Comment by krassowski** [comment]
> now you can see what is on screen at any time easily (which to me is the a key part of the minimap)

For reference this was previously included in a mockup of virtual scrollbar by @GabrielaVives here: https://github.com/jupyterlab/jupyterlab/issues/13343#issuecomment-1764740308 but by using background of the cell:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/b990aa05-c2ec-46da-955c-3945f0123455)

I think we could have some kind of outline box with high transparency, like in the codemirror-minimap:

<img height="275" alt="image" src="https://github.com/replit/codemirror-minimap/assets/16962017/3b148589-0883-4eb0-8b26-584909cb0900">

this still allows to see the colors underneath.

**Comment by krassowski** [comment]
https://github.com/jupyterlab/jupyterlab/pull/16392 makes a first steps by implementing the viewport indicator and refactoring code so that we can add more information to the scrollbar without performance penalty:


![viewport-indicator](https://github.com/jupyterlab/jupyterlab/assets/5832902/02af61a0-1358-486f-83a9-55a7c5f2eca7)

**Comment by krassowski** [comment]
The next step is adding more information. From quick experimentation I found out that it is feasible to just add the source code of the cell (without syntax highlighting/rendering markdown/math - anything) to the scrollbar and it works very smooth even with very large notebooks - unfortunately the recording does not do it justice (it skips many frames each time I try to use the browser scrollbar - might be a Wayland compositor issue on my side):

![wip](https://github.com/jupyterlab/jupyterlab/assets/5832902/9e11ba3b-d2e6-4db1-bb02-97f7b2a57f02)

It is currently trimmed to a few lines but we can adjust this further.

I will now implement running status indicator and open a draft PR to allow for testing.
