### ISSUE TITLE
Handling notebook code cell stream outputs in RTC

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#16480]
### Problem

Currently, outputs are a `YArray` which elements are non-shared objects. This is very inefficient memory-wise for outputs of type `stream`, because each time new data arrives on a stream, the whole output is replaced with a new one which is identical to the previous one except for the `text` array, which has one more element.
For instance, consider the following Python cell source code:
```py
for i in range(1000):
    print(i)
```
The first `print` will create the following cell output:
```json
{
  "output_type": "stream",
  "name": "stdout",
  "text": ["0\n"]
}
```
The second `print` will create the following cell output:
```json
{
  "output_type": "stream",
  "name": "stdout",
  "text": ["0\n", "1\n"]
}
```
etc.
From a CRDT point of view, the first element in the outputs `YArray` is deleted, and a new one is inserted. As data streams, the CRDT memory footprint grows exponentially.

### Proposed Solution

In jupyter-ydoc, notebook code cell outputs of type `stream` have been changed in this [PR](https://github.com/jupyter-server/jupyter_ydoc/pull/201), so that each element in the outputs `YArray` is of type `YMap`, and if the output is of type `stream`, the value corresponding to the `text` key is of type `YText`. This way, streaming data can just be appended to the `YText`, leading to a linear memory growth.
I am investigating how JupyterLab can take advantage of this. It seems that multiple packages are involved, such as `outputarea` and `rendermime`. I would appreciate any feedback :smile: 

cc @Zsailer @ellisonbg

**Comment by ellisonbg** [comment]
This is definitely inefficient and could lead to unwanted memory growth for relatively common and simple use cases. At the same time, there are many usage cases where there really isn't a need to store the full history in the CRDT. For example, with a progress bar or basic text streaming output, storing the final state in the CRDT should be fine (not sure why users would want to replay the history of the scrollbar. Because of that, I am wondering if we also might want to introduce a new output metadata field that indicates that only the final state should be stored in the CRDT. That way people building outputs could decide if the full history needs to be stored or not (in additional to what you are proposing).

**Comment by davidbrochart** [comment]
But when do we know that it is the final state of the output?

**Comment by davidbrochart** [comment]
I don't see how to implement that. Ultimately, it's the user code that knows if it's the last e.g. `print()`, and there is nothing in the language that can carry this information.

**Comment by ellisonbg** [comment]
Yeah, for some output types like streaming stdout, that would have to be built into the kernels themselves that trap and forward stdout/err.

**Comment by krassowski** [comment]
Should this be closed given https://github.com/jupyterlab/jupyterlab/pull/16498 was merged or is there more work to be done?

**Comment by davidbrochart** [comment]
Yes!
