### ISSUE TITLE
hanging and freezing

### ISSUE THREAD

**Issue by TylerRyan16** [jupyterlab/jupyterlab#16594]
im using plotly and pandas to create a map of the US. i have one singular scatter geo figure and jupyterlab constantly hangs, freezes, and crashes. its genuinely so frustrating how your program cant even handle ONE map, not even one. what is the point if its constantly running out of memory and crashing? its frustrating and pathetic from a system like this.

**Comment by krassowski** [comment]
I'm sorry that your experience was frustrating.

> what is the point if its constantly running out of memory and crashing

1. Is the JupyterLab hanging and unresponsive, or is you browser tab crashing - can you provide a screenshot?
2. Can you provide a reproducible example?
3. It would be helpful if you could follow the [bug report template](https://github.com/jupyterlab/jupyterlab/issues/new?assignees=&labels=bug%2C+status%3ANeeds+Triage&projects=&template=bug_report.md) and also provide some information about your machine

There are no known issues with JupyterLab hanging or freezing on itself, nor known major memory leaks so it might be that your issue is with the code that you are executing or the visualization library that you are using. If that is the case any volunteer here may not be able to help you much besides directing you to the appropriate repository to report the issue in.

**Comment by JasonWeill** [comment]
@TylerRyan16 I'd appreciate if you could provide the information @krassowski requested, so that others can reproduce your bug. In addition, please review the [Jupyter Code of Conduct](https://jupyter.org/conduct), which applies to communication in issues on our projects. I've personally used plotly and pandas to create maps before in JupyterLab, so your issue requires more detail to diagnose and fix. Thanks.

**Comment by JasonWeill** [comment]
Let's keep the conversation going in #4292, an older issue concerning performance in Jupyter notebooks.
