### ISSUE TITLE
Improve upgrade notification styling

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16608]
### Problem

The upgrade popup has a few usability problems:

1. The button labels are so long that they flow to a second line
2. The button labels are left-justified, not centered like other buttons in Jupyter are
3. The "Open changelog" button label is styled like a link, including an underline, even though it works like a button
4. The tooltip for "Do not check for updates" starts with "If pressed, you will not be prompted", which is verbose.

![image](https://github.com/user-attachments/assets/f57b90d8-5058-406b-b397-2c3c687a1990)

### Proposed Solution

1. Shorten "Do not check for updates" to "Ignore" and shorten "Open changelog" to "Changelog"
2. Center-align button label text
3. Style "[Open] changelog" as text, not as a link
4. Shorten the tooltips to be commands, not conditional statements: for example, "Do not prompt me if a new JupyterLab version is available."

**Comment by krassowski** [comment]
Thanks for opening this, I agree that this needs an uplift.

> Shorten "Do not check for updates" to "Ignore" 

I disagree here, if I clicked "Ignore" I would expect to be prompted on the next update but this button will make no update notifications appear. For ignore the user can click on "x". That said we can change the behaviour, and also I think this button should not be the first one.

Maybe something like `[Changelog] [Ignore] [⚙]` where ⚙ would open settings panel, or just a small menu with three choices: "All releases", "Major releases", "Never" (we currently do not have this distinction I think).

> shorten "Open changelog" to "Changelog"

:+1: 

> Style "[Open] changelog" as text, not as a link

I agree, but the wider context is that (a) technically this is a link (b) we need to disclose to users that clicking on the button will open an external website (unless we rework the implementation to show the changelog in a popup, e.g. by fetching the markdown from GitHub it and iframing it with sandbox just to be safe).

> Shorten the tooltips to be commands, not conditional statements: for example, "Do not prompt me if a new JupyterLab version is available."

:+1: 

Let me know if you think we should open separate issues for any of the suggestions above, but I think it is fair to keep discussing the overall design of this popup in a single issue until we have some consensus on the direction.

**Comment by JasonWeill** [comment]
Typically, JupyterLab uses the Apple style in dialogs, where the primary button is on the right. (Windows-style dialogs put the primary button on the left.) The primary button is usually styled differently; I think that rather than using an underline, it would be better to style the "Open changelog" button (or whatever we call it) with a blue background and white text (when using the default "Light" theme) and perhaps with an icon to suggest that it opens in a new tab/window.

"Do not check for updates" is five words, a very long phrase for a button label. "Turn off update check" would be four words, which I still think is very long, but at least it's shorter. "Disable updates" would be two words. All are longer than "Ignore", but are these still clear enough to inform the user?

**Comment by JasonWeill** [comment]
I was taking a look at the notification schema in apputils, and I found that there is not a provision to add a checkbox as above:

https://github.com/jupyterlab/jupyterlab/blob/d185c9bf3def74d440af1eac1e8a47d5c32c2e1c/packages/apputils/src/notification.ts#L204-L238

In the interest of making incremental progress, can we add a "Disable options" update in a first PR, then add another item for a checkbox in a notification?

**Comment by krassowski** [comment]
> a "Disable options" update

do you mean "Disable updates"? I am worried about using "Disable updates" because it is misleading; JupyterLab does not offer updates (but JupyterLab Desktop does). The button would only disable update checks.

Maybe "Disable update notifications"?

I should probably also mention that the broken line inside buttons that you see is indeed very ugly, but I never saw it like this; maybe we can fix CSS so that it does not do that?

**Comment by krassowski** [comment]
> Typically, JupyterLab uses the Apple style in dialogs, where the primary button is on the right. (Windows-style dialogs put the primary button on the left.) 

Thanks, I did not notice that different OS use different ordering here. If we want to make it a rule, it would be good to add this to the documentation. But as for notifications, I would say this is not currently the case:

![image](https://github.com/user-attachments/assets/54f858a2-39ae-431f-8ee9-7cd422d515c7)

**Comment by krassowski** [comment]
From a quick search:

<img width="300" src="https://github.com/user-attachments/assets/eea57284-afbe-4558-9092-6285e3d2fae1">

<img width="300" src="https://github.com/user-attachments/assets/9e956678-23b2-4099-8aef-45133f31c31b">

<img width="300" src="https://github.com/user-attachments/assets/38f01556-33cc-443b-ae0a-a876cfdabd2f">

<img width="300" src="https://github.com/user-attachments/assets/9b862a78-5622-4d4f-856f-eefd37fd8126">

It looks like only Spyder allows to disable checking for updates altogether from the level of the dialog and it is using the checkbox as suggested before (but then it has to because full screen pop-ups are more annoying than subtle notifications).
