### ISSUE TITLE
Invisible underscores in File Browser

### ISSUE THREAD

**Issue by Enum0** [jupyterlab/jupyterlab#16820]
## Description
Since I have updated my Ubuntu to 24.04 LTS version there is a glitch appeared in Jupyter Lab file browser - all underscores in file/folder names are visually replaced with spaces. When you put the cursor over the folder/file name, the popped up window contains the correct name (with underscores). The screenshot is attached below.

This issue is relevant to Google Chrome Browser, Firefox works fine.

## Reproduce

1. Open JupyterLab in Google Chrome.
2. Open File Browser (Folder icon in the left menu or Ctrl+Shift+F).
3. Find or create a folder/file with underscores in the name (e.g. "my_folder").
4. All underscores in the name are visually replaced with spaces (e.g. "my folder"). However if you put the cursor over the folder, the popped up hint displays the correct name (with underscores).

![Screenshot from 2024-09-26 16-39-54](https://github.com/user-attachments/assets/b24a67c8-68b2-498a-b7bd-7635ca5abbb1)

## Expected behavior

The folder/file name is displayed with underscores (e.g. "my_folder" instead of "my folder")

## Context

- Operating System and version:  Ubuntu 24.04.1 LTS
- Browser and version:  Google Chrome Version 128.0.6613.137
- JupyterLab version:   4.2.5

**Comment by Darshan808** [comment]
@krassowski 
I identified an issue related to the default font `Ubuntu` on Ubuntu 24.04. On a screen size of `1430 x 990`, the underscore character disappears in filenames. This issue can be resolved by either increasing the line height or adding padding to the class `.jp-DirListing-ItemText`.

However, when I attempted to reproduce this issue using my forked JupyterLab repository, I was unable to do so. This discrepancy might be due to the fact that my forked repo is on `4.3 beta`, while the installed version is `4.2.5`.

Given this situation, I would like to know if there is a way to modify the code for the previous version (`4.2.5`), or if it would be more appropriate to leave it as is since the issue may be resolved in the upcoming version.

**Comment by Enum0** [comment]
@JasonWeill thank you for your reply! I am not sure that I am able to fix this issue. I exploit only the user-side of JupyterLab, so I can help with testing if it is required and possible. The JupyterLab's code is a blackbox for me.
And to be accurate, I did not test 4.3 beta. If you think it is worth doing this test, please, share a guide, how to install the beta version.

**Comment by JasonWeill** [comment]
@Darshan808 Already has a pull request that fixes this: #16824.

**Comment by krassowski** [comment]
This is not JupyterLab specific though see for example
- https://github.com/microsoft/vscode/issues/227583
- https://github.com/rstudio/rstudio/issues/3898#issuecomment-2137170838

As per changelog in https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890 installing `fonts-ubuntu-classic` might help.

**Comment by Enum0** [comment]
Just to follow up, the problem has gone after the recent update.

JupyterLab 4.3.0
Google Chrome Version 128.0.6613.137
Ubuntu 24.04.1 LTS
