### ISSUE TITLE
Markdown remains un-rendered after leaving cell

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#16980]
## Description
Using the array keys to move focus to a markdown cell while in edit mode, unrenders it but when the user leave the markdown cell, it remains un-rendered even though no change was made. 

## Reproduce
Consider the gif below - 
![Markdown-unrendered](https://github.com/user-attachments/assets/cda3de8e-ea8a-4364-8e97-14a6d219dc79)

## Expected behavior
Markdown should go back to the rendered state. 

## Context

- JupyterLab version: v4.3.0 (I've seen this issue since atleast v4.0.x)

**Comment by JasonWeill** [comment]
@divyansshhh In which previous versions of JupyterLab did markdown convert to rendered markdown when a cell loses focus?

**Comment by krassowski** [comment]
I tested JupyterLab 3.6.7 and it has the same behaviour as 4.0, 4.1, 4.2 and 4.3 have (of keeping cell unrendering after leaving it). I personally would prefer if the markdown cells stay rendered as much as possible, e.g. during search (it is a frequent annoyance when they unnecessarily unrender because you then need to go to that cell and render it wasting time - this is especially true of more complex markdown syntax or latex equations). It feels like at least user should be able to configure the behaviour.

**Comment by JasonWeill** [comment]
Reclassified as an enhancement, accepted. Thanks @krassowski

**Comment by peytondmurray** [comment]
I'm happy to take this one on. My plan was to add a configuration option to the notebook settings so that users could set whether they want markdown to render automatically upon leaving a cell. Then I'll just modify the same code path that un-renders a markdown cell when the active cell index changes to do the rendering if appropriate. If this sounds good to everyone, I'll go ahead with this.
