### ISSUE TITLE
Reconsider hard/exact `httpx` dependency

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#17035]
### Problem

`4.3.2` shipped with a very tight pin on `httpx ~=0.28.0` (#17013) due to a small (zero?) window for changing its API. For security-related packages, such pins can make it difficult for users (or their administrators) to keep their environments free from (perceived) vulnerabilities through normal means.

### Proposed Solution

Some alternatives:
- revisit whether something from the `jupyter_server` stack (such as `tornado.httpclient`) can fulfill the "requirement" from #15219
- failing that, make `httpx` an optional dependency, e.g. `jupyterlab[extension-manager-httpx]`
  - and, if possible, loosen the constraint and perform version sniffing to allow for a wider window of (tested) versions, as these may incur _other_ overhead (see below)

### Additional context

`httpx` also hauls along a number of _other_ novel dependencies (vs `jupyter_server`):

```
+h11
+h2
+hpack
+httpcore
+hyperframe
```

**Comment by jtpio** [comment]
Quickly searching the code base for `httpx`, it seems to be used in the PyPI extension manager only:

https://github.com/jupyterlab/jupyterlab/blob/7ff8d16493f1c8b70cd76658aee80e9453c396a0/jupyterlab/extensions/pypi.py#L68-L69

**Comment by dlqqq** [comment]
The narrow version range is failing CI on Jupyter AI, because `pip install` is installing several versions of several packages to find a version that supports the version range of `httpx` required by JupyterLab: https://github.com/jupyterlab/jupyter-ai/issues/1138

**Comment by dlqqq** [comment]
In this thread, I see three main proposals:

1. Loosen the `httpx` version range.
2. Make the requests with `tornado.httpclient`, and drop `httpx` entirely.
3. Migrate `httpx` to an optional dependency group.

No. 1 is OK but it still depends on `httpx`, which hasn't had a stable major release yet. Plus it brings in a lot of other dependencies, as you mentioned. 2) is also OK, but I haven't verified that `tornado.httpclient` supports the existing use-cases while producing readable code. 3) raises some usability concerns for me. With 3), it seems as though users would have to install this optional dependency group to use the extension manager. IMO, this sort of defeats the point of the extension manager being a UI for people less familiar with using `pip` on the command line.

I suggest we also explore a 4th option: We can replace `httpx` with `requests`, and enjoy the ability to use a mature HTTP client library without dealing with breaking changes.

`requests` is highly mature & stable, is directly maintained by the PSF, is well-documented, follows semver, and uses a non-zero major version. It seems like `requests` is a better fit for `jupyterlab` given how enormously important it is for `jupyterlab` to be stable as well.

The only caveat is that `requests` doesn't offer an async API. However, this can be mitigated by running `requests` calls in a separate thread (which doesn't block the GIL since it's an I/O call):

```py
import asyncio
from concurrent.futures import ThreadPoolExecutor

async def make_call_async(fn, *args, **kwargs) -> Coroutine[Any, Any, str]:
    executor = ThreadPoolExecutor(max_workers=1)
    loop = asyncio.get_running_loop()
    _call_with_args = functools.partial(fn, *args, **kwargs)
    return await loop.run_in_executor(executor, _call_with_args)
```

TL;DR: It may make sense to explore both 2) and 4) and see which one works better for JupyterLab. I'll let the community decide. Need to head out now.

**Comment by dlqqq** [comment]
`requests` also brings in fewer total packages:

```
% pipdeptree -p requests
requests==2.32.3
├── certifi [required: >=2017.4.17, installed: 2024.8.30]
├── charset-normalizer [required: >=2,<4, installed: 3.4.0]
├── idna [required: >=2.5,<4, installed: 3.10]
└── urllib3 [required: >=1.21.1,<3, installed: 2.2.3]
```

```
% pipdeptree -p httpx
httpx==0.27.2
├── anyio [required: Any, installed: 4.6.2.post1]
│   ├── idna [required: >=2.8, installed: 3.10]
│   └── sniffio [required: >=1.1, installed: 1.3.1]
├── certifi [required: Any, installed: 2024.8.30]
├── httpcore [required: ==1.*, installed: 1.0.7]
│   ├── certifi [required: Any, installed: 2024.8.30]
│   └── h11 [required: >=0.13,<0.15, installed: 0.14.0]
├── idna [required: Any, installed: 3.10]
└── sniffio [required: Any, installed: 1.3.1]
```

**Comment by krassowski** [comment]
> is also OK, but I haven't verified that tornado.httpclient supports the existing use-cases while producing readable code.

As discussed on the frontentds meeting call which I mentioned in https://github.com/jupyterlab/jupyter-ai/issues/1138#issuecomment-2518710067 it certainly supports the 99% use case

> With 3), it seems as though users would have to install this optional dependency group to use the extension manager. IMO, this sort of defeats the point of the extension manager being a UI for people less familiar with using `pip` on the command line

This is incorrect, again as discussed on the meeting:
- the extension manager can work and worked without `httpx` in JupyterLab 4.0
- majority of users do not care about the proxy support that `httpx` was used to implement in https://github.com/jupyterlab/jupyterlab/pull/15219
- the <1% of corporate admins who are able to configure proxies should be also knowledgeable enough to use pip extras

The only problem, again as discussed in the meeting, is that we cannot do that in a patch release.

> `requests`

this only shifts the problem from one extra dependency (which is there for a benefit of a handful admins in corporate world) to another dependency which otherwise can also release a breaking change or have a security vulnerability, and even worse is commonly used by lots of other packages _and_ user code, where package/user may expect a very specific version to be present.

**Comment by krassowski** [comment]
CC @dolevf @jgoodson as contributors to the extension manager proxy function. Not sure if you are still active users of proxy, but I wanted to see if you have thoughts about replacing `httpx` for proxy implementation or making it optional.

**Comment by krassowski** [comment]
It looks like `tornado.httpclient.AsyncHTTPClient.fetch` supports proxy when given `tornado.httpclient.HTTPRequest` as an argument (instead of a string) when provided with `proxy_` arguments

> HTTP proxy hostname. To use proxies, `proxy_host` and `proxy_port` must be set; `proxy_username`, `proxy_pass` and `proxy_auth_mode` are optional. **Proxies are currently only supported with `curl_httpclient`.**

I think we could auto-switch to `curl_httpclient` when proxy arguments are set. Any concerns about this?

**Comment by jgoodson** [comment]
I still have a lot of users who are (mildly) affected by this and I know there are plenty of other academic sites using Jupyter Lab in a similar setup. A feature extra gating this would perfectly satisfy me personally, though I don't think that is the best or easiest option. Optional features just for proxy support aren't something I've come across before.

Although I didn't add the httpx dependency, I can't imagine that tight of a pin is necessary. I use it in some libraries I maintain and I've never had an issue, particularly with the really basic use present here, supporting a much larger range of versions. Loosening that pin would be an easy solution to this particular issue. 

As discussed, httpx is far from the only client library that supports proxies.  Requests, Tornado (with libcurl),  urllib2/3 and even the stdlib client will all happily do this, some with less effort than the patch that added proxy support. I do think that in the long run unifying the extension manager http client with whatever else is more broadly used in Jupyter Lab (if it even uses http clients elsewhere) is a good idea, particularly (and selfishly) if that use would consistently use standard proxy environment variables.

**Comment by bollwyvl** [comment]
Strawman up here which just puts back the old window:

https://github.com/jupyterlab/jupyterlab/pull/17041

Whenever this is actually fixed, it will need tests.

**Comment by bollwyvl** [comment]
> requests

... already (and has for a long time) been a dependency of `jupyterlab_server`... for the old `npm` extension  manager. So adding it to `jupyterlab` wouldn't constitute much of change.

The larger issue is `requests`, stdlib, etc. are blocking, which would require wrapping in e.g. `asyncio.run_in_executor` (with its own executor of size 1).

**Comment by jgoodson** [comment]
Ugh, okay, my feelings on the compatibility of httpx versions weresomewhat unwarranted. I see why the pin was made with the breaking change [removing the deprecated use of the `proxies` argument](https://github.com/encode/httpx/blob/master/CHANGELOG.md#0280-28th-november-2024).

I'll see what it looks like to use the Tornado client with this.

**Comment by jgoodson** [comment]
After actually testing the main branch, I'm not convinced this feature works fully as intended right now. There are two HTTP clients in the extension manager, one is the `self._httpx_client` which currently uses httpx to talk to the PyPI JSONAPI and works fine, at the cost of an annoying dependency, and  `self._rpc_client` which uses the stdlib `xmlrpc` client. One problem with this that is that while both are proxied, the `xmlrpc` client uses an example implementation of a transport that uses HTTP CONNECT with the default `xmlrpc.client.Transport` for HTTP instead of `SafeTransport` for HTTPS. Assuming your proxy allows this, it results in unencrypted traffic to pypi.org on port 80. Given that the manager normally connects using HTTPS, this seems like a bug to me. This unencrypted CONNECT proxying method doesn't work with our proxy setup or the default Squid configuration anyway, so it remains broken for us.

I can replace the ProxiedTransport implementation with one that uses the SafeTransport mechanism and I believe it works fine, but I can't actually access the XML-RPC endpoint on PyPI reliably, it doesn't seem happy at the moment, with or without a proxy. It is just alternating between 503 errors telling me the service is unavailable or that it is unhealthy, so I can't actually test this now.

I can replace httpx with the Tornado http client, although this doesn't necessarily help with the additional dependency issue. It replaces a dependency on httpx with a new (optional?) dependency on pycurl to provide the libcurl implementation of the async client. If that is preferable, I can push an example implementation that switches back to Tornado, removing httpx and adding pycurl, possibly as an extra with an error message indicating the need to install it if it isn't present, in addition to fixing the XML-RPC transport issue. I can't think of any easy way to use an async HTTP client that supports proxies without adding some dependency, either httpx, aiohttp, or pycurl. Implementing it with sync code in an async executor is also an option, as discussed.

**Comment by fcollonval** [comment]
@jgoodson Python have encountered some issues last week (here is the [servers status link](https://status.python.org/)). But the services are in a better shape now if you have a chance to re do your tests.
