### ISSUE TITLE
Terminal not sourcing .bash_profile

### ISSUE THREAD

**Issue by GrierPhillips** [jupyterlab/jupyterlab#1733]
I have a function defined in the file ~/.bash_theme which is sourced by ~/.bash_profile. When opening a terminal window I get `bash: parse_git_branch: command not found`. This error can be solved by a simple call of `source `/.bash_profile` I imagine there are users that will have much more than just a git branch function, and would like these to function as they do in a normal terminal window. I'm not sure why the terminal did not do this by default but it would be nice if it would.

**Comment by blink1073** [comment]
Hi @GrierPhillips, which OS are you using?  Does it launch `~/.bash_profile` for every interactive `bash` session?  My impression was that `~/.bash_profile` was launched at startup and `~/.bashrc` was launched when starting `bash`, which is the behavior I'm seeing in JupyterLab.

**Comment by GrierPhillips** [comment]
@blink1073 I am using OS X 10.12.3. I tested your suggestion by moving my commands to .bashrc and the terminal goes back to operating as expected. Will make a mental note of this for the future.

**Comment by blink1073** [comment]
Great, I'm glad you are off and running again.

**Comment by mpacer** [comment]
For people who arrive at this issue, rather than copying everything over you may be able use

`source ~/.bash_profile` in your `.bashrc` file. 

But actually what you probably want to do is to do the reverse.

`~/.bashrc` is loaded in a non-login shell context, `~/.bash_profile` is loaded in a login shell context. 

From that perspective you are likely to want to do the same things you do in the non-login shell context that you do in the login shell context, but not everything you do in a login shell context should be done in a non-login shell context.  

So, from that perspective, put everything that you want to run in every instance of a bash terminal inside your `.bashrc`. Then, leave everything that should only be done in a login shell context in `~/.bash_profile` and include the line `source ~/.bashrc` inside `.bash_profile` file to ensure that all the non-login shell commands are still run.
