### ISSUE TITLE
"Restart kernel" not restarting kernel

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#1779]
![screencap](http://g.recordit.co/AomcjZVJ2k.gif)

Steps to reproduce: 

1. Run `a = 1` in the first cell
2. "Restart kernel"
3. Run `a` in the second cell

Result: `a` is still defined

**Comment by blink1073** [comment]
@gnestor, the issue here is that there are two Restart Kernel commands, and you've selected the one for consoles.  https://github.com/jupyterlab/jupyterlab/pull/1687 partially addresses this by activating a widget before taking action on it, and I opened https://github.com/jupyterlab/jupyterlab/issues/1780 to track disabling commands that are not currently relevant.

**Comment by gnestor** [comment]
Oh, interesting. Ya, "Restart and Clear Outputs" works. #1780 sounds like a good solution.
