### ISSUE TITLE
Expose local cursor changes in editors (abstract editor).

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#1795]
### Problem
In order for a plugin like a code completer to function correctly, it needs to know where the cursor is at any moment. So far, we have been:

1. listening for editor `model.value.changed` events
1. asking the editor where its cursor is via `getCursorPosition()`
1. creating a completer based on the cursor state

This works if a completer is invoked after *some text has changed*. But suppose a document is loaded with text in it and a user places the cursor in a spot where a completer *ought to be* invocable but makes no text changes, without a notification that the cursor has changed, the completer plugin (or any other plugin with a similar lifecycle) can't have enough information to render itself in the current state.

### Proposal
In addition to the editor `model.value.changed` signal, we should expose an editor cursor changed signal as well.

*cf.* https://github.com/jupyterlab/jupyterlab/pull/1778

**Comment by ian-r-rose** [comment]
The `editor.model.selections` map carries a set of selections associated with a given editor `uuid`. A single cursor can be represented as a selection where the start and end positions are the same. This map emits change events for all cursors. You can track the local user by screening the change events for cursors only associated with the local editor `uuid`.

Does this provide enough information to move forward with the completer logic? If not, can we enrich the signals to give more information, rather than adding another signal?

**Comment by afshin** [comment]
Thanks @ian-r-rose, this is exactly what I needed.
