### ISSUE TITLE
why phosphorjs?

### ISSUE THREAD

**Issue by suanfazu** [jupyterlab/jupyterlab#1831]
there are so many great web frameworks. why phosphorjs? there are very few users and docs about phosphorjs.

**Comment by akosyakov** [comment]
@suanfazu it would be interesting to know which frameworks you mean.

**Comment by blink1073** [comment]
Hi @suanfazu, we are building PhosphorJS and JupyterLab simultaneously, building features into PhosphorJS as we need them in JupyterLab.  PhosphorJS provides the desktop-like features we need in JupyterLab, but is also intended to be used in other applications.  PhosphorJS has in-depth inline API documentation, but admittedly it does not yet have broader narrative docs, since we have been focused on adding features.

**Comment by ghisvail** [comment]
I'd be also interested to the know the details about the decision for rolling your own web framework versus picking one from the very large offering. Any chance you guys could write a blog post about it?

**Comment by ellisonbg** [comment]
@ghisvail Yes! I think we should do that, and I am one of the people that could help write such a post. Unfortunately right now I am completely booked with hiring, fund raising, JupyterCon, etc. For time being I will try to give a tweet sized (ok tweet storm) summary:

1) we do use react.js (when we started jupyterlab, we coudn't use react.js because of its problematic patent clause that has since been removed in the last year, in the meantime, we had our own lightweight vdom implementation, with this resolved we are moving more of the code base to react).
2) most of the interesting stuff in phosphor doesn't exist in other frameworks...

On the second point, most folks will ask, "such as what?"...here is a short list:

messages/signals for high performance non-css based layouts (things that allow you to optimize at the level of the browser's rendering/layout, below vdom diffing), DOM element level resize events, command system with builtin integration for menus, context menus, keyboard shortcuts, internationalized keyboard maps, npm based plugin system with dependency injection.

Another way to think about it is this - if we were to start over today, and say "we are using react/vue/angular/etc)" we would still have to build most of phosphor.

**Comment by sccolbert** [comment]
To continue on the points made above:

- a semantic widget hierarchy 
- difficult-to-implement widgets and layouts (dock panel, tab bar, non-crappy menus, etc.)
- non-crippled drag-n-drop
- attached properties
- high perf data grid
- all of the supporting code to implement all of the above
- type safety for all of the above

As Brian said, if we started JupyterLab today and said "we're building this in React", we'd still need 95% of what Phosphor provides. That is to say, Phosphor doesn't compete with React, it complements it (and other frameworks).

**Comment by bionicles** [comment]
@sccolbert @ellisonbg I'm a biologist getting into software engineering and I know Javascript and React but not Typescript. I'd love to use Phosphor but IDK what it does yet, and I have trouble following the codebase because it's written in typescript which I don't know yet, and because the codebase is spread out over many big files, and the docs are auto-generated. 

I think I'm not the only React / JSX guy who would probably find a lot of phosphorjs useful if it were more accessible for noobs. I really just want to embed JupyterLab in a big column in my react / ES6 app and hook it up to a cloud-hosted kubernetes cluster so I can use JupyterLab to prototype algorithms to run against the data in the react app ... but it's unclear where to begin in the quest to build a simple <JupyterLab /> component !

**Comment by nscozzaro** [comment]
I'll just add that until I read this thread I didn't know that PhosphorJS is essentially being built by the maintainers of JupyterLab. I see now that it "is also intended to be used in other applications", but it makes me wonder why it's not under the umbrella of Jupyter? I recognize that this ship has sailed, but from a branding perspective, seeing it on the Jupyter website would give me more "confidence" in using PhosphorJS. I was looking through the source code like, `import from @jupyterlab/...`  "ok",     `import from @phosphor/...` "what is that?"

**Comment by blink1073** [comment]
The reason to keep it separate is that it is intended to be used to build more generic applications that JupyterLab alone.  I used it in my day job to build an app that looked nothing like JupyterLab.
