### ISSUE TITLE
Context for command line mode is lost for notebooks

### ISSUE THREAD

**Issue by dmadeka** [jupyterlab/jupyterlab#2018]
I noticed a strange behavior - if I'm in command mode and I create a new file or explore files in the file browsers I lose the ability to perform command line operations (I tried selecting multiple cells with Shift + Up) until I enter the cell and press escape to go back to command mode. Not sure if this is a feature or a bug

**Comment by blink1073** [comment]
Hi @dmadeka, I think the takeaway is that it is not clear when keyboard shortcuts should apply to the main dock area item versus the side bar item.  This seems like a UI/UX question.

ping @ellisonbg @cameronoelsen

**Comment by ellisonbg** [comment]
We have run into this type of issue in the classic notebook as well. For example, when you click on a toolbar button or use a menu. Basically if you do anything that moves focus away from the notebook document. At different points we have played around with restoring focus on the notebook document, but even in the classic notebook we have alway run into severe, unwanted side effects. Because of this, we have standardized on letting the user controlling focus manually.

In JupyterLab, I overall this this is the right approach - and maybe even more so as it might not be obvious which document command mode should applied to. For example, what if a users does the following:

1) Works with a notebook in command mode
2) Uses the command palette to create a new code console

Which activity should get focus? This simple example clearly shows the fundamental problem. Actions that a users takes in the command palette, menus, etc can create new documents, close documents, and in general take focus changing actions. I don't see any reliable way of allowing these focus changing actions and *then* restoring focus to the "original" activity.
