### ISSUE TITLE
Add favorite and most recent support in filebrowser

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#2043]
Switching among different directories frequently is a pain in JupyterLab. It will make things much more convenient, if users cannot access their favorite or most recently used files.

**Comment by blink1073** [comment]
Agreed!  The most recently used could be tracked by the file browser extension and added to the file menu.  Favorites will have to wait until we have a proper settings system (cf https://github.com/jupyterlab/jupyterlab/issues/515).

**Comment by sccolbert** [comment]
You could easily use a single command for this. Populate the menu with, say, 10 items, where the args contains an index into the "recent history" use that index the command functions to determine the title, visibility, etc. of the menu item. This way, you're not modifying the menu structure every time the history changes.

**Comment by dclong** [comment]
@jasongrout Does this feature fit into 1.0? I really think it's a very useful one.

**Comment by flutefreak7** [comment]
+1

I'm introducing a bunch of folks to JupyterLab at work and one of the first things folks want is a better way to navigate to recently used notebooks.  A way to bookmark favorite folders or at least navigate to recently used notebooks is sorely needed.

If you use notebooks alongside other files in a hierarchy of projects it can become very difficult to find a notebook within JupyterLab (folder hunting is much slower than in an OS-level file browser).  It becomes easier to find the notebook using the OS search tools, but then there's no easy way to open the file within JupyterLab. Drag and drop, copy pasting paths, double clicking, etc don't work - you just have to note where you are and then clumsily click there via JupyterLab.

**Comment by jasongrout** [comment]
I agree that we definitely need smoother ways to work, like some of the suggestions above.

One note:  you can open a file from a path (where the path is relative to the server root) using the `File | Open from path...` menu item.

**Comment by flutefreak7** [comment]
> I agree that we definitely need smoother ways to work, like some of the suggestions above.
> 
> One note: you can open a file from a path (where the path is relative to the server root) using the `File | Open from path...` menu item.

I just tried to use this feature.

 - Open JupyterLab
 - Navigate to a file in Windows Explorer
 - Get full path to ipynb file (annoying that Windows doesn't make this a single click, but whatever)
 - Click `File | Open from Path...`
 - Paste
 - Remove the JupyterLab starting folder from the beginning of that path
 - Click Open
 - I get an unhandled exception.
     - because JupyterLab doesn't support Windows filepaths (#5626, #5051).
 - I then edit all the slashes and then it works

This makes the open from path option effectively useless for the typical Windows user because more work is required to constrain to its limitations than accomplishing the same task in other ways.

I'm considering making a small script that I can use as the file handler for ipynb files that puts the posix-style relative path on clipboard to make this more usable.  Right now it feels like my OS and JupyterLab are two different worlds since I can't double click an ipynb file, paste a filepath into an Open dialog, drag it onto the jupyterlab interface, select a recent file from the start menu or a Task Bar right click menu, etc.  

I don't mean to be whiny, I'm actually just trying to help the Jupyter devs understand the user perspective.

**Comment by jasongrout** [comment]
> I don't mean to be whiny, I'm actually just trying to communicate the user perspective.

And we thank you *very* much. You have a really good point about the mismatch between the paths creating more friction here, making for a very awkward workflow.

Part of the issue here is that we'd like a system that behaves well if you actually *are* in two different worlds, e.g., you're using jupyterlab served from a remote server. That's a difficult problem to have something that works well both locally and remotely.

It sounds like for this particular usecase, the 'recent' menu indeed may be the easiest way to reduce friction with the original issue.

**Comment by tslaton** [comment]
I got started working on something like this [here](https://github.com/tslaton/jupyterlab/pull/1). Since it's a very early proof-of-concept I just did a PR against my fork of this repo. If it'd be better to open a PR against this repo, please let me know.

The idea is to add a favorites area to the main JupyterLab Filebrowser package that will be exposed to extensions.

Then I plan to write an extension that writes and loads a list of favorites folders to/from disk. They will displayed in the favorites area. Adding a favorite will be performed via the right-click menu in the Filebrowser's file list, and removing a favorite will be performed by clicking an "x" on the favorites themselves. The favorites area will be hidden when there are no favorites.

Here's a rough idea of what it looks like right now:

![Screen Shot 2019-06-05 at 4 40 35 PM](https://user-images.githubusercontent.com/9665562/58997577-1eab9300-87b2-11e9-8e38-231383af1c66.png)

If this sounds good, I could use some help figuring out how to expose this favorites area to extensions. 

I'm fairly new to the codebase.

**Comment by tslaton** [comment]
I plan to implement recents as a separate extension [here](https://github.com/tslaton/jupyterlab-recents) when I'm done with favorites v1.0 (should be out within a week).

**Comment by tslaton** [comment]
Here's what favorites currently look like:

![favorites](https://user-images.githubusercontent.com/9665562/60629139-64577d80-9da9-11e9-8f99-5f7563f57fe7.gif)

If you have no favorites or choose to hide the widget (will be a file menu setting), the filebrowser will look like it normally does (no "FAVORITES" or "FILE BROWSER" headers).

Since this is an extension I'm not super concerned about this being worthy of getting merged into JupyterLab core immediately. 

However, if anyone has suggestions that would help me avoid mistakes and/or move in that direction, please let me know! You can look at my code [here](https://github.com/tslaton/jupyterlab-favorites).

Particular things I'm considering:
* Showing full paths as opposed to just the last part of the path in the Favorites area
* What is the notion of favorites for filebrowsers beyond the default browser? Will my schema or my code work?

**Comment by dclong** [comment]
Closed by https://github.com/tslaton/jupyterlab-favorites and https://github.com/tslaton/jupyterlab-recents
