### ISSUE TITLE
Need a story for offline extension install

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2065]
We would need to offer bundled assets for JupyterLab core and document a method for extension authors to bundle their assets.

Bundling options:
- not on the roadmap for npm core: https://github.com/npm/npm/issues/4210#issuecomment-221707747
- [npm-bundle](https://github.com/majgis/npm-bundle) uses standard npm commands has not been maintained in over a year and
does not support scoped packages
- [npmbox](https://github.com/arei/npmbox) is actively updated and has and just merged a [PR](https://github.com/arei/npmbox/pull/87) for scoped packages, but uses non-standard installation `npmunbox foo.npmbox`.

**Comment by blink1073** [comment]
cc @bollwyvl

**Comment by sccolbert** [comment]
What about "use a local npm mirror" ?

**Comment by blink1073** [comment]
Yep, [sinopia](https://github.com/rlidwka/sinopia) is one option there.

**Comment by bollwyvl** [comment]
Yarn has this: https://yarnpkg.com/blog/2016/11/24/offline-mirror/

If yarn was adopted wholesale (not just as a faster preferred alternative for extension rebuilds), each extension could publish their mirror in their package... I don't know if these mirrors can be easily combined, but it stands to reason they could.

Such big packages would be weird and bad on npm, especially in extension-of-extension cares, so I'm now thinking of last mile (conda, pip) packages, not npm packages, as (data) scientists should never have to deal with these things, even if they are happening on their behalf. To that point, thinking about conf.d vs maintaining a "real" package.json in share is clutch. We really want to get out of the post-link business. This boils down to an implicit build on launch, which can be overridden by someone doing, say, a docker build. Indeed, reinvestigating the dll build (shudder) could help reduce the impact of the core build (20s).

From a conda package perspective, i would see a jupyterlab-build package that would have webpack, typescript and friends in its mirror. Extensions would depend on this, such that user-driven extension remixes would incur the extra burden, while the core Jupyter lab package could remain svelte. To that end... It would be great to replace the big animated gifs I'm seeing in the webpack builds with js-animated svg!

**Comment by bollwyvl** [comment]
@blink1073 and I did some thinking about this:
https://docs.google.com/document/d/1UtyayBOMNUpMVkOnoJz_t8gijtDguJWKy5y62lkrWQA/edit#

Locally, the offline cache and build works as advertised. Extensions, npm pack and CLI issues are still a problem. Will update here, plan to discuss at JupyterLab Friday meeting!

**Comment by blink1073** [comment]
@bollwyvl, some more notes from explorations today: 
- I tried `yarn` for all things at the top level and don't see any reason we can't use it.  17sec install with lerna bootstrap from `yarn`'s cache with no internet connection.  :boom:
- I verified that `git submodule add` and adding a lerna package to our tree works.  I think that should be the way we handle "linking":  `yarn run devinstall <repo>` would add the submodule, add it to `lerna.json`, and we would add it to our "dev-mode" `package.json` and `index.js`.  The bonus is that running webpack in watch mode would automatically pick up changes to that linked repository because its files would be among those resolved by webpack.

**Comment by bollwyvl** [comment]
@blink1073 and I did some thinking about this:
https://docs.google.com/document/d/1UtyayBOMNUpMVkOnoJz_t8gijtDguJWKy5y62lkrWQA/edit#

Locally, the offline cache and build works as advertised. Extensions, npm pack and CLI issues are still a problem. Will update here, plan to discuss at JupyterLab Friday meeting!

**Comment by jmmease** [comment]
@blink1073 @sccolbert @bollwyvl Hi all, I'm going to need to setup some kind of workflow soon to use JupyterLab extensions in an offline environment.  Has anything changed on this front since last May?  Any suggestions on the best way forward at this point?  Thanks!

**Comment by toddrme2178** [comment]
@blink1073 @sccolbert @bollwyvl Hi, I am trying to get jupyterlab packaged for openSUSE and this is a major issue since packages are built in a sandboxed environment for security reasons.  So I would also greatly appreciate more information on the status of this.

**Comment by jasongrout** [comment]
@toddrme2178 - are packages built from the git repo, or are you installing from the official pypi packages? The pypi packages have all javascript prebuilt and included, so you shouldn't need to be online for installing the core JupyterLab.

**Comment by jasongrout** [comment]
@jmmease - is https://yarnpkg.com/blog/2016/11/24/offline-mirror/ helpful? We use yarn for installing packages, and it looks like setting up an offline mirror for yarn is straightforward, from those docs.

**Comment by jmmease** [comment]
@jasongrout That sounds promising. But based on #4149 above, I assumed that it wasn't yet possible to point Lab to an alternative npm repo. Is that accurate?

Alternatively, would it be reasonable to create a JupyterLab build in an online environment (with the desired extensions already installed) and then use it from an offline environment without an npm repo?

**Comment by jasongrout** [comment]
> @jasongrout That sounds promising. But based on #4149 above, I assumed that it wasn't yet possible to point Lab to an alternative npm repo. Is that accurate?

I'm not sure of the status of those discussions (and don't have permission to see that doc they mention).

> Alternatively, would it be reasonable to create a JupyterLab build in an online environment (with the desired extensions already installed) and then use it from an offline environment without an npm repo?

That should also be reasonable, though may require some work initially. Do you want to just have a single build that is totally self-contained with a specific set of modules (much easier), never to be extended, or do you want to have a full jupyterlab with just a different set of core modules prebuilt, and the possibility for users to install more extensions?

**Comment by jmmease** [comment]
@jasongrout I was picturing the former option. E.g. Build JupyteLab with ipywidget and bqplot support in an online environment and then distribute that to users in an offline environment. Users would use would be able to use ipywidgets and bqplot without any additional installation (and without yarn) but they wouldn't install additional extensions.

**Comment by toddrme2178** [comment]
Installing the core jupyterlab package is fine, but offline installing
important extensions needed to make it a valid replacement for the
notebook, like ipywidgets and ipympl, is not possible as far as I have been
able to determine since they need to download the jupyterlab-manager npm
package.

**Comment by bollwyvl** [comment]
Not sure where the discussion/prototype went (maybe a closed PR) but to get to a "true" offline install still capable of developing new extensions (which is what I really want at the end of the day), a local user install would need to have:

## option 1: run a local `npm` registry
Something like [verdaccio](https://github.com/verdaccio/verdaccio), and a way to point at the registry (though this _can_ be done with environment variables, and is indeed _required_ for certain complex forms of linked package development).

## option 2: keep a yarn [offline mirror](https://yarnpkg.com/blog/2016/11/24/offline-mirror/)
and a way to combine multiple [yarn.lock](https://github.com/yarnpkg/yarn/tree/master/packages/lockfile) files.

## option 3: punt :football: 
The big option #3 is taking an opinion more like eclipse, where there are pre-built versions of an application, so you might have "geolab" and "statslab" and "3dlab" or something, and each of them are installed into separate app dirs. Not a huge fan of that, as it precludes the ability to hack on extensions offline, even with the built-in friends.


## Then...

These problems can't really be solved in npmland itself, so this would make more sense for `pip` or `conda` packages... but I think that's what most folk would prefer anyway. Whichever of the above options is chosen, an extension package maintainer (not the author, necessarily) would need to be able to, in addition to populating `$PREFIX/share/jupyter/lab/extensions`, would also need to populate `$PREFIX/share/jupyter/lab/packages`, and in the case of option 2, something like `$PREFIX/share/jupyter/lab/lockfiles`.

Given that _professional teams of developers_ still have issues managing conflicts, etc. this might be kind of insane to expect users to support in the case of inevitable failure, but we won't know until we try.

Last I checked (JupyterCon 2017 sprints), the build chain (webpack, postcss, etc.) required something like 15mb of tarballs. I don't recall what the damage was for a full install, much less +widgets +bqplot + d3. Unfortunately, I don't have that laptop anymore, but the build changed a lot anyway since then, so it doesn't matter so much.

Anyhow, happy to take another look at this, as it smells like something that might be _really hard_ to change after 1.0...

**Comment by jmmease** [comment]
Thanks for laying out these options @bollwyvl 

My main priority would be to work out a way to distribute extensions in conda packages, without users needing to be aware of npm/yarn/lockfiles/etc.  When it comes to developing new extensions in an offline environment, I think it's probably reasonable to expect developers to host their own npm registry.

Do you have a sense of whether it would be feasible to handle the distribution of extensions entirely inside conda packages (without a separate npm registry or yarn mirror)?  Or will there inevitably need to be some central npm/yarn repo available during installation?

**Comment by jasongrout** [comment]
An issue with distributing extensions via conda packages is that you'd need to package up all of your dependencies too, and you'd need to somehow make sure that the dependencies you provide are compatible with any other extension that might need the dependency. 

For example, if you need version 1.1 or 1.2 of a dependency, and package up 1.1, and someone else needs 1.2 or 1.3, and packages up 1.3, then in theory you could have compatible dependencies (version 1.2), but neither of you provided it, so it's not available to the end user.

**Comment by bollwyvl** [comment]
> without users needing to be aware of npm/yarn/lockfiles/etc

On a sunny day, that is the goal. But webpack is "in the loop," and so we're all web developers now when things break. As such, we are trying to get a consensus `$PREFIX/share/jupyter/lab/staging/node_modules` by multiple, uncoordinated parties. My concern is that things _will_ break, and it's a question of how inscrutable the error actually ends up being. Anyhow, actually packaging `node_modules` is out of the question for the reasons @jasongrout mentions. However, by building up a consensus collection of npm tarballs and the lockfile, we have a chance of this working.

> handle the distribution of extensions entirely inside conda packages

This is also my goal. 

Unlike hosting an npm registry, which needs server processes, a yarn mirror is just a cache of tarballs, appropriate for checking into a repo (if you don't mind the hit vs. the unreliability of the network) that matches what `yarn.lock` thinks it wants. The tarballs include a full version specification in the name of the file, which can then be dereferenced from inside the `yarn.lock`, so we can handle the few instances of actual duplications of packages with multiple versions (sorry, no data on how many that actually is right now).

> somehow make sure that the dependencies you provide are compatible

Conservatively, this would be replacing all calls to `jupyter labextension` with a package tree, e.g.:
- jupyterlab-offline (the webpack buildchain and all the core deps in `share/.../packages` and `share/../lockfiles`)
- ipywidgets-jupyterlab-offline (the delta from core)
- bqplot-jupyterlab-offline (the delta from widgets)

We'd be merging the lockfiles, and the list of versioned packages. You'd end up with a ridiculous number of dependencies... but there shouldn't actually be any conflicts: while it's certain that two unrelated extensions would eventually both add the same version of a package, I don't think conda would freak out, as npm release _should_ be immutable (after 24 hours, yadda, yadda). Because it stores the _resolutions_, the given example means you'll just get duplication, because here in offline land, there's no way to resolve 1.2. I will take "some duplication of packages that worked as tested" vs "can't rebuild without the internet" any old day of the week.

Again, we won't know until we try! 

I've found that testing this is kind of insane, and am reconstructing my tree of docker/conda/etc. needed to emulate the stuff appropriately. 

> WHOOPS MEANT TO SEND THE ABOVE YESTERDAY

At present, I've gotten back to populating the above chain into a new `offline` directory:
<table class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>len</th>
      <th>sum</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th>size</th>
      <th>size</th>
    </tr>
    <tr>
      <th>package</th>
      <th>path</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>jupyterlab-offline-0.31.12-0.tar.bz2</th>
      <th>offline</th>
      <td>806</td>
      <td>27911041</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">jupyterlab-offline-bqplot-0.3.6-0.tar.bz2</th>
      <th>extensions</th>
      <td>1</td>
      <td>624035</td>
    </tr>
    <tr>
      <th>offline</th>
      <td>1</td>
      <td>435898</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">jupyterlab-offline-jupyter-widgets-jupyterlab-manager-0.33.2-0.tar.bz2</th>
      <th>extensions</th>
      <td>1</td>
      <td>8298</td>
    </tr>
    <tr>
      <th>offline</th>
      <td>12</td>
      <td>4813113</td>
    </tr>
  </tbody>
</table>

`bqplot` is interesting, as now all of its dependencies except for `popper.js` are included in its upstreams. On that note, here are the top ten packages included by size:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>package</th>
      <th>path</th>
      <th>name</th>
      <th>size</th>
      <th>member</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>798</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>offline</td>
      <td>@jupyterlab-services-1.1.4.tgz</td>
      <td>552558</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/@jupyterla...</td>
    </tr>
    <tr>
      <th>799</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>offline</td>
      <td>core-js-2.5.3.tgz</td>
      <td>586699</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/core-js-2....</td>
    </tr>
    <tr>
      <th>1</th>
      <td>jupyterlab-offline-bqplot-0.3.6-0.tar.bz2</td>
      <td>extensions</td>
      <td>bqplot-0.3.6.tgz</td>
      <td>624035</td>
      <td>&lt;TarInfo 'share/jupyter/lab/extensions/bqplot-...</td>
    </tr>
    <tr>
      <th>800</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>offline</td>
      <td>handlebars-4.0.11.tgz</td>
      <td>657458</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/handlebars...</td>
    </tr>
    <tr>
      <th>801</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>offline</td>
      <td>codemirror-5.24.2.tgz</td>
      <td>659243</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/codemirror...</td>
    </tr>
    <tr>
      <th>802</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>offline</td>
      <td>font-awesome-4.7.0.tgz</td>
      <td>671527</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/font-aweso...</td>
    </tr>
    <tr>
      <th>803</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>offline</td>
      <td>caniuse-db-1.0.30000815.tgz</td>
      <td>1148279</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/caniuse-db...</td>
    </tr>
    <tr>
      <th>804</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>offline</td>
      <td>fsevents-1.1.3.tgz</td>
      <td>1837200</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/fsevents-1...</td>
    </tr>
    <tr>
      <th>12</th>
      <td>jupyterlab-offline-jupyter-widgets-jupyterlab-...</td>
      <td>offline</td>
      <td>jquery-ui-1.12.1.tgz</td>
      <td>4053568</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/jquery-ui-...</td>
    </tr>
    <tr>
      <th>805</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>offline</td>
      <td>typescript-2.6.2.tgz</td>
      <td>5572057</td>
      <td>&lt;TarInfo 'share/jupyter/lab/offline/typescript...</td>
    </tr>
  </tbody>
</table>

I'm also putting the the `yarn.lock` files into the packages. Here's some data:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>package</th>
      <th>name</th>
      <th>size</th>
      <th>content</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>jupyterlab-offline-0.31.12-0.tar.bz2</td>
      <td>jupyterlab-offline-0.31.12.lock</td>
      <td>188763</td>
      <td># THIS IS AN AUTOGENERATED FILE. DO NOT EDIT T...</td>
    </tr>
    <tr>
      <th>0</th>
      <td>jupyterlab-offline-jupyter-widgets-jupyterlab-...</td>
      <td>jupyterlab-offline-jupyter-widgets-jupyterlab-...</td>
      <td>192916</td>
      <td># THIS IS AN AUTOGENERATED FILE. DO NOT EDIT T...</td>
    </tr>
    <tr>
      <th>0</th>
      <td>jupyterlab-offline-bqplot-0.3.6-0.tar.bz2</td>
      <td>jupyterlab-offline-bqplot-0.3.6.lock</td>
      <td>193427</td>
      <td># THIS IS AN AUTOGENERATED FILE. DO NOT EDIT T...</td>
    </tr>
  </tbody>
</table>

I haven't really dug into what it might mean to merge them.

As to duplication: yeah, it happens. In fact, with core, ipywidgets and bqplot it happens to 76 packages, including 4 different versions of `yargs`, `ajv` and `kind-of`. Of course, much of that is almost certainly in the build chain.

So anyhow. The offline mirror functionality is working, and these will successfully package up, but the mirror won't be used unless there is a `yarn.lock` in `staging` when `jupyter lab build` is run...  but this is presently not going to work, as [noted in the code](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/commands.py#L759), because of https://github.com/yarnpkg/yarn/issues/3967. 

Anyhow, what will probably need to happen next is to actually start to hack the yarn files... this is going to get a it hairy...

**Comment by bollwyvl** [comment]
Haven't had a chance to dig into this, but in reading, I see the official yarn lockfile package has built-in merge conflict (e.g. '<<<') resolution:
https://github.com/yarnpkg/yarn/blob/master/src/lockfile/parse.js#L396

So the next approach is to hack `commands.py` in jupyterlab:
- on a build where offline lockfiles are detected:
  - for each lockfile, sorted by "was shipped in jupyterlab package" or "name":
    - for the first lockfile, set `previous`
    - for each subsequent lockfile, `git file-merge current base previous`
    - roundtrip with the yarn parser

Haven't tried that yet, but seems like a place to start.

Otherwise, there is `yarn-tools` which might be worth looking at.

Because this will be far more concise with the js tooling (rather than rewriting a python yarn lock parser, tempting as that might be), this will need to end up someplace, probably other than a dumb file. Sigh. Even our problems with too many npm packages make new npm packages. The other downside is a runtime dependency on `git`, but that's another thing i won't be re-implementing any time soon.

**Comment by bollwyvl** [comment]
Here's some updated work:
https://github.com/bollwyvl/jupyterlab-offline

The key bits are:
- [`archiv_extension`](https://github.com/bollwyvl/jupyterlab-offline/blob/master/jupyterlab-offline/jupyterlab_offline/commands.py#L60) and a [`populate_staging`](https://github.com/bollwyvl/jupyterlab-offline/blob/master/jupyterlab-offline/jupyterlab_offline/commands.py#L105) which uses a the `_populate_staging` from `jupyterlab.commands`.

I'm still doing testing, which as i mentioned before is both tricky and slow: lots of builds, lots of packages.

Will try to put some more words on it soon.

**Comment by jmmease** [comment]
Thanks for digging into this @bollwyvl 

In the meantime, I've worked through an approach to creating a conda package that includes JupyterLab plus a set of predefined extensions.  See [jmmease/jupyterlab_delux](https://github.com/jmmease/jupyterlab_delux).

This approach is a bit analagous to a Linux distribution, where the distro chooses a set of base packages but users can adjust this base as long as they have a connection to the package repository.  If users don't have an online connection to the package repository (npm in this case), then they can still use all of the packages that were initially bundled in the distribution.

cc @blink1073 @sccolbert @jasongrout

**Comment by jasongrout** [comment]
Great! That's a lot of the reason that we separated out jupyterlab launcher and jupyterlab itself, so I'm really curious how easy this is.

**Comment by jasongrout** [comment]
Though thinking about it, I think *delux* might convey the wrong impression. In fact, it may make sense to bundle this sort of functionality back into jupyterlab (perhaps as `jupyter lab bundle` or `jupyter lab freeze` or something?)

We've also had conversations about how to appropriately package and message things. For example, right now jupyterlab itself has the ability to install extensions etc., while IIRC, creating a new 'spin' using jupyterlab_launcher doesn't - it's just a single package with whatever you bundled up. If someone wanted to create, say, 'AstroLab' with a predefined set of packages for astronomy, and they wanted that to just serve as an initial set of packges, perhaps we should somehow support that better as a 'package set' on top of stock JupyterLab, so instead of installing "AstroLab", you'd install JupyterLab and the astronomy package set.

In another situation where someone wanted to offer a completely locked-down version of jlab, with no possibility for installing new packages, perhaps that's where creating a new package based on jupyterlab_launcher comes in.

I think there is still a lot of conversation around how to best support all of these usecases. I think using the word *delux* might be misunderstood as implying "better" packages or "more" packages rather than "different" packages, though.

**Comment by jasongrout** [comment]
We should also think more about a naming convention. Right now we have `jupyterlab_<name>` for jlab extensions, so it might be confusing to have `jupyterlab_<distro name>` be a distribution.

**Comment by jmmease** [comment]
Potentially @jasongrout . I wasn't sure how much the JupyterLab team would want to encourage this approach.

One shortcoming is that I don't know how to prevent conda from allowing the installation of multiple jupyterlab spins at the same time.  I used the `run_constrained` line to keep the spin from being installed along with stock `jupyterlab`, but this wouldn't stop two spins from being installed at the same time and clobbering each other.

**Comment by jasongrout** [comment]
This is one more reason why maybe the better approach is a single jupyterlab package with an easy way to install a pre-built set of extensions.

**Comment by beverly0005** [comment]
I finally figured out an easy way to circumvent the internet issue and install jupyter notebook extension offline.

1. First, download all the necessary packages to a flash drive.
- For jupyter notebook extension: download the zipped file from https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master
(give you a zipped file called "jupyter_nbextensions_configurator-master")
- Also download other relevant packages like json5, jupytelab_server, jupyterlab, jupyter_nbextensions_configurator.
- I create a folder called **"pkg_folder"** and put all these packages in the folder

2. Copy the folder "pkg_folder" to the computer (which has no internet connection). For example, here I copy it to D:\ drive, so the folder's path is **"D:\pkg_folder"**.

3. Pip install these packages in command window (I am using Windows system). For example, to install json5 in command window:
- If it is a .whl file: **pip install --no-index -f <folder_path> - U json5**
  "--no-index" is to tell the computer not to search for the package online
  "-f" is to find the package in <folder_path>. Here it is D:\pkg_folder
  "-U json5" is to find some filename like json5
- If it is a zip file: unzip it first so it will give you a folder named "json5" here. Then, run the command: **pip install --no-index <folder_path>/json5**

**Attention:** I made a mistake when I installed python before... which was not installed in its default path. I put it in the folder "D:\Program\Python37", in this sense, when I run pip install, I need to use the command to locate python first: D, that is:\Program\Python37\python.exe -m pip install .... Hope you don't have the same issue as mine...

4. Install these packages sequentially, whenever there is an error report, for example, "Could not find a version.... jupyter_nbexternsions_configurator...", then make sure that you have the package  jupyter_nbexternsions_configurator and install it first.

5. After successfully pip install the jupyter notebook extension package (i.e. jupyter_nbextensions_configurator-master file), run one more command. If you install python in its default folder, I guess you can just do what is suggested online commonly. If you install python not in its default folder, you can try the command: in my case
D:\Program\Python37\Scripts\jupyter-nbextensions_configurator install --user

**Comment by blink1073** [comment]
Closing in favor of #7468
