### ISSUE TITLE
Standardize handling of stderr when running subprocesses

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2126]
cf https://github.com/jupyterlab/jupyterlab/pull/2117#issuecomment-297536821

**Comment by bollwyvl** [comment]
Yeah, I've run into some oddness around this as well. The only error that makes it out (when installing against 0.20.3) is some `fatal` about git tags not being available.

Put it behind a few layers of output buffering (I'm looking at you, `conda-build` `post-link.sh`), and it's basically impossible to tell what's causing a non-trivial problem. With this moving closer to the user (and not just package maintainers), it's not going to be supportable as things will just "not work," without any clear concept of how to get a build working... and I don't even know what state the "last known good" build will be in.

Some possible things (not sure what the right answer is):
- use `Popen` instead of `check_output`. more annoying to deal with, and there are windows gotchas, but could only print, say, on error... 
  - or follow the `npm` behavior of writing to a log file... but usually the location of that file gets jumbled up with all the other (usually nonsense) traceback noise (`emitTwo`?), and people wouldn't read it anyway
- add a `--verbose` flag... or be somewhat more verbose by default, with a `--silent` flag

**Comment by blink1073** [comment]
This was fixed in https://github.com/jupyterlab/jupyterlab/pull/3371
