### ISSUE TITLE
How can I get the notebook panel object associated with a given notebook

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#2176]
Hi,

I am trying to use the close and shutdown command through an extension. In this extension I have a list of open notebooks, and I want to close them and also shutdown their kernels. How can I get the notebook Panel object associated with the notebook I click on, given I have the name of the notebook?

**Comment by blink1073** [comment]
Hi @rsinha25, you can use the notebook tracker to get the current notebook panel, since clicking on  a notebook will make it the current one.  Your plugin would require the [INotebookTracker](https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook/src/tracker.ts#L58) token from `@jupyterlab/notebook`.

**Comment by rsinha25** [comment]
Sure, but is there a way to close a notebook which is not the current selected one?

**Comment by rsinha25** [comment]
Like, I can see you can shutdown the kernel of a notebook, using just the kernel id. Is there a way, to close the notebook as well in that way.

**Comment by blink1073** [comment]
If you have the notebook tracker, you can use `.forEach()` and call `.close()` on the panel whose `.context.path` matches the path you are interested in.

**Comment by rsinha25** [comment]
Ooh, Let me try that. Thanks!

**Comment by rsinha25** [comment]
Thanks a ton!

**Comment by blink1073** [comment]
Cheers!
