### ISSUE TITLE
Better handling of the JupyterLab launcher dependency

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2206]
Check for a compatible version and give the user an informative message if it is not available.

**Comment by blink1073** [comment]
Traceback below, it looks like we can't prevent this because it is in `install_requires`.  Going to have to look into what to do about this:

<img src="https://files.gitter.im/jupyterlab/jupyterlab/RXjy/Screen-Shot-2017-05-12-at-11.07.43-AM.png">

**Comment by blink1073** [comment]
Looking at http://setuptools.readthedocs.io/en/latest/setuptools.html, I don't think there is anything we can do about the above traceback.  What we can do is have a note in CONTRIBUTING.md about what to do in this scenario.

**Comment by fperez** [comment]
No prob, what we want is the section on installing from source working for folks in a dev environment (since that's the audience).  If that means adding `pip install --upgrade jupyter_launcher` to the instructions, before `pip install -e .`, I think that's fine (if their version is older).

That should suffice; I still do think it's worth doing since it might hit anyone installing from source who happens to have an older version of launcher, not just folks in a 100% dev environment.  If they don't have a conda-managed setup that coordinates updates, a manually installed older version would produce the same issue, I think...

In any case, I think this is a good solution path, many thanks!
