### ISSUE TITLE
disable/enable shortcuts using labextensions

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#2317]
Hi,

I am trying to disable a shortcut using labextension. Any help with how I can achieve that?

**Comment by blink1073** [comment]
There is no built in way to do this currently, pending the settings system.   The current manual method would be to add [jupyter.extensions.shortcuts](https://github.com/jupyterlab/jupyterlab/blob/ad7749a84a11946e2defc35c45e906fdd27ef579/packages/shortcuts-extension/src/index.ts#L362) to the [ignorePlugins](https://github.com/jupyterlab/jupyterlab/blob/master/docs/extensions_user.md#advanced-usage) config, and then create and install a custom extension extension similar to our [shortcuts extension](https://github.com/jupyterlab/jupyterlab/tree/master/packages/shortcuts-extension).

**Comment by sccolbert** [comment]
To be clear: user-configurable shortcuts is on our TODO list, but is currently blocked on the settings system, which is being built as we speak.

**Comment by afshin** [comment]
cf. https://github.com/jupyterlab/jupyterlab/pull/2585
We currently don't allow disabling of a shortcut, because deleting a user version still leaves the default value. We should probably add an `enabled` flag to each shortcut setting to allow selective programmatic and user disabling. The PR above is a step toward full configurability of shortcuts and gets us >80% of the way there.

**Comment by ellisonbg** [comment]
Now possible with the settings system, closing.
