### ISSUE TITLE
Feature Request: Ability to Convert a Panel Back Into a Tab

### ISSUE THREAD

**Issue by ssanderson** [jupyterlab/jupyterlab#2331]
Hi All,

Apologies if there's an issue for this (or if there's already a good way to do this that I couldn't figure out).  I was playing around with the latest JupyterLab today and one point of frustration I ran into was that once I move a notebook from a tab into a new window there doesn't seem to be any way to move the notebook back to a tab.  The workaround I eventually stumbled upon was to simply close the notebook panel and then re-open it from the "Running" window, at which point the notebook re-opens as a tab again.  As a user, I would have expected that I could re-dock a panel by dragging it back into an existing tab group.

Here's a GIF of me doing what would have expected to work:

![cant-redock-resized](https://cloud.githubusercontent.com/assets/1588357/26608784/74dc0f1a-456b-11e7-8673-133b27d0f5c2.gif)

**Comment by blink1073** [comment]
The drag target is the center of the target tab panel.

**Comment by sccolbert** [comment]
Yep. Just drag to the center of panel you want to tabify, and you'll the indicator expand to cover everything. The reason we don't have a hot-zone on the tab (we tried this before) is because there is another hot-zone at each edge of the dock panel area which will let you drop to the top/left/right/bottom of *everything*. If we allowed a tabbar hot-zone, that would conflict with the hot-zone at the very top of the area.

We tried this a different way before, where the edge zones were only accessible if you held shift while dragging, but that turned out to be cumbersome. People also complained that the tab bar hot-zones were too small, so we reverted back to the non-conflicting center hot-zone.

**Comment by ssanderson** [comment]
> The drag target is the center of the target tab panel.

So it is!  Feel free to close this as a feature-request.  As a user-experience report, I didn't figure this out in about half an hour of trying, so I suppose do with that feedback what you will.

**Comment by sccolbert** [comment]
Thanks for the feedback! Happy to field alternative UX ideas for this, which take into account the history and explanation I gave above.
