### ISSUE TITLE
npm@5 breaks linking to extensions

### ISSUE THREAD

**Issue by madx** [jupyterlab/jupyterlab#2435]
As [discussed on gitter](https://gitter.im/jupyterlab/jupyterlab?at=593fd880d83c50560c03ac5f), npm@5 breaks using `jupyter labextension link path/to/extension` because of the changed semantics when handling paths as package specifiers.

Here's the npm pull request implementing these changes: https://github.com/npm/npm/pull/15900

**Comment by blink1073** [comment]
As mentioned in the npm issue, there is a library that will allow us to use the previous semantics on npm@5: https://github.com/nicojs/node-install-local

**Comment by blink1073** [comment]
Ah, that lib is apparently equivalent to `npm pack` followed by an `npm install <tarball file>`, so we can just do that directly.

**Comment by madx** [comment]
Is there any way I could give a hand to resolve this?

**Comment by blink1073** [comment]
You could test the following change with your setup and see if it resolves the issue:

```diff
diff --git a/jupyterlab/commands.py b/jupyterlab/commands.py
index eaa3946e8..362e06eb3 100644
--- a/jupyterlab/commands.py
+++ b/jupyterlab/commands.py
@@ -285,7 +285,7 @@ def build(app_dir=None, name=None, version=None):

     # Install the linked extensions.
     for path in _get_linked_packages(app_dir).values():
-        run(['npm', 'install', path], cwd=staging)
+        install_extension(path, app_dir)

     # Build the app.
     run(['npm', 'run', 'build'], cwd=staging)
```

**Comment by blink1073** [comment]
Related: we can't use `npm@5` for the core workflow yet, but it may work if we add all of the deps to the top level `package.json` again: https://github.com/lerna/lerna/issues/856.

**Comment by bollwyvl** [comment]
@madx thanks for the info.

Heh, sounds like the issue over on yarn: https://github.com/yarnpkg/yarn/pull/3342

Yeah, the scoped packages are great, but still break tooling in subtle ways.

As suggested on #2079, would adopting a private `yarnpkg` (inside `jupyterlab labextension` at first, perhaps eventually adopted in core) do terrible things to your workflow? The idea is, as the bundled package manager of `nodejs`, with `npm` we'll have to continuously support a wide set of potential versions in the wild, since we can't control it's version... and at present every user that enables a custom package will have to do so! Of course, there's work on that, too, with conda and conda-forge things!

But if we ship `yarnpkg-legacy.js` (3.5MB js, (800kb compressed, might be able to minify)), which we'll only have to support until such a time as a security feature demands that we upgrade, and be pretty solid on all the nodes we might encounter. This is important, as the reproducibility of `yarn` and `npm@5` are subtly different: https://yarnpkg.com/blog/2017/05/31/determinism/
