### ISSUE TITLE
Launcher Design

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2468]
The current design of the launcher is a bit awkward in that we can get a proliferation of each activity type as the number of kernels grows, and the activity types can get interspersed.  
We have also lost the ability to use an existing (or no) kernel (but you can still do so with a kernel switch).

A thought: what if we had an option for whether the activity should have a kernel, and clicking on an that activity produces a phosphor menu with the available kernels (including running kernels), and selection of one of those kernels launches the activity.

<image src="https://user-images.githubusercontent.com/2096628/26892830-26d1e550-4b7f-11e7-8325-5cbd8c6c5bf8.png" width=500>

**Comment by blink1073** [comment]
cc @ellisonbg @cameronoelsen @athornton

**Comment by ellisonbg** [comment]
I would like to see if we can organize this information in a way that doesn't require the user to do multiple clicks. Even if we had multiple sections and required the user to scroll down to see different categories or views, I think that would be fine. My initial thought is to organize in rows/sections as follows:

1. Terminal/Text Editor
2. Notebooks
3. Consoles
4. Other Categories

Then we could have some virtual sections organized by kernels. Maybe let's see how far we can get with this approach - I don't think that most users have very many kernels (wish we had data).

@cameronoelsen was also wanting to do some other design work on the launcher as well.

**Comment by jasongrout** [comment]
Another interface would be a listing like a file "details" view, showing as one column the kernel, and another column the "type". You could click on the kernel header to group things by kernel, you could click on "type" to group things by type.

But in general, I think I prefer the idea of having a separate selection of the kernel from the activity, even if it requires multiple clicks.

(With the caveat that I may prefer something different after using it for a while...)

**Comment by jasongrout** [comment]
Note that Steve's approach makes it easy to create an activity with an existing kernel, while the current approach means that is much harder (i.e., you have to switch kernels once launched, or you have to a launcher that is constantly changing)

**Comment by jasongrout** [comment]
Another option is to by default have the old approach (i.e., click on the activity, and pick the kernel separately), but if you right-click on the activity, there is an option to 'Create a shortcut', which would let you pick a kernel and then it would create a new launcher icon with that specific kernel set. And we could create a QuickLaunch (?) icon automatically for the server's default kernel, for example.

That way we enable full flexibility, but give the user an easy way to create a quick shortcut for common tasks.

**Comment by cameronoelsen** [comment]
For the launcher design, first I was thinking about the top header area inside of the launcher area. Since the launcher's purpose is to launch new items for users, I feel that the JupyterLab logo and the project's version number only confuses users/is irrelevant to their use case. So I think we should instead replace it with a simple header that says "Start a new activity".

Also, after considering that some launcher items will have multiple kernels associated with them/more items as subitems, I created content sections for different activities that need them. Activity sections also only show a certain amount of items (that we can specify) so that the launcher is still easy to scroll/navigate, but also includes a "show all" button to expand all of the options.

I also believe that we should add a search (sometime down the road) to the launcher so users can easily navigate the launcher through their keyboard. Here is a mockup of the listed ideas in a design and let me know what you all think:

![launcher-new](https://user-images.githubusercontent.com/6437976/27358323-ee8cc8c6-55ca-11e7-93dd-68116fa229a0.png)

**Comment by dhirschfeld** [comment]
How about instead of duplicating everything for notebook/console there is instead just a listing of available kernels. Above the kernels is an Activities section with Notebook/Console/Editor.

The kernel selection is *"sticky"* so that there is always one kernel selected. Initially that would be the default kernel but would change to being whatever was the last used kernel. Upon double-clicking an Activity it would open whatever is appropriate for the currently selected kernel.

e.g. Python3 is the currently selected kernel so double-clicking on the Editor Activity would open an `untitled.py` file. Double-clicking on the Notebook or Console Activity would open each respectively with the currently selected kernel.

Single clicking an Activity would bring up a pop-up allowing you to select a kernel. The currently *"active"* kernel would initially be selected but you could choose another which would then open the Activity with that kernel and make that kernel the *active* one.

Double-clicking a *kernel* could likewise bring up a dialog allowing you to select an Activity to open with that kernel.

I guess terminals would be a 3rd section. On Windows, in a hypothetical future, this could include `cmd`, `powershell` and `bash` (WSL)

**Comment by ellisonbg** [comment]
I started to work on this yesterday and should be able to finish it up this morning.

**Comment by blink1073** [comment]
@rgbkrk also gave some feedback in #2518.

![jupyterlablolono](https://user-images.githubusercontent.com/836375/27444478-58d0e9f4-572b-11e7-8b08-67cdbe101894.png)

**Comment by rgbkrk** [comment]
Thanks all!

**Comment by ellisonbg** [comment]
Done in master!
