### ISSUE TITLE
Icon design

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2472]
Some minor icon related design work we may want to look at for the beta:

* Icon colors are currently black, we may want them to be a bit softer.
* There are a few icons @cameronoelsen and I have been thinking about re-doing.

This stuff shouldn't block the beta, but wanted to at least start to track it.

**Comment by hzarea** [comment]
I've been working on creating icons for .md, .py, .r, .csv, and .yml/.yaml file types in the browser, in addition to a new notebook icon and a new color for the generic file icon. Here is a rough preview I made in Sketch: 
![screen shot 2017-06-27 at 10 41 26 am](https://user-images.githubusercontent.com/27518229/27601913-c93eaf34-5b25-11e7-999f-a6b9517b7371.png)
Cameron and I are also thinking of making an icon for image files. I also still need a way to implement these into Jupyter Lab so that each icon will link to the specific file types, so the sooner we can add that, the sooner, I'll be able to finalize the icons!

**Comment by dhirschfeld** [comment]
In vscode the icon themes are pluggable. It might be nice if that were the case for JupyterLab too.

Maybe it's even possible to reuse the vscode icon themes directly?

Microsoft/vscode#10804
https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_adding-a-new-icon-theme

**Comment by ellisonbg** [comment]
Done in master.
