### ISSUE TITLE
Double scrolling in datagrid (for CSV) and other sizing issues

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2568]
Sometimes the datagrid for CSV files gets a native and phosphor scroll bar:

<img width="457" alt="screen shot 2017-07-03 at 2 50 14 pm" src="https://user-images.githubusercontent.com/27600/27808774-1e52de72-5fff-11e7-84c0-5b855c7c1dec.png">

Also, if a table doesn't take up all the space, it looks a bit odd:

<img width="809" alt="screen shot 2017-07-03 at 2 51 54 pm" src="https://user-images.githubusercontent.com/27600/27808789-38ebab4c-5fff-11e7-8b2c-5571e22cf5b5.png">

Maybe we should grow the column widths somehow?

@sccolbert

**Comment by sccolbert** [comment]
For 1) The double scrollbar is going to be caused by CSS in widgets *above* the datagrid. I'd check the default CSS for document containers and set overflow to hidden.

For 2) I imagined something like this would come up. I don't think we want to expand *all* columns when there is free space, because then each resize would require redrawing the entire grid. Qt has an option to expand the last column to fit. That would be much cheaper (in terms of runtime) to implement.

But if you are just worried about the color, you can control that with the `voidColor` option in the grid theme.

**Comment by sccolbert** [comment]
Part 2b) would we also want an option to expand the last row if there is excess vertical space.

**Comment by vidartf** [comment]
Just a note from a Qt user: In addition to the stretch-last option (which is on by default), the user can configure the scaling mode of the columns (http://doc.qt.io/qt-5/qheaderview.html#ResizeMode-enum), such that they are fixed, user-controlled, or stretchy. If there are multiple stretchy columns, they will distribute the available space equally between themselves, which I have found very useful in the past (this will e.g. allow you to say "stretch all the columns equally, maybe except this one").
