### ISSUE TITLE
Jupyterlab Google drive extension adds blank lines to code,

### ISSUE THREAD

**Issue by pesap** [jupyterlab/jupyterlab#2751]
Hi there,
When I try to open a .ipynb in my personal Google Drive, it adds new (blank) lines each line of code in every cell. Even if it is a new .ipynb it still adds the blank lines in every cell.

I am using
JupyterLab version - 0.26.4

and used 
```bash
jupyter labextension install @jupyterlab/google-drive 
```
to activate the plugin 

Any idea what is happening?

Thanks
![test](https://user-images.githubusercontent.com/2238996/28647271-0da46d56-721b-11e7-815e-a34c53b74831.gif)

**Comment by ian-r-rose** [comment]
Thanks for the report @pesap!

Just had a chat with @Carreau about this, and it turns out that this is a thornier problem than I had first thought. The essential problem is that [nbformat](https://github.com/jupyter/nbformat) allows for two representations of cell source for its on-disk representations of the notebook: a list of strings, and a single multiline string. The kind returned by the Jupyter notebook server contents API is the latter, but we should correctly handle both cases.

When the representation of the cell source is a list of strings, the newlines (`\n`) are *not* stripped (cf. the `split_lines` and `rejoin_lines` functions of https://github.com/jupyter/nbformat/blob/master/nbformat/v4/rwbase.py). Therefore, when we decode that case from JSON, we should join with an empty character, rather than a newline.

This dual representation of cell source is, clearly, kind of error-prone, and it is my understanding that there have been several discussions about deprecating it.

For this issue, however, it is a two-character fix.

**Comment by blink1073** [comment]
While nbformat allows for two representations, the in-memory version uses only strings, a fact we are enforcing after the notebook refactor.  cf https://github.com/jupyter/nbformat/blob/1ca2d1591331b145d190355d9650777ded72717a/nbformat/v4/rwbase.py#L22

**Comment by blink1073** [comment]
Enforcing only a string greatly simplifies the model implementation.  Our `coreutils` `nbformat` will also be updated accordingly.

**Comment by ian-r-rose** [comment]
Right. But in https://github.com/jupyter/nbformat/blob/1ca2d1591331b145d190355d9650777ded72717a/nbformat/v4/rwbase.py#L34 it joins with the empty string `(''.join`), since the list-of-strings keep the newline characters. This PR makes our cell implementation match that behavior.

I realize that this is changing with the model refactor, but then our `coreutils/nbformat` should handle this case correctly as well.

**Comment by blink1073** [comment]
Fair enough, we're going to be replacing the `model.ts` file in its entirety anyway.

**Comment by Carreau** [comment]
One of the thing I'm concern about (which is not JupyterLab implementation) is that the server returns notebooks models with joined lines. This make it pretty easy for any consumer to  the notebook server API to assume that they can "just" dump that on disk and get a valid notebook. 
We've been bitten by that before: In early classic notebook, "Download" was just a "Json.stringify" without the rejoin lines  and it has been a mess since then. In particular it would be nice if Lab handle both single line and line of string to have noisy warning in one of the two case stating that the notebook is invalid in order for alternative content manager to get early warning they may have a bug.

**Comment by blink1073** [comment]
We could do the conversion on the raw data from the server, and our in-memory, typed version can be pure strings.

**Comment by ian-r-rose** [comment]
@blink1073 I would prefer that, rather than requiring an alternative `ContentsManager` implementation (such as the Google Drive one) to have to know that a valid notebook with a list-of-strings is not a valid thing to hand to JupyterLab.

**Comment by ian-r-rose** [comment]
Fixed by #2752.
