### ISSUE TITLE
Support tab-completion in terminal

### ISSUE THREAD

**Issue by gnilrets** [jupyterlab/jupyterlab#2779]
The terminal would be much more functional if it supported tab-completion.

**Comment by gnilrets** [comment]
🤦‍♂️  - I was not in a bash terminal.....

**Comment by kleinash** [comment]
wait so when you open a new terminal you have to type bash to be in bash? odd.

**Comment by jasongrout** [comment]
The new terminal should use whatever your default shell is.

**Comment by kleinash** [comment]
I am on a remote machine running a docker that I thought was bash, but I could be wrong.

**Comment by stanislavprihoda** [comment]
_it might help someone..._ I just spent some time trying to change the terminal shell (when running on Docker) because jupyterlab kept opening terminal with /bin/sh although instruction _SHELL ["/bin/bash", "-c"]_ was defined in the Dockerfile and the user actually had /bin/bash as default in /etc/passwd. Explicitly setting the the SHELL environment variable (instruction _ENV SHELL=/bin/bash_) finally helped.
