### ISSUE TITLE
Inspector improvements

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2826]
- Add a context menu option to console and notebook to show the inspector
- Make shift+enter invoke both the tooltip and the inspector - need a new meta command that triggers both.

**Comment by jasongrout** [comment]
Also add a menu item to open the inspector (maybe instead of a context menu). Since there is only one inspector, I would suggest having a toggle option in the View menu, rather than a File | New option (since the file menu suggests you can create more than one inspector window).

**Comment by BoPeng** [comment]
Some observations/opinions:

1. It is really awkward to display the same information in both a tooltip and the inspector panel. I would suggest that Shift-Tab only sends the information to the inspector panel when the panel is open. It actually makes sense to me to remove the tooltip and always send the information to the inspector panel (and open the inspector panel  if needed).
2. The panel can be distracting when it updates by itself while I am typing, especially when it turns blank from time to time. I would suggest a "pause" button to switch to a mode that update only requested (e.g. Shift-Tab).
3. I cannot really keep the information I want there. For example, if I want the information on `print`, I would lose the information of `print` when I type `print(len` because the panel would turn to information on `len`. Again, a pause button can be useful.
4. I noticed that from [the initial demonstration video](https://www.youtube.com/watch?v=dv14RpA0Ht4&feature=youtu.be&app=desktop) some features such as navigation button, detail panel, yellow background, but I do not see them when I open an inspector panel for a Python 3 kernel. Am I missing something here?
5. I have proposed in another ticket (#4411) a mechanism for extensions and kernels to send information to a side panel. If we are to have a tooltip (Shift-Tab), an inspection panel, and an information side panel, it is much better to consolidate all these into a single panel, and put to a more prominent location (side panel). We can continue the discussion in #4411 if you are interested.

**Comment by ciyer** [comment]
Note on terminology: the inspector has been renamed to "Contextual Help" and is available under Help -> Contextual Help (Cmd-I on macOS).

This is basically the implementation suggested by @jasongrout, only it's in the "Help" menu, not "View". @ivanov I suggest marking this as resolved.

**Comment by ivanov** [comment]
Thanks for your help at the SciPy 2019 sprins, @ciyer !
