### ISSUE TITLE
License isn't yet copyright 2017

### ISSUE THREAD

**Issue by josephofiowa** [jupyterlab/jupyterlab#2919]
License reads copyright 2015-2016. I'll submit a PR with an updated license.

**Comment by blink1073** [comment]
Fixed in https://github.com/jupyterlab/jupyterlab/pull/2920, thanks!

**Comment by ivanov** [comment]
I just want to chime in that we moved to remove the end copyright date from files as we updated them in IPython starting back in 2012. The reason is that it keeps you from having to have a noop commit once per year that updates the whole repo's end dates. For more on this discussion, see  ipython/ipython#1644
