### ISSUE TITLE
Splash screen animation should have four satellites, not three

### ISSUE THREAD

**Issue by athornton** [jupyterlab/jupyterlab#2975]
It's Jupyter, right?  There are *four* Galilean moons of Jupiter.  One of Io, Callisto, Europa, and Ganymede will be sad until you add another orbiter.

**Comment by ian-r-rose** [comment]
:moon: :moon: :moon: :fire:

**Comment by athornton** [comment]
I can't read that comment as anything other than the beginning of Beethoven's Fifth Symphony.

**Comment by sccolbert** [comment]
We need a `/pedantry` flair, lol :)

**Comment by sccolbert** [comment]
Although it does call into question the jupyter logo.

**Comment by blink1073** [comment]
The three moons are Julia, Python, and R.

**Comment by athornton** [comment]
Well, then, the obvious solution is to make another language a first-class supported language.

I can't help but notice that we don't have any language representing the "te".

I mean, sure, "TeX" might not be a whole lot more work since MathJax is already part of the implementation....

....but may I humbly suggest "TECO" ?  It's Turing-complete, after all...

**Comment by ellisonbg** [comment]
You make a great point that brings up many important issues related to the brand identity of the project and the protection of our trademark. We have discussed this matter with the Steering Council's Intellectual Property Board and have the following statement to make:

We are observing broad confusion of Project Jupyter's name/logo with the planet Jupiter (spelling looks weird doesn't it - oh well, we had already taken the "jupyter" spelling and domain). This confusion is unfortunate and hurts the Jupyter brand. Especially since our logo is actually based on an ancient mythical creature known as Chompy:

![happy_compy](https://user-images.githubusercontent.com/27600/30286999-621e84ac-96d8-11e7-92ab-326e77297824.jpg)

We are sad that the planet copied our visual design, which we now have a trademark for. The issue you bring up is clear evidence of trademark infringement as it confuses users (wait, are those moons or eyes?). Our team of lawyers begin to pursue a suit against the planet, but it turns out that our U.S. based trademark doesn't apply in the larger solar system. We all know the patent/trademark system needs fixing, but this is ridiculous. Based on this outcome, we will have to live with the ongoing confusion :( ).

**Comment by bklaas** [comment]
Anecdata: I gave a demo last week of Jupyterlab to a bunch of programmers and data scientists here at Minnesota Population Center, and when launching lab and triggering the animation, I explained that the word Jupyter is a portmanteau of Julia Python and R and the three moons were representative of those languages. This received audible ooohs and aaahs. Data people love logically-connected iconography.

So, given the idea that you'd want to add another moon for astronomical accuracy, I'd also add that you don't want to mess up your portmanteau with the wrong first-level language. To the eye, Jupyter is a mashup of Ju[lia]pyt[hon]**e**[R], so you only have e available or else the whole thing is linguistic malarkey. Erlang? Probably not a reasonable choice, but hey it does start with E. Just don't do emacs. Vim ftw.

**Comment by athornton** [comment]
Nah, I'm sticking with Ju[lia]py[thon]te[co]r .  

Although embedding emacs in a cell sounds pretty charmingly insane too.

**Comment by jasongrout** [comment]
Clearly @athornton knows his astronomy :). Unfortunately, this issue will need to be taken up at the Jupyter governance or design repo, where the trademarks and logos are dealt with.

On the other hand, perhaps discussion can be moved to the IAU to reclassify one of the moons as a dwarf moon or moonoid, thus solving the problem by redefinition?
