### ISSUE TITLE
Default data frame view puts horizontal scroll at bottom of vertical scroll

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyterlab#2992]
i.e.
```python
import cufflinks as cf
cf.datagen.lines(50)
```

Horizontal scroll bar is not visible until scrolling all the way to the bottom

**Comment by blink1073** [comment]
This is because we are adding a [max-height](https://github.com/jupyterlab/jupyterlab/blob/2d32b6b4ecef076f6c2afda876be83c9b19daa38/packages/notebook/style/index.css#L67) and [overflow-y](https://github.com/jupyterlab/jupyterlab/blob/2d32b6b4ecef076f6c2afda876be83c9b19daa38/packages/outputarea/style/index.css#L22) to the output area itself but setting [overflow-x](https://github.com/jupyterlab/jupyterlab/blob/2d32b6b4ecef076f6c2afda876be83c9b19daa38/packages/outputarea/style/index.css#L51) on individual outputs.

**Comment by blink1073** [comment]
cc @ellisonbg

**Comment by ellisonbg** [comment]
I will look at this for the beta.

**Comment by ellisonbg** [comment]
We have stopped vertically scrolling output, so this problem has gone away (individual outputs will still scroll horiz).
