### ISSUE TITLE
UI feature requests

### ISSUE THREAD

**Issue by bokehuser85** [jupyterlab/jupyterlab#3013]
1. Code Minimap-sidebar with graphical code/cell map

2. Shortcut To Cell - make user selectable shortcuts in cell/code (i.e. FN+S+1 ==> function defs, FN+S+2 ==> DB import code) 

3. Cell/Code Folding - either an option in the cell that can fold/minimize it, or even a special comment like "#JLABFOLDSTART.....<code code code>   #JLABFOLDEND" so then it could still be copied into a .py file without affecting operation. 

4. Variable explorer - type, length/size etc would be great to be able to see

5. Code Breakpoints or auto pdb support i.e. on error run pdb to the line err-1

**Comment by blink1073** [comment]
Hi @bokehuser85, would you mind opening separate issues for the requests?  It is difficult to track issues with unrelated requests.

**Comment by saulshanabrook** [comment]
Thanks for these UI suggestions. I have addressed them item by item here and am closing this issue for now, since I think they are all covered by existing issues or would be good to implement outside of core. Feel free to re-open or open a new issue if there are issues that aren't covered.

> Code Minimap-sidebar with graphical code/cell map

#3738 Covers this now

> Shortcut To Cell - make user selectable shortcuts in cell/code (i.e. FN+S+1 ==> function defs, FN+S+2 ==> DB import code)

This sounds like a good thing to implement in [an extension](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html), since the behavior can be iterated on easier there then in core.

> Cell/Code Folding - either an option in the cell that can fold/minimize it, or even a special comment like "#JLABFOLDSTART..... #JLABFOLDEND" so then it could still be copied into a .py file without affecting operation.

You should be able to click on either of the blue buttons to the left of a cell to collapse it or it's output.
<img width="467" alt="screen shot 2018-04-26 at 1 38 53 pm" src="https://user-images.githubusercontent.com/1186124/39322250-3a3182aa-4957-11e8-9819-a5ef6a2b39e1.png">

> Variable explorer - type, length/size etc would be great to be able to see

Covered by #443 

> Code Breakpoints or auto pdb support i.e. on error run pdb to the line err-1

We have #3049 for adding a visual debugger, which I think would cover this.
