### ISSUE TITLE
IPywidget to run next cell

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#3017]
I'm trying to create a notebook with ipywidgers where I can have a ipywidget button to run the next cell or even the next N cells (like run the next 20 cells) 

How do I do this in Lab? 

In notebook this was easy to do: https://stackoverflow.com/questions/32714783/ipython-run-all-cells-below-from-a-widget

**Comment by blink1073** [comment]
@jasongrout might have input, but I think because we have deliberately isolated outputs in JupyterLab this would not be possible.

**Comment by jasongrout** [comment]
This was only possible in the classic notebook because it let "display" javascript that would interact directly with the page. However, this fundamentally broke the Jupyter model, since now your kernel code depended on a very specific frontend being available and exposing the specific javascript functions you wanted.

It's not possible in JupyterLab because things are much better isolated, so you can't directly run javascript like that from the kernel. Of course, this also doesn't work in any other kernel frontend either (like the console, interact, etc.) This has nothing to do with ipywidgets, it just has to do with the kernel code being agnostic about the frontend.

**Comment by jasongrout** [comment]
What are you trying to acheive? Likely there is a better way to approach the problem that doesn't require writing kernel code that depends on the frontend.

**Comment by AbdealiJK** [comment]
What I'm trying to do is make a notebook where a user can give a file name. Press a button to check the file and see the data in the file. 

Based on this file, the next ipywidget has a drop-down per column name. This input from drop-down is taken in the next cell and so on. 

Hence I need each ipywidget to take input from the last, and I want the user to not care about cells and so on and just interact with ipywidget

**Comment by jasongrout** [comment]
It sounds like you don't really even want a notebook, but more of a "wizard" or dashboard of sorts. We're going to be exploring this area after jlab 1.0.

**Comment by jasongrout** [comment]
Note that you can do your workflow above without executing cells. The easiest way is to take the cells you would have executed, turn them into functions, and then make the functions called from the buttons in the appropriate order.

It would be interesting to make a convenience function for wizards, which would take a sequence of functions to run, automatically put in buttons to go to the next step, etc. That sounds like an interesting project.

**Comment by jasongrout** [comment]
Opened https://github.com/jupyter-widgets/ipywidgets/issues/1725

**Comment by jasongrout** [comment]
I think we can close this and shift the discussion to https://github.com/jupyter-widgets/ipywidgets/issues/1725 as a stopgap, and we'll work on a richer dashboarding story after jlab 1.0.
