### ISSUE TITLE
Completer still active when modal dialog visible.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#304]
This one will likely be resolved with #5. 

I'm use to navigate around with shortcut, and the caught myself pressing tab a few time to try to close a dialog. The completer popped up after a few press. I guess that might be a focus issue. 

<img width="671" alt="screen shot 2016-07-11 at 22 01 54" src="https://cloud.githubusercontent.com/assets/335567/16753878/24ab197a-47b3-11e6-94e7-a0845f11b96a.png">

**Comment by jasongrout** [comment]
I see this too. Open a notebook, write something and execute it. Then close it without saving, and the modal dialog pops up. However, pressing tab eventually focuses back to the notebook and starts doing completions...

Perhaps the modal dialog should grab the tab key presses and make sure they only cycle in the dialog.

**Comment by afshin** [comment]
@blink1073 and I talked about this and we think it might actually make sense for an application wide signal that informs anybody who cares that there is a modal. Because modals are, by definition, application-wide in their scope, their presence should probably be broadcast so that other extensions can react accordingly.

**Comment by jasongrout** [comment]
On the other hand, maybe a modal should capture all keyboard and mouse interaction, so no one has to know it exists? I mean, I thought that was kind of the point of modal - to take over all user interaction.

**Comment by afshin** [comment]
But pre-existing things like the completion widget are the condition that led to this issue to begin with. You can imagine many widgets with "mini-modals" that only live in themselves but that ought to disappear when an "app-modal" appears.

**Comment by jasongrout** [comment]
Oh, you're talking about making the mini-modals disappear if an app modal appears, not about activating these mini-modals when an app modal is on the screen. Hmmm, I don't think it matters to me - the app modal should have a z-index above the mini-modals (this should be clearly documented what z-index values should be used), and should gray the screen so that the application state is essentially frozen.

I can see your point; I don't think it matters to me personally, though.

**Comment by afshin** [comment]
Yeah, `z-index` strategy is going to be important. Otherwise it'll become an arms race.

**Comment by jasongrout** [comment]
> Otherwise it'll become an arms race.

Up until you reach MAXINT, at which point nobody wins...

**Comment by Carreau** [comment]
> Up until you reach MAXINT, at which point nobody wins...

... well just [test for it](http://use.perl.org/use.perl.org/_Aristotle/journal/33448.html):

```
if (i > MAXINT){
   // get inspiration from PHP.
}
```

**Comment by jasongrout** [comment]
That's really funny...

**Comment by ellisonbg** [comment]
Anyone know if this bug is still there?

**Comment by blink1073** [comment]
@afshin has made subsequent changes to event handling in the completer, this appears to be fixed in master.
