### ISSUE TITLE
Watch mode to auto-compile extensions in active development

### ISSUE THREAD

**Issue by nross83** [jupyterlab/jupyterlab#3041]
First off, congratulations on JupyterLab. It's a great piece of software and I've loved working with it so far!

I'm trying to build an extension not too different from https://github.com/jupyterlab/jupyterlab-google-drive.  I'm having a hard time finding a good build process for rapid iteration on the extension and I've spend some time looking around for suggestions, but haven't found any.

I set up an npm script which does a babel compile whenever my source changes, but I find I have to do the following each time I want to verify a change:

1. Kill `jupyter lab` process
2. Run `jupyter lab build`
3. Start `jupyter lab` process (opens a new tab)

At this point, my extension changes are shown.  I'm wondering if there is a watch mode I can run or some way to symlink my directory like `npm link` for example to make this process more seamless.  Ideally without having to restart `jupyter lab` so I can keep working in my same tab.

I'm happy to contribute docs or help set up a watch process if there isn't anything currently in place on either front.  Thanks in advance.

**Comment by ian-r-rose** [comment]
Hi @nross83, we wrote the `npm addsibling` script for this purpose, which grafts your extension directory into the JupyterLab build tree so that it can be symlinked to the appropriate packages. This is what I use for the `@jupyterlab/google-drive` extension.

I am not sure if it would work for your extension if it is not in Typescript, but if not we could probably find a workaround.

A description of `addsibling` is [here](https://github.com/jupyterlab/jupyterlab/blob/master/docs/extensions_dev.md#extension-authoring)

**Comment by blink1073** [comment]
Hi @nross83, unfortunately we can't use `npm link` for this because it prevents us from de-duping packages because they no longer share parent directories.  @bollwyvl and I had previously talked about a way to implement `watch` that looks for changes in your source folder and then copies the folder to `<app_dir>/node_modules`, pokes a file that webpack is watching, which triggers a rebuild of the one package.  Then you could refresh the page and pick up the changes.

**Comment by blink1073** [comment]
Background on the `npm link` and dedupe problem here: https://github.com/npm/npm/issues/7742.

**Comment by blink1073** [comment]
Found a solution.  We can use the known linked package config to add a `jupyter lab watch` mode that uses the following `WebPack` config:

```javascript
  watch: true,
  watchOptions: {
    ignored: /node_modules/
  },
  resolve: {
    alias: {
      "@jupyterlab/foo-extension": "/path/to/foo"
      "bar-labextension": "/path/to/bar"
    }
  }
```

This allows us to install the linked extension (and deduplicate its dependencies), while loading it from its source directory and automatically rebuilding when a file in that directory changes.  Doing the above results in an auto-rebuild that takes <1s versus the current manual rebuild that takes 12s on my machine.

To make this work, we need to add the linked packages data and a `watch` script to `package.app.json`.  We also add the `jupyter lab watch` command that calls `npm run watch` asynchronously and uses `app-dir/staging/build` for assets instead of `app-dir/static`.

We can also support `jupyter lab watch --dev-mode` if we use the core extensions as the linked extensions in `jupyterlab/package.json` and asynchronously run `npm run watch` from that directory while still serving from `jupyterlab/build`.

**Comment by ian-r-rose** [comment]
That's exciting @blink1073 . Does your second point mean that we can entirely remove `addsibling` and `removesibling`?

**Comment by blink1073** [comment]
I don't think so, because you wouldn't be able to `npm install` or `npm run build` in your other directory because the Jlab JS packages it wants to use aren't yet published.

**Comment by ian-r-rose** [comment]
Ah, right. So that would mostly just cut down on rebuilding time while in watch mode?

**Comment by blink1073** [comment]
For dev mode, yes.   If you were working on one package, you could run `npm run watch` in that folder while `jupyter lab watch --dev-mode` is running in another terminal and have a really tight feedback loop.

**Comment by nross83** [comment]
@blink1073 This sounds like a great enhancement that would make my life much easier :)
