### ISSUE TITLE
Might it be possible to inform typescript of the input possibilities for app.commands.execute

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3120]
This might not actually be possible. But when using app.commands.execute the args object is an any type. Might it be possible to inform typescript of the input possibilities for these args? These args are specific to the function, and I think those commands are essentially defined at runtime. So what I'm asking might not be directly possible.

Another idea is when there is extra logic that only exists within an added command, might that command as a rule also be made into an exportable function first? That way if one wants to do exactly the same things as running app.commands.execute, but still have the benefits of typescript, they can go and import that respective function directly.

The main reason for asking for this is that I have found the code base quite nice to traverse and learn about using completion hints and ctrl click within Visual Studio code. However the IDE didn't know where to go or what to tell me when it came to using app.commands.execute, which makes sense. It made me want to use a different method and avoid app.commands.execute when possible while I am learning.

**Comment by sccolbert** [comment]
The command registry is part of Phosphor, and the type of `args` is actually `ReadonlyJSONObject`:
https://github.com/phosphorjs/phosphor/blob/master/packages/commands/src/index.ts#L343

That was done on purpose so that a command and its args can be serialized to JSON, which will enable the user (at some point in the future) to customize key bindings for commands which require args (since those settings must be saved to disk).

As for your second question, having a generic interface like this for commands allows the extension author to expose *less* public API, which can be a good thing in a lot of cases as it allows them to change their implementation details freely, without worrying about breaking existing code. The choice of when to use commands vs public functions, and whether to expose the command implementation as a function is a tradeoff. It's highly unlikely that we will expose every command implementation as a public function.

**Comment by SimonBiggs** [comment]
Makes sense :).

**Comment by SimonBiggs** [comment]
In hindsight you probably get sick of these sorts of questions regarding core implementation choices. Choices that have pros and cons but were chosen with those in mind. Sorry about that.

Thank you for the great phosphor framework :). It's wonderful to be able to build on-top of what you've made.

**Comment by sccolbert** [comment]
No worries! At least now we have the reason documented :)
