### ISSUE TITLE
Allow for system setting defaults

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#3179]
Add an environment variable option pointing to a system-wide settings folder that is merged with the application settings.

This allows system administrators to provide defaults for their users.

cf https://groups.google.com/forum/#!topic/jupyter/yLG_4PT22fQ

**Comment by afshin** [comment]
Would having a settings override object in the page config solve this problem? I think it may: any specific plugin's settings that you want to override could be included in the page config and the setting registry could account for this. I propose this route because it would be easier to set up as an administrator who wants to modify the settings of several extensions.

**Comment by blink1073** [comment]
The way we handle extensions is that it can be installed either in `sys-prefix` or in the `JUPYTERLAB_DIR` location, where the `JUPYTERLAB_DIR` location shadows `sys-prefix`.  This is the same way `pip` handles `--user` installed packages.  
Whether we use a new directory or `page_config` for this, I think it should be a separate file or files that can be merged with what the user wants.

**Comment by afshin** [comment]
After considering this a bit more, I think `page_config` is actually not the best idea because it puts the onus of establishing the system defaults on the client. Since we want to support multiple clients, it really ought to be handled purely in the settings handler in the API to always return a single source of truth about what the system defaults are.

**Comment by ellisonbg** [comment]
Should we target this to beta still, or do you think it will be move 1.0?

**Comment by jasongrout** [comment]
Fixed by the PR above by @afshin - now we are just waiting for the jupyterlab_launcher dependency to get bumped.
