### ISSUE TITLE
Cannot open files whose names contain special characters

### ISSUE THREAD

**Issue by guolingbing** [jupyterlab/jupyterlab#3351]
Hi, I finded a weird bug.
If a filename contains special characters like ':' , then I cannot open this file in JupyterLab.
However, it works well in classic Notebook.
For example, '2017-12-07 11:27:01.725726.txt'.

**Comment by ian-r-rose** [comment]
Hi @guolingbing , this is a result of the way we dispatch file operations between various different file browsers that might be installed in JupyterLab (Google Drive, GitHub, Default, etc). The first part of the path is `:`, and determines the drive. We could solve this in a couple of different ways:

1. Advise users not to use "`:`" in their file names.
2. Currently, the default browser has no name, so paths that are not prefixed are dispatched to that drive.  This runs afoul of the case that @guolingbing has described. We could give the default file browser with a name (e.g. `Default`) so that the first portion of the path is *always* the drive name, and thus unambiguous.
