### ISSUE TITLE
Audit multi-cell selection

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3373]
@ian-r-rose @jasongrout 

In a design review today we discovered that the multi-cell selection behaves differently than the classic notebook. We should audit this behavior (mouse and keyboard) for the beta.

**Comment by jasongrout** [comment]
The particular issue was that if you click on a cell, then shift click on another cell a few cells away to extend the selection, you can then click on one of the selected cells (without shift) and the selected cells are not unselected.

**Comment by jasongrout** [comment]
Here are some interesting things I'm finding with our notebook cell selection model:

1. `isSelected` is really `isSelectedOrActive`, in that the we can select/deselect the active cell, and the selection state is still triggered, but `isSelected` still returns true no matter what (so the selection state doesn't appear to change).
2. We don't have a good model for contiguous selections. I'm working on that. It's a bit hard since we don't assume any model for selection in the underlying data structure, so I have to verify that the current selection is contiguous before operating on it.

**Comment by jasongrout** [comment]
Fixed by #3414.
