### ISSUE TITLE
console shortcuts: esc entering 'command mode'

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#3484]
Right now console supports the same shortcuts for interrupting and restarting the kernel as the notebook, by default `i i` and `0 0`. However unlike the notebook, `ESC` does not remove focus from the input (in other words console has no command mode), and therefore these shortcuts are impossible to invoke without using the mouse or command palette.

At the same time, unlike `ipython`, `ctrl-C` is not caught by the console as interrupt.

**Comment by narfanar** [comment]
Worse, ESC goes to one of the open notebooks (not sure which, probably the last used), so it's not just that it does nothing, it's doubly disruptive.

**Comment by jasongrout** [comment]
I'm not seeing the `esc` go to an open notebook on master. However, I am seeing that `esc` does not enter 'command mode` in the console.

Looking into the code more, it looks like the focus handling is pretty hardcoded. I think it would make sense to add a `mode` attribute to the console widget, similar to the notebook. Then use this `mode` attribute to do the switching instead of hardcoding the editor focus. Then implement some commands to do the switching and tie them to keyboard shortcuts, like in the notebook.

**Comment by jasongrout** [comment]
Minimally, I think we should solve the explicit issue here of `esc` unfocusing the editor for 1.0. Revamping how focus is done could wait until after 1.0 (though it may make sense to just revamp it anyway)

**Comment by narfanar** [comment]
@jasongrout , Just confirmed that part is an issue from an extension.

https://github.com/ryantam626/jupyterlab_sublime/
