### ISSUE TITLE
Main Area Widget and Document Widget Refactor

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#3495]
Cleanup of the logic around creating main area widgets and documents.

The goals are:
- Provide a simplified top level widget for use across JupyterLab
- Defer loading from disk until after the app is restored
- Prepare for the Phosphor data store [API](https://github.com/phosphorjs/phosphor/blob/4b8f3f456d509ae31a6e7e901b7ba39282a3488e/packages/datastore/src/datastore.ts#L97) by not using the document model until is fully populated

Notes:
- Main Area widget work is happening in #3499.  
  -- Will take an optional `Toolbar` and proxy the content widget's title attributes to the main widget as well as handle re-focusing the content as appropriate based on toolbar interaction.
  -- Will handle asynchronously populated content using `isPopulated` and `populated`.  If an optional `populated` promise is given, it will show a spinner until resolved.  If it fails, it will show an error message in the widget.

- Contexts will have a `model` that is read-only and `null` until it is populated, and the document manager will have more control over the lifecycle of the model and context.

- The DocManager will optimistically create a document widget, and wait for a `when` promise that is `app.restored` before fetching any contents.
  -- Then, it try and fetch its contents model only - if that fails, show something to the user in the top level widget.
  -- If we get the contents model, initialize the model.  If that fails, show something to the user in the top level widget

-  The context gets a promise to the `contentsModel` and a promise to the `model`.  
 -- The context waits for those, then, and declares itself populated
 -- The context then initializes the session
  -- The only API change is that the `context.model` can be null when it is not populated

Other notes:
- There is no more need for `NotebookPanel` -> some of that logic is no longer needed and the rest will move to the widget factory.
- Widget extenders (like ipywidgets) will get called with the new top level document widget
- Document widgets will be a `MainAreaWidget` with additional handling of "dirty" state and path tracking that updates the title.
- The standalone notebook example will use the `Notebook` widget, the default `Notebook` Toolbar, and a new function `NotebookModel.fromFile(manager: ContentsManager, path: string): Promise<NotebookModel>`.
- Initial save should happen after the session is initialized - and then create a checkpoint

Major changes to Document registry:

```typescript
  /**
   * The options used to initialize a widget factory.
   */
  export
  interface IWidgetFactoryOptions {
    ...
    /**
     * The callback for a new document widget created using the factory.
     * The default is a no-op.
     */
    readonly callback?: (widget: IDocumentWidget) => void;
   ...
  }

  /**
   * A widget for a document.
   */
  export
  interface IDocumentWidget<T extends Widget = Widget, U extends IModel = IModel> extends Widget {
    /**
     * The content widget for the document.
     */
    readonly content: T;

    /**
     * The toolbar for the document.
     */
    readonly toolbar: Toolbar;

    /**
     * A promise that resolves when the document is initially populated.
     */
    readonly populated: Promise<void>;

    /**
     * Whether the document is populated.
     */
    readonly isPopulated: boolean;

    /**
     * The context for the document.
     */
    readonly context: IContext<U>;
  }

  /**
   * The interface for a widget factory.
   */
  export
  interface IWidgetFactory<T extends Widget = Widget, U extends IModel = IModel> extends IDisposable, IWidgetFactoryOptions {
    /**
     * Create a new content widget.
     *
     * #### Notes
     * This happens first in the widget factory lifecycle.
     */
    create(context: IContext<U>): T;

    /**
     * Initialze a widget created by this factory and its toolbar.
     *
     * #### Notes
     * This happens second in the widget factory lifecycle.
     * The returned promise is used to determine when fully
     * populated (in addition to `context.populated`).
     */
    populate(widget: T, context: IContext<U>, toolbar: Toolbar): Promise<void>;

    /**
     * Finalize a new document widget created using the factory.
     *
     * #### Notes
     * This happens last in the widget factory lifecycle.
     * This is typically where the widget factory would add the top level
     * document widget to an instance tracker.
     */
    finalize(widget: IDocumentWidget<T, U>): void;
  }

  /**
   * An interface for a widget extension.
   */
  export
  interface IWidgetExtension<T extends Widget = Widget, U extends IModel = IModel> {
    /**
     * Create a new extension for a given widget.
     */
    createNew(widget: IDocumentWidget<T, U>): IDisposable;
  }
````

**Comment by jasongrout** [comment]
(FYI, the description was updated 16 Feb 2018 as a result of a design discussion.)

**Comment by blink1073** [comment]
More notes from discussion today:

- The context should self-populate and create its own model:
 -- Pass in a promise for when it should load (`app.restored`) and whether it is a new file
 -- Continue to create the model using the model factory and interact with the model using `to/fromJSON/string()`

When moving to the data store, some things to keep in mind:
- The `ModelDBFactory` will have to be mapped to a `DataStoreFactory`
- The model should take fully qualified `dataStore` in its constructor, as well as optional JSON/string data - which means we need an API as to whether a `dataStore` has been populated before

**Comment by afshin** [comment]
Fixes https://github.com/jupyterlab/jupyterlab/issues/3572

**Comment by jasongrout** [comment]
Further conversation between @blink1073 and I today resulted in this set of notes:

### Document Manager:

Plugins instantiate widget factories, and pass into the widget factory a callback that is called with any document widget created. This callback can, for example, add the document widget to the plugin's instance tracker.

Call the WidgetFactory methods in order:

1. content = WidgetFactory.create(): returns a Widget (such as a notebook or file editor widget). This will be the content area of the panel.
2. Create a context object and toolbar widget
3. documentReadyPromise = Call WidgetFactory.initialize(context, toolbar, content): returns a promise for when it is okay to show the document widget in the dock area (i.e., to get rid of the spinner).
4. Create a document widget with the context, toolbar, content, and documentReadyPromise
5. Call the WidgetFactory document-widget-created callback with the document widget.

### Context

Context creation takes a `when` promise for the save/revert action. This when promise typically is the layout restore promise. The constructor then:

1. create an empty model
2. when.then({
    start session
    return (save or fromStore) promise
}).then(resolve context ready promise)


We delay save/fromStore until after layout restore because we don't want to schedule any heavy work that might delay the layout restore from resolving (which pulls down the application spinner).

### Model state in server

Eventually, move the model state to the server, and interact directly with the disk on the server, without pulling file contents over to the client and then pushing back to the server model store.

**Comment by jasongrout** [comment]
Related to this is #4087, which was released in 0.32.

**Comment by jasongrout** [comment]
Also, it would be *great* if there were a way for document model factories to say: *don't* give me the content - instead, all I need is a URL. For example, a viewer for large videos using an html5 player would want a url, rather than the entire content of the video.

Perhaps this is best implemented by a new file type in the server - instead of type `text` or `base64`, it's type `url` or type `''` or type `empty`, which would mean content always returns an empty string, or perhaps that content just returns the path to the file as a resolvable URL in the `url` case.

**Comment by jasongrout** [comment]
New thoughts, while working in the middle of #4453:

*Insisting* on us creating the document widget is perhaps too much. Perhaps some widget factory actually wants to create their own widget with some extra data or methods? For example, suppose a notebook widget wants to add some extra methods to the toolbar to expose special toolbar items?

So how about this instead, which is closer to the current strategy:

### Document Manager:

Plugins instantiate widget factories, and pass into the widget factory a callback that is called with any document widget created. This callback can, for example, add the document widget to the plugin's instance tracker.

Call the WidgetFactory methods in order:

1. Create a context widget
2. Pass the context to the widget factory, which returns an IDocumentWidget (which has a toolbar attribute, and a content attribute
3. Display the IDocumentWidget

We have a default implementation of IDocument people can use. The IDocumentWidget has:

* toolbar widget attribute: IToolbar
* content widget attribute: Widget
* some notion of 'loaded' as a promise and isLoaded attribute, for example. This is so that things that depend on the content being on the page can trigger on the promise resolution.
* context

The basic DocumentWidget shows a spinner when the document hasn't loaded, and swaps the spinner out for content and toolbar when it does load. The spinner also covers the toolbar since (a) the toolbar isn't active while content is being loaded, and (b) the toolbar state may depend on the content (like the current cell type in the notebook).

### Context

Context creation takes a `when` promise for the save/revert action. This when promise typically is the layout restore promise. The constructor then:

1. create an empty model
2. when.then({
    start session
    return (save or fromStore) promise
}).then(resolve context ready promise)


We delay save/fromStore until after layout restore because we don't want to schedule any heavy work that might delay the layout restore from resolving (which pulls down the application spinner).

**Comment by blink1073** [comment]
Sounds good to me.

**Comment by jasongrout** [comment]
We'll take care of the Context section of https://github.com/jupyterlab/jupyterlab/issues/3495#issuecomment-386505613 on a different PR than #4453, since that PR is getting so huge.

**Comment by jasongrout** [comment]
Right now, it looks like the context save/revert happens when the context.initialize method is called, and we wait to call that until after a ready promise. So I *think* we have the same effect right now. It might be still good to (a) check that we actually are delaying the save/revert until after the application spinner is removed, and (b) think if there is a simpler way to do things (like in the comment above).

I'll make a new issue for this part specifically, and close this as resolved.
