### ISSUE TITLE
Preventing context menu in jupyter-widget output

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#3521]
I was playing around with pythreejs today in jupyterlab (it creates a WebGL context as its widget view), and I noticed that when I pan the scene by dragging with the right-click mouse button, I always get the context menu when I release the button.

The drag handler in question registers for several events, among others doing this:

```js
element.addEventListener( 'contextmenu', onContextMenu, false );
element.addEventListener( 'mousedown', onMouseDown, false );

function onContextMenu( event ) {
  event.preventDefault();
}
function onMouseDown( event ) {
  event.preventDefault();
  document.addEventListener( 'mouseup', onMouseUp, false );
}

function onMouseUp( event ) {
  // preventDefault and/or stopPropagation seems to have no effect here
  document.removeEventListener( 'mouseup', onMouseUp, false );
}
```

What is the right way to prevent the context menu from showing in this case? I'd prefer it to show up for other cases (e.g. when these controls are not enabled).

**Comment by vidartf** [comment]
(note, in the example code `element` is the `HTMLCanvas` element of the WebGL context)

**Comment by blink1073** [comment]
I think these [selectors](https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/src/index.ts#L546) need to be scoped to `:focus` as we do in the [shortcuts](https://github.com/jupyterlab/jupyterlab/blob/master/packages/shortcuts-extension/schema/plugin.json#L210).

**Comment by OKaluza** [comment]
This is not fixed, or the fix has been regressed, using Version 0.35.4

**Comment by zerline** [comment]
I have the same problem on my jupyterlab 0.35.6

**Comment by vidartf** [comment]
@OKaluza / @zerline Would you mind sharing steps to reproduce your issue? Are you using pythreejs, or something else? Which events are you listening to / preventing?

**Comment by OKaluza** [comment]
@vidartf I'm using my own html and WebGL components, but in general anywhere I click in the output cell has the jupyterlab context menu, even controls that have focus.  
You can test with the example provided in the fix: https://github.com/jupyterlab/jupyterlab/pull/3527
```
input("""foo
bar""")
```
Execute above and try right clicking on the produced input field, it should show the default browser context menu. I can put together an example using a WebGL component if that helps.  

I would say there's a lot to be said for not having the custom context menu appear for output cells at all. For example: if an image is produced you can't use the browser features for saving or copying the image (well you can still get it with shift, but not everyone will be aware of that).

I have since worked around it where it matters in my code by calling stopPropogation() in the contextmenu event for my components.

**Comment by jasongrout** [comment]
> well you can still get it with shift, but not everyone will be aware of that

We've added an item to the context menu telling people about the shift-click to get to the native menu.

**Comment by zerline** [comment]
@jasongrout @vidartf thank you for your help. I probably should check even more, but until now, I still _can't see_ my right-click menus (from francy-widget) on jupyterlab -- although I see them very well on the notebook.

1. with a right-click, I see the jupyterlab context menu everywhere on the windows ; even on an element which has focus and specialized cursor

1. with a shift-right-click, I see the underlying browser context menu instead of the jupyterlab context menu

**Comment by vidartf** [comment]
The last PR I can find that touched that code is https://github.com/jupyterlab/jupyterlab/pull/3554. @blink1073  / @ellisonbg / @jasongrout  you were the most involved that, and I'm struggling to follow the rather long discussions and big code changes. Was this an intended reversion, or a regression?

**Comment by blink1073** [comment]
Yes, that PR switches us to using the capture phase for the context menu, which simplified our selector logic across the board.  We added instructions for extension authors [here](https://github.com/jupyterlab/jupyterlab/pull/3554/files#diff-7cc0da241c2f5e77289291f2c7c16516).   Current docs link: https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/extension_dev.rst#context-menus
