### ISSUE TITLE
Right-clicking on a cell input shows system menu when the cell is focused.

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3556]
To reproduce (for me on Firefox 57 on OS X, but not Chrome):

1. Go into command mode
2. right-click on a cell input

effects:
1. The cell is changed to edit mode
2. the *system* context menu is shown, rather than the JLab notebook context menu.

Right-clicking on the cell input after the cell is already in edit mode correctly shows the JLab context menu.

Likely we're missing a `preventDefault` when switching the cell to edit mode? Or perhaps the Firefox 57 workaround in the code is somehow not finding the cell we're clicking on?

**Comment by jasongrout** [comment]
This is on current master: a47bb82a6cdd0ca4bb080b0d95850312a20d6f6e

**Comment by ian-r-rose** [comment]
Is this with Firefox?

**Comment by jasongrout** [comment]
Yes, on OS X. I just checked Chrome, and don't see the issue there.

**Comment by ian-r-rose** [comment]
I think that the root cause of a lot of the focus difficulties that we have seen (for instance, #3531) is due to the fact that CodeMirror explicitly handles right-clicks differently for Chrome and Firefox.

My suspicion is that the most reliable way to deal with this (probably post-beta) is to make sure that *all* of the focusing logic on our end relies on the left-click only.

**Comment by jasongrout** [comment]
I'm okay with this being addressed post-beta. I'll see if I can look into it Monday, but we shouldn't hold up the beta for it, I think.
