### ISSUE TITLE
Undock sidebar tabs

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3707]
It might be useful to be able to un-dock sidebar tabs, or at least to be able to have side-panels on each side and to be able to drag tabs between them.

Currently having one sidebar tab open hides the others whereas it might be nice to be able to keep seeing e.g. your FileBrowser while using the Git tab.

**Comment by sccolbert** [comment]
There is currently a right bar, it's just automatically hidden if there's nothing in it. Since we don't put anything there, you never see it. The RBrain folks have put some stuff in it:

https://r-brain.io/en/

We've talked loosely about the ability to drag/drop sidebar tabs before. I think it could be a good idea with the proper UX treatment.

**Comment by dhirschfeld** [comment]
Some of the r-brain stuff does look pretty nice!
