### ISSUE TITLE
Tab completion not working on dataframes?

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#3735]
Oddly, I'm seeing that on Pandas dataframes, say something simple like:

```python
import pandas as pd
df = pd.DataFrame({'a':[1,2,3]})
df
```

Tab completion doesn't show any menu of attributes, though if I type enough letters to reach non-ambiguous state, then Tab will complete typing. This means the problem seems to be with the display of a menu when there's more than one option.

Now, the problem is somehow specific to some data structures (at least pandas DFs), b/c in the same session, a simple string completes fine:

![image](https://user-images.githubusercontent.com/57394/35467573-fe987c90-02c4-11e8-9e80-3a1a37e0d748.png)

This may give someone ideas, though I'm not sure what's going on here (maybe the types of certain attributes are confusing the menu generating JS code?).  FWIW, classic on the same notebook completes fine, though that completer doesn't show types.

This is on JLab 0.31.1. running on macOS/Chrome.

**Comment by verginer** [comment]
Could this be related to  issue #3678 ?

**Comment by ibdafna** [comment]
Also experiencing this. 

jupyter lab --version
0.31.1

**Comment by ibdafna** [comment]
I did some testing to see where this is coming from, and whilst autocomplete does work on the normal Notebook interface - it duplicates autocomplete results. 

The duplicate results issue is coming from IPython and will be fixed in version 6.3. This issue appears to be the culprit of autocomplete not working for pandas in Jupyter Lab. For now this fix worked for me:

pip install ipykernel==4.6.1

**Comment by afshin** [comment]
@fperez Is this issue a duplicate of https://github.com/jupyterlab/jupyterlab/issues/3678

I think it may be, in which case, it is fixed in https://github.com/jupyterlab/jupyterlab/pull/3688

Here is a screenshot of the current master:

<img width="462" alt="screen shot 2018-01-28 at 12 39 50" src="https://user-images.githubusercontent.com/159529/35482131-9be1cefc-0428-11e8-94ca-ea6de767f8a6.png">

You can see in the screenshot that some of the experimental type annotations are unavailable but we weren't handling `null`s properly.

**Comment by fperez** [comment]
Sorry @afshin, failed to search enough :) Yes, looks like a dupe, closing here as such. Thx!
