### ISSUE TITLE
"minimap" of notebook structure for navigation

### ISSUE THREAD

**Issue by gfrogat** [jupyterlab/jupyterlab#3738]
it would be nice to have some sort of a "minimap" preview of the notebook structure, that can be used to navigate large notebooks or large cells.

this idea was already mentioned once in #3013 but it seems it wasn't discussed any further.

I think this feature could be very helpful for users, but it's still not completely obvious to me what to show when in the "minimap".
Here are some options that came to my mind:

### cell preview
preview the cells of the notebook, where the cells in the preview are scaled to match the size in the real notebook (so no not just showing a "pearl chain" where all cells are the same size).
In this view one could color-code the cells based on their type (e.g. code, markdown, ...) and cell tags (mentioned in issue #2277). It would be even more interesting to automatically tag and highlight cells with certain contents such as function definitions or module imports.

### code preview for very big cells
for very large cells one could switch to a standard code minimap that simply displays the structure of the code in this cell.

### code preview of all code cells
display a code minimap that contains the code of all notebook cells where different cell regions are visually hinted

### thumbnail preview of all figures / graphics
a slideshow of all graphics in the notebook that can be used for navigating to the respective part of the notebook

### table of contents preview
this functionality is related to #723. One could even use the "section information" to further structure the the other minimap types mentioned above.

I would be willing to work on this and would like to get some thoughts on the idea/concept.
I'll add some sketches later this week.

**Comment by jasongrout** [comment]
(Also, just to set expectations, a performant minimap of code can be incredibly complicated to implement)

**Comment by gfrogat** [comment]
yes definitely, I'm aware of that 🙂 

I would have started with the normal cell minimap anyway. I just wrote down all my ideas so there's some basis for discussion.

**Comment by bollwyvl** [comment]
Hey folks, this is wonderful to see it come up again. I've wanted for as long as I can remember. 

Back In The Day, one of my first notebook extensions was [ipython-notebook-navigator](ipython-notebook-navigator)... 
![](https://github.com/bollwyvl/ipython-notebook-navigator/raw/master/screenshot.png)

wow, those install instructions are brutal! `custom.js` hacking! Feel free to grab anything you find there, and please don't judge 😊!

Since then, it has also show up here:
- https://github.com/jupyter/notebook/issues/594

...and the techniques ended up in some other extensions I worked on, especially use of [html2canvas](https://github.com/niklasvh/html2canvas). It's definitely worth checking out what that project has been up to! It's probably not the best ultimate approach, but it will get you to an 80% solution really quickly.

Some of the tools at our disposal now:
- multi-cell select
- robust drag-drop
- (more) robust mimetype handling

Anyhow, I'm really looking forward to having fresh eyes on the problem! Loop me in if you start hacking in anger!

**Comment by omarkb93** [comment]
Visual Studio has a pretty nice minimap option where the minimap replaces the vertical scroll bar.

![image](https://user-images.githubusercontent.com/4393192/35546990-c8dd7e36-0533-11e8-81b0-2f20676ca37b.png)

**Comment by hadim** [comment]
FYI, I am also posting a screenshot of the SublimeText 3 minimap (very similar to Visual Studio).

![capture 2](https://user-images.githubusercontent.com/528003/36357734-53171e12-14d0-11e8-8204-30fcd8317a31.PNG)

**Comment by BoPeng** [comment]
I would also like to some feature like this. I frequently need to scroll to another part of a (long) notebook for information and scroll back to continue editing. Locating the cell of interest and going back to the cell I am working on can be difficult for long documents so having some way to go back to visited cells can be a real time saver.

The problem could be solved in a number of ways (minimap, split view, TOC, mark location etc) but for my particular problem, the simplest solution could be a shortcut to "return to edit". That is to say, JLab can remember the cell that was last edited, even the cursor position. Then after some navigation, a shortcut can be used to return to the cell and allow continued editing. Does this sound like a valid feature to anyone?

**Comment by ian-r-rose** [comment]
@BoPeng You may be interested in [this](https://github.com/ian-r-rose/jupyterlab-toc) extension, which provides a ToC for notebooks and markdown files.

**Comment by BoPeng** [comment]
I am aware of the jupyterlab-toc extension (Thank you very much for the work) but I have long code cells with few subsections so a TOC only helps partially. Instead of a "return-to-edit" shortcut I proposed, it could be helpful to have a TOC that marks last visted/edited cells in some way, e.g.

```
section 1
section 2
  ==> cell that I am editing
```
so that I can go back to the cell after scrolling up and down.

**Comment by ian-r-rose** [comment]
Note that in the most recent version of `jupyterlab-toc` (just published!) clicking on a header *within* a rendered cell now scrolls that header into view, rather than just the cell. A "return to last edited" feature is being discussed, but not yet implemented.

**Comment by BoPeng** [comment]
That sounds cool, I will check out the most recent version of `jupyterlab-toc`. I actually believe that `jupyterlab-toc` should be a standard extension of jupyterlab because the first thing I was looking at when I saw jupyterlab's side panel was a TOC panel and I was disappointed when I did not see one.

I will search for discussions on "return to last edited" and might propose a PR if there is enough interest.

**Comment by jasongrout** [comment]
Note that the just-released toc extension now supports lots of other cool things.

**Comment by orena1** [comment]
Wondering if there is an update on this ticket?

**Comment by macsunmood** [comment]
Any updates ?
