### ISSUE TITLE
Persistence for collapsed input/output cells

### ISSUE THREAD

**Issue by leonsp** [jupyterlab/jupyterlab#3799]
The UI for collapsing input/output cells from #714 is great, but it doesn't persist in saved notebooks.

We are adopting JupyterLab to run online courses and deliver hands-on labs. With Jupyter, we could have a hidden answer key at the end of a lab notebook using `<style>` tags, but this is not possible in JupyterLab. JupyterLab's native UI would work, but it's not persisted so we can't deliver labs with hidden cells to our students.

#2740 mentions that there is support for marking cells as hidden in the notebook file format. However, it sounds like this is not exposed in JupyterLab at all.

It would be great if JupyterLab persisted cell visibility to saved notebooks.

**Comment by sputnik62** [comment]
First of all, thank you all for consideration. We are really stocked about JupyterLab and we are going all in on it.

**Comment by ellisonbg** [comment]
It shouldn't be too difficult to implement. Here is a rough sketch of our plan:

* If the official collapsed metadata exists in the notebook when it is loaded, rendering the notebook with that state.
* While a user is editing the notebook and changing the collapsed state, don't auto-update the metadata in the file. This is because when there are multiple users editing the notebook at the same time, they may want to have different collapsed states.
* Add a new command and menu item to persist the current collapsed state of the UI to the actual file.

**Comment by vidartf** [comment]
> This is because when there are multiple users editing the notebook at the same time, they may want to have different collapsed states.

What would different views of the notebook see (i.e. different widgets in the same browser tab)? I'm not entirely sure what I would expect as a user.

**Comment by ellisonbg** [comment]
That is a great question and I don't think we have an answer yet. We have the option to do either by putting the state on the view (not shared) or model (shared) respectively. Thoughts?

**Comment by vidartf** [comment]
A similar case could be code folding (collapsing a region of code, e.g. a function definition). Here I would expect folding in one view to *not* affect another view (which is the behavior I see in several IDEs). That said, there are some difference between the two cases, so I'm not 100% on this.

**Comment by saulshanabrook** [comment]
I am thinking of taking a go at this in the way @ellisonbg described above.

**Comment by ellisonbg** [comment]
Thanks Saul!

**Comment by saulshanabrook** [comment]
Closing this since https://github.com/jupyterlab/jupyterlab/pull/3981 has been merged in. It adds support for persisting the collapsed state of input and output cells and the scrolling state of output cells. It adds a new command `Save Notebook with View State` that saves the current notebook with the current collapsed/scrolling state. Also, if you open a notebook with collapsed/scrolling state specified in the metadata, this will be reflected in the initial view. The keybinding of `Ctrl Shift S` is also now bound to this action.
