### ISSUE TITLE
Add "Copy Path" to context menu

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3845]
As it says in the title. It's very convenient to be able to get the path to a file (dataset) so you can easily paste it into your notebook/console to then import it with e.g. pandas.

**Comment by ian-r-rose** [comment]
I like this idea! Marking as a "Good First Issue"

**Comment by jasongrout** [comment]
We may only be able to get it relative to the notebook starting directory (i.e., our "home" directory in lab). Is that sufficient?

**Comment by dhirschfeld** [comment]
Relative to home would be fine I think

**Comment by timkpaine** [comment]
should be able to derive relative as well if something is open, since that thing will have its path in its context. e.g.. a notebook at /my/test/notebook.ipynb and a dataset at /my/test2/data.csv, you can grab the notebooks's context which should tell you how many levels from "home" (so ../../) and then append the thing you're clicking (so ../../my/test2/data.csv).
