### ISSUE TITLE
Coreutils `isLocal` is too broad

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#3862]
Found with @SylvainCorlay.

If there is a notebook server deployed with the same host domain as some other resources, the `isLocal` check can pass incorrectly. If you then refer to those resources in a notebook, JupyterLab tries to patch up the url to point to the contents API when it shouldn't.

cf. https://github.com/jupyterlab/jupyterlab/blob/master/packages/coreutils/src/url.ts#L102

I think it would be more correct to have the `isLocal` check just be
```typescript
return protocol !== 'data:' &&  host === '';
```
rather than
```typescript
return protocol !== 'data:' && host === location.host ||  host === '';
```

**Comment by timkpaine** [comment]
related to #3796?

**Comment by afshin** [comment]
Interesting. So are we talking about something that has both the same host name and the same port?

**Comment by ian-r-rose** [comment]
Yes, I believe so. In Sylvain's case it was a large deployment on https/443 which had both notebook and non-notebook resources.

**Comment by afshin** [comment]
So how can we differentiate between something that should be served by the contents API and something should not be? Because we can't change the definition of `isLocal` if it's strictly meant to describe attributes of a URL, right? `URLExt.isLocal()` should correctly tell you if a URL can be described as `/foo/bar` instead of `protocol://foo/bar` I think.

**Comment by ian-r-rose** [comment]
I think something that has a host specified shouldn't be considered local (even if the host matches the notebook server host).

**Comment by afshin** [comment]
Hm, but in that case we could simply do `isLocal = !!URLExt.parse(url).host`.

**Comment by blink1073** [comment]
The issue is that when you assign even a relative path to an `anchor`, the `host` ends up being the local host.  We need a different way to determine whether the original string is local or not.  It appears the classic notebook is not using its own `parse_url` [function](https://github.com/jupyter/notebook/blob/ae7d39af1eaab1a93aa8f1b0b6fb0380011aea07/notebook/static/base/js/utils.js#L570) at all, merely converting urls to anchor [tags](https://github.com/jupyter/notebook/blob/ae7d39af1eaab1a93aa8f1b0b6fb0380011aea07/notebook/static/base/js/utils.js#L507).  Still digging...

**Comment by blink1073** [comment]
@SylvainCorlay, what do your other URLs look like, do they explicitly start with the local host or are they also relative links?

**Comment by blink1073** [comment]
Note, the following change fixes the handling of `data:` URLs (added parens):

```javascript
return protocol !== 'data:' && (host === location.host || host === '');
```

**Comment by afshin** [comment]
I don't think we are fully covered. I am thinking the following:

```
  /**
   * Test whether the url is a local url.
   *
   * #### Notes
   * This function returns `false` for any fully qualified URL, including
   * `data:` and `file:` protocol URLs.
   */
  export
  function isLocal(url: string): boolean {
    return url.toLowerCase().indexOf(parse(url).protocol) !== 0;
  }

  [
    /* isLocal() should return false */ 'http://localhost:8888/lab',
    /* isLocal() should return false */ 'https://localhost:8888/lab',
    /* isLocal() should return false */ 'https://localhost:8888/lab/https:woot',
    /* isLocal() should return false */ 'https://localhost/lab',
    /* isLocal() should return false */ 'http://google.com/lab',
    /* isLocal() should return false */ 'file://foo/bar',
    /* isLocal() should return false */ 'data:foo/bar',
    /* isLocal() should return true */  '/foo/bar/baz',
    /* isLocal() should return true */  'foo/bar',
    /* isLocal() should return true */  '../foo/bar',
    /* isLocal() should return true */  './foo/bar',
  ].forEach(url => { console.log(url, isLocal(url), parse(url).host); });
```
