### ISSUE TITLE
workspace loading canceled

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3872]
I'm seeing a situation where a workspace load is canceled. Debugging, I see that we essentially cancel any workspace loads in our unload function at https://github.com/jupyterlab/jupyterlab/blob/6067ba1caa544868f9e8c77056645708edbeb2b9/packages/apputils-extension/src/index.ts#L263 by setting `resolve` to true. This happens immediately after the routing handler is called.

However, since the workspace loads in the routing handler are asynchronous: https://github.com/jupyterlab/jupyterlab/blob/6067ba1caa544868f9e8c77056645708edbeb2b9/packages/apputils-extension/src/index.ts#L358
I end up seeing resolve check at https://github.com/jupyterlab/jupyterlab/blob/6067ba1caa544868f9e8c77056645708edbeb2b9/packages/apputils-extension/src/index.ts#L359 run *after* resolve is set to true in the unload function. Thus the workspace load is actually skipped, and I don't see my workspace.

**Comment by jasongrout** [comment]
CC @afshin

**Comment by afshin** [comment]
@jasongrout, I am not sure what's happening in this situation, because if the sequence you lay out were the general case then no workspaces would ever load.

* The `routed` signal should emit after routing is finished and routing only finishes after the command promises are all resolved.
* The workspace load command returns the `fetch` promise.
* So the `unload` function won't be called until the workspace `fetch` has resolved.

There's some condition that breaks this for you, though. I *think* all the edge cases are addressed in the refactor in https://github.com/jupyterlab/jupyterlab/pull/3687 ... which is more reliable and easier to reason about.

If you're up for it, could you try to recreate this issue on that branch? It may have fixed this issue.

**Comment by jasongrout** [comment]
I was puzzled too why it seemed to work okay up to now. I'll try with the other branch.

**Comment by jasongrout** [comment]
Moving to beta 3 to check, after all the workspace things are merged in beta 2.

**Comment by jasongrout** [comment]
This code has been completely rewritten several times now, and I haven't seen the issue recently. I'll close this as resolved, and reopen if I see a problem again.

**Comment by ian-r-rose** [comment]
Hi @amangarg96, there is a `reset` query parameter you can put in the url to clear any existing workspace upon load (e.g. `(/lab?reset`). You can make this the default URL for the application by setting in your `jupyter_notebook_config.py`: `c.NotebookApp.default_url = '/lab?reset'`.
