### ISSUE TITLE
Have the icon in the Jupyter lab tab change state if any of the opened notebooks is running cells

### ISSUE THREAD

**Issue by davidefiocco** [jupyterlab/jupyterlab#3957]
Jupyter notebooks tabs are labeled with three dots or a hourglass when they are still "busy" running cell calculations, however the Jupyter lab browser tab doesn't currently provide any visual cue on my machine (using Firefox 58).

**Comment by mikeyford** [comment]
I agree this is a great feature of notebook which would be really handy in lab too.

I'm hoping that further down the line it will be possible to build an extension that could give an alert notification the machine (or even send one to my phone!), after a long computation has completed.

**Comment by saulshanabrook** [comment]
We want some input here on what people want from a busy signal, since there are multiple ways we could implement this (as shown in the back and forth in #4361).

How will having the favicon change based on the kernel status help you? @mikeyford mentioned the desire to be notified when a long running task is done. Are there other needs that this supports?

If you have multiple kernels running, what would the favicon reflect? If any of them (including those without windows open?) are busy? If the kernel corresponding to the active window is busy?

Would you want other third party extensions to be able to change the busy status? Should they have a way of changing the favicon to some arbitrary icon?

Maybe it's helpful to see this issue as two features.

The first is some sanctioned way of understanding the "busyiness" of JupyterLab. This could be implemented in a variety of granularities, single boolean, mapping of widgets to boolean, mapping arbitrary strings to boolean. Besides updating the favicon, are there other needs this would help with?

The second is updating the favicon to display this busyiness, or some computed value based on it.

**Comment by davidefiocco** [comment]
Just my two cents here: 
I think that ideally it would be nice to have an indication that _some kernel_ is running and some sort of "counter" that indicates _how many_ kernels are running.
For example (nothing more), this could be achieved with a change in color and a digit in the favicon.

Cannot think of other ways I would take advantage of the info on "busyness" of JupyterLab atm, sorry!

**Comment by saulshanabrook** [comment]
That makes me wonder if the "Running" tab on the left should have kernel status associated with each kernel, so if you can see if they are busy. So then the favicon would just be a more condensed view on this page.

**Comment by davidefiocco** [comment]
HI @saulshanabrook, if you are hinting at giving more nuance/info about kernel status in the "Running" tab, e.g. diplaying a "busy" flag, I think that that would be a separate, useful feature for JupyterLab! As you stated that could pair nicely with a "summary" given in the favicon. 
(I think I never saw that "busy" flags/indication in the running tab of Jupyter, so it's not a feature that I miss nor a "regression" though)

**Comment by saulshanabrook** [comment]
FYI there is some discussion going on in another issue about the visibility of kernel states https://github.com/jupyterlab/jupyterlab/issues/4304#issuecomment-388171239
