### ISSUE TITLE
Internationalization and localization

### ISSUE THREAD

**Issue by leonsp** [jupyterlab/jupyterlab#3965]
What are the plans for internationalization and localization in JupyterLab?

For example, if someone's browser is set to prefer the `zh_CN` locale, what would it take to JupyterLab to provide its menus in Simplified Chinese?

I couldn't find anything about i18n and l10n for JupyterLab on the internet.

Jupyter Notebook added i18n in the 5.1.0 release last September: https://blog.jupyter.org/jupyter-notebook-5-1-0-ddc8b0d6e989

**Comment by lokinell** [comment]
I have the same question, hope this feature can implement quickly.

**Comment by blink1073** [comment]
This is not an area we have actively looked at yet, but I imagine it would follow a similar trajectory to what was implemented in the notebook.

**Comment by futurist** [comment]
I also faced the problem, the users are mainly Chinese people, think about 2 ways:

1.
Can make some private method that process messages open for override, like below:

https://github.com/jupyterlab/jupyterlab/blob/98b4e6a73256d6a6980170fcde404ba3e2f6893d/packages/docregistry/src/context.ts#L512

`this._handleError` is **private** and can do nothing for it, possible to make it `protected` or even `public`?

2.
The other way is to override methods in `apputils`, like `showDialog` and `showErrorMessage` etc., and catch the message passed in to do localization.

**Comment by blink1073** [comment]
The way the classic notebook handled it was to instantiate an `i18n` [instance](https://github.com/jupyter/notebook/blob/5711075f0b48dcf4f7ffcd4d93b35ecd1fe363d0/notebook/static/base/js/i18n.js) and pass that to any component that wished to render [text](https://github.com/jupyter/notebook/blob/b8b66332e2023e83d2ee04f83d8814f567e01a4e/notebook/static/notebook/js/actions.js#L122).  The translations are passed from the [server](https://github.com/jupyter/notebook/blob/872a6c7b9b0dbedd2a2fdc98cc9d6e0f1614d1bb/notebook/base/handlers.py#L487) to the client using the page ][template](https://github.com/jupyter/notebook/blob/9c60369a1773753ab138dad6e9b8be4a3eebe32d/notebook/templates/page.html#L101).

I think all of the above could be done in JupyterLab.  We would use `PageConfig` to pass the desired translation, and a single application translator instance, similar to our [clipboard](https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/apputils/src/clipboard.ts#L13), which is used [here](https://github.com/jupyterlab/jupyterlab/blob/2e7bdd6889f3da978f361a4b4f3ab8ff011228a8/testutils/src/notebook-utils.ts#L95).

**Comment by goanpeca** [comment]
Hello @blink1073! I would like to work on this front.

I have looked at different options and since there are so many different ways to get things done:
- https://www.i18next.com/. (Heavy weight...)
- https://airbnb.io/polyglot.js/. (Custom solution)
- https://github.com/messageformat/Jed (Last commit 3 years ago).  (Custom solution)
- https://github.com/guillaumepotier/gettext.js/.  (Small project)
- VSCode tooling https://github.com/microsoft/vscode-nls and https://github.com/microsoft/vscode-nls-dev. (Custom tooling)

I saw how the classic Notebook handled it with Jed with the inks you posted, that could be also used but it seems Jed has not had much activity for three years now.

There are several topics that go into localization: 
- Source files TS/JS/HTML files.
- Storage format for localization (JSON seems to be favored one).
- Tool for extracting updated strings on files.
- Tool for generating the JSON stubs to translate.
- Public service to use for the actual translations (Transifex, Crowdin etc...)

--- 

Also the way to use it. Traditional (gettext) based approach would look like the code you shared

`i18n.msg._('restart the kernel, then re-run the whole notebook (with dialog)')`

Then a tool would parse all occurrences of `_('<sometext>')` and create a `.po` file.  More "modern" approaches are more key based so something like: `nls.localize('InPlaceReplaceAction.previous.label', "Replace with Previous Value")` (VSCode example)  where the localization function will use a key to find the string `'InPlaceReplaceAction.previous.label` and provide the default value as the second parameter. The localization files with the later look like https://github.com/microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-bg/translations/main.i18n.json

Are there any approaches to favor within the project? I could attempt the Jed approach as described in the class notebook and make a test PR.

Thoughts?

**Comment by saulshanabrook** [comment]
@goanpeca I don't have much experience with these tools, but my gut is we shouldn't be too tied to what Jupyter Notebook chose. Things have changed a lot since then and this codebase is a lot different from that one (using typescript, different build system, etc).

Unless others have strong opinions, I would maybe try to understand what you/we think is ideal for the codebases, in terms of the different approaches, and see which tools fit these requirements the best. Of course feel free to experiment with any!

Thank you for offering to start working on this, it is a really important feature and is sorely lacking.

**Comment by goanpeca** [comment]
Hi @saulshanabrook thanks for the feedback. I started experimenting and will test a few of the different available options.

Does it make sense to have a package devoted to this? even if it wraps any chosen tools

`@jupyterlab/i18n  -> repo/packages/i18n/...`
`@jupyterlab/localization -> repo/packages/localization/...`  ?

**Comment by saulshanabrook** [comment]
> Does it make sense to have a package devoted to this? even if it wraps any chosen tool?

Possibly, it depends on the tools. If it would be helpful to wrap some functionality that would be imported in other packages, then yes. If we just need some build time tooling added to the whole repo, we could add that to the buildutils package.

**Comment by blink1073** [comment]
Hi @goanpeca, thanks for the offer to help!  I'll digest your proposal later today and give feedback.

**Comment by goanpeca** [comment]
I started working a bit on this based on what you suggested form notebook, I will have a POC to push later today.

**Comment by blink1073** [comment]
No way!  :heart:

**Comment by blink1073** [comment]
I like the idea of an `i18n` package, tying it to a standard.  I'd also be in favor of the VSCode approach since it puts all languages on equal footing.   However I'd also be happy with the `i18n.msg._('<foo>')` approach.

**Comment by goanpeca** [comment]
There is one thing I would like to ask. 

## Option A, external plugins

Single pot files per `package`, using `es` as example here:



```
package-name/src/locale/package-name.pot
package-name/src/locale/LC_MESSAGES/es/package-name.pot
package-name/src/locale/LC_MESSAGES/es/package-name.json
```

Should `package-name` be the name of repo folder or the name of the NPM package? 

## Option B, for jlab

For the JLab case with all the packages, the single package layout would look something like:

```
jupyterlab/packages/package-name/src/locale/package-name.pot
jupyterlab/packages/package-name/src/locale/LC_MESSAGES/es/package-name.po
jupyterlab/packages/package-name/src/locale/LC_MESSAGES/es/package-name.json
```

## Option B, for jlab with a single huge file

Or if using a single locale for every single package

jupyterlab/packages/locale/jupyterlab.pot
jupyterlab/packages/locale/LC_MESSAGES/es/jupyterlab.po
jupyterlab/packages/locale/LC_MESSAGES/es/jupyterlab.json

**Comment by blink1073** [comment]
I like the idea of all of the languagues being opt-in and readily install-able as conda packages.

**Comment by blink1073** [comment]
As opposed to us being a central spot for all of that work and shipping with every language.

**Comment by blink1073** [comment]
Maybe a single separate repo in the JupyterLab org that produces individual python/conda packages?

**Comment by goanpeca** [comment]
>I like the idea of all of the languagues being opt-in and readily install-able as conda packages.

Sure, like a pack. This is probably not very UX friendly though, unless we provided a way to install for the user in a straight forward way.

>As opposed to us being a central spot for all of that work and shipping with every language.

Is the concern size or?

Now, how would that approach work for extension authors? Not all extensions would be bundled in a single repo, so we need a way for authors to provide that on their own plugin?

**Comment by blink1073** [comment]
Yes, I was concerned about overall size.  It looks like Mozilla implements them as Add-ons.  I think we could make them readily discoverable using metadata.

Extension authors is a good question, we'd want them to be able to provide their own phrases as part of their package, but then how would contributors provide all the translations?   Perhaps if we had language as a setting, we could auto-install language packs associated with an extension, e.g. `jupyterlab-git-ja` would come with `jupyterlab-git` if you had `ja` set as your language.

**Comment by goanpeca** [comment]
>Yes, I was concerned about overall size. It looks like Mozilla implements them as Add-ons. I think we could make them readily discoverable using metadata.

Doable, for anything in core JLab, we can get away with a separate repo bundling all languages and connect that to crowdin to make the process easier (Crowdin is the service I know, free for open source and has good integration with github)

For extensions I will need to think a bit more how to do it extension authors should probably bundle their localization files within the same package.

**Comment by blink1073** [comment]
My brain dump from our meeting today:

- @goanpeca will start with a personal repo that adds a server extension and lab extension providing i18n
   - The localization endpoint will eventually be a. part of `jupyterlab_server` and will provide the translations to the front end extension
   - There will be endpoints for both the available languages and the translations
   - Translations will be loaded from known locations similar to how settings are handled, with extensions able to provide their own locale data that takes precedence
   - The front end extension will take a data connector and provide a translation interface that is used by extensions
- We will consider making a monorepo for internationalization mirroring https://crowdin.com/project/spyder so that we can crowd source translations
- The chosen language will be a setting, and changing the language will require a page refresh

**Comment by blink1073** [comment]
Also, the monorepo could be used to generate language packs that are conda packages, and we could provide a UI for selecting a language and installing that language pack.

**Comment by blink1073** [comment]
Crowd.in site: https://crwd.in/jupyterlab

**Comment by blink1073** [comment]
WIP repos:
https://github.com/goanpeca/jupyterlab-translate
https://github.com/goanpeca/jupyterlab-language-pack-cookiecutter

**Comment by blink1073** [comment]
Screenshot from @goanpeca's demo today :clap:

![image](https://user-images.githubusercontent.com/2096628/86952088-0fff8000-c118-11ea-89b7-1be1ea76c753.png)

**Comment by blink1073** [comment]
@vidartf did you have some more feedback from today's meeting?

**Comment by goanpeca** [comment]
Some next steps:
- PR against jupyterlab_server to provide the translations_handler
- PR against jupyterlab to create a new `@jupyterlab/translation` package.
- PR against Jupyterlab to transform all strings to localizable strings.

Just to clarify, this work is dealing with localization (i10n). i18n will be for future work :-)

**Comment by vidartf** [comment]
I just wanted to mention that while reading up a bit, I came over the project [formatjs](https://formatjs.io/) which seems to have some popular packages. That package links to a few other standards that they claim to be following, among others an EMCA effort to standardize an API. I have been having a hard time figuring out if that is going anywhere though (the ECMA standard), so not sure if it is something that should affect our efforts, but I just wanted to flag it for attention.

As an aside, one of the standards linked also has a larger effort on keyboard layouts! http://cldr.unicode.org/index/charts/keyboards  That might be relevant for lumino (cc @jasongrout ).

**Comment by blink1073** [comment]
I've been speaking with Craig Cummings from the Unicode Technical committee this week.  He pointed out the the following emerging standards: 

The Unicode MessageFormat working group for standardized handling of plurals, gender, etc.: https://github.com/unicode-org/message-format-wg

ECMAScript Temporal API Specification: https://github.com/tc39/proposal-temporal
 
ECMAScript Internationalization API Specification: https://github.com/tc39/ecma402
I was excited to see [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) but it has no support on Safari.

He is sharing with me some tips on bidirectional support, which I'll post on https://github.com/jupyterlab/jupyterlab/issues/1359

| As an aside, one of the standards linked also has a larger effort on keyboard layouts! http://cldr.unicode.org/index/charts/keyboards

Great!

**Comment by goanpeca** [comment]
>I have been having a hard time figuring out if that is going anywhere though (the ECMA standard), so not sure if it is something that should affect our efforts, but I just wanted to flag it for attention.

Thanks, @vidartf for the link. I will take a look. Maybe it should at some point but since gettext is quite standard I think any moving to any other system in the future should be straightforward 🤷 ?

---

Thanks for all the information @blink1073 ! I will be taking a look at it. Do you think any of these should affect the original idea/work in progress?

**Comment by blink1073** [comment]
I'm not sure yet, still digesting all the info myself.

**Comment by goanpeca** [comment]
Ok, so I read a bit. I guess is just different formats and reasons and origins. ICU seems to be a more involved and complex format to support more complexity, but I do not think the JLab UI needs that.

```icu
"{gender_of_host, select, "
  "female {"
    "{num_guests, plural, offset:1 "
      "=0 {{host} does not give a party.}"
      "=1 {{host} invites {guest} to her party.}"
      "=2 {{host} invites {guest} and one other person to her party.}"
      "other {{host} invites {guest} and # other people to her party.}}}"
  "male {"
    "{num_guests, plural, offset:1 "
      "=0 {{host} does not give a party.}"
      "=1 {{host} invites {guest} to his party.}"
      "=2 {{host} invites {guest} and one other person to his party.}"
      "other {{host} invites {guest} and # other people to his party.}}}"
  "other {"
    "{num_guests, plural, offset:1 "
      "=0 {{host} does not give a party.}"
      "=1 {{host} invites {guest} to their party.}"
      "=2 {{host} invites {guest} and one other person to their party.}"
      "other {{host} invites {guest} and # other people to their party.}}}}"
```

Which also seems to be very painful for a translator : Crowdin with ICU

![image](https://user-images.githubusercontent.com/3627835/87563418-cd442780-c684-11ea-817a-d5cff254f978.png)

**Comment by goanpeca** [comment]
Will explore the usage of the ICU format to see how that would change.

**Comment by qiujiangkun** [comment]
I have a weird localization setting.
I'm using Manjaro with localization en_US but some other settings for China. The notebook page is mixed with Chinese and English. Everything but prompts is in English. They are inconsistent somehow. 

```text
LANG=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_MONETARY=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_NUMERIC=zh_CN.UTF-8
LC_PAPER=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_TIME=en_US.UTF-8
```

**Comment by fcollonval** [comment]
@blink1073 @goanpeca Could we close this?

**Comment by blink1073** [comment]
Yep!
