### ISSUE TITLE
Catching terminal shortcuts

### ISSUE THREAD

**Issue by gessha** [jupyterlab/jupyterlab#400]
When I was trying the console, I noticed that it doesn't catch some bash shortcuts. For example:
Ctrl+L for clearing the screen
Alt+B for going to previous word in current command

Is it possible for these shortcuts to be catch when the focus is on the console?

**Comment by blink1073** [comment]
Hi @gessha, do you mean providing those shortcuts in the Jupyter Console, or are they not working for you in the terminal emulator?

**Comment by gessha** [comment]
Hi @blink1073, I meant the Jupyter Console.
Btw, I haven't tried this outside of Chrome.

**Comment by fperez** [comment]
While we may over time be able to implement some of these, it's important to clarify that the console is *not* a terminal emulator.  It's much closer to an "append-only notebook without markdown"... The text editing experience should be identical to that of the notebook, the difference being that up-arrow retrieves the previous "cell" for re-execution rather than moving up, as there is no document to be edited.

I can see the case for clearing the screen, as that one already works in the qt console and is useful (we could even consider having a way to *fully* clear the console, not just moving the prompt to the top but discarding all previous entries).

So my suggestion is:  `Ctrl-L` for a basic clear-screen is in-scope for 1.0, `Alt-B` and full vt-100 terminal control characters are out of scope.  For text-editing, we'll just reuse the same machinery in the console as in the notebook and have it offer parity with that (after all, that's the point of using the same tools, to get benefits of code reuse :)

Does that sound OK?

**Comment by gessha** [comment]
Yeah, it sounds great.
Thank you for working on this awesome project! I'm using it on a daily basis and I've also introduced it to a couple of my friends and we all love it.

**Comment by sccolbert** [comment]
I'd like to add that this behavior should be exposed as commands for the console, so that users are free to customize the shortcuts via the shortcut registry. We can of course, provide a default shortcut for the time being.
