### ISSUE TITLE
Handling code cells with execution errors

### ISSUE THREAD

**Issue by wstomv** [jupyterlab/jupyterlab#4026]
We use Jupyter notebooks in our education on a large scale (over the last three weeks, we processed over thirty thousand notebooks). For our (2300) students and (100) assistants it would be helpful to have two features:

* Run all cells, proceeding _even when errors occur_ (same as `nbconvert` with `allow-errors` option)
* Ability to navigate to the next code cell that _raised an exception_

Also, the [toc](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/toc2) extension (for Table of Contents) of Jupyter Notebook is helpful in this respect, because it shows execution progress, by highlighting toc entries that have not yet been executed.

Currently, we use Jupyter Notebook (classical); so, this would be something for next year, when JupyterLab could be the preferred tool to work with notebooks.

**Comment by jasongrout** [comment]
Thanks for the feedback!

**Comment by jasongrout** [comment]
CC @ian-r-rose, who started working on a TOC extension: #3878.

**Comment by wstomv** [comment]
To add some detail, in the current Jupyter Notebook (we use 5.0), when you do **Cell > Run All **, the view immediately navigates all the way to the last cell of the notebook, and stays there even if execution gets interrupted halfway. It is very annoying that you then have to search for the cell that raised the exception.

**Comment by vidartf** [comment]
> Run all cells, proceeding even when errors occur (same as nbconvert with allow-errors option)

This is already in notebook (from version 5.1, https://github.com/jupyter/notebook/pull/2549), and there is an issue tracking feature parity with that for lab #2412.

I'm also going to add a cross-reference to #2277 for bookkeeping, as that ties into this feature.

**Comment by vidartf** [comment]
Reading the initial post again, I'm guessing there is some difference to your request from the tag based one after all. This isn't dealing with expected failures is it? This is saying that all cells should be independent of each other, so simply run all of them no matter what.

**Comment by Mahluza** [comment]
Hi, so has this feature been created yet? The one to run all cells.

**Comment by joelostblom** [comment]
@wstomv  @Mahluza 
> Run all cells, proceeding even when errors occur (same as nbconvert with allow-errors option)

This is possible by adding a `"raises-exception"` tag to the cell metadata:

```
{
    "tags": [
        "raises-exception"
    ]
}
```

 It was introduced in #2412 and restored in #7020 after not working for a bit.

For ways to add a ToC to the JupyterLab notebook, [see my SO answer here](https://stackoverflow.com/a/59286150/2166823).

**Comment by fperez** [comment]
It seems to me that this issue is now largely handled, at least at the level of how classic did, by honoring the `raises-exception` tag (I just wonder if we should have called that `causes-error` to be a bit more generic regarding languages that don't use the term "exception").

So I wonder if it should be closed?

I only have one idea/suggestion left, but that could be a separate, purely UI/UX issue: it might work to have a stateful toggle in the "Run" menu called "Ignore all errors when running cells" for people to easily switch between the two behaviors. That would be per-session and global, so much more coarse-grained than the metadata tags, but perhaps a useful tool for many users who may want to experiment with quick runs rather than carefully annotate teaching-oriented notebooks.

@jasongrout if you think that's worth discussing but it belongs better in a separate issue I'm happy to open one :)

**Comment by jasongrout** [comment]
I think that sounds like an excellent idea, and I think this issue is an excellent place for the discussion. I'd love to hear if @wstomv thinks this would solve their usecase better than the metadata approach.

**Comment by fperez** [comment]
Done @jasongrout, see link above! I suggest closing this one then as I think its scope is now well handled in current Lab.

**Comment by jasongrout** [comment]
Thanks!
