### ISSUE TITLE
Custom kayboard shortcuts in notebook

### ISSUE THREAD

**Issue by klonuo** [jupyterlab/jupyterlab#4079]
Hi,

in Jupyter Notebook I've set preferred keyboard shortcuts to Sublime text, by editing `~/.jupyter/custom/custom.js`:

```javascript
require(["codemirror/keymap/sublime", "notebook/js/cell"],
    function(sublime_keymap, cell) {
        cell.Cell.options_default.cm_config.keyMap = 'sublime';
    }
);
```

However this doesn't seem to work for Jupyterlab.
OTOH, there is menu option to set custom shortcuts for text editor.

Is there easy way to make custom shortcuts for notebooks?

**Comment by ian-r-rose** [comment]
Hi @klonuo, this is currently not possible in the core of JupyterLab. However, it is possible to write an extension that does this. As an example, you can look at https://github.com/jwkvam/jupyterlab_vim, which enables vim keybindings for notebook cells.

**Comment by klonuo** [comment]
Ok, thanks

**Comment by flekschas** [comment]
@ian-r-rose Are you planning to add support for this later? Or support for `~/.jupyter/custom/custom.js`? I am just wondering. Thanks!

**Comment by ian-r-rose** [comment]
It is likely to be some time before this is in the core of JupyterLab (just how much, I don't know). There are a number of challenges in getting custom keyboard mappings working in the notebook, since the notebook *also* has it's own keyboard shortcuts that can conflict (at least with the vim keybindings). At the moment, I recommend trying an extension like the one linked above (which is the new apprach for extensions, superseding `custom.js`)
