### ISSUE TITLE
ipywidgets and Jupyterlab extensions

### ISSUE THREAD

**Issue by zonca** [jupyterlab/jupyterlab#4092]
I'd like to build a simple display in Jupyterlab that monitors my jobs in the queue of a Supercomputer every 5 minutes. I was planning to use ipywidgets.

However I would like it to display in a separate Jupyterlab tab and have an icon in the launcher. Is there a way to turn a ipywidgets widget into a Jupyterlab extension?
Or should I just implement a Jupyterlab frontend extension + nbserver extension and forget about ipywidgets?

Thanks!

**Comment by jasongrout** [comment]
Is monitoring your queue something you would do from a python kernel? What sort of things do you want in the display? Are they just things you can use from standard html controls, or are you wanting to use things like bqplot to visualize more complex things?

It sounds easier and simpler to create a server extension to provide the data, and a jlab extension to display the data, rather than spin up a kernel to talk to ipywidgets, and package up ipywidgets to run outside of the notebook.

To answer your specific questions: right now it would take some work to get ipywidgets to display in from a new launcher tab. Probably not *too* much work, since we already have ipywidgets working in static html pages, and probably fairly straightforward work, but still, some work.

**Comment by zonca** [comment]
it's from the Python kernel, I use subprocess to launch a command over ssh and get a blob of text back that I can parse in Python to get the job name, if it is running, job length and so on.
Then I want to display that in a HTML table and refresh it every 5 min. No graphics, just plain text.
Later I'll want to add also a couple of buttons for example to kill a job or submit a new one.

What is the simpler server extension + jlab extension pair I can look at?

**Comment by jasongrout** [comment]
Are there any security concerns with exposing that information to anyone with access to the server? i.e., anyone that could go to a specific URL on the server?

I don't think we have a simple example of a server extension+jlab extension pair. Your example would be an idea one to point future people to, though! We're happy to help you through the process of making it.

Here is a simple example of a server extension: http://jupyter-notebook.readthedocs.io/en/stable/extending/handlers.html

That would probably provide the necessary info, probably in some structured format like json.

The jlab extension would know to hit that server URL, get the information, and display it in a table. For an example of a simple extension like this, take a look at the xkcd extension example: http://jupyterlab.readthedocs.io/en/stable/developer/xkcd_extension_tutorial.html

**Comment by zonca** [comment]
No, it's public information

**Comment by jasongrout** [comment]
Do you need to do that subprocess/ssh command from a kernel? Or is any python process good enough? (i.e., is it just as easy to do it from a server extension as from a kernel?)

**Comment by zonca** [comment]
Yes, any python process should be good

Il ven 2 mar 2018, 19:53 Jason Grout <notifications@github.com> ha scritto:

**Comment by zonca** [comment]
ok, I started with a toy example to play with this, it displays the output of a shell command inside JupyterLab:

https://github.com/zonca/jupyterlab_shellcommand_monitor

there is a bit of description in the readme, I have some questions I opened as issues here: https://github.com/zonca/jupyterlab_shellcommand_monitor/issues

**Comment by jasongrout** [comment]
Great! I submitted a small PR to clarify the readme.
