### ISSUE TITLE
Creating new Notebook then Hitting Cancel Still Creates a Notebook

### ISSUE THREAD

**Issue by cancan101** [jupyterlab/jupyterlab#4157]
If I hit cancel here, a notebook file is still created:
![image](https://user-images.githubusercontent.com/51059/37176421-53b9cd88-22ea-11e8-9795-3dbb4b95deb8.png)

**Comment by ian-r-rose** [comment]
I think this is actually behaving as intended, though that intent is kind of confusing, and we should probably change it: the dialog is for selecting a kernel, not for creating a new notebook. So if you cancel the dialog, you cancel the kernel selection but not the notebook creation.

Unfortunately, this will be kind of tricky to fix, and I think it will require some API breaking changes in `IClientSession`. In particular, it will be a similar fix to #3703, where we need to change the resolved-type of the Promise to indicate whether the dialog box was canceled. If it is canceled, we will then delete the just-created notebook. In running this down I also found some circular logic in `IClientSession` that will also need to be fixed (`selectKernel` can call `initialize` which can call `selectKernel`).

Since this will be API-breaking, I am bumping this to beta 3. What do you think, @jasongrout?

**Comment by ian-r-rose** [comment]
I am not sure what the best fix is. I have some recollection of us handling this case a while back. I think we deleted the notebook if a kernel is not selected, rather than conditionally creating it, but it was several refactors ago, and I could not find the commits. I think from the user perspective, either of those behaviors should be okay, and it can be an implementation detail for us.

Currently the kernel selection dialog is the same for creating a new notebook vs changing the kernel on an existing one. That should be okay, but we want fundamentally different behavior in those two cases if the user presses `CANCEL`. If it is a new notebook, we don't want it to be created in the first place. If it is an existing notebook, we don't want to change the kernel. At the moment, `IClientSession.selectKernel` returns `Promise<void>`. I think we should change it to `Promise<boolean>` where the return value indicates whether a selection was made. Then we can respond to that boolean depending on whether it is a new notebook or not.
