### ISSUE TITLE
Black text on dark background in advanced settings with dark theme

### ISSUE THREAD

**Issue by fuglede** [jupyterlab/jupyterlab#4169]
Similar to what is mentioned in #3922, when opening the "Advanced Settings Editor" for the first time, while also using the "JupyterLab Dark" theme, black text appears on a dark background.

**Comment by ian-r-rose** [comment]
Hi @fuglede, can you be more specific (perhaps with a screenshot)? I can't find a place with black text on a dark background (though I suppose it would be hard to find).

**Comment by fuglede** [comment]
@ian-r-rose It shows up on the welcome screen for the settings, shown (only) the first time you open the menu.  (Can I somehow reset my settings to make it appear again?)

**Comment by ian-r-rose** [comment]
Ah, thanks for the information. I pulled up the instructions and it looks fine to me:
![image](https://user-images.githubusercontent.com/5728311/37528267-7356122a-28f1-11e8-949b-b9512a8cede2.png)
I wonder if this was fixed in #3887 a few days ago. What version of JupyterLab are you using, and can you try updating?

**Comment by ian-r-rose** [comment]
Oops, no, you're right, it's broken. I had just accidentally started on a fix :smile:. PR incoming.
