### ISSUE TITLE
Double-clicking the dark-grey empty space next to tabs should create a Launch screen

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#4185]
I find myself wanting to "double-click" the grey areas next to a tab to create the "new tab" window. Does this sound like a reasonable pattern to support with JupyterLab? Alternatively, if there were a little floating button to the right of the right-most tab for creating a launch window, I think that'd work as well.

**Comment by timkpaine** [comment]
Or just a small + sign like the add tab on most browsers

**Comment by timkpaine** [comment]
This is a browsery UX thing, I like it

**Comment by sccolbert** [comment]
Just an anecdote on why the "+" isn't *already* there, is because it's a bit of a tricky UX issue. Since tabs can be moved around and reordered, the question arises as to what to do with the "+" when the user starts moving tabs (since it would be in the way). Chrome simply hides the "+", and that's an option. But we also thought that we might want more buttons to the right in the future, perhaps minimize/maximize/settings/etc., and didn't really have a good answer about a "+" would interact with those.

So, we're not opposed to putting something there, but exactly *what* to put there is not yet fully clear.
