### ISSUE TITLE
Keep theme for client (browser)

### ISSUE THREAD

**Issue by gaborvecsei** [jupyterlab/jupyterlab#4307]
It would be really nice if we could keep a theme for a certain client (browser) when the JupyterLab is in use by multiple users.

**Comment by saulshanabrook** [comment]
We do support themes that can be used in JupyterLab. Please comment to clarify what exactly you are looking for on top of that.

**Comment by saulshanabrook** [comment]
Thanks for the clarification! So everyone is using one JupyterLab server?

**Comment by gaborvecsei** [comment]
Yes, everyone used one server

**Comment by jasongrout** [comment]
Right now the theme settings are saved on disk in a single location per jupyterlab server (the idea of a jlab server is that only *one* person is using it). In order to have different settings for different people using the exact same jlab server, there needs to be the concept of multiple users first of all. That is usually done through something like jupyterhub, which launches a new jlab server for each user.

Having multiple people use a single jlab server isn't supported right now. For example, if two people open the same file and start editing it, one person's changes will likely mess up the other, or at least overwrite other changes.

**Comment by gaborvecsei** [comment]
@jasongrout Thanks for the clarification!
