### ISSUE TITLE
Dragging an image into a markdown file should embed the image as a link to imgur

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#4333]
This could be similar to how HackMD handles image/GIF embedding. Basically:

1. A user drags an image onto a code editor that has a markdown folder open.
2. When they release, it automatically uploads the image to imgur, gets the URL, and embeds it as an image in the markdown file.

Here's an example of how this works (with a GIF) in HackMD:

![2018-04-06_13-51-31](https://user-images.githubusercontent.com/1839645/38443768-b000be08-39a1-11e8-9200-74cb64dabecf.gif)

**Comment by choldgraf** [comment]
cc @jasongrout :-)

**Comment by ian-r-rose** [comment]
This should be possible to do a similar fashion to the native file upload that the filebrowser uses. Note that GitHub comments also allow native dropping and pasting into markdown.

**Comment by jtpio** [comment]
Pasting an image from the clipboard would also be super handy (also supported by GitHub comments).

**Comment by nevanscott** [comment]
I like this idea, but why upload the image to a service like imgur instead of as a local asset? (Maybe using an external service could be available through a plugin for example.)

**Comment by nevanscott** [comment]
Related issue: #4306

**Comment by vidartf** [comment]
Note: The drag-and-drop / copy-paste functionality for this could be shared with that needed for adding attachments to markdown cells in notebooks.

**Comment by jasongrout** [comment]
> I like this idea, but why upload the image to a service like imgur instead of as a local asset?

+1 to local upload. I would *not* expect my cutting-edge research graphics to be uploaded to a third-party service. Perhaps we could create a directory named `.<filename>-images` or something to put the images in the same directory as the file?

**Comment by dansteingart** [comment]
+1 to this so long as it can be customized through the config file.

On Thu, Apr 19, 2018 at 12:46 PM, Jason Grout <notifications@github.com> wrote:
I like this idea, but why upload the image to a service like imgur instead of as a local asset?

+1 to local upload. I would not expect my cutting-edge research graphics to be uploaded to a third-party service. Perhaps we could create a directory named .<filename>-images or something to put the images in the same directory as the file?

**Comment by flutefreak7** [comment]
Just since it hasn't been said yet - there are lots of folks in government or industry working with data that would be illegal to upload to a service such as imgur. This issue title scared me a little.

Looks like this is resolved in #4306 and that pasting an image now embeds it as an encoded png directly to the notebook file? Sounds great! It's unclear to me why this one is still open then...

**Comment by vidartf** [comment]
Yes, I think this remained open mostly as an oversight. Closing as out of scope.

**Comment by vidartf** [comment]
PS: This should still be possible to implement in a third-party extension. If anyone attempts that and need some changes to core to allow it to override the current behavior, please open a new issue referring back to this one.
