### ISSUE TITLE
Jupyterlab should not save untitled.txt every time a text editor is opened

### ISSUE THREAD

**Issue by jstaf** [jupyterlab/jupyterlab#4351]
Just a UX quirk - Jupyterhub automatically opens and saves an untitled.txt file to disk every time a text editor is opened. This file remains, even when saving the file under the actual name a user wants.

I do not think most users will want a folder full of blank "untitled.txt" files - it would be better if these files were not saved by default when opening a text editor (and instead it should prompt for the "save as" dialog if the user attempts to save one).

**Comment by jinjiren** [comment]
I'm wondering why only so few users are complaining about this... I hate the `untitled.txt` files :(

**Comment by jinjiren** [comment]
@jstaf @BoPeng, Hi, I wrote a [solution](https://gist.github.com/jinjiren/29244faa896ac788357a46338f78b580) for solving the problem caused by opening notebooks, but maybe it can also help solve your problems.

```Python
import io
import os
import re
from nbconvert.exporters.script import ScriptExporter
from notebook.utils import to_api_path


def script_post_save(model, os_path, contents_manager, **kwargs):
    """Save a copy of notebook to the corresponding language source script.
    For example, when you save a `foo.ipynb` file, a corresponding `foo.py`
    python script will also be saved in the same directory.
    However, existing config files I found online (including the one written in
    the official documentation), will also create an `Untitile.txt` file when
    you create a new notebook, even if you have not pressed the "save" button.
    This is annoying because we usually will rename the notebook with a more
    meaningful name later, and now we have to rename the generated script file,
    too!
    Therefore we make a change here to filter out the newly created notebooks
    by checking their names. For a notebook which has not been given a name,
    i.e., its name is `Untitled.*`, the corresponding source script will not be
    saved. Note that the behavior also applies even if you manually save an
    "Untitled" notebook. The rationale is that we usually do not want to save
    scripts with the useless "Untitled" names.
    """
    # only process for notebooks
    if model["type"] != "notebook":
        return

    script_exporter = ScriptExporter(parent=contents_manager)
    base, __ = os.path.splitext(os_path)

    # do nothing if the notebook name ends with `Untitled[0-9]*`
    regex = re.compile(r"Untitled[0-9]*$")
    if regex.search(base):
        return

    script, resources = script_exporter.from_filename(os_path)
    script_fname = base + resources.get('output_extension', '.txt')

    log = contents_manager.log
    log.info("Saving script at /%s",
             to_api_path(script_fname, contents_manager.root_dir))

    with io.open(script_fname, "w", encoding="utf-8") as f:
        f.write(script)

c.FileContentsManager.post_save_hook = script_post_save
```

You can add this script to your `.jupyter/jupyter_notebook_config.py` to use it. Note that you may need to restart the jupyter notebook / lab for it to work.

**Comment by jasongrout** [comment]
We made the decision early on to save a file when it is created (which means we need a filename right away) because:

1. We didn't want to lose file content if there was an issue with the browser (i.e., we didn't want to keep the unsaved file's state only in the browser)
2. The notebook server's new file api design worked this way (See the /api/contents POST operation at http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml#/contents/post_api_contents__path_)
3. It allowed us to work consistently with how model changes worked, syntax highlighting was chosen, etc., across all files.

I agree the workflow is not ideal. I think it would be great if the notebook server supported having unsaved temporary files that could be named and saved later. We are going to be redoing how the Jupyter Notebook server works with files as part of real-time collaboration, and this will be one of the design choices we will keep in mind. If anyone here has ideas they'd like to explore about how to enable this using the current Jupyter notebook server, please let us know. One option is to force people to pick a name when they create a file, but even that has some tricky cases dealing with race conditions about overwriting other files.

**Comment by jstaf** [comment]
I'd prefer to be prompted for a filename upon creating a new file. It's a pretty intuitive workflow and I think that's how Atom and VSCode do it too.

Currently the workflow requires creating a new file, saving it as what you want, closing and deleting untitled.txt, reopening the file, and finally start working. In my ideal world it would be create file and choose its name, then start working immediately.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nickeubank** [comment]
@jasongrout What if, when one creates a text file, Jupyter asks for a name before opening the file rather than defaulting to (and saving) it as Untitled.txt?

**Comment by jasongrout** [comment]
Let's consolidate the discussion over to #5207, where this is discussed in more detail.
