### ISSUE TITLE
<kbd> tag does not render in notebook

### ISSUE THREAD

**Issue by JarnoRFB** [jupyterlab/jupyterlab#4374]
Using `<kbd></kbd>` in Jupyter notebook renders to a keyboard key markup like <kbd>Ctrl</kbd>. In the Jupyter lab notebook, nothing really happens. Could be related to #1812 .

**Comment by jasongrout** [comment]
Fixing this (and other tags mentioned in #1812 such as sup/sub, colspan/rowspan) should be very straightforward, so tagging this as a good first issue. These tags just need to be added to the security whitelist: https://github.com/jupyterlab/jupyterlab/blob/e377acd19b1bb13dfd76d65d2e7210938e273ec0/packages/apputils/src/sanitizer.ts#L64

Here is another PR that did exactly this for the del tag: https://github.com/jupyterlab/jupyterlab/pull/3771

PRs adding kbd and the other tags above to the whitelist are more than welcome!

**Comment by reevejd** [comment]
I've opened a PR here: https://github.com/jupyterlab/jupyterlab/pull/4618

**Comment by jasongrout** [comment]
Closed by #4618.

**Comment by domoritz** [comment]
It looks like we can use `kbd` now but the default style is not great. Could you add some CSS to make it look more like a keyboard button?

**Comment by ian-r-rose** [comment]
Nice idea. I'm going to reopen this as a good first issue. There is some sample `<kbd>` CSS here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd , which somebody could use as inspiration (though I personally think the dropshadows are a bit much in that example).

A new `jp-RenderedHTML kbd` rule would be added here: https://github.com/jupyterlab/jupyterlab/blob/a6d293461ae90d4b27b8799ec81cf1918cc74e49/packages/rendermime/style/index.css#L164

**Comment by bollwyvl** [comment]
Just to throw it out, blueprint does provide styling of kbd:

https://blueprintjs.com/docs/#core/components/hotkeys.dialog

However, I am highly against making bp part of the renderedhtml dependency
chain, as then we're right back in bootstrap land, and I would like to keep
the eventual lab-forward nbconvert target as lean as we can make it.

I actually like the dropshadow, but the fake 3d shine is gross. GitHub also
has a nice one:

https://help.github.com/en/articles/using-keyboard-shortcuts

Anyhow, whatever ends up happening, it should expose some theme variables
so that a theme author can make them look like Atari buttons or whatever.
Pew pew pew!

**Comment by domoritz** [comment]
I sent a PR at #6025.
