### ISSUE TITLE
Adding more than 11 types displays unrecognizable color in completer extension

### ISSUE THREAD

**Issue by geonilpark** [jupyterlab/jupyterlab#4402]
Hi, 

I am trying to utilize populate my data with typeMap that can be passed by Jupyter Client complete_ reply - reply.metadata._jupyter_types_experimental.

From the completer code, I noticed there are 5 reserved types so, completer extension made the color to be transparent which is "white" if more than 6 new types are coming.

My data has more than 10 types and most of them turned into the "white" since completer/completer-extension only supports 10 colors now.

Current 10 colors scheme seemed to be small to handle many categories.

Can anyone take a look at this? or do you have any plan to extend colors?

![image](https://user-images.githubusercontent.com/14316384/38840060-8c49f42c-4192-11e8-937c-c9c7b1958341.png)

Thank you,
Geonil

**Comment by ian-r-rose** [comment]
Thanks for the report @geonilpark! Confirmed, this looks like a bug. We should be cycling through the colors [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/completer/src/widget.ts#L728), rather than monotonically increasing them.

I think we can get this into a patch release within the next week or so.

**Comment by geonilpark** [comment]
Thank you!
