### ISSUE TITLE
Command palette interaction

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#447]
Right now the command palette has some awkward interactions:

* When you open the CP with Command+Shift+P, it focuses the search field and you can type and press enter to run the command. But there is no visual indication the command was run. The search field is still populated/filtered and the original selected item is still selected. Running a command should completely reset the search field and selection.
* After you run a command, you can't keep working on your previous activity as the CP is still focused. We should focus the previous activity.
* If you ran a command, go back to your activity and they try to run another command, the CP collapses. This makes it impossible to run multiple commands in a row. Command+Shift+P should always *open* (not toggle) the CP.

We might eventually want to move the CP away from the L side panel, but let's first get the interactions right and see how it feels.

**Comment by sccolbert** [comment]
A couple points to this:

(1) What you describe *used* to be the behavior. We opted with the current behavior as this is what sublime does (except that sublime closes the palette on each command execution). I have no strong opinion on this either way.

(2) The input field is focused and selected *before* the command is run. So if the command execution sets focus to something, that thing will remain focused. In general, the command palette has no way of knowing what was previously focused. I think the best course of action is to allow the command to decide what should get focus.

(3) Yep. Some of us talked about this briefly as Scipy and seemd to agree `Cmd+Shift+P` should always open the command palette instead of toggle it. And `Esc` should probably close it. However to be clear, this is only adjust the default key bindings, and will be completely user-specifiable in the future.

**Comment by jasongrout** [comment]
(1) Some ideas: perhaps even a temporary indication, such as the command entry in the command palette blinking once or twice when executed, would help provide visual feedback that a command was executed. And then once the command is executed, deselect the command, but leave the filter left in place and selected, as is currently done.

**Comment by jasongrout** [comment]
+1 to `Cmd+Shift+P` always opening, and `Esc` closing when the palette is focused.

**Comment by jasongrout** [comment]
> After you run a command, you can't keep working on your previous activity as the CP is still focused. We should focus the previous activity.

We decided in the JLab meeting that this was a bad idea. The command itself should focus if desired, but the command palette wouldn't know where to focus.

**Comment by ellisonbg** [comment]
I think this can be closed.

**Comment by jasongrout** [comment]
> But there is no visual indication the command was run.

> (1) Some ideas: perhaps even a temporary indication, such as the command entry in the command palette blinking once or twice when executed, would help provide visual feedback that a command was executed.

This was not addressed, but I'll open another issue for it.
