### ISSUE TITLE
jupyterlab markdown highlight not working as it does in classic

### ISSUE THREAD

**Issue by afonit** [jupyterlab/jupyterlab#4549]
version:
jupyterlab                0.32.0                   py36_1    conda-forge

When in classic I can do this:
![classic](https://user-images.githubusercontent.com/1798497/39876224-9c921e20-5440-11e8-9d91-179e3292b8d6.png)

But when I do this in jupyterlab I get:
![lab](https://user-images.githubusercontent.com/1798497/39876239-a2fecea2-5440-11e8-8a3e-32afd5a323c6.png)

It is doing __something__ in lab as the font looks different, but it appears as though the background highlight is not showing up.

I have tried other markdowns such as bullets on lists, numbering items, tables etc, and the only one I can't get to work is this highlight.  Searching on github I am not see an issue like this reported with markdown - although there are some dealing with html tags in markdown https://github.com/jupyterlab/jupyterlab/issues/1812.

**Comment by OmegaNJU** [comment]
Yes, in default jupyterlab theme, html <pre> tag is too confusable to find and distinguish with plain texts.

**Comment by ns23** [comment]
Can I work on this issue??

**Comment by ian-r-rose** [comment]
Yes @ns23, we would welcome your help. I think what is needed is to update the CSS rule [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/style/index.css#L280) to have the same (or similar) background color as in the classic notebook. It should probably be chosen from the theme variables [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/theme-light-extension/style/variables.css#L178) so that it can be overridden by different themes.

**Comment by ian-r-rose** [comment]
Fixed by #4846, thanks @biermeester!
