### ISSUE TITLE
WebGL for vegalite rendering? (potential enhancement)

### ISSUE THREAD

**Issue by jamestwebber** [jupyterlab/jupyterlab#4586]
I've been poking around the edges of this idea for a little while and I _think_ this is the place to check in, but I might be wrong because it's a dense codebase and ecosystem.

Since Altair 2.0 came out I've been experimenting with it in JupyterLab and it's mostly great. The one thing that could be better is its performance on very large datasets (tens of thousands of points). WebGL seems like a great candidate to speed that up, and some folks at vega actually implemented a WebGL renderer [here](https://github.com/vega/vega-webgl-renderer) that appears to work.

I'm not a JS guru and so it's been tough to decipher exactly where this would plug in, but I think it would take the form of an extension that bundles the linked code and tells the notebook to use webgl for rendering. I'd be happy to try implementing it if I had a little guidance, although it might be faster for someone else.

**Comment by jasongrout** [comment]
It sounds like possibly a small modification of https://github.com/jupyterlab/jupyterlab/tree/b16e635d4e7c6d39f27b7421e045238904066104/packages/vega3-extension? Perhaps a setting for the vega3 extension to use the webgl renderer or the canvas renderer?

**Comment by jasongrout** [comment]
It looks to me like you add the npm package to the package.json as a dependency. I'm not sure how to tell vega to use the webgl version, though perhaps if you import this function: https://github.com/vega/vega-webgl-renderer/blob/f81aa1c19b2840423bf1026b9ebd759144c305bb/src/WebGLRenderer.js#L10
and use it as a renderer in place of this renderer? https://github.com/jupyterlab/jupyterlab/blob/b16e635d4e7c6d39f27b7421e045238904066104/packages/vega3-extension/src/index.ts#L90

I'm not sure exactly how the vega project is architected, so that's just a guess.

**Comment by saulshanabrook** [comment]
This would be very cool. But how do you plan on rendering vega on webgl? Are you planning on using this project https://github.com/vega/vega-webgl-renderer ? It looks like it hasn't been updated in a while, so I doubt it will be compatible with the latest vega version that altair now defaults to.

**Comment by jamestwebber** [comment]
That was the hope. The linked repo was built for the at-the-time-beta Vega 3.0, so it _might_ work unless 3.0 changed a lot since then.

Fair warning: this is on my list of fun things to try while on vacation so I give it a 10% shot of happening.

**Comment by saulshanabrook** [comment]
Cool, well it seems like an interesting approach. It seems like using the webgl renderer could be integrated at the `vega-embed` layer, since it looks like that is what we are using to actually doing the rendering. @domoritz might be the right person to help with that part.

**Comment by domoritz** [comment]
The renderer can be changed through Vega-Embed (passing `{renderer: 'svg'}` as options) and we have added support for passing options in ipyvega (https://github.com/vega/ipyvega/blob/master/vega/base.py#L22). This way switching the renderer is easy. Right now, the default renderers that come with Vega are `svg` and `canvas`. The experimental webgl renderer you are referring to is not ready for production yet! I also doubt that it will be anytime soon as our team (Vega team) is not working on it. I personally think that the biggest performance bottleneck right now is not the rendering (although interactive performance would be much better with webgl if someone wants to finish the renderer) but loading data into the browser. 

I'd suggest to close this issue here until the webgl renderer is ready. If I remember correctly, the main issue was support for text. A viable solution could be to render text separate from the other content but someone needs to look into the webgl renderer code (and probably update some more things).

**Comment by saulshanabrook** [comment]
Closing this since I don't think we need to do anything on the jupyterlab side if we wanted to move forward on this type of integration.

**Comment by jamestwebber** [comment]
For my use case, rendering really is the bottleneck because I'm running a local notebook and client == server. I think WebGL would be a big win for the [Altair](https://github.com/altair-viz/altair) library etc, at least for the initial coding and data exploration–right now they limit the amount of data primarily (I think) because of the rendering cost.

But if the webgl renderer is not ready for use that seems like a big blocker.

**Comment by saulshanabrook** [comment]
@jamestwebber even in the case where you are running locally, the data can be prohibitively big for your browser. I am not sure about your specific use case, but my browser has crashed before when trying to load big datasets, although [altair's built in support for outputting json/csv](https://altair-viz.github.io/user_guide/faq.html#passing-data-by-url) helps a bit. Have you tried that?

**Comment by domoritz** [comment]
> @saulshanabrook saulshanabrook: This is off topic, but do you have thoughts on the best way to proceed on that front? Like doing some/all of the computation server side maybe? Are there projects taking that approach for vega (lite) rendering?

I am planning to work on pushing some computation into the kernel/pandas over the summer. 

> @jamestwebber: For my use case, rendering really is the bottleneck because I'm running a local notebook and client == server. I think WebGL would be a big win for the Altair library etc, at least for the initial coding and data exploration–right now they limit the amount of data primarily (I think) because of the rendering cost.

I completely agree that a webgl renderer would be a huge win and our team will support anyone who wants to dig into it as much as we can. Unfortunately, we don't have the resources to do it ourselves right now.

**Comment by jamestwebber** [comment]
@saulshanabrook I hadn't tried that before, it definitely helps speed things up! I imagine interactivity would still be slow but that's not a big issue.

@domoritz Totally understand that it's not a priority. I'll try to play around with it and if I have questions I'll ask in whatever forum seems appropriate.
