### ISSUE TITLE
Inconsistent font size of codeblocks in titles of markdown documents.

### ISSUE THREAD

**Issue by qria** [jupyterlab/jupyterlab#4609]
Font size of codeblocks of jupyterlab is inconsistent with jupyter notebook.

In jupyter notebook the font size of codeblock matched the title size, however jupyterlab does not.

Here's the following markdown rendered in both jupyterlab and jupyter notebook.

```markdown
# Hello `Codeblock`!
## Hello `Codeblock`!
### Hello `Codeblock`!
#### Hello `Codeblock`!
##### Hello `Codeblock`!
```

<img width="720" alt="jupyterlab_codeblock" src="https://user-images.githubusercontent.com/4233072/40281513-f5b45c6a-5c9d-11e8-879c-4ab7f7e7ded2.png">

<img width="403" alt="jupyter_notebook_codeblock" src="https://user-images.githubusercontent.com/4233072/40281514-f5df957e-5c9d-11e8-8ff1-716718ac0c75.png">

Jupyter versions 

```
jupyter==1.0.0
jupyter-client==5.0.0
jupyter-console==5.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.3.3
jupyter-core==4.3.0
jupyter-highlight-selected-word==0.1.0
jupyter-latex-envs==1.4.1
jupyter-nbextensions-configurator==0.2.8
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
```

**Comment by jirivrany** [comment]
Hi, 
I would like to help with this, but I'm not sure which CSS file should be edited. Is it [this one](https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/style/index.css)?

**Comment by jasongrout** [comment]
That looks like the right one to me. Does it work?

**Comment by jasongrout** [comment]
Do you see why the font size is smaller? Is it that there is some `<code>` css accidentally overriding things?

**Comment by jirivrany** [comment]
I'm not that far yet. Right now I'm trying to figure out how the markdown is rendered. DevTools in Chrome are not useful, because render output is not just simple html element. Any suggestion what to read for getting started?

**Comment by jasongrout** [comment]
Great question - it can be a bit tricky. The markdown cells render their content here: https://github.com/jupyterlab/jupyterlab/blob/e377acd19b1bb13dfd76d65d2e7210938e273ec0/packages/cells/src/widget.ts#L903

Basically, it constructs a markdown mime message (just like if it was a markdown display type in an output), and then asks the markdown renderer to render it. The actual renderer is here: https://github.com/jupyterlab/jupyterlab/blob/e377acd19b1bb13dfd76d65d2e7210938e273ec0/packages/rendermime/src/renderers.ts#L301

That's why that package's CSS style is the one used for the markdown: https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/style/index.css

However, I wonder if the real problem is that some *other* package's css styling is being misapplied here. That's my question about if it seems that the fontsize is coming from some other overly-broad css somewhere.

**Comment by jirivrany** [comment]
It looks like, that the final rule applied to <code> is the .jp-RenderedHTMLCommon pre, .jp-RenderedHTMLCommon code class. And the font-size value is font-size: var(--jp-code-font-size); 

The value for h1 is not applied, probably because the selector for code is more specific. 
![screen](https://user-images.githubusercontent.com/2290566/40328240-fbd3fb5c-5d45-11e8-8043-63d677875c24.jpg)

**Comment by jasongrout** [comment]
So one way to do it is to override font-size for code in the headings with a more specific selector: `.jp-RenderedHTMLCommon h1 code  { font-size: unset; }`? Similarly for h2, h3, etc.?

**Comment by jirivrany** [comment]
I agree that is probably the easiest way.
