### ISSUE TITLE
OutputGutter needs drag indicator UX love

### ISSUE THREAD

**Issue by sccolbert** [jupyterlab/jupyterlab#462]
cf  #424

We need some UX to indicate the output gutter is draggable.

cc @danielballan @blink1073 @ellisonbg

**Comment by danielballan** [comment]
Should it be styled with a "copy" cursor on hover? Or with grab, and then copy once the drag has begun?

One issue: it seems Safari does not support that cursor yet.

http://www.w3schools.com/cssref/pr_class_cursor.asp

**Comment by SylvainCorlay** [comment]
A hand cursor?

**Comment by danielballan** [comment]
I thought "copy" might more precisely suggest the behavior of mirroring. A hand cursor might wrongly suggest that dragging rearranges the order of the cells.

**Comment by SylvainCorlay** [comment]
The open hand cursor can be on hover, and another used when dragging...

Showing that this applies to the whole ouput by changing its background
color on hover of the gutter (except when already holding another output)
could help understand what os going on.

On Sep 25, 2016 6:18 PM, "Dan Allan" <notifications@github.com> wrote:

I thought "copy" might more precisely suggest the behavior of mirroring. A
hand cursor might wrongly suggest that dragging rearranges the order of the
cells.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jupyter/jupyterlab/issues/462#issuecomment-249450268>,
or mute the thread

**Comment by danielballan** [comment]
Great, that is what I meant to suggest but explained poorly. ;- ) I think we are on the same page.

I like your suggestion of changing the background color. Maybe we should change it on mouse-down (instead of on hover) so it is less distracting as the mouse moves over the notebook.

**Comment by ellisonbg** [comment]
@SylvainCorlay did add some styling of this, do we need more?

**Comment by ellisonbg** [comment]
Not relevant anymore, closing (output gutter isn't draggable).
