### ISSUE TITLE
Mirrored output needs a discriminated title.

### ISSUE THREAD

**Issue by sccolbert** [jupyterlab/jupyterlab#464]
cf #424 

Currently, mirrored output panes all have the same title: `'Mirrored Output'`. We probably want to come up with a way to discriminate these and make them more specific.

cc @danielballan @ellisonbg @blink1073

**Comment by danielballan** [comment]
I agree, but it's not obvious what they should be. The notebook name + cell number? That's not completely unique (notebooks at different paths with the same filename...) but might be good enough.

**Comment by jasongrout** [comment]
@danielballan - that would be a huge improvement, even if it's not perfect.

**Comment by danielballan** [comment]
To be clear, I am thinking we should display the cell number, meaning the cell's index in the `'cells'` list in the notebook document. This would have to be updated whenever another cell is inserted into the document above the mirrored cell. Alternatively, we could show the prompt number. I think I prefer the cell number because it (correctly) suggests that the pane shows the current state of a cell, not a frozen snapshot of a specific output. But I could see the argument for showing the prompt number, since that number is shown to the user.

Are we on the same page?

**Comment by jasongrout** [comment]
The prompt number is also updated when the cell is re-evaluated, and is intrinsic to the cell, so it would be probably easier to get to from a widget just having the cell, so +1 for the prompt number...

**Comment by ellisonbg** [comment]
Closing as no longer relevant (output alone is not mirrored).
