### ISSUE TITLE
can i use jupyter to connect to a server via ssh?

### ISSUE THREAD

**Issue by isalirezag** [jupyterlab/jupyterlab#4722]
So lets say i want to connect to a server. in terminal i go and write `ssh aaa@bbb -p 0000` and then i type my password and connect to my server.

Can i do it in the jupyter?

I can type `! ssh aaa@bbb -p 0000` and it then ask me to type my password, but the problem is i dont know where to type my passport... if i type it in the next cell it does not work...

**Comment by jtpio** [comment]
If you use JupyterLab you can open a new terminal by following these instructions:
http://jupyterlab.readthedocs.io/en/stable/user/terminal.html

**Comment by isalirezag** [comment]
yeah but it isnot what i asked.
I wanna know how it can be done in notebook...

**Comment by jasongrout** [comment]
I don't think this is possible right now (executing a shell command that expects input). Does it work in the classic Jupyter notebook?

**Comment by isalirezag** [comment]
nope it doesnot work in jupyter notebook either

**Comment by afshin** [comment]
If you use SSH keys to log in (i.e. you can log in without interactive input) then you can run that command, but otherwise, you cannot currently log in interactively.

<img width="852" alt="screen shot 2018-06-20 at 14 54 30" src="https://user-images.githubusercontent.com/159529/41662948-2c691962-749a-11e8-9451-d3730bcb74b9.png">

**Comment by jasongrout** [comment]
Closing as answered, but feel free to continue posting here if you still have questions about this.
