### ISSUE TITLE
Feature Request: Adding a new language mode into CodeMirror via extensions

### ISSUE THREAD

**Issue by ruslanrf** [jupyterlab/jupyterlab#4754]
It would be very useful to have a possibility dynamically attach a new language mode for a specific MIME type into Jupyter Lab.

For example, given a new kernel which can evaluate a specific language, to be able to define syntax highlighting for the corresponding code cell in a Jupyter Lab extension.

**Comment by bollwyvl** [comment]
This works today, here's an example!

https://github.com/PhE/jupyterlab_graphviz/blob/master/src/mode.ts

Called here:

https://github.com/PhE/jupyterlab_graphviz/blob/master/src/index.ts#L19

It's doing it in a crazy place, sure, and should wait until the extension
is activated, but it works fine.

There are examples in core that do it more cleanly, but it's all
codemirror.defineMode().

I'm a really big fan of the simpleMode add-on, as you don't have to mess
about with stands and such, but it is limiting in a number of ways.

We have talked about setting up a jupyterlab/syntaxes monorepo that would
make managing this easier, as the old path of submitting directly to cm is
now closed, and we need some way for novel language kernels to manage this.

The idea would be to have the mode itself be a package (not happening above
:p), so that other projects can use it, and then have minimal boilerplate
extensions. Pygments, used by nbconvert, is still new taking modes, so a
new kernel would also want to get into that community.

**Comment by ruslanrf** [comment]
Thank you.
