### ISSUE TITLE
Vim key bindings: autocomment

### ISSUE THREAD

**Issue by tmaric** [jupyterlab/jupyterlab#4782]
I have 0 idea how the vim key bindings in the editor are implemented, so excuse my probably stupid question. 

Would it be possible to get the functionality of the [nerdcommenter](https://github.com/scrooloose/nerdcommenter) the text editor with vim key bindings? 

As a vim user, that's one of the things I find the editor would really benefit from. I've used the vim plugin for the jupyter notebook and it seemed to have "picked up" all the vim plugins I have installed on my system.

**Comment by ian-r-rose** [comment]
Hi @tmaric, the vim keybindings are a reimplementation of (a subset of) vim in CodeMirror (the browser-based text editor we use). Since it is a completely separate implementation, essentially no vim plugins will work.

As a workaround, if you have vim installed on your system with plugins that you like, you can always open a terminal and launch it from there.

**Comment by tmaric** [comment]
@ian-r-rose OK, thanks!

**Comment by jasongrout** [comment]
Closing as answered.
