### ISSUE TITLE
Move Extension Manager handler into jupyterlab_launcher

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#4819]
The other server extensions are in `jupyterlab_launcher`, the extension manager probably should be as well.

**Comment by vidartf** [comment]
I didn't realize this split. Makes sense!

**Comment by vidartf** [comment]
That being said, note that the extension manager handler has a dependency on two methods on the "private" `_AppHandler` class. Maybe those should get wrapper functions similar to the other functions?

**Comment by jasongrout** [comment]
I'd be okay bumping the decision to 0.34, since it's mainly a code refactoring change. 

It may make a lot of sense to keep the handler in jupyterlab. The idea of jupyterlab_launcher is to be a base people can build on, but we've explicitly made the runtime extension installing infrastructure part of jupyterlab, not jupyterlab_launcher. The idea there was that people building on jupyterlab_launcher would have a single curated list of extensions they would be bundling at packaging time, and would not allow extra extensions to be installed at runtime.

**Comment by ian-r-rose** [comment]
For people building on `jupyterlab_launcher`, is there an obvious way to *not* enable the runtime extension installation via this machinery?

**Comment by ian-r-rose** [comment]
(Bumping to 0.34)

**Comment by blink1073** [comment]
I agree that the extension manager is too heavily tied to the core to be extracted.

**Comment by ian-r-rose** [comment]
Okay, I'll close this unless there is some bright idea of how to get it working.
