### ISSUE TITLE
Autocompletion of local tokens in notebook cells

### ISSUE THREAD

**Issue by claresloggett** [jupyterlab/jupyterlab#4876]
In Jupyter Notebook, pressing TAB will autocomplete: 

* any variable name in the current namespace
* any variable name in the current cell, even if the cell hasn't yet been executed

Jupyterlab currently does the first of these but not the second. The second would be very nice to have!

**Comment by afshin** [comment]
@claresloggett If you are curious and want to work on this issue, here are some hints. I hope you find them helpful.

* Since only one completer ever appears on the screen, there is a completion manager (which can be required by an extension by requiring the token `ICompletionManager`) that handles the creation and disposal of completer widgets. (*cf.* https://github.com/jupyterlab/jupyterlab/blob/master/packages/completer-extension/src/index.ts#L75-L107)
* The manager allows new widgets that support completion (basically code consoles and notebooks only right now) to register a new handler that mediates  switching cells (by setting its `editor` attribute) etc. and also makes requests to populate the completer.
* An `IDataConnector` instance is created (*e.g.*, the `KernelConnector` here: https://github.com/jupyterlab/jupyterlab/blob/master/packages/completer-extension/src/index.ts#L130-L131) and it makes the actual requests to the kernel when a new completion request comes in.
* You can see the `KernelConnector` implementation here: https://github.com/jupyterlab/jupyterlab/blob/master/packages/completer/src/kernelconnector.ts It is pretty straightforward.
* So if you wanted to support *both* the kernel's completion responses and a local tokenizer's list of tokens, you could either sub-class `KernelConnector` and do some extra work in the `fetch()` method, or you could compose a new class that takes a `KernelConnector` and uses that internally in its own `fetch()` method.
* The completion manager doesn't care what sort of `connector` you `register()` with it, as long as it matches the interface: `IDataConnector<CompletionHandler.IReply, void, CompletionHandler.IRequest>`. You can see from the `KernelConnector` that the `save()` and `remove()` methods of `IDataConnector` are basically no-ops.

If you decide to take on this task, please open a PR early in your process so that there's a spot where discussion about the issue can happen. You don't need to wait until it is ready to go to make the PR. We typically have "work in progress" PRs open.

**Comment by afshin** [comment]
Also, there is a utility class called `DataConnector` (https://github.com/jupyterlab/jupyterlab/blob/master/packages/coreutils/src/dataconnector.ts) that `KernelConnector` inherits from. It doesn't do much except give you stubs for the data connector interface's required methods.

**Comment by ian-r-rose** [comment]
Fixed by #5049

**Comment by mwcraig** [comment]
Thanks @ian-r-rose!
