### ISSUE TITLE
Terminal cursor should be hidden if the terminal does not have focus

### ISSUE THREAD

**Issue by sccolbert** [jupyterlab/jupyterlab#496]
Even if some other input field has focus, the terminal cursor will still blink. This makes it _appear_ that the terminal has focus, when in fact it does not. We should disable/hide terminal cursors unless the terminal actually has input focus.

**Comment by ellisonbg** [comment]
@roshancvp any update on this?

**Comment by roshancvp** [comment]
@ellisonbg still working on this.

**Comment by blink1073** [comment]
After #2297, it looks like this when not focused (no blinking):

<image src="https://cloud.githubusercontent.com/assets/2096628/26493433/2d11fb20-41df-11e7-8e1e-e7c304fe6479.png" width=200>

<image src="https://cloud.githubusercontent.com/assets/2096628/26493440/36eca834-41df-11e7-84f3-fc20c1538339.png" width=200>

Are those outlines intentional, @ellisonbg?

**Comment by ellisonbg** [comment]
In the default dark theme of xterm.js the outlines are then when it is not focused. I am guessing that they got this design from other terminals. The default terminal on Mac does this. For the light theme I simply inverted the design. Here is the look on a Mac:

<img width="758" alt="screen shot 2017-05-27 at 9 16 51 pm" src="https://cloud.githubusercontent.com/assets/27600/26526066/d6faaef0-4321-11e7-8fd6-5258dc552be4.png">

**Comment by blink1073** [comment]
Fair enough, closing this as fixed then.
