### ISSUE TITLE
Workspace creation redirects to wrong URL with jupyterhub

### ISSUE THREAD

**Issue by liffiton** [jupyterlab/jupyterlab#5002]
The "Please use a different workspace" prompt redirects me to an incorrect URL that results in a 404.  I believe this may be related to running jupyterlab under jupyterhub.

If I copy my standard jupyterlab URL:

```
https://<HOST>/user/<USERNAME>/lab
```

into a new browser tab, I get the "Please use a different workspace" prompt.  If I enter a name like "work," I get redirected to:

```
https://<HOST>/hub/lab/workspaces/work
```

This URL is a 404.

From the [workspace documentation](https://jupyterlab.readthedocs.io/en/stable/user/urls.html), the correct URL appears to be:

```
https://<HOST>/user/<USERNAME>/lab/workspaces/work
```

Entering that URL manually seems to work.

Versions:

```
# jupyter --version
4.4.0
# jupyterhub --version
0.9.1
# jupyter lab --version
0.33.4
```

**Comment by exowanderer** [comment]
I had this same issue, and several others. I turned out that I had (via Chrome) "block all cookies".  After I changed that, the Jupyter notebooks started working again. 

Between identifying the problem and finding the solution (cookies) was about 5 minutes. Albeit, I did not turn off cookie blocking *for* the Jupyter notebooks.
