### ISSUE TITLE
What are the paths given by `jupyter lab path`?

### ISSUE THREAD

**Issue by krinsman** [jupyterlab/jupyterlab#5045]
Running in the terminal `jupyter lab path`, one gets output similar to the following:

```
Application directory:   /opt/miniconda/share/jupyter/lab
User Settings directory: /user_directory/.jupyter/lab/user-settings
Workspaces directory /user_directory/.jupyter/lab/workspaces
```

I was hoping to find somewhere in the docs a brief mention/explanation of what is meant by each of these three terms, "Application directory", "User Settings directory", and "Working directory". 

It is probably there somewhere (I am bad at Google searches), in which case a pointer to the location would be extremely appreciated.

For example, what would happen if those directories were changed or deleted, or if it is possible to set the values of the directories to be somewhere different, and how they are determined in the first place.

What I am looking for is similar to [the Jupyter page for](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html) the "Config directory", "Data directory", and "Runtime directory" in the Jupyter notebook documentation.

**Comment by blink1073** [comment]
Hi @krinsman, the docs for `Application Directory` are [here](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/extensions.rst#jupyterlab-application-directory).  We do not however have explicit docs for the other two directories.

**Comment by blink1073** [comment]
A quick breakdown of them:

- The User Settings directory is in the default Jupyter configuration [location](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#configuration-files).  It is created dynamically when you change things in the front end that affect settings, but can also be manually edited if desired.
- The Workspaces directory is also created dynamically as needed and is also in the default Jupyter config location.  A workspace file is a named file that contains the information needed to restore a JupyterLab session (what was open, and how everything was laid out).  The files are created as you browse to workspace urls.  Docs on workspaces are [here](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/urls.rst#managing-workspaces).

**Comment by blink1073** [comment]
Note that the workspace file is automatically updated as you open/close widgets and change their sizes/location.

**Comment by blink1073** [comment]
We should also explain [here](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/extensions.rst#advanced-usage) *why* we use a different directory than Jupyter [Data Files](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#data-files).  The explanation is:

 The default Jupyter data files location does not differentiate between a system install and a virtual environment install.  In a system install, we want the user location to take precedence over the system location.  In a virtual environment, we want the sys-prefix location to precede the user-level location, since a user can have multiple virtual environments.  In the case of a `pip --user` install, we use pip's [user install](https://pip.pypa.io/en/stable/user_guide/#user-installs) location, since the system location might not be writable (`sudo` might be required).  We need it to be writable for when the user installs new extensions.

**Comment by blink1073** [comment]
I just realized that the above is not quite correct.  The default application directory mirrors the behavior of [data files](https://docs.python.org/2/distutils/setupscript.html#installing-additional-files) in Python.  It is where the static assets are populated when the `jupyterlab` package is installed.  We choose that location as a default location to also install extensions because it is guaranteed to be scoped by virtual environment and is also writable by the user that installed `jupyterlab`.

**Comment by krinsman** [comment]
@blink1073 **1.** You said that the application directory is the location where packages that ship `jupyterlab` extensions as tarballs can be automatically installed by adding files there, right?

So if one wanted to make a conda package from the GitHub repository of a JupyterLab extension, should the build script copy the contents of the repository to the application directory before running `npm install; npm run build; jupyter labextension link .`?

**2.** If I were to eventually get around to making a PR to include the above info in the docs (I can't promise that I will actually have the time to do this), which documentation file should this information go in? The same document where the information about the application directory is?

**Comment by blink1073** [comment]
1.  The python package would add the tarballed npm package using data_files under share/jupyter/lab/extension.  The conda build also picks up this file. When the user installs the conda package, that one file is populated.  Then the user can either run "jupyter lab build", or they will be prompted for an auto-build the next time they launch JupyterLab.  Here is an [example](https://github.com/matplotlib/jupyter-matplotlib/blob/3d43a36443886a9aa1492530e776f8f531c8c3bf/setup.py#L73). 

2.  I think maybe a new top level page under user documentation about the config and directory structure.

**Comment by saulshanabrook** [comment]
We have some documentation now on paths [on the Extensions page](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#advanced-usage), so we could add this explenation there or consolidate the path documentation to another place.

**Comment by krinsman** [comment]
@saulshanabrook That sounds like a good idea. I'll leave this issue open so you can close it when you feel like the documentation has been improved enough to make it irrelevant.

**Comment by jasongrout** [comment]
@krinsman, if you feel like you understand it now, would you like to submit a PR to kick-start the process?

**Comment by krinsman** [comment]
@jasongrout To be honest I don't feel like I actually understand it now -- I haven't been working on anything JupyterLab related recently enough. I'm sorry about this.

**Comment by jasongrout** [comment]
No problem, thanks for considering it. We're happy to answer any more questions you might have, and we can leave this issue open for someone else to write up, based on their understanding and the discussion above.
