### ISSUE TITLE
save widget state in Jupyter Lab

### ISSUE THREAD

**Issue by cornhundred** [jupyterlab/jupyterlab#5235]
How can we save widget state in the notebook using Jupyter Lab? In notebooks I see the `Widgets` menu and `Save Notebook Widget State` option in the traditional notebook, but I do not see the same in Jupyter Lab.

**Comment by bollwyvl** [comment]
@maartenbreddels hacked this up at the JupyterCon Open Studio Sprint Day:
https://github.com/maartenbreddels/jupyterlab-supersave/blob/master/src/index.ts#L85

Through some gnarly hacks on both the widget side (to get access to the manager/state) and the services side (:speak_no_evil: patching `toJSON`), we technically proved that _saving_ is possible, though haven't yet handled the flipside of instantiating the widgets on load, even in a hacky way.

I missed a broader discussion with @jasongrout and others around the saving lifecycle, and how a more general, predictable approach to What Happens When We save, e.g. Outputs, collapsed state, and a raft of other things we can't even imagine yet. Stay tuned!

**Comment by cornhundred** [comment]
Thanks for the info.

**Comment by maartenbreddels** [comment]
Apart from saving the widget state, the jupyter lab widget manager also needs to be able to restore the widgets from their state. I am not sure if there is an open issue on this on the ipywidgets repo or not.

I think we quick way forwards is to get the widget restore feature in the widget manager for lab, while at the same time thinking about how we deal with controlling we control what gets stored in the notebook upon saving it, until this is figured out we could use my extension (I recommend making a shortcut key for it).

**Comment by jasongrout** [comment]
@vidartf mentions widget restore at https://github.com/jupyter-widgets/ipywidgets/issues/1005#issuecomment-351992277. I can't find an issue specifically for it, though.

**Comment by jasongrout** [comment]
cf also the save design mentioned at https://github.com/jupyterlab/jupyterlab/issues/5200

**Comment by vidartf** [comment]
@jasongrout That comment was basically saying that the task can be split into two (consecutive) steps:
1. Write logic for restoring widgets from saved state and from live state in kernel, after the pattern for the nbextension. This should then be able to load state saved previously from classic notebook.
2. Write logic for saving / clearing state, that can be triggered from the UI.

**Comment by saulshanabrook** [comment]
I think this could use the `persist-and-save` command that is currently just implemented in the notebook for saving the collapsed/scrolled state of output cells.

**Comment by jasongrout** [comment]
This could also be related to a more general framework for saving extra data sketched in #5200.

**Comment by ian-r-rose** [comment]
@jasongrout is this resovled by #5968?

**Comment by jasongrout** [comment]
Yes, and any further issues on it should be opened in the ipywidgets repo too.
