### ISSUE TITLE
Leaking server paths to the browser

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5313]
We are leaking a number of server paths to the browser: https://github.com/jupyterlab/jupyterlab/blob/68a000b96176fc3851cff026fe299269995428a7/packages/application/src/index.ts#L456-L465

I think those paths are strictly a server implementation detail, and should not be exposed to the browser.

**Comment by blink1073** [comment]
Counterpoint: https://github.com/jupyter/notebook/blob/86e473e754302705dba6721e30ed81b03c9774d3/notebook/templates/tree.html#L11

**Comment by jasongrout** [comment]
@minrk, @takluyver - do you know why the notebook exposes the server root path to the notebook?

The only place I see serverRoot being used is https://github.com/jupyter/notebook/blob/0da9648ed3b2bb030c372a3a189f72cbe5ad010e/notebook/static/tree/js/notebooklist.js#L1044

**Comment by jasongrout** [comment]
@blink1073 - one other note - that server root is exposed to the tree page, not the notebook page. Notebooks don't have access to the server path, it seems, in the classic notebook.

**Comment by blink1073** [comment]
Here is one of the requests for server root: https://github.com/jupyterlab/jupyterlab/issues/5273

**Comment by minrk** [comment]
A few things about the use in the notebook:

1. it's not really an information leak, since kernels can do arbitrary things on the filesystem already
2. it's not used in logic in any way, and probably shouldn't be. It would be just as valid for this string to be "my-s3-stuff" or "I'm not telling you" or anything else for non-local notebook file storage, without any loss in functionality.

So it should be fine to expose some of these things like is done in the tree page for UI *hints only* (e.g. `"You can look at your workspaces in $workspaceDir"`), but filesystem paths should never be involved in APIs.

**Comment by jasongrout** [comment]
>     1. it's not really an information leak, since kernels can do arbitrary things on the filesystem already

Assuming the kernel is on the filesystem

> filesystem paths should never be involved in APIs.

Since we don't have any places where these paths are used in JLab, I think we should go ahead and remove them and only add back what we really need.
