### ISSUE TITLE
It takes a long time to load a slightly larger notebook, and it takes a long time to switch between large notebooks.

### ISSUE THREAD

**Issue by 935048000** [jupyterlab/jupyterlab#5457]
The problem is described in the title.

It takes too long to load a large notebook, which is not conducive to rapid development and debug

It takes 1 minute to turn on the 1.14Mb notebook and 14 seconds to switch back from the other notebook. This response time is not acceptable.

**Comment by jasongrout** [comment]
Thanks. We're tracking this at #1639 and #2639, let's move the discussion over there. If you can post an example notebook to benchmark against, that would be helpful, or at least posting how many cells your notebook has (the time seems proportional to number of cells, rather than raw size). Any other help you could give towards investigating this issue or contributing code would be great - we all want it to be faster!
