### ISSUE TITLE
How to extend DocumentManager of JupyterLab

### ISSUE THREAD

**Issue by commandlinegirl** [jupyterlab/jupyterlab#5467]
I would like to add my own custom behavior (server-side) to the closing tab(s) operation, so I think I should extend this method `closeFile()` of the `DocumentManager` https://github.com/jupyterlab/jupyterlab/blob/master/packages/docmanager/src/manager.ts#L177.

I have a custom file browser plugin (extension) that works well if I use it with JupyterLab's core IDocumentManager but not if I use it with the extended/overwritten IMyDocumentManager like here:

```
    const browserPlugin: JupyterLabPlugin<void> = {
      id: "my:fs",
      requires: [IMyDocumentManager, ISettingRegistry, IMainMenu],
      activate: activateMyBrowser,
      autoStart: true
    };
```

My `IMyDocumentManager` looks like this:

```
    import { IDocumentManager, DocumentManager } from '@jupyterlab/docmanager';
    import { Token } from '@phosphor/coreutils';
    
    export interface IMyDocumentManager extends IDocumentManager {}
    
    export const IMyDocumentManager = new Token<IMyDocumentManager ('@jupyterlab/docmanager:IDocumentManager'); 
     
    export class MyDocumentManager extends DocumentManager implements IMyDocumentManager {
       closeFile(path: string): Promise<void> {
        console.log("Test override a method for closing: " + path);
        return super.closeFile(path);
      }
     }
```

When I load JupyterLab in the browser I get the error:

<img width="541" alt="screen shot 2018-10-09 at 4 32 40 pm" src="https://user-images.githubusercontent.com/2283292/46705114-f6e43b00-cbe2-11e8-93e4-10a8c2cde85d.png">

It's probably because I have to define the Token differently. Instead of `new Token<IMyDocumentManager ('@jupyterlab/docmanager:IDocumentManager')` I should use some other string than `'@jupyterlab/docmanager:IDocumentManager'` but I don't really know what. I tried `IMyDocumentManager` but I get the same error.

How to create a Token for my simple extended class?

Maybe there is an easier way to overwrite closing tab behavior? Thank you!

**Comment by ian-r-rose** [comment]
Hi @commandlinegirl, interesting! In general, the application assumes that there is only a single document manager, so I think your best way forwards is to replace the application document manager with your own. So instead of using your own token, you will want to write a plugin that provides the regular `IDocumentManager` token, which will then be used all over the application. So the plugin might look something like:
```typescript
    const myDocManagerPlugin: JupyterLabPlugin<IDocumentManager> = {
      id: "my:fs",
      requires: [],
      provides: IDocumentManager,
      activate: activateMyDocManager,
      autoStart: true
    };
```
Then, when your custom filebrowser plugin requests the `IDocumentManager` (not `IMyDocumentManager`), it will get the one that you provided, rather than the default application one.

That being said, if you are looking to do some extra operations (possibly with a server side component), you may be able to get away with using the default Document Manager. Widgets emit a `disposed` signal when they are closed, and you could attach a callback to that. You could also add a message hook to the intercept close messages to a widget and possibly do some extra work (an example of this is in the `DocumentWidgetManager`).

If either of those are enough to accomplish your goals, it may be simpler than overriding the application document manager.

**Comment by commandlinegirl** [comment]
Thank you so much @ian-r-rose! Very interesting to learn! I was trying to create a proper extension of the document manager but was not providing the default `IDocumentManager` properly, so that's a very helpful general note! I'll definitely look into `DocumentWidgetManager` example and the callback. Thanks!

**Comment by commandlinegirl** [comment]
I'm thinking about the `activate` function in the doc manager plugin. This is here where I should initialize the DocumentManager, override the file closing method, and return it, is that right? In that case it'll be similar to [what is done in `docmanager-extension`](https://github.com/jupyterlab/jupyterlab/blob/ec061435789d0db3b269d7e5f201402435ccc3f7/packages/docmanager-extension/src/index.ts#L97) - won't my extension and docmanager-extension interfere?

**Comment by ian-r-rose** [comment]
Yes, if you override the docmanager-extension with your own implementation, they will interfere (and all of the stuff that the docmanager-extension does would need to be re-implemented). That is why it may be simpler to write a plugin that *requests* the application docmanager, and does extra work on it's document widgets, rather than providing your own.

**Comment by commandlinegirl** [comment]
I see, I'd like to replace the application document manager with my own, as per one of your suggestions above, but was not sure what to do in  the `activateMyDocManager` method. Thank you for your help with this!

**Comment by commandlinegirl** [comment]
A couple of notes to wrap this up:

I connected a callback to the `disposed` signal that is emitted when my widget is closed, like this:

```
widget.disposed.connect(this._onWidgetDisposed, this);
```

The callback:

```
  private _onWidgetDisposed(widget: IDocumentWidget): void {
    // Send an HTTP request to the backend using custom
    // implementation is "fileApi" 
    this.fileApi.doSomethingWithFile(widget.context.path);
  }
```

More information on signals:
https://jupyterlab.readthedocs.io/en/stable/developer/patterns.html?highlight=signal#signals

This phosphor code, incl comments, is very helpful:
https://github.com/phosphorjs/phosphor/blob/cdb412e9dfb9a987b99143e4be79d477e5136832/packages/signaling/src/index.ts#L37

HTH to anyone.

**Comment by ian-r-rose** [comment]
Thanks for the update!
