### ISSUE TITLE
Transform css variables into plain values for production

### ISSUE THREAD

**Issue by futurist** [jupyterlab/jupyterlab#5480]
Transform css variables into plain values when `jlpm build`, to make it more compatible, can use like [postcss-extract-value](https://github.com/lutien/postcss-extract-value) etc. tools.

**Describe the bug**

I'm also faced the problem https://github.com/jupyterlab/jupyterlab/issues/4852 and some browser lack `css-variables` supports.

**Expected behavior**
The css variables is good but can be safely transformed using a toolchain like [postcss-extract-value](https://github.com/lutien/postcss-extract-value) or similar, for the **production building output**

Below can also be in the list:

[postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [IE, Edge<16, Edge 15 is buggy]
- JupyterLab [0.35]

**Comment by jasongrout** [comment]
Thanks. CSS variables are an integral part of our theming. As noted in https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#supported-browsers, we don't support Edge precisely because it doesn't support CSS variables. Like you, we point out that "A tool like postcss can be used to convert the CSS files in the jupyterlab/build directory manually if desired."

Would you like to work on instructions for how to post-process the CSS for people that need to support Edge? I think that would make a great addition to that paragraph about browser support.

Does Edge >= 16 support CSS variables? If so, that's wonderful news!

**Comment by jasongrout** [comment]
(labeling as future and docs, for instructions for how to post-process the build directory with something like postcss.)

**Comment by jasongrout** [comment]
From https://caniuse.com/#feat=css-variables, it appears that Edge 17 and 18 (released this year) support CSS variables. That's wonderful! Perhaps we can add Edge 17 and 18 to the supported browser list (someone should test it first, of course).

**Comment by futurist** [comment]
@jasongrout That make sense, I'll find some time to find the best practice for this, and add a section in the docs.

**Comment by jasongrout** [comment]
Great, thanks!

**Comment by jasongrout** [comment]
In the institutional context, where extensions are not installed by users, basing the installation on the examples/app example probably makes more sense. In that case, it may be as easy as adding a few lines in the webpack config.
