### ISSUE TITLE
Link in documentation is not valid anymore.

### ISSUE THREAD

**Issue by bobmayuze** [jupyterlab/jupyterlab#5552]
On [file](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/extension_dev.rst)

In section `standard-extension-example`, the link to `how to extend the notebook plugin` is not valid anymore. I wonder if it is renamed to xkcd_extension_tutorial.rst

**Comment by bobmayuze** [comment]
Or that is the current available tutorial on how to develop an extension? https://jupyterlab.readthedocs.io/en/stable/developer/xkcd_extension_tutorial.html

**Comment by jasongrout** [comment]
The link seems to work for me: https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#standard-extension-example (goes to https://jupyterlab.readthedocs.io/en/stable/developer/notebook.html#how-to-extend-the-notebook-plugin)

**Comment by jasongrout** [comment]
That said, it looks like it is not using the standard RST linking syntax, so should be updated. Putting as a good first issue.

**Comment by russtoku** [comment]
I was trying to tackle this one but am not clear what the issue is.

The file link in the initial report points to the GitHub page for the RST source file for the **Extension Developer Guide** page. Viewing that page and then clicking on the link to **How to Extend the Notebook Plugin** returns a GitHub 404 error.

This appears to be a problem with viewing the page on GitHub because the link points to an HTML page (notebook.html). From the GitHub page of rendered RST source, it would be nice to be able to click on that link and see the rendered RST source file for the target link. In this case, it would be https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/notebook.rst.

@jasongrout Could you clarify your comment about the RST linking syntax?
