### ISSUE TITLE
Any new information on setting "Enable Scrolling for Outputs" as default?

### ISSUE THREAD

**Issue by realcodingmonster** [jupyterlab/jupyterlab#5563]
[#4028](https://github.com/jupyterlab/jupyterlab/issues/4028) As the thread points out, some users want the option 'enable scrolling for outputs' to be a default option for Jupyter Lab.

I am curious to know if anything is going on recently on this topic. I am using the latest version of Jupyter Lab at the moment, and since it does not have that default option, curious to know when it would be updated!! Thank you!

**Comment by jasongrout** [comment]
Thanks for asking. There's not any new information, besides the discussion on #4028. Let's keep the discussion on that issue so that it's easy to find all the relevant information there - new comments there can notify all participants in that discussion.

If someone would like to work on such an option, posting a comment on #4028 would be a good first step, and we can help them get started.
