### ISSUE TITLE
Excuse me, I want to add my own function in the function bar. What do I need to do? I used PIP intall jupyterlab to deploy the environment.

### ISSUE THREAD

**Issue by hq8399** [jupyterlab/jupyterlab#5573]
Excuse me, I want to add my own function in the function bar. What do I need to do? I used PIP intall jupyterlab to deploy the environment.

**Comment by ian-r-rose** [comment]
Hi @inspurodoo, please see [this](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html) extension developer guide.

**Comment by vidartf** [comment]
@inspurodoo There is a demo here: https://jupyterlab.readthedocs.io/en/stable/developer/xkcd_extension_tutorial.html#xkcd-extension-tutorial 

For that demo, everything before the section "Add an xkcd widget" should be the same for all kinds of extensions. After that, it depends on what kind of action you want to happen once your function is called. 

For menus, you want to require the `IMainMenu` object from `@jupyterlab/mainmenu`. To require it, put it in the `requires` field of your plugin definition. That is, use `IMainMenu ` instead of `IStateDB` here: https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#state-database . Then replace the `activate` function to make calls on the main menu object (API here: http://jupyterlab.github.io/jupyterlab/mainmenu/modules/imainmenu.html).
