### ISSUE TITLE
Height of isolated mimebundle output

### ISSUE THREAD

**Issue by flying-sheep** [jupyterlab/jupyterlab#5696]
When I display a mime bundle containing an entry of e.g. `text/html` with the metadata “isolated: true”, I get an iframe without height attribute/style, which results in a slim 150px high window.

Jupyterlab should infer the height for the iframe on `DOMContentReady` and once again at `load`.

**Comment by jasongrout** [comment]
Thanks. This sounds like an interesting project someone to play around with (maybe using `document.body.getBoundingClientRect()` in the iframe?). In general, I think it will be tricky since there are few DOM elements with a natural size, but I think it makes sense for us to try to get a better default experience at least.

**Comment by jasongrout** [comment]
For whoever wants to work on this, it looks like the relevant code is at https://github.com/jupyterlab/jupyterlab/blob/c3fff81d3f053c4f94e84263ae785eda56cb55aa/packages/outputarea/src/widget.ts#L391 and https://github.com/jupyterlab/jupyterlab/blob/c3fff81d3f053c4f94e84263ae785eda56cb55aa/packages/outputarea/src/widget.ts#L790-L851

**Comment by flying-sheep** [comment]
Hmm, it already has `iframe.style.height = body.scrollHeight`.

But many sites are isolated because they have some JS in there. Apparently the `load` event isn’t early enough…
