### ISSUE TITLE
Add fragment handler for CSVs

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#5720]
@AlbertHilb implemented a nice interface for handling URI fragments in documents in #5630. This already works for markdown, HTML, PDFs, and notebooks, but should also be possible for CSVs. This will allow people to link to specific rows in a CSV document.

Documentation for the CSV URI fragment format can be found [here](https://tools.ietf.org/html/rfc7111).
One would go to the CSV document widget and implement a `setFragment` function that scrolls the right row into view. This can be found here: https://github.com/jupyterlab/jupyterlab/blob/6185bda1b29967bfdcce3d320774e8534a51ac1c/packages/csvviewer/src/widget.ts#L353-L370
In particular, I think we will want to call `CSVViewer.goToLine()`.

An example of a document widget that handles a fragment can be found in the notebook: https://github.com/jupyterlab/jupyterlab/blob/6185bda1b29967bfdcce3d320774e8534a51ac1c/packages/notebook/src/widget.ts#L1163-L1172
https://github.com/jupyterlab/jupyterlab/blob/6185bda1b29967bfdcce3d320774e8534a51ac1c/packages/notebook/src/widget.ts#L1324-L1336

Marking as a good first issue.

**Comment by lheagy** [comment]
:wave: Hi @ian-r-rose, I am playing around with this and have a question for you. Within the CSVDocumentWidget, how do I access methods of the CSVViewer (`goToLine`). I initially thought it should be from `this.content`, but that doesn't seem right. 

I don't entirely understand how the inheritance is working:
https://github.com/jupyterlab/jupyterlab/blob/6185bda1b29967bfdcce3d320774e8534a51ac1c/packages/csvviewer/src/widget.ts#L333

Thanks!

**Comment by jasongrout** [comment]
What seems wrong about using`this.content`?

**Comment by ellisonbg** [comment]
Hi @lheagy - I am not too familiar with this part of the API, but my understanding as well is that `this.content` should work:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/docregistry/src/registry.ts#L1290

The only thing I can think of is that the `T` in the `IDocumentWidget` interface is a generic `Widget`, so you might need to cast `this.content` as a `CSVViewer` to access `goToLine`:

```typescript
(this.content as CSVViewer).goToLine();
```

The casting in typescript always trips me up...

**Comment by lheagy** [comment]
Thanks @jasongrout and @ellisonbg. I think I need to take a step back and get my mental-model of typescript calibrated. Do you have a good tutorial you could point me to for getting started? 

For example, I have a fairly basic question, I have created a simple `getFragment` method on the `CSVDocumentWidget` 

https://github.com/lheagy/jupyterlab/blob/csv-fragment/packages/csvviewer/src/widget.ts#L355-L357

When clicking on a URL from a notebook, I expected to just print the value of the fragment to the console (and then probably error), but I don't see the value printing. 
![image](https://user-images.githubusercontent.com/6361812/49532284-05607300-f871-11e8-962a-094e8970a77e.png)

after click:
![image](https://user-images.githubusercontent.com/6361812/49532848-4dcc6080-f872-11e8-8345-fb43c2e35dae.png)


@jasongrout, we talked a bit about the role of `Promise` yesterday, does that need to be included here? (e.g. I am not seeing the output to the console because it is an order-of-operations question)

Thanks for your help!

**Comment by AlbertHilb** [comment]
Hi @lheagy.
I think the problem is the fragment identifier must be introduced by a hash mark "#", not a question mark "?" (%3F).

**Comment by lheagy** [comment]
thanks @AlbertHilb!

**Comment by ian-r-rose** [comment]
@lheagy `this.content`. should be fine to use: that is a class attribute that is provided by a `CSVDocumentWidget` super-class.

The base-class for most panels in the main work area is the `MainAreaWidget`, which has a toolbar and a `content` node. This is defined here: https://github.com/jupyterlab/jupyterlab/blob/6185bda1b29967bfdcce3d320774e8534a51ac1c/packages/apputils/src/mainareawidget.ts#L105-L110
