### ISSUE TITLE
Allow toolbar button to be triggered by keyboard

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#5757]
It is currently possible to focus a toolbarbutton by tabbing with the keyboard. However, it is not possible to trigger it with the keyboard (space/enter). This should ideally be possible.

**Comment by jasongrout** [comment]
I think that is an excellent accessibility idea.

Why do we use the mousedown event in a toolbar button rather than a click event to trigger the button? https://github.com/jupyterlab/jupyterlab/blob/bf808f8fa61ac9aabcde19ac00f6b61a9e6295a0/packages/apputils/src/toolbar.tsx#L390 If we used the click event, the keyboard could trigger it.

(neither I nor @saulshanabrook have changed this in our PR either: https://github.com/jupyterlab/jupyterlab/blob/6ff2cb75502113148449915ccc294cdc7ce64545/packages/apputils/src/toolbar.tsx#L389)

**Comment by jasongrout** [comment]
Marking as good first issue, since hopefully it is as easy as switching the event to use click instead of mousedown.

I think the purpose for preventing the mousedown default is to prevent the focus from shifting away from the document. Perhaps we prevent the mousedown default, but *don't* directly call the onClick prop, instead wait for the click event to actually happen.
