### ISSUE TITLE
Inspector menu item

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5763]
I think people would appreciate the inspector more if it was more discoverable. A menu entry in the View menu to pull it up would be great, I think.

Here's how the terminal adds some entries to the view menu: https://github.com/jupyterlab/jupyterlab/blob/bf808f8fa61ac9aabcde19ac00f6b61a9e6295a0/packages/terminal-extension/src/index.ts#L146-L154

The inspector code is at https://github.com/jupyterlab/jupyterlab/tree/master/packages/inspector-extension/src

**Comment by jawnsy** [comment]
Hey @jasongrout!

I tried adding an Open Inspector item to the View menu from the inspector-extension's activate function, but ran into a recursive dependency problem because the mainmenu-extension depends on inspector-extension. it turns out that the mainmenu-extension already puts an Open Inspector menu item in the File menu. Here's what it looks like currently:

![image](https://user-images.githubusercontent.com/52710/56855582-0bc5b900-68fe-11e9-8b9b-f8d09d62c5a4.png)

Do you want to move this to the View menu? Also, would you want to move this to the inspector-extension?

Cheers,

Jonathan
ps: It was great meeting you at Jupyter Open Studio! 👋

**Comment by jasongrout** [comment]
Wow, sorry for not noticing that! My guess is that we originally put it in File because it opens a new tab. Perhaps this issue can be closed since it is available in a menu, even if it wasn't the one I was expecting.

Good to meet you too!
