### ISSUE TITLE
Executing a cell while it is running removes the execution asterisk

### ISSUE THREAD

**Issue by ma2331550908** [jupyterlab/jupyterlab#5779]
**Describe the bug**
jupyterlab . execute again what is being executed Input prompt is [] ,not [*]
![14_48_46__12_18_2018](https://user-images.githubusercontent.com/8001249/50137118-24312180-02d5-11e9-9899-08483e511431.jpg)

**To Reproduce**

1. open jupyter-lab
2. open one notebook
3. run code 
```
from time import sleep
print('a')
sleep(20)
print('b')
```
4. when the cell is running, execute again the cell
5. the In prompt is  [ ] , not [*]

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [mac os 10.14 (18A391)]
- Browser [chrome 71.0.3578.98]
- JupyterLab [0.33.7]

**Additional context**

-  ***Jupyter does not have this problem***

**Comment by jasongrout** [comment]
Confirmed in 1.0a1. It seems that the second execution clears the output and the `[]`, but of course execution doesn't proceed until the first execution is done.

**Comment by Madhu94** [comment]
[This](https://github.com/jupyterlab/jupyterlab/blob/a2681c4c2b531eab4bee8ebba23a38f89502a0fd/packages/cells/src/widget.ts#L828) seems pretty deliberate.  What would happen if we just removed this line and leave the '*' there? The second cell execution updates the correct execution_count

**Comment by jasongrout** [comment]
What if the execution was really canceled (i.e., the kernel interrupted)? The puzzling thing to me is that after the state is cleared, why does the re-execution not set the prompt to `*`? Or is the re-execution setting it to `*`, and *then* it is getting cleared?

**Comment by jasongrout** [comment]
@Madhu94 - were you wanting to work on this? There may be another person willing to take a look at it too, but I think they are happy to let you have it if you wanted to work on it.

**Comment by Madhu94** [comment]
@jasongrout I won't get to this for a few days,  so it would be great if
someone else took over.

**Comment by jasongrout** [comment]
Okay, thanks for the update. If anyone wants to start working on this issue, please post a message let people know.

**Comment by cquah** [comment]
@jasongrout I've started looking into this

**Comment by cquah** [comment]
Here's my diagnosis of the issue:

The execution request here
https://github.com/jupyterlab/jupyterlab/blob/86ac08051d573af947c4a51554a85fd5abf96246/packages/outputarea/src/widget.ts#L552
is being called with `disposeOnDone` set to false. This means that the returned Future will not be disposed at the time that it is resolved.

Instead, when the next execution request on the same cell happens, this step within the `execute` call https://github.com/jupyterlab/jupyterlab/blob/86ac08051d573af947c4a51554a85fd5abf96246/packages/outputarea/src/widget.ts#L553 results in https://github.com/jupyterlab/jupyterlab/blob/86ac08051d573af947c4a51554a85fd5abf96246/packages/outputarea/src/widget.ts#L165, which is when the Future associated with the previous execution request gets disposed. 

Now, if a 2nd execution request occurs on a cell while the 1st one is still in progress, a `dispose()` call is triggered on the 1st request's Future due to the above logic, and because the 1st request's Future is not actually resolved yet, this https://github.com/jupyterlab/jupyterlab/blob/86ac08051d573af947c4a51554a85fd5abf96246/packages/services/src/kernel/future.ts#L171 results in the 1st Future being rejected with a `Canceled` error, which clears the prompt as pointed out by @Madhu94 . So yup @jasongrout , the prompt is being set to * by the re-execution, but then getting cleared.

It's also worth noting that interrupting the kernel does not trigger a `dispose()` call (at least with `disposeOnDone` set to false), and hence will not result in any Future being rejected with a `Canceled` error. This `dispose()` call for a Future is the only place where it can get rejected with a `Canceled` error.

Another interesting but perhaps tangential observation is that if a 2nd execution request on a cell occurs while the 1st is still in progress, and then the kernel is interrupted, neither a cell execution count nor a kernel interrupted error message shows up. This behaviour appears to be the same in both JupyterLab and the classic notebook.

**Comment by cquah** [comment]
It looks like https://github.com/jupyterlab/jupyterlab/blob/a2681c4c2b531eab4bee8ebba23a38f89502a0fd/packages/cells/src/widget.ts#L827 was introduced by @blink1073 in https://github.com/jupyterlab/jupyterlab/commit/301cf6318af2a8053c172e0c7b2821a9935d2bb1 for the purposes of resetting the cell prompt to empty when the kernel restarts, because the restart event triggers a dispose call on all unresolved Futures via https://github.com/jupyterlab/jupyterlab/blob/86ac08051d573af947c4a51554a85fd5abf96246/packages/services/src/kernel/default.ts#L858

**Comment by cquah** [comment]
In my mind, the needs that are currently in tension are:

- If a cell execution is in progress, we want to clear the cell prompt on kernel restart, and ideally this is managed purely from the kernel and the futures it holds
- When a cell is re-executed while a prior execution is in progress, the first execution’s future does need to be properly disposed of to remove reply handlers etc.
