### ISSUE TITLE
Data converters in the data registry

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#5831]
As we build the data registry (#5548) we are seeing a need for a dataset converter API. A prototype of this has been built out in #5734.

## Questions

Some of the questions that are coming up in its design:

* Should we do multistep conversions?
* Do we want an API to list all possible target MIME types that converter chains can create?
* How to we track the "fitness" of a given conversion path. For example, converters that reify a dataset (IOW, load an abstract dataset into memory) should be lower priority than ones that keep things abstract?
* What initial converters do we want to ship?

### Tabular datasets

I think that initially we should focus on tabular datasets, as there are a number of different formats and lots of existing extensions that can work with them. Some of the relevant formats:

* CSV as text
* JSON table schema
* Vega/VegaLite format JSON
* Plotly format JSON
* Arrow
* Phosphor datagrid data model

Rather than implementing O(N^2) converters between all these formats, I think we should use Arrow as a base format that we have coverters to/from.

I am guessing that most of these converters are mostly written already in some form.

@gnestor @saulshanabrook

**Comment by saulshanabrook** [comment]
> Should we do multistep conversions?

Yes! This will let us break conversions into multiple pieces. i.e. like you noted below, instead of having `O(N^2)` we can have `O(2N)` if we settle on some common middle grounds (like arrow, or other suitable in memory JS formats). 

> Do we want an API to list all possible target MIME types that converter chains can create?

Also yes, because then a user can open that dataset in any mimerender extension that supports any of those types.

> How to we track the "fitness" of a given conversion path. For example, converters that reify a dataset (IOW, load an abstract dataset into memory) should be lower priority than ones that keep things abstract?

Maybe to start with we could assume each conversion has the same cost. Therefore, it would choose the path with the least conversions. That would let us "force" it to choose a simpler straight shot instead of a more intensive two step process if we would like.

Then, we could extend that, if we end up needing it, for arbitrary costs.

If the idea of materializing a dataset becomes the primary kind of cost we care about, we could define that cost as a constant, so users could import it to declare their converter did materialize the data:

```typescript

const MATERIALIZED_COST = 10;

...


const myConverter = {
  cost: MATERIALIZED_COST
}

```

If we assert that the cost is always > 0, we could use something like A* algorithm to efficiently find the cheapest path between nodes.

> What initial converters do we want to ship?


Having the csv viewer extension use the data transformers would be nice, at least.

**Comment by ellisonbg** [comment]
Sounds good.

**Comment by saulshanabrook** [comment]
I am taking some notes about how the existing mime render system is working, so that we can figure out where the data converters/data registry should fit in there.

In the `rendermine` package there is a `RenderMimeRegistry` that holds a mapping of mimetypes to to rendering functions.

The `preferredMimeType` method takes in a mimebundle and returns the first mimetype that has a renderer in the bundle, with some logic about safe vs unsafe mimetypes.

There are builtin mimetypes for these things:

```
0: "text/html"
1: "text/markdown"
2: "text/latex"
3: "image/svg+xml"
4: "image/bmp"
5: "image/png"
6: "image/jpeg"
7: "image/gif"
8: "text/javascript"
9: "application/javascript"
10: "text/plain"
11: "application/vnd.jupyter.stdout"
12: "application/vnd.jupyter.stderr"
13: "application/json"
14: "application/pdf"
15: "application/vdom.v1+json"
16: "application/vnd.vega.v4+json"
17: "application/vnd.vegalite.v2+json"
```

When you open *some* files they use a renderer, including JSON, but not CSV or other files.

JSON files can be opened either as `application/json` or as `application/vdom.v1+json` or as `application/vnd.vega.v4+json` mimetypes, for example. 

**Maybe when you right click on a file and go to "Open With" it would not only show the renderers directly available based on the mimetypes of the file, but also those that can be converted to**

So how does the renderer thing work? An `IRenderer` has a method named `renderModel` that is called with a model every time new data is loaded, to-reload that data. It takes in an instance of `IRenderMime`

```typescript
    /**
     * A model for mime data.
     */
    interface IMimeModel {
        /**
         * Whether the data in the model is trusted.
         */
        readonly trusted: boolean;
        /**
         * The data associated with the model.
         */
        readonly data: ReadonlyJSONObject;
        /**
         * The metadata associated with the model.
         *
         * Among others, it can include an attribute named `fragment`
         * that stores a URI fragment identifier for the MIME resource.
         */
        readonly metadata: ReadonlyJSONObject;
        /**
         * Set the data associated with the model.
         *
         * #### Notes
         * Calling this function may trigger an asynchronous operation
         * that could cause the renderer to be rendered with a new model
         * containing the new data.
         */
        setData(options: IMimeModel.ISetDataOptions): void;
    }
```

When is `setData` called? In some places for dragging (ignoring these) and also when adding a new mimetype to the mimebudle (So i guess `data` is often a mimebundle, but this isn't enforced in the type signature.

In [JSON](https://github.com/saulshanabrook/jupyterlab/blob/c2d82c2bf8771c119540c365cac18bec87df757d/testutils/src/rendermime.ts#L27-L31):

```
    renderModel(model: IRenderMime.IMimeModel): Promise<void> {
      let source = model.data['application/json'];
      model.setData({ data: { 'text/html': json2html(source) } });
      return super.renderModel(model);
    }
```


and in [Vega](https://github.com/saulshanabrook/jupyterlab/blob/c2d82c2bf8771c119540c365cac18bec87df757d/packages/vega4-extension/src/index.ts#L105-L109):

```
    // Add png representation of vega chart to output
    const imageURL = await this._result.view.toImageURL('png');
    model.setData({
      data: { ...model.data, 'image/png': imageURL.split(',')[1] }
    });
```


OK so it looks like another use case for data converts is from going from things like vega to png or from JSON to html. These other formats can be saved in the output of cells, so that when you load a notebook with one type, it persists the other type as well.

**Comment by saulshanabrook** [comment]
In chatting with @ellisonbg today, I asked about how he sees data registry integrating with existing JupyterLab UX. 

For files: Don't change initial UX, at least initially. Still have open with and double click. 

We could certain file types to register by default with data registry. Or have right click item to register with data registry.

Outputs in the notebook: some maybe should be auto registered. Others could be right click on output to add to registry. 

For file opening, leverage existing doc manager, to map file extensions to mimetypes. Right now there are implicit conversions, between types of files. 

For CSV you might be able to tell mimetype out of the box. for other things like JSON, you need something like open with, to switch between "JSON as Vega" vs "JSON as data" which be registered with different mimetypes. 

For now the simplest thing to explore this is probably sufficient.

**Comment by gnestor** [comment]
I've been following this conversation but haven't commented because I'm lacking some context. I'd be happy to discuss details around mimerender functionality and UX. 

I'm curious if we've considered making all data _reigstered_ by default? To elaborate: provide a UI for querying/selecting data from all open documents. For non-notebook documents, a user would simply select the data by the filename. For notebook documents, the user would select the data by cell (cells could be presented similarly to how the toc extension presents them). This could all happen within a modal. I imagine that a second modal could proceed data selection that prompts the user for target data type, allowing them to convert from some JSON format to CSV or vice-versa. 

I'm just throwing ideas out there since I haven't been apart of the previous conversations about the data registry 🤷‍♂️

**Comment by saulshanabrook** [comment]
@mpeaton mentioned that this research tool called ["Boomerang: A bidirectional programming language for ad-hoc, textual data."](https://www.seas.upenn.edu/~harmony/) might be interesting to look at. They seem link to some relevant sounding research papers:

* [**Boomerang**: Resourceful Lenses for String Data](http://www.cis.upenn.edu/~bcpierce/papers/boomerang.pdf)
* [**Relational Lenses**: A Language for Updateable Views](http://www.cis.upenn.edu/~bcpierce/papers/dblenses-tr.pdf)
* [**Combinators for bidirectional tree transformations**: A linguistic approach to the view-update problem.](http://www.cis.upenn.edu/~bcpierce/papers/newlenses-popl.pdf)

> I'm curious if we've considered making all data reigstered by default? 

@gnestor Not at the moment. Right not it's more of a push-based model instead of a pull one. You can "register" a file as a dataset, and I am working on right clicking on a notebook output to be able to register that as well. I am iterating on this [in a PR](https://github.com/jupyterlab/jupyterlab/pull/5857), not everything is documented yet, but the description checkboxes are up to date in terms of my status.

Having some sense of a "data provider" though that says "Hey here are all the datasets I can access" I think does make a lot sense, though.  

> I imagine that a second modal could proceed data selection that prompts the user for target data type, allowing them to convert from some JSON format to CSV or vice-versa.

Right now, I have implemented the UI as basically only showing the user what "viewer" are valid for the dataset. Hidden from them is the path through the graph of datasets that needs to be taken to convert from what they have to what they need for that viewer.

However, maybe there are good use cases for requiring manual conversion? One thing we have to figure out still is what is the right story for things that *could* be multiple types, but we aren't sure yet. For example, a JSON might really be a Vega Lite spec or be a list of records. The user really needs to manually specify in that case which one it is, so the relevant viewers can be understood. Or just allow them to convert to all possible forms, and just fail if it isn't valid.

Also happy to have a call if you wanna talk more in depth.

**Comment by gnestor** [comment]
I'll check out your PR 👍 

Boomerang looks like an interesting solution.
