### ISSUE TITLE
Create build targets to output platform specific JS packages

### ISSUE THREAD

**Issue by modean** [jupyterlab/jupyterlab#5856]
**Describe the bug**
If consuming `jupyterlabe/services` from within a node project it is non-obvious that you need to define `jupyterlab/services` dependencies in the node module that consumes `jupyterlab/services`.

Usually this isn't common sense if consuming 3rd-party libs and also it is of advantage if the 3rd-party lib would maintain its own dependency because that way it could lock down the exact dependency plus version it requires if installing them on its own instead of delegating it to the consumer.

Cause `jupyterlab/service` and most likely other `jupyterlab` JS packages are consumed by different platforms (namely browser and NodeJS) the dependencies were not added to the `package.json` file to not pollute/bloat the browser platform with node packages.

The proper way to deal with this is to introduce build targets and output distribution packages per supported platform (e.g. browser and node).

@saulshanabrook ^^^

**Comment by jasongrout** [comment]
@ian-r-rose points out on chat that the (relatively undocumented?) package.json `browser` field might help here, in that it might be able to tell webpack to ignore certain dependencies. See for example https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module and webpack/webpack#4674

Another option that @saulshanabrook points out is separate packages targeting different environments, for example `@jupyterlab/services-browser` and `@jupyterlab/services-node` packages (see https://github.com/ReactiveX/IxJS#packaging  for an example).

**Comment by jasongrout** [comment]
Adding to 1.0 milestone so that people can actually import the services package in node to provide a kernel api. I'm hoping that the package.json `browser` field may be a simple solution for this (i.e., declare the dependency like the websocket node polyfill, and use the `browser` field to tell webpack to ignore this polyfill when packaging for the browser).

@modean - if you're trying to interact with a kernel directly from node, you might also consider the nteract enchannel libraries, which directly talk to a kernel over zmq or socket.io (using the kernel relay server).

**Comment by saulshanabrook** [comment]
To add some more details from gitter:

> if installing @jupyterlab/services via npm install required dependencies like ws or node-fetch won't get installed.

Interesting that in `service` we already seem to be doing a check if we are in node and then importing `node-fetch` and `ws`: https://github.com/jupyterlab/jupyterlab/blob/86a2dddc0c7756c47ddc75f9d62b020aae7393be/packages/services/src/serverconnection.ts#L16-L31

So I think webpack should already ignore these if they are installed.
