### ISSUE TITLE
Uncaught ReferenceError: IPython is not defined

### ISSUE THREAD

**Issue by tamama** [jupyterlab/jupyterlab#5888]
Hi JupyterLab,

In Jupyter Lab 0.33.11  (from Anaconda version 4.5.12 -- 2018.12), I try to extract pass javascript objects into IPython kernel, it failed with "Uncaught ReferenceError: IPython is not defined".

However, in Jupyter Notebook 5.7.4 (classical tree), everything works as usual.

May I kindly attach the code in the following image ...

Expected behavior: (Works well with Jupyter Notebook 5.7.4)
============================================

![image](https://user-images.githubusercontent.com/17287685/51424335-29043080-1c07-11e9-9ced-b6c9860383e3.png)

**Comment by jasongrout** [comment]
Yes, the Javascript API has completely changed. There is no longer a single kernel on the page (since there can be multiple notebooks), and the kernel is not readily accessible from javascript coming from the kernel.

The way to do things like execute kernel code from JS in jlab is to write a jlab extension.

**Comment by tamama** [comment]
@jasongrout Thanks! Kindly let me revert with more findings.
