### ISSUE TITLE
No option to choose checkpoint in JupyterLab

### ISSUE THREAD

**Issue by amangarg96** [jupyterlab/jupyterlab#5923]
I'm using [Postgres-backed ContentsManager](https://github.com/quantopian/pgcontents) with Jupyter Lab, which allows you store multiple checkpoints for a  particular Notebook.

In classic Jupyter Notebooks, the list of checkpoints appear as expected (Screenshot below)
![image](https://user-images.githubusercontent.com/16137472/52059137-0111b700-258f-11e9-960d-62f9cd6fb8ac.png)

But in JupyterLab, you do not get a list of checkpoints and you can only choose the latest checkpoint. (2 Screenshots below)
![image](https://user-images.githubusercontent.com/16137472/52059260-62398a80-258f-11e9-8ec0-4dc7c52b9b8b.png)
![image](https://user-images.githubusercontent.com/16137472/52059275-6d8cb600-258f-11e9-816d-5e8232c8f181.png)

What can be done to make JupyterLab show all the accessible checkpoints?

Jupyter Lab version - 0.35.4
Jupyter Notebook version - 5.7.4

**Comment by jasongrout** [comment]
Great question. Tagging as 1.0 for discussion.

**Comment by jasongrout** [comment]
It looks like IPEP 15 was implemented as written, in #618, which specifies only one checkpoint. You're right that the notebook now offers a menu of many checkpoints.

**Comment by tgeorgeux** [comment]
@jasongrout From a technical perspective, does this mean that we have all the checkpoints saved and could access if we wanted to? If so I can whip up a prototype of what that would look like.

**Comment by amangarg96** [comment]
@tgeorgeux  The default ContentsManager implementation stores only one checkpoint per notebook, but with other implementations like [Postgres-backed ContentsManager](https://github.com/quantopian/pgcontents) you have all the checkpoints saved which have a corresponding checkpoint id. 
In classic Jupyter Notebooks, you can access all these checkpoints but in Jupyter Lab you can access only one (which is sometimes not even the latest checkpoint).

**Comment by diocas** [comment]
Hi, can we also allow the creation of checkpoints to return empty?
Currently, doing this fails [here](https://github.com/jupyter/notebook/blob/e937fd79927e5806656a4229091d9814686626d2/notebook/services/contents/handlers.py#L261), since `checkpoint` is empty. While in the Notebook UI the error is ignored, in Lab it prevents the opening of any file. I would suggest that Lab just displays an empty list instead.

Why do we want to return empty?
Because Lab calls the checkpoint creation endpoint when it creates a new file. At CERN we rely on our storage backend ([EOS](https://cern.ch/eos)) to create checkpoints, but this only happens after a save and not when a file is created and is still empty.

**Comment by jasongrout** [comment]
Can you open a new issue for this? As an error preventing you from opening files, it looks materially different than the subject of this issue, which is displaying more than one checkpoint in the submenu.

**Comment by diocas** [comment]
Ok, will do.
The part that is related to this issue is that the submenu list should be allowed to be empty.

**Comment by jasongrout** [comment]
>  The part that is related to this issue is that the submenu list should be allowed to be empty.

Yes, good point. Thanks.

**Comment by hMED22** [comment]
Me and my team have needed this once and had it done on an extension and now I want to open a pull request to bring it to Jupyterlab but the list of checkpoints may not be as you're expecting, when you click on "Revert Notebook to Checkpoint" you get a select input dialog instead of a list of submenu items.
![image](https://user-images.githubusercontent.com/34286755/105343195-988bcc80-5be1-11eb-81b6-a11251359acb.png)

This way we don't have to pull the list of checkpoints to update the submenu items whenever the active document changes or a new checkpoint is created.

**Comment by jasongrout** [comment]
Brainstorming here about the ux: 

* is there a way to have both ways? Still have a submenu with, say, the last checkpoint (probably the most common usecase), and a "More..." menu item that pulls up a dialog like this?
* On the other hand, submenus are hard to interact with (they require pretty precise pointing skills, etc.). Maybe it's just better to have a dialog come up anyway. One nice thing about the dialog is that it implicitly acts as a confirmation (since reverting to a checkpoint is a pretty destructive operation).

**Comment by jasongrout** [comment]
Either way, I think a dialog that lets you choose checkpoints is an improvement on what we have. I'd love to see the PR. Thanks for offering to contribute it!

**Comment by hMED22** [comment]
> is there a way to have both ways? Still have a submenu with, say, the last checkpoint (probably the most common usecase), and a "More..." menu item that pulls up a dialog like this?

Maybe I should have described the whole thing, if there is only one checkpoint available (most common usecase) there would be no select dialog just the confirmation exactly like Jupyterlab is currently doing, if multiple then the last checkpoint is already selected on the select, I hope this is helpful enough.

And an informative error dialog in case no checkpoints available.
