### ISSUE TITLE
Disable Travis and Appveyor

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#5951]
Now that we have had Azure Pipelines running for a while and it seems to work, we should disable Appveyor and Travis CI. Right now it's a bit of an information overload to have all of them running on every PR.

- [x] Remove links from README
- [ ] Deactivate on Github repo

**Comment by kaylangan** [comment]
Not sure if this is better as a separate issue, but I noticed that the [names of the jobs on Azure Pipelines](https://dev.azure.com/jupyterlab/jupyterlab/_build/results?buildId=707) are "Travis" and "Appveyor". Might be good to change those to "Linux" and "Windows" instead.

Since "Travis" and "Appveyor" are in the [job name](https://github.com/jupyterlab/jupyterlab/blob/master/azure-pipelines.yml#L2) rather than the [displayName](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job), you'll have to also adjust your branch policies if you're using them.

**Comment by saulshanabrook** [comment]
@kaylangan Thanks for the suggestion! Yeah that's a good idea. I also want to do some refactoring of our CI once we disable appveyor and Travis. I think we can parallelize the jobs more and split them out of those big scripts.

**Comment by ian-r-rose** [comment]
@kaylangan, you are absolutely right. I made that switch in eff023d, which we can hopefully get merged soon.

**Comment by ian-r-rose** [comment]
@kaylangan We have been running into an issue on our Azure Windows builds where we hit path length limits for Windows 10.  281cb38 seems to fix it, but it would be nice if the base images had long paths enabled by default. Is this something the Azure team has looked at, or is there some configuration option I am missing?

**Comment by ian-r-rose** [comment]
Closed by #5974

**Comment by kaylangan** [comment]
@ian-r-rose let me check with the team. I see that we have https://github.com/Microsoft/azure-pipelines-image-generation/issues/157 open and it was most recently updated 2 weeks ago.

**Comment by ian-r-rose** [comment]
Thanks for checking!

**Comment by kaylangan** [comment]
@ian-r-rose just to follow up. Yes, we want to enable long paths by default on the Windows image. We're trying to see where we can fit it into our plans, but I'm very hopeful that we'll get to it soon-ish. After that, it might take a few weeks for it to fully roll out, so definitely feel free to ping me for updates. Thanks for reminding us about this!

**Comment by ian-r-rose** [comment]
Thanks @kaylangan!
