### ISSUE TITLE
[Feature request] restore "Output view"

### ISSUE THREAD

**Issue by defeo** [jupyterlab/jupyterlab#5976]
Hello,

This issue popped up while discussing with @fperez. I have an output view on a notebook cell, like this:

![screenshot_2019-02-11 jupyterlab](https://user-images.githubusercontent.com/1315842/52584158-a0f1ff00-2e31-11e9-8cd8-a888ec0948fc.png)

The split view is saved in the current workspace, however without enough information to restore the output view. If I reload the page, the output view disappears:

![screenshot_2019-02-11 jupyterlab 1](https://user-images.githubusercontent.com/1315842/52584215-c7179f00-2e31-11e9-92dd-4d8c523d9f09.png)

It would be nice if the output view could be restored. I'm especially interested in having this for Binder.

Tested in 1.0.0a1

**Comment by ian-r-rose** [comment]
Thanks @defeo, this is a nagging issue that I've been wanting to fix for a while. Unfortunately, the output area clone doesn't work that well with the layout restoration system. It should be possible to figure out, but it's not very natural.

It would definitely be nice to be able to rely on this for binder demos.

**Comment by jasongrout** [comment]
@ian-r-rose - a 1.0 issue, or Future?

**Comment by ian-r-rose** [comment]
Let me take a look this afternoon.  Last I checked it wasn't trivial, but maybe I can see a way through...

**Comment by ian-r-rose** [comment]
I took a look at this: it's a really tricky problem. The cloned output area widgets are not normal widgets to restore: they are irrevocably tied to a particular notebook. This means, for instance, that they cannot be restored until after all the notebooks are restored. Unfortunately, this leads to a cycle of promise resolution that would have to be broken:
1. Notebook widgets restore, but the documanager does not load the contents until the app is restored.
2. Cloned output areas need the notebook contents to be loaded before restoring, which needs to happen after the app is restored.
3. The app restore promise is not resolved until both conditions above are met.

The solution is probably to put empty placeholder widgets for cloned output areas and populate them once their notebook is loaded (right now they are populated synchronously), but that requires some reworking of things. I have some initial work [here](https://github.com/ian-r-rose/jupyterlab/tree/restore-cloned-output), but it's not functional yet.

This is not even touching the problem of out-of-band or unsaved output clones: a cloned output could be of an unsaved or moved cell that is not possible to restore, since it does not exist on the server. *That* can of worms likely couldn't be solved until we have a server-side data model.

Marking as future, unless I feel inspired.

**Comment by ian-r-rose** [comment]
Okay, I went after this in #5981. The problem of unsaved notebook changes is still there, but this should still work for a lot of use-cases.

**Comment by bollwyvl** [comment]
Awesome stuff!

Apropos of cloned outputs: is there something public on them that would
reveal which notebook they are from? I've been dinking around with
son-of-tabs-and-running, and they don't have a session or a context on
them, so I presently draw them under the lonely "no kernel" kernel... But
I'd love to actually nest them under the Notebook that spawned them, as
they can't really be moved into another kernel, unlike a notebook, console,
or general document.

**Comment by ian-r-rose** [comment]
There wasn't anything like that before (except in the hover text for the tab). In #5981, however, I added a `path` and `index` attribute to the cloned output content. Would that do the trick?

**Comment by bollwyvl** [comment]
> added a `path` and `index` attribute to the cloned output content

That's a good start! Here's what my current janky :duck: typing code (poorly) does at present (obviously should be checking types):
```ts
    getSession(widget: Widget): Session.ISession {
      let unsafe = widget as any;
      let clientSession =
        unsafe.session || (unsafe.context && unsafe.context.session);
      let session = (clientSession && clientSession._session) || null;
      return session || clientSession || null;
    }
```

I'm pulling the private session because i then immediately call `changeKernel`, and doing so on a `ClientSession` kills the underlying `ISession`, which may not be what I want if I have, say, a console _also_ attached to that kernel. Anyhow, if the above doesn't work, I can look through the running sessions and slap it under whatever one is open... there isn't really a way to know, probably, exactly which widget it came from, as I don't think my current setup would actually allow you to move a "new view" of a notebook onto another kernel, as I'm pretty sure they share the same underlying session, and there's probably no way to break that now (if that's even a good thing).

This is definitely model-breaking stuff, but then we'll never know if it can work if we don't look :japanese_ogre:... looking forward to messing with 1.0.0!
![screenshot from 2019-02-14 08-07-06](https://user-images.githubusercontent.com/45380/52788634-8e451900-302f-11e9-8a64-8c73ff826655.png)
