### ISSUE TITLE
CodeMirror ActiveLine highlight issues

### ISSUE THREAD

**Issue by mbektasbbg** [jupyterlab/jupyterlab#6053]
- If `styleActiveLine` is set to `true` in CodeMirror settings, styling doesn't work properly in Dark theme.
- If it is set back to `false`, still stays on until restart.

![active-line-dark](https://user-images.githubusercontent.com/40003442/53603579-c63b7880-3b66-11e9-8cee-4b42b8dd6323.png)
![active-line-light](https://user-images.githubusercontent.com/40003442/53603550-ac019a80-3b66-11e9-889e-21e6b9dcbe5c.png)

**Comment by jasongrout** [comment]
Thanks! Some relevant places in the code are:

https://github.com/jupyterlab/jupyterlab/blob/bdfaab157854ce6f6e91d2146c4bb8cc3e36a021/packages/codemirror/src/editor.ts#L1201-L1207

https://github.com/jupyterlab/jupyterlab/blob/bdfaab157854ce6f6e91d2146c4bb8cc3e36a021/packages/codemirror-extension/src/index.ts#L151-L184

And the themes should probably define values for the codemirror classes noted above.

**Comment by jasongrout** [comment]
Sorry, the references above are not what is needed. The active line looks great if you set the text editor theme to something else. However, the `jupyter` editor theme looks bad, primarily because the appropriate codemirror variables aren't defined, `CodeMirror-activeline`, `CodeMirror-activeline-background`, and `CodeMirror-activeline-gutter`.

So probably what needs to happen is:

1. Define appropriate colors for these in each theme:
https://github.com/jupyterlab/jupyterlab/blob/2dcdd45fea89f29ecd2865a3539a60d8e89ce67b/packages/theme-dark-extension/style/variables.css#L338-L363
https://github.com/jupyterlab/jupyterlab/blob/2dcdd45fea89f29ecd2865a3539a60d8e89ce67b/packages/theme-light-extension/style/variables.css#L335-L360

2. Add the `.cm-s-jupyter .CodeMirror-activeline`, etc. classes using these colors in the codemirror package at the bottom of https://github.com/jupyterlab/jupyterlab/blob/2dcdd45fea89f29ecd2865a3539a60d8e89ce67b/packages/codemirror/style/index.css

**Comment by jasongrout** [comment]
Fixed by #6261
