### ISSUE TITLE
Enhance documentsearch extension and interface for search and replace

### ISSUE THREAD

**Issue by aschlaep** [jupyterlab/jupyterlab#6081]
To properly finish out #1074, the documentsearch extension should have search and replace.  Notebooks, text files, and .csv files are currently supported by the existing extension, so these should all support search and replace as well.  It should have a "replace current match" and "replace all" features and should play nice with the undo/redo stack.  It will grow off of the existing search dialog via some sort of expansion toggle.

**Comment by aschlaep** [comment]
I'm starting work on this today!

**Comment by jasongrout** [comment]
Putting as 1.1 as it's not a blocker for 1.0, but if we merge it before 1.0, all the better!

**Comment by jasongrout** [comment]
Back to 1.0 since it has a PR open.

**Comment by Alexboiboi** [comment]
Hi there, I agree on the fact that this 'find and replace' feature was much awaited and is great to be implemented. Will there be a way to choose if this feature applies to the entire notebook or just one cell? Depending on the use case it is very useful to have both ;)
Otherwise keep up the great work!

**Comment by gabegrand** [comment]
@aschlaep Thanks so much for adding this feature - now I finally feel comfortable switching from VSCode to JupyterLab. One request: would it be possible to automatically populate the "find" field with whatever term the user has currently highlighted in their file? This feature is included in Atom, VSCode, and other editors, and I find it's super useful to be able to highlight a word and then ctrl+F to quickly search for it. Otherwise, others have said, fantastic work!

**Comment by aschlaep** [comment]
Thanks @Alexboiboi and @gabegrand! Regarding limiting the replace all action to cells - it's something we considered, but the UX for it is a bit tricky (limit to selected cells, active cell, etc), so we punted on it, hopefully we'll get a chance to come back to it at some point.  And regarding @gabegrand's suggestion, that's a great idea and would be pretty quick to add, I'll take a swing at it either tomorrow or early next week.  It'd involve a change to the `ISearchProvider` interface, so it should get in before 1.0.
