### ISSUE TITLE
MIME type ('text/plain') is not executable

### ISSUE THREAD

**Issue by Calvin-he** [jupyterlab/jupyterlab#6098]
This issue is related with: [jupyter/notebook/issues#4467](https://github.com/jupyter/notebook/issues/4467). It's due to jupyter's issue.
Chrome console shows error message:

Refused to execute script from 'http://localhost:8888/lab/static/vendors~main.10079ad9676c70f28097.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Refused to execute script from 'http://localhost:8888/lab/static/main.13de647526d0a582493b.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
lab:1 Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by saulshanabrook** [comment]
Hm, I haven't seen this error before. Does the regular notebook server work for you? (which is `/tree` instead of `/lab`)

**Comment by ilango100** [comment]
I had the exact same issue a while ago. I think this issue is specific to Windows. It is due to the wrong MIME type being set in Windows registry for javascript files. I solved the issue by editing the Windows registry with correct content type:

regedit -> **HKEY_LOCAL_MACHINE\Software\Classes** -> You will see lot of folders for each file extension -> Just scroll down to  ".js" registry and select it -> On the right, if the "Content Type" value is other than application/javascript, then this is causing the problem. Right click on **Content Type** and change the value to **application/javascript**

![Annotation 2019-03-19 022627](https://user-images.githubusercontent.com/16995641/54563143-76760180-49ee-11e9-96fb-41cb9eb03853.jpg)

Try again in the browser.

**Comment by multimulti** [comment]
I think this is related to this issue with jupyter notebook:  https://github.com/jupyter/notebook/issues/4467

Apparently there is a fix waiting to be merged: https://github.com/jupyter/notebook/pull/4468

**Comment by Calvin-he** [comment]
Thanks  @ilango100 @multimulti for offering the reason and solution.  I think this issue can be closed now. @saulshanabrook

**Comment by jasongrout** [comment]
Thanks!
