### ISSUE TITLE
Need to remove few items on filebrowser context menu 

### ISSUE THREAD

**Issue by subivasudev** [jupyterlab/jupyterlab#6115]
I am building a custom lab extension. In which I want to remove few items from default file browser context menu. I appreciate any support on the matter.

**Comment by saulshanabrook** [comment]
I don't believe this is possible at the moment. 

It's the `app.contextMenu` (which is an instance of Phosphor's `ContextMenu`) class which you add an item to. [`addItem`](http://phosphorjs.github.io/phosphor/api/widgets/classes/contextmenu.html#additem) returns a disposable that you would call to remove that item. But since you didn't add the items, you don't have access to that disposable so can't remove them.

I think this question was raised in https://github.com/jupyterlab/jupyterlab/issues/3994, but that was closed, because you can now *add* items to the default filebrowser context menu, even though you can't remove them.

**Comment by subivasudev** [comment]
many thanks @saulshanabrook
