### ISSUE TITLE
`jupyterlab extension list` outputs to stderr

### ISSUE THREAD

**Issue by OleMussmann** [jupyterlab/jupyterlab#6145]
**Describe the bug**
The bash command `jupyterlab extension list` outputs by default to stderr.

**To Reproduce**

1. Go to terminal
2. Type `jupyterlab extension list`
3. Confirm exit code with `echo $?`. This should be `0`, aka a-ok.
4. Type `jupyterlab extension list 1>stdout 2>stderr`
5. Check file content of `stdout` and `stderr`. `stdout` is empty, while `stderr` contains the regular output.

**Expected behavior**
`jupyterlab extension list` should output to `stdout`, not `stderr`.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- JupyterLab v.0.35.4

**Comment by afshin** [comment]
I would start with the `ListLabExtensionsApp` which is actually tasked with responding to that command, and wind down to where it outputs to fix this.

Here's where that class is defined: https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/labextensions.py#L180

**Comment by vidartf** [comment]
I think this is because the default python logger uses stderr: https://docs.python.org/2/library/logging.handlers.html#logging.StreamHandler

It seems this is the default behavior of all traitlets (Jupyter) applications: https://github.com/ipython/traitlets/blob/c3abe9a677967ec9f034e28060140a016ba8812a/traitlets/config/application.py#L209-L216

**Comment by vidartf** [comment]
The question following my previous observation is then: Should the primary output of a command be output with `print()` instead of via logging? (probably yes)
