### ISSUE TITLE
Feature request: display ipywidgets in code console

### ISSUE THREAD

**Issue by cdgreenidge** [jupyterlab/jupyterlab#6165]
Would it be possible to display ipywidgets in the code console? Currently, when an ipywidget is evaluated in the code console, it just prints the string representation.

The use case for this is to display interactive plotting widgets from libraries like Plotly during an iPython session (e.g. https://plot.ly/python/jupyter-lab-tools/). The widget versions of the plots are nice because they don't crash with lots of data.

Thank you for your time!

(tagging @bccho because he's interested in this too.)

**Comment by jasongrout** [comment]
I would love to have this as well. It's definitely possible, someone would just need to write the code for it.

**Comment by jasongrout** [comment]
Writing the code for it will hopefully be easier after the next release of ipywidgets, which has more complete support for JupyterLab in ipywidgets.

This is really an issue for the ipywidgets repo, though, since that is where JLab support code resides. JupyterLab itself doesn't have any code special for ipywidgets. Would you mind opening this issue in the ipywidgets repo? https://github.com/jupyter-widgets/ipywidgets

**Comment by cdgreenidge** [comment]
Thank you! I will open the issue in ipywidgets.

**Comment by jasongrout** [comment]
Great, thanks! I'll close this one here too.
