### ISSUE TITLE
Lower display priority for PDF

### ISSUE THREAD

**Issue by mgeier** [jupyterlab/jupyterlab#6222]
This was already discussed in #3038, but in the context of introducing a configuration option for display priority.

This issue right here is about changing the default display priority. This is more urgent than having a configuration option. This is required to get feature-parity with the Classic Notebook.

The default display priority should be first SVG, then PNG and then (as a last resort) PDF.

**Comment by blink1073** [comment]
Marking as a good first issue.  The ranks are defined here: https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/src/factories.ts.

**Comment by mgeier** [comment]
Thanks @blink1073! The word "pdf" is suspiciously missing from this file, though ...

**Comment by jasongrout** [comment]
The pdf renderer is registered in a separate extension: https://github.com/jupyterlab/jupyterlab/blob/3b0c6e622b25b8fee11fc11fff3da0436fbc2756/packages/pdf-extension/src/index.ts#L74-L79

@ian-r-rose - do you recall why it is its own extension, and not in the standard renderers?

**Comment by jasongrout** [comment]
I think it may be easier to grok the renderer file at https://github.com/jupyterlab/jupyterlab/blob/3b0c6e622b25b8fee11fc11fff3da0436fbc2756/packages/rendermime/src/factories.ts if we listed the renderers in order of rank.

I think I'm +1 on moving the pdf renderer into the standard renderers too, instead of having its own extension. That doesn't have to be this PR, of course.

**Comment by jasongrout** [comment]
For context: @ian-r-rose introduced the pdf renderer in #2867, fixing #670. In https://github.com/jupyterlab/jupyterlab/issues/670#issuecomment-321056166, Ian mentions it could be its own package or in the core renderers package, but I don't see a reason he picked a separate package over including it in core. @ian-r-rose - thoughts about moving the pdf renderer into the core renderers package?

**Comment by ian-r-rose** [comment]
@jasongrout I believe it was a separate renderer for two reasons:
1. It started life as a third-party extension, and
2. It was an early test of the rendermime extension interface

**Comment by jasongrout** [comment]
Great. I think it would be great to move into core now:

1. images in core could use the objecturl logic instead of setting src to the base64, maybe other renderers too
2. it's small enough I don't think it's a huge burden codewise

If we eventually implemented something like two-way syncing for latex/pdf files like cocalc has, we could make a more sophisticated pdf renderer as a standalone plugin.

**Comment by jasongrout** [comment]
(Again, for this issue, changing that one display priority number in the pdf package is all that is needed. We can open a separate issue for the other thoughts here.)

**Comment by ian-r-rose** [comment]
Yep, I have no problem with migrating the logic to be with the rest of the default renderers.

Note that my LaTeX extension, which uses PDF.js, has some synchronization between the two views implemented.

**Comment by ian-r-rose** [comment]
@jasongrout Took a closer look at moving the PDF renderer to core. One difficulty with that is that the rendermime extension also handles instance tracker / mime-document logic for the new renderer. So if we were to move the renderer into the core, we would still need the pdf extension to do the rest.

Do you still think the advantage of reusing the objecturl logic is worth the churn?

**Comment by mgeier** [comment]
Thanks a lot for solving this long-standing issue!
