### ISSUE TITLE
Put token definitions in submodule

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#6302]
## Problem description:
The plugin/token system as it is used today has one annoying issue: When declaring an optional dependency, or writing a plugin that will replace another existing plugin, you normally end up importing the *entire* lib package just for the token definition. This might end up making dead code elimination / three-shaking harder, and in general just feels wrong. A better pattern might be to standardize on declaring tokens in "./tokens.ts", which should only import typings, if anything (in addition to `Token` of course).

### Advantages:
- Easy to find which tokens each package define.
- Allow to import tokens without importing package logic (helping optimizers?).
- We can still re-export tokens in index (but should we?).

### Disadvantages:
- Will either split Token definition from interface declaration OR interface declaration from implementation. This might end up being an advantage, but it might also be a disadvantage in some cases.
- Some extra churn for the refactoring.

## Initial proposal:

- For each package, move all token definitions to `./tokens.ts`.
- Also move the interface declarations for the token to `./tokens.ts`.
- Re-export tokens from `./index.ts` to avoid breaking imports outside of core, but change all cross-package imports in core to import from the sub-modules.
- Change cookiecutters / examples to import from sub-modules to establish the pattern for new packages.

**Comment by afshin** [comment]
We have an `interfaces.ts` in `@jupyterlab/coreutils` and one in `@jupyterlab/documentsearch` ... which isn't a standard, but it's pointing out this sort of thing might be a good idea.

**Comment by blink1073** [comment]
I'd prefer it to be called `interfaces.ts` and have both the interface definition and the token definition.

**Comment by ian-r-rose** [comment]
I agree with your proposal @vidartf (and `interfaces.ts` seems fine to me).

After seeing the work that @bollwyvl went through to get the terminal lazy-loading, putting some distance between some interfaces/tokens and their implementation seems like a good idea.

**Comment by vidartf** [comment]
Thanks for the quick feedback. I'll do a PR along the lines of the initial proposal above, but with the filename as suggested. I'll link it here when submitted.

**Comment by vidartf** [comment]
Any thoughts about what to do about namespaced tokens/interfaces? Is it worth it to break them out, or is it helpful to keep them in their existing namespace?

**Comment by afshin** [comment]
If the namespace is a concrete namespace (i.e. if they are basically statics of a class) I would propose they stay where they are. If the namespace is itself an interface name, then it seems okay to move it into the interfaces file.

**Comment by jasongrout** [comment]
Putting as 1.0, since this will have massive ramifications on plugins and our recommendations for plugins.

**Comment by jasongrout** [comment]
Okay, fair enough. I think we could make the argument that you actually are importing tokens, and the interfaces are just how the tokens are typed.

**Comment by saulshanabrook** [comment]
Main point:

Token should be importable without any side effects or other imports. 

We would like to do this with tree shaking unless all dependencies have the side effect free tag. 

In principal this about making JupyterLab more usable in libraries.

So the use case here is that someone wants to implement a library without pulling in all its dependencies. 

Our todo is:

- [ ] We won't import from lib in core, but we will provide them in a seperate files if third parties want to import them in https://github.com/jupyterlab/jupyterlab/pull/6334
- [ ] Do the CSS refactoring below

We could import the CSS in the extension package instead of the core one. We can have a standard pattern for declaring where this CSS is, like this: https://jaketrent.com/post/package-json-style-attribute/ https://github.com/webpack-contrib/css-loader/issues/51 

Each extension will have a CSS file that imports what it needs. You declare this with the new `style` field. We don't ever import CSS files in JS except inside the generated dev mode file. 

Our recommended pattern is to declare a `style` key in your package.json that points to a CSS file.

Apputils has its own CSS, like the markdown colors, so the notebook package should import this as well.
