### ISSUE TITLE
Programatically execute cells

### ISSUE THREAD

**Issue by agentS** [jupyterlab/jupyterlab#6563]
Hi,

First of all, thank you so much for your work on this great open source planet. I really appreciate the effort you put into it.

I need to programmatically execute some cells in a notebook designed for presentations. However, I could not find any documentation on how to do this. [Jupyter Notebook allows executing cells using custom JavaScript](https://stackoverflow.com/questions/32714783/ipython-run-all-cells-below-from-a-widget), but this doesn't work in JupyterLab. I found [this StackOverflow question](https://stackoverflow.com/questions/53214644/jupyterlab-run-all-cells-below), but it does not have any answers.

I would be most grateful, if somebody could provide me an answer for the current JupyterLab version. Thank you!

**Comment by downiec** [comment]
Hi,

For JupyterLab 0.35 stable, I managed to execute cells within a notebook programmatically by first having a handle on the specific notebook, selecting the cell (so it's active), then executing the "notebook:run-cell" command in the command registry. I unfortunately can't point you to documentation on the proper way to do it, but I can point you to the functions I wrote that ended up working for me. Particularly the 'runCellAtIndex' function might help you see what I did. https://github.com/CDAT/jupyter-vcdat/blob/master/src/CellUtilities.ts

Please note that JupyterLab 1.0 is due to release soon and I plan to revisit these functions once it's released. Hope that is helpful!

**Comment by saulshanabrook** [comment]
@agentS thank you!  

In JupyterLab, you should create a custom extension that supports your workflow and have it render a custom mimetype that you define for your use case. See https://github.com/jupyterlab/jupyterlab/issues/4623 for the larger issue. I also just submitted a PR (https://github.com/jupyterlab/jupyterlab/pull/6596) to 
add some explanation to our FAQ around this question, we get it quite a bit. 

If you give some more context around what you are trying to achieve, I could try to give you some pointers on where to start.

**Comment by agentS** [comment]
@saulshanabrook Thank you so much for your answer.

I'll hopefully be able to work on this issue on Thursday or Friday. I'll send you more details then, but I know how to create basic JupyterLab extensions.
