### ISSUE TITLE
Tables should use tabular numbers

### ISSUE THREAD

**Issue by dansondergaard** [jupyterlab/jupyterlab#6570]
**Describe the bug**
Tables rendered in Jupyter Lab (likely also Jupyter Notebook), e.g. from pandas, do not use tabular numbers. This causes sorted columns to look unsorted and makes numbers harder to read and compare.

**To Reproduce**

Create a table like this:

<img width="299" alt="Screenshot 2019-06-14 at 08 38 42" src="https://user-images.githubusercontent.com/204911/59488447-dc541700-8e7f-11e9-8aff-50274888859c.png">

**Expected behavior**

With tabular numbers applied through CSS:

<img width="302" alt="Screenshot 2019-06-14 at 08 41 07" src="https://user-images.githubusercontent.com/204911/59488557-3228bf00-8e80-11e9-917d-62e6024233bf.png">

CSS used to apply tabular numbers:

```
table { font-variant-numeric: tabular-nums; }
```

**Screenshots**

Screenshots attached above.

**Desktop (please complete the following information):**

- OS: Any
- Browser: Any
- JupyterLab: Tested on 0.35.6, but probably applies to any version of Jupyter Lab

**Comment by saulshanabrook** [comment]
That sounds like a good idea. I believe that Pandas outputs that HTML and chooses what styles to apply, so I would open an issue there to describe this problem.

**Comment by TomAugspurger** [comment]
Pandas provides the HTML, but ever since Brian implemented the new styling the notebook / jupyterlab a few years ago, we've tried to keep things minimal: https://github.com/pandas-dev/pandas/blob/master/pandas/io/formats/html.py#L525. Basically, just things to handle pandas quirks like MultiIndexes. IIUC, the majority of the table style comes from jupyterlab.

Would this change be appropriate for all tables in a notebook (I'm not sure)?

**Comment by dansondergaard** [comment]
I think it would make sense for all tables in a notebook. For tables without numbers there would be no difference. For any table that contains numbers using tabular numerals improves readability significantly.
