### ISSUE TITLE
Styling shipped third-party React UI toolkit (i.e. Blueprint for now)

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6590]
This issue follows some discussion in PR https://github.com/jupyterlab/jupyterlab/pull/6389
@ellisonbg  @echarles 

**Describe the bug**

Currently JupyterLab ships with Blueprint JS as React-based UI toolkit. But the theme is not overwritten to fit JupyterLab theme. Starting from the hypothesis that introducing a third-party library as base for React UI component is a positive thing, I think it will harm JupyterLab project if that third-party toolkit is not modified to match JupyterLab style by default.

The current status is:
* when we use Blueprint component, styling them to fit JupyterLab style request to use explicitly Blueprint class names; for e.g. in the [PR](https://github.com/jupyterlab/jupyterlab/pull/6389/files#diff-edfc32797ef53c10b2d490a0dd9eccc5) or in the [`ui-components` package](https://github.com/jupyterlab/jupyterlab/blob/79e03992b2964063a917184072be3c8819cefa19/packages/ui-components/style/base.css#L59). Updating Blueprint may break it as such usage is not [advised](https://blueprintjs.com/docs/#core/classes) by Blueprint authors.
* author extensions will need to define style for standard blueprint components to be correctly integrated in JupyterLab. This could results in duplicating style or defining incoherent one.

This highlights the need to style the React UI toolkit within JupyterLab.

Looking at some of the [toolkits available](https://hackernoon.com/23-best-react-ui-component-libraries-and-frameworks-250a81b2ac42) out there, they are two strategies regarding styling: 

* using a theme component around the full react app or locally to overwritten the default theme (like [Material UI](https://material-ui.com/customization/themes/) or [Grommet](https://v2.grommet.io/))
* using SaSS or Less to define the toolkit style; like Blueprint, Ant or [Material Design for Web](https://material.io/develop/web/)

As JupyterLab is not a React application, only the second category seems the way to go.

In the aforementioned PR #6389, I propose to regenerate the Blueprint CSS after modifying the SaSS variables to match more closely the JupyterLab style. But it is not included in the final state as this needs discussion in this issue ;)

**Comment by echarles** [comment]
Thx @fcollonval for starting this discussion. Before going into the potential solutions, a description of the existing situation may be interesting (correct the following, I am sure it is approximative and contains errors and sorry if this bring more questions/confusion).

1. CSS loading order: Webpack packages the CSS in some order which are then loaded and applied by the browser. A CSS rule can overwrite a previously loaded rule. For now, jlab core and blueprints are shipped => What is the load order? For extensions, I guess the CSS are loaded after core/blueprint.

2. jlab core and blueprint (or other external library) clash/conflict: This happens when a rule overwrites and visually impacts the core rendering. This should be avoided => How to identify this (apart from visual inspection) and how to correct this (@fcollonval proposes regeneration after modifying the variables, another approach maybe to move the blueprint loading so jlab core can overwrite that and revert back to the correct rule -> this may impact the blueprint rendering).

3. When should we change the rendering? This is not obvious to me. I would say that if no CSS rule conflict is found, the normal rendering could be kept. How one can say a CSS must be changed for e.g. a [blueprint progress bar](https://blueprintjs.com/docs/#core/components/progress-bar)? Also I am personnaly not shocked seeing different look and feel in jlab - it may also clearly show that this is an external contribution (e.g. [plotly chart editor](https://raw.githubusercontent.com/plotly/jupyterlab-chart-editor/master/notebooks/ChartEditorExample.gif), but in this case the jlab theme will not work anymore (leading to next point).

4. Theme Manager: [office-ui theme manager](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Theming) is another example of react theme manager implementation. The value react could bring is to extend its [existing theme manager](https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/thememanager.ts) to react components, potentially proxing the management to an existing react theme manager.

**Comment by blink1073** [comment]
I'm afk this week, but the load order is @jupyterlab/application first, and then all extension packages in alphabetical order.

**Comment by blink1073** [comment]
cf https://github.com/jupyterlab/jupyterlab/blob/79e03992b2964063a917184072be3c8819cefa19/buildutils/src/build.ts#L209
