### ISSUE TITLE
JupyterLab 1.0 UX audit

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6593]
This is a general audit of usability.

CC @ellisonbg

**Comment by tgeorgeux** [comment]
This is a small gripe, but there's a consistency issue with the File Browser extension. The folder icons are square instead of rectangular like the icons elsewhere in JupyterLab. They're also outlined instead of filled. I think it would add some consistency at the very least to center them and use the correct ratio for a Material Icon. Attached picture for reference, see how the folder looks squashed in the file browser when compared to the new breadcrumbs.
<img width="348" alt="Screen Shot 2019-06-17 at 4 42 36 PM" src="https://user-images.githubusercontent.com/22109376/59646237-e3eb1880-912a-11e9-8038-3d4ad083ea56.png">

**Comment by tgeorgeux** [comment]
### UX Defect

When you make a new folder in the File Browser extension it automatically 'focusses' the folder after it's named. But something is wrong with that focus. Though the folder gets focus visually, if you press enter it doesn't open the folder. The gif below demonstrates. For context after I made the folder, I pressed enter to open it. Nothing hapened. I then clicked on the folder with my mouse once and pressed enter again. I don't know if other elements of focus are broken or not.

![filebrowserdefect](https://user-images.githubusercontent.com/22109376/59704145-4f2afe00-91b0-11e9-89fa-869034ac4f1f.gif)

**Comment by tgeorgeux** [comment]
### UX Enhancement - File Browser

I was testing the upload functionality and it doesn't look like you're able to upload an entire folder. Is this intentional behavior? 

I was using jakevdp's iPython Handbook as an example and it was pretty tedious to upload all the elements and remake the folder structure in the JupyterLab file browser.

**Comment by tgeorgeux** [comment]
### Command Pallette

**UX Deficiency - No easy way to clear search.**

**Context:** This came up when I was simulating a mouse-focused user on the command palette. 

**Problem:** If you click a heading it will insert the heading name into the search bar. There is no way to clear that with a mouse. You will need to select the text in the box and manually delete it. It's not uncommon for a text input field (such as a search) to not have a way to clear the field. It is a bit odd that you can accidentally fill out the input box (By clicking the header) with no clickable way to clear it. 

![CommandPalletteDeficiency](https://user-images.githubusercontent.com/22109376/59711291-aedcd580-91bf-11e9-8cdb-9b2b79dc9fa4.gif)

**Solution:** Add a small round (X) button that's clickable when text is in the input field that will allow users to quickly clear the text. This button should not be available when the input box is focussed, only on hover when the input box is unfocused.

**UX Defficiency (1) Defect (2) -  "..." Icon on headers in command palette**

**Context:** When you mouse over a header in the command palette, a "..." Icon appears to indicate you can filter the command palette by clicking on the dots or the header. Clicking will filter the search as shown above.

**Problem 1:** I'm not sure "..." is the correct icon usage here. When I saw the "..." icon I thought it was going to open a menu with more options. 

**Solution 1:** I think a "filter_list" icon makes more sense here. 
![baseline_filter_list_black_18dp](https://user-images.githubusercontent.com/22109376/59711878-d8e2c780-91c0-11e9-8b3c-36c825f3ef95.png)

**Problem 2:** If you're trying to click the icon that appears there's a very small window in which you can hit the icon without surfacing the slider. See the gif below.
![CommandPalletteDefect](https://user-images.githubusercontent.com/22109376/59712147-7807bf00-91c1-11e9-9db6-d24143a36ffe.gif)

**Solution 2:** This one's a bit trickier, one option would be to render the icons further left when the slider appears.

**Comment by tgeorgeux** [comment]
Closing as we have specific issues for these.
