### ISSUE TITLE
Clicking the terminal scrollbar does not scroll

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6674]
1. Open a terminal
2. Generate enough content so that the scrollbar appears
3. Try to drag the scrollbar with the mouse

What happens: the scrollbar doesn't move, but you end up selecting the text you are dragging over.

What should happen: the scrollbar should be clickable and draggable

**Comment by ian-r-rose** [comment]
Unfortunately, it looks like the culprit is the screen-reader mode for `xterm.js`, though I don't know why that is. I don't see any issues about it on that repo.

I see a few options in the short-term:
1. Live with the bad scrollbar behavior.
2. Revert screen-reader mode.
3. Expose screen-reader mode to the user as a setting, defaulting to `false` (maybe?)

I am leaning towards three, as it would fix the issue for most users, keep screen-reader mode for those who need it, and can be implemented quickly.

**Comment by ian-r-rose** [comment]
cf. https://github.com/jupyterlab/jupyterlab/pull/6359

**Comment by jasongrout** [comment]
+1 for 3 if we can implement it for 1.0, otherwise option 2.
