### ISSUE TITLE
Enable Publish from Windows

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6733]
We should support publishing from a Windows machine.  We ran into https://bugs.python.org/issue31226 when trying to publish 1.0.0.

For dev_mode, we should have a `clean:node` command that removes all node_modules.  This should be called before trying to create the `sdist` if on Windows: https://github.com/jupyterlab/jupyterlab/blob/e2fd4c8841a7393f9131fb6b6e8252864a8bd351/buildutils/src/publish.ts#L53.

We can refactor the logic [here](https://github.com/jupyterlab/jupyterlab/blob/master/clean.py#L8) used for `clean:slate` into a node module that also calls `rmdir` in a child_process.

**Comment by blink1073** [comment]
@vidartf, you want to take this one?

**Comment by vidartf** [comment]
Sure. I don't think I have publish rights, but if I do, could you disable them? 😄

**Comment by blink1073** [comment]
I confirmed you don't have access :wink:

**Comment by blink1073** [comment]
I think we'll need a `--dry-run` flag for `publish.ts` that prints the lerna publish command instead of printing it.  We could then run it on CI too

**Comment by blink1073** [comment]
Note that the CI would have to be run when there are no local version changes, since we need published packages for core_mode.

**Comment by vidartf** [comment]
Troubleshooting log entry 1:
- The original attribution to the linked BPO was in error. I basically got confused by the `os.unlink` call that failed, which is the same as `os.remove` (deletion).
- The reason this fails is due to the following circularity:
  - `jlpm [publish-all]` is run
  - `jlpm` on Windows is a Python entry-point that maps to the vendored `yarn`
  - one of the sub-commands that is run is `pip install -e .`
  - the pip install sees that there is already an installation of lab, that it tries to uninstall
  - during the uninstall, `jlpm.exe` is moved to a temporary directory
  - on successful installation, the uninstall is committed, which will try to delete (`unlink()`) jlpm.exe
  - As `jlpm.exe` is currently running (parent process), Windows disallows the deletion of the file.

**Comment by vidartf** [comment]
Repro: The command `jlpm run clean:slate` always fails on Windows.

**Comment by vidartf** [comment]
Troubleshooting log entry 2:
- Actually, the logic is different than what I outlined above. Here's the breaking logic in `jlpm run clean:slate`:
  - First, the git dir is cleaned. This removes the local egg info.
  - Then it tries to uninstall jupyterlab. This fails with `Skipping jupyterlab as it is not installed.` since it does not find the egg info.
  - Then, lab is reinstalled with `pip install -e .`. This recreates the egg-info, and then finds something to uninstall, since the egg info is now there.
  - That uninstall fails since it is trying to remove files based on the egg info it just generated?

I'm a bit unsure about exactly what causes it to fail in the end, but moving the `pip uninstall` command above the `git clean` command in `clean.py` seems to fix the issue.

**Comment by vidartf** [comment]
Troubleshooting log entry 3:
 - Seems my fix in entry 2 didn't actually work, it just moved the timing of the exception such that it didn't cause the entire process to fail (the exception ended up being ignored). The issue in entry 1 seems to be the main fault after all.

**Comment by vidartf** [comment]
Xref: https://stackoverflow.com/questions/1606140/how-can-a-program-delete-its-own-executable

**Comment by vidartf** [comment]
Solution outline:
- Replace all calls to `jlpm` with `npm` in all paths that use `clean:slate`. If the `jlpm` entry point is not used to invoke the command, the executable can be replaced.

PR incoming after some more testing.

**Comment by vidartf** [comment]
@blink1073 I think some of your comments are still not resolved, but maybe not relevant to fixing Windows build. Do you want to reopen or move them to a new issue?

**Comment by blink1073** [comment]
I'll make a new issue
