### ISSUE TITLE
Pressing "End" when selecting multiplle cells does not expand selection

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#6783]
When navigating notebook <kbd>Up</kbd> an <kbd>Down</kbd> arrows move us one cell up or down; pressing <kbd>Home</kbd> or <kbd>End</kbd> quickly scrolls up to the beginning or end of the notebokok.

If we select cells in a notebook, we can extend the selection down with <kbd>Shift</kbd> + <kbd>Down</kbd> or reduce it with <kbd>Shift</kbd> + <kbd>Up</kbd> (and vice versa when going up from the starting cell).

However, <kbd>Shift</kbd> + <kbd>End</kbd> does not select all the cells until the end of the notebook (and <kbd>Shift</kbd> + <kbd>Home</kbd> does not select cells till the begining).

**Expected behavior**
I would expect the <kbd>Shift</kbd> + <kbd>Home/End</kbd> to select all cell in specified direction, just as if I were repeating <kbd>Shift</kbd> + <kbd>Up/Down</kbd> until reaching the begining/end of he notebook.

**Desktop (please complete the following information):**

- OS: Ubuntu 19.04
- Browser: Chrome 70+
- JupyterLab: 1.0.1

**Comment by ian-r-rose** [comment]
I think this is a nice idea @krassowski (though I would expect this behavior on PageUp and PageDown, rather than Home and End, which is how my text editor behaves).

I think this would be a good issue for an advanced new contributor.
One would add new commands to the command registry to select all above/below, mimicking these commands:
https://github.com/jupyterlab/jupyterlab/blob/079115dd36705f11067ebfd9c34f783719f1775a/packages/notebook-extension/src/index.ts#L1446-L1467

The notebook actions `extendSelectionAbove` and `extendSelectionBelow` could be enhanced to take an option for whether to extend just one cell, multiple cells, or to the top/bottom:
https://github.com/jupyterlab/jupyterlab/blob/079115dd36705f11067ebfd9c34f783719f1775a/packages/notebook/src/actions.tsx#L718-L766

Then one would add a keyboard shortcut that checks for the up/down arrows and pageup/pagedown/home/end:
https://github.com/jupyterlab/jupyterlab/blob/079115dd36705f11067ebfd9c34f783719f1775a/packages/notebook-extension/schema/tracker.json#L80-L99

**Comment by jasongrout** [comment]
Fixed in #7177
