### ISSUE TITLE
Cannot save Jupyter Lab user preferences for custom shortcuts

### ISSUE THREAD

**Issue by somghosh** [jupyterlab/jupyterlab#6865]
**Describe the bug**
Cannot save Jupyter Lab user preferences for custom shortcuts 

**To Reproduce**
I have recorded this screencast as it will help the best: https://youtu.be/qixcS2jeQQs

I am entering in the User Preferences box

```
{
            "command": "application:toggle-left-area",
            "keys": [
                "Accel P"
            ],
           "selector": "body"
 }

```

**Expected behavior**
The User settings json area will not activate teh Save button upon entering of a valid json
The error shown will be
```[additional property error]  command is not a valid property```

**Screenshots**
https://youtu.be/qixcS2jeQQs

**Desktop (please complete the following information):**

- OS: MacOS 10.14.4
- Browser : Chrome 75.0.3770.100
- JupyterLab Version 1.0.2

**Comment by ian-r-rose** [comment]
Hi @somghosh, thanks for the report, and the very clear video. The issue appears to be that your JSON setting is not nested within the `"shortcuts"` list. So your example should instead be something like:
```json
{
       "shortcuts": [
        {
            "command": "application:toggle-left-area",
            "keys": [
                "Accel P"
            ],
            "selector": "body"
        }
    ]
}
```
Sorry if the documentation about that was not clear -- PRs welcome to clarify it!

Long-term, we have plans to dust of a shortcut editor UI that some interns made and migrate it into core JupyterLab so that users don't have to write raw JSON5, but for the time being, this is what we have.

**Comment by drunkwretch** [comment]
> Hi @somghosh, thanks for the report, and the very clear video. The issue appears to be that your JSON setting is not nested within the `"shortcuts"` list. So your example should instead be something like:
> 
> ```json
> {
>        "shortcuts": [
>         {
>             "command": "application:toggle-left-area",
>             "keys": [
>                 "Accel P"
>             ],
>             "selector": "body"
>         }
>     ]
> }
> ```
> 
> Sorry if the documentation about that was not clear -- PRs welcome to clarify it!
> 
> Long-term, we have plans to dust of a shortcut editor UI that some interns made and migrate it into core JupyterLab so that users don't have to write raw JSON5, but for the time being, this is what we have.

thanks , i came across the same problem, and now fix it according to your reply .

**Comment by evertrol** [comment]
To note (as I just spent some time searching for this new format): the documentation still points to a video showing the old style of adding keyboard shortcuts, at https://jupyterlab.readthedocs.io/en/stable/user/interface.html?highlight=keyboard#keyboard-shortcuts

Perhaps this is already a PR or another issue, but the documentation seems to be behind the JupyterLab 1.0 release.

(Additional note: I was hesitant to try something along the above lines, since it feels as if the default "shortcuts" array is overridden with the user one; it is not immediately clear that, apparently, the system default and user arrays are merged. Contrast it with objects, where merging feels more evident.)

**Comment by goudantongxue** [comment]
what if  I want to save several shortcuts at one time? what should I do? I coded as follows, but it seems that the first shortcut doesn't work.

{
       "shortcuts": [
        {
        "command": "notebook:move-cell-down",
        "keys": [
        "Alt J"
        ],
        "selector": ".jp-Notebook:focus",
        "title": "Move Cells Down",
        "category": "Notebook Cell Operations" 
        }
    ],     
        "shortcuts": [
        {
        "command": "notebook:move-cell-up",
        "keys": [
        "Alt K"
        ],
        "selector": ".jp-Notebook:focus",
        "title": "Move Cells Down",
        "category": "Notebook Cell Operations"
        }
    ]
}

**Comment by telamonian** [comment]
@goudantongxue You need to format it so that there's one `"shortcuts"` list with several entries:

```
{
    "shortcuts": [
        {
            "command": "notebook:move-cell-down",
            "keys": [
                "Alt J"
            ],
            "selector": ".jp-Notebook:focus",
            "title": "Move Cells Down",
            "category": "Notebook Cell Operations"
        },
        {
            "command": "notebook:move-cell-up",
            "keys": [
                "Alt K"
            ],
            "selector": ".jp-Notebook:focus",
            "title": "Move Cells Down",
            "category": "Notebook Cell Operations"
        }
    ]
}

I'm going to close this issue as solved. If anyone runs into any more trouble with these settings please feel free to open a new issue
```
