### ISSUE TITLE
Document that you should use ^ in extension dependencies

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#6885]
In our meeting today we were talking about how all extensions should depend on JL/Phosphor packages using the `^` NPM version specifier, like `^1.1.0`. That way, if we release a new minor or patch version of one of our packages, the extension will install properly.

**Comment by vidartf** [comment]
A main motivation point for this is also that we want to do synchronized (lock-step) bumping of minor versions across all packages in order to reduce the maintenance burden. This will lead to some churn on the minor version releases (some releases being "empty" for certain JS packages), so using the `~` dependency would be rough for extension devs.
