### ISSUE TITLE
Find/Replace missing RegEx group reference

### ISSUE THREAD

**Issue by LukaPitamic** [jupyterlab/jupyterlab#6936]
In Jupyter notebook RegEx works like a charm, Jupyter Lab struggles...

RegEx **Find** works in both, but referencing string groups in **Replace** only works in Notebook. In Jupyter Lab it is replaced with exact replace string, not referenced string groups.

![image](https://user-images.githubusercontent.com/34914144/62393626-36a55600-b55a-11e9-8984-c56b2bdc06cf.png)

**Replaced results are...**
Jupyter Notebook: 
`1st is: var1 ; 2nd is: var2` <-- OK!
Jupyter Lab: 
`1st is: $1; 2nd is: $2` <-- **_exact_** replace string instead of **_RegEx_** referenced **_group_** string

**Comment by jasongrout** [comment]
CC @aschlaep

**Comment by jasongrout** [comment]
Thanks for pointing this out!

**Comment by HamsteRider-m** [comment]
so is this problem solved yet?

**Comment by agoose77** [comment]
I'm working on other deadlines at the moment, but I think the patch itself could be quite simple: 
http://www.mergely.com/MpZ2Sn60/

**Comment by LukaPitamic** [comment]
Just tested it on JLab v2.0.2, and still does not work. 

Groups are not recognised.
Work around is to open notebook in Classic Notebook (menu/Help/Launch Classic Notebook) and do RegEx transformations there, save and reload notebook back in JupyterLab.

**Comment by kenahoo** [comment]
Could this issue get a little love?  Looks like it's still not fixed in Jupyter Lab 2.2.8.

**Comment by LukaPitamic** [comment]
@kenahoo +1 for issue love, I’m still throwing back and forward between JL and classic notebook quite often

**Comment by jasongrout** [comment]
+1 also for issue love. But what we'd really appreciate and welcome is a PR.

**Comment by kenahoo** [comment]
@jasongrout it looks like there’s already a proposed implementation, is it suitable?

**Comment by jasongrout** [comment]
I think the comment was pointing to the place in the jlab codebase where replaces happened, and pointing out that the codemirror implementation linked might provide some inspiration for how replacing groups could be implemented.

**Comment by LukaPitamic** [comment]
Love has different faces, but it’s still love

**Comment by jasongrout** [comment]
> Love has different faces, but it’s still love

Sorry, I didn't mean to be offensive, if that was how my comment was taken.

To move this issue forward, we'd welcome a PR.

**Comment by LukaPitamic** [comment]
@jasongrout no, no, it was a joke really - probably there is no place for it here in tech community. I apologize. I would love to make a PR, but haven’t done it yet. As I’m googling forking it out would not make any sense for me since I have no idea what to do afterwards - therefore there is nothing to be expected to merge. Or am I getting this totally wrong. Again.

**Comment by jasongrout** [comment]
> no, no, it was a joke really - probably there is no place for it here in tech community.

No problem, just wanted to make sure communication is clear.

Our new contributor guide is at https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html

**Comment by sssimonyang** [comment]
I have installed the latest version jupyter lab 3.0.11 but it still can't reference string groups in Replace.

**Comment by chestergan** [comment]
> I have installed the latest version jupyter lab 3.0.11 but it still can't reference string groups in Replace.

It's 21st May 2021. I am using Jupyter Lab 3.0.14 and it still does not allow me to reference string groups in replace.

**Comment by agoose77** [comment]
No-one has yet contributed a fix to resolve this, which is why it doesn't work yet :)

**Comment by chenyulue** [comment]
Jupyter lab 3.4.2 still has the issue.

**Comment by agoose77** [comment]
> No-one has yet contributed a fix to resolve this, which is why it doesn't work yet :)

:)

**Comment by amueller** [comment]
I'm a total TS newbie, so please bear with me. It looks to me that ``RegExpExecArray.groups`` is only available for ``ES2018`` if I look at [this PR](https://github.com/microsoft/TypeScript/pull/22176/files), while the global target is set to ``ES2017``. Am I missing something and/or what would be the solution?

**Comment by amueller** [comment]
Ok so we're passing around a list of `ISearchMatch` which contains only the match and the index, but not the groups. Should we pass around an extension of `ISearchMatch` that also contains the groups instead?

**Comment by agoose77** [comment]
@amueller IIRC https://github.com/jupyterlab/jupyterlab/blob/37c7a647a1344712c8cf80414db73809f486e766/packages/documentsearch/src/providers/codemirrorsearchprovider.ts#L218 `findNext` should return the match object in the case that a regular expression was passed as the query. You could then use that object to construct the replacement pattern.

**Comment by amueller** [comment]
Ok, thanks for confirming. I've been struggling a bit with that because it seems kind of integrated with the codemirror provider. Any pointers would be appreciated.

**Comment by agoose77** [comment]
I haven't been involved with new search provider system, so I could be slightly off here. 

Having looked over the source, it's not immediately clear that `ISearchMatch` needs to have any group-awareness. The core `SearchProvider` interface doesn't expose the match object when performing find and replace, which is where groups would be useful. It does expose `ISearchMatch` objects during highlighting, where groups are less useful. However, I think it's reasonable that a regex-matching interface should expose the matched groups. 

So, from my perspective, we want to add an additional `groups` field (or perhaps the regex match itself) to `ISearchMatch`. That definition is [here](https://github.com/jupyterlab/jupyterlab/blob/43f784a35b5ec474f5a94433c5d2d4d6d712cbc8/packages/documentsearch/src/tokens.ts#L129-L139).

It looks as though the text search providers employ the [`TextSearchEngine`](https://github.com/jupyterlab/jupyterlab/blob/a6f634ea807ec89bc6f3cfe4ff986818d13eda28/packages/documentsearch/src/providers/textprovider.ts) to generate matches, so that's one place where we need to store the new field on the `ISearchMatch` object.

The strategy here would be to look at all of the implementations of `SearchProvider` and update the places that they construct an `ISearchMatch` object:

- https://github.com/jupyterlab/jupyterlab/blob/22bc71d1c8481bf847e33d2e1603f10e5b510f11/packages/codemirror/src/searchprovider.ts
- https://github.com/jupyterlab/jupyterlab/blob/22bc71d1c8481bf847e33d2e1603f10e5b510f11/packages/fileeditor/src/searchprovider.ts
- https://github.com/jupyterlab/jupyterlab/blob/22bc71d1c8481bf847e33d2e1603f10e5b510f11/packages/cells/src/searchprovider.ts
- https://github.com/jupyterlab/jupyterlab/blob/22bc71d1c8481bf847e33d2e1603f10e5b510f11/packages/csvviewer-extension/src/searchprovider.ts
- https://github.com/jupyterlab/jupyterlab/blob/22bc71d1c8481bf847e33d2e1603f10e5b510f11/packages/documentsearch/src/providers/genericsearchprovider.ts
- https://github.com/jupyterlab/jupyterlab/blob/22bc71d1c8481bf847e33d2e1603f10e5b510f11/packages/documentsearch/src/searchprovider.ts
- https://github.com/jupyterlab/jupyterlab/blob/22bc71d1c8481bf847e33d2e1603f10e5b510f11/packages/notebook/src/searchprovider.ts

Only a few of these actually need changes for `ISearchMatch` - many just wrap around other search providers or similar concepts like the "text search engine".

If you change the signature of `ISearchMatch` to require the regex match (or groups), the TypeScript compiler should tell you which packages need fixing to provide that field. 

The next step is then to use the matched groups in the replacement logic.

@fcollonval might be able to provide some more tips / hints, as he authored the original implementation IIRC

**Comment by fcollonval** [comment]
Thanks for the ping Angus

We have two choices here. Either we increase transient memory by storing the groups. Or we reapply on the fly the query on a text match for replacement.

I lean towards the second one to have a small PR and no need to change the API.

For example, for `CellSearchProvider.replaceCurrentMatch` at

https://github.com/jupyterlab/jupyterlab/blob/master/packages/cells/src/searchprovider.ts#L236

We will replace it by:

```diff
          this.cell.model.value.text =
            this.cell.model.value.text.slice(0, match!.position) +
-           newText +
+           match!.text.replace(this.query, newText) +
            this.cell.model.value.text.slice(
              match!.position + match!.text.length
            );
```

Similarly for `CellSearchProvider.replaceAllMatches`

For `CodeMirrorSearchProvider.replaceCurrentMatch` at

https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/searchprovider.ts#L210

```diff
-       cursor.replace(newText);
+       const orig = this.editor.doc.getRange(cursor.pos.from, cursor.pos.to);
+       cursor.replace(orig.replace(this._query, newText);
```

and similarly for `replaceAllMatches`

Other places don't matter as they do not support replacement.

**Comment by amueller** [comment]
@fcollonval did you want to do the PR given that you already posted the fix, or should I open one?

I think your solution seems more straightforward and probably easier to do and maintain.

**Comment by amueller** [comment]
Would love to, worst case during the sprints (assuming *someone* will sprint at SciPy) but I'll try to do it today.

**Comment by amueller** [comment]
Hm so I'm trying to just run the current main branch and doing any replace, even without capture groups, hangs the notebook, so I'm a bit stumped. It seems none of the jupyter lab folks are around at the scipy sprints any more, so I'll give it another go next week.

**Comment by itcloudmanagement** [comment]
Hi guys, Is this fixed ?
