### ISSUE TITLE
[Feature Request] Workspace name in title

### ISSUE THREAD

**Issue by nehz** [jupyterlab/jupyterlab#6946]
Working with a few different workspaces in different tabs, it would be useful to have the name of the workspace in the tab/window name.

Current behaviour: Page title = "JupyterLab"
Proposed behaviour: Page title = "JupyterLab - [WORKSPACE_NAME]"

**Comment by mlucool** [comment]
I'd like to propose something similar here, but also handle the auto workspace.

If there is a workspace name, the notebook title should be: "[WORKSPACE_NAME] - JupyterLab" (This is flipped because it makes it easier to find when you have many tabs)
If the workspace is an "auto" workspace, it should be named by the last active document and include the other notebooks in some respect e.g. "Foo and 3 others - JupyterLab"

**Comment by saulshanabrook** [comment]
That sounds good. We should bring this up at a weekly meeting to see if there is any immediate feedback, and start on a PR to try to implement this!

**Comment by Carreau** [comment]
If I may suggest, provide good default, but let user provide a template string into which variables will be interpolated, with known interpolation target like `workspace`, `current_document`, etc....

**Comment by saulshanabrook** [comment]
From Brian in meeting:

In single document PR there are many ways to monitor active title of document, so we could look at that to see how to implement. 

Would need to watch the current document and for rename events, and we create a signal for this.

From Tony: It could help in screen shares, to know which window to share. So this would help me a lot.

Agreement from Isabela, Tim, and Max about that makes sense to include workspace name.

**Comment by goanpeca** [comment]
I can work on this :-)

**Comment by isabela-pf** [comment]
I agree that "[WORKSPACE_NAME] - JupyterLab" is the better approach. 

While I think this is a good step in helping users manage multiple open JupyterLabs, I also would be interested in thinking about more options (as in user choice, not default) for users to take advantage of so that they can tell at a glance what JupyterLab (or more Jupyters?) they are opening. That's another issue, but I wanted to bring the idea up in case anyone else felt similarly.

**Comment by bollwyvl** [comment]
@isabela-pf very cool idea: I wonder if status bar items could be re-purposed for this to not create "another thing" or become a template nightmare? At present, it looks like the status bar is just the typestyle nonsense selectors in there, but if, like main-area widgets, these demanded an id, they could be referenced unamibguously (and be easier to test).

So the current default today might be:
```yaml
"@jupyterlab/some-appropriate-extension":
  browser-title:
    - JupyterLab
```

I could _also_ imagine making the favicon configurable in this way... the ⌛ doesn't say much, sometimes.

So a future one could be:
```yaml
"@jupyterlab/some-appropriate-extension":
  favicon:
    - status-item: jp-status-docmanager-current-kernel-status
  browser-title:
    - status-item: jp-status-docmanager-current-document
    - status-item: jp-status-docmanager-current-workspace
```

If these widgets also had `title`s, they could become draggable/reorderable tabs (perhaps hidden behind a mode).

**Comment by goanpeca** [comment]
For now I added `+ N` to denote all the items. Did not make a distinction between the items.

![title](https://user-images.githubusercontent.com/3627835/90582688-0267fc00-e194-11ea-90b5-4e16012fc6fb.gif)

Plus one with emojis in the name, because @tonyfast :-p 

![image](https://user-images.githubusercontent.com/3627835/90582724-14e23580-e194-11ea-8b19-469e35c04aba.png)

**Comment by isabela-pf** [comment]
This came up in this week's JupyterLab team meeting (thanks @jess-x!). We needed to clarify the UX we were thinking for this because the PR looks like it is putting document names in title and not workspaces as this issue title requests. Here's the behavior we were imagining:

- When a non-default workspace is open, the title will read "[workspace name] - JupyterLab"
- When a default workspace(s) is open, the title will read "[active document name + number more] - JupyterLab"

This is because workspaces as they are now are not very discoverable and users can easily use JupyterLab without ever being aware of workspaces. If they are not aware of workspaces, starting a title with the workspace name is confusing; this is especially true if they are default ones, because several tabs with "auto" or "default" or similar terms doesn't give any useful information. Saying what file is active provides much more relevant information.

Hope that help clears it up!

**Comment by krassowski** [comment]
Straying away from  the discussion on defaults, I see there is a preference towards user-customisable template. Are there any lumino/jupyterlab internals that could be used for safe templating of user-provided strings at runtime?

**Comment by jess-x** [comment]
#10002 added the active document name and workspaces to title Bar :)

**Comment by blink1073** [comment]
Indeed, thanks again @jess-x!
