### ISSUE TITLE
New Icon for Command Palette

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#7038]
We need a better Icon for the Command Palette. The current "artists palette" doesn't very clearly communicate what's going on. This issue was brought up in [Another Repo](https://github.com/jupytercalpoly/jupyterlab-richtext-mode/issues/17) by @isabela-pf . 

Opening this up as a place to discuss alternatives.

**Comment by isabela-pf** [comment]
I want to make sure this issue is up to date with the previous discussions on this topic I have found. First is issue [#5269](https://github.com/jupyterlab/jupyterlab/issues/5269) which discusses multiple icon improvements (some of which have been implemented in 1.0) including potential replacements for the command palette. I also found [this comment on PR #5920](https://github.com/jupyterlab/jupyterlab/pull/5920#issuecomment-467103886) helpful for understanding why previous attempts have failed and what the conceptual goals for the command palette are.

**Comment by isabela-pf** [comment]
After reviewing existing Material Icons, I've found that they do not have an icon that closely communicates what the command palette does. Here are two options based on existing icons and the idea that the a good icon for the command palette represents it as a ["set of things you can use in your work."](https://github.com/jupyterlab/jupyterlab/pull/5920#issuecomment-467103886)

The first icon combines the searching aspect of the command palette with the standard icon for a command. Its main weakness is that it focuses on code when the command palette has a greater scope than code alone.

![Search + Square 28x](https://user-images.githubusercontent.com/50221806/64991211-4cf73f00-d886-11e9-8f8d-1d8eab0f8a1e.png)

![context1](https://user-images.githubusercontent.com/50221806/64991277-6d26fe00-d886-11e9-9266-c44e47fa9b71.png)

The second icon continues to reference searching and replaces the reference to code with Material Icons' existing icon ["list."](https://material.io/resources/icons/?search=list&icon=list&style=baseline) This approach more closely addresses the "set of things" idea. Its main weakness is that representing the command palette as a list may be too vague. 

![Search + Square 78](https://user-images.githubusercontent.com/50221806/64991288-744e0c00-d886-11e9-8335-5c1bb4f63197.png)

![context2](https://user-images.githubusercontent.com/50221806/64991299-7a43ed00-d886-11e9-8b4c-1fffbbb7abdd.png)

**Comment by tgeorgeux** [comment]
I think both of those are better than what we are currently using. I tend to prefer the second one as it matches what's going on more clearly (searching a list). 

The first one looks more like searching for something in code or in console output for something.
