### ISSUE TITLE
New Experience for Command Palette

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#7039]
Resurrecting some discussion around the idea of modal Command Palette #4851 . 

I think the current Command Palette is disjointed from the where it may be having an effect, a single modal window similar to VSCode, Sublime, Classic Notebook etc. is worth exploring.

@isabela-sf @javag97

**Comment by mlucool** [comment]
Should modals be made into a first class place to add a widget? I could see a few other non-core extensions that work better as modals then as main/side panel widgets.

**Comment by tgeorgeux** [comment]
@mlucool yes, we need to think about modals in general, in this process we hope to define both a modal class and a command palette class to lay over the top of that. 

Here are some example command palette interfaces to get our thinking started.
![Uploading using_command_palette.jpg…]()
<img width="770" alt="Screen Shot 2020-01-09 at 1 54 42 PM" src="https://user-images.githubusercontent.com/22109376/73403112-9d09f780-42a3-11ea-9fea-8b118c2ae558.png">
<img width="820" alt="Screen Shot 2020-01-09 at 1 55 01 PM" src="https://user-images.githubusercontent.com/22109376/73403113-9d09f780-42a3-11ea-97b5-668e84c608c8.png">
![Screen-Shot-2017-12-04-at-08 11 52](https://user-images.githubusercontent.com/22109376/73403114-9d09f780-42a3-11ea-86b8-16abbc595c78.png)
<img width="773" alt="Screen Shot 2020-01-09 at 1 54 28 PM" src="https://user-images.githubusercontent.com/22109376/73403115-9d09f780-42a3-11ea-95a2-719f40f294a0.png">

**Comment by isabela-pf** [comment]
I've started grappling with the current state of JupyterLab's command palette and collecting what comparable interfaces function and look like. Here's where I am now:

Talking to @tgeorgeux and reading [this article](https://robdodson.me/command-palettes/) he sent left me with a few ideas to keep in mind.

- Changing the command palette experience includes thinking about modals in JupyterLab in general in addition to the command palette-specific needs. (This is mentioned on the last comment, but worth reiterating.)
- Accessibility concerns need to be at the foundation of exploring this new experience.

I also collected comparable interfaces for reference.
**VS Code**
<img width="619" alt="vsCode1" src="https://user-images.githubusercontent.com/50221806/73413142-a86b1c00-42bf-11ea-9ba5-ca3ee412a2c8.png">
<img width="618" alt="vsCode2" src="https://user-images.githubusercontent.com/50221806/73413143-a86b1c00-42bf-11ea-9bf0-4aeeacf59dc7.png">
<img width="610" alt="vsCode3" src="https://user-images.githubusercontent.com/50221806/73413144-a86b1c00-42bf-11ea-9237-c35fab1f91de.png">
<img width="615" alt="vsCode4" src="https://user-images.githubusercontent.com/50221806/73413145-a86b1c00-42bf-11ea-8a49-c5e479b02b38.png">

**Mac OS**
<img width="361" alt="macOS1" src="https://user-images.githubusercontent.com/50221806/73413217-dcded800-42bf-11ea-9525-c4b18fd770de.png">
<img width="711" alt="macOS2" src="https://user-images.githubusercontent.com/50221806/73413218-dcded800-42bf-11ea-9a0a-83fe7b5a4cf9.png">

**Jupyter Notebook**
Taken from [here](https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/).
![jnb1](https://user-images.githubusercontent.com/50221806/73413269-fda72d80-42bf-11ea-8b55-73fed7dfe0ea.gif)

Because this needs to fit with JupyterLab as a whole, I reviewed Material Design's components (I find it helpful to use [this page as a visual glossary](https://material.io/components/)) to find most closely matches the experience needed for a command palette. It seems like we are pursuing an experience most like the [simple dialog](https://material.io/components/dialogs/#simple-dialog), but maybe with some of the recommendations for the [dropdown menu](https://material.io/components/menus/#dropdown-menu) or [cards](https://material.io/components/cards/#) for more specific command palette activities.

Looking at different interfaces has also made me consider what might be basic considerations that are key to positive command palette experiences, such as:
-  Keep fuzzy search.
-  Make it easy to leave the command palette. Do not just rely on users clicking away.
 - Put the dialog directly in the line of sight, over the document but without obscuring menus is ideal.
- Having Help options available from the command palette. See VS Code's use of '?' to quickly bring up help (above).

**Comment by isabela-pf** [comment]
Since I last commented, I've been thinking through the use of the command palette by considering what activities users might visit the command palette for. I'd love to get feedback on their accuracy or what might be missing.
1. Complete any action in JupyterLab (User is familiar with JupyterLab)
1. Complete an action in JupyterLab that does not have a configured shortcut (User is familiar with JupyterLab)
1. Complete an action in JupyterLab that the user does not use on a daily basis and/or does not know how to access it elsewhere (User familiar with JupyterLab)
1. Find a new or unfamiliar action in JupyterLab (search) (User could be familiar with or new to JupyterLab)

I started to sketch out some early ideas, but found I had a lot of ideas about the content of the command palette that I couldn't confirm or deny were true, so I started an [inventory](https://airtable.com/invite/l?inviteId=inv6VRrH2sJ4e2Hdz&inviteToken=09a2c782157eb958469c545e7546fd75fe215a77dc850b3ed5cbb79e9f57b04f) of what is in the command palette (and tracked some things that were not). It's a work in progress, but it's helping me sort through what is there more effectively. 

Next steps include making better/more complete mockups to share here. So far I've worked mostly with the hybrid Material Design specs I mentioned in my previous comment.

**Comment by isabela-pf** [comment]
This is still one of several works in progress, but I want to share this so you can see where I am now.

![cp3](https://user-images.githubusercontent.com/50221806/74393258-6e6d4000-4dbe-11ea-9e0f-26b54bc86c7b.png)


Changes include moving and lowering the emphasis of the search icon, removing current command palette headings (I'm very unsure about this), and proper elevation for dialogs in Material Design.

**Comment by dhirschfeld** [comment]
Showing the keyboard shortcuts (if configured) is also very useful (vscode does this above).

**Comment by javag97** [comment]
Hello @isabela-pf! I hope all is well at CP Jupyter. I believe what you currently showed to be a considerable improvement from the current command palette. Your latest design iteration reminds me of the spotlight search feature from the macOS environment. 
1.  I agree with the comment regarding keyboard shortcuts. I imagine this has been talked about internally yes? 
1. With this new design, how do users get this  "floating" search pop up?
1. Minor visual critique. I don't know if this is just me, but the listed search elements feel a little close. I think this has to do with having no border and the elongated type. Have you tried playing around with that spacing? I'm not sure if it would look better, but that was my first thought. 

Say hi to Zack and Tim for me!

**Comment by isabela-pf** [comment]
@dhirschfeld You are absolutely right! I made the mistake of choosing example commands that do not have default configured shortcuts (so the space is empty), but I will make sure to include ones with shortcuts on the next mockup. Thank you for pointing that out.

**Comment by isabela-pf** [comment]
Hi from Jupyter Cal Poly @javag97 ! It's great to hear from you. And you are correct, what I looked at for comparable designs included the macOS spotlight search. In response to your questions

1. Yes, keyboard shortcuts will be shown when applicable. I chose poor example commands for this.
1. How users get here is something I am still flexible on, but I do think it could be opened the same way the command palette is currently opened: either with crtl/cmd + shift + C or by clicking the icon on the left side bar.
 1. That's good feedback about spacing; I'll adjust my mockup.

**Comment by isabela-pf** [comment]
Here's an updated mockup based on the current feedback:

![cp2](https://user-images.githubusercontent.com/50221806/74892176-b8fe3780-533d-11ea-87df-10af3106819f.png)

**Comment by dhirschfeld** [comment]
As to how users find out how to open the command palette, I still quite like the idea of a default background advertising important shortcuts - #5524

**Comment by isabela-pf** [comment]
@dhirschfeld I like that approach too, especially since I found multiple times users reported not finding the command palette or its shortcut when looking into issues associated with the command palette. I've seen #5524 before, and thought there had been more work done on it. I'll put it on my list to explore, though I will likely follow up on that issue when I get there.

**Comment by ellisonbg** [comment]
OK, have a prototype of a modal command palette working:

![Screen Shot 2020-08-10 at 10 52 12 PM](https://user-images.githubusercontent.com/27600/89862173-3f147180-db5c-11ea-9cab-df0070e359a1.png)

Lots of fine tuning (keyboard, focus, styling), but the initial exploration was straightforward and doesn't break any APIs. Should be able to polish this for 3.0.

**Comment by krassowski** [comment]
Should icons be displayed in the palette? Like in the context menu (e.g. icons to the left, ticks if needed to the right). It seems that they were there in classic notebook (for some commands).

**Comment by ellisonbg** [comment]
I do think we should display icons in the palette, but we will have to make that change to the underlying widget in lumino.

**Comment by vidartf** [comment]
> **Jupyter Notebook**
> Taken from [here](https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/).
> ![jnb1](https://user-images.githubusercontent.com/50221806/73413269-fda72d80-42bf-11ea-8b55-73fed7dfe0ea.gif)
> 

As a note: I keep forgetting that classic notebook as a command palette, although that might be because I don't need anything from it (?).

**Comment by isabela-pf** [comment]
It's so exciting to see that there's a prototype for this! From the little bit I'm seeing, I want to +1 including icons when relevant as well as shortcuts in a final version.

As mentioned in this week's team meeting, what options are currently being planned to open the command palette? I imagine the shortcut is staying, but should it also have a place in the menu bar or keep the button's current left sidebar placement? I do think there needs to be at least one option other than the shortcut being used.

**Comment by ellisonbg** [comment]
The command palette has been changed for 3.0 in significant ways, and I think most of the feedback here has been taken into account. I am going to close this and if there are further changes we want to make moving forward, let's open up new issues that reference the new state of the command palette in 3.0 as the baseline.
