### ISSUE TITLE
Refactor the code completer API

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#7044]
## Description

I propose that instead of passing list of string matches, and a JSON object of metadata to the completer, we pass a single list of items with properties obeying a new `ICompletionItem` interface.

The proposed changes are needed in order to:
- make tight and powerful LSP integration with JupyterLab (for now in an extension)
- enable the creation of powerful completer extensions, for example integrating Kite

There already is an [`IMatch`](https://github.com/jupyterlab/jupyterlab/blob/3592afd328116a588e3307b4cdd9bcabc7fe92bb/packages/completer/src/model.ts#L433-L450) interface but it is only used internally as a Private of `CompleterModel`.
This proposal is about making a similar interface but on the level of [`CompletionHandler.IReply`](https://github.com/jupyterlab/jupyterlab/blob/3592afd328116a588e3307b4cdd9bcabc7fe92bb/packages/completer/src/handler.ts#L477), which currently treats text matches and metadata as separate fields - which is nice given the current kernel protocol, for example:

https://github.com/jupyterlab/jupyterlab/blob/3592afd328116a588e3307b4cdd9bcabc7fe92bb/packages/completer/src/kernelconnector.ts#L59-L60

but less handy when advanced LSP features are to be integrated.

## Expected behaviour

- this proposal does NOT aim to change the kernel completion protocol, but only how it is handled internally by JupyterLab.
- the interface would allow passing an optional score (number), which when set would be preferred over the MSS score, currently calculated by  `_filter`:
https://github.com/jupyterlab/jupyterlab/blob/3592afd328116a588e3307b4cdd9bcabc7fe92bb/packages/completer/src/model.ts#L368-L375
 one of many benefits of custom scoring/prioritization rules is that we can move the keyword arguments of a function signature to the beginning of the hints list
  - when at it, the score calculation might be moved out of `_filter` - this was quite unexpected to find it here
- the interface would allow providing additional fields, such as documentation
- rendering of the additional fields (such as documentation) is NOT a part of this proposal
- completion renderer should be made easily extensible to allow the extensions to define custom rendering functions for items (for example, displaying documentation below the completion suggestion item); passing custom rendered seems straightforward already, but it might be even better if the large-ish [createItemNode](https://github.com/jupyterlab/jupyterlab/blob/master/packages/completer/src/widget.ts#L731) was split into protected `createPlainNode` and `createTypedNode`, which could be used as building blocks in extensions (i.e. if the more advanced construct is not needed for given item) 
- we could mimick the LSP `CompletionItem` interface, but I think that it may not be realistic nor useful to follow it 1-1, as it has seen some changes, deprecations and is overall designed for more complex tasks than we need to handle. Here it is, for reference:

```typescript
interface CompletionItem {
	label: string;
        // our "type", and we got "string" rather than a number mapped to a string
	kind?: number;
	detail?: string;
	documentation?: string | MarkupContent;
	deprecated?: boolean;
	preselect?: boolean;
	sortText?: string;
	filterText?: string;
	insertText?: string;
	insertTextFormat?: InsertTextFormat;
	textEdit?: TextEdit;
	additionalTextEdits?: TextEdit[];
	commitCharacters?: string[];
	command?: Command;
	data?: any
}
```

I think that something simpler and adapted to existing JupyterLab codebase might do:

```typescript
interface ICompletionItem {
    label: string;
    type?: string;
    score?: number;
    documentation?: string;
    deprecated?: boolean;
    data?: any
}
```

The kernel responses would be then translated to objects obeying the `ICompletionItem` interface internally.

Does it make sense to you? I would love to hear some feedback on this idea.

## Context
- JupyterLab version: 1.1a

**Comment by krassowski** [comment]
@meeseeksdev tag "pkg:completer" "type:Enhancement"

**Comment by blink1073** [comment]
I like the proposal and the interface. Thanks for pushing on this!  If it could be done in a backward compatible way we can slot this for 1.1 in 1.5 weeks.  Otherwise it will have to be targeted for 2.0 later this year.

**Comment by daejong123** [comment]
Great!!!
Really looking forward to next version!

**Comment by krassowski** [comment]
I will try to get it working by the end of the month (so it may be a little bit late for 1.1, but we will see).

**Comment by daejong123** [comment]
Hi.
how can I use new code completer API? Where there is a document about new code completer api?

**Comment by blink1073** [comment]
Hi @daejong123, we didn't make it for 1.1, hopefully for 1.2 in about a month.

**Comment by krassowski** [comment]
A short update on the idea - maybe instead of:

```typescript
    data?: any
```

It would be better to have:

```typescript
    data?: [provider_name: any]
```
where the `type provider_name = string` which informs the (thrid-party) renderer about the additional metadata which may or may not be provided, for example "kernel", "lsp", "code-mirror-token". This is to allow to pass the metadata from kernel, without disrupting the LSP implementation.

Example:
```typescript
data: {
    kernel: {},  // any metadata provided by the kernel
    lsp: { detail: 'stats.py' }
}
```

Not 100% sure of this yet, but wanted to write down before I forget.

ETA: I hope that I will have this ready before the end of this month.

**Comment by blois** [comment]
Something to keep in mind is that a full completion list with documentation can be large enough that transferring it over a non-local connection can introduce significant overhead. A simple pandas dataframe completion returning all members w/ full documentation may be 50-100KB.

LSP includes the ability to provide the documentation only when needed via the [Resolve request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#completionItem_resolve) and the `isIncomplete` parameter to provide a partial list of completion results.

In Colaboratory where we're using the Monaco editor the initial completion request is essentially:

```typescript
interface ICompletionItem {
    label: string;
    type?: string;
    definition?: string;
}
```

Where `definition` is the LSP detail string used to show the method declaration in a completion such as:
![image](https://user-images.githubusercontent.com/2152569/72546669-0c153400-3840-11ea-9b80-ca59bdc74e3f.png)

Colab's code for this can be found at https://github.com/googlecolab/colabtools/blob/master/google/colab/_kernel.py#L75-L93.

**Comment by edzkite** [comment]
[Kite](https://kite.com) is building a JupyterLab extension. As a a completions provider, we’d like to put forth a concrete implementation plan for this API refactor proposal. We intend to take on the work of actually implementing this, in co-ordination with @krassowski.

### Architecture
![flow](https://user-images.githubusercontent.com/47993402/75833323-8dcc0d00-5d6d-11ea-8b02-9283c5c41dce.png)
* As outlined in the issue, we will create an interface capable of receiving a list of `ICompletionItems`.
*  This interface will exist along with the current completer interface, to maintain backwards compatibility
    * Current connectors, e.g. the Kernel Connector and the Context Connector, will continue to use the current Completer interface.
    * Extensions can hook into the new Completer API
    * Internally, we will add transformers between the two interfaces

### Model
```typescript
interface ICompletionList {
    isIncomplete: boolean;
    completions: [ICompletionItem];
}

interface ICompletionItem {
    label: string;
    insertText: string?
    range: 
        {
            start: number,
            end: number
        }
    type?: string; // kind in LSP
    // url of icon to display next to the completion item (possibly base64)
    icon: string;
    // See section on Documentation
    documentation?: string;
    resolve: function;
    // See section on Scoring 
    score?: number; 
    filterText: string
    // @krassowski  -- Use cases for these two fields?
    deprecated?: boolean;
    data?: any 
}
```
Key Additions:
* `insertText`, to differentiate between what’s displayed to the user vs. what’s inserted into the buffer.
* `range` so providers can specify a range of text to be replaced by the completion item. If not provided, a sensible range will be chosen automatically (as in the existing implementation).
* `icon`, so providers can control the icon shown next to the completion (useful for a variety of purposes, including distinguishing completions from different sources).

The latter sections contain our thoughts on documentation and sorting of completions. These are more open questions, and we'd love to hear from the community on this.

#### Documentation
With a full completion list, the payload for documentation can be significant in size. A couple options we could pursue to resolve this:

* Cap the number of completion items sent, setting `isIncomplete` to true. Presumably, the majority of completions below the fold (e.g. after the 5th result) are irrelevant to the user.
* Pass a per-completion-item callback (resolve) that returns the documentation text, instead of passing the text directly.

#### Ordering and Filtering
Allowing providers to send a score that is globally compared may create an arms race where different providers will try to make their completions show at the top by inflating scores.
If a provider only wants to control the ordering of its own completions, then a score is overkill, and we can just pass an ordered array (perhaps a boolean to indicate the order should be untouched by Jupyter). Users can then choose the preferred display order.

As part of its ordering logic, JupyterLab does some filtering https://github.com/jupyterlab/jupyterlab/blob/3592afd328116a588e3307b4cdd9bcabc7fe92bb/packages/completer/src/model.ts#L360.

This may not be desirable to all providers. To enable more flexibility, JupyterLab can use the `filterText` value from LSP, or take in a boolean denoting whether to filter completions.

Any feedback would be appreciated!

**Comment by krassowski** [comment]
@edzkite would you be also interested in snippet support? https://github.com/krassowski/jupyterlab-lsp/issues/208

**Comment by edzkite** [comment]
Absolutely!
