### ISSUE TITLE
Hyperlinks do not work for notebook table of contents. 

### ISSUE THREAD

**Issue by duarteocarmo** [jupyterlab/jupyterlab#7054]
## Description

When creating a table of contents for a notebook. The links do not work.

## Reproduce

1.Create a markdown cell in the top of the notebook with: 
`- [1.Import and clean data](#1)`
2.And then create a another one with:
`### 1.Import and clean data  <a class="anchor" id="1"></a>`

## Expected behavior
When clicking the first cell, you should be directed to the second cell. Just like the basic jupyter notebook interface. 
## Context
In large notebooks a way to navigate through a table of contents is essential. 

- Operating System and version: not relevant
- Browser and version: not relevant
- JupyterLab version: latest

**Comment by krassowski** [comment]
I can confirm that empty anchors are not rendered in JupyterLab v1.0.

If you seek generic way to create a table of contents for use in JupyterLab, you can:
1. use [jupyterlab/jupyterlab-toc](https://github.com/jupyterlab/jupyterlab-toc) extension - it's awesome!
2. instead of creating the anchors manualy, use those generated by JupyterLab - just hover over a header and you will see "¶" symbol appear to the right; click on it and your browser will update the address bar with the anchor id.
3. place the header text (or any text really) inside of the anchor
```
### <a class="anchor" id="1">1. Import and clean data</a>
```

4. add a zero-width character inside of the anchor:
```
### 1.Import and clean data <a class="anchor" id="1">​</a>
```

The last one is a hack and may not work in the future (zero-width characters can be evil).

**Comment by duarteocarmo** [comment]
To confirm, all of these will work once in something like nbviewer right?

**Comment by krassowski** [comment]
I do not know; I think (1) does not as it is a JupyterLab widget, but (2), (3) and (4) should - if they do not it might be worth opening a nbviewer issue.

**Comment by duarteocarmo** [comment]
@krassowski just to confirm then and potentially close this. We have no plan of creating anchors in the same way they are created in jupyter notebooks?

**Comment by jasongrout** [comment]
Note that DOM ids must be unique on a page. That means they work well in classic notebook, where only a single notebook is on a page. However, they don't work as anchors when you have multiple notebooks on a page with the same ids, or the same notebook open twice. We would have to manage the anchors and scrolling ourselves in jlab instead of depending on the browser to do it.

**Comment by duarteocarmo** [comment]
Hi @jasongrout, thanks for reaching out! That makes a lot of sense. I completely understand this can be a blocker because of multiple notebooks on different tabs or screen sections..

My idea is that users should (ideally, in my view) be able to create something like [this](https://nbviewer.jupyter.org/github/duarteocarmo/technological_capabilities/tree/master/notebooks/?flush_cache=true/) in their projects. 

I think we should either make a change that allows this (not very likely due to multiple notebooks in DOM), or point that out in the documentation. I'm happy to create a paragraph in the relevant section of the documentation that will point this out..

**Comment by jasongrout** [comment]
All that said, we do do some magic in jlab to automatically open documents and scroll to appropriate positions, even if ids are listed multiple times on a page.

I tried your original experiment and it worked great in JLab 1.1.1, actually.

1. Create a markdown cell in the top of the notebook with:
`- [1.Import and clean data](#1)`
2. And then create a another one with:
`### 1.Import and clean data <a class="anchor" id="1"></a>`
3. Click on the link in the first cell

For me, jlab *does* scroll the notebook to the anchor.

**Comment by duarteocarmo** [comment]
It's working now! Probably because there were multiple notebooks open and I was running an old version. Thanks @jasongrout  and sorry for any time wasted on this. 

Closing this. Let me know if you still want this documented somewhere, happy to help.
