### ISSUE TITLE
Run CI on mulitple Python versions

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#7126]
As exemplified by #7124, we could probably benefit from running the CI python tests on mulitple versions of Python. Ideally, the full minor span from oldest to newest (3.5, 3.6, 3.7 currently), but the minimum should probably be oldest and newest (3.5, 3.7) to pick up the largest feature span. If we do not want to add more entries to the build, we could e.g. do the oldest on Windows, and the newest on Linux.

**Comment by jasongrout** [comment]
I support this.

**Comment by saulshanabrook** [comment]
This sounds good! I would support running them all on linux. If we end up needing more concurrency we can always try to ping the pipelines team.

**Comment by telamonian** [comment]
I'm a little concerned about adding more test suites to our already only "mostly reliable" CI. If the Python suite ever has any intermittent failures, doing it in triplicate will increase the failure rate for the CI overall. This is good if the intermittent problem is due to a bug that we can fix, but we also get a lot of intermittent CI failures for spurious reasons (eg flood protection during the documentation link check).

As an alternative, maybe we could just lint check for post 3.5 features in a pre-commit hook? I was planning on adding a hook to prettify Jlab's Python. It probably wouldn't be too hard to get some static code checks in there as well.

**Comment by vidartf** [comment]
My impression is that it is mostly the JS tests that have spurious test timeouts? Others might have a more complete picture than me though. Here are Python test failures from last 30 days, and I think most of them are relevant failures: https://dev.azure.com/jupyterlab/jupyterlab/_test/analytics?definitionId=1&contextType=build

**Comment by vidartf** [comment]
(filtering to master branch is most likely to show spurious failures, as most relevant ones are dealt with before merging).
