### ISSUE TITLE
UI/UX for collapsing input/output

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#713]
This is an issue to track the UI/UX aspects of hiding showing some or all of a cell (input, output or both).

**Comment by faricacarroll** [comment]
I started a design mockup for collapsing cells.

However, I spoke with Cameron and we discussed there are a lot of other actions to take into account when designing the UI/UX for collapsing cells. By adding an individual cell menu for hide/show, we have to consider other cell-specific actions that could/should be included in the menu.

Such as:
* copy
* execute
* hide all
* hide input
* hide output
* etc.

Sketch file share link:
https://share.sketch.cloud/lGV7

**Comment by matt-bowers** [comment]
I like the minimalistic approach with the three dots! I'm only confused that some users may be confused when trying to distinguish the three dot icon that expands the context menu, with the three dot icon that represents a hidden cell. Also I think that a quick button (without needing to open a context menu) to hide the cell would be nice if possible (kind of like it is now, but actually a button 😛 ). Other thoughts besides mine?

**Comment by zertrin** [comment]
I'm not sure if this issue is about that, but in jupyterlab I'm currently missing the functionality of jupyter notebook where I can collapse the output of a cell that is otherwise very long by clicking on the empty place left of the output. This makes the output cell height small enough to avoid filling too much vertical screen size and I can scroll the resulting output cell.

I'm wondering why what seems to be a "built-in" of the notebook isn't available in jupyterlab, unlike most of the standard Notebook functionalities, but I must be missing something here.

If that feature isn't part of this issue, do you know if that's currently tracked somewhere else. If not I could open a separate issue for that feature.

**Comment by cameronoelsen** [comment]
![hidden](https://cloud.githubusercontent.com/assets/6437976/19328544/fbbdc3b8-9088-11e6-98f2-e8fa46f59d06.png)
One approach to this that simplifies the UI and makes sense (@faricacarroll @matt-bowers @spoorthyv @ellisonbg) is to show an empty cell inline in between the not collapsed cells. The empty, collapsed cell will act as a button, so when a user clicks within the collapsed cell area, it will expand that section. I am still thinking of what symbolic icon that we can put in the middle of the cell or if it should just be a different color (white) and no icon at all.

This collapsed cell UI in conjunction with the new Cell Tools section that we are thinking about I think will work very well for this use case.

Here is a walkthrough of how it might work like this:
![1](https://cloud.githubusercontent.com/assets/6437976/19330156/9a2053ec-9091-11e6-8704-b1c03f6d04c5.png)
First the user would select the cell that they want to edit/put into focus. They would then click the new cell tools button at the top of the notebook.

This would then open the Cell tools in the side pane:
![2](https://cloud.githubusercontent.com/assets/6437976/19330260/32f39304-9092-11e6-9cad-602fb4430f6e.png)
In this case, I just put in a few things that we are using that could be nice quick controls for cells (undo, redo, hide cell, split cell, delete cel) in the cell tools pane. These aren't set in stone but felt they would be used most (need to talk to users about this and get more info).

Lastly, when the user clicks the hide quick control in the cell tools, it would affect the notebook and hide the cell in the hidden state that I showed above:
![3](https://cloud.githubusercontent.com/assets/6437976/19330264/387fb668-9092-11e6-99be-b84f2e19c51d.png)

**Comment by ellisonbg** [comment]
@jasongrout just to clarify - this is feature parity for 1.0 as we need to at least have the cell toolbar capabilities done.

**Comment by benbovy** [comment]
> I am still thinking of what symbolic icon that we can put in the middle of the cell or if it should just be a different color (white) and no icon at all.

As an alternative to the three dots, a possible design for the icon could look like the github's expand icon:

<img width="77" alt="github_expand" src="https://cloud.githubusercontent.com/assets/4160723/19565052/e3868b14-96e5-11e6-8780-a81385cf3131.png">

and why not short (1-line), low-contrast summary / description too, if needed?

This is less relevant if the goal is *hiding* a cell rather than collapsing it, though.

**Comment by ellisonbg** [comment]
Some ongoing design explorations around this:

![screen shot 2017-03-17 at 9 20 08 am](https://cloud.githubusercontent.com/assets/27600/24052534/0a60ac66-0af3-11e7-9fa2-edccf155ed20.png)

The main idea here is:

* Separate the UI that visually indicates hidden/shown from the UI control for changing the view.
* Use the common three center dots to indicate "more" visually

**Comment by gnestor** [comment]
Issue on nbconvert tracking cell hiding, etc. using cell tag metadata: https://github.com/jupyter/nbconvert/issues/445

Issue on nbconvert tracking cell hiding, etc. using cell tag metadata: https://github.com/jupyter/notebook/issues/534

**Comment by OldGuyInTheClub** [comment]
Point of clarification, please: Per @zertrin's comment, is it the case right now that neither the input nor the output can be collapsed to save vertical space?  The standard notebook allows very easy output collapsing and many of us would like that to extend to inputs.  I am working with JupyterLab to understand its capabilities and am not able to do this. I hope that it won't be necessary to open a toolbar to do this in future...

**Comment by blink1073** [comment]
@OldGuyInTheClub, that is correct.  We have not yet implemented the collapsing behavior for either input or output in JupyterLab.

**Comment by OldGuyInTheClub** [comment]
Thanks.  I liked what I've seen with JupyterLab and it is a step closer to fulfilling the promise of Notebook.  I am a little rattled to see collapsing cells as an enhancement vs. a standard feature as it has been on IPython and Jupyter notebooks to now (at least for output).

**Comment by dhirschfeld** [comment]
+1 for collapsible output! I'm using JupyterLab for more of my day-to-day work now and this is a pain point as compared to the classic notebook.

**Comment by ellisonbg** [comment]
I have this mostly done in a PR that I will submit later today, marking at Beta.

**Comment by OldGuyInTheClub** [comment]
Big step forward, thanks.  I tried this today and it worked on a couple of my notebooks that have large code cells and even larger output cells.  It is very good to be able to collapse both.  Three dots look good to me and indicate that there is something to expand.  I think I can live with either fully collapsed or fully open cells if it means having it for both input and output.  Conventional notebooks have the in-between scrolling output cell size which some may like to have.

Autoindent does not seem to work; e.g. a the next line after a correct for statement is usually autoindented 4 spaces in regular Notebook but not in this.  I can live with that as well.

re: Installing from master, the webpage at https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md
gives `git clone https://github.com/<your-github-username>/jupyterlab.git` as the first step in the build process after installing dependencies

I tried it using my github username as directed and it didn't work.  When I plugged in jupyterlab in its place it went well.  That substitution may be obvious to frequent github users  but it was not to me.

**Comment by blink1073** [comment]
Thanks for the feedback, @OldGuyInTheClub.  I opened #2497 with a note about forking the repository.  The four spaces bug will be fixed in the next release, cf #2419.

**Comment by zertrin** [comment]
> Conventional notebooks have the in-between scrolling output cell size which some may like to have.

Fully open or fully closed is already a big improvement, thanks for it! 👍 

However, the in-between default of the notebook is really a useful feature IMHO. It allows to preview long outputs instead of hiding them completely, and allows for scrolling on demand without needing to expand the output fully (output data `AND` space saving). Currently we have to choose between hiding the output completely or having it flood our view because it is too long, neither of the choices being ideal because in each case we lose something (output data `XOR` space).

Is it completely out of scope for jupyterlab or can it be considered at a later time?

This is the last feature missing that keeps me on the notebook.

**Comment by jhgoebbert** [comment]
Thanks for adding the ability to collapse cells. This really removes some cluttering from notebooks.
But currently it is not saved to the notebook file, which cells are collapsed - at least I have not found any way to save it.
Is this somehow possible?

**Comment by jasongrout** [comment]
Please see https://github.com/jupyterlab/jupyterlab/pull/3981

**Comment by jhgoebbert** [comment]
Thanks!

**Comment by flekschas** [comment]
Any news regarding @zertrin idea? Maybe I am missing something but it seems be rather simple to add this functionality. I've adjusted the CSS mildly and it already results in the behavior of the classic notebook:

```
.jp-OutputArea-output pre {
    ...
    max-height: 10rem;
    overflow: auto;
}
```

**Comment by jasongrout** [comment]
^ CC @tgeorgeux, our UX person.

**Comment by akhmerov** [comment]
There's also a notebook format issue here. The classic notebook implements what is [defined](http://nbformat.readthedocs.io/en/latest/format_description.html#cell-metadata) in the `collapsed` field of the cell metadata. Jupyterlab now implements `cell.jupyter.source_hidden`/`jupyter.outputs_hidden`. Partial collapse would be an incorrect representation of the `jupyter.outputs_hidden` metadata field, but jupyterlab may implement UI for switching and representing both states.

**Comment by zertrin** [comment]
@flekschas FYI: The current issue opened to track the progress on partially collapsed output cells (with scrolling) is #4028

**Comment by flekschas** [comment]
@zertrin Ah thanks!

I realized it needs more than 2 lines of CSS due to dynamic DOM manipulations in certain cases but an extra parent `div` could fix the issue together with a toggler of 3 instead of 2 options (completely visible, partially visible (with scrolling), and entirely hidden). I am sure there's more to it but it doesn't seem to be overly tricky.

Anyway, I hope this is somewhat high up the priority list. :)
