### ISSUE TITLE
Notebook & Python module synchronized design feature

### ISSUE THREAD

**Issue by vishal-srini-rao** [jupyterlab/jupyterlab#7217]
Some of the challenges I face with Jupyter are:
- the functions & classes defined in notebooks cannot be easily imported to other notebooks & modules.
- existing Python modules and packages cannot be directly used like notebooks. You will have to manually copy the code to a notebook. 

I was thinking it would be good have an architecture where there is a Python module associated with every Python notebook. The Python module could contain some annotations which help the notebook understand how the cells are separated. Any additional data like text results of cell-executions can be stored in the notebook wrapper. The notebook and its module would always be in sync ie modifying the notebook should also modify the code in its module. Such an architecture may help address the first issue above because the functions and classes in the notebook can be accessed from its associated Python module. This would also ensure that minimal changes are required to codes before deploying them.

Additionally, to address the second issue, it may be good to have a feature convert any existing modules and packages compatible with Jupyter. There would be a piece of code which generates Python notebook wrappers around selected modules. The logic here could be something like moving each function or class to a separate cell. In case there are some ambiguities in the code which makes this difficult, the entire code could be stored in a single cell of the notebook. Optionally, the user could provide some simple hints in the Python file to help the tools understand how to generate cells. This feature would make it easy to use all existing Python packages in Jupyter environment.

**Comment by telamonian** [comment]
Notebooks already do a lot of what you talk about (the `.ipynb` file contain a serialized representation of the code in your notebook cells, see https://nbformat.readthedocs.io/en/latest/). Many of the details are completely different, though, due to the fundamental design choices of the Jupyter project as a whole. So the short answer is no, Jupyterlab will not be implementing any of that.

However, there are existing ways to get what you want. For directly importing notebooks, check out the [`ipynb` package](https://github.com/ipython/ipynb). For converting notebooks to normal `.py` python modules, there's [`nbconvert`](https://github.com/jupyter/nbconvert):

```bash
jupyter nbconvert --to script <path-to-your-notebook>
```

**Comment by bollwyvl** [comment]
> existing Python modules and packages cannot be directly used like notebooks. You will have to manually copy the code to a notebook.

At least for python, it depends on your definition of "used" and "manual":
```py
import inspect, IPython, some_module
get_ipython().set_next_input("\n".join(inspect.getsourcelines(some_module.some_fn)[0]))
```

Outside of that, it's probably a losing battle to try to get module authors to write their code in a specific way, a la [jupytext](https://github.com/mwouts/jupytext), so that they are "pretty" in your editor.

> the functions & classes defined in notebooks cannot be easily imported to other notebooks & modules.

 [importnb](https://pypi.org/project/importnb/) (also on [conda-forge](https://anaconda.org/conda-forge/importnb)) might be what you're looking for.

`importnb` performs dark magic on some pretty low-level import stuff to make Python (3.4+) notebooks importable like any other `.py` files... even in non-notebook/IPython/ipykernel settings. 

```py
# This notebook I wrote the other day.ipynb
x = 1

# This notebook I'm working on today.ipynb
import importnb

with importnb.Notebook(): # you can also %reload_ext importnb, but `with` is more portable
  import This_notebook_i_wrote_the_other_day

assert This_notebook_i_wrote_the_other_day.x == 1  # that is all
```

Give it a try on binder! 
> [![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/deathbeds/importnb/master?urlpath=lab/tree/readme.ipynb)
