### ISSUE TITLE
Datagrid should not be a singleton

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#7303]
## Description
As of now, datagrid is listed as one of our singletons, and pinned to the 0.1 version.  This prevents extensions from utilizing newer versions of the datagrid since they will be forced to use the older version.  There is no sound reason for the datagrid to be a singleton, so removing it is the easiest solution.  Our existing csv package can continue to use an older version of the datagrid while other extensions like `jupyterlab-hdf` can upgrade to the newer one sooner.  This should be backported to 1.2.

**Comment by vidartf** [comment]
So the logic here is:
- If a package is a *proper* singleton (references are passed across extension boundaries), removing one from the singleton list *is likely* to be a backwards-incompatible break.
- The data grid wasn't really a proper singleton in terms of that definition, so it is ok to remove.

Sounds good to me.

**Comment by vidartf** [comment]
Actually, I'm still unsure, what about the current case:
- Core library package A has a dependency on `foo: ^1.1.0`, it is declared as a singleton with the same semver, and released in a lab release.
- The singleton entry is removed and released.
- Someone makes an extension B that depends on `foo: ^1.2.0` (it needs a new feature added in 1.2).
- Someone tries to install extension B into the release with the singleton present.

What happens?

**Comment by sccolbert** [comment]
In this case it's fine, because both the `0.1.x` and `0.3.x` versions of datagrid depend on the same `^1.x.y` version of `@phosphor/widgets`, so both `DataGrid` prototypes will inherit the same `Widget` prototype. This means `instanceof(thing, Widget)` will work when pass either grid instance across module boundaries.

What won't work is `instanceof(thing, DataGrid)`. But I think that use case would be exceedingly rare.

**Comment by vidartf** [comment]
@sccolbert but won't any reliance on `DataGrid.dataModel` break if they get the old singleton version ? Or will the install of the extension fail, since it is not compatible with the old singleton value? This is what I meant with "what will happen?".

**Comment by sccolbert** [comment]
Yes, that would fail. My assumption is that *both* versions would be bundled, and the packages would get the correct version for their use.

**Comment by vidartf** [comment]
To be a little more explicit for a scenario:
- datagrid is currently a singleton for `^0.1.11` in current release.
- in the next release (1.2) we remove the singleton lock
- a new extension is made that depends on datagrid `^0.3.0`
- someone tries to install that new extension in the current release of JupyterLab

Possible results that I can imagine:
- The install on the current release fails, due to install-time checks OR
- The install completes, and the new extension is given 0.1.11, even though it asked for 0.3.0.

The first of these two alternatives is what *should happen* for third party extension, but I haven't double-checked. What I am unsure of is what happens if that extension *is a core extension* that gets pulled into a mixed version lab (e.g. 1.0.2).

**Comment by vidartf** [comment]
Just for completeness: For library users, this is a non-issue, as they are not affected by the singleton config/

**Comment by blink1073** [comment]
Because of the `resolutions` metadata, you can't just uninstall the core extension and install a replacement.  The problem is baked into the package.json file.  We really just need to remove this bug and be more selective about singletons going forward.

Sent from Phone

________________________________

**Comment by blink1073** [comment]
We might also consider *only* using resolutions during a prerelease cycle, since the original intent was to make it easier to test extensions without them chasing the current alpha or rc version.

Sent from Phone

________________________________

**Comment by sccolbert** [comment]
> you can't just uninstall the core extension and install a replacement

Yikes! That's the whole point of a plugin system.

**Comment by blink1073** [comment]
Right, what we really need is for extensions themselves to declare singletons.  There is an open issue for that.

Sent from Phone

________________________________

**Comment by vidartf** [comment]
Just for reference: While the change from the PR is backwards compatible, it comes with a corollary: The datagrid dependency of the CSV extension cannot be upgraded to use the new features of the datagrid package before 2.0. The reasoning being:
- That extension might automatically be pulled into lab 1.0.x (since it uses caret deps on core packages).
- Lab 1.0.x incorrectly has datagrid 0.1 as a singleton, meaning that is what would be used.
- This would break at runtime (if not before) when the CSV extension is trying to access the new API.
