### ISSUE TITLE
Mac terminal in JupyterLab has no disk access

### ISSUE THREAD

**Issue by veterparga** [jupyterlab/jupyterlab#7358]
hey

Really liking the built in terminal to jupyterlab, however I can't seem to get access to the full disk - I keep getting the error "operation not permitted":

![image](https://user-images.githubusercontent.com/56538431/66740664-9f1e8680-ee6b-11e9-988f-d6701d8072eb.png)

I added both the terminal, google chrome and Anaconda to get full disk access in system prefs:

![image](https://user-images.githubusercontent.com/56538431/66740693-b8bfce00-ee6b-11e9-8e35-b7ccba5e05e6.png)

Any workaround this so I can use the terminal in the same window as my jupyterlab?

Thanks in advance.

**Comment by bw-space** [comment]
Have you tried using sudo ls?

**Comment by veterparga** [comment]
Oh yes!

So not only it did not let me enter a password (after "Password:" whatever I typed didn't appear), it still does not let me perform the operation. 

![image](https://user-images.githubusercontent.com/56538431/66756469-02231400-ee92-11e9-9b4c-4892240d4c13.png)

**Comment by telamonian** [comment]
I don't see this problem on my Mac. Permissions issues can be tricky, and Apple does some questionably aggressive extra things in the name of security. Did you recently upgrade to Catalina (OS X 10.15)?

**Comment by telamonian** [comment]
Also, what happens when you try to do the same `ls` operations from within a notebook?

**Comment by sccolbert** [comment]
@veterparga Just an FYI - Mac never shows the password as you type it in the terminal. That's not a JLab bug. It's just how the terminal works.

**Comment by sbonaretti** [comment]
Hi,

Similar issue here. I need to list the files in a folder of a mounted volume in MacOS Catalina. 

I start Jupyterlab from Anaconda and I type:  
`print(os.listdir("/Volumes/my_folder"))`, I get the error `PermissionError: [Errno 1] Operation not permitted: '/Volumes/my_folder'`
However, when I try:
- `print(os.path.isdir("/Volumes/my_folder"))`, I get `True`, i.e. that's a directory
- `print(os.access("/Volumes/my_folder", os.R_OK))`, I get `True`, i.e. I have reading rights  

The same happens if I start the terminal from inside JupyterLab.

However, if I start Jupyter notebook from Anaconda, `os.listdir` works. Same if I try on my Mac terminal.

I have added Anaconda to `Full disk access` under `Privacy` in `Security & Privacy`, and restarted. 
Do you have any other suggestions?  

Thanks a lot!
Serena

**Comment by jasongrout** [comment]
@sbonaretti - is this still an issue?

**Comment by sbonaretti** [comment]
Hi @jasongrout,
You can close the issue for me. 
Thanks a lot for asking!
Serena
