### ISSUE TITLE
Prompt to save files before rebuild

### ISSUE THREAD

**Issue by julianbarg** [jupyterlab/jupyterlab#7372]
Hopefully title describes it well. Before a rebuild is triggered (e.g., when installing an extension), the user should be prompted to save all changes. Otherwise, the user might discover that all unsaved progress is lost after rebuilding and relaunching JupterLab.

**Comment by vidartf** [comment]
I think the rebuild is safe to do, but I agree that the refresh on the completion of the build should do a check to see if files need saving, and if so prompt the user.

**Comment by vidartf** [comment]
The place in the code that the reload happens is here:
https://github.com/jupyterlab/jupyterlab/blob/b5f6178751bc8b767f564fcd1fdbc56788f06221/packages/application-extension/src/index.tsx#L136

The way to check if anything needs saving is as done here (I think):
https://github.com/jupyterlab/jupyterlab/blob/b5f6178751bc8b767f564fcd1fdbc56788f06221/packages/application-extension/src/index.tsx#L182

**Comment by markellekelly** [comment]
I'm willing to take this on, but think there is a nontrivial design question here. I'm hoping to avoid chaining two dialogs. Pinging @isabela-pf for thoughts.

**Comment by isabela-pf** [comment]
I agree that chaining dialogs would create several problems. Markelle and I came up with a few options on how the existing dialog could be adapted.

This is the option we think would be best. The dialog looks the same when all documents are saved, but when unsaved files are detected the dialog reflects more options. I recommend this because it still reflects the status of open documents without having an alarming or overwhelming dialog when all documents are already saved. It also makes the option more clear.

![Option 6](https://user-images.githubusercontent.com/50221806/75939870-5d08d800-5e40-11ea-9bd9-55145f87747e.png)

Feedback is appreciated! Let me know if you want to see some of the other ideas as well.

**Comment by isabela-pf** [comment]
I've had some time to think about this and want to add some of the problems this interface might still need worked out. 

- I'm unsure if this is a high priority to users or not, but I don't like that this view does not specify if it is some or all documents unsaved.  This could be important if users made changes to a document they are hoping to get rid of via not saving, but are unsure if other documents they worked on with the intent of saving are properly saved. 

- I also spoke to @/ zsailer about this direction, and he mentioned that the "Cancel" button could be more unclear now that multiple actions (both save and reload) are being prompted in this dialog. Users could be unsure which actions are being cancelled.

These could be resolved with some more specificity (text or otherwise) in the dialog, but that would break somewhat from our current use of dialogs. I also don't know if it is the best way to solve these problems, but I will follow up with other dialogs to try it.

**Comment by isabela-pf** [comment]
Thinking about what @/ zsailer said and after getting to talk to @tgeorgeux, I've made more adjustments. 

![Screen Shot 2020-03-11 at 5 14 00 PM](https://user-images.githubusercontent.com/50221806/76475386-e3329a80-63bb-11ea-9602-64e0527ba8cc.png)

Adding the "close" x in the upper right is a break from most of Material Design's dialogs. It does not completely solve the potential confusion of the cancel option (as mentioned above), but it might be more clear that the user does not have to reload JupyterLab right then if they choose not to. This dialog could also still have the cancel button in addition to the x if it seems appropriate.

I also updated the text to match standard unsaved documents wording.
