### ISSUE TITLE
Convert URLs in cell output to clickable links

### ISSUE THREAD

**Issue by tibdex** [jupyterlab/jupyterlab#7393]
## Description

Related to https://github.com/jupyterlab/jupyterlab/issues/5489#issuecomment-467749932.

## Reproduce

When an URL is in the output of a cell, today nothing special is done:

![URL as plain string](https://user-images.githubusercontent.com/6574550/67219104-c1924000-f427-11e9-9045-5fa64abcad5b.png)

## Expected behavior

It would be nice to convert URLs as clickable links:

![URL as link](https://user-images.githubusercontent.com/6574550/67219105-c1924000-f427-11e9-9c5f-c6e737aaea59.png)

## Context

- JupyterLab version: 1.1.4

## Work around

An untasteful workaround is to use a custom URL class:

```python
"""URL Wrapper."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Url:
    """Wrapper around a URL string to provide nice display in IPython environments."""

    __url: str

    def _repr_html_(self):
        """HTML link to this URL."""
        return f'<a href="{self.__url}">{self.__url}</a>'

    def __str__(self):
        """Return the underlying string."""
        return self.__url
```

It has the drawback of forcing the user to do `str(url)` to actually get the wrapped URL as a string.

**Comment by mlucool** [comment]
This makes conversion from nb to lab much harder as many libraries print links.

**Comment by saulshanabrook** [comment]
I think the next step here would be to do some more research into how this is supported in the classic notebook and see what it would take for us to replicate it.

**Comment by jasongrout** [comment]
I think it is probably here:
 https://github.com/jupyter/notebook/blob/f185f4127d0cdfcca501b8c10983c2b23035c3c3/notebook/static/notebook/js/outputarea.js#L778
https://github.com/jupyter/notebook/blob/f185f4127d0cdfcca501b8c10983c2b23035c3c3/notebook/static/notebook/js/outputarea.js#L549
https://github.com/jupyter/notebook/blob/f185f4127d0cdfcca501b8c10983c2b23035c3c3/notebook/static/notebook/js/outputarea.js#L559
which all call:
https://github.com/jupyter/notebook/blob/f185f4127d0cdfcca501b8c10983c2b23035c3c3/notebook/static/base/js/utils.js#L506-L510

**Comment by saulshanabrook** [comment]
Thanks @jasongrout! What a lovely regex to find "URL"s :)

**Comment by jasongrout** [comment]
> What a lovely regex to find "URL"s :)

Better than markdown-it's? https://github.com/markdown-it/markdown-it/blob/1ad3aec2041cd2defa7e299543cc1e42184b680d/lib/rules_inline/autolink.js

**Comment by kgryte** [comment]
@jasongrout Do you know if there was any particular reason why this was not included in core? Was there any expectation that users would rely on an extension for this behavior instead?

I suppose another workaround in the lab notebook environment might include creating an output Markdown cell, which would presumably require users to wrap existing libraries which generate links (e.g., to reports) with `display` calls.

**Comment by jasongrout** [comment]
I think most likely because we weren't aware of the behavior in classic Notebook :). You certainly could do it from an extension, but the question here is if we should do this in core JupyterLab.

I think the primary concerns at this point are:

1. Is this useful? (I think you are answering the question that it is, and that libraries are relying on this?). Since it exists already in the classic notebook, that's a vote in favor, since we want to be compatible with the classic notebook. Similarly, did this cause problems? (Now would be the time to change it if it did.)
2. How can we replicate it in a safe, secure manner? The regex the classic notebook uses looks a bit simplistic, and getting parsing of URLs right is I think is notoriously tricky. We want to take another look at making links clickable by default from a security perspective, since clicking on a link can have lots of ramifications.
3. Just curious, do you know if other frontends like nteract or colaboratory or sagemath implement this behavior?

I'm bumping this to the 2.0 milestone so we can at least triage it next week in our dev meeting.

**Comment by tibdex** [comment]
I've look at other popular frontends and they do support it:

### Colaboratory

<img width="619" alt="Colab" src="https://user-images.githubusercontent.com/6574550/75143345-27a01400-56f5-11ea-9e12-8edc6bea4409.png">

You can see that they even linkify the input.

### nteract

<img width="790" alt="nteract" src="https://user-images.githubusercontent.com/6574550/75143376-35ee3000-56f5-11ea-89ea-8c82b4de2ac3.png">

They use this [regex `/(https?:\/\/(?:www\.|(?!www))[^\s.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,})/`](https://github.com/nteract/nteract/blob/c4a3be42854b094ecc0266c04feedc64d87fe272/packages/ansi-to-react/src/index.ts#L5) for [plain text](https://github.com/nteract/nteract/blob/c4a3be42854b094ecc0266c04feedc64d87fe272/packages/outputs/src/components/media/plain.tsx#L9-L13).

**Comment by jasongrout** [comment]
I'll also add that xterm.js, for example, has a much more complicated regex: https://github.com/xtermjs/xterm.js/blob/fb5ff49008558f42050d4566f327cda5e578d059/addons/xterm-addon-web-links/src/WebLinksAddon.ts#L9-L27
