### ISSUE TITLE
Add kernel switch dialog when clicking notebook kernel name display

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#741]
From https://github.com/jupyter/jupyterlab/issues/320#issuecomment-232084070.

**Comment by ellisonbg** [comment]
This should also be used for the console.

**Comment by ellisonbg** [comment]
Even better than the dialog on click would be a plain drop down menu, but the dialog is a good start.

**Comment by hadim** [comment]
Is there is a way (even not user-friendly) to choose the kernel on Jupyterlab at the moment ? Or should I wait for it ?

**Comment by blink1073** [comment]
Hi @hadim, yep!  You are given a choice of kernel when creating a new notebook, and there is a `Notebook -> Switch Kernel` menu option.

**Comment by hadim** [comment]
The `Notebook -> Switch Kernel` click does not produce anything on my system (last jupyterlab conda package installed). I see no error in the console browser as well as in the terminal executing the `jupyter` process.

I wonder if it's due to the fact that my kernels are in a separated conda envs ? I have installed the `nb_conda_kernels` package and I am able to choose my kernels correctly in the regular `jupyter notebook` (see https://github.com/Anaconda-Platform/nb_conda_kernels).

Is there is an incompatibility between `nb_conda_kernels` and `jupyterlab` ?

**Comment by blink1073** [comment]
Hmm, I just tried a fresh conda env with `notebook` and ran `conda install -c conda-forge jupyterlab nb_conda_kernels` and the kernel switcher is working as expected.  What OS/ python version are you running?

**Comment by hadim** [comment]
Oh I think my root conda env is running 3.5 and my env 3.6. Could it explain the missing kernel ? I'll check that tomorrow.

**Comment by blink1073** [comment]
To be clear, you launched `jupyter lab` from the root 3.5 env?

**Comment by hadim** [comment]
Yes

**Comment by hadim** [comment]
I have opened a new issue with more details to not pollute here.

https://github.com/jupyterlab/jupyterlab/issues/1557

**Comment by ellisonbg** [comment]
The button version of this would consist of the following:

* Replace the kernel name by a toolbar button
* On click, call the `notebook:switch-kernel` command.

**Comment by ellisonbg** [comment]
Wondering if we should just do this as a context menu as suggested in #919 

Would be really easy and general - are folks ok with that?

**Comment by blink1073** [comment]
Sounds good to me.

**Comment by ellisonbg** [comment]
Fixed in master by #2195
