### ISSUE TITLE
Cell delete or insert causes jump to last search result

### ISSUE THREAD

**Issue by notuntoward** [jupyterlab/jupyterlab#7476]
Say I've done a Jupyterlab search (ctrl-F) and have then moved the cursor to a different cell.  If, at the new location, I delete a cell (Delete Cells: D,D) or insert one (Insert Cell Below: B), then the cursor moves to the last search match.

I never want that, and instead want to continue working at the spot where I've just done the cell editing.

- Operating System and version:  Windows 10
- Browser and version: Firefox 70.0.1
- JupyterLab version: 1.1.4

**Comment by gittar** [comment]
I also observed this. In particular with larger notebooks it can be quite distracting since suddenly and unwilling you are at a completely different part of the notebook. A crude workaround for users is to delete the search window each time before adding or deleting cells, but that is easily forgotten.

**Comment by khof312** [comment]
Same issue. I hadn't connected it to the presence of an open search window though, thanks for the tip...that's helpful.

- Operating system and version: Windows 10
- Browser and version: Chrome 79.0.3945.117
- Jupyterlab version: 1.1.4

**Comment by marisaaquilina** [comment]
Fixed in PR #7835!

**Comment by vidartf** [comment]
Thanks!
