### ISSUE TITLE
JupyterLab build fails with extensions having SCSS to be loaded

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#7502]
## Description

Some external extensions may provide SCSS files in their `lib` folder which are then webpacked with a `sass-loader`. However, when jupyter lab builds that extension to create a minimized distribution, it fails as no `sass-loader` is defined.

**Comment by jasongrout** [comment]
Thanks for trying to help JupyterLab!

Our policy is that extensions should compile their style files down to plain css (for example, the publish step of your package could compile your scss files to plain css), which our webpack config can understand.

This policy ensures that we support the common denominator across all styling packages without the maintenance cost to us of lots and lots of loaders for different ways people can write style files. This policy also means that you get to choose what version and variant of scss you write, rather than having to align with the one loader we would ship.

Happy to discuss more, and this really should be in the docs somewhere (we've had this conversation many times on various issues).

**Comment by echarles** [comment]
Thx Jason. The policy makes sense and I have updated my code to use [JSS]](https://cssinjs.org/?v=v10.0.0) (converting SCSS to CSS was another option).

I have created a branch to write what you say in the docs, but realized that this is already covered [here](https://github.com/jupyterlab/jupyterlab/blob/a441eb9c34aa82429c4d04fb85e697991150cbad/docs/source/developer/extension_dev.rst#extension-authoring).

```
The following file types are also supported (both in JavaScript and CSS): json, html, jpg, png, gif, svg, js.map, woff2, ttf, eot.

If your package uses any other file type it must be converted to one of the above types or include a loader in the import statement. If you include a loader, the loader must be importable at build time, so if it is not already installed by JupyterLab, you must add it as a dependency of your extension.

If your JavaScript is written in any other dialect than EMCAScript 6 (2015) it should be converted using an appropriate tool. You can use Webpack to pre-build your extension to use any of it's features not enabled in our build configuration. To build a compatible package set output.libraryTarget to "commonjs2" in your Webpack configuration. (see this example repo).
```

I have seen in regular comments regarding "how to build an extension". @saulshanabrook 's [jupyterlab-webpack](https://github.com/saulshanabrook/jupyterlab-webpack) is a great start for a webpack case but I still feel the last mile (configure jlab and see the result) is missing.

I am following the [Extension Development Wishlist ](https://github.com/jupyterlab/jupyterlab/issues/7468) gathered by @saulshanabrook and upon the listed actions that would solve a lot of pain, I would propose to create a `jupyterlab-extension-examples` repo which would have a lot a very simple extension examples covering typical cases. For now, the existing options (cookiecutter, example folder in jupyterlab repo, existing extension like jupyterlab-github, Astronomy Picture of the Day...) do not answer the needs.

I am closing this issue.
