### ISSUE TITLE
Port JupyterLab shortcut UI to core

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#7597]
The shortcut editor user interface should be migrated to the core packages to ship with JupyterLab 2.0.

This issue is dependent on https://github.com/jupyterlab/lumino/issues/10

cf. https://github.com/jupyterlab/jupyterlab-shortcutui

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/11079.

The new settings editor UI now has a built-in way to configure keyboard shortcuts:

![image](https://user-images.githubusercontent.com/591645/161011557-563221de-0140-466a-9c07-1e3ae352e368.png)

The follow-up would be to sunset https://github.com/jupyterlab/jupyterlab-shortcutui as discussed in the triage meeting: https://github.com/jupyterlab/team-compass/issues/137#issuecomment-1064397945
