### ISSUE TITLE
Calling ContentsManager.get() with an absolute file path

### ISSUE THREAD

**Issue by n-a-sz** [jupyterlab/jupyterlab#7623]
In JupyterLab front end extension, I would like to fetch a file from the JL server by using an absolute path.
I have found the [`ContentsManager.get()`](https://jupyterlab.github.io/jupyterlab/services/classes/contentsmanager.html#get) function, but that only accepts relative paths to JL's work directory.

As a workaround, I'm creating a symbolic link under JL's work directory to the folder I need, so I can reach it with the `get` function.

Could we have a FetchOption to the `get()` method that enables passing absolute paths to it? e.g.: `contentManager.get("/path/to/my/file", {"absolutePath": true})`

**Comment by jasongrout** [comment]
For security, the contents manager is intentionally scoped to the server's working directory. In order to change that, you'd need to change the contents manager on the server, which would be a change and issue in the notebook: https://github.com/jupyter/notebook/

Alternatively, you could load your own contents manager, which could derive from the stock contents manager and remove the file scoping restriction. Again, that is an issue with the server though, not JupyterLab.

**Comment by n-a-sz** [comment]
Ok, thanks for the answer!
I understand that this is a security concern. And I also wanted to avoid the server extension, so using a symlink serves well for my case. I have created it with a starting dot, so it is hidden from the user.
