### ISSUE TITLE
Kernel gateway `envs` parameter

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7640]
In refactoring the services package in #7252, I came across the envs parameter added in #7499. Right now, that parameter is not consistently used across sessions and other places kernels can be started.

I'm trying to figure out:

1. Exactly what it is. I can't find it in any rest api spec, and the closest mention I can find in the gateway documentation is https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-security.html#security-features, where it indicates that the server is handling the single parameter it's talking about.

2. How it is supported. Looking at the kernel gateway code in the notebook server, it appears that it pulls the environment from the server, not from the post request body: https://github.com/jupyter/notebook/blob/d0a74353e62ad5a5b0141f831c5aa59f8c2933bb/notebook/gateway/managers.py#L354-L365

I'm confused why we added the parameter if it doesn't seem to be used by the notebook server. Luckily, we haven't released 2.0 (it was introduced in a 2.0 alpha), so we have time to reconsider how this fits into the various ways we have of starting and restarting kernels in the services package.

@borremosch, are you using the services package to talk directly to the gateway server, and not through a notebook server? If so, I think that isn't a case we considered when we made the services package. Can you elaborate on what you are trying to do a bit more? Maybe there is a better way to support it, either as a wrapper on top of services or a way to more cleanly support it through extending services in a more generic way.

I'm thinking of this also in context of the discussions we've been having about kernel startup parameters, which is another set of information we'd like to send to the server when starting a kernel.

CC @blink1073, @vidartf, @kevin-bates

**Comment by borremosch** [comment]
Hi @jasongrout, I am using the @jupyterlab/services package to talk to an instance of Jupyter Enterprise Gateway. I am using Enterprise Gateway on top of Kubernetes and I needed to dynamically inject some values into the kernel pod specs. This is supported — albeit very poorly documented — in Enterprise Gateway by sending an env variable in the request body, as described here: https://jupyter-enterprise-gateway.readthedocs.io/en/latest/kernel-kubernetes.html#kubernetes-kernel-instances.

```All ${kernel_xxx} parameters correspond to KERNEL_XXX environment variables that can be specified from the client in the kernel creation request’s json body.```

A more generic way of doing this should be fine for my use case as well.

**Comment by jasongrout** [comment]
Are you just starting plain kernels, or are you using sessions, etc.?

**Comment by borremosch** [comment]
I am using plain kernels

**Comment by jasongrout** [comment]
Thanks.

I've modified my PR at #7252 to simply json stringify any options passed in to the kernel creation routine (which makes it consistent with how we were doing sessions as well), so I think you should be able to pass in any extra parameters you want now.

**Comment by blink1073** [comment]
Stringifying extra options sound good to me.

**Comment by kevin-bates** [comment]
Support for the `env:` stanza in the request body has been present in Kernel Gateway server since before I started working on the Gateways a few years ago.  Enterprise Gateway has extended its use by automatically propagating any variables prefixed with `KERNEL_` to the kernel launch - as @jasongrout points out in his reference.

Regarding the poor documentation, Kubernetes is just one resource manager EG deals with.  I would argue that this should have been the documentation reference: https://jupyter-enterprise-gateway.readthedocs.io/en/latest/config-options.html#per-kernel-environment-overrides   That said, EG and Kernel Gateway could stand to improve their swagger docs to include this `env` entry.

I'd like to add support for this entry to `jupyter_server`, but wanted to see how we address env variables relative to the [parameterized launch proposal](https://github.com/takluyver/jupyter_kernel_mgmt/issues/38) since it may become embedded in the parameters stanza. (EG will still need to support an independent `env` stanza for b/c purposes but I'm hoping to update the Gateway code in jupyter_server to extend/create the env section of the launch parameters to continue support of `KERNEL_` and white-listed values for b/c support.)

> I am using the @jupyterlab/services package to talk to an instance of Jupyter Enterprise Gateway.

I'm surprised to see this.  How is this accomplished?  I.e., how do you point an instance of lab to the headless EG server w/o bouncing through a Notebook server configured with `--gateway_url=...`?  As @jasongrout points out, the NB server essentially builds the request body before forwarding to EG so you must be hitting an EG server directly for these client-side change to have any affect.  Since the gateway servers disable the Contents service, how are you (@borremosch) managing your notebook files?

**Comment by borremosch** [comment]
All file management is done by our own code. We are not using notebooks in a traditional sense, but instead have built a tailor-made hybrid UI that resides somewhere inbetween a Git file browser and a Jupyter notebook. We are using the `jupyterlabs/services` package to communicate with Enterprise Gateway, but are not using any other JupyterLab or Jupyter Notebook components.

I realize I could have been a bit more clear about what I meant by poorly documented. The EG documentation in general is quite extensive, but I was missing the implementation details as to how this passing of environment variables works. Although both my and your referenced documentation mentions that environment variables can be added to the kernel startup calls JSON body, neither source seems to mention that the environment variables should be added as an object under the name `env`. As you said, it would be great if that could be added to the Swagger spec.

**Comment by kevin-bates** [comment]
Very interesting - thank you for your response.  I didn't realize portions of lab could be used that way (but then again, I stay away from the client side of things :smile:).  I'm curious to hear more about your application.  What does the services package give you that using the REST api directly doesn't?

I've also opened [this issue](https://github.com/jupyter/enterprise_gateway/issues/761) relative to documenting `env` in the swagger specs.

**Comment by jasongrout** [comment]
>  What does the services package give you that using the REST api directly doesn't?

I'm really curious about this too.

In #7252, I factored out the REST api parts of services so they can basically be used standalone, so creating a kernel using the REST api is just a few lines. Do you also use the websocket connection logic from services?

**Comment by borremosch** [comment]
> Do you also use the websocket connection logic from services?

I believe so yes. I leave most of the connection handling up to `@jupyterlab/services`. I also use `Kernel.iopubMessage.connect()` and `Kernel.statusChanged.connect()`, which I think use websockets. Other than that, using this package saved me the trouble of writing my own typed wrapper for the REST api.

The difference in perspective is interesting. The choice to use this package was very obvious to me. I was searching for a low-level way to connect with Jupyter kernel backends, then I found a [public package on NPM](https://www.npmjs.com/package/@jupyterlab/services), written in TypeScript and well documented. I guess if you never intended for the package to be used outside of JupyterLab it is a coincidence that that it is exactly what I needed. But it does mean you did a very good job making your code modular!

**Comment by jasongrout** [comment]
We definitely the services package to be used outside of JupyterLab (there are at least a few other people using it too that we know of). What I didn't anticipate is someone using it with something other than the notebook server.
