### ISSUE TITLE
Launcher losing focus when creating new activity

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7641]
## Description

On current master, a launcher will not stay focused when you click one of the activity icons.

## Reproduce

1. Open a launcher
2. Open a second launcher
3. In the second launcher, click on the notebook icon to make a new notebook
4. Observe that the focus shifts to the first launcher, not the new notebook.

## Expected behavior

I expect the new notebook to retain focus in the above case.

## Context

- Operating System and version: macOS 10.14
- Browser and version: Firefox 71
- JupyterLab version: current master (e16485e4bbec4729e43dfc98e45f12298054a33a)

I didn't see any errors in the js console or in the server console.

If I had to take a guess without git bisecting, perhaps it is related to https://github.com/jupyterlab/jupyterlab/pull/7349?

**Comment by jasongrout** [comment]
I just tried it out, and yes, it is something in #7349. I see the issue in 8d773bf, the merge commit from that PR, but I don't see the issue in that commit's parent, 92913c4f238e0aeb7e081d7309a9d7fd1db30304

CC @mbektasbbg

**Comment by blink1073** [comment]
I don't think we can disambiguate.  The launcher opens another item, which activates the new widget, and then closes itself.    
At this point, a previous tab is selected by the dock panel, which causes the logic in #7349 to dispatch a second activation, which is in a race condition with the first one (but most likely comes second).  We can't just add a `requestAnimationFrame`, because the activation logic for the newly created widget might be async.  
Even if we added the logic for "a widget was closed", we'd still get tripped up here because the launcher does close.
Maybe the best we can do is add a 1sec delay, and if nothing is focused, give focus.

**Comment by jasongrout** [comment]
In the worst case, if we can't find a good compromise, I'd say we revert #7349 before 2.0.

**Comment by blink1073** [comment]
Agreed.

**Comment by mbektasbbg** [comment]
I have been debugging this, looks pretty tricky. there is a race condition as @blink1073 mentioned. if we can disable activation logic in #7349 conditionally (which should be possible by using a toggle flag) then this case can be fixed, but we need to handle all other similar cases too.
