### ISSUE TITLE
JupyterLab makes too many requests resulting in 503 while the backend is not reachable

### ISSUE THREAD

**Issue by n-a-sz** [jupyterlab/jupyterlab#7756]
## Description

We have a JupyterHub instance with built-in proxy and DockerSpawner. Let's say there are several users already using it so there are running containers. If we stop the containers (e.g. host kernel patch) and have JupyterHub running, we got a lot of HTTP 503 error log - like 20 lines per user per second - and our log file quickly grows to several GBs which is not that convenient. This is because JupyterLab is still open in the browser of the users and it constantly tries to reconnect to the server on different URLs.

## Reproduce

1. Set up JupyterHub with DockerSpawner and JupyterLab
2. Make JupyterHub log to a file
3. Start a container through JupyterHub
4. Stop the container through docker command
5. Check the log file

## Expected behavior

I would expect JupyterLab to go into an offline state after it gets the first 503 and ping the backend in a well defined and configurable way until the backend or network connectivity is back (or the user closes the browser). Maybe, this would require some changes in JupyterHub too.

## Context

We get HTTP 503 to several endpoints:

/hub/user/*/lab
/hub/user/*/metrics
/hub/user/*/api/sessions
/hub/user/*/api/terminals
/hub/user/*/api/contents
/hub/user/*/lab/workspaces
/hub/user/*/api/kernelspecs
/hub/user/*/lab/tree

- JupyterLab version: 1.2.3

**Comment by vkaidalov-rft** [comment]
Hello! My team deploys JupyterLab under JupyterHub and we are facing the same issue. In our case, the notebook servers are also getting shut down due to inactivity by the `cull-idle-servers` service of JupyterHub.
Currently, the `hub-extension` shows the users an error message within the `Dialog` widget instance that appears in case of the user notebook server that has been shut down. The requests are still being sent to the backend periodically. The configurable-http-proxy, that is used in JupyterHub deployments, forwards these requests to JupyterHub by default if there is no user notebook server to forward the requests to. As a result, JupyterHub logs 503 errors when it gets the requests that are intended to be processed by the user notebook server instead.
Although the "decorrelated jitter" strategy is used by the `Poll` instances of the `lumino` library to reduce the frequency of the requests sent to backend after the first request failed, the total number of logged 503s may still be huge - users may sometimes leave the dialog showing an error message, prompting to restart their servers, for hours in our practice.

![how-it-currently-works-browser](https://user-images.githubusercontent.com/79568556/116078746-a8fb8980-a69f-11eb-8f6d-055170fdb090.png)
![how-it-currently-works-hub-logs](https://user-images.githubusercontent.com/79568556/116078761-ac8f1080-a69f-11eb-9b2c-0ab8d686e878.png)


Moreover, if the dialog showing the error is displayed and the periodic requests are not failed anymore at some point, the dialog won’t be closed unless the user closes it themselves. The UI is darkened when a `Dialog` widget is displayed, so I think that the users aren’t supposed to see any updates in the darkened UI until they resolve the dialog. Thus, I suppose that the results of those requests aren’t really useful if this particular `Dialog` widget of the `hub-extension` is displayed over the UI regardless of the responses received.
I propose to pause sending requests from the browser to the user notebook server unless the `Dialog` widget created by the `hub-extension` is resolved. In order to enable the `hub-extension` and other extensions to express their wish to temporarily pause periodic polling conducted by these and other extensions, I propose to add the `bandwidthSaveMode` boolean property to the `ServiceManager` class. I will open a WIP pull request soon.
