### ISSUE TITLE
Gaps between plain text cell output lines in Chromium

### ISSUE THREAD

**Issue by mgeier** [jupyterlab/jupyterlab#7760]
## Description

There is too much distance between lines in Chromium, in Firefox it's OK.

## Reproduce

Example code to reproduce:

```python
text = ' XYZ '
formatstring = '\x1b[{}m' + text + '\x1b[m'

print(' ' * 6 + ' ' * len(text) +
      ''.join('{:^{}}'.format(bg, len(text)) for bg in range(40, 48)))
for fg in range(30, 38):
    for bold in False, True:
        fg_code = ('1;' if bold else '') + str(fg)
        print(' {:>4} '.format(fg_code) + formatstring.format(fg_code) +
              ''.join(formatstring.format(fg_code + ';' + str(bg))
                      for bg in range(40, 48)))
```

On Chromium, the result looks like this:

![image](https://user-images.githubusercontent.com/705404/72065486-a0cadf80-32de-11ea-9097-5e26d0eba669.png)

There are ugly gaps between the lines.

Example notebook: https://github.com/spatialaudio/nbsphinx/blob/master/doc/code-cells.ipynb

## Expected behavior

On Firefox, it looks like this:

![image](https://user-images.githubusercontent.com/705404/72065527-bf30db00-32de-11ea-80c4-f8f10df5ea38.png)

## Context

- Operating System and version: Linux (Debian Testing)
- Browser and version: Chromium Version 79.0.3945.79
- JupyterLab version: 9d2e61634f568efa5013f47a15d1083b71ed2603

**Comment by telamonian** [comment]
For me (OS X 10.14), your example code has the same appearance in Chrome and Firefox, and shows whitespace between the lines.

That being said, this is all a problem of CSS. The fundamental issue is that the `font-size` and the `line-height` are different on purpose, in order to give a bit of space between the lines. The standard practice (which we follow) is that `line-height` is roughly ~1.2 times the `font-size`.

I don't think there's a perfect solution, but the issue can probably be reasonably fixed. All of the relevant CSS is in the `rendermime` package:

https://github.com/jupyterlab/jupyterlab/blob/95671a0cb2c8d5a6c5681a852f4c9885f72a06b5/packages/rendermime/style/base.css#L53-L76

One possibility (which I just briefly tested out) is to give the colored spans a top and bottom border, like so:

```css
.jp-RenderedText pre .ansi-green-bg {
  background-color: #00a250;
  border-top: .15em solid #00a250;
  border-bottom: .15em solid #00a250;
}
```

Want to take a crack at a PR, @mgeier?

**Comment by mgeier** [comment]
> For me (OS X 10.14), your example code has the same appearance in Chrome and Firefox, and shows whitespace between the lines.

How does it look for you in the Classic Notebook?

**Comment by telamonian** [comment]
The same, and for the same reason: `line-height` > `font-size`. What version of Firefox are you using?

**Comment by mgeier** [comment]
> What version of Firefox are you using?

72.0.1 (64-bit)

> One possibility (which I just briefly tested out) is to give the colored spans a top and bottom border

That sounds like an unnecessarily clunky and brittle work-around, there must be a better way!

This, for example, seems to have decent interline spacing, but it still works in Chromium:

https://nbsphinx.readthedocs.io/en/material-theme/code-cells.html#ANSI-Colors

**Comment by ggbhat** [comment]
Issue is due to the line height is being added for **pre** tag

```
tt, code, kbd, samp, pre {
    font-family: var(--jp-code-font-family);
    font-size: var(--jp-code-font-size);
    line-height: var(--jp-code-line-height);
}
```

Since **pre** preserves both spaces and line breaks we can set line height to normal. 

```
 .jp-RenderedText pre,
.jp-RenderedJavaScript pre,
.jp-RenderedHTMLCommon pre {
  color: var(--jp-content-font-color1);
  font-size: var(--jp-code-font-size);
  border: none;
  margin: 0px;
  padding: 0px;
line-height:normal;
}
```
If you look at https://nbsphinx.readthedocs.io/en/material-theme/code-cells.html#ANSI-Colors also the line-height is set to normal.
