### ISSUE TITLE
Cannot override the default rendered viewer

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7776]
In https://github.com/jupyterlab/jupyterlab/pull/6813, @ian-r-rose wrote a nice setting for overriding the default editor for a file. This is used in preferredWidgetFactories to allow a user to control a default editor for the file: https://github.com/jupyterlab/jupyterlab/blob/57cd4545b93606177950e7189d03394b26c63b0c/packages/docregistry/src/registry.ts#L334-L339

However, this override is *not* taken into account when we ask for the default rendered widget factory: https://github.com/jupyterlab/jupyterlab/blob/57cd4545b93606177950e7189d03394b26c63b0c/packages/docregistry/src/registry.ts#L406-L421

This means that we can't set the default renderer for clicking on a file in a rendered markdown, for example. This is confusing since, for example, the setting name is "defaultViewers" (and not defaultEditors or something).

Should we allow a separate override for the default rendered widget?

This came up in https://github.com/mwouts/jupytext/issues/271

**Comment by parmentelat** [comment]
Hiya; is there any hope to see this settled in a reasonable future ? 

sorry in advance that this is going to go a little off track from the issue at hand
I tried to discuss this on discourse too, but it did not trigger a reaction yet, so I'm trying my luck here
https://discourse.jupyter.org/t/opening-a-jupytext-powered-notebook-under-jlab/9545

---
in a nutshell I "just" need to have a url to a jupytext notebook open the document as a notebook (like the classic notebook does) instead of the other available widgets
(I'd even be ready to rename my material to have it end in .nb.md or .nb.py if that can help)


I ended up here from 
https://github.com/jupyterlab/retrolab/issues/162

which brought me to open 
https://github.com/mwouts/jupytext/issues/803

where I was linked to
https://github.com/mwouts/jupytext/issues/271


at this point it feels like there is no practical solution right now to achieve that simple 'open .mds as a notebook', is this right ?

to me it is an important impediment to moving to jlab as a replacement for classic - and I'd expect some other colleagues to feel the same

I'd be ready to help make this happen 

in that journey I have seen a few references to 'do this in an extension', but apparently nobody seems to know whether it's doable at all as an extension (but probably I am missing something here) and if so, where to start to tackle that 

so I guess what I'm asking is, where to go / who to ask to know where to start investigating this
