### ISSUE TITLE
Some icons look "dimmer" with the Dark Theme in 2.0

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#7859]
Testing from the [current master](f17361c2d6ecf1b5ccae5b576266355150f09af2), some icons (mostly the check marks and submenu arrows) now look dimmer than before (1.x).

With 1.2.6:

![image](https://user-images.githubusercontent.com/591645/74044629-a09c2d80-49cb-11ea-8f6c-9ea894674d31.png)

With 2.0 / current master:

![image](https://user-images.githubusercontent.com/591645/74044607-967a2f00-49cb-11ea-810d-29c4a8f89f22.png)

**Comment by jasongrout** [comment]
Testing, this seemed to change between 2.0b1 and 2.0b2. It seems that the icon pulled in by the css has a different svg font between then. @telamonian - do you know of an easy workaround to have brighter checkmarks? Is this related to (IIRC) consolidating the svgs for various themes into the ui package, so you only get one svg?

It looks like the checkmark is using currently using this css: https://github.com/jupyterlab/jupyterlab/blob/f17361c2d6ecf1b5ccae5b576266355150f09af2/packages/apputils/style/commandpalette.css#L166-L170

**Comment by telamonian** [comment]
No, sadly there's no workaround that is both clean and easy. The real problem is that there's no underlying support in lumino for `LabIcon`-like icons in commands or menu items (as there currently is in lumino `title` objects, via their `.iconRenderer` prop). I'm working on fixing that right now.

I *really* wanted to avoid it, but the quick and dirty fix would be to just go back to having 2 of each of the icons (light/dark) that get used in the menus. The drawback (aside from being an annoying mess for me to maintain, especially on a temporary basis) is that the icon colors wouldn't match to any custom theme, just to the default light/dark themes. I'd prefer if we lived with the styling defect for a week or two, I'll go and fix the underlying issue in lumino, and then we can fix the menu icon styling for real in a 2.0.x point release

**Comment by telamonian** [comment]
This will get fixed by #7864
