### ISSUE TITLE
Flash of huge notebook icon on open

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7922]
## Description

JupyterLab 2.0.0rc2 flashes a huge Notebook icon when first opening in the launcher page, before it is immediately resized to a small icon on the launcher next to "Notebook"

## Reproduce

1. Install JupyterLab 2.0.0rc2
2. Open the page
3. Note the flash of a huge icon, which immediately scales down to be the Notebook icon in the launcher

## Expected behavior

No flash of a huge icon

## Context

- Operating System and version: macOS High Sierra
- Browser and version: Firefox 73
- JupyterLab version: 2.0.0rc2

CC @telamonian, @tgeorgeux

**Comment by jasongrout** [comment]
I think @telamonian mentioned at some point that the svg files like hhttps://github.com/jupyterlab/jupyterlab/blob/d3c1ffbcc85db1a85a8c3d733cd66438b302d812/packages/ui-components/style/icons/filetype/notebook.svg need a width and height specified, as in https://github.com/jupyterlab/jupyterlab/blob/d3c1ffbcc85db1a85a8c3d733cd66438b302d812/packages/ui-components/style/icons/filetype/folder.svg. Is that right?

**Comment by telamonian** [comment]
I've been playing around with this. The FOUC (flash of unstyled content) seems to be an issue specific to Firefox and inline svg rendered using React.

#7931 gives all the icons a default inline width/height (24x24 for most of them). There's still a FOUC when you reload the launcher, but since it's a small decrease in icon size rather than a large increase, it's much less noticable
