### ISSUE TITLE
another issue with shutdown kernel and re use

### ISSUE THREAD

**Issue by SlowMonk** [jupyterlab/jupyterlab#7946]
jupyter lab

when it shutdown kernel and when I just try to reuse the jupyter lab 
it have to restart the kernel. but jupyer notebook just automatically restart the kernel when I shutdown 
please apply this issue

**Comment by jasongrout** [comment]
I'm not sure exactly what seems to be wrong to you. It seems like you are describing a difference between JupyterLab and the classic notebook? Something to do with shutting down a kernel and it restarting, or something?

Can you follow the template for new issues to describe a precise set of steps so that we can reproduce what you are seeing, and tell us exactly what different thing you expect to happen, and include the other information we ask for like the JupyterLab version number, etc.?
