### ISSUE TITLE
some doubt about button click

### ISSUE THREAD

**Issue by drhades** [jupyterlab/jupyterlab#8002]
Here is my code in JupyterLab:
<img width="515" alt="截屏2020-03-0610 23 21" src="https://user-images.githubusercontent.com/82670/76044322-f517d600-5f94-11ea-9e57-74c09bb51751.png">

My doubt is, after button"ttt" is click, why:
1. button"prompt", no rich-rendered in cell output area, just text-rendered in log console twice as warn and info
it irch-rendered in Notebook

2. logging, no display in log console

3. print"abc", display  in logconsole twice as warn

Version info:
jupyter lab      : 1.2.6
ipywidgets       : 7.5.1
python             : 3.8.0

Looking forward to description of the principle.
Thx very much!

**Comment by jasongrout** [comment]
> Looking forward to description of the principle.

The missing principle here is that the JupyterLab logconsole has nothing to do in and of itself with the python logging module. The JLab log console is for JupyterLab messages to the user. By default, all output from the kernel is logged to the jlab log console under the info level. Additionally, ipywidgets logs all output from things like button clicks, which normally is not displayed in the notebook, at the warning level - that explains the double messages that you are seeing, since you have the log filter level set to debug.

The other principle at play here is that output from button clicks is not displayed in notebook outputs (or more generally, it is not clear where output generated from comm messages in the protocol should go). If you wish to display such outputs in the notebook, use an output widget, like documented in https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html#Debugging-errors-in-callbacks-with-the-output-widget

Does that help?

**Comment by jasongrout** [comment]
And the one more thing you are seeing is that the log console does not support rich widgets, so it is showing the text display of a widget rather than an interactive widget as a control.

**Comment by drhades** [comment]
@jasongrout Quite helpful. Thx!
