### ISSUE TITLE
Yellow color in notebook tracebacks is almost invisible

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#807]
Trying out JupyterLab as a day-to-day replacement and I've noticed that tracebacks are pretty hard to read. Is it too early for this sort of feedback? I'm happy to continue using the Notebook until things settle down but am also happy to provide this type of feedback if its useful at the current stage of development?

As can be seen below:
![image](https://cloud.githubusercontent.com/assets/881019/18072628/fbc7fd9a-6ea2-11e6-9165-da1660c87ff2.png)

The same traceback but with the text selected so that it's actually visible:
![image](https://cloud.githubusercontent.com/assets/881019/18072636/0b71314e-6ea3-11e6-8ea7-5eb17ea61374.png)

**Comment by Carreau** [comment]
That's one long standing issue about the traceback, and its also in part due to IPython.

@takluyver and I have been wanted for a while to refactor the exception mechanism to have "Structured" traceback that can have a richer/more pleasant representation that may adapt to the UI instead of dumping them to text+ANSI escape sequence.

I've been recently reading on [error reporting](https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html) across [various languages](http://elm-lang.org/blog/compiler-errors-for-humans) , but there are some limitation in Python I've tried [work around](https://github.com/ipython/ipython/pull/9073) without much success.

The harsh color are "Just" a question of mapping from ansi-escape sequence to actual color and are a question of CSS, but changing them will make other people unhappy are AnsiColor tend to be standard.

It's probably a combination of tweaks to both JupyterLab and IPython.
