### ISSUE TITLE
File Browser: Hide or resize 'Last modified' column

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#8081]
## Description

Hi,
it would be nice to allow to hide / change width of **Last modified** column in File Browser.

Explanation why?
* **We know, it is possible to resize the File Browser horizontally**.  This helps a lot in general,
but for our cases this is not friendly solution, because resizing FileBrowser cause re-rendering of all displayed notebooks. We mostly have quite **big notebooks** and re-rendering big notebooks takes long time (5-30 seconds) and it is very slowing down / painful experience.

See visualization below.
 
![2020-03-24_181927](https://user-images.githubusercontent.com/6208056/77457629-3d405080-6dfd-11ea-8d5c-319cbf661b3b.png)

## Expected behavior

Ideal solution:
1. FileBrowser should have its columns resizeable.
2. There should be option to completely hide secondary column like 'Last modified'

## Context

It is is clearly visible in any 2.0.x JupyterLab (latest version in March 2020)

**Comment by markellekelly** [comment]
I can work on this!

**Comment by isabela-pf** [comment]
I talked to @markellekelly about what would be good UX for making this happen. For resizing, we plan to follow what JupyterLab already does for resizing spaces (for example the cursor change between the sidebar and the notebook).

For hiding and showing the Last Modified section, we have two main options.
If hiding Last Modified is something that needs to happen infrequently, it can easily be a context menu option. The con here is that it will be the only thing in the context menu for that narrow top area of the sidebar. If it should be more toggle-able, then it could work as a button with a text label like “Hide” and “Show,” respectively. It would need to be text-based because the sort by arrow in the top of the sidebar already toggles between Name and Last Modified, making it impractical and possibly confusing to have more icons in that small area.

Let me know if this makes sense and please feel welcome to provide feedback.

**Comment by stefansimik** [comment]
My opinion:
- Last Modified is something that needs to happen infrequently.
- Context menu option is **intuitive, simple** and just makes sense.
- Context menu is also systematic solution, because we can possibly extend it with more columns in the future, in case FileBrowser will support more columns.

I thing suggested design is OK: simple, intuitive and extendable UX design.
100% meets all my expectations for usability and future extension.

**Comment by isabela-pf** [comment]
It looks like the PR has been successfully merged. Can this issue be closed?

**Comment by jasongrout** [comment]
Thanks!
