### ISSUE TITLE
Too Many CI Jobs

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8117]
## Description
Our limit for concurrent jobs is [20](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits).   Right now we are getting backed up hard from active development today.  I think we should stick with a services job and an all-the-rest job for JS on Windows and Linux.

**Comment by blink1073** [comment]
cc @jasongrout

**Comment by blink1073** [comment]
Also, workflows have to be restarted in full, you can't [restart a single job](https://github.community/t5/GitHub-Actions/Ability-to-rerun-just-a-single-job-in-a-workflow/td-p/41629) yet.  We might need to have separate `.yml` files.

**Comment by blink1073** [comment]
We should put the longest running jobs first, as @ivanov can attest.

**Comment by blink1073** [comment]
Ha, and in the opposite direction, I think we need to break out the checking of the changelog links into a separate job, since the docs job is sometimes timing out now as we add more links to it.

**Comment by blink1073** [comment]
@bollwyvl is doing some excellent work in https://github.com/jupyterlab/pytest-check-links/pull/12 to add caching to our link requests.

**Comment by blink1073** [comment]
@trallard, do you know who we can talk to about getting our jobs limit raised?  Because we have 200+ members of our org, the Teams price is rather large.  The Teams pricing seems geared toward a GitHub org that is owned by a company, not by a distributed OSS project.

**Comment by trallard** [comment]
Hi apologies for only getting back to you folks. I am going to reach out to people in GH as I know in the past Teams was free for Open Source large orgs but I cannot find any reference anywhere now. 

Will get back to you as soon as I hear back.
In the meantime, if you need any help with the migration to GH actions ping me here!

**Comment by blink1073** [comment]
Thanks @trallard, I hope you are well!

**Comment by trallard** [comment]
Hey folks just got a response back! It seems the Jupyterlab account is not an org but Jupyter is. 

Will shoot an intro email with folks at GH so that they help you get into the org/plan that makes more sense for you all. 

@blink1073 can you email me at trallard [at] bitsandchips dot me so I can send the intro. 

I will also add @jasongrout  but I am sure I already have his contact email

**Comment by jasongrout** [comment]
Thanks @trallard!

**Comment by blink1073** [comment]
Update: we're now upgraded to GitHub Team, meaning we get 60 concurrent GH Action jobs across the org.
Thanks again @trallard!

**Comment by goanpeca** [comment]
@blink1073 since CI on Github does not cancel duplicate builds on forks, that is also a source of problems and consumption. I have built a small bot to cancel duplicate builds and run on heroku free tier. I could set that up for the jupyterlab org as well so we do not waste resources when running successive commits from forks. I could open a new issue to track that Thoughts?

**Comment by blink1073** [comment]
Sounds great, thank you!
