### ISSUE TITLE
UI UX Exploration: Settings User Interface.

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#8148]
We currently have an advanced settings editor, but not a 'normal' one.

There is a team from UCI who's working on this with me, we'll post updates and questions here.

**Comment by telamonian** [comment]
We absolutely need this. I like vscode's approach to presenting core and extension settings together in one scroll. I think anything we have should have roughly the same capabilities, if not exactly the same design:

![image](https://user-images.githubusercontent.com/2263641/78167547-ac7cfc80-741c-11ea-9cf4-1765d667ccd3.png)

**Comment by telamonian** [comment]
One blocker on the technical side has been "how do we generate appealing forms from our existing settings .json files?" We currently don't have the necessary zoo of nice input components internally.


There was a brief push for us to adopt [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form):

#5892
#7250

@ian-r-rose actually got it working in an experimental branch, but it was never merged:

https://github.com/ian-r-rose/jupyterlab/tree/settings-form

In theory, react-jsonschema-form can generate fairly nice looking forms directly from our existing .json schema files:

![image](https://user-images.githubusercontent.com/2263641/78168779-82c4d500-741e-11ea-9bac-e46bea543651.png)

The upstream issues that stopped those earlier efforts have seemingly been resolved, so now may be a good time to revisit that work. If we do adopt react-jsonschema-form, it will still likely require a great deal of theming work in order to actually look nice.

**Comment by fcollonval** [comment]
Hey just sharing a recent discovery here:
https://github.com/vazco/uniforms

It looks more interesting than react-jsonschema-form due to it's higher modularity especially regarding theming.

And this also brings back the question of a dedicated UI components library for jupyter.

**Comment by telamonian** [comment]
@fcollonval uniforms looks neat

**Comment by bollwyvl** [comment]
Howdy folks! Very glad this conversation has come back up.

The work that ian started was blatantly stolen by me and eventually became [jupyterlab-rjsf](https://github.com/deathbeds/jupyterlab-starters/tree/master/packages/jupyterlab-rjsf), extracted from the [parent repo](https://github.com/deathbeds/jupyterlab-starters) into its own [installable](https://www.npmjs.com/package/@deathbeds/jupyterlab-rjsf) package. I've shipped a couple products with it, and seen some folk do some pretty mind-blowing but alas, not open source, things with it.

In its current form, `jupyterlab-rjsf` is a few things:
- an async react component, to keep the load small
- a JupyterLab theme (on top of the "basic" bootstrap layer)
- _decent_ jupyterlab theme variable-aware CSS 
- a fairly opinionated lumino widget which wraps the above
- a couple of extra rjsf fields and widgets (buh)
  - a pretty full-featured codemirror field for text (and a "deep" one for ye-olde-blob-of-JSON)
- a markdown-aware renderer for `title` and `description`
  - this has some kinks, because of some the impedance between react and how rendermime works... good enough for static schema, less good for highly-dynamic ones
- no tests, other than robotframework browser tests against FF 68 esr

> On a [branch in that repo](https://github.com/deathbeds/jupyterlab-starters/pull/38), I even went down the document registry route, where you could live author JSON schema, JSON instances, and rjsf's ironically un-schema'd `uiSchema` as separate documents... the closest to the "mime pipe" concept I'd done that kinda inspired, but then got run over by, the "data bus". Will probably warm that back up at some point.

**However**, since the first alpha release of `jupyterlab-rjsf` a few weeks ago, rjsf 2.0 dropped (which had a _very_ long alpha cycle), which handles a _ton_ of issues, and now 
- is Typescript native (or what isn't, has tested, first-party typings)
  - my typings were... okay
- offers a material ui theme out of the box (thanks, i'll take plain-old-dom
  - but more importantly, demonstrates a clear path to deeper theme customization

So my thoughts on the matter:
- draft 7 JSON schema is probably the most jupyter-aligned thing we have today for specifying arbitrary data
- rjsf is the best implementation I've found (i tried out uniforms and formik, and went back to rjsf)
  - though I want grids like formik real bad, but can't stomach the handsontable-based add-on one for rjsf 

i would be ecstatic if, after I update it to rjsf2, `jupyterlab-rjsf` or a derivative would be considered to be moved up into core, with whatever UI opinions we have to slap on top of it. I could even see aligning things like an "advanced" command palette based on [command arg schema](https://github.com/jupyterlab/lumino/issues/58) which would make deep, chained, no-nodejs-or-webpack macros and history possible.

**Comment by telamonian** [comment]
@bollwyvl Dumb question: what's the difference between .json5 and "draft 7 json"?

**Comment by jasongrout** [comment]
draft 7 json schema is https://json-schema.org/specification.html - a way of specifying the structure of a json file, kind of a meta-json file.

json5 is https://json5.org/ - a "nicer" json format

**Comment by bollwyvl** [comment]
@jasongrout thanks for the backup!

- Another good resource is [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/)

I don't think there's a strong coupling between the serialization and the schema form model: a particular `SchemaForm` Widget, takes a value, or `formData` in rjsf terms, which could (presumably) be serialized to json5, and _also_ claim that it conforms to a JSON Schema... I haven't seen many JSON Schema definition _in_ json5, though, while yaml seems quite popular in the config space.

**Comment by bollwyvl** [comment]
A little news from the front: the upgrade from `react-jsonschema-form@1.8` to `@rjsf/core@2.0` (and adding `strictNullChecks` along the way) has been basically painless. I'll probably do an alpha release, and take a look at some other downstreams before trying a PR here. No guarantees on timeline, but given that @ian-r-rose and I had basically done all the integration work before, it should be fairly straightforward to warm back up. It would be a pretty straight shot to bring back, with the components being like:
```
packages/
  ui-components/
    src/
      components/
        async.tsx
        schemaform/
           form/ # all the rjsf stuff
           widget.tsx 
  settingeditor/
    src/
      formeditor.tsx 
```

from what is already implemented, I would likely leave out...
- the live markdown stuff
- the codemirror form/fields

...and from the UI feedback above:
- the collapsing tree nav, just sticking with the multiple picker
- search

...as all of these things would entail _even more_ opinions than adopting `@rjsf/core`. However, I feel we'd definitely want them, eventually!

**Comment by josecaldera** [comment]
Hello, everyone! I'm with the UCI team that's tackling the normal/basic settings view.

Our work so far is heavily informed by VS Code's single scroll experience (which we agree with @telamonian is well-constructed).

We've prepared a [small wireframe prototype](https://www.figma.com/proto/6FMvhnqrPMNax4S9ti1FFA/UCI_CC_IA_Wire?node-id=401%3A673&scaling=min-zoom) for you to check out. You can also find the screens as PNGs below.

This is still in wireframe stages, so we're only thinking about where things are placed and how people will interact with them at the moment. We'll layer UI design to make it more visually appealing in the coming weeks.

Please help us shape this experience! We're specifically looking for hard blockers or feedback on how this will be implemented technically, and any interplay that has with design. We're also interested in reading your thoughts on the value of the "Commonly Used" section (which would be the same for all users/not personalized).

Many thanks in advance!

---

**1. Accessing Settings**

<img width="1600" alt="1_AccessingSettings" src="https://user-images.githubusercontent.com/8893000/87810958-b3384f80-c812-11ea-8eff-0f5c4de178d8.png">

**2. What We'd First See Upon Clicking Basic Settings**

<img width="1600" alt="2_CommonlyUsedExperience" src="https://user-images.githubusercontent.com/8893000/87810972-b8959a00-c812-11ea-953b-5c605f96052a.png">

**3. The Search Dropdown in Action (note that we're also preparing a search results screen 🙂)**

<img width="1600" alt="3_SearchDropdown" src="https://user-images.githubusercontent.com/8893000/87810989-bf241180-c812-11ea-9676-e4600fe8f36d.png">

**4. A Confirmation Dialog That Appears When Restoring All Modified Settings to Default**

<img width="1600" alt="4_RestoreDefaultsDialog" src="https://user-images.githubusercontent.com/8893000/87811003-c519f280-c812-11ea-8409-b7a0283026f7.png">

**5. A Toast That Would Appear When Restoring an Individual or All Settings**

<img width="1600" alt="5_Undo" src="https://user-images.githubusercontent.com/8893000/87811028-d06d1e00-c812-11ea-8992-88cac2fd0454.png">

**Comment by bollwyvl** [comment]
From an implementation perspective, this would be relatively straightforward as one MainAreaWidget with a SplitPanel, with each of the individually-constrained schema as a separate instance of rjsf. RJSF makes (kinda nasty) `id`s for every field, so you'd be able to do the anchor links fairly effectively from the sidebar.

The hack i put into jupyterlab-rjsf would be able to do the markdown rendering in the messages (I see some links there).

Another very useful feature for this would be to be able to import/export the `overrides.json` (_not_ json5, i think) that one needs to re-create the specific settings when doing a lab build e.g. on binder. Both might need to allow for not (im|ex)porting a particular extension, or even a particular field, as some extensions put sensitive information in these settings. But trying to gather all that stuff up by hand is a real pain.

**Comment by bollwyvl** [comment]
Some additional treatments probably needed: what does it look like when...
- a value is not valid according to the the schema?
- an extension doesn't provide `title` and/or `description`?
  - by default, rjsf just uses the name of the current field
- an item of type `array` is addable/removeable/reorderable?

**Comment by bollwyvl** [comment]
Welp, you didn't ask for it, but with jupyterlab/jupyterlab_server#99 in, there's the promise of knowing (in the future):
- whether the user has created a personal settings file for a particular section
- when they created it
- when they last modified it

Not sure what to do with this!

**Comment by josecaldera** [comment]
@bollwyvl - thanks for the feedback! 

1. Happy to hear that the anchoring is pretty straight forward!
2. Interesting that you brought up import and export! This came up during user interviews as well and we chatted with Tim about it potentially being a phase 2 or phase 3 feature. Glad to hear more demand for it though because it helps support priority!
3. By value not being valid, I imagine you mean error handling? If so, good news - that's in the process of being designed!
4. Will make sure to design layout cases in which a title or description is not present.
5. More good news, we are polishing the UX on an addable/removable/editable/reorderable array!
6. In the metadata issue you linked you mentioned there being the possibility of "settings I most recently changed" would that facilitate sorting? Asking cause in the modified section we originally envisioned a sort that allows users to sort by alpha or recently changed.
7. Will toss the availability of last_modified and created values into the old noggin. Will come in handy when we start preparing to handoff of a post-launch list of recommendations.

Thank you again for the feedback and the info!

**Comment by bollwyvl** [comment]
> By value not being valid, I imagine you mean error handling?

Well... you kinda get what you get: sometimes they are pretty good, like `value is not one of foo, bar or baz`. Sometimes they are gibberish `does not match regular expression \d+(px|rem|%)`. I've usually ended up flex-boxing them to the right, so you can scan down the right-hand side for all the warnings, and _generally_ not have the overall length change, which looks gross. I think the overall field group with a schema violation also gets a class, so you can put a border on it, too...

> In the metadata issue you linked you mentioned there being the possibility of "settings I most recently changed" would that facilitate sorting?

You'll be able to know, for example, _which extension did i most recently configure?_, not _what individual setting entry did i most recently change?_. Some extensions have... a lot. So it's not going to be overly-informative. But it's probably still better than "A-Z or the highway".

**Comment by isabela-pf** [comment]
I’ve spoken to members of this team twice now and wanted to record in writing some of the potential connections to workspace management UI in #6944 we’ve talked about. 

Saving and loading settings (and needing to export and import them to do so) also came up in the [JupyterLab Team meeting yesterday](https://github.com/jupyterlab/team-compass/issues/79). I mentioned that people agreed on a good experience for this in the case of workspaces ([prototype is here](https://www.figma.com/proto/SBQKZNYlMwqs7I0C9ZPx6Fxr/Launcher-Design-Iterations?node-id=672%3A345&scaling=scale-down) if anyone is interested in testing if that experience might roughly make sense for settings) and it might make sense to draw on that for settings. Multiple people mentioned that where a workspace is one JSON file, a whole set of settings is probably multiple files and the experience would have to address that.

Even though we decided in #6944 that a main area widget seemed ideal for managing workspaces for now, there has already been interest in it belonging elsewhere. We have discussed that it might make sense as an addition to the normal/basic settings UI explored here or as an overview in a consolidated left sidebar panel (over in #8650). Personally, I am not confident yet that either is a better option and would like to keep exploring to make sure that workspaces fit with the surrounding content. This would be a great place for people to weigh in on how they expect workspaces and settings to relate (if at all).

I haven't had a chance to look at the prototype in depth, but I'm looking forward to doing so soon. This is an exciting project with great work behind it!

**Comment by josecaldera** [comment]
@bollwyvl - Awesome, thanks for the info! We'll be sure to include our MVP version of error handling in the upcoming mocks. We'll keep your placement and the info you shared in mind as we think it through. Hang tight as we prepare that next cut for you to look at. Also, noted on the metadata - I fully envision that metadata being leveraged in a v2 or beyond.

@isabela-pf Thanks for the links and the info! Are you perhaps free to join the UCI team and I this coming week to discuss the placement? Def want to start baking that into the normal/basic UI sooner than later if we decide that it's the appropriate home.

**Comment by bollwyvl** [comment]
> a whole set of settings is probably multiple files and the experience would have to address that.

The [overrides.json](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#settings) format might be the right one for import/export. 

It looks like:
```yaml
{
  "@jupyterlab/filebrowser-extension:browser": {
    "navigateToCurrentDirectory": true
  },
  "@jupyterlab/apputils-extension:themes": {
    "theme-scrollbars": true
  },
  ...
}
```

Pro:
- Reusing existing things we already have code and tests for is good.
- Anything that helps people build something interactively, then check in and reuse programatically is good.
- When put in `$PREFIX/share/jupyter/lab/settings/overrides.json` It can be used to start Lab where that becomes the default, which is nice in a deployment scenario (e.g. binder) without modifying actually-configured user settings (which is correct Jupyter behavior, however frustrating that is) 
- For import/export purposes, it may be appropriate to fancy up the name, e.g. `my-settings.jupyterlab-config`.
- if it actually _is_ JSON, it could _also_ have a schema, of sorts... but not much of one without loading all the _other_ schema, dynamically basically 
```yaml
type: object
patternProperties:
  '[^:]+:.+':
    type: object
```
 
Con:
- I can't find whether it is a JSON file or a JSON5 file. It probably doesn't make a big difference, as I wouldn't even go to the effort of doing a treatment of leaving notes for yourself in the new UI, but... 
- if JSON
  - it might be surprising if you hand-edit a bunch of config files and leave notes for yourself (please don't take that away) and then it comes out without those comments.
- if JSON5
  - is a non-standard file format where the various parsers don't agree on how much of the "spec" they support

Non-exclusive alternatives:
- zipball/tarball of a subset of `$APP_DIR/settings/*/*.json`
  - pro
    - would preserve comments 
    - would reuse existing directory structure, which is the "truth"
  - con
    - would either have to add a dependency to parse said bundle in-browser, or add significant complexity to backend
    - wouldn't be hand-editable
- concatenate with magic delimiter
  - pro
    - hand editable
  - con
    - yet another file format that nothing else will be able to parse
- stuff into notebook metadata, e.g. `#/metadata/jupyter/lab/settings`
  - pro
    - could be attached to _any_ notebook
    - is raw JSON with a first-party schema on disk
    - when opened, it could toast, `This Notebook suggests settings for [ico] Plugin [...] [View]`
    - as hand-editable as any of the above, i suppose, less so than JSON5
  - con
    - is raw JSON
    - if broadly used, the toast would probably be annoying, and you'd end up enabling it... as a setting...
- TOML/YAML/etc
  - pro
    - even more hand-editable than JSON5
  - con
    - not used anywhere else in the stack by users

**Comment by isabela-pf** [comment]
@josecaldera I can meet this week! I passed on more specific scheduling details via Tim.

**Comment by isabela-pf** [comment]
I finally got a chance to put my thoughts about the prototype in writing. Overall this works as I would expect of a settings editor, which I hope is great news! 

It’s a small detail, but right now the menu bar option calls this editor Basic Settings while the tab title just says Settings. I’d be better if they match to avoid confusion.

I’m curious about how you envision some of the interactions for the search. Do you imagine search results returning just headers and subheaders, or do they almost work like Find and show everywhere (even descriptions) that the word is found? I notice the search predictions has a prompt to “Search in Extensions.” Do is there a reason searches only search part of the settings? Does it default to Core JupyterLab or to the area the user is currently in?

Additionally, I’m also excited to see how some of these interface elements that I think are new to JupyterLab (like the radio buttons) are used. I also see this as a good chance to test some existing elements in an interface unlike others we currently have. 

Long term, I’m wondering if there is a reason that these new Basic Settings and Advanced Settings would need to be separate main area widgets rather than the same main area widget with different headers. This is looking ahead and may not be in the scope of this work, but I wanted to bring it up nonetheless.

**Comment by afshin** [comment]
@bollwyvl The `overrides.json` file is JSON without comments. I am a proponent of the zip format for import/export but I think you make good points about its downsides.

@isabela-pf:
> Long term, I’m wondering if there is a reason that these new Basic Settings and Advanced Settings would need to be separate main area widgets rather than the same main area widget with different headers. This is looking ahead and may not be in the scope of this work, but I wanted to bring it up nonetheless.

I agree. We originally wanted two views of the settings editor and even began a "table view" version that was read-only and meant to eventual work a bit like an earlier version of Firefox's advanced settings `about:config`, but we removed it because it was read-only and not that useful. Putting both UIs in the same place makes sense to me.

**Comment by jonmariano21** [comment]
**UPDATE** of feedback when restoring default settings and different color scheme ideas. 

![Restore_Default](https://user-images.githubusercontent.com/5933700/89480102-5b25a680-d749-11ea-9b11-8993ac9cd87d.jpg)
![Color_Options](https://user-images.githubusercontent.com/5933700/89480101-5a8d1000-d749-11ea-88d6-a7f8d1170805.jpg)

**Comment by hyeji36** [comment]
Thanks for the feedback! Adding to above screen shots, here are the latest navigation/search experience design. We will figure out putting basic and advanced settings on the same panel.

1. Accessing basic settings
![Screen Shot 2020-08-05 at 9 27 28 PM](https://user-images.githubusercontent.com/62810147/89482629-460c4000-d768-11ea-8267-8a0afa41aeb1.png)

2. Basic settings with navigation panel (tab title has been revised to Basic Settings from just Settings)
![Screen Shot 2020-08-05 at 10 11 48 PM](https://user-images.githubusercontent.com/62810147/89482860-ca5ec300-d768-11ea-98a2-7de6d0f723c1.png)

3. Anchor/external link visual design
Anchor link: orange italics font
External link: orange font with external link icon
![Screen Shot 2020-08-05 at 9 27 50 PM](https://user-images.githubusercontent.com/62810147/89482973-042fc980-d769-11ea-8acb-d0cdd76eef6f.png)

4. Anchor/external link visual design hover state
![Screen Shot 2020-08-05 at 9 28 04 PM](https://user-images.githubusercontent.com/62810147/89482999-114cb880-d769-11ea-8cfd-b26ba88563a1.png)

5. Search experience: 10 matching options, give an option to find a feature in extension outside of jupyterlab.
![Screen Shot 2020-08-05 at 9 28 18 PM](https://user-images.githubusercontent.com/62810147/89483080-435e1a80-d769-11ea-8ea5-1050331efa53.png)

**Comment by josecaldera** [comment]
@isabela-pf Thanks for all of the feedback! We just updated the tab header to read "Basic Settings." And to answer your question we were originally just displaying matching setting names (I.e. we're not envisioning this searching against descriptions, parent category labels, or anything else). We are however going to be including small, breadcrumb-like labels to each result for additional context.

@isabela-pf & @afshin - Phenomenal point! Our initial instinct was to use a tab system within the same panel: one tab for Basic and one tab for Advanced. We'll speak with Tim this week and see if there's any reason/blocker on why we can't reconsider it again for MVP. In the meantime, here's an early look at what it could look like:
<img width="905" alt="PotentialTabs" src="https://user-images.githubusercontent.com/8893000/89851748-17b0ab00-db42-11ea-9f47-d160ce4371fa.png">

**Comment by josecaldera** [comment]
Status Update: We ran a final set of sentiment tests against mid-fidelity mocks over the past weekend. We used this prototype: 

https://www.figma.com/proto/6FMvhnqrPMNax4S9ti1FFA/UCI_CC_IA_Wire?node-id=539%3A710&scaling=min-zoom

**Major Takeaways:**

1. Settings dropdown experience needs some polish (we're exploring a breadcrumb-like experience to provide further context/differentiation around matching strings. Not unlike this wire with placeholder results/parent category data:
<img width="271" alt="Screen Shot 2020-08-10 at 7 08 51 PM" src="https://user-images.githubusercontent.com/8893000/89851965-9e658800-db42-11ea-9ad6-4eec000c746f.png">

2. We'll be adjusting the wording in several areas of the feature.

3. Assorted UI updates to get this much closer to PROD-quality work.

Please feel free to reply with any further feedback or questions! Any items that can responsibly make it into MVP will do so and any pieces of feedback that are out of scope will be included in a list of improvements to be made in future iterations.

**Comment by ajbozarth** [comment]
I've mentioned this in a couple dev meetings but I'm willing to work on implementing this. I know there was interest in getting this into 3.0, but I'll be taking a week vacation this coming week and wouldn't be able to start on it until after Labor Day So if someone else wants to start work and try to get it into 3.0 while I'm out, feel free, otherwise I'll be picking this up on Sept 2nd when I'm back. (right after the dev meeting that day)

**Comment by josecaldera** [comment]
@ajbozarth - This is great to hear! The UCI team has taken the MVP just about as far as we can with the time allotted. We reviewed with @isabela-pf and @tgeorgeux and it's just about ready for handoff. I'll be creating two replies beneath this one momentarily for linking reasons: 
1. Mocks of Several Key States
2. Developer Notes

**Comment by josecaldera** [comment]
### **Basic/Normal Settings MVP Handoff Part 1 - Mocks of Spacing/Key States**

Hi, below are mocks for key states of the MVP. These mocks should provide a very clear picture of the relationship between all of the elements with nearly full conformity to JupyterLab's design system (new font variants leveraging different weights and letter spacing were created among other small things). 

@isabela-pf and @tgeorgeux have reviewed and approved, though they've communicated that there may be small adjustments/refinements as they prepare to formally hand it off to engineers. I additionally expect that engineering might uncover use or edge cases that weren't foreseen at which point @isabela-pf will be person to reach for any design questions.

Thank you all for your feedback throughout the past few months - I can't wait to see future iterations of the settings experience!

![1 1 Settings Panel - Min-Width](https://user-images.githubusercontent.com/8893000/91609009-78eec180-e92b-11ea-8be3-5b559a522de1.jpg)
![1 2 Settings on Load (Without Modified Settings)](https://user-images.githubusercontent.com/8893000/91609013-7be9b200-e92b-11ea-82c5-e080bc4216f1.jpg)
![1 3 Settings on Load (With Modified Settings)](https://user-images.githubusercontent.com/8893000/91609016-7c824880-e92b-11ea-8f8d-aa7813d4fbb9.jpg)
![1 4 Restore All Settings Dialog](https://user-images.githubusercontent.com/8893000/91609018-7db37580-e92b-11ea-9581-e8feb6e5184a.jpg)
![1 5 Restoration Toast](https://user-images.githubusercontent.com/8893000/91609020-7e4c0c00-e92b-11ea-9105-b98e25041754.jpg)
![1 6 Conducting A Search](https://user-images.githubusercontent.com/8893000/91609022-7ee4a280-e92b-11ea-97df-e515091b0b1b.jpg)
![1 7 Search Results Page - With Results](https://user-images.githubusercontent.com/8893000/91609025-7f7d3900-e92b-11ea-917e-11727e48e587.jpg)
![1 8 Search Results Page - No Results](https://user-images.githubusercontent.com/8893000/91609028-8015cf80-e92b-11ea-9538-158b13175670.jpg)

**Comment by josecaldera** [comment]
### Basic/Normal Settings MVP Handoff Part 2 - Developer Notes (+ Bonus: Visibility on Progress on Array Input Not Meant for MVP)

Below are developer notes documenting the items above. The UCI team has aimed to be as comprehensive as possible while still having the documentation be loose enough to not be rigid and uncompromising.

@isabela-pf will be the point of contact for design moving forward.

Thanks again!

![2 1 Developer Notes - Left Panel](https://user-images.githubusercontent.com/8893000/91609360-1ea23080-e92c-11ea-8c1b-0c491e92299f.jpg)
![2 2 Developer Notes - Right Panel](https://user-images.githubusercontent.com/8893000/91609366-2366e480-e92c-11ea-9e58-bcd4fdee25c8.jpg)
![2 3 Not For Development - Array](https://user-images.githubusercontent.com/8893000/91609368-25c93e80-e92c-11ea-9da4-84d6f3e2becc.jpg)

**Comment by bollwyvl** [comment]
Mocks look good! We'll see how they survive first contact with code!

Had been discussing with @goanpeca and @krassowski about other places we basically need an off-the-shelf, feature complete JSON schema form generator. `jupyterlab-lsp` is going to end up having a _ridiculous_ level of configurability: e.g. for completion (that issue linked above) we have:
- grouping of "related" features (not nested in the schema)
- custom UI for picking completion icons
- a custom inspector of the DOM to find CodeMirror tokens (far more humane than having to use inspector, or read the CodeMirror source)
- might end up with animated SVG/HTML previews of how some of the features interact with each other

... and all of the above should be configurable at both a global level, and per-language.

Here's a very-WIP (but fully-functional) screenshot of the gross bespoke UI:

![](https://user-images.githubusercontent.com/45380/91661883-b890e700-eaac-11ea-83dc-b0e2e1926d34.png)

So, from a DX point of view, this issue needs to take into consideration ways that an extension developer can:

- get 90% configurability for free, if they just follow the spec
- a way to add annotations to groups in the schema (or code)
  - ideally with icons
- have an escape catch to overload a _particular_ widget for a _particular_ field, which may include:
  - a bespoke renderer (probably react, because that's what all the off-the-shelf stuff supports)
  - filling in a `patternProperties` with not-available-until-runtime values
- have everything look consistent, and participate in fancy search behavior, etc.

We're probably going to try to land the bespoke thing we have in-progress, and then independently work on a `jupyterlab-rjsf` refactor, which should inform whatever solution arises here... presumably a new API for `ISettingsManager`.

**Comment by goanpeca** [comment]
Thanks for the feedback @bollwyvl, I could work on bringing the necessary parts from  https://github.com/deathbeds/jupyterlab-starters/tree/master/packages/jupyterlab-rjsf into core if this is a path that is agreed on.

Building this new settings UI will definitely need something like that, as @bollwyvl pointed out, the LSP work has "a ridiculous level of configurability".

**Comment by bollwyvl** [comment]
@goanpeca as was mentioned elsewhere, that library is there for the taking, and was extracted for basically for this purpose. It's _basically_ good enough to use, already, and I've shipped it (in starters and wxyz) on a number of open source and work projects. I'm happy to help in any way I can so I can stop having to maintain it separately! Some caveats:
- obviously only knows about the Lab 2.x APIs
- doesn't have dedicated jest-based unit tests, but is heavily tested as part of starters with robotframework/selenium
- integration with the markdown+math rendering of `title` and `description` leaves a something to be desired, and almost doesn't work with rapidly changing schema (a la widgets)
- uses "dumb" theming based on the plain-old-bootstrap-like DOM... a blueprint-based theme exists, but doesn't appear to be open source.
- the codemirror field isn't _great_
- as mentioned, we'll be learning more as we try to bring in some of our fancy LSP stuff, but our focus there is getting out a new release (with or without my new stuff)

**Comment by isabela-pf** [comment]
Thank you so much for all your work @josecaldera and the whole team! ✨ It was great to work with you all. I’m excited to support this UI being developed and happy to answer questions around how it will shift with it’s “contact with code,” as bollwyvl put it.

To follow up, one of the things we talked about was if workspace management UI could fit here, particularly in relationship to a switch workspaces UI in the left sidebar like in #8650. This is very much a WIP, but here’s my current idea of mockups. 

To reiterate, this isn’t in the MVP of the proposed Settings UI. Just an additional proposal for review, especially as an alternative to #6944’s proposal (since I’m not sure workspaces are high-profile enough to warrant their own main are widget). Feedback always welcome.

I particularly dislike the Create New and Import sections. But it's not getting better without feedback, so here it is.

<img width="785" alt="settingsworkspaces" src="https://user-images.githubusercontent.com/50221806/92023210-4c62ed00-ed11-11ea-8772-958d9109f3f9.png">

**Comment by bollwyvl** [comment]
A wrinkle on this:

As long we we can think about settings as being "just JSON," and ignore JSON5, we have a number of places where settings could live, roughly in order:
- outputs (i have no idea what this would mean)
- cell metadata
- notebook metadata
- workspaces (in metadata... or somewhere better)
- paths (e.g. a folder that contains a `.jupyterlab-settings`) with "closest to the file wins"
- repos? (e.g. a `.jupyterlab-settings` in the root of the repo)

Any would be a lovely place for a large number of extensions to be able to put finely-tuned settings information, following the `overrides.json` structure.

Concrete cases:
- [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp/issues/440)
  - wants this for controlling completion sources 
- [@jupyterlab/pull-requests](https://github.com/jupyterlab/pull-requests)
  - could use this to constrain pull requests fetched to those in the current repository
- [jupyterlab-fonts](https://github.com/deathbeds/jupyterlab-fonts/)
  - already implements this for notebook and cell (though some things, like embedded fonts, only get blobbed into top-level notebook)

A concrete design for the plumbing:
- a `jupyterlab:scopes` attribute on top-level schema `properties` which would default to `[user]` if omitted, as registered by `ISettingsManager` itself.
  - `priority` and `rank` are always tough, probably need some way to constrain their position, e.g. `overloads` and `defersTo`
- `ISettingsManager.registerScope(key: string, provider: ISettingsProvider)` would allow extensions to provide their source of information
- subsequent requests to get/set settings could be enhanced to include some `ISettingsContext`

While in the porcelain:
- the UI described here would show at what level a value _can_ be set
  - and can be opened for a specific scope, e.g. _Show Notebook Settings_

This would definitely strain what RJSF is capable of today, and may require something more like an ordered conjunctive graph, if that's even a thing.

**Comment by isabela-pf** [comment]
@bollwyvl just checking in, do you think these options have UI impacts other than the last bullet point? This sounds mostly like options for how to implement this so different parties can interact with it in different ways, but I want to check there's nothing I need to immediately address here.

**Comment by bollwyvl** [comment]
Ehm, I guess one could reflect the _effective_ settings at a particular place, e.g. in a particular cell. In the notebook, where this would get the most complex, an ["annotation sidebar"](https://github.com/jupyterlab/jupyterlab/issues/9976#issuecomment-804960077) could show a _:gear:_, and open a scope-filtered list of settings which _could_ be set on _that_ Cell, and after being set, a list of configured settings would be displayed.

I don't _think_ this would impact export/import, as I don't think there'd be the expectation that you'd get magic cell config somehow into `overrides.json`.

**Comment by ajbozarth** [comment]
A heads up, @marthacryan and I are starting to look into implementing this. Is there anyone currently working on this that we may step on their toes?

**Comment by isabela-pf** [comment]
@ajbozarth @marthacryan Hooray! 

I'm not aware of anyone working on this! Last I heard was @afshin had his name on it for #9647 but has also said in meetings that he'd be happy if other people did it.

**Comment by afshin** [comment]
@ajbozarth and @marthacryan, please do, by all means!

**Comment by bollwyvl** [comment]
Yeah, my toes are safe, as well. Again I'll toss out the 80% solution represented by [jupyterlab-rjsf](https://github.com/deathbeds/jupyterlab-starters/tree/master/packages/jupyterlab-rjsf)... 80% in that:
- the markdown rendering for titles, description, etc. is kinda trash
- it still gets a tad confused when the schema changes quickly
- is going to take some _thinking_ with how defaults/composite work

Giving extension authors access to a general-purpose, schema-driven form tool for _their_ boring form UI (not just _our_ shared settings UI) will make a _lot_ of things simpler for folk that don't want to wade into heavy react junk. Of course, they _also_ need to be able to make their settings look harmonious with the rest of lab, but not be stuck with what comes in the box if they need something custom... if they _do_, they _will_ have to get dirty with some react, but hopefully it's much more scoped (e.g. handle _this one field_ etc). So this might raise the bar a bit on how aware a given extension needs to be of the settings ui.

Of _significant_ note: [rjsf 3](https://github.com/rjsf-team/react-jsonschema-form/releases/tag/v3.0.0) just dropped (with which the above package is _not_ compatible, almost certainly). This represents a number of substantial improvements which couldn't land until some breaking changes were allowed to happen... but sadly, embedding ui customization into schema directly didn't make the cut. But that's ok: we already have bespoke fields all over the settings meta-schema that _aren't_ part of Draft 7, so adding `uiSchema` (or whatever) won't be much of a departure.

**Comment by ajbozarth** [comment]
Copying some notes from todays dev meeting:

  - [example](https://user-images.githubusercontent.com/45380/91661883-b890e700-eaac-11ea-83dc-b0e2e1926d34.png) of desired customized settings (crusty [PR](https://github.com/krassowski/jupyterlab-lsp/pull/328))
  - additional [shortcuts UI](https://github.com/deathbeds/jupyterlab-keycaps) implementation

**Comment by aiqc** [comment]
closed by https://github.com/jupyterlab/jupyterlab/pull/11079
