### ISSUE TITLE
Feedback on new extensions manager disclaimer in 2.1b0

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#8149]
Follow up on  #7967 #7989

- after updating from 2.0.1 I had to enable the extensions, even though I was offered to re-build to include the extensions that I had previously installed (and I had the extension manager enabled) - IMO the upgrade experience is not the smoothest and a bit confusing, but this may be ok
- once enabled the warning shows up again and again when I refresh the page - is this intended?
![warning_stays_on](https://user-images.githubusercontent.com/5832902/78175771-4e1f4080-7453-11ea-9e7a-001f939d9dc6.gif)
(please ignore the blurry text it's an HDPI/scaling issue in Chrome)
- not a designer, but the lack of a separation between the warning and the list seems weird:
![Screenshot from 2020-04-01 20-00-47](https://user-images.githubusercontent.com/5832902/78175928-95a5cc80-7453-11ea-8219-224e0d4548c5.png)
IMO having a 1 px line would make it nicer:
![Screenshot from 2020-04-01 20-02-28](https://user-images.githubusercontent.com/5832902/78176067-cbe34c00-7453-11ea-9fed-3241072dfde5.png)

Otherwise great work everybody, looking forward to see final 2.1 release!

**Comment by jasongrout** [comment]
CC @tgeorgeux

**Comment by saulshanabrook** [comment]
Just chatted with @jasongrout about this and have some thoughts:

> after updating from 2.0.1 I had to enable the extensions, even though I was offered to re-build to include the extensions that I had previously installed (and I had the extension manager enabled) - IMO the upgrade experience is not the smoothest and a bit confusing, but this may be ok

I think this is unavoidable unfortunately with our current build system. We could improve the message to make it clear that this also happens when you upgrade jupyterlab as well as when you install a new extension.

> once enabled the warning shows up again and again when I refresh the page - is this intended?

Yes, I think when disclaimed setting is true, we should hide the message by default on load.


> not a designer, but the lack of a separation between the warning and the list seems weird:

Yeah I agree. What about just not making the header sticky? The other headers are not sticky headers.

**Comment by echarles** [comment]
>>    once enabled the warning shows up again and again when I refresh the page - is this intended?

> Yes, I think when disclaimed setting is true, we should hide the message by default on load.

I have thought about that while developing the disclaimer and though that the disclaimed setting was not really the one to use to show/hide the warning section. In other words, it is not because you agree with the warning that you want to hide it.

I guess introducing another extension manager setting for show/hide would be overkill.

The workspace state comes to my mind but I have never really looked how this was working. It sound to me that the show/hide of the warning section would be a good candidate to persist as a workspace state.

WDYT?

>>    not a designer, but the lack of a separation between the warning and the list seems weird:

> Yeah I agree. What about just not making the header sticky? The other headers are not sticky headers.

Will look into this.

**Comment by jasongrout** [comment]
> In other words, it is not because you agree with the warning that you want to hide it.

I think making it workspace state makes sense, but I also think the vast majority of the people will want to acknowledge it and then for it to go away, so I think Saul's suggestion is great too, and quite a bit easier to implement, i.e., that the default open/closed state is set from the acknowledgement status.

**Comment by echarles** [comment]
I have opened a PR to fix the reported issues https://github.com/jupyterlab/jupyterlab/pull/8163

I can onboard in that PR the final decision discussed in https://github.com/jupyterlab/jupyterlab/issues/8161

**Comment by saulshanabrook** [comment]
Fixed in https://github.com/jupyterlab/jupyterlab/pull/8163
