### ISSUE TITLE
Invalid response: 500 Internal Server Error

### ISSUE THREAD

**Issue by mher2004** [jupyterlab/jupyterlab#8171]
Hello i am a newbie in this and when i open the terminal in jupyter lab in the windows opens a new tab and said a error 500 i haved updated jupyter jupyter lab with pip command i have windows 7 32 bit sp1 the browser i have is opera gx i tried in the general opera browser but i think it is not from browser jupyter i have downloaded with pip comands because anaconda doesnt work on my pc(i dont know why) please help me )

**Comment by asteppke** [comment]
The response `500 Internal Server Error` is unfortunately not very specific. Jupyter lab consists of many components and packages, if the installation did not produce a state of compatible dependencies this can lead to this response. 

You can start diagnosing this by looking into the console output, often the source of the problem is already obvious from this. 

Even though you said that anaconda does not work for you I would still try to get that running, they provide a relatively stable environment that has been tested to work well with Jupyter lab and is therefore more beginner friendly.

**Comment by mher2004** [comment]
if i upload the image of my console can you help me in this error i definitely doesnt know what to do i tried very much times to install anaconda but it doesnt install well i had viewed many tutorials to solve the error but nothing works if you help me i will be very thankful
![Capture](https://user-images.githubusercontent.com/44675886/78503466-c188c100-7777-11ea-9940-5a0134e3ff87.PNG)

**Comment by asteppke** [comment]
So Jupyter lab is trying to start a terminal using `powershell.exe` and this fails. It looks at first glance that this is preventing the further startup of Jupyter. 

You can reset Jupyter by moving or deleting the configuration. The configuration is located in 
`C:\Users\<your username>\.jupyter`. If you rename the whole directory Jupyter will create it from scratch. 

If this does not help I would still go for the Anaconda route and look into their documentation for the installation.

**Comment by mher2004** [comment]
Thank you for your help i will try that way if doesnt work will serach a method to install anaconda thanks very much
