### ISSUE TITLE
Remove Azure Pipelines Checks

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8265]
## Description
As we've been investing more into GH Actions, our Azure Pipelines are suffering.  Frequently we've been merging PRs that pass GH Actions and fail Azure Pipelines.  I think at this point we have enough confidence in GH Actions to commit to it and not split our efforts.

cf #8261 #8117

**Comment by jasongrout** [comment]
One other reason I kept Azure around is because it had better stats, like which tests are failing across a number of checks and issues, etc. It's too bad that we don't have that with GitHub actions. We weren't really making use of that data, though, so I don't think that consideration should hold us back either.
