### ISSUE TITLE
Fontawesome icon in ToolbarButton is invisible.

### ISSUE THREAD

**Issue by qzchenwl** [jupyterlab/jupyterlab#8277]
This problem is caused by #7947, the color attribute for `.jp-Icon` was removed.

When I manually add `.jp-Icon { color: var(--jp-layout-color4); }`, then the fa icon is visible.

**Comment by telamonian** [comment]
Yep, this is intentional. A whole bunch of unused, redundant, and/or conflicting icon-related CSS was removed as of juptyerlab 2.0. For example, `.jp-Icon { color: var(--jp-layout-color4); }` was a) the wrong color (too dark) and b) causing an issue with the coloring of inline svgs in certain contexts.

In general, if you use an external framework (fontawesome, material ui, blueprint, etc) to create icons you should expect to have to supply your own styling.

On the other hand, if you use one of our supported icon patterns, then we supply the styling:
- LabIcon
  - [docs](https://github.com/jupyterlab/jupyterlab/blob/205462d332ac7cd6ca89f7a0d22976b56f0143d6/packages/ui-components/README.md)
- icon-as-css-background:
  - in CSS, set an icon as the `background-image` for class `my-icon`
  - add the `my-icon` and `jp-Icon` classes to your icon DOM nodes
