### ISSUE TITLE
Notebook-only mode: provide a 1 to ~1 equivalent of notebook classic, implemented using jupyterlab api

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#8450]
As discussed in the 5/20/20 meeting, one perennial feature request for jlab has been a mode that looks and feels exactly the same as notebook classic. Some people don't like the filebrowser, or the side bars, or anything that pulls focus from a single notebook experience, etc. More broadly, there's [a huge swath of classic notebook users](https://www.jetbrains.com/lp/python-developers-survey-2019/) who currently haven't migrated to jlab but might do so if the UI/UX was basically identical.

There are a number of different ways we could implement such a thing. Some basic sketches:

1. Hide everything except a single widget (which could be a notebook document widget or anything else) and maybe the menu bar
2. 1-to-1 emulation of classic notebook, but built using jlab api

Some things to consider:
1. What should we name this mode? Notebook classic-ish?
2. Should there be a separate launch command for this mode?
3. Should there be a separate url?
4. Should the user be able to dynamically switch into/out of this mode?

pinging @ellisonbg @afshin @jasongrout @vidartf @ajbozarth @lucbouchard1 @nproctor @declanvk

**Comment by jtpio** [comment]
Missed the call today, but here are some thoughts from prior casual conversations with @afshin about this topic:

- Having a separate page for the file browser (reusing the existing file browser component), and being able to open single notebooks in separate browser tabs just like the classic notebook would truly recreate the classic notebook experience, instead of having several modes within the same browser tab
- This classic mode could be launched via the command line with something like `jupyter classic`, or by changing the URL to `/classic` (or `/lab/classic`)
- The classic notebook is still used a lot during presentation, and to some extent can be considered as a "zen mode" too (especially when the title bar is hidden)
- It should also be mobile-friendly (see screenshots in https://github.com/jupyterlab/jupyterlab/issues/3275)
- Technically speaking, we could imagine having another application shell with the following areas:

![image](https://user-images.githubusercontent.com/591645/82484597-6cf89580-9ada-11ea-9db7-7d49bb6555ca.png)

- This would allow some of the existing lab extensions that add components to these areas to also work in this more limited classic mode.

[Discourse](https://discourse.jupyter.org/latest) is also another place where the differences between lab and classic have been discussed. It would be interesting to ask some of the folks there to know what they would expect of a classic mode in lab.

**Comment by jtpio** [comment]
Here are a couple of relevant topics on Discourse:

- https://discourse.jupyter.org/t/any-recent-usage-polling-on-jupyter-lab-vs-notebook-usage/4344
- https://discourse.jupyter.org/t/benefits-of-the-classic-ui-and-use-cases-for-classic-over-jupyterlab-was-why-is-tim-not-moving-to-lab/2419
- https://discourse.jupyter.org/t/deploying-jupyterhub-at-your-institution/723/15

**Comment by yuvipanda** [comment]
my attempt at doing exactly this: github.com/yuvipanda/simplest-notebook

**Comment by ellisonbg** [comment]
I have opened a new issue that dives into the history, UX design and broader considerations for this: #8567

And a first PR that makes progress towards these ends: #8531

The good news is that we are closer to having this than we thought, and it will be straightforward to get there incrementally.

**Comment by vidartf** [comment]
> my attempt at doing exactly this: https://github.com/yuvipanda/simplest-notebook

Yes, that is the look and experience that I would want (and I did know of this from before) ❤️ The current hope is to make such an interface but have it be able to pick up installed lab extensions that work on the notebook, e.g. various ipywidgets extensions, etc. One way of achieving this would be to have this be a special "mode" you could put lab in.

**Comment by jtpio** [comment]
> Technically speaking, we could imagine having another application shell with the following areas

> ![image](https://user-images.githubusercontent.com/591645/82484597-6cf89580-9ada-11ea-9db7-7d49bb6555ca.png)

Currently exploring this idea in https://github.com/jtpio/jupyterlab-classic (still a very early prototype)

With a working Binder to try it out (pinned on a commit): https://mybinder.org/v2/gh/jtpio/jupyterlab-classic/fa4246e5643cc58c8d48ce474687c2ea7cb1b02a?urlpath=classic/notebooks/binder/example.ipynb

**Comment by ellisonbg** [comment]
While this is super impressive work, I think this needs more discussion. To entirely replicate the classic notebook (which has been frozen in time for many year and not itself improved significantly) misses the mark. We got years of feedback about the classic notebook that led us to create JupyterLab. Users and extension authors wanted a more powerful and complex layout system and there are many classic notebook extensions hack around these limitations in painful ways. While there is a lot more work needed, I believe the Simple/Single Document Mode of JupyterLab is a good start in finding the right tradeoffs between the elements of the classic notebook that users miss, and the extensibility and layout that classic notebook users were asking for.

**Comment by yuvipanda** [comment]
Love this, @jtpio!

@ellisonbg for a lot of use cases, I think having 1:1 replication of classic notebook is a *great* transition step for folks already used to the UX + docs that point to it. I don't think this will go into JupyterLab classic, but IMO it's important to encourage this kinda work - both to possibly deploy it, but also to make sure that JupyterLab components are truly usable outside of JupyterLab itself.

**Comment by echarles** [comment]
>  IMO it's important to encourage this kinda work 

+1

> make sure that JupyterLab components are truly usable outside of JupyterLab itself.

+1

**Comment by yuvipanda** [comment]
As an example, I'm just in a video call where someone is teaching new faculty how to use the notebook, with the classic UI. There's a *lot* of these, and would need to be updated before they can use JupyterLab, even in single document mode. Having something that's more visually equal will be an easier transition, and then we can move them slowly over afterwards if needed.

**Comment by jtpio** [comment]
Thanks Yuvi!

This is heavily inspired and motivated by your work on the [simplest notebook](https://github.com/yuvipanda/simplest-notebook), as well as the work from the cal poly interns on the [clarity mode](https://github.com/jupytercalpoly/jupyterlab-clarity-mode).

I think there is indeed room for both JupyterLab and an alternative distribution like JupyterLab Classic. Users can switch between the two as they wish. Especially since most components are directly reused from JupyterLab.

Some updates:

- A release candidate has been published, get it with: `pip install --pre jupyterlab-classic`
- Or use this gist on Binder: https://gist.github.com/jtpio/795608163800b4a7d34d60a015c3d27c
- Or check the screencasts in the README: https://github.com/jtpio/jupyterlab-classic#usage
- It has support for:
  - notebooks
  - files
  - terminals
  - the tree page with the file browser and running sessions
  - open new documents in a new browser tab by default
  - JupyterLab themes, the command palette
  - zen mode (full screen + main document only)
  - federated extensions

![quick-tour](https://user-images.githubusercontent.com/591645/102074925-cbce8500-3e05-11eb-9a6d-1f241597a86d.gif)

**Comment by paulrutter** [comment]
We at BlueConic offer the classic Jupyter UI within our product, do offer the user a nice way of using their profile data with python code and do machine learning and such.
This is exactly the thing we're looking for, as it offers us all the improvements of Jupyterlab, without the UI changing as much. 
Some questions about backwards compatibility remain and whether this project is future proof enough to bet on. 
I'm interested to know how you think about this?

**Comment by SylvainCorlay** [comment]
Hi @paulrutter, let me know if you would like to connect with us at @QuantStack to discuss your usecase.

The team comprises 6 core devs of Jupyter and we develop and provide professional support around the Jupyter ecosystem. Along the lines of this "classic notebook" experience, @jtpio recently published "jupyterlab-classic" which provides that kind of experience (see https://github.com/jtpio/jupyterlab-classic/).

**Comment by paulrutter** [comment]
@SylvainCorlay We're certainly open for discussing our usecase (and why we need/want something like JupyterLab Classic).
I haven't had the time to check out jupyterlab-classic yet.

**Comment by SylvainCorlay** [comment]
@paulrutter sorry I missed your message. Please feel free to reach out to me directly by email. Sending you a message to start a thread right now.

**Comment by stonebig** [comment]
Hi, 

With latest version of jupyter eco-system on windows, my Jupyter-notebook fails to opens its main page.
By contrast, Jupyterlab-classic works out-of-the-box.

I hope this transition will come soon.

**Comment by jtpio** [comment]
Closing in favor of #9869 

In the meantime, JupyterLab Classic has been renamed to RetroLab and has been [moved](https://github.com/jupyterlab/team-compass/issues/119) to the `jupyterlab` organization: https://github.com/jupyterlab/retrolab.

It is still installable with pip / mamba / conda for those who want to use it as a standalone application.
