### ISSUE TITLE
Pressing Alt+W multiple times doesn't close more than one tab

### ISSUE THREAD

**Issue by chhanganivarun** [jupyterlab/jupyterlab#8575]
## Description
Shortcuts should be designed so that if the same shortcut is pressed/entered multiple times, that particular action should be done those many number of times. However, for the Alt+W shortcut to close a tab, however number of times I press it, it only closes one tab

## Reproduce

1. Start Jupyter Lab
2. Open a few tabs
3. hold Alt key and press W key multiple times
  - **Alternate**: press Alt+W release all the keys and repeat it multiple times

## Expected behavior
On entering shortcuts _n_ number of times, _n_ tabs (or all of the tabs if number of tabs is < _n_) should be closed

## Context

- Operating System and version: Ubuntu 20.04 LTS
- Browser and version: Firefox 77.0.1 (64-bit) / Chrome Version 83.0.4103.97 (Official Build) (64-bit)
- JupyterLab version: Version 2.1.4

<details>
<summary>Further Detailes NA</summary>
<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>
</details>

**Comment by jasongrout** [comment]
The mechanics here are a bit tricky. The [close shortcut](https://github.com/jupyterlab/jupyterlab/blob/72cbe68e624e1a9a5d646984d31bd75209eae0a8/packages/application-extension/schema/main.json#L27-L29) is registered to be applicable to any element that is itself or a descendant of an element with the `.jp-Activity` css class. This makes sure you can only close actual activities. When the keybinding is run:

1. It closes the shell's current widget
2. Browser focus shifts to the `body` DOM element, which does *not* have the `.jp-Activity` class
3. Subsequent `Alt W` then do not take effect since it is not considered active for the `body` element (since it doesn't have a `.jp-Activity` class)

One workaround is to make the `Alt W` shortcut just work on the body DOM element, like all the other application-level shortcuts defined next to it. Probably a better thing is to specifically activate the tab that is the document current tab. This reminds me of something @mbektasbbg worked on a while ago, activating tabs when another closed.

My guess is that the same issue happens with the [file close and cleanup](https://github.com/jupyterlab/jupyterlab/blob/85c872efbd85d7fe5a99de5fe19c6df34d055024/packages/mainmenu-extension/schema/plugin.json#L36-L38) shortcut.

**Comment by jasongrout** [comment]
Yeah, https://github.com/phosphorjs/phosphor/issues/396 was filed by @mbektasbbg about the underlying issue here.

**Comment by jasongrout** [comment]
Ah, which leads us to this issue: https://github.com/jupyterlab/jupyterlab/issues/6648

Let's move the conversation over to #6648, which is exactly this same issue.
