### ISSUE TITLE
Does the use-sys-dir work?

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#8604]
Does the `--use-sys-dir` flag work?

## Description
 I'm trying to run JupyterLab from a specified application directory `--app-dir=./foo` and to *not* use the system directory's extensions with `--use-sys-dir=False` and I'm getting on JupyterLab 2.x and also JupyterLab 1.x:

```
[C 13:39:29.634 LabApp] Bad config encountered during initialization:
[C 13:39:29.634 LabApp] Invalid argument: '--use-sys-dir=False'
```

## Reproduce
```
jupyter lab --app-dir=./foo --use-sys-dir=False
```
## Expected behavior
This flag should be accepted as valid configuration and ignore the system directory.

## Context

cf. https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/commands.py#L314-L317

- Operating System and version: macOS and also Linux
- Browser and version: N/A
- JupyterLab version: 1.x and 2.x

**Comment by blink1073** [comment]
cc @vidartf who has more insight into `AppOptions` usage.

**Comment by vidartf** [comment]
I added that as an escape hatch on the `AppOptions` object so that the option was available (either for other apps reusing the commands, or for Lab to use in the future), but it was not wired through to the relevant application entry points. There are quite a few entry points that might be relevant in ordinary lab usage (the main entry `jupyter lab` is the most important one, but I think it will be relevant for all the `labextension` and `build` entry points as well, maybe more). All of those entry points would need to add the trait + alias and then parse that into the `AppOptions` object they create. There might be a more DRY method to expose various options on a set of entry points, but that would then need to be written.

Sorry if the presence of this option gave you false hope 😞 

A more efficient way to achieve what you want in the interim is probably to set the environment variable `JUPYTERLAB_DIR` as that will set both the appdir *and* the sys dir.

**Comment by afshin** [comment]
Cheers; thanks for the clarification @vidartf!
