### ISSUE TITLE
When the kernel is waiting for input, it can get deadlocked

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#8632]
## Description

If you run a cell with `input()` then rerun it before entering input the kernel will be deadlocked (using this term loosely from the users POV). This most often happens when interacting with `pdb`

## Reproduce
![input](https://user-images.githubusercontent.com/1813603/86173478-0c537400-baee-11ea-8be9-f2e054beac2c.gif)

Above, you can see that the second "hi" was queued correctly. But rerunning the "input" cell lost the UX element forever and thus caused a deadlock.

## Expected behavior

When waiting for input, you are blocking from doing anything that would lock the kernel from the users POV. Ideally this can be fixed for both the page refresh and rerun the same cell case. It may be easier to just handle the "oops, I reran a cell waiting for input case."

## Context

- Operating System and version: Windows
- Browser and version: Chrome
- JupyterLab version: 2.1.2

**Comment by echarles** [comment]
Thx @mlucool. I will have a look at it. I guess we can implement a lock or similar construct on the client side to deal with that case.

But we also need to take care that the lock can be unlocked otherwise the user will be be deadlocked anyway... I mean if for whatever reason the input text field is not more visible (e.g. user runs a `clear cell ouput`), the user will not have the ability to type his input, so the lock we has set on the client side will stay forever. I guess in that edge case a refresh would solve the issue as this will produce brand new client objects without client-side lock.

cc/ @blink1073  @jasongrout
