### ISSUE TITLE
Launcher customization

### ISSUE THREAD

**Issue by omazapa** [jupyterlab/jupyterlab#8840]
Dear Experts,

I am working on my customized JupytebLab extension and I would like to know if there is an easy way
to customize the Launcher. I have a set of commands and I want to have it in a launcher, without any pre-defined sections, like Nonetbook/Console/Other. (An Empty canvas).

Is that possible using the current Launcher class or should I write a custom widget from scratch?

Thanks
Omar.

**Comment by jasongrout** [comment]
These categories are hard-coded in the current Launcher extension. It would be great if someone made the Launcher more customizable.

This issue is already requested at https://github.com/jupyterlab/jupyterlab/issues/6202, so let's move any further discussion there. Also, I'll note there has been lots of conversation about the Launcher UX at https://github.com/jupyterlab/jupyterlab/issues/3795 and https://github.com/jupyterlab/jupyterlab/issues/5524
