### ISSUE TITLE
Send wait screen before loading extensions javascript

### ISSUE THREAD

**Issue by joequant** [jupyterlab/jupyterlab#8865]
### Problem

Right now when Jupyterlab starts up it loads an extension file which could be several megabytes.  In this time browser has no load screen and the system seems dead for a minute.  This only happens on the first run as the extension file is cached afterwards.

### Proposed Solution

This can be fixed by loading and displaying the wait screen first, and then loading in the extension file rather than waiting for the extensions javascript file to load.

### Additional context

This will  greatly improve usability as a lot of extensions now have large javascript files that require a large amount of time to load.

**Comment by jasongrout** [comment]
Thanks. This is also reported at #5463, with some of the same suggestions, so let's move the conversation over there. If you'd like to work on it, we'd love the help!

Some of this pain is eased with the new extension system in 3.0, since 3rd party extensions no longer have to be compiled into the single main js bundle.
