### ISSUE TITLE
Need Build steps to do a jupyterlab full build

### ISSUE THREAD

**Issue by suryag10** [jupyterlab/jupyterlab#8900]
Hi,
We are trying to take the change https://github.com/jupyterlab/jupyterlab/pull/8432 on top of jupyterlab 2.2.2. 
Can you please let us know the full build steps to generate the jupyerlab wheel file or tar ball, similar to https://pypi.org/project/jupyterlab/#files.

**Comment by jasongrout** [comment]
The release packaging instructions are at https://github.com/jupyterlab/jupyterlab/blob/master/RELEASE.md

However, these involve publishing packages to npm. This is because installing extensions into jlab involves building from released npm packages.

To build a self-contained wheel with whatever is in the source tree, I'd suggest using the application example: https://github.com/jupyterlab/jupyterlab/tree/master/examples/app

After doing the dev setup at https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#installing-jupyterlab, follow the example building instructions at https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#build-and-run-the-stand-alone-examples. The app example does not have a setup.py for packaging itself, but you could add one and package it up.

**Comment by jasongrout** [comment]
It would be nice to have a setup.py in the app example so people could make local builds, but somehow would not be publishable. Does python have the equivalent of the nodejs "private: true" package.json field that disallows uploading to pypi? If not, perhaps we set a package name, but then we publish to it, so there is an official package that we control?

**Comment by suryag10** [comment]
Thx jason for the steps. I am new to node and js. So still figuring out the steps to get the same working. I feel that the self sufficient build system should be provided as provided in other packages as well. Any thoughts?

**Comment by jasongrout** [comment]
It's a lot more complicated than that, given that JupyterLab relies on published npm packages. A self-sufficient packagable version of the app example is definitely doable, though.

**Comment by suryag10** [comment]
Looks great, app example would be a good one to start. Shall i raise a enhancement for the same.

**Comment by jasongrout** [comment]
Sure, thanks

**Comment by suryag10** [comment]
Raise https://github.com/jupyterlab/jupyterlab/issues/8916

**Comment by jasongrout** [comment]
Closing as resolved - new discussion at #8916 about the app example.
