### ISSUE TITLE
Get username from extension

### ISSUE THREAD

**Issue by djangoliv** [jupyterlab/jupyterlab#8947]
I need the username in my extension, but I don't find the best way to get the username of the current user.

Regards

**Comment by jasongrout** [comment]
What is the user name to you? Is this in JupyterHub, where you have a login username? Or are you just talking in a normal single-user setup, and you just want the username on the host machine the user is logged in as? Are you wanting the username running the server process, or a specific kernel (since kernels are different processes, they could be a different username).

Probably the easiest thing to do if you are in a typical single-user setup is to create an extension with a server-side component. The server side part creates an api endpoint on the server that can be queried for the current username of the process, and the frontend part just hits that api.

Perhaps we should have a command line argument that lets you add arbitrary information to the PageConfig. Then something like this, which won't change over the lifetime of the server, could just be in the server startup command and easily queried by any extension.

**Comment by djangoliv** [comment]
Thanks for your response. 
I want the username on the host machine. 
I will get it with a server-side component with python.
Issue is resolved for me Thanks.

**Comment by agoose77** [comment]
@jasongrout this can be closed :)

**Comment by jasongrout** [comment]
Thanks!
