### ISSUE TITLE
Audit of notebook focus/scrolling

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#906]
Because focus/srolling is so extremely subtle in the notebook, we need to audit how focus and scrolling are handled. Things to try:
- Various mouse and keyboard events related to command/edit mode.
- Scroll position
- Large cells.
- Running cells.
- Cell on different positions.

**Comment by metaperture** [comment]
In 0.2, when using the down arrow key to navigate from an editable cell to a displayed markdown cell, the "active cell" focus switches, but the cursor remains in the editable cell.

To reproduce (0.2):
[1:code] print('asdf')
[2:markdown] my markdown
render [2], put focus in 1, and hit the down arrow

**Comment by jasongrout** [comment]
Thanks. This is still a problem with e8eda3a7e25871bd0cceb00569547b578d9531cf (current master):
![focus](https://cloud.githubusercontent.com/assets/192614/18834864/34b8f040-83ad-11e6-9b02-f082bed34dbc.gif)

**Comment by jasongrout** [comment]
I think this issue may have been fixed in #981.

**Comment by blink1073** [comment]
I confirmed that the specific issue highlighted above is fixed, but I don't think we should close the issue quite yet.

**Comment by cameronoelsen** [comment]
One thing that I noticed is inconsistent between the selected state:
![screen shot 2016-10-03 at 1 27 57 pm](https://cloud.githubusercontent.com/assets/6437976/19052891/5d8c4948-896d-11e6-8b51-29acd7672b80.png)

and the active/in focus state:
![screen shot 2016-10-03 at 1 28 11 pm](https://cloud.githubusercontent.com/assets/6437976/19052896/63ee908e-896d-11e6-8b08-989b9c828955.png)

is that the border around the cell in the selected state is a larger blue border on the lefthand size with an all around border of #ABABAB while the active/in focus state has a large green border with an all around border of the same green color. This might have been done to make the shift in state more apparent. But, Here is an example of the two if they stay consistent on that gray border:

Selected state:
![screen shot 2016-10-03 at 1 27 57 pm](https://cloud.githubusercontent.com/assets/6437976/19052938/9f79248e-896d-11e6-8d6c-9c25f64ffee9.png)

active/in-focus state:
![active-consistent](https://cloud.githubusercontent.com/assets/6437976/19052997/d3c49fac-896d-11e6-9a97-8705bd1235c5.png)

Another variation that could work was only change the larger lefthand border based on state as well as change the color of the "In []" cell indicator as such:

Selected state:
![new-take1](https://cloud.githubusercontent.com/assets/6437976/19053131/6dc009fc-896e-11e6-9fbc-e047edc2345c.png)

Active/in-focus state:
![new-take2](https://cloud.githubusercontent.com/assets/6437976/19053140/74cbd38e-896e-11e6-8561-5b05e26d6363.png)


Just wondering if we want to make it so that it is a given that that left-hand border is the indicator of what state the cell is in. Up for discussion, just something I saw while poking through the latest build.

**Comment by ellisonbg** [comment]
Marking as beta because if there are remaining problems with focus, they will be really painful for users.

**Comment by ellisonbg** [comment]
The current state of master is quite nice in this respect. I have been using the notebook a ton over the past few weeks and the scrolling/focus is entirely delightful.
