### ISSUE TITLE
Single Document Mode Switch

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9105]
Thanks @jasongrout and @telamonian for working on this in #9100 and #9104. 

A couple of thoughts after trying it out:

- The new switch + label now takes quite a bit of valuable space in the top area, that was until now mostly left to third-party extensions so they could add widgets to it (examples are `jupyterlab-topbar`, `jupyterlab-system-monitor` and others, but I'm a bit biased :) )
- One might think that a user is not going to switch to single document mode often. For example classic notebook users who will probably want to switch to single document mode only once and stick to it thereafter.
- Toggling the switch on and off makes the UI "jump" up and down (when switching to SDM), which feels a bit off. Meaning that clicking at the same spot without moving the mouse does not hit the switch button:

![sdm-click](https://user-images.githubusercontent.com/591645/94660397-e5335b00-0305-11eb-8af4-df1c4985c3db.gif)

Here are a few options that come to mind to address some of these observations:

- using an icon instead of the long "Single Document Mode" string to save space in the top area
- place the switch somewhere else, or have a hint pointing to the View menu on first use. When a user knows it is in the View menu, they will be able to find it afterwards.
- make it part of the main menu, next to the Help section, for instance called `Mode`.

**Comment by telamonian** [comment]
@jtpio

- I agree with you about the jumping up and down. It's off-putting.

- I'm not crazy about the "icon + slider" UI pattern (like how the debug on/off slider is now):

  
    ![image](https://user-images.githubusercontent.com/2263641/94679414-0be59780-02ee-11eb-9e05-27640cf1f1bf.png)

  Maybe there's some way to make it seem more than one unified unit, rather than two buttons that do the same thing.

- The text content on the button is an absolute requirement for accessibility (apparently `aria-label` just doesn't cut it/work right with every tool). We can have icon-only buttons, but they need some very funky CSS to visually hide the button text while leaving it visible to the accessibility tools: https://css-tricks.com/places-its-tempting-to-use-display-none-but-dont/.

Right now I'm working on a general purpose accessible `LabButton` component. It should be easy to specialize into a `LabSlider` component as well. What's here I think is more of a one-off.

**Comment by telamonian** [comment]
The blocker on `LabButton` for me right now is ironing out a general purpose styling system that will be able to work with any future `LabFoo` components that get made. To start with, there just needs to be a way to define Typestyle styles and then dispatch them to each sub-element in the component individually. The existing styling system I made for `LabIcon` is a starting point, but it needs some work (both needs to be simplified and generalized).

@jtpio If you have any interest in weighing in on the styling system, that would be most welcome. Since this is meant to be a general purpose api that will be used community wide, it definitely should not be designed by me alone

**Comment by jtpio** [comment]
> I'm not crazy about the "icon + slider" UI pattern

Agree, and also because of the accessibility concerns mentioned above. But it could be one way to keep it compact.

**Comment by joelostblom** [comment]
What do you think about using more traditional icons for entering full screen / large view and exiting full screen / small view instead of the current slider/toggle? If you choose an icon that people are used to clicking on other sites (youtube, etc), then I think you don't need any text at all since the behavior of this icon is already recognized from elsewhere (together with a hover tooltip for clarification if needed) Some screenshot suggestions below:

What YouTube uses:

![image](https://user-images.githubusercontent.com/4560057/95379240-f9dd9900-0899-11eb-9864-ce92777364e9.png) ![image](https://user-images.githubusercontent.com/4560057/95379255-ff3ae380-0899-11eb-8382-9e7c36d273a2.png)

Two arrows:

![image](https://user-images.githubusercontent.com/4560057/95378717-280ea900-0899-11eb-82d2-9396e70c9490.png) ![image](https://user-images.githubusercontent.com/4560057/95378734-3066e400-0899-11eb-8e1d-dbd8374bbb29.png)

Four arrows:

![image](https://user-images.githubusercontent.com/4560057/95378917-7cb22400-0899-11eb-985b-b65cd0050b21.png) ![image](https://user-images.githubusercontent.com/4560057/95378989-9a7f8900-0899-11eb-8726-adebe81a8e37.png)



More elaborate:

![image](https://user-images.githubusercontent.com/4560057/95379088-bc790b80-0899-11eb-83db-c8267fa5c1b8.png) ![image](https://user-images.githubusercontent.com/4560057/95379113-c4d14680-0899-11eb-9cfd-44fbbd5a5865.png)

**Comment by jasongrout** [comment]
> * The new switch + label now takes quite a bit of valuable space in the top area, that was until now mostly left to third-party extensions so they could add widgets to it (examples are `jupyterlab-topbar`, `jupyterlab-system-monitor` and others, but I'm a bit biased :) )

The label is simply "Mode" now.

> * Toggling the switch on and off makes the UI "jump" up and down (when switching to SDM), which feels a bit off. Meaning that clicking at the same spot without moving the mouse does not hit the switch button:

Fixed now.

**Comment by jasongrout** [comment]
Is there anyone that wants to iterate more on this for 3.0, or should we move this issue to 3.1 to consider with other feedback in #9117?

**Comment by jtpio** [comment]
Thanks @jasongrout for the improvements on the single document mode.

And also the mode switch has now been moved to a separate plugin that can be disabled: https://github.com/jupyterlab/jupyterlab/pull/9270 (linking here for extra context).

> should we move this issue to 3.1 to consider with other feedback in #9117?

We can even close this issue and keep the discussion in #9117.
