### ISSUE TITLE
Add support for evaluating code when stopped at a breakpoint

### ISSUE THREAD

**Issue by dbalabka** [jupyterlab/jupyterlab#9111]
Currently, during a debug session, ipython console isn't available because is blocked by debug session.
It would be great to get the possibility to add custom expressions into variables panel. As I understood, the variable panel represents only current scope variables and there no such possibility. 
![image](https://user-images.githubusercontent.com/1269372/77638478-ea32de80-6f5f-11ea-8d69-3f3923657812.png)

**Comment by wuyuanyi135** [comment]
This will be an extremely useful feature. Currently writing a function embedded in a cell is painful because of the lack of autocompletion and variable tracking. With this it should be much easier.

**Comment by JohanMabille** [comment]
I think a console might be more adapted if we want to keep track of the evaluated code. A few remarks regarding this console:

- it should be clearly different from other consoles, so the user can clearly identify it
- we should forbid some functions to be executed in this console, such as asking for a user input. The reason is that the code will be executed by the debugger and not the shell. This will prevent the kernel from sending the message to create the input widget in the frontend, and this will result in a deadlock.

**Comment by jasongrout** [comment]
A kernel can signify whether it provides a stdin channel or not, IIRC. Perhaps we can just pretend that the kernel does not have a stdin channel?

**Comment by JohanMabille** [comment]
Ah, I was not aware of this feature. This is a great idea!
