### ISSUE TITLE
Enable dynamic?federated extensions in dev mode

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#9235]
### Problem

For now, the dynamic?federated extensions are forced-disabled in dev_mode

https://github.com/jupyterlab/jupyterlab/blob/f7cb7b5e208d732c8d841ae84d219cbebc97b22a/jupyterlab/labapp.py#L618-L619

Sometimes, like the work done in https://github.com/jupyterlab/jupyterlab/issues/8804, we need those extensions enabled in dev mode

### Proposed Solution

Add a setting/flag like `--extensions-dev-mode` to keep the extensions enable in dev mode,.

**Comment by jtpio** [comment]
Maybe this could even replace the `add:sibling` script, if third-party federated extensions can be installed in dev mode.

**Comment by jasongrout** [comment]
We discussed this in a meeting, and realized that it's more subtle, since you'd want to use `yarn link` to install the dev core packages into the federated extension. Essentially, since the core extensions are all in a monorepo, yarn automatically links them all together so they see the version that is on disk, but since a federated extension would be in a different repo, we'd need to do that linking ourself.

That said, we *could* have a federated extension compiled against a released set of core packages, but then loaded in dev-mode with the dev packages. For many situations, this would work (even if it complains if the dev mode versions do not match the existing released versions).
