### ISSUE TITLE
Naming for Type A and Type B Extensions

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#9237]
### Problem

JupyterLab 3 supports:

- Installing Type A extensions which needs a build
- Installing Type B extensions without the need for a build

We have used various naming so far without a decision on this, e.g. :

- Static (Type A), Dynamic (Type B)
- Bundle (Type A), Federated (Type B)

### Proposed Solution

This issue is opened to have a decision on this so the docs, UI and code can be updated

cc/ @jasongrout @isabela-pf

**Comment by isabela-pf** [comment]
Of the terms we’ve already been using, I prefer dynamic/static.

I think bundled works fine, but don’t like federated since I don’t think it will mean much to users. I think something like dispersed or remote works better since it describes the location of the extension in more common language.

I also have a few rough options for names that might be meaningful from the user side because they focus on what the results of this change will feel like when installing an extension. Since they are all based on the same ideas and can (probably) be interchanged, I’ve listed them by type.
- Type A: build-needed, local, restart, delay
- Type B: dispersed, remote, quickstart, instant, one-click

I expect some of these ideas to be thrown out because they match with or confuse other technical languages, so just let me know if these are on the right track at all if you like this concept.

**Comment by jasongrout** [comment]
Here's another thought:

For users, we don't try to distinguish between the two types of extensions. From a user's perspective, an installed extension is in one of three states:
  - Activated (i.e., installed and functioning on the page, technically these are the ones coming in the browser page config)
  - installed, but browser page refresh needed (these are federated extensions, or extensions requiring a rebuild that have already been built in - technically these are the ones the extension api says are installed or compiled in, but are not in the page config)
  - installed, but needing a rebuild (presumably the api will tell me which extensions still are requiring a rebuild)
Thinking like a "typical" user, I don't care about the technical details, and it's confusing to map from these technical terms onto what I need to do. All I care about is how I get the extension installed and functioning, i.e., what is the next step to get the extension working on the page. This answers those questions.

We might eventually want to distinguish for a user whether an extension would hypothetically require a rebuild if it were installed, before installation, but I think the common pattern in other platforms is to just install the extension, and then it tells me that, oh, by the way, you'll need to quit and restart for this particular extension.

Doing this means we don't need a user-facing term for these two ways of distributing extensions. That means we can start using more technical terms for extension developers. For a technical term, static vs dynamic sort of captures some of the intuition, but it's not a good match either (typically statically compiling something means that you include all its dependencies in a single bundle, but you aren't doing that for the single npm package, and the "dynamic" extensions are compiling some of their dependencies in, so in that sense they are sort of on the static side...).

For the technical side, for extension developers, I think "federated" is a good word because:

1. It conveys the idea of multiple things coming together, somewhat independent from each other, to form a whole
2. It is not a technical term in wide use in our area, so we get to define it more clearly without people having the wrong intuition
3. It maps well onto the "module federation" lingo that we are building on in webpack

**Comment by jasongrout** [comment]
Another thing I realized when writing https://github.com/jupyterlab/jupyterlab/pull/9252 is that we need to be careful not to create the intuition in extension developers that these two ways of distributing an extension are mutually exclusive. It is perfectly reasonable for an extension to be published to npm as a single package and at the same time be wrapped in a python package as a federated extension. For that reason, I think using "type", which sort of sounds mutually exclusive, is the wrong word for this concept. I tried to explain this in #9252 for extension developers.

**Comment by jasongrout** [comment]
> From a user's perspective, an installed extension is in one of three states:

That list was for the frontend extension manager. `jupyter labextension list` of course cannot distinguish between activated and requiring page refresh, so it should just distinguish between extensions that are installed and ready to use, and those that require a rebuild. I think we probably also ought to take out the paths, and list the paths when you give a `--debug` or `--verbose` switch.

**Comment by echarles** [comment]
@jasongrout How would you name the "non-federated" extensions?

**Comment by jasongrout** [comment]
> @jasongrout How would you name the "non-federated" extensions?

For developers? I don't know - that is really just the npm package, so perhaps just saying that you publish the package to npm and that's it? An extension is a JavaScript package, and you can for convenience distribute that package as a federated bundle? Still working on the terminology here. Thoughts?

**Comment by echarles** [comment]
> Thoughts?

A lot... too many?... e.g.

- For the user, a `federated` which does not need rebuild and can not be uninstalled from CLI is not the same as a `non-federated` which does need rebuild and can be uninstalled from CLI. We can try to make look the same, try to make the technical details transparent to them, but there are not the same, and we will get IMHO push back from users soon.
- I'd love reviews on the extension manager WIP in https://github.com/jupyterlab/jupyterlab/pull/9236, especially from the user perspective to ensure we know what to develop there.
- I love the recent (and very fast, congratulations for that!) move to add the metadata which define the packager. I would see even more details to add the provider of the extension (conda-forge is not pypi...). Maybe showing the provider and the characteristics of the provider (needs rebuild or not), we could solve the terminology question. So we say `npm` extension (needs rebuild), `pypi` does not need rebuild.... later on `nix` does not need rebuild...

**Comment by jasongrout** [comment]
>  * So we say `npm` extension (needs rebuild), `pypi` does not need rebuild.... later on `nix` does not need rebuild...

Whether or not it needs a rebuild is independent of the package manager.

**Comment by isabela-pf** [comment]
I think that’s a good point, @jasongrout, that most users might not care about different extension types or even what they have to do to fully install them. I also agree that not having any feedback until being told “oh you need to restart to have this take effect” is a common pattern we could follow, and it might help prevent confusion between needing to have user versus developer terms for the extension types.

I still have one question. It sounds like users can wait to rebuild as long as they want/need as long as they don’t personally need that extension immediately. Is there any reason this isn’t true? Because this would be the case where I would want to make sure we keep the labels.

Because we tend to hear a lot from JupyterLab users who also develop for Jupyter, I also agree with @echarles that we might not want to totally hide that there are different kinds of extensions. Still, I think I could be convinced to go either way.

It sounds like it might be most important to name for development purposes, and `federated` might be the most informative. Why not use `bundled` as has already been used so far for the non-federated extensions?

**Comment by jasongrout** [comment]
> It sounds like users can wait to rebuild as long as they want/need as long as they don’t personally need that extension immediately.

That's correct. Also, JupyterLab automatically prompts a user to rebuild if it is needed.

**Comment by jasongrout** [comment]
> Why not use `bundled` as has already been used so far for the non-federated extensions?

'bundled' makes sense for both extensions, depending on your frame of reference. Either an extension is bundled with core JupyterLab (the non-federated extensions), or it is bundled together with its dependencies (the federated ones). If we use the word bundle for the non-federated extensions, then we have to be careful about the words we use to describe the federated extensions (we can't say they are bundled with their dependencies, for example).

**Comment by jasongrout** [comment]
More thoughts:

- pre-built vs needs-built
- cooked vs uncooked
- baked vs unbaked
- one step vs two step
- plug-and-build vs plug-and-play

**Comment by asteppke** [comment]
As a humble user a quick office poll lead to very confused facial expressions when asking about the cooking terms or non-descriptive ones such as 'one step' vs 'two step'. Please use descriptive terms (a large number of your users are non-native speakers) with their most common usage. 

* MyHumbleExtension (built package), (built), (plug-and-play), (pre-built)
* MyHumbleExtension (unbuilt package), (src package), (build-needed), (build required), (plug-and-build)

seem broadly understandable.

The term `bundled` is almost always used for extra items that comes with a main software package, which would describe extensions that are part of the base JupyterLab installation well.
`Federated` is clear within the developer context of the extension build process but outside of this context it is not clear what the larger federal thing is that the package might be a federated item of. `Static` and `Dynamic` have a clear meaning within a software development context where both resulting products can be used without further processing/compilation which is clearly not the case for an unbuilt package (on a developer machine this distinction is less clear but an end user as far as I understand it can never use an unbuilt package right away).

**Comment by jasongrout** [comment]
Ah, a "source" extension - I like that, and it contrasts nicely with a "pre-built" extension.

**Comment by jasongrout** [comment]
For what it's worth, I've started using "prebuilt extension" and "source extension" and those two terms are growing on me.

**Comment by asteppke** [comment]
@jasongrout 
This looks quite intuitive, depending on the context (e.g. on a page listing different extensions) this can even be shortened to 
* MyJupyterlabExtension ([prebuilt package](http://prebuilt), [source package](http://source))

Anyway thank you for pushing 3.0 out the door!

**Comment by jasongrout** [comment]
We discussed it more in the dev meeting today, and decided on:

* Type A (need to be built): "source"
* Type B (do not need to be built): "prebuilt"

Thanks everyone for the discussion and thoughts!
