### ISSUE TITLE
Upgrade style setting in upgrade_extension

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#9514]
### Problem

The upgrade script is great. But it is missing a late complex point about style setting in `package.json`

### Proposed Solution

The script should update the `package.json` file to add `style/index.js` where needed.

### Additional context

It took me some times to figure out what was wrong when replacing the official launcher when porting that alternative launcher: https://github.com/fcollonval/jlab-enhanced-launcher

**Comment by jasongrout** [comment]
Because of https://github.com/jupyterlab/jupyterlab/pull/9475, using `styleModule` doesn't really help for prebuilt extensions yet (i.e., things are not deduplicated between prebuilt bundles), though it does help with source extensions where you have all the packages in the same bundle, which is why it is important we use it in core. If an extension does not import styles from dependencies (and does not have its own styles imported in other extensions), it doesn't help any either.

Until https://github.com/jupyterlab/jupyterlab/pull/9475 is resolved, it may be better to remove the styleModule parts of the cookiecutter.
