### ISSUE TITLE
White border in black terminal in Lab 3.x is distracting

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#9529]
## Description

In 3.x with light mode, new dark terminals display a distracting white border around the entire terminal.

## Reproduce

1. Create a new terminal while using the light mode. The resulting terminal has a 1px white border as shown here:

![image](https://user-images.githubusercontent.com/57394/103431130-4a565100-4b80-11eb-98f7-f5d439fce5e5.png)

As @timkpaine pointed out in discussion on gitter, this is coming from [an explicit css rule](https://github.com/jupyterlab/jupyterlab/blame/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/terminal/style/base.css):

![image](https://user-images.githubusercontent.com/57394/103431143-65c15c00-4b80-11eb-87ad-ecf002dbc512.png)

## Expected behavior

I think this white border should simply be removed. It wasn't there before, no terminal emulator I've ever used has one, it serves no functional purpose, and it's quite distracting while using Lab.

I'm happy to make a small PR if it would help, though I imagine the core team could fix this (if agreed) far faster than I'll gear up a dev setup for Lab :) 

Thanks folks!

**Comment by jasongrout** [comment]
Looks like this is from https://github.com/jupyterlab/jupyterlab/pull/8994. My guess is that it would have been better to set the color to [transparent](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#transparent_keyword), rather than keyed off of the theme, if we have to have a border.

Good news! You don't have to get a dev setup to contribute this fix! You can edit the [file in GitHub](https://github.com/jupyterlab/jupyterlab/blob/master/packages/terminal/style/base.css) online using the pencil icon in the upper right, create a PR straight from the editor, then use the binder link that is automatically generated for you to test it. I'd suggest just making it a single rule like:

```
.xterm .xterm-screen canvas {
  border: none;
}
```

or

```
.xterm .xterm-screen canvas {
  border: 0px solid transparent;
}
```

**Comment by jasongrout** [comment]
In fact, the best solution is probably just to delete those two CSS rules completely.

**Comment by fperez** [comment]
Done, thx for the tip @jasongrout! I trust my CSS skills so little that I was skittish about posting a PR without local testing, but given it's just code removal, might as well :)

**Comment by ellisonbg** [comment]
Sorry I missed this one over the holiday. Those CSS lines were an (partially failed) attempt to fix a bug in xterm. This PR shows a screenshot of the bug: https://github.com/jupyterlab/jupyterlab/pull/8994

These issues describe the bug and the fix used here:

https://github.com/xtermjs/xterm.js/issues/1974
https://github.com/eclipse-theia/theia/issues/4665#issuecomment-494699663

The problem with my fix is that I keyed this style to the overall theme rather than the terminal theme. I don't have JLab built right here to check this - does anyone know if we have a CSS class on the terminal that encodes its theme color, so we could switch on that rather than the JupyterLab theme?

**Comment by ellisonbg** [comment]
Ironically, the bug I was trying to fix was exactly the bug I introduced, just in a different context.

**Comment by jasongrout** [comment]
> I don't have JLab built right here to check this - does anyone know if we have a CSS class on the terminal that encodes its theme color, so we could switch on that rather than the JupyterLab theme?

I think we just deleted the border css. It seemed to be our CSS anyway--we weren't overriding anything from xterm (perhaps there used to be xterm css that we were overriding?)
