### ISSUE TITLE
Table of Contents collapsibleNotebooks setting

### ISSUE THREAD

**Issue by jvschoen** [jupyterlab/jupyterlab#9535]
### Problem

* One of the best features of the old toc extension was collapsible sections. This allowed one to work through large projects from one notebook going through the pipeline/workflow. This core table of contents doesn't show how to enable collapsible sections in the notebook. In recent versions there was a `collapsibleNotebook` config variable in the *Advanced Settings* sections. 

### Proposed Solution

* Add option to allow collapsible notebook sections when collapsing table of contents sections. I personally think this should be default behavior.

**Comment by jeffyjefflabs** [comment]
There is [this extension](https://github.com/aquirdTurtle/Collapsible_Headings) but it doesn't look like it's been updated for Lab 3 yet.

**Comment by jeffyjefflabs** [comment]
Update: The [collapsible_headings extension](https://github.com/aquirdTurtle/Collapsible_Headings) works with Lab 3 as of a few days ago.

**Comment by jdtsmith** [comment]
I can't seem to find how to enable section collapsing despite reading the docs very closely.  This would match the excellent TOC behavior of Google Colab, for example.  Is there still a `collapsibleNotebooks` setting I can enable (lab version 3.0.7)? I don't find it anywhere in Advanced Settings...

**Comment by andrewfulton9** [comment]
It looks like [collapsing notebook cells from the ToC  was removed from the ToC extension when it was became part of core Jupyterlab due to a lack of APIs for collapsing groups of cells.](https://github.com/jupyterlab/team-compass/issues/63#issuecomment-631763535)

I am wondering if there has been any work on those mentioned API's. Is that something that is on the roadmap for future development?
Is the idea to have someone write an external extension to handle the collapsing notebook cells?[ I see that the ToC has had signalling added to communicate a sections collapse.
](https://github.com/jupyterlab/jupyterlab/pull/8601)
@kgryte, @marthacryan, @blink1073, and @jasongrout, do any of you have an understanding of what the status is here? I'm reaching out because it looks like all of you were the most involved in the ToC core extension development/discussion.

**Comment by jasongrout** [comment]
There is a lot of discussion about this over in https://github.com/jupyterlab/jupyterlab/issues/2275

In particular, you may be interested in an extension @aquirdTurtle showed: https://github.com/aquirdTurtle/Collapsible_Headings

Do you think we should move discussion over to #2275 and close this issue, or does this issue cover a separate concern not addressed in the discussion over in #2275?

**Comment by andrewfulton9** [comment]
My understanding is that the Collapsible_Headings extension adds the ability to collapse groups of cells which is needed for this issue to be resolved, but I don't think it is set up to listen to signals from the ToC extension so that when a user collapses a section in the ToC, the corresponding cells are collapsed too. I think this issue is dependent on #2275, but Im not sure its covered by it.

**Comment by jasongrout** [comment]
Cool, thanks for the clarification.

**Comment by aquirdTurtle** [comment]
@andrewfulton9 that's correct and syncing with the toc extension / functionality is probably one of the bigger [feature requests](https://github.com/aquirdTurtle/Collapsible_Headings/issues/23) in the extension... I was trying to get some of this signaling like this set up with the notebook looking for the right signals earlier, e.g. in [this](https://github.com/jupyterlab/jupyterlab/issues/9507) issue. I guess I was trying to get this dragging and dropping issue working properly first and never got around to figuring out how I might be able to look for signals from the toc extension. I think I spent a little time looking at how to do this and it wasn't immediately obvious to me. This sounds like in principle it shouldn't be hard to fix if someone could indicate how to reference the appropriate signal from my extension, but I'm also not sure how much this is desired to be independent of my extension.

**Comment by jvschoen** [comment]
I agree all around. The collapsible_headings is a great extension that I use as well, but it would be nice if the native TOC would integrate with something like @aquirdTurtle's extension, or if this was just native functioning of TOC for the new jupyter verison.

**Comment by andrewfulton9** [comment]
@aquirdTurtle, I should have some bandwidth to help add in the signalling if you'd like the help. I think it would also be desired to add a signal to your extension so when a user collapses a header in the notebook, the ToC plugin collapses as well making the communication two way. I think since the collapsible functionality seems to be a popular feature request, it's worth considering making your extension a core package of JupyterLab so users get it out of the box. I would like to hear your thoughts on that though.

**Comment by aquirdTurtle** [comment]
@andrewfulton9 Absolutely. As far as I can tell the signal should be emitted [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/toc/src/generators/notebook/index.ts) in the onClick handlers, and currently there is simply no signal. I'm not super familiar with typescript or the style that jupyterlab is written in so I'd be really hesitant to submit a pull request myself. I looked a while ago and I also couldn't find anything about the desired way to set up signaling within the extension developer's guide. I'm a little busy right at the moment so I can't promise I'll get to anything immediately, but I'd definitely pick it up given a week or two.

If people want to add the extension as a core package, I'm happy to support this in any way I can! It's probably not currently up to the the standards for jupyterlab core code, but I'm happy to spend a bit of time cleaning it up for that as well given a little time.

**Comment by fcollonval** [comment]
@marthacryan could we consider this as fixed with #10260?
