### ISSUE TITLE
jupyterlab.upgrade_extension generates wrong package names

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#9560]
## Description

upgrade_extension chooses the JS name for the python package instead of a pythonic name. That is if an extension is named `foo-bar`, it uses `foo-bar` in `setup.py` instead of `foo_bar`. This breaks imports.

## Reproduce

1. Clone https://github.com/deshaw/jupyterlab-execute-time
2. Run jupyterlab.upgrade_extension (I choose to replace all files when asked)
3. Follow the `Development install` step in the README. When you get to `jupyter labextension develop . --overwrite` it will error with:
```
$ jupyter labextension develop . --overwrite
/opt/python/python-3.7/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
An error occured.
ModuleNotFoundError: No module named 'jupyterlab_execute_time'
```

## Expected behavior

It just works :). The solution for me was the change name in setup.py and rename the generated directory.

## Context

- Operating System and version: Linux
- Browser and version: N/A
- JupyterLab version: 3.0.1

**Comment by xcao38** [comment]
I got the same error as yours when I was following this tutorial: https://jupyterlab.readthedocs.io/en/latest/extension/extension_tutorial.html#extension-tutorial
I have MacOS. 
```
$ jupyter labextension develop --overwrite .
An error occured.
ModuleNotFoundError: No module named 'jupyter_ext'
See the log file for details:  /var/folders/21/dr8847md4mz_fzks9mzt6npr0000gn/T/jupyterlab-debug-o79trbl2.log
```

**Comment by jasongrout** [comment]
I thought this might be a problem with the cookiecutter since that seems to be the thing in common between the two situations.

I followed the steps in the tutorial and didn't see an error when doing the `jupyter labextension develop --overwrite .` (on macOS as well). I see that somehow you have `jupyter_ext` in your error (maybe you didn't use the same names as in the tutorial?), so I tried having different python and labextension names in the cookiecutter, and the labextension develop command still worked fine.

**Comment by jasongrout** [comment]
@xcao38 - can you show exactly what you used as inputs to the cookiecutter prompt?

**Comment by jasongrout** [comment]
@mlucool - as far as I can tell, this came from the default python name suggested by the cookiecutter being an invalid name for a python package, namely `jupyterlab-execute-time` instead of `jupyterlab_execute_time`.

Perhaps the upgrade script should replace invalid package name characters with `_` like Python would, to give a valid python name.

@xcao38 - is that your problem too? Did you give a python name of `jupyter-ext`, which would be an invalid python name because of the dash?

**Comment by jasongrout** [comment]
> @mlucool - as far as I can tell, this came from the default python name suggested by the cookiecutter being an invalid name for a python package, namely `jupyterlab-execute-time` instead of `jupyterlab_execute_time`.

So I guess I'm just confirming what you mentioned in your first paragraph.

**Comment by krassowski** [comment]
@bollwyvl I believe you had an opinion on this when we were upgrading the LSP extension

**Comment by xcao38** [comment]
@jasongrout -  Hi I can confirm that I was using `-` dash for my labextension name and python name when I posted my comment. I then tried to use `_` underscore for both labextension and python name. The problem was alleviated.
