### ISSUE TITLE
Client performance when moving notebook panels

### ISSUE THREAD

**Issue by mrocklin** [jupyterlab/jupyterlab#958]
Moving panels around in my browser appears to be more performance intensive than I would have expected. I can easily push chrome to 100% usage by dragging borders between panels around. Is this expected?

I'm moving a notebook and a terminal to reproduce the issue.

Migrating here from https://github.com/phosphorjs/phosphor/issues/148

**Comment by sccolbert** [comment]
Note: there are potentially two issues here:
1. Drag-Drop panels which cause a *reconfiguration* of the dock panel.
2. Resizing individual panels by dragging a splitter handle.

There are reports that some browsers are slow on (1). I am working on a new dock panel internal layout mechanism which will fix this and also provide better support for iframes.

Number (2) is really what we should pay attention to here. There is a known optimization we can make by limiting the number of code mirror widgets in a notebook. If a cell does not have input focus, it should be a static rendering rather than a live code mirror cell. This will cut down on the number of reflows per resize event.

**Comment by jasongrout** [comment]
> Number (2) is really what we should pay attention to here. There is a known optimization we can make by limiting the number of code mirror widgets in a notebook. If a cell does not have input focus, it should be a static rendering rather than a live code mirror cell. This will cut down on the number of reflows per resize event.

Agreed, and tracked at #25.

**Comment by ellisonbg** [comment]
Yeah, I saw some performance problems today opening some medium sized notebooks...
