### ISSUE TITLE
Add run selection from .py file in interactive window.

### ISSUE THREAD

**Issue by petrhrobar** [jupyterlab/jupyterlab#9583]
Hi,

I really like jupyter lab as a IDE, however it is not still there just yet. Therefore, in some real projects it is not the best IDE, mostly for debuging.

What I believe would be a really appreciated feature, taking inspiration from VS studio code, is to allows for proper work not only with **.ipynb** but with **.py** files as well. As if now we are able to source **.py** files in jupyter lab with no problem, however writting then in jupyter lab is not most efficient (again, mostly for debuging).

What I suggest is to allow to work with **.py** files just like in VS code. Let's say I am writting some classes as a proper python file and I want to source in interactive window. here I would have to be 'by hand' moving and copying code from one file to notebook.

I think adding option (in an exemple bellow) to ***Source selection in an interactive notebook*** that would just copy and paste my selection from **.py** file into **.ipynb** file would be really nice feature and this would move jupyter lab a bit closer to being a proper and loved IDE.

<img width="1680" alt="Screenshot 2021-01-09 at 12 46 56" src="https://user-images.githubusercontent.com/47755107/104090881-e7e50b00-5279-11eb-99c7-8077d8769b60.png">

**Comment by jsh9** [comment]
_Disclaimer: I'm not a Jupyter Lab developer or in any way affiliated with Jupyter._

It seems like you'd be much better off using Spyder (https://github.com/spyder-ide/spyder) instead of Jupyter Lab.  Spyder is a full-fledged Python IDE that does all you described in your post.  If you have an anaconda installation, you should already have Spyder installed.

This said, I do hope that Jupyter Lab supports executing just `.py` files instead of notebooks.  But from the number of open issues (1,800+) in this repo, I'm somewhat pessimistic...

**Comment by petrhrobar** [comment]
As the matter of fact, it has already been implemented :D.

The solution is called `jupytext` and can e found [HERE.](https://github.com/mwouts/jupytext)

**Comment by krassowski** [comment]
Would the "Create Console for Editor" feature be of any help for you? It allows to execute selections with <kbd>Shift</kbd> + <kbd>Enter</kbd>:

![c](https://user-images.githubusercontent.com/5832902/124389090-8c9e4d80-dcdd-11eb-9909-440b08814a9d.gif)
