### ISSUE TITLE
Plugin transform time out

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#9587]
## Description

There are two ignore warning of failed plugin transform due to timeout in JLab 3 (at least):
- @jupyterlab/shortcuts-extension
- @jupyterlab/docmanager-extension

Note: I wonder if this is related to https://github.com/jupyterlab/jupyterlab/issues/9228 (I did not check if the same error occurs in JLab2)

## Reproduce

1. Launch JupyterLab
2. Open the web console

## Expected behavior

No warning

## Context

- Operating System and version: WSL on Windows 10
- Browser and version: Firefox 84.0.2
- JupyterLab version: 3.0.3

<details><summary>Browser Output</summary>
<pre>
Ignored setting registry preload errors. 
(1) […]
​
0: {…}
​​
dataPath: ""
​​
keyword: "timeout"
​​
message: "Transforming @jupyterlab/shortcuts-extension:shortcuts timed out."
​​
schemaPath: ""
​​
<prototype>: Object { … }
​
length: 1
​
<prototype>: Array []
jlab_core.a6bd38f47ff66b08e9e2.js:2:932874
Ignored setting registry preload errors. 
(1) […]
​
0: {…}
​​
dataPath: ""
​​
keyword: "timeout"
​​
message: "Transforming @jupyterlab/docmanager-extension:plugin timed out."
​​
schemaPath: ""
​​
<prototype>: Object { … }
​
length: 1
</pre>
</details>

**Comment by jasongrout** [comment]
Digging into this, I see this in the debugger when we get to the shortcuts settings transform:

![Screen Shot 2021-01-14 at 7 49 09 AM](https://user-images.githubusercontent.com/192614/104614503-2b09fa00-563d-11eb-951f-de96a23d67de.png)

Notice that the elapsed time is basically calculated by taking the difference between when the function default argument was calculated and the very first line of the function was run. When I log `elapsed`, I see numbers like [1003, 1826, 1062, 1004, 1911, 1886, 1916, 1058, 1676, 1842, 1793, 1789].

* We don't really have control over when the js engine generates the default values for function parameters, and it seems we are making a pretty big assumption about that. The engine could be doing something like evaluating the default function parameters all at once way before the functions are called or something. 
* We could bump the timeout value, but that seems pretty fragile, and the result (not transforming the setting) seems pretty drastic? Besides, how can we continue on if the setting is not transformed?

CC @afshin

**Comment by jasongrout** [comment]
I only see this timeout on a preload: https://github.com/jupyterlab/jupyterlab/blob/d848b6856c9c55ef0e47b6e78f70d6bb56145e4b/packages/settingregistry/src/settingregistry.ts#L538-L550

Here's another hypothesis: That code creates a bunch of promises to load all the settings, and presumably that `start` default argument is timing when all the promises are created together. Then settings are loaded one by one. By the time we get to the docmanager and shortcuts, it's been a second or two to load all of the promises, so we see a timeout. So in the preload phase, we are seeing the timeout measuring the wall clock for loading *all* of the settings, while usually the timeout is just measuring loading a single setting.

It does seem like the preload is purely a caching optimization - not having something load in the preload phase is no big deal? If so, we probably ought to do a `console.debug` rather than a `console.warn`?

If the preload is important, then we should probably either set the timing individually for each one (perhaps the promise could be wrapped in a function, so it is called only when the promise function is invoked), or bump the timeout in the case where we are loading a bunch of settings together.

@afshin, what are your thoughts?

**Comment by afshin** [comment]
@jasongrout,
This should likely be a `console.debug`, yes. I forgot that was a thing. It is not an error that the preloaded version is not transformed yet. It has been bugging me as well.

**Comment by jasongrout** [comment]
On the other hand - perhaps we don't need to display anything at all? Assuming this preload step is just populating a cache, a computer doesn't usually warn about cache misses, especially if it is designed to easily recover from cache misses.

**Comment by afshin** [comment]
I don't have any objection to that. It just seemed like an anti-pattern to just have the comment saying the errors are ignored and doing it silently. But I don't like the noise it creates in the console and it costs real estate and cognitive load to show it. I'm 👍  on removing it.

**Comment by fcollonval** [comment]
Thanks @jasongrout to dig this one up and happy to hear it has no consequences.
