### ISSUE TITLE
Trim large notebook outputs for better performance

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#9593]
### Problem

When many outputs are created in separated divs, the rendering of the notebook page becomes slow.

### Proposed Solution

In case of many output (larger than a predefined threshold), only render the first and last outputs.

### Additional context

https://github.com/jupyterlab/jupyterlab/issues/9279
https://github.com/jupyterlab/benchmarks/issues/49

**Comment by echarles** [comment]
Work is done in https://github.com/jupyterlab/jupyterlab/pull/9594

**Comment by isabela-pf** [comment]
I'm following up based on the discussion in #9594 since that has been merged.

I haven't had time to figure out ideas for all the recommendations, but I have two proposals for ways the message could be styled to help it stand out. I’ll be using using  `info` colors because I think that makes most sense for this type of message, though as far as I know we aren't currently using these colors anywhere else in JupyterLab. 

First, could we have a colored background on the output like we already do for certain feedback? This follows existing output styling for error and warning messages. I don't personally like the way it looks, but it is what we are already doing if we want to be consistent or make a change quickly (since the code already exists elsewhere in a different color. It uses the lightest `info` color `--jp-info-color3`. 

On top of that, using color alone as an indicator for what type of message is being shown does not sound like good accessibility practice to me (in this output or others). There is a chance it is okay, however, since the message is still communicating in full; I just don't think it's the best we could be doing.

### Option 1

<img width="870" alt="0-1" src="https://user-images.githubusercontent.com/50221806/105430392-36928d80-5c08-11eb-9e81-f264b3d52d11.png">

The second option is inconsistent with other output messages in JupyterLab: add an icon to the front of the message. I'm proposing the Material [`info` icon](https://material.io/resources/icons/?search=info&icon=info&style=round) in JLab's `--jp-info-color1`. I think this looks simpler and better meets accessibility principles of communicating information with more than one indicator (color and icon instead of only color).

### Option 2

<img width="870" alt="0-3" src="https://user-images.githubusercontent.com/50221806/105430400-3befd800-5c08-11eb-99bd-83c59610c9d8.png">

If this option is liked, I think it would be worth considering changing other output messages to match (though that would be another issue).


I have a few other thoughts based on what I read on the PR. 
1. It’s good users won’t have to rerun a cell to view the whole output. How is the output expanded right now? Some areas seemed to say it needed to be rerun, while some just said to click on the output.
2. I also agree this might be best to not have as the default setting for a notebook, though I could probably be convinced. I understand this is for performance, but it seems wrong to default to hiding people’s work in a space that is made for exploring work.

Great work as always, @echarles! Thanks for asking me for feedback (and sorry I took so long to reply)!

**Comment by echarles** [comment]
Thx @isabela-pf I am linking here to https://github.com/jupyterlab/jupyterlab/issues/9652 which is the place where we collect feedbacks on user interactions.

**Comment by fcollonval** [comment]
Closing as the trim is in place and feedback should be reported in #9652
