### ISSUE TITLE
How to conceal Property Inspector?

### ISSUE THREAD

**Issue by ctwangtz** [jupyterlab/jupyterlab#9627]
How to conceal sidebar?

**Comment by ctwangtz** [comment]
Also, this useless function occupies too much space !!

**Comment by jasongrout** [comment]
> Also, this useless function occupies too much space !!

First, this comment comes across to me as rude and inconsiderate. I almost ignored this question because of the tone of this comment. Please be [more respectful](https://jupyter.org/conduct/).

You can move the property inspector to the left side by clicking on the icon. You can also disable it entirely by disabling the plugin providing it: `jupyter labextension disable @jupyterlab/application-extension:property-inspector`
