### ISSUE TITLE
How to preview .md and .adoc file in Jupyter Lab 3.0.4?

### ISSUE THREAD

**Issue by ChineseYjh** [jupyterlab/jupyterlab#9635]
Sorry~I cannot find the way to preview MD file, which can be reached in old version by right clicking and selecting "preview Markdown". Do I need to download some pluggin?

BTW, how to preview .adoc file in Jupyter Lab?

Thank you~

**Comment by jtpio** [comment]
Thanks @ChineseYjh.

The Markdown preview feature should still be available in JupyterLab 3.0, and can be used as follows:

https://user-images.githubusercontent.com/591645/104939614-eec5f900-59b0-11eb-8df5-e2b6c31c0af3.mp4

**Comment by jasongrout** [comment]
> BTW, how to preview .adoc file in Jupyter Lab?

I don't know what .adoc files are (and I don't think JLab does either). Someone would have to write a plugin that understands and displays those files to be able to preview them.

**Comment by ChineseYjh** [comment]
Thanks @jtpio 
In old version of JupyterLab I can preview markdown file in the way that your video shows.

But I **cannot find the option of "Show Markdown Preview"** when right-clicking in my current JupyterLab of **version 3.0.4**...

What possible reason would cause this problem?

**Comment by ChineseYjh** [comment]
Thanks @jasongrout 

.adoc file means AsciiDoc file, a language similar to Markdown.

One possible way to preview .adoc file in JupyterLab is to convert AsciiDoc file to Markdown file via some tools. But now I cannot even preview MD file in my JupyterLab, which is really puzzling...

**Comment by jasongrout** [comment]
I just checked on a clean install of jlab 3.0.5, and was able to get the preview of a markdown file. You can try to narrow down the problem using our guide at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html

**Comment by jamesmyatt** [comment]
I've just had this problem. Turns out that there are 2 options:

* You can right-click on the body of the document:
https://www.youtube.com/watch?v=eQsRlqK-z1c

* Or right-click on the file in the browser and select "Open With ..." / "Markdown Preview":
https://deppen8.github.io/posts/2018/09/jupyterlab-favorites/#markdown-previews

@jasongrout , I don't find any of these options very intuitive. The "Open With ..." option is not easy to find. There's no option in the main file browser context menu or the tab context menu and there's no option in the command palette, which were the first 3 places I looked before turning to Google.

**Comment by ChineseYjh** [comment]
Thank you~The 2nd option works in my JLab! @jamesmyatt
