### ISSUE TITLE
Migrating Code Snippets Extension to 3.0

### ISSUE THREAD

**Issue by kpinnipa** [jupyterlab/jupyterlab#9666]
## Description

We are currently working on updating the jupyterlab-code-snippets extension to be compatible with JupyterLab 3.0. We installed the dependencies and executed the update script as specified in the Migration to 3.0 readthedocs. However, we soon ran into an error wherein only part of the jupyterlab window was actually displayed upon running jupyter lab --watch. 

Image for reference:
<img width="1440" alt="® localhost8888lab" src="https://user-images.githubusercontent.com/49247883/105542399-2339fd80-5cae-11eb-8467-5775d8a7aea1.png">

We were informed it may have been an issue regarding previous dependencies that are no longer compatible with jupyterlab 3.0, so we removed it but unfortunately the problem persisted (specifically we removed the tabmanager extension from our list of dependencies).

The main source of the problem is that p-Widget and lm-Widget css classes applied before jp-LabShell class (which are supposed to be applied after) in jupyterlab as shown in the below picture:
<img width="1439" alt="Screen Shot 2021-01-22 at 12 12 39 PM" src="https://user-images.githubusercontent.com/49247883/105542172-c76f7480-5cad-11eb-95b1-79c26770f91f.png">

When the widget.css code is unchecked and the screen is resized, jupyterlab displays normally:
<img width="1440" alt="Screen Shot 2021-01-22 at 12 13 04 PM" src="https://user-images.githubusercontent.com/49247883/105542543-4c5a8e00-5cae-11eb-98a3-a5f5b0c3cd76.png">

We are unsure about how to go about fixing this ordering so if anyone has any advice we would appreciate the help!

## Reproduce

1. Navigate to code snippet extension main folder (files in [PR](https://github.com/jupytercalpoly/jupyterlab-code-snippets/pull/155)).
2. Run jupyter lab --watch on command line.
3. JupyterLab window opens in browser.

## Expected behavior

JupyterLab should display normally (fill screen) and widget.css styling should be applied after base.css styling.

## Context

- Operating System: iOS
- Browsers: Google Chrome, Safari
- JupyterLab version: 3.0

**Comment by jasongrout** [comment]
> Navigate to code snippet extension main folder.

Where is this repo?

**Comment by kpinnipa** [comment]
This is the link to the repo: https://github.com/jupytercalpoly/jupyterlab-code-snippets

**Comment by jasongrout** [comment]
Are we talking about the master branch, or is there a PR?

**Comment by jasongrout** [comment]
For more context - I've seen this when there was a dependency issue where the bad dependency caused its own copy of the jlab css to be loaded after all of the base jlab css was loaded. It would be good to look at your code.

**Comment by kpinnipa** [comment]
That makes sense, the previous link was to the master branch. Here is the link to the new PR that has the changes made after starting the update process which has the display issue: https://github.com/jupytercalpoly/jupyterlab-code-snippets/pull/155

**Comment by jasongrout** [comment]
I checked out the repo and built it, and indeed saw the same issue you saw. As you can see in the css view, that same lumino css is being applied like 3 times. So that points to somewhere css is being duplicated.

I looked in your extension's labextension folder and searched for `p-mod-hidden`, and sure enough found several references to it in vendors-node_modules_css-loader_dist_cjs_js_node_modules_jupyterlab_celltags_style_base_css-n-a58a7d.4d96a1354ad31ff1ae24 (which was generated doing a `jlpm run build` in your extension's repo). So that means that somewhere someone is getting several extra copies of the jlab css and putting it on the page.

So then it was just poking around in that file and figuring out who was importing something from jlab. That led to these lines: https://github.com/jupytercalpoly/jupyterlab-code-snippets/blob/270aab7d3cd3ce78fa4ab120307dd318554a8af3/style/base.css#L378 and https://github.com/jupytercalpoly/jupyterlab-code-snippets/blob/270aab7d3cd3ce78fa4ab120307dd318554a8af3/style/base.css#L499

Those lines are importing part of jlab, and dragging in lots of copies of jlab css in with it, and causing the issue. Delete those lines and things should be fine (the css imported in those lines is already on the page in JupyterLab).

**Comment by jahn96** [comment]
That did fix the issue! Thank you so much!

**Comment by jasongrout** [comment]
Great! I hope that elaborating on the debugging process helps you and others that see these issues.
