### ISSUE TITLE
How can i show an input box when debugging using pdb?

### ISSUE THREAD

**Issue by sarrbranka** [jupyterlab/jupyterlab#9691]
When i try to debug with `from IPython.core.debugger import Pdb; Pdb().set_trace()` or `import ipdb; ipdb.set_trace()`,  jupyter doesn't show an input box for debugging. Even if I restart kernel and run the code again, it doesn't show the input box.  Here is the cell output.
![Screenshot from 2021-01-28 23-47-08](https://user-images.githubusercontent.com/76247476/106155562-29573f00-61c4-11eb-9ce9-09187dec313b.png)
  
I was expecting like this.
![https___qiita-image-store s3 amazonaws com_0_10290_3c195522-a68b-5610-c070-ca60b63afcc3](https://user-images.githubusercontent.com/76247476/106156312-b601fd00-61c4-11eb-809d-b99c5234b4c8.png)

**Comment by jasongrout** [comment]
For those reproducing this:

```python
def my_sum(initnum, step, n):
    x = initnum
    from IPython.core.debugger import Pdb; Pdb().set_trace()
    for i in range(n):
        x = x + step
    return x
my_sum(10, 2, 3)
```

**Comment by jasongrout** [comment]
For reference, this works in classic notebook for me.

**Comment by jasongrout** [comment]
This seems to work in JLab 3.0.6, macOS Catalina, Firefox 85 for me.

![pdb](https://user-images.githubusercontent.com/192614/106237674-205e7180-61b4-11eb-9f21-c474d2f6975a.gif)


It seemed you ignored or deleted the issue template that requested information to reproduce the issue, like jlab version, etc. Please fill out the [bug report issue template](https://raw.githubusercontent.com/jupyterlab/jupyterlab/master/.github/ISSUE_TEMPLATE/bug_report.md) with the information it requests about your version of JupyterLab, browser, OS, etc.

Also, I would suggest going through the troubleshooting/diagnosis guide in the documentation at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to narrow down the problem.

**Comment by sarrbranka** [comment]
> For those reproducing this:
> 
> ```python
> def my_sum(initnum, step, n):
>     x = initnum
>     from IPython.core.debugger import Pdb; Pdb().set_trace()
>     for i in range(n):
>         x = x + step
>     return x
> my_sum(10, 2, 3)
> ```

When i try this on jupyter lab, it worked! but when i store the code in a file and ran `!python pdb_test.py` , it didn't show an input box.
![Screenshot from 2021-01-29 15-22-26](https://user-images.githubusercontent.com/76247476/106239457-fce40700-6245-11eb-9213-e30a135e9872.png)

but running py file with the code :/
![Screenshot from 2021-01-29 15-25-25](https://user-images.githubusercontent.com/76247476/106239658-52b8af00-6246-11eb-9dfa-e13092004f51.png)

pdb_test.py
![Screenshot from 2021-01-29 15-27-25](https://user-images.githubusercontent.com/76247476/106239832-99a6a480-6246-11eb-91f9-5db8307b2c19.png)

**Comment by sarrbranka** [comment]
Here is my environment
```

 conda list ipython
# packages in environment at /home/zzz/anaconda3:
#
# Name                    Version                   Build  Channel
ipython                   6.1.0            py36hc72a948_1  
ipython_genutils          0.2.0            py36hb52b0d5_0  

```

```
jupyter-lab --version
3.0.5
```
ubuntu 18.04

**Comment by jasongrout** [comment]
For reference, I get what you get when the code is in an external file and executed with `!python` in both JupyterLab and the classic notebook. So at least we are parity for the classic notebook here.

The problem is a more general problem with stdin getting lost somewhere. For example, this also has issues in that external file: `print(input('hi'))` (but works fine inline in a cell).

A couple of thoughts:

1. It's a bit tricky, since you are asking the kernel to run a subprocess with `!python` - the kernel needs to hook up the stdin appropriately.
2. As such, this seems like it may be more a kernel issue than a JupyterLab issue. The kernel needs to send a stdin message to the frontend for jlab to put that box for input there. I checked, and in this case, the kernel is *not* sending a stdin message to the frontend, so JupyterLab itself is behaving correctly.

I think the issue should be opened in the IPython kernel: https://github.com/ipython/ipykernel

**Comment by sarrbranka** [comment]
ok Thanks Jason! i opend a new issue in the IPython kernel.

**Comment by telamonian** [comment]
@sarrbranka If your `pdb_test.py` file is in the same dir as your notebook, if you just do

```python
import pdb_test
```

instead of running the file directly with the `!` bash magic, then you'll get a debugger input box as expected:

![image](https://user-images.githubusercontent.com/2263641/106242271-67a92a00-61d5-11eb-9880-ca9d73e0888a.png)

A pattern I use all the time for debugging is to also enable autoreload of python modules, like

```python
%load_ext autoreload
%autoreload 2

import pdb_test
```

That way your notebook will pick up any changes you make to `pdb_test.py` without having to restart your kernel

**Comment by sarrbranka** [comment]
@telamonian It worked! Would it work if the py file has some arguments?
Actually I want to run this code
```
!python run_training.py \
--data-dir=/home/zzz/Downloads/3d/gan/ \
--total-kimg=5 \
--metrics=None \
--dataset-train=/home/zzz/Downloads/3d/gan/tfds \
--dataset-eval=/home/zzz/Downloads/3d/gan/eval \
--config=config-ada-sv-flat \
--resume-pkl=network-final.pkl \
--resume-pkl-dir=/home/zzz/Downloads/3d/gan/few-shot-gan/results/00036-stylegan2-tfds-tfds-config-ada-sv-flat-aug 
```

Would it work if i change the bash magic after moving run_training.py to same dir as notebook?
```
import run_training.py \
--data-dir=/home/zzz/Downloads/3d/gan/ \
--total-kimg=5 \
--metrics=None \
--dataset-train=/home/zzz/Downloads/3d/gan/tfds \
--dataset-eval=/home/zzz/Downloads/3d/gan/eval \
--config=config-ada-sv-flat \
--resume-pkl=network-final.pkl \
--resume-pkl-dir=/home/zzz/Downloads/3d/gan/few-shot-gan/results/00036-stylegan2-tfds-tfds-config-ada-sv-flat-aug
```
