### ISSUE TITLE
Add dialog option to select whether or not to close modals by clicking outside of them

### ISSUE THREAD

**Issue by DianeHu** [jupyterlab/jupyterlab#9884]
### Problem

In #3784 someone asked whether we could add an option to close dialogues by clicking outside of them. It was subsequently enabled across the board. This shouldn't be the only option--there should have been a parameter exposed to indicate whether this behavior is desired. When we pop up dialogues sometimes we require user input, and having this behavior always enabled means the user is able to circumvent logic they shouldn't be able to.

### Proposed Solution

Add an option to the showDialog function to make this behavior optional.

**Comment by jasongrout** [comment]
IIRC, the problem is deeper than clicking outside the dialog - pressing escape *also* exits any dialog (IIRC, when reviewing #3784, I realized it was just making the "escape" key handling more consistent with clicking outside the dialog - it wasn't adding any new behavior that wasn't accessible before).

I think the real feature request here is to have a way to disable both the escape key and click-outside-dialog behaviors.

https://github.com/jupyterlab/jupyterlab/blob/9cdb1fac5dd6d2e095fd5cf8fcac9e36da60faf8/packages/apputils/src/dialog.tsx#L281-L286
https://github.com/jupyterlab/jupyterlab/blob/9cdb1fac5dd6d2e095fd5cf8fcac9e36da60faf8/packages/apputils/src/dialog.tsx#L303-L307

For example, we already have a `hasClose` option that determines whether a close button is added that effects the same result. perhaps the escape and click handler can reference that attribute to determine whether they work as well?
https://github.com/jupyterlab/jupyterlab/blob/9cdb1fac5dd6d2e095fd5cf8fcac9e36da60faf8/packages/apputils/src/dialog.tsx#L494-L497

**Comment by jasongrout** [comment]
Here's a suggestion: save the hasClose option in the constructor to `this._hasClose`, like we save the host option, etc.:
https://github.com/jupyterlab/jupyterlab/blob/9cdb1fac5dd6d2e095fd5cf8fcac9e36da60faf8/packages/apputils/src/dialog.tsx#L92-L97
Then make the two behaviors noted above (click outside box or escape keydown) conditional on the `this._hasClose` value.

**Comment by jasongrout** [comment]
Setting as a good first issue - @DianeHu - would you like to work on a pull request implementing this?

**Comment by DianeHu** [comment]
@jasongrout sounds good, I can do that! I probably won't have time to get around to this until next week or so, but will open that PR. Thanks for the recommendations, this makes sense!

**Comment by DianeHu** [comment]
@jasongrout apologies for the delay--working on this now. For testing I wanted to run jupyterlab in dev mode and install an extension with a test popup on startup to show that the new behavior is as expected, but I can't seem to find in the docs how to run jupyterlab in dev mode with my changes in the jupyterlab repo, as well as install my own extensions. Do you have any advice?

Here are the steps I've taken, according to https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#general-guidelines-for-contributing and https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html#extension-tutorial:

1. Modify local version of jupyterlab repo
2. Create a cookiecutter extension that just shows a basic example dialog on app startup
3. In the directory of the extension, run 
```
pip install -ve .
jupyter labextension develop --overwrite .
jlpm run build
```

4. In the jupyterlab directory, run 
```
pip install -e .
jlpm install
jlpm run build  # Build the dev mode assets (optional)
jlpm run build:core  # Build the core mode assets (optional)
jupyter lab build  # Build the app dir assets (optional)
```
5.  Run jupyterlab in the jupyterlab directory with ```jupyter lab --dev-mode```. If I run with dev mode, then the extension isn't installed. If I run without dev mode, then the extension is installed, but my jupyterlab changes inside apputils don't show (console logs don't show up, etc.).

Is this not the right way to test extensions with jupyterlab changes--should I just install a modified apputils, disable the original one, and test without dev mode instead?

**Comment by DianeHu** [comment]
Nvm--for future reference, #9896 mentions that you can run both ```--dev-mode``` and ```--extensions-in-dev-mode```, which solved my problem
