### ISSUE TITLE
Comment about a cell (not inline code comments # """)

### ISSUE THREAD

**Issue by layne-sadler** [jupyterlab/jupyterlab#9885]
### Problem
When reviewing a notebook, either in a collaborative or solo setting, I want to be able to flag something to be revisited. For example "get input from @Jamie as she owns this endpoint" or "optimize this section w generators tomorrow." In contrast,  when I write inline code comments, it's more about how the code works. It's possible to *comment* in a markdown cell, but it's hidden so it does not achieve the desired effect.

### Proposed Solution
* Right click > Add comment. 
* A right pane approach might be good so that you could list all comments.
* Metadata about comment like time it was made.
* Toggle show/ hide all comments in DOM.
* Should comment only be allowed in input cell?

![image](https://user-images.githubusercontent.com/76759666/109583182-7c772700-7acd-11eb-915a-5c95d27a1b11.png)
![image](https://user-images.githubusercontent.com/76759666/109583226-8e58ca00-7acd-11eb-83ff-905c27c8002b.png)
![image](https://user-images.githubusercontent.com/76759666/109583243-97499b80-7acd-11eb-8874-820b7e68c3be.png)
^ In google docs.

### Additional context
* This item ranked 10th most important out of 33 items.
![image](https://user-images.githubusercontent.com/76759666/109583006-2efaba00-7acd-11eb-8ea5-701ae5e72173.png)

**Comment by cameron-toy** [comment]
Hi @layne-sadler, I'm a [Cal Poly Jupyter intern](https://github.com/jupytercalpoly) and my team and I have been working on an extension that will address this issue (here: https://github.com/jupytercalpoly/jupyterlab-comments)

The extension will support comments on text selections in notebooks as well as markdown and code files. There's a pre-alpha version running on a binder in the repo that has support for comments in notebooks if you want to test it out. Note: currently adding a text selection comment is done by clicking the red button that appears next to cells with text selected.

We don't have an official release yet but we hope to get one out in the next four weeks.

**Comment by aiqc** [comment]
@cameron-toy Thanks for reaching out. Although I created a few issues just to give feedback, I wanted to reply and let you know that it looks and feels fantastic so far!

**Comment by jasongrout** [comment]
From our JLab dev meeting this morning:
- @ellisonbg is going to reach out to touch base with the authors of  https://github.com/jupytercalpoly/jupyterlab-comments about the current status.
- @williamstein: having the comments stored in the notebook format would be nice so that other frontends could also edit and display these comments.
- @ellisonbg: this system tries to be generic about commenting on any file, but for notebooks, it does make sense to store the comments in the file.
- @blois: often commenters do not have permission to edit the file you are commenting on, so it may not make sense to always store the comment in the file. For Drive-based notebooks Colab uses https://developers.google.com/drive/api/v3/manage-comments

**Comment by dmonad** [comment]
In Yjs you can use the ["relative position"](https://docs.yjs.dev/api/relative-positions) concept to annotate the document. Since every character in Yjs can be uniquely addressed (using lamport timestamps) we can refer to those characters using Relative Positions. They are already being used to render remote user selections. 

The advantage of relative positions above other approaches is that they ensure that all users render the cursors at the same position. Since we use the Lamport Timestamps to refer to positions, positions are automatically updated when local or remote changes are performed. I.e. Assume we have a comment from index 1 to index 2 in the document `A{comment-start}B{comment-end}C`. When a remote change (e.g. insert X at position 1) comes in, we need to update the range of the comment to `AX{comment-start}B{comment-end}C`. An alternative approach is to use index-transformations - but they do not guarantee that everyone renders the comments at the same location.

As @blois said, you usually want to store that in a different data structure so we can handle permissions separately. Relative positions are just JSON objects and can be stored in a Yjs document (e.g. in a shared-model implementation for comments) or anywhere else.

**Comment by aiqc** [comment]
@cameron-toy how did your comments extension project turn out? did you ever discuss merging this feature in?

**Comment by aiqc** [comment]
Closing in favor of: https://github.com/jupyterlab/jupyterlab/issues/12032
