### ISSUE TITLE
CSS behaviour with prebuilt extensions

### ISSUE THREAD

**Issue by raulotaolea** [jupyterlab/jupyterlab#9948]
This issue is about how to configure prebuilt extensions that depend on each other, and how css work in this context.

### Description
We are creating a set of extensions to customize Jupyterlab v3 adding our own services.

Our directory tree is something like this:
```
/packages
  /package-a
  /package-a-extension
  /package-b
  /package-b-extension
  /package-c-extension
```
The rol of the packages and extensions are the following:
 - `package-a`:
   - exports token `serviceA`.
   - exports several functions/classes.
   - exports css in `/style/index.css`
   - the `package.json` is:
```json
      ...
      "dependencies": {},
      "jupyterlab": {
         "outputDir": "package-a/labextension"
      }
      ...
```
 - `package-a-extension`:
   - imports token `serviceA` from `package-a`.
   - creates a plugin providing `serviceA`. 
   - the `jupyterlab` section of `package.json` is as follows:
```json
      ...
      "dependencies": {
         "package-a": "^0.1.0"
      },
      "jupyterlab": {
         "extension": true,
         "outputDir": "package-a-extension/labextension",
         "sharedPackages": {
            "package-a": {
               "singleton": true,
               "bundled": true
            }
         }
      }
      ...
```
 - `package-b`:
   - exports token `serviceB`.
   - exports several functions/classes.
   - exports css in `/style/index.css`.
   - imports functions/classes from `package-a`.
   - the `jupyterlab` section of `package.json` is:
```json
      ...
      "dependencies": {
         "package-a": "^0.1.0"
      },
      "jupyterlab": {
         "outputDir": "package-b/labextension",
         "sharedPackages": {
            "package-a": {
               "singleton": true,
               "bundled": false
            }
         }
      }
      ...
```
 - `package-b-extension`:
   - imports token `serviceB` from `package-b`.
   - creates a plugin providing `serviceB`. 
   - requires `serviceA` from `package-a-extension`
   - the `jupyterlab` section of `package.json` is as follows:
```json
      ...
      "dependencies": {
         "package-a": "^0.1.0"
      },
      "jupyterlab": {
         "extension": true,
         "outputDir": "package-b-extension/labextension",
         "sharedPackages": {
            "package-a": {
               "singleton": true,
               "bundled": false
            },
            "package-b": {
               "singleton": true,
               "bundled": true
            }
         }
      }
      ...
```
 - `package-c-extension`:
   - creates a plugin exposing `serviceC`. 
   - imports functions/classes from `package-a`.
   - the `jupyterlab` section of `package.json` is as follows:
```json
      ...
      "dependencies": {
         "package-a": "^0.1.0"
      },
      "jupyterlab": {
         "extension": true,
         "outputDir": "package-c-extension/labextension",
         "sharedPackages": {
            "package-a": {
               "singleton": true,
               "bundled": false
            }
         }
      }
      ...
```

Then, we install only the packages that are extensions:
- `package-a-extension`.
- `package-b-extension`.
- `package-c-extension`.

assuming that `package-a` and `package-b` are bundled with `package-a-extension` and `package-b-extension` respectively.

### Problem
What I see is that the logic work correctly but the css doesn't exist. However, if I install the packages `package-a` and `package-b` the css are imported and all work properly.

My doubts are:
- should I install only the extensions, or both packages and extensions.
- If I install both, am I not repeating the bundles?
- should I package the packages to take into account css?

**Comment by jasongrout** [comment]
Thanks for posting this issue.

A typical pattern in JupyterLab is (framing it for your situation):

- `package-a`, `package-b`, and `package-c` are *not* jupyterlab extensions. They are just normal npm packages that are essentially libraries. They are not explicitly installed into JupyterLab (but are bundled/deduplicated with extensions that require them). So the first thing I would do is delete the `jupyterlab` keys in those package.json files - nothing is looking at that key in these packages, since it is only the jlab build process for jlab extensions that looks at that.
- A JupyterLab extension provides plugins ([docs](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html), [dev docs](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html)), so only `package-a-extension`, `package-b-extension`, and `package-c-extension` are JLab extensions - they are the only ones that should have a `jupyterlab` key.
- By default, the direct dependencies of an extension are `bundled: true`, but it doesn't hurt to be explicit about how dependencies are shared. Note that this sharing config applies to any package in the entire dependency tree, not just direct dependencies, so you can configure a sub-sub-sub dependency to be shared if you wish.

**Comment by jasongrout** [comment]
Just to be clear, are your extensions prebuilt extensions or source extensions?

> should I install only the extensions, or both packages and extensions.

Install just the extensions `package-a-extension`, `package-b-extension`, `package-c-extension`

**Comment by jasongrout** [comment]
> should I package the packages to take into account css?

A prebuilt extension will automatically include the css from the extension's package.json `style` key and put it on the page. It is your responsibility to get your dependency's css on the page. There are several ways to do that:

1. your dependency might put its css on the page by itself. Then nothing is needed (though if the dependency is not shared/deduplicated, the css might be on the page multiple times)
2. You might `@import` your dependency's css in your extension's css. Each time you `@import` the dependency css, though, it will make another copy on the page, so if you have two extensions that each `@import` the dependency's css, you'll get two copies of that css on the page.
3. We do something more complicated to try to deduplicate css dependency with our convention of a style.js file. Essentially, this piggy-backs on the js deduplication to deduplicate the css files. I can go into more detail if you like, though it's a bit complicated and technical. Some brief docs are at https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#extension-css

**Comment by jasongrout** [comment]
> If I install both, am I not repeating the bundles?

This depends on if the extensions are source extensions or prebuilt extensions. Source extensions automatically deduplicate with each other and the core jlab if possible (because they are all compiled together into one bundle). Prebuilt extensions may or may not repeat bundles, depending on how the sharing config is set up and works out.

**Comment by raulotaolea** [comment]
Thanks a lot @jasongrout for your explanations. Now it is much clearer. My mistake was to assume that the packages were extensions and therefore handled by Jupyterlab somehow. 

So if I understood it correctly, if I install `package-a-extension` extension, the css defined in `package-a` is not loaded automatically. I have to explicitly import the css from `package-a` and declare it in `style/base.css` of the extension, having also in `style` folder:
- `style/index.css` with `@import url('base.css');`
- `style/index.js` with `import './base.css'`.

In addition, in the package.json in the `package-a-extension` the sections related with css should be:
```json
// this is probably used by webpack
"files": [
    "lib/**/*.{d.ts,eot,gif,html,jpg,js,js.map,json,png,svg,woff2,ttf}",
    "style/**/*.{css,js,eot,gif,html,jpg,json,png,svg,woff2,ttf}"
  ], 

// this indicates to JLab to include it in the page.
"style": "style/index.css",

// Not sure about this ???
"sideEffects": [
    "style/*.css",
    "style/index.js"
],

// this is like style but with more priority (will be used instead of style if included).
"styleModule": "style/index.js",
```

Is that right?

**Comment by jasongrout** [comment]
> So if I understood it correctly, if I install `package-a-extension` extension, the css defined in `package-a` is not loaded automatically.

Correct



> Is that right?

That's one way of doing it.

Comments on your package.json:

> // this is probably used by webpack

`files` is not used by webpack (IIRC). It's used by npm when publishing a package to know what files to include in the package. If you aren't publishing to npm, I think these lines are not needed.



> ```json
> // Btw '.js' should be without the '.'?
> ```

Correct. If that's in our cookiecutter, do you want to contribute a fix?



> ```json
> // this indicates to JLab to include it in the page.
> "style": "style/index.css",
> ```

This is a standard package.json field that many tools recognize, including jlab. It is not jlab-specific, though jlab does use it in the way you say.



> ```json
> // Not sure about this ???
> "sideEffects": [
> ```

This is for indicating to webpack and other bundling tools which things can be hot-reloaded, etc. My guess is that it has no practical effect on you right now.



> ```json
> // this is like style but with more priority (will be used instead of style if included).
> "styleModule": "style/index.js",
> ```

Comment is correct. This is the workaround we have for deduplicating css that I was talking about above, since our css loader does not deduplicate css (anymore).

**Comment by jasongrout** [comment]
> declare it in `style/base.css` of the extension

Our convention in core jlab is:

- An extension's own styling is in `base.css`.
- Any dependency css is `@import`ed in `index.css`, along with `base.css`
- `style/index.js` is basically a copy of `style/index.css` with js syntax (i.e., the css `@import` becomes the js `import`). However, any dependency that has a "style module" gets its `import 'mydependency/index/style.css'` replaced with the corresponding js module `import 'mydependency/style/index.js'`. This is the thing that provides deduplication of the css. However, this does not quite play nice with the prebuilt extension system yet (issue at https://github.com/jupyterlab/jupyterlab/pull/9475), so we don't advertise it widely for prebuilt extensions.

All this to say that your current convention above will lead to duplicating that css on the page (each extension that is importing the dependency css will put another copy on the page. You can deduplicate manually (by just including the dependency css in *one* extension), or you can "deduplicate" by import the dependency css in its own js code (which then deduplicates because the css code itself is deduplicated).

**Comment by raulotaolea** [comment]
Thank you very much @jasongrout for taking the time to explain this in detail. It's a great help.
